### ISSUE TITLE
do not copy default notebook into ~/.beaker

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#100]
this makes it impossible for us to change it later.

**Comment by anglee** [comment]
In general, users should be able to specify a default notebook to use. And if that is not specified, the 'default' default notebook is used. But it is not entirely clear to me what would be the best thing to do when the default default notebook updates. Maybe beaker ask in the UI let user choose, maybe we provide some notebook merge tool?

**Comment by scottdraves** [comment]
in general, the the default default updates then we should leave theirs in place.
maybe there should be a button in the UI to open the default default instead of the default.

the problem is that right now we copy the default default to the default.  that should stop.
maybe we just have to rename the default.

**Comment by scottdraves** [comment]
i thought we had addressed this but the file is still being copied.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/779
