### ISSUE TITLE
Build failure on windows 7

### ISSUE THREAD

**Issue by jaehyeon-kim** [twosigma/beakerx#1010]
Hi

Can you please check what's wrong with the build on Windows 7?

A noticeable message is **ECONFLICT Unable to find suitable version for angular** and below is some more details.

Thanks.

Jaehyeon

---

:dev:core:bowerInstall
bower jquery#2.0.3              cached git://github.com/jquery/jquery.git#2.0.3
bower jquery#2.0.3            validate 2.0.3 against git://github.com/jquery/jquery.git#2.0.3
bower angular-route#1.2.6       cached git://github.com/angular/bower-angular-route.git#1.2.6
bower angular-route#1.2.6     validate 1.2.6 against git://github.com/angular/bower-angular-route.git#1.2.6
bower angular#1.2.28            cached git://github.com/angular/bower-angular.git#1.2.28
bower angular#1.2.28          validate 1.2.28 against git://github.com/angular/bower-angular.git#1.2.28
bower angular-animate#1.2.6     cached git://github.com/angular/bower-angular-animate.git#1.2.6
bower angular-animate#1.2.6   validate 1.2.6 against git://github.com/angular/bower-angular-animate.git#1.2.6
bower angular-mocks#1.2.6       cached git://github.com/angular/bower-angular-mocks.git#1.2.6
bower angular-mocks#1.2.6     validate 1.2.6 against git://github.com/angular/bower-angular-mocks.git#1.2.6
bower d3#3.3.9                  cached git://github.com/mbostock/d3.git#3.3.9
bower d3#3.3.9                validate 3.3.9 against git://github.com/mbostock/d3.git#3.3.9
bower underscore#1.5.2          cached git://github.com/jashkenas/underscore.git#1.5.2
bower underscore#1.5.2        validate 1.5.2 against git://github.com/jashkenas/underscore.git#1.5.2
bower underscore.string#2.3.3   cached git://github.com/epeli/underscore.string.git#2.3.3
bower underscore.string#2.3.3 validate 2.3.3 against git://github.com/epeli/underscore.string.git#2.3.3
bower codemirror#4.7.0          cached git://github.com/marijnh/CodeMirror.git#4.7.0
bower codemirror#4.7.0        validate 4.7.0 against git://github.com/marijnh/CodeMirror.git#4.7.0
bower angular-bootstrap#0.12.0  cached git://github.com/angular-ui/bootstrap-bower.git#0.12.0
bower angular-bootstrap#0.12.0         validate 0.12.0 against git://github.com/angular-ui/bootstrap-bower.git#0.12.0
bower q#0.9.7                            cached git://github.com/kriskowal/q.git#0.9.7
bower q#0.9.7                          validate 0.9.7 against git://github.com/kriskowal/q.git#0.9.7
bower bootstrap#3.1.1                    cached git://github.com/twbs/bootstrap.git#3.1.1
bower bootstrap#3.1.1                  validate 3.1.1 against git://github.com/twbs/bootstrap.git#3.1.1
bower requirejs#2.1.11                   cached git://github.com/jrburke/requirejs-bower.git#2.1.11
bower requirejs#2.1.11                 validate 2.1.11 against git://github.com/jrburke/requirejs-bower.git#2.1.11
bower font-awesome#4.0.3                 cached git://github.com/FortAwesome/Font-Awesome.git#4.0.3
bower font-awesome#4.0.3               validate 4.0.3 against git://github.com/FortAwesome/Font-Awesome.git#4.0.3
bower big.js#~2.5.1                      cached git://github.com/MikeMcl/big.js.git#2.5.2
bower big.js#~2.5.1                    validate 2.5.2 against git://github.com/MikeMcl/big.js.git#~2.5.1
bower angular-datatables#0.2.0           cached git://github.com/l-lin/angular-datatables.git#0.2.0
bower angular-datatables#0.2.0         validate 0.2.0 against git://github.com/l-lin/angular-datatables.git#0.2.0
bower angular#1.2.6                      cached git://github.com/angular/bower-angular.git#1.2.6
bower angular#1.2.6                    validate 1.2.6 against git://github.com/angular/bower-angular.git#1.2.6
bower datatables#>=1.9.4                 cached git://github.com/DataTables/DataTables.git#1.10.4
bower datatables#>=1.9.4               validate 1.10.4 against git://github.com/DataTables/DataTables.git#>=1.9.4
:dev:core:bowerInstall FAILED
:build FAILED

BUILD FAILED

**Comment by scottdraves** [comment]
thanks for the report, we'll look into it.

**Comment by scottdraves** [comment]
actually all of our builds are broken like this.
