### ISSUE TITLE
docker image failing to permit connection, root issue unclear

### ISSUE THREAD

**Issue by dsjoerg** [twosigma/beakerx#1011]
When starting via docker on OS X 10.9.5, cannot connect to it via the provided URL nor `https://localhost:8800/` nor `https://127.0.0.1/8800/`.

When I attempt to connect to any of those URLs my browser simply says "This webpage is not available".  Tried via both Chrome and Safari.

Or perhaps I'm doing something wrong?

```
was:beaker david$ docker run -p 8800:8800 -t beakernotebook/beaker
Dec 22, 2014 4:14:06 PM com.twosigma.beaker.shared.module.util.GeneralUtilsImpl readFile
INFO: ERROR reading file /home/beaker/.beaker/v1/config/beaker.pref.json
running nginx: nginx -p /home/beaker/.beaker/v1/nginx5148824486890710235 -c /home/beaker/.beaker/v1/nginx5148824486890710235/conf/nginx.conf
nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to https://3b522d1d2889:8800/
Submit this password: D0LCMJEIiaMKePd
```

**Comment by scottdraves** [comment]
Thanks for the report.  I haven't tried Docker on OSX, so I don't really know, but that looks right to me.  I'll have to try it.  Are you using boot2docker?

**Comment by rseymour** [comment]
I assume if you're using boot2docker you're going to want to type

```
boot2docker ip
```

And use that as the IP to connect to instead of 127.0.0.1.  The other option is to do port forwarding in virtualbox to take the boot2docker ip 8800 and forward it to your machine's 8800.

I feel like connecting to the boot2docker ip is a bit cleaner though.

**Comment by dsjoerg** [comment]
Whoa thanks @rseymour that did it!  I'm in!

I updated my comment on the docker page for those who follow me.
