### ISSUE TITLE
Hierarchy number does not update after a header is deleted

### ISSUE THREAD

**Issue by adgnaw** [twosigma/beakerx#1014]
Say currently I have
1. H1 foo
2. H1 bar
3. H1 abc

And after deleting "H1 bar" the hierarchy display shows
1. H1 foo
3. H1 abc
while I think in general people expect
1. H1 foo
2. H1 abc

**Comment by adgnaw** [comment]
Also, for multi-level headers, The numbering for sub-sections start from 0, which is a bit weired, as we got:

```
2. Section
2.0 subsection
2.0.1 subsubsectino
```

Something starting from 1 is more natural.

**Comment by scottdraves** [comment]
Thanks Da.

I was unable to reproduce lack of renumbering, can you be more specific? perhaps share the notebook and paste the link to it here?  how did you delete it the header?

About the numbering from 0, I agree this is a bug: https://github.com/twosigma/beaker-notebook/issues/629.  We will get to that sooner than 2.0 :)

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/264

**Comment by scottdraves** [comment]
could not reproduce
