### ISSUE TITLE
window title stuck on "New Notebook"

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1062]
even though i have loaded a notebook from a file.

**Comment by buob** [comment]
I'm having a hard time reproducing this -- open recent, open, open python all work for me.

**Comment by scottdraves** [comment]
try opening a tutorial.

**Comment by buob** [comment]
That also works for me, which tutorial are you opening?

**Comment by scottdraves** [comment]
the main tut.  after i load it the window title on the browser tab still says "New notebook" instead of "tutorial.bkr"

![screen shot 2015-01-20 at 1 49 08 pm](https://cloud.githubusercontent.com/assets/963093/5823488/25fcee12-a0ab-11e4-9cfd-2a8f2aa77f3c.png)

**Comment by buob** [comment]
Sorry, window title.  Yup.  :dango:
