### ISSUE TITLE
Beaker Crashes on Mac with JDK6

### ISSUE THREAD

**Issue by sabraham** [twosigma/beakerx#1064]
13-inch, Mid 2010
Software  OS X 10.9.5 (13F34)

java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)

1/17/15 12:37:55.530 PM Beaker[48501]: java.lang.UnsupportedClassVersionError: com/twosigma/beaker/core/Main : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
1/17/15 12:37:55.530 PM Beaker[48501]:  at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
1/17/15 12:37:55.530 PM Beaker[48501]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by scottdraves** [comment]
The problem was JAVA_HOME was set in .bash\* files.  this causes a problem because of https://github.com/twosigma/beaker-notebook/issues/703

the workaround until that's fixed is to comment out the lines with JAVA_HOME in ~/.bash*

**Comment by logannc** [comment]
Is Beaker compiled with JDK 1.7 compatibility? I am getting this issue on Linux with JDK7 as well. (major.minor version 52.0)

**Comment by scottdraves** [comment]
As of 1.3 we are using Java 8, and the Linux version does not include Java it has to be installed separately.  The Linux instructions include the apt-get to install 8.

**Comment by logannc** [comment]
You mean https://github.com/twosigma/beaker-notebook/wiki/Ubuntu-build-and-run?

I will follow these now, but the build hosted at http://beakernotebook.com/getting-started?linux&scroll does not contain instructions (that I saw).

**Comment by logannc** [comment]
You mean https://github.com/twosigma/beaker-notebook/wiki/Ubuntu-build-and-run?

I will follow these now, but the build hosted at http://beakernotebook.com/getting-started?linux&scroll does not contain instructions (that I saw).

EDIT: Oh, weird. I unzipped the package and it apparently placed the `install-dependencies.sh` file in the parent of the unzipped folder. That is,

```
mybuildfolder
    | beaker-notebook.zip
    | install-dependencies.sh
    | beaker-notebook/
        | beaker.command, etc
```

I just `cd`ed into the folder assuming that everything would have been on the same level. It might be more clear if `install-dependencies.sh` was in the beaker folder.

**Comment by scottdraves** [comment]
Thanks for the bug report, I filed it here: https://github.com/twosigma/beaker-notebook/issues/1873

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/2193
