### ISSUE TITLE
Unpredictable behavior in R output

### ISSUE THREAD

**Issue by aolney** [twosigma/beakerx#1067]
R sometimes prints to cell output, sometimes to stdout, and sometimes as a table.

Repro set up:

```
data(mtcars)
m1 <- lm(mpg~cyl, data=mtcars)
```

Followed by `anova(m1)` will create a cell output _table_ where what the user probably expects is the _narrative output_ that goes to stdout when `print(anova(m1))` is used. 

For example `summary(m1)` sends narrative output to cell output.

Conversely `step(m1)` outputs the narrative for the  _model_ to the cell output but sends all of the _narrative step output_ leading to the final model to stdout.

Is there a reason for these various different behaviors?

**It would be really nice if the user could redirect stdout to cell output**

Right now in R I'm using `capture.output`, e.g. `capture.output(anova(m1))`

**Comment by scottdraves** [comment]
Thanks for the feedback.  We use `withVisible` to determine if the result should be shown.

And we are changing stdout to show in the output section instead of the tray: https://github.com/twosigma/beaker-notebook/issues/667 in fact Davide is working on this next.

**Comment by aolney** [comment]
withVisible works fine for `anova()` but not for `step()`.  `capture.output` works for both though with less "pretty" output

**Comment by scottdraves** [comment]
Sorry do you mean that even with showing stdout in the cell output isn't enough?  I am definitely not an R expert and we have only got as far as we have with input through this issue tracker...  so please explain your idea if you think our design would benefit.  where are you expectations coming from in terms of R GUIs?  thanks, -spot

**Comment by aolney** [comment]
Contrast

```
data(mtcars)
m1 <- lm(mpg~cyl, data=mtcars)
withVisible(step(m1))
```

and

```
data(mtcars)
m1 <- lm(mpg~cyl, data=mtcars)
capture.output(step(m1))
```

`withVisible` does not prevent some of the output from going to stdout. `capture.output` seems to force everything into cell output.

Ideally everything should go to cell output by default. There may be cases where the user wants to suppress this, but I imagine that is a minority of cases.
