### ISSUE TITLE
R par() causes later plots to be distorted

### ISSUE THREAD

**Issue by aolney** [twosigma/beakerx#1068]
Execute this in one cell:

```
data(mtcars)
op <- par()
par(mfrow=c(1,2),mar=c(3,3,3,1))
dotchart(mtcars$mpg)
```

Followed by this:

```
par(op)
hist(rnorm(100))
```

And the histogram will be "bisected" -- only the left hand side, corresponding to mfrow = c(1,2), will be drawn. What is interesting about this is that if you go back and rerun the first cell with the par line commented out, it will fix the display of the lower histogram. This suggests to me that the bug is a more general display bug and not something specific to the image in cell output.

**Comment by scottdraves** [comment]
http://sharing.beakernotebook.com/gist/anonymous/68057363dbaf964ed449

i didn't see a bisection with chrome and v1.1.2.  i have seen some issues but i think they were firefox (note that the bug may just repeat itself on the shared page and appear broken to you but working to me.
when i try it on firefox i don't see the text/numeric labels (https://github.com/twosigma/beaker-notebook/issues/987), but bisection sounds different... can you take a screenshot?

**Comment by aolney** [comment]
I stopped using firefox when I noticed the font bug. This is happening in IE 11 on Windows. 

![screenshot from 2015-01-19 22 26 15](https://cloud.githubusercontent.com/assets/4432084/5812205/8e89b34c-a02a-11e4-8791-b75a5491dde3.png)

**Comment by scottdraves** [comment]
Thanks.  Yea, looks broken.
I have never tried IE, we don't officially support it.
If you try Chrome I'll bet it will work...

**Comment by aolney** [comment]
I just tried Chrome 39 (had to install it; this is a virtual machine) and it worked fine. Sorry about that.

I don't recall what the installation directions say, but it might make sense to give strong guidance on using Chrome. My path was Firefox -> IE -> Chrome :)
