### ISSUE TITLE
Use bootstrap.scss with variables instead of overriding boostrap.css

### ISSUE THREAD

**Issue by buob** [twosigma/beakerx#1071]
There are a couple ways one can include bootstrap css:  pre- or post-compilation.  If we include it pre-compilation, we can take advantage of all of [bootstrap's variables](http://getbootstrap.com/customize) in order to use plain old bootstrap elements instead of overriding them post-compilation like we are now.

This would not only get rid of most or all of the following files:
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/styles/dropdowns.scss
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/styles/header.scss
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/styles/modal.scss
First half of https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/styles/ui.scss

... We would also be able to eliminate some of the ambiguity between our custom classes (`beaker-btn`, `insert-cell-indicator`, etc.) and use bootstrap's classes (`btn`, `btn-group`) out of the box with 100% consistency, whereas right now we use `btn btn-primary` some places and `beaker-btn` other places.  After this, we could add new bootstrap components (popovers, button groups, etc.) that have never been added and be confident they will use our variables and be cohesive with the rest of the application.

**Comment by buob** [comment]
There's also now an officially supported sass port of bootstrap which I forgot about, so we wouldn't have to convert them to less.

**Comment by scottdraves** [comment]
after our next release we can consider this.
i am concerned though, where these variables get defined, and what happens when a new version comes out.
