### ISSUE TITLE
Don't automatically close command window on Windows when there's a startup error

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#108]
When you double click 'beaker.command' and there's an error during startup, the window automatically closes. This isn't useful. Can we make the window keep itself open?

**Comment by scottdraves** [comment]
http://www.computerhope.com/issues/ch000738.htm

**Comment by jchendy** [comment]
The pause statement seems like a reasonable option.

**Comment by melmac48** [comment]
will be addressed by launcher
