### ISSUE TITLE
in advanced mode clicking on cell bottom margin does not work

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1096]
in regular mode if you click in a cell outside the actual text editor, in the margin, then it still puts the cursor in the cell and allows you to type.  this doesn't work in advanced mode.

**Comment by buob** [comment]
I'm not able to reproduce this; with code cells I'm able to click on the margins in normal and advanced mode.  I do notice that this effect doesn't work with text cells, is that what you mean?

**Comment by buob** [comment]
Actually when clicking on the bottom margin it doesn't work, is that what you're experiencing as well?

**Comment by scottdraves** [comment]
right, the bottom.
