### ISSUE TITLE
on firefox, language element badges are off

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1097]
The text is too bold and too low.  top image is chrome, bottom is ffox:
![screen shot 2015-01-29 at 4 37 13 pm](https://cloud.githubusercontent.com/assets/963093/5966763/31fe91e4-a7d5-11e4-9e67-211ff84031cd.png)
![screen shot 2015-01-29 at 4 36 55 pm](https://cloud.githubusercontent.com/assets/963093/5966762/31fe70a6-a7d5-11e4-8729-9fbda0e3bb37.png)

**Comment by scottdraves** [comment]
part of this looks like the bold font in general, here's another place they look different:
![screen shot 2015-01-29 at 4 49 01 pm](https://cloud.githubusercontent.com/assets/963093/5966959/d743e6e4-a7d6-11e4-94c0-cfe65455c0c3.png)
![screen shot 2015-01-29 at 4 49 08 pm](https://cloud.githubusercontent.com/assets/963093/5966961/d9efdcf4-a7d6-11e4-9ada-ddea653ecd51.png)

**Comment by buob** [comment]
The bold doesn't look as bad on my machine (retina macbook)

![screen shot 2015-01-30 at 12 16 23 pm](https://cloud.githubusercontent.com/assets/986404/5979940/f86faf3a-a879-11e4-8a58-991773756e0e.png)
![screen shot 2015-01-30 at 12 16 29 pm](https://cloud.githubusercontent.com/assets/986404/5979952/fe4a3218-a879-11e4-9db9-302e313ee75b.png)

The language icons are off even if we take off the font weights though, so I can fix that.

**Comment by buob** [comment]
Non-retina looks rough -- that's where I see similar to your screenshots

**Comment by scottdraves** [comment]
You are right the difference in weight is less in retina though still noticeable.
The arrow is quite different though and that might be a clue.

And yea the biggest problem is the language icons need to be centered.
