### ISSUE TITLE
narrow window breaks menus

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1105]
on chrome if the window is less than about 775 pixels wide the menus stack up
![screen shot 2015-01-30 at 11 53 59 am](https://cloud.githubusercontent.com/assets/963093/5979560/bcd3ce46-a876-11e4-98c3-7f57531aeff9.png)

**Comment by buob** [comment]
Is it possible to table this for now?  This would be much easier once we have bootstrap in pre-compilation, then we could just set a few variables to disable responsive views altogether: http://stackoverflow.com/questions/17935601/how-to-remove-responsive-features-in-twitter-bootstrap-3

**Comment by scottdraves** [comment]
depends on https://github.com/twosigma/beaker-notebook/issues/1071
