### ISSUE TITLE
drag-and-drop on control-panel needs drop-zone

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1116]
add a div that says "Drag a notebook from your desktop and drop it here to open it"

**Comment by buob** [comment]
The entire document is a drop-zone, so I'm not sure if there's a nice way to say that without adding a div that looks like only that one section is a drop-zone? _shrug_

**Comment by scottdraves** [comment]
It doesn't matter if it looks like only one section is the drop-zone, what's important is that users know there is a drop zone.  Exactly where the drop zone is is not so important.  So please add a div, in the same row as the two new notebook buttons, on the right (new empty would move to the middle of the page).
