### ISSUE TITLE
Can't run Julia plugin on Windows

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#114]
It looks like it's trying to run a shell script.

![screen shot 2014-03-31 at 4 35 28 pm](https://cloud.githubusercontent.com/assets/1740497/2572478/05ac38f4-b914-11e3-861e-73c62b3e4f0d.png)

**Comment by scottdraves** [comment]
i wasn't able to install ijulia on windows so i can't really test this but i did update that shell script to work on windows so if someone else gets it working it will have a chance at least.
