### ISSUE TITLE
stdout from node opens tray

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1145]
![screen shot 2015-02-05 at 10 19 26 pm](https://cloud.githubusercontent.com/assets/963093/6074086/4600ab68-ad85-11e4-9384-52f4e28980ad.png)

**Comment by samccone** [comment]
this totally makes sense since console.log simply prints to stdout with a newline at the end.

Would we like special behavior for this?

**Comment by scottdraves** [comment]
it should work like stdout in the other languages, which goes into the cell output area.

**Comment by samccone** [comment]
kk :+1:
