### ISSUE TITLE
Browser "can't connect to the Server" when launching Beaker Notebook

### ISSUE THREAD

**Issue by maroonblazer** [twosigma/beakerx#1148]
I'm new to Python and want to try out Beaker Notebooks so downloaded and installed the app. When I launch it, Safari (Mac OS 10.10.2) launches a blank page with the message "Safari can't connect to the server. Safari can't open the page '127.0.0.1:8801 because Safari can't connect to the server '127.0.0.1'"

I have iPython installed and that runs fine. I've tried searching for others having similar issues but couldn't find anything.
Ideas?
Thanks.

**Comment by scottdraves** [comment]
Thanks for the report.  We fixed a couple of bugs that caused this for some users.  
You can try the workaround here: https://github.com/twosigma/beaker-notebook/issues/982
Or it might have been this: https://github.com/twosigma/beaker-notebook/issues/824

Your best option might be to just try our prerelease of v1.2 which has both of these fixes and many more.  See the last question at the bottom of our FAQ: http://beakernotebook.com/faq

**Comment by maroonblazer** [comment]
Thanks for the quick reply. I installed v1.2 and was able to connect, however the screen is blank. Using Chrome works though.

Thanks again!

**Comment by scottdraves** [comment]
xlnt.
just tried it with safari on 10.10.1 and it was fine.  who knows.
glad you persisted -- and thanks for coming back to close it.
