### ISSUE TITLE
add to scala plugin

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1149]
these libs http://www.scalanlp.org/ or maybe just https://github.com/scalanlp/breeze

**Comment by PabloLeon** [comment]
Is there any way to integrate breeze right now? I just found this for the jupyter notebooks http://jcrudy.github.io/blog/html/2013/12/08/introduction_to_iscala.html using ipython magics to run sbt, but it didnt work.

**Comment by scottdraves** [comment]
If you compile it with sbt with a terminal, then you should be able to put the resulting jar in the classpath with the language manager.

**Comment by PabloLeon** [comment]
Thank you!
