### ISSUE TITLE
Bash and Powershell support [enhancement]

### ISSUE THREAD

**Issue by aolney** [twosigma/beakerx#1157]
It would be excellent if cells could contain bash or powershell for automating OS scripting.

For example (a somewhat spurious example) let's say that I want to do a statistical analysis on the modified times of all files on my computer. 

Using bash, one could execute `find . -type f -printf '%T@ %p\n` and then use auto-translation to pass this to R in the next cell for analysis

**Comment by scottdraves** [comment]
agreed, bash as a language type would be handy.

**Comment by yassinebha** [comment]
Yep, that would be good add

**Comment by jlncrnt** [comment]
Agreed, I'd be glad to be able to run bash commands to plot the resulting files with another language. Most of my analysis scripts are actually unix pipes.
