### ISSUE TITLE
nginx process not killed on Windows

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#116]
I've run Beaker a few times by clicking on 'beaker.command' and killed it by closing the command windows that pop up. When I start again, it reports that all the ports are still used. See the screenshot:

![screen shot 2014-04-01 at 11 23 21 am](https://cloud.githubusercontent.com/assets/1740497/2580805/96fba90a-b9b1-11e3-996d-19c5f9fbd64c.png)

If I try to reconnect to one of the old URLs, I get a 404 from nginx.

**Comment by scottdraves** [comment]
kill it with control-c in the window, not by clicking the x on the window.

**Comment by jchendy** [comment]
That's not going to be an acceptable answer for users. Can we add a hook into the .bat file that kills everything when the window is closed?

**Comment by scottdraves** [comment]
no this has to wait until we have a proper app.

**Comment by scottdraves** [comment]
this is really subsumed by this:
https://github.com/twosigma/beaker-notebook/wiki/Improving-the-install-and-launch-process

**Comment by scottdraves** [comment]
closing because it will be handled by our windows native launcher
