### ISSUE TITLE
comment tokens should switch if the user switches languages

### ISSUE THREAD

**Issue by dmitri-at-twosigma** [twosigma/beakerx#1164]
e.g. if the user has a python cell and switches to javascript the editor should change # to //

**Comment by scottdraves** [comment]
sounds dangerous

**Comment by dmitri-at-twosigma** [comment]
i noticed when a user switched a cell from the default notebook from python to javascript. maybe safe if that's the case.

agreed, probably another warning should be displayed if there is lots of code already though.
