### ISSUE TITLE
add line numbers and stacktraces to JS error output

### ISSUE THREAD

**Issue by dmitri-at-twosigma** [twosigma/beakerx#1165]
users just see a single terse error which is difficult to debug, e.g.:

```
Error
 SyntaxError: Unexpected token ;
```

**Comment by scottdraves** [comment]
this is a problem with our JS plugin, thanks for filing the bug.

**Comment by scottdraves** [comment]
dup of https://github.com/twosigma/beaker-notebook/issues/889
