### ISSUE TITLE
alert the user if nginx fails to start

### ISSUE THREAD

**Issue by dmitri-at-twosigma** [twosigma/beakerx#1169]
for example, if it fails on mac osx, now the user just sees a web browser error of connection refused.

**Comment by scottdraves** [comment]
is it failing for you?  are you running 1.2pre2?

**Comment by dmitri-at-twosigma** [comment]
not for me. i saw another user have it fail because libssl was missing, but we were only able to discover this by looking at console.

**Comment by scottdraves** [comment]
i think console log is appropriate for an internal error.  best fix is to not crash :) 1.2 should have this covered.
