### ISSUE TITLE
initial gradle run invocation might fail if not run as admin on mac osx due to global npm install attempts

### ISSUE THREAD

**Issue by dmitri-at-twosigma** [twosigma/beakerx#1170]
i followed these instructions:
https://github.com/twosigma/beaker-notebook/wiki/Mac-build-and-run

gradle run failed because it tried to install a global npm package. i was able to sudo gradle run and make it install the deps, but it should install as a local dependency or sudo in that part of the bootstraping.

**Comment by scottdraves** [comment]
is there an npm install -g?  i can't find it there are a few npm installs but those should be fine.

**Comment by dmitri-at-twosigma** [comment]
i didn't look into the script or try to repro yet. in the beginning state i had npm installed but not all of the beaker deps.

**Comment by scottdraves** [comment]
i will have to test on my vm that i believe i can reset to factory state.
or maybe i can try uninstall/reinstall of npm.
