### ISSUE TITLE
R on Windows does not use PATH

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1178]
On Windows the R installer does not put it in the PATH, it only sets a registry entry.

By default we should use the registry to find this backend.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1179

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/703

**Comment by k-dahl** [comment]
This fix only appears to work when run via python 2.7, python 3 renamed _winreg to winreg.

**Comment by scottdraves** [comment]
thanks for the bug report.  i explained the situation and workaround here: https://github.com/twosigma/beaker-notebook/issues/1463
