### ISSUE TITLE
Make it obvious that Beaker supports running multiple notebooks

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#1197]
Several users have asked how to open multiple notebooks and wondered what happened to their work after they open a new notebook. This suggests that Beaker's support for multiple notebooks is non-obvious. 

The screenshot below is one suggestion for how to make it more obvious. I imagine there would be a menu item for each open notebook plus one that says something like "new Beaker tab."

![screen shot 2015-02-22 at 6 44 17 pm](https://cloud.githubusercontent.com/assets/1740497/6321227/4c4b5018-bac3-11e4-92ef-36fe67b4f7bf.png)

**Comment by scottdraves** [comment]
agreed we need to make this more discoverable.
i am not sure about this menu though, i think "new beaker tab" under File might be adequate.

**Comment by scottdraves** [comment]
could be as simple as that.  works in ffox and chrome, opens a new tab (for me on linux at least).

**Comment by scottdraves** [comment]
![screen shot 2015-02-23 at 8 48 36 am](https://cloud.githubusercontent.com/assets/963093/6328773/d21a413e-bb38-11e4-8b37-d1f20ea5e77e.png)

**Comment by scottdraves** [comment]
OK that menu item is merged in v1.2 and master.

I think we should consider something like a menu of open notebooks for v1.3 though so I am going to leave this open.

I think I would prefer a menu named "Windows" in our regular menu bar though.  There are some complications to deal with, like editing the same notebook from two different windows.
