### ISSUE TITLE
Can't run R cells (installed with Homebrew)

### ISSUE THREAD

**Issue by gwerbin** [twosigma/beakerx#1207]
Apologies if this turns out not to be a proper "bug report," but I don't seem to have a problem with R on my system and I haven't done anything "weird" in my setup, so it seems like the issue might lie with Beaker itself.

I've installed R with Homebrew, and I've installed Beaker as a Homebrew "cask." I'm on a more or less fresh install of OSX Yosemite (version 10.10.2).

I open Beaker, and create a new R cell. To test it, I enter something simple that the R console can spit back at me, like `1 + 2`, and press "Run". I get the following error instead of output:

```
from dev.off(): eval failed, request status: error code: 127
```

and stderr reports the following:

```
Error in dev.off() : cannot shut down device 1 (the null device)
In addition: Warning messages:
1: In (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  :
  unable to load shared object     '/usr/local/Cellar/r/3.1.2_1/R.framework/Resources/library/grDevices/libs//cairo.so':
  dlopen(/usr/local/Cellar/r/3.1.2_1/R.framework/Resources/library/grDevices/libs//cairo.so, 6): image     not found
2: In (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  :
  failed to load cairo DLL
```

Maybe this is really just a "bug" with the "R Installation" section on the website, but I do have all of the correct packages installed:

```
c("Rserve", "ggplot2", "devtools", "RCurl", "RJSONIO") %in% installed.packages()[, 1]
# [1] TRUE TRUE TRUE TRUE TRUE
```

Am I missing some other (unmentioned) prerequisite? Is it an issue with Homebrew? Or is there a bug in Beaker itself?

Here's my R `sessionInfo` (from RStudio), for completeness:

```
sessionInfo()
# R version 3.1.2 (2014-10-31)
# Platform: x86_64-apple-darwin14.1.0 (64-bit)
# 
# locale:
# [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# loaded via a namespace (and not attached):
# [1] tools_3.1.2
```

**Comment by scottdraves** [comment]
Thanks for the report, Greg.

It looks like your R install is missing the packages needed by Beaker or maybe XQuartz.  Did you take the steps outlined in the section "R Installation" on http://beakernotebook.com/getting-started?

**Comment by gwerbin** [comment]
Yup. Like I said, I have all the correct packages installed, and XQuartz as well:

```
[[ $(brew cask list | grep xquartz) ]] && echo $(which xquartz)
# /opt/X11/bin/xquartz
```

It seems like there's an _additional_ dependency not listed in that section, which might be installed with binary versions of R but not in the compiled version, as obtained from Homebrew.

**Comment by scottdraves** [comment]
Ah sorry I was confused by the "attached base packages" in the session info.

on closer inspection, looks like you need to reinstall XQuartz, as yosemite moved the shared objects.  This is covered in our FAQ: http://beakernotebook.com/faq

**Comment by gwerbin** [comment]
I just reinstalled XQuartz, no luck.

```
brew cask uninstall xquartz
# ==> Running uninstall process for xquartz; your password may be necessary
# ==> Removing launchctl service org.macosforge.xquartz.startx
# ==> /private/tmp/org.macosforge.xquartz.startx: No such file or directory
# Password:
# ==> Quitting application ID org.macosforge.xquartz.X11
# ==> Removing files from pkgutil Bill-of-Materials
# ==> Removing files: ["/opt/X11/"]
brew cask install xquartz
# ==> Downloading https://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.7.dmg
# ######################################################################## 100.0%
# ==> Running installer for xquartz; your password may be necessary.
# ==> Package installers may write to any location; options such as --appdir are ignored.
# ==> installer: Package name is XQuartz 2.7.7
# ==> installer: Installing at base path /
# ==> installer: The install was successful.
# 🍺  xquartz staged at '/opt/homebrew-cask/Caskroom/xquartz/2.7.7' (64M)
open -a beaker
```

Same error. And sure enough there's no `cairo.so` file there:

```
ls /usr/local/Cellar/r/3.1.2_1/R.framework/Resources/library/grDevices/libs//
# grDevices.so
```

Is my R installation missing something, or is Beaker looking in the wrong place for the file?

It's also worth mentioning that this was a _clean_ Yosemite install. That is, I reformatted first, so nothing was moved by the update because there was nothing to move.

**Comment by scottdraves** [comment]
Thanks for your persistence.  Beaker doesn't look for the shared object that's done way downstream by R.  Here's a link to where I had the problem: https://github.com/twosigma/beaker-notebook/issues/792 and found the recommended fix from the R community was to reinstall XQuartz.

We don't recommend users install R and XQuartz with brew and I have never tried that and so I have to wonder if that's the problem.  On the other hand I certainly want Beaker to work with as many configs as possible, and I definitely want to make it work for you and understand what's wrong here.

To find out, I could come up with an R script that does what Beaker does, and you could just run your R on it and see if it has the same problem.  Do you want to try that or do you have another idea?

Also, I am curious what you mean by _I've installed Beaker as a Homebrew "cask."_?  Seems unlikely that would cause a problem like this, but who knows.

**Comment by gwerbin** [comment]
Homebrew casks are '.app' files, whereas the regular 'brew install' command compiles from source.

It turns out that the 'cairo.so' file is _supposed_ to be included in the R installation, so it's an issue with the Homebrew version of R rather than something related to Beaker. I'll look into it further, but I have a feeling you guys are off the hook. Thanks for being so responsive!

**Comment by gwerbin** [comment]
Just as an update, it turns out that there was, in fact, an issue with the Homebrew version of R: https://github.com/Homebrew/homebrew-science/issues/1890
