### ISSUE TITLE
Consider support for Bokeh visualization library

### ISSUE THREAD

**Issue by ghost** [twosigma/beakerx#1210]
http://bokeh.pydata.org/en/latest/

**Comment by scottdraves** [comment]
yes this would be great!

**Comment by ghost** [comment]
Does this help?

https://github.com/bokeh/bokeh-scala

**Comment by scottdraves** [comment]
just firing it up doesn't work because (at least) it redefines _ to the underscore library but beaker has set _ up to include _.string and that gets overwritten.

**Comment by scottdraves** [comment]
@samccone this is the module system conflict i mentioned.
lmk if you want me to show you how to repro.

**Comment by scottdraves** [comment]
Looks like Bokeh has fixed it: http://sharing.beakernotebook.com/gist/anonymous/d042e9cd25f478121b7a

**Comment by samccone** [comment]
:+1: should be good to close now right?
