### ISSUE TITLE
Table highlight interrupted by sorted column

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1242]
![screen shot 2015-03-04 at 10 36 40 pm](https://cloud.githubusercontent.com/assets/963093/6498836/f7201a8e-c2be-11e4-90a3-80ef47ec20c3.png)

**Comment by buob** [comment]
The selection highlight isn't interrupted, it's just the hover that is, is that still worth overriding that CSS?

**Comment by scottdraves** [comment]
yes please
