### ISSUE TITLE
Julia PyPlot Intermittent Plotting

### ISSUE THREAD

**Issue by dahlend** [twosigma/beakerx#1244]
[Example](http://sharing.beakernotebook.com/gist/anonymous/2644d1f0a40a1940af80)

Plotting with PyPlot in beaker is intermittent, I have to run a cell multiple times until a plot sticks.

**Comment by scottdraves** [comment]
Thanks for the bug report.  I'll check this out after v1.2 is finished, and we'll see if it's still a problem.

**Comment by dahlend** [comment]
This seems to be less specific then just PyPlot. While PyPlot output is often dropped, there are occasions when any output from a Julia cell is missed, albeit less frequently than PyPlot.
