### ISSUE TITLE
replace default notebook

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#126]
right now we have 5 evaluators, which is slow to start and takes a lot of memory.
can this be simplified, maybe just to JS?

**Comment by jchendy** [comment]
I think that makes sense for after we implement a redesign that makes adding plugins easy.

**Comment by scottdraves** [comment]
is what we have so hard (3 clicks)?
the real problem is since we have no way to remove a plugin, all user notebooks will start all plugins.
do we really want that?

**Comment by jchendy** [comment]
Yes. I've heard things like 'I didn't know you supported language X' from multiple users. If our default notebook had JS only, a large portion of users would assume Beaker only worked with JS. We can definitely clean things up once we have a UI design for easily adding and removing plugins from a notebook.

**Comment by scottdraves** [comment]
What if the control panel just had some promo text with a list of the
supported languages?
That would be a lot easier than redoing the plugin UI.

On Tue, Apr 8, 2014 at 4:48 PM, Jeff Hendy notifications@github.com wrote:

> Yes. I've heard things like 'I didn't know you supported language X' from
> multiple users. If our default notebook had JS only, a large portion of
> users would assume Beaker only worked with JS. We can definitely clean
> things up once we have a UI design for easily adding and removing plugins
> from a notebook.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/twosigma/beaker-notebook/issues/126#issuecomment-39899910
> .

## 

ScottDraves.com http://www.ScottDraves.com
google.com/+ScottDraves

**Comment by jchendy** [comment]
We're going to redo the plugin UI anyway. I'm just recommending we postpone this request for a few weeks. Is there some particular reason you think it can't wait?

**Comment by jchendy** [comment]
I'd also be fine with a mid-way solution for now. We could remove a couple evaluators from the default. I'd be fine with loading just JS, Python, and R.

**Comment by scottdraves** [comment]
Yes we are going to redo it... eventually.  It's a big project and who knows when it will really happen.
The reason I don't want to wait is the current experience sucks.  It is slow, takes up a ton of memory, and spews errors if you don't have all these languages installed.
Putting the list of languages on the control panel solves these problems and does a better job of solving the problem of communicating to users that we support all these languages.   Right now Julia and Node are missing from the default notebook and so users have no way to hear about them.

**Comment by scottdraves** [comment]
And, adding some html to the control panel is trivial.

**Comment by jchendy** [comment]
We agreed on a temporary compromise solution:
- Default notebook has just R, Python, and JS
- Both the default notebook and the control panel list available languages and instructions for adding them

In the long term, after we implement the redesign and new plugin manager, we'll have 0-1 languages in the default notebook and make it easy for users to add new languages.

**Comment by jchendy** [comment]
I updated the default notebook with this commit: https://github.com/twosigma/beaker-notebook/commit/79f8ffaed29e879b46a0847fd8bc0f6d5f29cf6c

Updating the control panel is still a TODO.

ps. The diff on notebook files is pretty easy to ready. That's awesome.

**Comment by scottdraves** [comment]
this all got done thanks.
