### ISSUE TITLE
allow collaborative realtime editing

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#128]
here's one way
https://developers.google.com/drive/realtime/

**Comment by anglee** [comment]
We might want also look at https://www.firebase.com/ and [AngularFire](https://www.firebase.com/quickstart/angularjs.html)

**Comment by scottdraves** [comment]
https://github.com/share/ShareJS

**Comment by scottdraves** [comment]
https://togetherjs.com/

**Comment by scottdraves** [comment]
relevant https://www.firebase.com/blog/2014-10-21-firebase-joins-google.html
