### ISSUE TITLE
Menu sub-items should be visible whenever the menu is in active state

### ISSUE THREAD

**Issue by planyon** [twosigma/beakerx#1290]
Click on the File menu, the contents of that menu will be visible.
Hover over the Notebook menu and "Notebook" is set to active state but the menu items are not visible.

The menu should behave in the same manner as a browser menu, moving your cursor over the various menu items after having clicked on one should open and highlight whichever item your cursor is hovering on. A second click will close the menu and hovering over an items will not show the list of sub-items or show the item in an active state.

In the attached screenshot "Notebook" should have its menu items displayed.

![screen shot 2015-03-12 at 10 43 08 am](https://cloud.githubusercontent.com/assets/5454235/6620065/f6433236-c8a4-11e4-931f-e26673be9b71.png)

**Comment by scottdraves** [comment]
agreed this is better behavior.
