### ISSUE TITLE
Menu Not Loading Completely

### ISSUE THREAD

**Issue by dahlend** [twosigma/beakerx#1294]
![screen shot 2015-03-13 at 12 44 34 pm](https://cloud.githubusercontent.com/assets/8423587/6644000/c054d7b2-c97e-11e4-8c9e-027a5845df99.png)

I couldn't find this as a current issue, but menu loading is intermittent.  Sometimes all the options show, sometimes not.

**Comment by ildipo** [comment]
Hi, thanks for the report.
I don't think we have a github issue for that but it is an annoying effect I noticed too - it is due to the heavy dynamic loading of menus.
The workaround I use is to open and close an empty notebook and usually this loads all remaining menus.
We'll work on it ASAP.

**Comment by dahlend** [comment]
Thanks for the work around, not being able to show the hierarchy on a larger notebook was a pain.

**Comment by samccone** [comment]
has anyone been able to reproduce this recently? I have not seen it in a very long time

**Comment by scottdraves** [comment]
not by me
