### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by zafarali** [twosigma/beakerx#1297]
Hi all, I'm excited to try out Beaker but I've been shot down before I even started.

When I run the launcher I get the Web Page Not Available error from Google Chrome. With the description: 
`Google Chrome's connection attempt to 127.0.0.1 was rejected. The website may be down, or your network may not be properly configured.`

I'm using version 1.1.2 (1) of Beaker and I'm on OS X 10.10 Google Chrome 41.0.2272.89 (64-bit)

I do alot of development on my machine and that might be causing an interference with the app but I have no idea how to begin debugging it. If someone can guide me through it or point me to where to look I'm sure I will be able to figure it out.

**Comment by scottdraves** [comment]
Thanks for the bug report.  I think we might have have fixed this one, can you try the prerelease of v1.2 which is available from the last question on the FAQ page: http://beakernotebook.com/faq

**Comment by zafarali** [comment]
Thanks so much! It works now, excited to try it out.

Cheers
