### ISSUE TITLE
stdin for evaluation

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1304]
here's a vague idea.

we handle stdout but if during cell evaluation you try to read from stdin then it just hangs.

should either give an error (can we close it before forking?) or actually get some input.

i have a fantasy that we could somehow detect this and pop up a box dialog to prompt for the input.
but that sounds hard to do that completely automatically.

but maybe some kind of API or UI could determine when to do that, or otherwise connect stdin to something.

**Comment by ildipo** [comment]
I think it is a good idea.

In JVM based languages this can be done by adding an overloading to stdin object as we are doing for stdout and stderr... we can then extend the SimpleEvaluationResult (which is not simple anymore) to signal the client that we want some input and provide a rest call to provide it.

For Python this is available as a callback from the kernel already running in the browser so it should be even easier.
