### ISSUE TITLE
Clojure needs

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1311]
in order:
- a beaker object with autotranslation (and other runtime functions)
- a demo tutorial notebook
- settable classpath and dynamic classpath, shared with the other JVM languages. 
- autocomplete

**Comment by scottdraves** [comment]
and work with https://github.com/technomancy/leiningen

**Comment by scottdraves** [comment]
define the beaker object with deftype as per http://clojure.org/datatypes

but how do you define the getters and setters so you can say (:x beaker) instead of (get "x" beaker)?

**Comment by ildipo** [comment]
Added individual github issues to track each functionality independently
