### ISSUE TITLE
clojure prints errors on defn

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1316]
![screen shot 2015-03-24 at 10 05 19 pm](https://cloud.githubusercontent.com/assets/963093/6817048/fdb6a724-d271-11e4-9484-c6e2deed462f.png)

**Comment by buob** [comment]
This is a custom error we're reporting if we don't understand the return value of a cell.  If you tried to use the method after it, it would work fine.  Should it just not put anything in the output?

**Comment by scottdraves** [comment]
we should do what the standard clojure repl does.

**Comment by scottdraves** [comment]
This is the result of the new autotranslation work, and so this applies to all of the JVM languages.
![screen shot 2015-03-31 at 10 59 14 am](https://cloud.githubusercontent.com/assets/963093/6921801/fcca3038-d794-11e4-8f35-6a771bdd1bdf.png)

just removing "ERROR: unsupported object" is fine.

**Comment by maksim-lauryk** [comment]
I tested this case and now it works following manner:
![output_object](https://cloud.githubusercontent.com/assets/13995034/10190089/f2fcd268-6772-11e5-9efe-6b49e3e775ec.PNG)
