### ISSUE TITLE
build required to edit plugin JS

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#133]
during development, you can't just edit the plugin JS and reload.
the JS is copied during build.  this is confusing and slows down working with the code.

**Comment by anglee** [comment]
Agreed. A related problem is when we start deploying the frontend with front-end asset files with tasks minifying, uglifying, concatenating...

We should use [gulp](http://gulpjs.com/) (or [grunt](http://gruntjs.com/), or any task runner we choose) and set up a 'watch' task.
