### ISSUE TITLE
move cleaning js out of html to master

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1347]
https://github.com/twosigma/beaker-notebook/commit/df8fc2d8e4e9bb17e5b5e64b7f284ca8afd30700

**Comment by ildipo** [comment]
We want to keep some event handlers while in beaker (to support html forms) but since it is impossible to remove an event listener if you don't save its registered function we can only leave all event listeners attached.
We can clean dangerous tags.
