### ISSUE TITLE
Remove "cell output"

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1360]
and move up the content of the output box.

**Comment by buob** [comment]
Right now it shows "Error" if there's an error, otherwise "Cell Output".  It also shows the cell run time next to it.  Should we kill all of those?  The run time in small print might look weird by itself.

**Comment by scottdraves** [comment]
Keep "Error" if there is one.
remove the run time.  i actually don't see that anymore IDK why but I know it used to be there.
any any case, it's in the cell menu so not important to keep here.

**Comment by scottdraves** [comment]
"Output Hidden" should also be removed.

**Comment by buob** [comment]
So should we just show an empty cell output if it's hidden?

**Comment by scottdraves** [comment]
yup, just the controls on the right visible.
