### ISSUE TITLE
markdown cells should use code mirror

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1362]
then we get  https://github.com/twosigma/beaker-notebook/issues/704 and https://github.com/twosigma/beaker-notebook/issues/1345

**Comment by buob** [comment]
Are we okay with them behaving like normal code cells?  Input and output?

**Comment by scottdraves** [comment]
nothing should change except editing would be enabled.

**Comment by scottdraves** [comment]
related https://github.com/twosigma/beaker-notebook/issues/1345
