### ISSUE TITLE
No keyboard shortcut for commenting out code?

### ISSUE THREAD

**Issue by k-dahl** [twosigma/beakerx#1365]
Typically this is CTRL-/ with IPython. It's a pretty integral part of any code exploration I do.

Edit: I had added something about CTRL-A as well, but it appears that is actually in there and working.

**Comment by scottdraves** [comment]
That's a good idea.

**Comment by scottdraves** [comment]
the interesting thing about this command on beaker is that it would have to do something different in each language, so we would need a new API call into the plugin.
