### ISSUE TITLE
should this be checked in?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1370]
this is generated and out of date right?
https://github.com/twosigma/beaker-notebook/tree/master/embeddable_assets

**Comment by scottdraves** [comment]
at a minimum it needs a README.md that explains what it's for and how to update it.

**Comment by mforsyth** [comment]
Hi @scottdraves, yes, it's generated.  The embeddeble_assets are the version of the Beaker client code that is intended for being used as a library (embedding in another application).  Although I usually don't like the idea of checking generated files into source control, in the case of frontend libraries, checking the "compiled file" into the github repo that contains the source seems to be the normal way to publish compiled builds these days.   For example, the generated single-file version of Angular is available in the Angular git repo in addition to  all of the original source files that go into it.

I'll add a small readme to the embeddable_assets dir that tells how to generate the assets (it only requires running a gradle task).

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1535
