### ISSUE TITLE
How do get or set the working directory for html renderer?

### ISSUE THREAD

**Issue by InfantLab** [twosigma/beakerx#1371]
Can't figure this one out,
Thanks in advance

**Comment by scottdraves** [comment]
Not sure what you mean, the HTML is not written to disk.
What are you trying to do?

**Comment by InfantLab** [comment]
I want to display an image from the same directory as the notebook file: 

`<img src="./Workflow.png">`

**Comment by scottdraves** [comment]
similar: https://github.com/twosigma/beaker-notebook/issues/708

**Comment by scottdraves** [comment]
You can't change this and we don't have a good solution for you right now.

But it is not hard to work around, you just have to copy the files into the application.
On the Mac the root of the web server is `/Applications/Beaker.app/Contents/Resources/dist/src/main/web/`
so just create a directory in there, say "ext" and then you should be able to refer to assets there with
`<img src="./ext/myimg.png">`

**Comment by InfantLab** [comment]
Ah right. In that case, I think I'll just host them from the web.
Thanks.

**Comment by scottdraves** [comment]
the fix for this has been released in v1.3 https://github.com/twosigma/beaker-notebook/pull/1769
