### ISSUE TITLE
node plugin needs

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1395]
- output should go into the cell not into the tray
- variables should be accessible from one cell to another
- autotranslation
- autocompletion

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/1145

**Comment by scottdraves** [comment]
autotranslation done: https://github.com/twosigma/beaker-notebook/issues/4267

**Comment by sshkalikov** [comment]
> variables should be accessible from one cell to another

already done - https://github.com/twosigma/beaker-notebook/commit/80e412b48a9d65cf441ff0785809e809a5014965
