### ISSUE TITLE
markdown cells should flag spelling errors

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1404]
this is one of the nice things about text cells now, when writing prose it's nice to get the red underline indicating a spelling error.

**Comment by samccone** [comment]
Looks like this is never going to happen so long as we use codemirror for markdown
https://github.com/codemirror/CodeMirror/issues/1017#issuecomment-52287597

**Comment by scottdraves** [comment]
How about https://github.com/cfinke/Typo.js?
