### ISSUE TITLE
JS crashes on circular structure

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1409]
![screen shot 2015-04-07 at 1 54 51 pm](https://cloud.githubusercontent.com/assets/963093/7029728/bcf68c10-dd2d-11e4-8fb0-fc42df6f45e6.png)

**Comment by ildipo** [comment]
fixed in master

**Comment by scottdraves** [comment]
looks the same
https://github.com/twosigma/beaker-notebook/issues/1701
