### ISSUE TITLE
remove plugin URLs from notebook files

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#142]
Currently notebook files have an evaluators section that includes a record for each plugin.  In addition to a name (just shown to the user) there's a field "plugin" that is sometimes a URL pointing at a JS file, and sometimes a name that is resolved by the plugin manager (https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/js/module/evaluatorManager.js#L34).  Here's an example:

```
    {
        "name": "Latex",
        "plugin": "./plugin/evaluator/latex.js",
        "shellID": null
    }
```

Here's another example:

```
    {
        "name": "IPython",
        "plugin": "IPython",
        "shellID": "2EEE891A2CF1433EA04171031F51CFA4",
        "imports": "",
        "supplementalClassPath": ""
    }
```

When a plugin is added from the plugin manager, a URL is used.  The only time (afaik) that a name can be in the plugin field is because the default notebook has some names here and most notebooks are made by saving copies of the default.  The default was created manually (https://github.com/twosigma/beaker-notebook/blob/master/core/config/default.bkr).

Storing and using a URL here is a problem for numerous reasons, including:
- The URLs are based on the internal organization of the beaker code.  This has changed several times and will no doubt change again.  And the URLs differ depending on which version of beaker you are running.  If you load a notebook from and old/different version, then the plugin will fail to load since the URL is not found.
- If the URL is to a server external from Beaker core, then you cannot run the notebook disconnected from the net.  Or if that server is temporarily down.  Or if that server is permanently down, since its owner decided to remove it.
- If the URL is to an external server, there is a giant security hole because it could be hacked and a rogue plugin loaded into customers browsers.

The fix is simple:  always use names and let the translation to URLs be done by the plugin manager.

**Comment by jchendy** [comment]
We discussed this in person and broke this into three issues:

#143 needs to be addressed before beta launch
#144 should be done soon
#145 will be addressed later
