### ISSUE TITLE
backquotes around math blow up markdown

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1427]
rendering ``$\pi$`` results in:

![screen shot 2015-04-08 at 4 58 33 pm](https://cloud.githubusercontent.com/assets/963093/7055303/88779838-de10-11e4-9bed-053e1d53fb88.png)

**Comment by samccone** [comment]
So I think this is "expected" behavior.

in markdown 

```
`
```

denotes an inline code block

> http://daringfireball.net/projects/markdown/syntax#code

Which is going to wrap the latex in a `<code></code>` block, thus we are see the markup from KaTex as compared to the rendered DOM.

thoughts?

**Comment by scottdraves** [comment]
i think the $ should not be expanded inside `.
but this isn't a priority so don't worry about it now.

**Comment by samccone** [comment]
oh it is being expanded :) just markdown is wrapping it all in `<code></code>` which makes it not render as html

**Comment by scottdraves** [comment]
would be OK if we could avoid this as follows:
<img width="702" alt="screen shot 2016-10-18 at 10 07 29 pm" src="https://cloud.githubusercontent.com/assets/963093/19503055/2116619c-957f-11e6-8372-3081ef6a4b3e.png">
