### ISSUE TITLE
need a way to put a dollar into markdown

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1428]
$ is triggering LaTeX mode.  We need a way for users to mean it literally.

**Comment by scottdraves** [comment]
i think just a backslash should do.  so \$ means $, but without LaTeX.
and if you really want a \$ then \$.

**Comment by scottdraves** [comment]
does `&dollar;` work?

**Comment by samccone** [comment]
Test cases:

#### Single `$` :white_check_mark:

![screen shot 2015-05-06 at 10 55 14 am](https://cloud.githubusercontent.com/assets/883126/7495844/70c58ac2-f3de-11e4-9dfe-5776e3bdfcd6.png)

![screen shot 2015-05-06 at 10 56 06 am](https://cloud.githubusercontent.com/assets/883126/7495860/88d6d5ee-f3de-11e4-9c6c-31956eee683c.png)

#### Two `$` :warning:

![screen shot 2015-05-06 at 10 55 25 am](https://cloud.githubusercontent.com/assets/883126/7495948/3f062fd6-f3df-11e4-9438-4aa8578ef66c.png)\

![screen shot 2015-05-06 at 10 55 28 am](https://cloud.githubusercontent.com/assets/883126/7495954/4355fd8c-f3df-11e4-8ee9-14922c88cf9c.png)

#### HTML `$` entity `&dollar;` :warning:

![screen shot 2015-05-06 at 11 02 13 am](https://cloud.githubusercontent.com/assets/883126/7495978/60d0728e-f3df-11e4-823c-536605691c4b.png)
![screen shot 2015-05-06 at 11 02 17 am](https://cloud.githubusercontent.com/assets/883126/7495980/64211af6-f3df-11e4-809f-8c276f9ea2a4.png)

#### Escaped `\$` :warning:

![screen shot 2015-05-06 at 11 03 13 am](https://cloud.githubusercontent.com/assets/883126/7496004/84541fa8-f3df-11e4-8f70-58757f887186.png)

![screen shot 2015-05-06 at 11 03 17 am](https://cloud.githubusercontent.com/assets/883126/7496006/882cd2fa-f3df-11e4-8f78-2458ad37543d.png)

---

### Goal

`\$` should render a single $
