### ISSUE TITLE
code sometimes missing

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1433]
starting a week or so ago i've noticed code cells sometimes are missing their code.
clicking on the cell brings the code back.

here's an example of how a cell looks when the problem manifests:
![screen shot 2015-04-09 at 7 00 22 pm](https://cloud.githubusercontent.com/assets/963093/7078811/dff51d44-deea-11e4-9cb8-e5f0b4c63bb4.png)

and then clicking it brings it back to normal:
![screen shot 2015-04-09 at 7 00 28 pm](https://cloud.githubusercontent.com/assets/963093/7078816/ec6fee0a-deea-11e4-80a9-f2bcf943b441.png)

to reproduce this, make a notebook with (in order from top) an html cell and a section heading.
make sure the html cell has some code.
close the (empty) section. click the down button on the html cell, it moves into the section and vanishes.
open the section.  the code cell manifests the problem.

**Comment by scottdraves** [comment]
this fixes the deterministic problem with code cells in sections, but not the problem where when you open a notebook, some code cells are broken.  try opening the JS tutorial.

**Comment by buob** [comment]
I couldn't reproduce this (Ubuntu 13.10 & Chrome 39); on which versions are you seeing this bug?

**Comment by scottdraves** [comment]
this machine is 14.04.2 & 41.0.2272.118

**Comment by samccone** [comment]
@scottdraves is this still happening for you after we updated code mirror?

**Comment by scottdraves** [comment]
i will test on my machine at home, thanks for reminding me.
