### ISSUE TITLE
improve beaker.pref.json handling

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1436]
the server should not crash completely if there is a syntax error in the beaker.pref.json file.

also should probably support yaml https://github.com/twosigma/beaker-notebook/issues/397

**Comment by samccone** [comment]
I think it would be quite nice to expose a config screen in the application where a user can edit this file.

thoughts?

**Comment by scottdraves** [comment]
yes and that was the original plan.  but right now since you can't retry loading plugins, after you edit the file the only thing you could do is exit and restart the application, which is too painful.  so after the plugin API gets fixed we can make the editor for it.

**Comment by samccone** [comment]
:+1:
