### ISSUE TITLE
error during init cells unreported

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1438]
If you open a notebook with initialization cells, and there is an error while they are running,
then Beaker gets stuck with the "Please wait" window up.
It should close the window and move the notebook to the cell showing the error.
Actually it should change the window to one that says "initialization failed" with an OK button.

**Comment by ildipo** [comment]
after the (last month?) evaluation queue changes the evaluate call will resolve the promise as failure si it should be straightforward to add this

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1758
