### ISSUE TITLE
header is gone from shared notebooks

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1441]
the sharing server is supposed to have a header that links to us, allows you to download the notebook, or go to the original gist.  it's not there.

**Comment by ildipo** [comment]
I think it is a style change. I had to modify it for our internal sharing server since it was layout as 0 height

**Comment by scottdraves** [comment]
yea but which style??

i just hardcoded a few styles in the html of the index and it looks OK now but this was just hack/patch.
