### ISSUE TITLE
Correctly position cursor from first click on markdown cells and section headers

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1478]
right now the 1st click on a markdown cell or section header enables editing on it, and the formatted version is replaced with plain text that you can then click on and edit.

we set the cursor at the beginning or end depending on if they clicked on the upper or lower half of the cell, but it would be better if the cursor could be initialized to where you actually clicked.

the problem is, the text moves when it is formatted, so there's no simple way to determine where to put it.
however, it seems theoretically possible to keep track of where each character goes, and hence map clicks back to their original locations.

this is a nontrivial change that probably needs real help from marked itself.

**Comment by scottdraves** [comment]
it doesn't work for dragging though

**Comment by samccone** [comment]
yeah I think this is totally doable, let me know where this stacks up priority wise

**Comment by scottdraves** [comment]
xlnt.  not on the agenda yet.
