### ISSUE TITLE
windows build only works on 64-bit OS

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1498]
we should put a note on the website where you download it.

**Comment by altavir** [comment]
Windows is practically always comes with installed oracle jvm 7+. In my opinion, it is easier to remove jvm from distribution and declare is as required software. This will also dramatically decrease distribution size. The only problem I see is that windows Java installation does not automatically set `JAVA_HOME` environment value. But its probably easier  to ask user to define it on configuration before first run.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/commit/e52b23e83b243a026a58a52a2c08d86b034bd29c

**Comment by scottdraves** [comment]
we also have the nginx binary, which is 64-bit.  but eventually that will be removed and then yes it would be great to have an option to use a s pre-installed jvm.
