### ISSUE TITLE
bad js in html cell crashes on notebook load

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1499]
the html cell with highcharts in this notebook: http://sharing.beakernotebook.com/gist/anonymous/19af750f02363db42de6
breaks beaker when it's loaded.  you can fix it easily:
http://sharing.beakernotebook.com/gist/anonymous/8ba897527e5a5dc259e3
but we should not let users break the app.

i tried a trivial notebook with an html cell that just has an html cell with a script error, but it did not bork the application the same way.  not sure why yet.

related: https://github.com/twosigma/beaker-notebook/issues/862

**Comment by samccone** [comment]
we could manually crawl all `<script></script>` tags wrapping them in a `try catch`
