### ISSUE TITLE
Function arguments list/help

### ISSUE THREAD

**Issue by gauravkumar37** [twosigma/beakerx#1501]
Hi,

I couldn't find anything in help or any issue here regarding this.
Beaker should help with tooltips when calling functions similar to what IPython  does. You write `len(` and press `Shift+Tab` and it will show you the function parameter lists.
The absence of this feature is a blocker for me currently.

Thanks.

**Comment by scottdraves** [comment]
thanks for the feedback.  i agree, we should support tooltips in addition to autocompletion.

**Comment by gauravkumar37** [comment]
Thanks a bunch !!! Looking forward to it...
I would suggest you to take a look at IPython/Jupyter's implementation.

**Comment by scottdraves** [comment]
<img width="548" alt="screen shot 2015-10-02 at 11 58 19 pm" src="https://cloud.githubusercontent.com/assets/963093/10261360/b758168c-6961-11e5-8bf2-7e4132eeb391.png">
