### ISSUE TITLE
on windows ipython is incompatible with cygwin

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1511]
If you install cygwin and then anaconda, the python that ends up first in your path is from cygwin.
this is a problem even if you use beaker.pref.json to specify a path, because the path you put in there is to ipython, which anaconda puts in C:\Anaconda\Scripts.  But the python executable is in C:\Anaconda.  the anaconda installer puts both of these directories into the path, but our mechanism only allows one directory.

there are a couple of ways of dealing with this:
1) tell the users to put cygwin after anaconda in the path.  could probably detect this situation (just check sys.version for "cygming") and suggest it.
2) the fact that we need python in addition to ipython is quite annoying, but using ipython instead of python gave a different result for the hash function.  there is probably some way to fix that, and use just ipython.

**Comment by scottdraves** [comment]
the failure: https://github.com/twosigma/beaker-notebook/issues/1500

**Comment by scottdraves** [comment]
added to FAQ https://github.com/twosigma/beaker-notebook-www/commit/38627eda332f28384baeefe09e9476b312982b51

**Comment by BAM-BAM-BAM** [comment]
When trying to launch (virtualenv, not Anaconda) iPython using cygwin64, getting file-not-found error (the path of the file is mixing Windows-backslash style with Linux forward-slash style):

```
ipython-version-stderr>Traceback (most recent call last):
ipython-version-stderr>  File "C:\Beaker\beaker-notebook-1.5.2-0-g34d512f-windows/config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin", line 25, in <module>
ipython-version-stderr>    os.execlp("ipython", "ipython", "--version")
ipython-version-stderr>  File "C:\Beaker\beaker-notebook-1.5.2-0-g34d512f-windows\python\lib\os.py", line 327, in execlp
ipython-version-stderr>    execvp(file, args)
ipython-version-stderr>  File "C:\Beaker\beaker-notebook-1.5.2-0-g34d512f-windows\python\lib\os.py", line 344, in execvp
ipython-version-stderr>    _execvpe(file, args)
ipython-version-stderr>  File "C:\Beaker\beaker-notebook-1.5.2-0-g34d512f-windows\python\lib\os.py", line 380, in _execvpe
ipython-version-stderr>    func(fullname, *argrest)
ipython-version-stderr>OSError: [Errno 2] No such file or directory
```

This is my beaker.pref.json file:
`{
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : true,
  "languages" : {
    "IPython" : {
      "path" : "C:\\cygwin64\\home\\John\\.virtualenvs\\myenv\\bin"
    }
  },
  "advanced-mode" : false,
  "edit-mode" : "default"
}`

`C:\cygwin64\bin;` is near the end of my %path%. Anaconda is not installed.

**Comment by scottdraves** [comment]
we don't support cygwin. i don't think there's a problem with mixing forward and backward slashes, they both work.

it looks like your virtualenv is simply missing ipython.  beaker might work if you add its python dependencies, but i have never tried with cygwin.
