### ISSUE TITLE
Using boot2docker on Windows to run Beaker Container

### ISSUE THREAD

**Issue by njss** [twosigma/beakerx#1512]
The installation was smooth, but when I was trying to execute ipython or R code in a new notebook I get some erros like:
IPython-stderr>2015-04-23 08:17:51.124 [NotebookApp] Kernel shutdown: 56155ec5-f
6bf-425f-84ad-f4b7f3b7380a
java.io.FileNotFoundException: /home/beaker/.beaker/v1/config/beaker.pref.json (
Read-only file system)

**Comment by scottdraves** [comment]
thanks for the report.  i haven't tried boot2docker yet but i will and see if i get this too.
