### ISSUE TITLE
Add python dependencies to website

### ISSUE THREAD

**Issue by diogo149** [twosigma/beakerx#1528]
Not sure if this is the right place for issues on the website, but the dependencies for running an ipython kernel are missing: http://beakernotebook.com/getting-started

**Comment by scottdraves** [comment]
Hi Diogo, this is a fine place for that.

Which platform do you mean?  For Mac, for IPython (this is down in the "optional components" section, below the "Download base install" button) we recommend installing Python with Anaconda, which should be complete.

Which dependencies were you thinking of?

**Comment by diogo149** [comment]
Sorry, misread anaconda to conda (the package manager)! It may be useful to explicitly provide a list of the pip dependencies somewhere if an individual wanted to use an existing virtualenv though (I've only seem them listed in the Dockerfile and an install script).

**Comment by scottdraves** [comment]
You are right, we should make that easier to find.  I'll add a link to the Python section for people who want to use a preexisting python.

**Comment by scottdraves** [comment]
how's this? https://github.com/twosigma/beaker-notebook-www/commit/ef2ac3510ecfb98527acea6490f5d5bcea5cef2d
it's live on the site now.

**Comment by diogo149** [comment]
Looks good to me! (:
