### ISSUE TITLE
Investigate replacing all non updating `{{ }}` with a one time binding

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1530]
It is no secret that the cost of establishing a two way data binding in angular comes at quite a high cost  (to the digest loop) when there are many bindings established, due to the dirty check and application phase of **the loop**.

This memory issue is quite visible on notebook pages with many cells and sections. 
An obvious path or increasing performance, not crashing the browser, and improving end user experience would be to find a way to minimize the number of these bindings that exist. 

To do this I propose taking a look at everywhere that we use `{{}}` and asking the question 

> do we ever update this value over time (after the initial null => "val" application)

If the answer is no, then it allows us to implement a type of one time binding logic where the value is interpolated and then the binding and registration is dropped. 

Ideally this should significantly reduce the memory overhead and performance hit that we have been seeing for a long time.

---

Thoughts @scottdraves ?

**Comment by scottdraves** [comment]
sounds like a good idea.  can you say more about the cost?  how much upside is there from going down this road?  and how are you suggesting we implement a one-time binding?  surely we are not the only ones to face this so there should be a standard solution right?  do you have a link to a discussion of this problem in general?

**Comment by samccone** [comment]
The cost would be identifying which bindings were eligible for this optimization
the upside would be a performance boost. 

Yep this is a relatively "solved" problem
https://github.com/Pasvaz/bindonce

this solution however is a bit invasive but we can piggy back off of the work done here to implement something like 
`[[ foo ]]`

within our templates

**Comment by scottdraves** [comment]
i tried the reactive test http://plnkr.co/edit/jwrHVb?p=preview
i didn't see any freezing.  what am i missing?

**Comment by samccone** [comment]
hmm yeah I am not able to get that demo to work at all

**Comment by scottdraves** [comment]
maybe it has been fixed in angular in the browser?  i would like to see more discussion of this problem and other ways of solving it.  i am not convinced that the number of watchers is a problem for us.  also, i am not convinced that bindonce is needed, as it has the extra capability of handling data that's not available at link time, but we might be able to reduce our watchers with a simpler mechanism.

**Comment by samccone** [comment]
> maybe it has been fixed in angular in the browser

The cost of binding and watchers is an issue that has not gone away in Angular and will not go away until they kill scope and the digest loop (as they are planning in 2.0). It is simply a reality of how watch and digest works in 1.x 

I agree that there should be more investigation into the cause of the perf issues on the site, as with any perf issues it is best to have some hard numbers and stats and run a few controlled tests to verify assumptions before taking and wide reaching actions.

I used this approach when fixing a set of leaky directives on the todomvc example angular apps
https://github.com/tastejs/todomvc/issues/1254#issuecomment-90666232

I would love to use the same process for this issue, since I think the resulting fix to the problem will be useful not only to this application, but also the angular community at large.

**Comment by scottdraves** [comment]
good work on that todo demo, sam.  we could definitely use some of that :)

so yea after we have some better metrics, we can look at this as one way to improve them.
