### ISSUE TITLE
formatted markdown overlaps cell menu

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1532]
When a markdown cell is formatted, if the text is long enough it overlaps with the cell menu buttons:
![screen shot 2015-04-29 at 11 34 29 am](https://cloud.githubusercontent.com/assets/963093/7394794/e800947c-ee63-11e4-8ae1-cdaf1dc0c139.png)

Would it be possible to flow the text around, ie break that first line early?  Is there a better way of solving this?

**Comment by samccone** [comment]
:heavy_check_mark: on it
