### ISSUE TITLE
R pairs() command failed to execute

### ISSUE THREAD

**Issue by frankz-ai** [twosigma/beakerx#1540]
pairs() command in beaker is very slow for small data sets, and failed to execute for large ones.
Example:
library(MASS)
pairs(Boston)
This will stuck at executing and I have to restart the beakernotebook page.
Even if the graph was loaded, the whole notebook page will freeze and becomes extremely slow.
Run these commands at terminal R session will be really fast. 
No warning on Console and javascript console recorded. I am using OSX 10.10.3

**Comment by scottdraves** [comment]
Thanks for the bug report.  That's a 33MB plot, which is pretty hefty but shouldn't hang.
We'll look into what's wrong.

**Comment by frankz-ai** [comment]
Great! Thanks for the quick response!

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1753
