### ISSUE TITLE
advanced mode insert button changes size on mouseover

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1542]
the buttons change to a darker blue on mouseover.  but the menu one on the right also changes size, by one pixel on the left.
![screen shot 2015-05-01 at 6 08 03 pm](https://cloud.githubusercontent.com/assets/963093/7438140/577a5f16-f02d-11e4-9f60-e83231eec81b.png)
![screen shot 2015-05-01 at 6 08 16 pm](https://cloud.githubusercontent.com/assets/963093/7438139/5778d88a-f02d-11e4-8f5f-829b6c92de96.png)

**Comment by samccone** [comment]
Currently unable to reproduce on chrome 42.0.2311.90

![out](https://cloud.githubusercontent.com/assets/883126/7454260/e478daf0-f23f-11e4-9a61-e6bbe7b83bbf.gif)

**Comment by scottdraves** [comment]
that's not advanced mode

**Comment by samccone** [comment]
![out](https://cloud.githubusercontent.com/assets/883126/7454342/c05470ca-f240-11e4-83d5-c9f3c5b5d29d.gif)

Ah seeing the same behavior in advanced mode as well

**Comment by scottdraves** [comment]
idk why it doesn't happen for you.
but whatever this is not a high priority.

**Comment by samccone** [comment]
@scottdraves still an issue for you? It still seems ok for me
