### ISSUE TITLE
need downloads list on web page

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1543]
need a link, maybe even a tab "downloads", with a list of simple links for all current and past versions.

the "getting started" download is nice but you can't get the URL out of the web browser UI because of the way the JS is written.  plus we need to make past version archive accessible.

release notes would be moved here too.

**Comment by samccone** [comment]
:+1: @scottdraves did this
https://github.com/twosigma/beaker-notebook-www/commit/82f4965fc18b824affd3d2984d5f6047db15c80a

:space_invader:
