### ISSUE TITLE
Performance Investigation Tickets

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1546]
Here are the current tickets that we have filed:
#178 -- initial notebook load time
#838 -- write performance tests
#1530 -- watchers

---

An initial step might be to manually generate some performance numbers so that we have a base to go from.
What do you think @scottdraves ?

**Comment by scottdraves** [comment]
i believe we already have a test for 178, though i am not sure it is right.
we need to have some large notebooks for 838, i can provide you with links.
adding a protractor tests that do these and just report the number somewhere on the console would be great.

**Comment by scottdraves** [comment]
http://nbviewer.ipython.org/url/norvig.com/ipython/TSPv3.ipynb
is a good big one.  also very instructive to see how fast it loads in ipython vs beaker.
it took me about 20s to load in beaker vs 5s in ipython, timed informally.
plus, it opens almost instantly on their sharing server.

**Comment by samccone** [comment]
# Performance Investigation into slow initial boot. 

_(5/5/15)_

The first several seconds when visiting a notebook from a cold start seems to take a very long time. I broke the "slowness" into two discrete categories of issues. One is more the "why" someone things a page loads slowly and the other is the actual performance issues that cause certain aspects of the page to load sluggishly. 

## Perceived slowness

When A user visits a new notebook they are presented with a screen that looks like an empty notebook 

![screen shot 2015-05-05 at 3 03 51 pm](https://cloud.githubusercontent.com/assets/883126/7480904/0ab5f81a-f33a-11e4-83c1-6257bd79f914.png)

The screen then sits in that state until the entire notebook populates in (on large notebooks this can take multiple seconds) – most of this time is actually the load time of the notebook from the sever .. not the render time.

#### Solution

This is more a a UX problem, and should be quite easy to solve with a loading indicator and or spinner, to give the user some feedback that something is happening. 

## Perf Bottlenecks

On large notebooks the perf issues become quite obvious, due to the sheer number of elements and directives that are rendered into the DOM. (on larger notebooks this can be upwards of 100+ code editors)

### CodeMirror

The biggest offender by far is the code editor directives and more specifically codemirror performing multiple expensive root layout reflows when generating a single codemirror instance 

![screen shot 2015-05-05 at 10 35 40 am](https://cloud.githubusercontent.com/assets/883126/7481546/a874c7da-f33e-11e4-93b9-89717c621fc4.png)

These four calls are taking up around 20% of the total JS execution time for rendering one large notebook **yikes**

When we drill down further we see that all of these calls originate inside of codemirror
![screen shot 2015-05-05 at 10 37 59 am](https://cloud.githubusercontent.com/assets/883126/7481620/51d73cae-f33f-11e4-941e-5890fba742db.png)

#### Expensive Methods

:warning:  **maybeUpdateLineNumberWidth:**
https://github.com/codemirror/CodeMirror/blob/5e989bdabd38535794987c8192f3ca16e24f92a6/lib/codemirror.js#L589

:warning:  **updateGutterSpace**
https://github.com/codemirror/CodeMirror/blob/5e989bdabd38535794987c8192f3ca16e24f92a6/lib/codemirror.js#L324

:warning:  **visibleLines**
https://github.com/codemirror/CodeMirror/blob/5e989bdabd38535794987c8192f3ca16e24f92a6/lib/codemirror.js#L545

##### CodeMirror potential fixes
- Look into lazy instantiation of the editors. 
  - Start them up serially
  - Only start them when they enter into the viewport
  - Only "start" them when someone clicks in to edit.

@marijnh Let me know if you have any thoughts on this matter.

### Many Requirejs Network Requests

On a cold boot of the notebook page there is a fixed cost of downloading all of the requirejs and vendor dependencies from the server before the initial request for the notebook can even be issued. 

In a browser context there is a limit to the number of concurrent connections to the same domain for a single browser instance

![](http://3.bp.blogspot.com/-mkwnVq6Idms/UtlIhhMYtJI/AAAAAAAAAEg/8B51WIPcAag/s1600/max-browser-parallel-connection.png)

[Reference article](http://sgdev-blog.blogspot.com/2014/01/maximum-concurrent-connection-to-same.html)

So it is easy to see that we are easily hitting this limit based on the volume of requests that it takes to boot the app up. Due to this fact, the app incurs a significant perf penalty just because of fetching dependencies.

###### Here are only the javascript resources that we are fetching from the server, to give some perspective on the number.

![screen shot 2015-05-05 at 4 20 15 pm](https://cloud.githubusercontent.com/assets/883126/7482032/a88098fe-f342-11e4-9928-592f4d818394.png)

The requirejs network dance manifests itself in a profile like this:

![screen shot 2015-05-05 at 11 54 10 am](https://cloud.githubusercontent.com/assets/883126/7482508/f6d3af98-f345-11e4-93aa-40efb4bd4b18.png)

##### Requirejs potential fixes

Look into compiling all of the requirejs files into a single optimized file
http://requirejs.org/docs/optimization.html

Reducing the network requests to 1 (also allowing us to uglify and minify the code shrinking the total network payload significantly) 

### Sequential blocking config and setup requests

After the requirejs files are downloaded from the server, there is a dance of requests that takes place between the server and frontend application to establish things like version, plugins, and menu items. 
- `.../recent-menu/getItems`
- `.../rest/util/getVersionInfo`
- `.../rest/util/getMenePlugins`
- `.../getCellMenuPlugins`
- `.../outputlog/get`
- `.../isUseAdvancedMode`

All of these requests happen prior to loading the main notebook file.

##### Potential Sequential blocking config and setup requests fixes
- Consider bootstrapping the initial config payload onto the page when someone hits the url. 
  - `html<script>var config = {...}</script>`
- Create a single config endpoint
  - This "god" endpoint would simplify the complexity on the client side for getting this info, it would also reduce the number of blocking requests to issue the initial load notebook request 

---

### Beaker Takeaways, tldr;
-  Large numbers of reflow causing JS can have significant performance penalties.
  - Even when using popular OS libs,  one must be aware of performance issues that can happen when using them at a scale that is not a common use path.
-  A large number of network requests for vendor js files can cause sluggish boot times.
  - Thinking of ways to reduce network traffic is critical to having an app that feels fast to boot.

**Comment by scottdraves** [comment]
This looks great Sam, thanks.  The requirejs fetches must be an artifact of how you are running, try "gradle run", all the JS should be gulped into a couple of files.

I think your first suggestion is good to go though, I will create a separate issue for its resolution.

I like the idea of lazy instantiation of CodeMirrors.  We need the syntax highlighting as soon as they are visible.  Furthermore, only 1 needs to be really active at a time.  Is there any support for lighter-weight visible-only mode?

**Comment by scottdraves** [comment]
spinner during session load: https://github.com/twosigma/beaker-notebook/issues/1559

**Comment by paulirish** [comment]
I'm looking at http://sharing.beakernotebook.com/gist/anonymous/7df554918e7415f1da2c .. this isn't post-"gradle run" is it?

**Comment by paulirish** [comment]
Agree with the above analysis. It's spot on.

#### require

you could use use r.js + almond for optimized frontend load of scripts, but not sure if the `gradle run` already takes care of that.

#### codemirror

codemirror is definitely layout thrashing a lot. 
- I would first update to latest. You're on 4.7 and latest is 5.2. 
- I would investigate adding layout boundaries around each codemirror so they don;t affect each other. (needs defined px height/width and overflow:hidden).
- Disable CM features you dont need. Hypothetically the gutters, as calculating their widget is one of the reflows.

**Comment by scottdraves** [comment]
> I'm looking at http://sharing.beakernotebook.com/... this isn't post-"gradle run" is it?

correct that is our last release.  "gradle run" on master reduces them to the following (mostly unminified):
![screenshot - 05052015 - 10 41 15 pm](https://cloud.githubusercontent.com/assets/963093/7486770/5c1fc10c-f378-11e4-9724-96c47729de86.png)

which has the main code reduced to about 7 files.  getting rid of the dynamic loading of the plugins will take more effort but it is on the roadmap.

the timeline i see is:
![screenshot - 05052015 - 10 37 31 pm](https://cloud.githubusercontent.com/assets/963093/7486787/8454c3a2-f378-11e4-8d67-fc0829465ddf.png)

thanks for the codemirror tips!
