### ISSUE TITLE
Hierarchy Mode - and + buttons are not aligned correctly

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1548]
![screen shot 2015-05-04 at 9 22 44 am](https://cloud.githubusercontent.com/assets/883126/7454188/5f0fc82e-f23f-11e4-89f3-726db9f14e28.png)

**Comment by samccone** [comment]
(this is also present in advanced mode)

**Comment by scottdraves** [comment]
yea it has gotten pretty bad.  markdown is especially broken in hierarchy view.
really needs a makeover, here are some ideas to improve it: https://github.com/twosigma/beaker-notebook/issues/470

related: https://github.com/twosigma/beaker-notebook/issues/613
