### ISSUE TITLE
one line output is taller than one line input

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1565]
![screen shot 2015-05-06 at 11 52 17 am](https://cloud.githubusercontent.com/assets/963093/7497102/71ffad52-f3e6-11e4-8521-af8ce59d3ff7.png)

i am not 100% sure this is a problem but i don't understand why a one-line output cell is taller than the one-line input side of the same cell.  above is what i get and if you copy and paste, i see a six pixel difference:

![screen shot 2015-05-06 at 11 52 17 am](https://cloud.githubusercontent.com/assets/963093/7497221/23e32288-f3e7-11e4-8021-bae5f5a451f5.png)

**Comment by scottdraves** [comment]
btw those cells were JS.  looks like HTML cells are behaving a bit differently I have to look into that, prob an unrelated issue.

**Comment by samccone** [comment]
I agree for a single line "text" output they should be the same height, obviously as soon as there is any formatting it is going to be quite hard to ensure that they are the same height, but for "raw text" I think we can make a single line code output line up.
