### ISSUE TITLE
last line of code truncated on windows

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1574]
on windows on chrome 42.0.2311.135m and 40.0.2214.115m (at least), the very bottom of the last line of code is truncated and not visible.  this is especially bad for underscores, which appear as spaces.  
![screen shot 2015-05-07 at 2 29 55 pm 2](https://cloud.githubusercontent.com/assets/963093/7523043/f7b64434-f4c6-11e4-87ef-b347e5b29a46.png)
i suspect this was introduced with https://github.com/twosigma/beaker-notebook/commit/299d42e7789e132ee37bd25c206fc4c84a8306bc

**Comment by samccone** [comment]
on it :white_check_mark:

**Comment by scottdraves** [comment]
fixed by https://github.com/twosigma/beaker-notebook/pull/1578
