### ISSUE TITLE
Initialize ipython for more than 10 mins

### ISSUE THREAD

**Issue by liushiqi9** [twosigma/beakerx#1579]
js console :
installing keydownHandler
ipython.js:423 Using ipython compatibility mode: 3
kernel.js:435 Starting WebSockets: ws://127.0.0.1:8801/../../7dc8ced/ipython.929270749895/api/kernels/5c9e4c1f-e39f-4fc8-9b66-b6dc11116277
lookup.js:87 Initializing IP
lookup.js:87  This is a code cell.
# Click below, on the 3rd line, then type some Python code (eg "1+2"), then cl

lookup.js:87 L

ipython works fine under terminal.

**Comment by scottdraves** [comment]
Hi, thanks for the report.  Try following this instructions: https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences
especially the part about saying `which ipython` and then entering that into your prefs file.

**Comment by liushiqi9** [comment]
After I read the instruction. I changed the ~/.beaker/v1/config/beaker.pref.json into
{
  "languages" : {
    "IPython" : {
      "path" : "/usr/local/bin"
    }
  },
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : false
}
The path is from which ipython.
but I still cannot use ipython. Java R and other languages works fine.
console:
installing keydownHandler
:8801/7dc8ced/beaker/plugins/eval/ipythonPlugins/ipython/ipython.js:423 
Using ipython compatibility mode: 3
:8801/7dc8ced/beaker/plugins/eval/ipythonPlugins/vendor/ipython3/kernel.js:435 
Starting WebSockets: ws://127.0.0.1:8801/../../7dc8ced/ipython.093221804038/api/kernels/1fb2fa6d-4515-4c51-aa2d-381fd77a34ed

Also I would like to ask how to use a class I have in a .jar file in beaker. I cannot find out how to use the language management to add my class. Do you mind give me some instruction?

**Comment by scottdraves** [comment]
What is your OS version? How did you install ipython?  I think it is unlikely that /usr/local/bin is the right location... 

As for accessing a class in a jar, open the language manager and click the tab of language you want to access it from, and then put the path to the jar file (not the directory containing it) into the class path, and click "Set".  I'll add a FAQ about this: https://github.com/twosigma/beaker-notebook/issues/1590

**Comment by liushiqi9** [comment]
I am in ubuntu 14.04.2
I think I install ipython using pip
I cd into the location and use ./ipython It works fine...

My main question is what path I should put into it since the webpage basically  works on a vm(I think).

**Comment by scottdraves** [comment]
The webpage was mostly designed for Mac users and virtualenvs.  With ubuntu and pip it should be fine.  Is /usr/local/bin in your PATH?

**Comment by liushiqi9** [comment]
I unistall my ipython and intall it again use pip.
still not working.
when i run beaker on command line,try to support ipython here is what it says:
looking on stderr found:[I 11:41:20.146 NotebookApp] The IPython Notebook is running at: http://127.0.0.1:8804/
Acknowledge IPython plugin started
Done starting IPython
IPython-stderr>[I 11:41:20.352 NotebookApp] 302 POST /login?next=%2E (127.0.0.1) 1.94ms
IPython-stderr>[I 11:41:20.380 NotebookApp] Kernel started: 106c6aaf-76e7-4154-824d-bf1f5b02d1c7

then I try 8804 port, I can use ipython notebook on that port.  

And my second question about the path, I meant when I was using java in beaker what should I put in the class path in language management page since it works on a vm(I think)?

**Comment by scottdraves** [comment]
1) is /usr/local/bin in your PATH?
2) put the path to the jar into the class path field in the language manager.  there is no VM but there is a JVM.

**Comment by liushiqi9** [comment]
1> yes I put it in~/.bashrc export PATH=$PATH:/usr/local/bin
2>Thanks I will give it a try.

**Comment by scottdraves** [comment]
well i am baffled why it doesn't work -- that's how we develop beaker on ubuntu and it seems fine.  sorry.

**Comment by liushiqi9** [comment]
It's fine. I will keep trying. Thank you for your help, at least I can run my java program now!

**Comment by liushiqi9** [comment]
Two questions to follow up. 
1> What is the dynamic class directory for ?
2> When we use java to connect spark one Error pops out :
 No configuration setting found for key 'akka.version'
I wonder this is because beaker's class which is used to support java may be override my  reference.conf file or something.
Because our program works fine under intellij.
Have you met this error before?

**Comment by scottdraves** [comment]
1) the dynamic class directory is for sharing classes between the various JVM languages like Java, Groovy, Scala, and Clojure.  By default it uses a directory created specially for each notebook in ~/.beaker.  But if you want to you can set it to a location under your control, and then you can access a class defined in Beaker from an outside program.

2) The following classes are in imported by default:

```
com.twosigma.beaker.NamespaceClient
com.twosigma.beaker.chart.Color
com.twosigma.beaker.chart.xychart.*
com.twosigma.beaker.chart.xychart.plotitem.*
com.twosigma.beaker.BeakerProgressUpdate
```

You can change them with the language manager.  Given the names, I think that kind of conflict is unlikely.  I have never seen that akka error but it sounds like an issue with out the jar was made, according to this: http://stackoverflow.com/questions/27915512/akka-missing-akka-version
