### ISSUE TITLE
you can add a plugin multiple times and they come out the the same name

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#158]

**Comment by jchendy** [comment]
The resolution to this should be not allowing the plugin to be added more than once.

**Comment by scottdraves** [comment]
right.  no reason to show the name in a text field here anymore.  it should be more like a checklist.  the page for downloading and installing code from the web should be separate from where you pick which languages you are using in a notebook.  does the new design work like that?

**Comment by scottdraves** [comment]
dup of https://github.com/twosigma/beaker-notebook/issues/503
