### ISSUE TITLE
last line of output truncated on windows

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1585]
like https://github.com/twosigma/beaker-notebook/issues/1574
but on the output side

**Comment by samccone** [comment]
Currently unable to reproduce:

![screen shot 2015-05-11 at 10 15 56 am](https://cloud.githubusercontent.com/assets/883126/7566775/be58b8e0-f7c6-11e4-9558-5e11846a7ed7.png)
![screen shot 2015-05-11 at 10 15 49 am](https://cloud.githubusercontent.com/assets/883126/7566776/be5cf572-f7c6-11e4-9ce2-31f304745ba0.png)

**Comment by scottdraves** [comment]
![screencap-output-button-bug](https://cloud.githubusercontent.com/assets/963093/7566999/4726d84a-f7c8-11e4-9c60-ed2fd7237841.png)

note also the weird line over the insert cell button.  could be my 4k screen since davide does not see it.

**Comment by samccone** [comment]
@scottdraves what version of chrome are you guys in?

**Comment by scottdraves** [comment]
40.0.2214.115m

**Comment by samccone** [comment]
Unable to reproduce still

![screen shot 2015-05-19 at 11 05 03 am](https://cloud.githubusercontent.com/assets/883126/7706202/f0989f18-fe16-11e4-95c3-2a813ed7fa49.png)
![screen shot 2015-05-19 at 11 04 21 am](https://cloud.githubusercontent.com/assets/883126/7706201/f095c310-fe16-11e4-966c-f5e1c4d693ea.png)
![screen shot 2015-05-19 at 11 04 00 am](https://cloud.githubusercontent.com/assets/883126/7706203/f09ad508-fe16-11e4-8321-2ca0bd308ddc.png)

Are you zoomed in or anything?

**Comment by scottdraves** [comment]
i think this one is related to the 4k monitor, so not very important.

**Comment by scottdraves** [comment]
can't repro

**Comment by samccone** [comment]
:dancer:
