### ISSUE TITLE
cell menu stuck open

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1594]
i opened the cell menu and it does not go back down
![screen shot 2015-05-11 at 6 52 40 pm](https://cloud.githubusercontent.com/assets/963093/7576715/f150e1a8-f80e-11e4-8ca6-17d60435954b.png)
also true of advanced mode language menu

**Comment by samccone** [comment]
fixing this right now :white_check_mark:

**Comment by samccone** [comment]
Found this leak in my investigations... will fix :)

![out](https://cloud.githubusercontent.com/assets/883126/7590398/542b33fa-f896-11e4-8b39-848d4d711d2c.gif)

**Comment by samccone** [comment]
Ok @scottdraves been playing around with the language menus for a while trying to get them into a stuck state and am currently unable to do so.

![out](https://cloud.githubusercontent.com/assets/883126/7611831/fe7e0526-f954-11e4-8b7a-f48601ca49d2.gif)

Thoughts?
