### ISSUE TITLE
more date formats

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1599]
esp those that omit time

**Comment by ildipo** [comment]
date-time objects convert to a { type: Date, timestamp: XXX } JSON object, which is displayed by:
- a Date display type (for a single cell)
- a field in datatabletable

currently time object and date objects are not explicitly handled.
What do you want for this issue?

1) provide different formatting options for the DateTime object we do have today
- and/or -

2) provide new Time and OnlyDate object serialization and auto-translation along with their display types?

**Comment by scottdraves** [comment]
I mean in table options -> cell formatting -> display type, if you have a time object, right now you can only display it as "time", "string", or "html".  time and string are identical.  html is broken (shows [object object]).  this issue proposes adding say "date" for "2015-06-17".  Further than that, would need a format string to pass to moment.format.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1780
