### ISSUE TITLE
Julia kernel name

### ISSUE THREAD

**Issue by sharingtom** [twosigma/beakerx#1602]
To make Beaker find the Julia kernel I had to change its name from "julia 0.3" to "julia-0.3" on line 75 in \config\plugins\eval\ipythonPlugins\julia.js. Not sure if this is the case for other operating systems as I have yet to try it on Linux.

Windows 8.1
Beaker Notebook 1.2.1
iPython Notebook/Jupiter 3.1.0
Julia 0.3.8

**Comment by samccone** [comment]
Thanks for the report @sharingtom

**Comment by scottdraves** [comment]
thanks.  looks like they changed the name from 0.3.7 to 0.3.8.
we'll have to come up with a more robust mechanism, prob query the server for available kernels.

**Comment by sharingtom** [comment]
I'm fairly certain I had the same problem with 0.3.3, which I was running when I first got Beaker. Ended up upgrading to 0.3.8 before realizing what the problem was.

The only reason I figured it out was that when I started Jupiter/iJulia through Anaconda (to see if Julia worked at all) I saw the that kernel name in the URL had a hyphen.

**Comment by scottdraves** [comment]
ah ok then maybe a windows thing?

On Wed, May 13, 2015 at 1:51 PM, sharingtom notifications@github.com
wrote:

> I'm fairly certain I had the same problem with 0.3.3, which I was running
> when I first got Beaker. Ended up upgrading to 0.3.8 before realizing what
> the problem was.
> 
> The only reason I figured it out was that when I started Jupiter/iJulia
> through Anaconda (to see if Julia worked at all) I saw the that kernel name
> in the URL had a dash.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twosigma/beaker-notebook/issues/1602#issuecomment-101758384
> .

## 

BeakerNotebook.com
ScottDraves.com http://www.ScottDraves.com
@Scott_Draves http://twitter.com/scott_draves

**Comment by scottdraves** [comment]
We should hit the api/kernelspecs endpoint, it returns JSON with a list.  By default should just take most recent version, but really all the ipy plugins should allow user to override and select exact kernel implementation.  presumably this would go in the beaker.pref.json file.

**Comment by scottdraves** [comment]
Until then, maybe a FAQ for Julia on Windows?

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/commit/753cc9e8c037a721659e851a69b9930096872798

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1778

**Comment by scottdraves** [comment]
updated the name of julia but still need to make it autodetect

**Comment by scottdraves** [comment]
autodetecting jupyter backends should be part of the https://github.com/twosigma/beaker-notebook/wiki/Refactoring don't need an extra issue
