### ISSUE TITLE
redesign the page layout of the tutorial index

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1604]
this has gone from bad to worse
![screen shot 2015-05-13 at 10 18 47 am](https://cloud.githubusercontent.com/assets/963093/7612589/cc44a4b6-f959-11e4-84a9-3dbb737da1f5.png)

**Comment by samccone** [comment]
Thoughts on something like this?

![screen shot 2015-06-16 at 3 42 28 pm](https://cloud.githubusercontent.com/assets/883126/8192767/782c2552-143e-11e5-9cf7-b06c4d20b53b.png)
