### ISSUE TITLE
plot legend merge matching lines

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1616]
if the displayName of two lines are the same, then their legend lines should be merged and a single checkbox toggles them both.

**Comment by mnavasiolava** [comment]
and what about the color and outline color of legend item? usually they correspond to line’s color. 
![image](https://cloud.githubusercontent.com/assets/12935591/8937899/e974025c-3563-11e5-8dd7-77c70b1803a2.png)

and with LOD hints. should we apply LOD type changes to all lines with the same name? 
![image](https://cloud.githubusercontent.com/assets/12935591/8937906/f3853ec8-3563-11e5-900b-9b11823529d0.png)

**Comment by scottdraves** [comment]
1) only merge them if the color is the same.
2) yes
