### ISSUE TITLE
need a source map for our JS

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1619]
so we get more informative traces than this:
https://github.com/twosigma/beaker-notebook/issues/1618

**Comment by samccone** [comment]
:+1: I will add one to the gulp task

**Comment by samccone** [comment]
Just to be extra clear you would like this when the source code is compiled down into the two main JS files (vendor and beakerApp.js)

**Comment by scottdraves** [comment]
Yes beakerApp.js and beakerVendor.js please
