### ISSUE TITLE
Support writing JS in ES6

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1625]
I think it would be a pretty neat ability to write in ES6 much like http://babeljs.io/repl/
Not sure if the core user base would appreciate this, however I think it would be a nice to have feature, and people in the JS community would find it quite nifty.

**Comment by scottdraves** [comment]
this is a good idea but not a priority yet.

**Comment by ei-grad** [comment]
+1 to babeljs support

**Comment by scottdraves** [comment]
is this something we could drop in for eval() that just takes an extra parameter that could be set from the language manager?  i couldn't find an api for it.

**Comment by tomca32** [comment]
We can compile it to es5 before passing it to eval using something like https://github.com/Daniel15/babel-standalone

**Comment by tomca32** [comment]
Looks simple enough:

```
Babel.transform(input, { presets: ['es2015'] }).code;
```

Then we simply feed this to eval.

**Comment by tomca32** [comment]
OK pushed something to tom/1625 branch, seems to work.

Try something like:

```
var lambda = (x) => x * 2;
lambda(2);
```

**Comment by scottdraves** [comment]
that's awesome!

but it really should be an option to switch back to plain old eval, can you add radio button set to the spec for JS to allow user to choose ECMAScript 5 or 6?  default can be 6.
