### ISSUE TITLE
after you open a notebook, should be able to scroll it

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1627]
with the page down or arrow down.

**Comment by samccone** [comment]
This works for me, what are you seeing?

**Comment by scottdraves** [comment]
i have to click on the page to be able to scroll.

**Comment by scottdraves** [comment]
wait it's gone.  huh.  oh well.

**Comment by samccone** [comment]
:grapes:

**Comment by scottdraves** [comment]
OK i finally get this one.  you don't have to click.  but the first time you hit page-down (or space bar), then it's ignored.  2nd time you hit the key, then it scrolls.
