### ISSUE TITLE
github branch clean up

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#164]
Here are the branches I vote 'to delete':

[ubuntu](https://github.com/twosigma/beaker-notebook/tree/ubuntu)
[google-analytics](https://github.com/twosigma/beaker-notebook/tree/google-analytics)
[hotfix](https://github.com/twosigma/beaker-notebook/tree/hotfix)
[hotfix-141](https://github.com/twosigma/beaker-notebook/tree/hotfix-141)
[ubuntu-dev](https://github.com/twosigma/beaker-notebook/tree/ubuntu-dev)
[major-refactoring](https://github.com/twosigma/beaker-notebook/tree/major-refactoring)
[major-refactoring-p1-backend](https://github.com/twosigma/beaker-notebook/tree/major-refactoring-p1-backend)
[major-refactoring-p2-repo-sep](https://github.com/twosigma/beaker-notebook/tree/major-refactoring-p2-repo-sep)
[recent-menu](https://github.com/twosigma/beaker-notebook/tree/recent-menu)
[section-cell](https://github.com/twosigma/beaker-notebook/tree/section-cell)
[fix-ipython-autocomplete](https://github.com/twosigma/beaker-notebook/tree/fix-ipython-autocomplete)
[open-ipython-nb](https://github.com/twosigma/beaker-notebook/tree/open-ipython-nb)
[menu-plugin](https://github.com/twosigma/beaker-notebook/tree/menu-plugin)

Here are the branches I vote 'keep'
[windows](https://github.com/twosigma/beaker-notebook/tree/windows)
[release-redact](https://github.com/twosigma/beaker-notebook/tree/release-refact)
[dev-refact-evaluator-managers](https://github.com/twosigma/beaker-notebook/tree/dev-refact-evaluator-managers)
[dev-refact-file-open](https://github.com/twosigma/beaker-notebook/tree/dev-refact-file-open)
[win-dev](https://github.com/twosigma/beaker-notebook/tree/win-dev)
[beaker-conf](https://github.com/twosigma/beaker-notebook/tree/beaker-conf)
[e2e-test](https://github.com/twosigma/beaker-notebook/tree/e2e-test)
[dropbox-support](https://github.com/twosigma/beaker-notebook/tree/Dropbox-support)

For other not mentioned branches, i have no opinion.

**Comment by scottdraves** [comment]
done
