### ISSUE TITLE
markdown button flow-around triggers too often

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1643]
The way markdown formats it should flow around the cell menu in the upper-right.  It does, but it looks like more than just the 1st line is truncated.  It looks like it generates an extra block of negative space for every paragraph in fact.  Just looking at the first cell of the main tutorial you can see the 2nd paragraph 1st line wraps too soon, after "variety of" even though "languages" would fit:
![screen shot 2015-05-19 at 5 42 34 pm](https://cloud.githubusercontent.com/assets/963093/7714724/ff75aa02-fe4e-11e4-8d12-c7aadaaa10d0.png)
If you select the text you can see unwanted negative space blocking it there:
![screen shot 2015-05-19 at 5 44 02 pm 2](https://cloud.githubusercontent.com/assets/963093/7714746/4300c34c-fe4f-11e4-9bbc-7bbca58bf6f5.png)

**Comment by samccone** [comment]
I think it might just be that text you posted ^

![screen shot 2015-05-20 at 4 11 25 pm](https://cloud.githubusercontent.com/assets/883126/7735520/be40d8f0-ff0b-11e4-8d39-c61fe1b33602.png)

I created a manual test case with long non breaking strings of "s" and it seems like it has no problem filling in the space.

......

I then conducted a test to see if the elements are filling in and breaking correctly 

![screen shot 2015-05-20 at 4 23 24 pm](https://cloud.githubusercontent.com/assets/883126/7735672/9daab704-ff0c-11e4-92ee-06c33ef33813.png)

It seems like there are.

---

Would you like for me to drop the right padding to make it closer to the right edge?

**Comment by scottdraves** [comment]
OK that's the main fix but because the margin got reduced, the text is now overflowing into the menu area just a bit.  you can see the last "a" is gray and too close to the trash can.

**Comment by scottdraves** [comment]
![screen shot 2015-05-21 at 10 15 16 am](https://cloud.githubusercontent.com/assets/963093/7750517/b1f0a296-ffa2-11e4-9fe5-3c4a8b2f445e.png)
