### ISSUE TITLE
make tutorials read-only

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#166]

**Comment by anglee** [comment]
This has been addressed in the release-refact branch. I will close this issue after the branch is merged to master and tested to ensure it works.
https://github.com/twosigma/beaker-notebook/blob/release-refact/core/src/main/web/plugin/menu/help.js#L33
https://github.com/twosigma/beaker-notebook/blob/release-refact/core/src/main/web/js/module/bkHelper.js#L57

**Comment by scottdraves** [comment]
will that work for the R and Groovy tutorials, or just the main one?

**Comment by melmac48** [comment]
@anglee any update on this?

**Comment by anglee** [comment]
The main tutorial should be opened as read-only now. Other tutorials still need work.

**Comment by melmac48** [comment]
add a read only flag to the url
