### ISSUE TITLE
Default notebook contains fake settings for JavaScript

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#167]
https://github.com/twosigma/beaker-notebook/blob/master/core/config/default.bkr#L25  

```
"jsSetting2": "",
"jsSetting1": ""
```

Presumably those are an artifact of some plugin testing we did long ago?

**Comment by samccone** [comment]
seems to be resolved

https://github.com/twosigma/beaker-notebook/blob/master/core/config/default.bkr#L34-L44

**Comment by scottdraves** [comment]
no jsSetting1 and 2 are right there.

**Comment by samccone** [comment]
oh nm nm I was looking at a different spot for that text :+1:

**Comment by scottdraves** [comment]
also remove from:
./core/src/main/web/plugin/evaluator/javaScript.js
./core/src/main/web/plugin/menu/file_ipython.js
./core/src/main/web/app/utils/notebookversionmanager_test.js
