### ISSUE TITLE
show hierarchy shows too much

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1675]
there are sub-numbers on every cell, not just on the sections.

**Comment by scottdraves** [comment]
![screenshot - 05272015 - 09 57 05 pm](https://cloud.githubusercontent.com/assets/963093/7851322/97c1ece0-04bb-11e5-968b-0449dfcd9aab.png)

**Comment by scottdraves** [comment]
related https://github.com/twosigma/beaker-notebook/issues/470

**Comment by samccone** [comment]
The initial design looked like this:

![screen shot 2015-06-01 at 11 27 26 am](https://cloud.githubusercontent.com/assets/883126/7916343/3efd658c-0851-11e5-94b0-017040b183b4.png)

---

Would you like to drop the hierarchy label on all non section cells?

**Comment by scottdraves** [comment]
yes

**Comment by samccone** [comment]
:+1:
