### ISSUE TITLE
expand variables from notebook namespace in markdown

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1692]
it would be cool if in a markdown cell ${x} got expanded to beaker.x, that way in prose i could refer to values calculated by the notebook, and have them updated automatically.

**Comment by samccone** [comment]
oh wow that would be really cool

**Comment by scottdraves** [comment]
I am thinking syntax should be {{x}} since $ would be confusing with LaTeX.

Then x could resolve to beaker.x, but why not generalize this and let x be
any JS expression?  Then you could say {{beaker.x}} or you could say {{somefun()}}
or {{beaker.x.toFixed(3)}}.

the value returned by the JS would be substituted before markdown parsing.
