### ISSUE TITLE
Cannot save notebook or backup session due to nginx issue 

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#17]
To reproduce, open a new notebook and add a Python cell with the following content:

```
from pylab import *
import matplotlib.pyplot as plt
x = linspace(0, 5, 10)
y = x ** 2
figure() 
plot(x, y, 'r') 
xlabel('x')
ylabel('y') 
title('title')
show()
```

then try to save.

The Chrome console shows that the save request response with 500 server internal error.
Note that before evaluating the code cell or after evaluation, delete the output cell, the notebook saves fine. Only when the output cell appears (a PNG), the notebook file saving fails.

**Comment by anglee** [comment]
It looks like the bigger the content body, the more likely save fails. But the limit is not fixed. Also if manually invoke the saving (by sending HTTP requests), when the frequency is high, even saving with small content body fails

**Comment by scottdraves** [comment]
i can't reproduce this but it looks like our installation of nginx doesn't have client_body_temp_path set.

**Comment by anglee** [comment]
Upon further investigating with nginx debug logging turned on, when it fails, nginx prints error about client_body_temp directory permission denied:
![image](https://f.cloud.github.com/assets/1767921/2034434/13d2ad28-892b-11e3-80a8-719fd0bc149b.png)
