### ISSUE TITLE
Strange boxes in shared notebook

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#170]
http://sharing.beakernotebook.com/gist/anonymous/11158489

Mouse over the text and you'll see this

![screen shot 2014-04-21 at 6 15 56 pm](https://cloud.githubusercontent.com/assets/1740497/2759549/2965ae0c-c9a3-11e3-9dd6-3f3d630f714b.png)

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-sharing-server/commit/65e7f655d35d2fe125d6e63683719b5531c6abeb
