### ISSUE TITLE
Edit notebook title by clicking it

### ISSUE THREAD

**Issue by sabraham** [twosigma/beakerx#1704]
Please allow for editing the notebook title by clicking the the tile beside "Beaker" in the top header.

**Comment by scottdraves** [comment]
That's an interesting idea.  It's not just a title though it's actually the file name, so if you change it, that would mean saving the notebook to a new file, is that what you want?  If you click it, we could just bring up the save as dialog...

**Comment by sabraham** [comment]
Hm, I see. For me, I'm not thinking about the notebooks as files -- they're their own entity. Really I would rather Beaker abstract the file handling from me initially -- e.g., self manage files in a .beaker folder or something, and then when I want to export a file, let me save it as whatever I wanted to call it.

**Comment by scottdraves** [comment]
I appreciate what you are saying and we might get there some day, but currently we are sticking with files.
