### ISSUE TITLE
Default to new row creation when moving down to a row that doesn't exist

### ISSUE THREAD

**Issue by sabraham** [twosigma/beakerx#1705]

**Comment by scottdraves** [comment]
Thanks for the feedback.  Do you mean when you are editing a code cell, and you press the down arrow key to move to the next row, but you are in the last row, then it should create a new row instead of moving to the next cell?

**Comment by sabraham** [comment]
That would be ok. I meant when I "move up" / "move down" through the shortcuts "ctrl-alt-up" / "ctrl-alt-down"

**Comment by scottdraves** [comment]
those keys move the current cell up and down in the list of cells in the notebook.
you want that you create a new cell sometimes?  perhaps i am confused...
