### ISSUE TITLE
Section title editing breaks onto a new line

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1708]
When you click on a title that fits on a single line, it sometimes breaks onto two lines.

![screen shot 2015-06-04 at 3 46 16 pm](https://cloud.githubusercontent.com/assets/883126/7993095/c8c84fa2-0ad1-11e5-8273-e1aca5c151f7.png)

It should not do this.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1819
