### ISSUE TITLE
Wrong font in shared notebook

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#171]
Export is on the left, Beaker is on the right. Somehow certain pieces of text are rendered in a serif font.

![screen shot 2014-04-21 at 6 19 04 pm](https://cloud.githubusercontent.com/assets/1740497/2759562/78b30d74-c9a3-11e3-916e-ae1837965566.png)

**Comment by anglee** [comment]
I think this has already been fixed by @scottdraves (https://github.com/twosigma/beaker-sharing-server/commit/65e7f655d35d2fe125d6e63683719b5531c6abeb)

**Comment by jchendy** [comment]
Confirmed I'm seeing it correctly now.
