### ISSUE TITLE
too much chrome / margins

### ISSUE THREAD

**Issue by sabraham** [twosigma/beakerx#1713]
there is way too much space between cells and borders -- I would like/should be able to have twice as many lines of code on the screen as I currently do

**Comment by scottdraves** [comment]
did you try advanced mode?

**Comment by sabraham** [comment]
oh no. that's definitely better! still would like way to make change font size / reduced spacing between cells -- but right now it's workable

**Comment by samccone** [comment]
@sabraham is there a notebook style editor that you like the spacing on?

**Comment by scottdraves** [comment]
thanks!  but you are not alone in asking for more...
we will definitely keep thinking about improving the density.

**Comment by scottdraves** [comment]
we did this
