### ISSUE TITLE
fix first column of table output 

### ISSUE THREAD

**Issue by sabraham** [twosigma/beakerx#1715]
a la ngrid https://github.com/twosigma/ngrid does.

ie, when browsing the output of a table, I would like to be able to fix the first column, so when I browse right, the leftmost column stays fixed; if the column/s that stayed fixed were configurable, that would be really awesome

**Comment by scottdraves** [comment]
thanks for the report, i totally agree,it's on the agenda but i believe there was a bug in the implementation in the underlying library.

the code that activates it is commented out:
https://github.com/twosigma/beaker-notebook/blob/5d1d9ab82421ee555553d25032e98bf401d5c053/core/src/main/web/outputdisplay/bko-tabledisplay/bko-tabledisplay.js#L734

we should check if it's fixed, we are using 1.10.5 but they are up to 1.10.7
https://datatables.net/download/index

**Comment by scottdraves** [comment]
also the FixedColumn plugin is up to v3.0.4 when we are using v3.0.3
