### ISSUE TITLE
Problems closing sessions when running beaker-notebook via Dockerfile.

### ISSUE THREAD

**Issue by mforsyth** [twosigma/beakerx#1729]
I tested using the prerelease version, using the standard launch command "docker run -p 8800:8800 -t beakernotebook/beaker-prerelease".

You can open and create notebooks fine... however, when closing a notebook with an ipython3 cell you get this:  
DELETE https://10.10.10.10:8800/a66a03f/ipython.908022001784/api/kernels/bc24ca4f-b224-4c04-93a4-729a4579c34b 404 (Not Found)
From that point forward, the following error is printed out to the console once per minute, forever:
Uncaught Error: kernel is not connected

**Comment by mforsyth** [comment]
(similar problem with a node cell)

**Comment by samccone** [comment]
can you reproduce this outside of docker?

**Comment by mforsyth** [comment]
Nope, it only happens in docker.
