### ISSUE TITLE
table output broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1738]
ReferenceError: moment is not defined
    at Array.<anonymous> (:8801/fdadf68/beaker/app/dist/beakerOutputDisplay.js:27)

 https://github.com/twosigma/beaker-notebook/commit/7daabc0c5f59e4db0f52e58c2c99e559d2231611

**Comment by samccone** [comment]
Well that is odd, @scottdraves do you have a sample code cell that will kick this error?

**Comment by scottdraves** [comment]
the javascript tutorial.

**Comment by samccone** [comment]
kk shall get this one fixed asap

**Comment by scottdraves** [comment]
i remembered there was something funky about moment but i thought it was in the plots which i tested. i forgot about the tables, my bad.

**Comment by scottdraves** [comment]
perhaps it should go in its own directory, like it was, but with a different name from "vendor" so vendor is easier to keep in sync with the zip file.

**Comment by scottdraves** [comment]
thx

**Comment by scottdraves** [comment]
can't repro here at work

**Comment by samccone** [comment]
ok I just tested and everything seems to be ok on my side.
