### ISSUE TITLE
Sort a time column in datatable is broken 

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#1741]
If you have a column with type 'time' you cannot sort it.
Use test/testnotebook/timeDisplayTest - first cell output.

**Comment by samccone** [comment]
:warning:  Sorting is indeed no longer working

---

~~Seems to be working OK on my system:~~

![screen shot 2015-06-12 at 10 32 01 am](https://cloud.githubusercontent.com/assets/883126/8132243/49c0d92c-10ee-11e5-9062-8ba33e5e18a4.png)

~~do you have any JS errors?~~

related #1738
