### ISSUE TITLE
Document the list of modules needed for python to work properly

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#1751]
sudo easy_install ipython
sudo easy_install pyzmq
sudo easy_install jinja2
sudo easy_install tornado
sudo easy_install jsonschema
sudo easy_install pandas

**Comment by scottdraves** [comment]
if you don't use anaconda then you need to install these manually

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/commit/1ef7458

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/wiki/Using-a-Preexisting-Python

maybe the FAQ should point here.
