### ISSUE TITLE
Can open same notebook multiple times

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1766]
#### How to reproduce:
- Create a new notebook
- Save it 
- Open it from Recent notebooks
- Return to the dashboard, reopen the same notebook from open recent

(repeat the last two steps)

![screen shot 2015-06-17 at 9 40 56 am](https://cloud.githubusercontent.com/assets/883126/8208327/0fe4b814-14d5-11e5-983d-b9669775a371.png)

---
#### What is expected

The same notebook is not open multiple times

**Comment by scottdraves** [comment]
This is a general problem that you can open the same notebook multiple times, and you end up editing the same file in different windows.

while it might be hard to exactly always determine if two paths resolve to the same file, we should be able to easily check if we already have open the same exact path.

and on unix we can compare inodes.

**Comment by scottdraves** [comment]
In the electron version if you try to open the same file twice it should just bring the window with the already-open notebook to the front.  in the web version, that's not possible, so instead can issue a warning dialog.

**Comment by scottdraves** [comment]
so if we ever open a notebook that is already open we should warn the user "This notebook is already open in another window.  Do you want to deactivate the other window?" and if they say "no" then just open the start page instead.  if they say yes, then open as normal but server should disconnect the other window.  The other window then gets a popup that says "This notebook was opened in another window, and has been disconnected."  Then you can reconnect or download a copy.  
the server already pushes all open/close events to the start page at least, so any page could subscribe.

if we can actually force the other window to close then we should consider it.
i am not aware that you can force a tab to pop to the front but if possible we should consider it.

**Comment by sshkalikov** [comment]
we can close browser window with simple `window.close()` call
forcing a tab to pop to the front is not so easy.. actually the only solution i've found so far is to call `alert()` - this makes the tab active, but alert window is too ugly.

**Comment by scottdraves** [comment]
if i call window.close() i get: `Scripts may close only the windows that were opened by it.`
i think users might be surprised also, so just disconnecting them and having a popup is my preferred plan.
