### ISSUE TITLE
autocomplete broken in the middle of a line

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1773]
in ipython if you put the cursor in the middle of "import" and hit tab and return you get "importort".
in groovy it does nothing in the middle.

maybe if in the middle it should act like at the beginning and just increase indent?

just like when you select a region and tab then it increases indent.

as action at beginning and middle are the same, not middle and end.

**Comment by dela3499** [comment]
In IPython cells, I'd suggest that autocomplete be allowed in the middle of a line, as is the case for the IPython/Jupyter notebook. I often return to edit some text in the middle of line, and find autocomplete useful.

**Comment by scottdraves** [comment]
you can do it with control-space in the middle of a line.
but yea we might allow tab to work there too.
