### ISSUE TITLE
Improve notebook loading speed

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#178]
Try a large notebook such as https://raw.githubusercontent.com/gumption/Python_for_Data_Science/master/Python_for_Data_Science_all.ipynb

In Beaker, it takes ~45 seconds before anything appears and another 45 seconds before  the loading is fully complete.

For comparison, IPython loads the whole thing in ~12 seconds.

**Comment by scottdraves** [comment]
not there yet

**Comment by samccone** [comment]
@jchendy Would love to to have some feedback on how this "feels" now with the new fix that just landed

**Comment by scottdraves** [comment]
we made some improvements on this front, need to keep working on it.

**Comment by scottdraves** [comment]
dup of https://github.com/twosigma/beaker-notebook/issues/2336
