### ISSUE TITLE
sharing server needs to be updated

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1787]

**Comment by ildipo** [comment]
Test notebooks:
- text tutorial: http://sharing.beakernotebook.com/gist/anonymous2/65177cadec4ef5c1544f
- javascript tutorial http://sharing.beakernotebook.com/gist/anonymous2/feb14b2b193ddbde1d7c
- R tutorial http://sharing.beakernotebook.com/gist/anonymous2/f8e142ff22be3336c98e
- forms tutorial http://sharing.beakernotebook.com/gist/anonymous2/7464c6e16ffb7b146d9a
- progress reporting (while running) http://sharing.beakernotebook.com/gist/anonymous2/aadfe036a2418ba17007

**Comment by ildipo** [comment]
Completed. Submitted PR to beaker and beaker-sharing-server

**Comment by scottdraves** [comment]
thanks, still needs to be deployed.
