### ISSUE TITLE
Require JRE instead of JDK for end users

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#179]
The CLI aliases we use to launch our Java app don't get updated by a JRE install/upgrade, so users have to install JDK. This process is more confusing and error prone, and is unnecessary for users who already have JRE 7. Let's see if we can eliminate the JDK dependency.

**Comment by scottdraves** [comment]
we might want to consider 1.6 as well, we use little of 1.7

**Comment by jchendy** [comment]
Yeah, it would be a big improvement for users if we could remove the 1.7 dependency.

**Comment by scottdraves** [comment]
on mac to make it work with JRE instead of JDK basically we just need to do
export JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
in the beaker.command script

**Comment by scottdraves** [comment]
fixed on mac https://github.com/twosigma/beaker-notebook/pull/217

**Comment by scottdraves** [comment]
done on windows too
