### ISSUE TITLE
gulp fails silently, libsass is unreliable

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1798]
if there is a bug in the css, or a file is missing, or bug in the sass compiler, then
gulp fails but no error is reported.  this makes debugging extremely difficult
and can result in a broken product.  furthermore, some commonly used
gulp tasks like removing comments are broken.

we should look into replacing gulp.

**Comment by scottdraves** [comment]
gulp causes too many problems.  right now i can't build on ubuntu because in core:

```
$npm run-script compile
...
Error: Cannot find module 'util-deprecate'
```

**Comment by scottdraves** [comment]
https://github.com/nodejs/readable-stream/issues/103
and yet it's still broken but why only on ubuntu?

**Comment by scottdraves** [comment]
This really confused someone today:

[23:06:05] Using gulpfile ...../core/gulpfile.js
[23:06:05] Starting 'compile'...
[23:06:05] Starting 'compileBeakerScss'...
^G src/main/web/app/vendor.scss
  27:9  file to import not found or unreadable: ../vendor/bower_components/bootstrap-sass/assets/\
stylesheets/bootstrap.scss
Current dir:
:build
:shared:assemble
:shared:compileTestJava UP-TO-DATE
:shared:processTestResources UP-TO-DATE
:shared:testClasses UP-TO-DATE
:shared:test UP-TO-DATE
:shared:check UP-TO-DATE
:shared:build

BUILD SUCCESSFUL

**Comment by scottdraves** [comment]
In general, node-sass has given us a lot of problems too.
I am concerned that it is compiling from source C++ with every clean build, for example.
Could we improve the reliability of our build by using the ruby implementation?
We also found a case where the gulp filter for removing JS comments actually removed a legit line of code.

**Comment by scottdraves** [comment]
Here's libsass getting compiled by our build (on mac):

```
> node-sass@0.9.6 install /Users/spot/beaker-notebook/core/node_modules/node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/binding/binding.o
  CXX(target) Release/obj.target/binding/sass_context_wrapper.o
  CXX(target) Release/obj.target/binding/libsass/ast.o
  CXX(target) Release/obj.target/binding/libsass/base64vlq.o
```

**Comment by DiegoAlbertoTorres** [comment]
Additionally, there is a problem with building node-sass on Windows: http://stackoverflow.com/questions/14278417/cannot-install-node-modules-that-require-compilation-on-windows-7-x64-vs2012.
MSVS has to be installed, and MSVS is huge and takes ages to install.

**Comment by scottdraves** [comment]
Building our container:

```

> node-sass@0.9.6 install /home/beaker/src/core/node_modules/node-sass
> node build.js

`linux-x64-v8-3.14` exists; testing


  ??????????????????????????????????????????????????????????????????????????????

  26 passing (61ms)

Binary is fine; exiting
npm ERR! cb() never called!
npm ERR! not ok code 0
:dev:core:npmInstall FAILED
:build FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:npmInstall'.
> Process 'command 'npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by samccone** [comment]
One solution for the sass problem would be to switch over to stylus. The stylus compiler is implemented in pure JS and thus does not have to do any native compilation (which has been the root of the issue with sass)

Since stylus is **very** close to sass we should be able to automatically port all of our styling rules.
We are using bootstrap sass, however there is a 1:1 port for stylus https://github.com/maxmx/bootstrap-stylus :ok_hand: 

@Los83 and I actually created a tool to port sass to stylus a year or so ago :palm_tree: 

http://sass2stylus.com/
https://github.com/mojotech/sass2stylus

This might be a decent first step!

**Comment by scottdraves** [comment]
yet another mysterious failure.  deleting node_modules and rebuilding fixed it.

```
:dev:core:compileAssets

> beaker@0.0.0 compile /Users/spot/qulix/beaker-notebook/core
> gulp compile

/Users/spot/qulix/beaker-notebook/core/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148
    throw new Error(['`libsass` bindings not found in ', binaryPath, '. Try re
          ^
Error: `libsass` bindings not found in /Users/spot/qulix/beaker-notebook/core/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64\
-14/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/Users/spot/qulix/beaker-notebook/core/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148:\
11)
    at Object.<anonymous> (/Users/spot/qulix/beaker-notebook/core/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/spot/qulix/beaker-notebook/core/node_modules/gulp-sass/index.js:163:21)
    at Module._compile (module.js:460:26)
```

**Comment by scottdraves** [comment]
i am leaning towards ruby sass over stylus.  seems to be a much more well-trod path.  and though i am no fan of ruby, its main weaknesses (memory, performance, and security) would not come into play as a build step.

it still leaves open the question of what to do about gulp, though maybe just replacing libsass is enough.

**Comment by scottdraves** [comment]
biting again, this time on windows.  a developer gets these build errors:

```
d:\projects\beakernotebook\beaker-notebook\core\node_modules\node-sass\libsass\sass_interface.h(4): fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory [D:\projects\Bea
kerNotebook\beaker-notebook\core\node_modules\node-sass\build\binding.sln]
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [D:\projects\BeakerNotebook\beaker-notebook\core\node_modules\node-sass\build\binding.sl
n]
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [D:\projects\BeakerNotebook\beaker-notebook\core\node_modules\node-sass\build\binding.sln]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [D:\projects\BeakerNotebook\beaker-notebook\core\node_modules\node-sass\build\binding.sln]
..\libsass\prelexer.cpp(65): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const ' [D:\projects\BeakerNotebook\beaker-notebook\core\node_modules\node-sass\build\binding.sl
n]
..\libsass\prelexer.cpp(65): error C2973: 'Sass::Prelexer::exactly' : invalid template argument 'char' [D:\projects\BeakerNotebook\beaker-notebook\core\node_modules\node-sass\build\binding.sln]
..\libsass\prelexer.cpp(65): error C2563: mismatch in formal parameter list [D:\projects\BeakerNotebook\beaker-notebook\core\node_modules\node-sass\build\binding.sln]
```

davide found this possible fix:

> Thanks! After trying out all 3 versions of the blasted VS 2013, it turns out only one of them will get node-sass to work - VS2013 Windows Desktop. http://www.visualstudio.com/downloads/download-visual-studio-vs#d-express-windows-desktop
> May this help whoever finds this issue in the future :simple_smile:
> Download free 90-day trials of Visual Studio products, free Visual Studio Express products, and additional Visual Studio software.

it's endless

**Comment by scottdraves** [comment]
yup it's completely broken: https://github.com/dlmanning/gulp-sass/issues/236

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2539 fixes the proximate problem of libsass.  quick, let's declare victory.

**Comment by sethkrasnianski** [comment]
Regarding @samccone's [comment](https://github.com/twosigma/beaker-notebook/issues/1798#issuecomment-120925388), stylus is virtually identical and doesn't cause any headaches (like node-sass). You wouldn't really notice a difference when styling Beaker. It's a fairly quick migration. I'd be happy to give it a go if you'd like.

**Comment by sethkrasnianski** [comment]
Or alternatively, gulp-sass could be switched in favor of using [gulp-ruby-sass](https://github.com/sindresorhus/gulp-ruby-sass) which internally leverages ruby's (reliable) version instead of libsass.

**Comment by scottdraves** [comment]
we went with ruby.
still looking to replace gulp.

**Comment by sethkrasnianski** [comment]
Any ideas as to what you would like to replace it with?
Is gulp causing other problems aside from the node-sass issue?

**Comment by scottdraves** [comment]
see https://github.com/twosigma/beaker-notebook/issues/2562 for my answers and any further discussion
