### ISSUE TITLE
improve insert cell GUI

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1799]
The advanced mode insert cell GUI as it is now:
![screen shot 2015-06-20 at 8 53 06 pm](https://cloud.githubusercontent.com/assets/963093/8269912/961c1a74-178e-11e5-9433-0cd4cb2366e7.png)

as it should be: change this from 2 buttons + and v to 4: +, t, h, and v.
- \+ inserts default cell type
- t inserts as "text" (what is now called "markdown") cell
- h brings up menu of 4 heading levels,
- and v brings up a menu with just the available languages (with badges).

**Comment by samccone** [comment]
<img width="506" alt="screen shot 2015-07-31 at 11 37 36 am" src="https://cloud.githubusercontent.com/assets/883126/9011351/cbd71162-377a-11e5-9ada-e994dbb77ec9.png">

a rough draft of what I am thinking here

**Comment by samccone** [comment]
<img width="493" alt="screen shot 2015-08-03 at 11 05 58 am" src="https://cloud.githubusercontent.com/assets/883126/9040385/c7f1c702-39cf-11e5-965d-5b00a046df98.png">

**Comment by scottdraves** [comment]
looks good but: put the language menu between the + and Text menus.  make the "v" be the triangle we have now.

**Comment by samccone** [comment]
ok no problem!

**Comment by samccone** [comment]
:+1: I think this has been merged in :)

**Comment by scottdraves** [comment]
this is what we ended up with:
<img width="402" alt="screen shot 2015-10-02 at 11 13 14 pm" src="https://cloud.githubusercontent.com/assets/963093/10261215/3eb39428-695b-11e5-9f9f-b32df7d398e3.png">

and in-between cells:

<img width="224" alt="screen shot 2015-10-02 at 11 14 51 pm" src="https://cloud.githubusercontent.com/assets/963093/10261220/7710356a-695b-11e5-81f9-fcf8fcc88eb3.png">

**Comment by samccone** [comment]
:+1: i dig it
