### ISSUE TITLE
Row labels get lost when translating dataframes from Python to R

### ISSUE THREAD

**Issue by emilydolson** [twosigma/beakerx#1802]
Since both Pandas and R support row labels, it would be nice if auto-translation would handle them.

**Comment by scottdraves** [comment]
thanks, sounds like a good idea, we'll look into it.

**Comment by ildipo** [comment]
This is implemented in https://github.com/twosigma/beaker-notebook/pull/2445

**Comment by scottdraves** [comment]
Emily, if you have a small example that we can use to confirm we did what you need, please paste it here.  Thanks.
