### ISSUE TITLE
in nonadvanced mode, when you edit a markdown cell, it jumps down

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1805]
![screen shot 2015-06-21 at 4 51 00 pm](https://cloud.githubusercontent.com/assets/963093/8273312/d0e9a110-1835-11e5-9da3-d7d8cd1daf42.png)

**Comment by samccone** [comment]
related #1708

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1819
