### ISSUE TITLE
clojure crashes on the following code:

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1806]
```
Jun 21, 2015 4:57:12 PM com.twosigma.beaker.jvm.serialization.BasicObjectSerializer runConfiguredSerializers
SEVERE: exception in serialization
java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.core$fib_seq_iterative
    at clojure.lang.RT.seqFrom(RT.java:505)
    at clojure.lang.RT.seq(RT.java:486)
    at clojure.core$seq.invoke(core.clj:133)
    at clojure.core$take$fn__4270.invoke(core.clj:2626)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.LazySeq.isEmpty(LazySeq.java:171)
    at com.twosigma.beaker.jvm.serialization.BasicObjectSerializer.isListOfPrimitiveTypeMaps(BasicObjectSerializer.java:71)
```

from

```
(defn fib-step [[a b]]
  [b (+ a b)])

(defn fib-seq-iterative []
  (map first (iterate fib-step [0 1])))
(take 20 fib-seq-iterative)
```

**Comment by maksim-lauryk** [comment]
I new in Clojure, but it looks like that 'fib-seq-iterative' function in last string should be surrounded by parentheses: (take 20 (fib-seq-iterative))

![fib_seq](https://cloud.githubusercontent.com/assets/13995034/10188900/add36d8e-676b-11e5-964f-d7063d1e8c64.PNG)

**Comment by scottdraves** [comment]
the user should not be able to crash the system.
if there is an error it should be reported nicely.

**Comment by maksim-lauryk** [comment]
added a check of corrupted clojure objects.
now error message looks like that:
![clojure_obj_error](https://cloud.githubusercontent.com/assets/13995034/10214583/3f6e8d08-6822-11e5-8aef-5f8efe153aa6.PNG)

**Comment by scottdraves** [comment]
i think it should produce this:

```
#'sandbox10869/fib-step
```

but with a different namespace....
it is not an error.

**Comment by maksim-lauryk** [comment]
I tried to run this code in a REPL. It executes code line by line and #'sandbox10869/fib-step is an output for the first line. If we execute our code fully, we get the same error:
![fib_seq_err](https://cloud.githubusercontent.com/assets/13995034/10241181/3b7dedf2-68ee-11e5-9279-419ce399cb35.PNG)

**Comment by maksim-lauryk** [comment]
besides, this is namely the error of result output, when they try to show object from any string, even if string does not include a print function (println etc.)
If we simple run the code without output object from last string, the error will not appear.
the same, if we add next line after line with a problem, for example:
![fib_seq_woor](https://cloud.githubusercontent.com/assets/13995034/10242010/4691ac58-68f6-11e5-9f81-2c92c39321b9.PNG)
whereas, attempt (println (take 18 fib-seq-iterative)) gives the exception in any case, independent from place in code

**Comment by scottdraves** [comment]
This is still a bug

**Comment by maksim-lauryk** [comment]
up to date with master
such exceptions will be shown in the cell output
