### ISSUE TITLE
Create a user-friendly launcher

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#181]
Something like this would have many benefits:
- Users who didn't see the 'getting started' page won't be confused when Beaker doesn't work
- We could probably get rid of the 'getting started' page completely
- We could allow configuration of nginx location in the UI so that Windows users don't need to edit their PATH
- The URL for opening Beaker won't get lost in mountains of stdout noise
- Users won't forget that they have a server running
- Solved the issue of 'improperly' shutting down Beaker on Windows by closing the cmd window

Quick mockups:

![beaker-launcher](https://cloud.githubusercontent.com/assets/1740497/2793587/906705d4-cbe1-11e3-9753-56ddc4d71862.PNG)

**Comment by scottdraves** [comment]
so you mean this would be a zero-dependency native app on each platform?

**Comment by jchendy** [comment]
That would be ideal. We could also probably get away with a minimal-dependency app (ie something that works with Java >= 1.4) as long as there's a clear error message if that one dependency is missing.

**Comment by scottdraves** [comment]
sounds good

**Comment by jchendy** [comment]
I just saw this while installing Ubuntu. That's totally what we want for handling stdout/stderr. By default, hide it and show a user-friendly version of the current state, but keep the raw output somewhere easy to access.

![screen shot 2014-04-28 at 2 51 32 pm](https://cloud.githubusercontent.com/assets/1740497/2821441/41a0c66a-cf06-11e3-8a51-b875f5074110.png)

**Comment by scottdraves** [comment]
closing as dup https://github.com/twosigma/beaker-notebook/issues/221
