### ISSUE TITLE
CSS for language dropdown/controls broken

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#1815]
![screen shot 2015-06-22 at 11 15 49 am](https://cloud.githubusercontent.com/assets/3867399/8285250/29e368f6-18d0-11e5-8e67-f0e57425a48e.png)

**Comment by samccone** [comment]
Looks like a z-Index issue

**Comment by ildipo** [comment]
nop. z-index has no effect

**Comment by scottdraves** [comment]
try changing the opacity of something to 0.999

**Comment by scottdraves** [comment]
http://philipwalton.com/articles/what-no-one-told-you-about-z-index/

**Comment by ildipo** [comment]
Actually this was there since losing time: it is not related to bootstrap update to 3.3.5.
Bump to 1.4
