### ISSUE TITLE
uninitialized tables

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1834]
![screen shot 2015-06-23 at 10 09 30 pm](https://cloud.githubusercontent.com/assets/963093/8321549/4986ef76-19f6-11e5-88ad-822aeb3db0dc.png)
![screen shot 2015-06-23 at 10 09 41 pm](https://cloud.githubusercontent.com/assets/963093/8321552/4fb7b39e-19f6-11e5-85dc-f44749189d40.png)
from test/notebooks/groovy.bkr open and scroll down

**Comment by ildipo** [comment]
This was happening to tables inside a result display (used when there's stdout/stderr).
Opened PR to master - we must bring the commit to 1.3

**Comment by scottdraves** [comment]
i am seeing it when the table is in a section that is closed when the notebook is opened.
when the section is closed, the table is not formatted.
