### ISSUE TITLE
autotranslation types gone bad?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1836]
![screen shot 2015-06-23 at 10 11 23 pm](https://cloud.githubusercontent.com/assets/963093/8321586/ddd196ae-19f6-11e5-98e7-86b8332d5d3d.png)
![screen shot 2015-06-23 at 10 12 58 pm](https://cloud.githubusercontent.com/assets/963093/8321587/df77d6a8-19f6-11e5-8c3e-8320a689f324.png)

**Comment by ildipo** [comment]
nope this works as expected: a dict containing complex type is serialized to JSON and not displayed using the plot and image. If you want that you should return an output container

**Comment by scottdraves** [comment]
look below at the 2nd cell where just the image is extracted and returned
but display is wrong.

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by ildipo** [comment]
actually this works fine on master

**Comment by scottdraves** [comment]
if you evaluate the cell with the run button it works, but if the cell is run by beaker.evalute() then it doesn't work.
