### ISSUE TITLE
cell menu do not close when you click on another one

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#1842]
This is a regression

**Comment by samccone** [comment]
Normally a click on anywhere on the page causes the window click handler for the menus to fire and close themselves, however our good friends jquery ui and angular decided that they should prevent default on the toggle click thus killing the click event and preventing it from bubbling up to the window and thus preventing the other menus from closing.

<img width="490" alt="screen shot 2015-07-16 at 4 39 59 pm" src="https://cloud.githubusercontent.com/assets/883126/8734710/ba59f3f2-2bd9-11e5-98d6-ccacd6f8d027.png">

---

Investigating a real fix :construction:

**Comment by samccone** [comment]
If we take a look at the current implementation of the dropdown menu from bootstrap we can see that this prevent default is not actually present:

<img width="761" alt="screen shot 2015-07-17 at 9 44 00 am" src="https://cloud.githubusercontent.com/assets/883126/8748441/69a8c0fc-2c68-11e5-8dcb-f7823933845c.png">

https://github.com/twbs/bootstrap/blob/83bfff7f0765503b990b96c303eef67009e48d77/js/dropdown.js#L58-L91

The current angular port of the dropdown logic in the angular directive is from 2012, so we are quite a bit behind from how actual bootstrap works.

<img width="823" alt="screen shot 2015-07-17 at 9 51 34 am" src="https://cloud.githubusercontent.com/assets/883126/8748593/896ed236-2c69-11e5-8b29-a9e100e49a6d.png">
