### ISSUE TITLE
Control panel not notified of notebook changes

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#1852]
Notebook edits are not reflected in the control panel, thus allowing the user to close edited notebooks. This can lead to potentially disastrous code loss.

**Comment by scottdraves** [comment]
can't repro on v1.3

**Comment by DiegoAlbertoTorres** [comment]
I managed to reproduce the bug on master: 
1. Open a beaker control panel in one tab and a beaker notebook in the other.
2. Edit the notebook.
3. Switch to the control panel and close the notebook
The control panel will fail to ask if you want to keep your changes.

**Comment by DiegoAlbertoTorres** [comment]
Duplicate of #1909
