### ISSUE TITLE
javascript syntax error stack trace is bad

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1865]
![screen shot 2015-06-30 at 10 23 22 am](https://cloud.githubusercontent.com/assets/963093/8433149/0e906034-1f12-11e5-9b24-6ea55987f9bd.png)

**Comment by samccone** [comment]
@scottdraves is the goal here to never show the stack back to the beaker js vendor files?

**Comment by scottdraves** [comment]
with syntax errors there is no stack, so yea.
