### ISSUE TITLE
scala spark causes linkage error

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1867]
http://sharing.beakernotebook.com/gist/anonymous/6c7539f37aadfad9d00a

java.lang.LinkageError: loader constraint violation: when resolving method "java.lang.management.ManagementFactory.newPlatformMXBeanProxy(Ljavax/management/MBeanServerConnection;Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;" the class loader (instance of com/twosigma/beaker/jvm/classloader/JarClassLoader) of the current class, org/apache/spark/util/SizeEstimator$, and the class loader (instance of ) for the method's defining class, java/lang/management/ManagementFactory, have different Class objects for the type javax/management/MBeanServerConnection used in the signature

**Comment by syepes** [comment]
Is there currently any kind of workaround to make Spark work with Scala?

**Comment by scottdraves** [comment]
no sorry, I am baffled by the error and haven't had a chance to really dig into it yet.
maybe someone who knows spark better can help.

**Comment by syepes** [comment]
I think this must be some kind of run-time class loading issue. I have done some similar tests with Groovy and I get the same issue running it from the console. But if I compile the same code in a fatJar it works as expected.

Are there any docs on how the backend works? to try and debug this issue.
