### ISSUE TITLE
Issues with Python plugin on Linux

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#187]
Repro:

Make sure R and Rserve are not installed, and kill ~/.beaker:

Run in R:

```
remove.packages('Rserve')
```

In terminal:

```
sudo apt-get --purge remove r-base
rm -rf ~/.beaker
```

Launch Beaker and run some Python code

Reinstall R and Rserver

```
sudo apt-get install r-base
```

In R:

```
install.packages('Rserve',,'http://www.rforge.net/')
```

Now run Beaker. Python cells don't initialize.

**Comment by scottdraves** [comment]
could not reproduce on 12.04 with dev tree, trying with release zip.

**Comment by scottdraves** [comment]
ditto with 0.51-beta release zip.

**Comment by jchendy** [comment]
I tried two more times and couldn't reproduce. At least Scott saw my computer where it was happening once. :)

I unfortunately lost the error message when I restarted my VM. This is what I had from the same error a few days ago.

```
nginx-stderr>2014/04/24 17:34:50 [error] 13029#0: *176 "/home/jeff/.beaker/v1/nginx6866668021935821668/html/ipythonQkdY95/kernels/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: , request: "POST /ipythonQkdY95/kernels/?notebook=kernel.CmANy7.5461052AD5934D5186FE1F92B61B2E62 HTTP/1.1", host: "ubuntu1404:8801", referrer: "http://ubuntu1404:8801/beaker/"
```

**Comment by scottdraves** [comment]
this was that race condition or case sensitivity bug in nginx, fixed a long time ago.
