### ISSUE TITLE
ui bug: datatables bottom right border

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1874]
![screen shot 2015-06-30 at 8 04 49 pm](https://cloud.githubusercontent.com/assets/883126/8446719/6bb64926-1f63-11e5-9b46-caa7f8f8cd86.png)

the bottom right ^

spotted in https://youtu.be/e5KerO_xg1w

**Comment by scottdraves** [comment]
yup https://github.com/twosigma/beaker-notebook/issues/1439

**Comment by samccone** [comment]
:+1: sorry did not see that one :)

**Comment by scottdraves** [comment]
no worries, better to file a few dups than to miss filing
