### ISSUE TITLE
ui: should datatables column header have an arrow that toggles when you click?

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1875]
![screen shot 2015-06-30 at 8 04 49 pm](https://cloud.githubusercontent.com/assets/883126/8446738/94f3011c-1f63-11e5-9789-3bdc523021c2.png)

descending vs ascending?

**Comment by ildipo** [comment]
Yes they should, but...
Why are you still seeing the old data table? This is outdated.

**Comment by scottdraves** [comment]
current code has arrows
