### ISSUE TITLE
ui bug: datatable alignment seems off by one initially

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1877]
![screen shot 2015-06-30 at 8 15 13 pm](https://cloud.githubusercontent.com/assets/883126/8446846/cf497a34-1f64-11e5-8c06-7a215a463289.png)

**Comment by ildipo** [comment]
Why are you still seeing the old data table? This is outdated.

**Comment by scottdraves** [comment]
it's a screencap from the video of the SparkR presentation a couple of weeks ago so it has the old table.
i think the bug is in the current code too though.
seem pretty minor though, does not appear to grow with the columns.

**Comment by samccone** [comment]
this off by one issue looks like only when a user is zoomed in, going to close as a non issue.
