### ISSUE TITLE
beakerVendor.js is large enough to cause significant slowdown when using Beaker over the internet.

### ISSUE THREAD

**Issue by mforsyth** [twosigma/beakerx#1879]
It's currently at about 10MB, and it contains, among other things, Angular, so it would be difficult to render anything meaningful until it's fully downloaded.

The majority of the file appears to consist of some sort of base64 encoded binary content (sourcemaps, or something along those lines?)

**Comment by samccone** [comment]
Ok, I think that we can put a pretty simple fix in for this. As you stated, the end of the file looks like binary content, that content is the inline source-maps for our JS. For the normal build of beaker we should be able to use external sourcemaps which will only be downloaded if someone opens dev tools.

This should trim us down quite a bit. 

thoughts @spot ?

**Comment by scottdraves** [comment]
an external source map sounds good, yes please.
