### ISSUE TITLE
text selection is opaque

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1884]
![screen shot 2015-07-02 at 10 19 25 am](https://cloud.githubusercontent.com/assets/963093/8479255/7825b006-20a4-11e5-9b1f-e71659b3abe2.png)

**Comment by samccone** [comment]
on it :goat:

**Comment by samccone** [comment]
This broke in:
https://github.com/twosigma/beaker-notebook/pull/1837/files#diff-2314905bb6a414a883c230a7a0e9934fR28

codemirror inlines a z-index which is causing problems:
https://github.com/codemirror/CodeMirror/commit/e1727acbd2f703811f1332efa5cbb5b619d4c4ef

---

I have a fix for us, just wanted to identify the origin on both fronts
