### ISSUE TITLE
Add new cell perf

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1885]
There currently is a tangible delay between clicking on new cell and when the new cell actually shows up in the notebook. 

![screen shot 2015-07-02 at 11 35 23 am](https://cloud.githubusercontent.com/assets/883126/8480990/e3186ed0-20ae-11e5-9f53-eb36fd56096d.png)

![screen shot 2015-07-02 at 11 43 43 am](https://cloud.githubusercontent.com/assets/883126/8481163/a1c45e98-20af-11e5-9515-1dd82cae7b72.png)

The time to show significantly increases as your notebook gets larger and larger. On small notebooks it is almost happening within the 40ms however as the notebook grows it quickly can take upwards of 200ms to insert a new cell. 
##### measure patch

``` patch
diff --git a/core/src/main/web/app/mainapp/components/notebook/codecell.jst.html b/core/src/main/web/app/mainapp/components/notebook/codecell.jst.html
index 7954435..b9cc191 100644
--- a/core/src/main/web/app/mainapp/components/notebook/codecell.jst.html
+++ b/core/src/main/web/app/mainapp/components/notebook/codecell.jst.html
@@ -46,6 +46,11 @@
             evaluator-id="{{ cellmodel.evaluator }}"
             cell-id="{{ cellmodel.id }}">
       </bk-code-cell-output>
+      <script>
+        if (window.p) {
+          console.log(performance.now() - window.p);
+        }
+      </script>
     </div>
   </div>
 </div>
diff --git a/core/src/main/web/app/mainapp/components/notebook/newcellmenu-directive.js b/core/src/main/web/app/mainapp/components/notebook/newcellmenu-directive.js
index be28be3..891745f 100644
--- a/core/src/main/web/app/mainapp/components/notebook/newcellmenu-directive.js
+++ b/core/src/main/web/app/mainapp/components/notebook/newcellmenu-directive.js
@@ -42,6 +42,7 @@
         };

         $scope.newCodeCell = function(evaluatorName) {
+          window.p = performance.now();
           var newCell = newCellFactory.newCodeCell(evaluatorName);
           attachCell(newCell);
         };
```

---

My current hypothesis is that this operation can be optimized however, the bigger offender is simply the memory overhead of the notebook causing user interactions to slow down.

**Comment by scottdraves** [comment]
thx for collecting that info
