### ISSUE TITLE
the JSON plot API is broken in python

### ISSUE THREAD

**Issue by jthornbrue** [twosigma/beakerx#1889]
In an IPython cell, define the following data:

``` python
beaker.myPlot = {'type': 'Plot', 'data': [{'elements': [{'x': 1, 'y': 1}, {'x': 2, 'y': 2}, {'x': 3, 'y': 1}]}]}
```

Now, in another IPython cell, try:

``` python
beaker.myPlot # this results in an empty plot (no data on axes)
```

But, it works in a JavaScript cell:

``` javascript
beaker.myPlot // this renders the plot as expected
```

**Comment by scottdraves** [comment]
Thanks for the bug report, I can reproduce it, should be straightforward to fix.

**Comment by jthornbrue** [comment]
Thanks, this will be very helpful.

James Thornbrue | jthornbrue@gmail.com | 858.231.2357

**Comment by scottdraves** [comment]
this is triggering erroneously:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/ipythonPlugins/src/dist/ipython/beaker_runtime.py#L143

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2449
