### ISSUE TITLE
electron mac app needs to be signed

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1896]

**Comment by DiegoAlbertoTorres** [comment]
Done! Will add signing to gradle script

**Comment by DiegoAlbertoTorres** [comment]
Gradle now signs the app: f4e68e9462a94eeb869c53bbfc104245b60cc3f9

**Comment by scottdraves** [comment]
needs to be conditional so no error in case of missing cert

**Comment by DiegoAlbertoTorres** [comment]
Certification is now conditional: 181d4e7
