### ISSUE TITLE
initialization errors not reported

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1902]
eg try opening the PySpark tutorial without having working spark installed

**Comment by DiegoAlbertoTorres** [comment]
Are you talking about the "ERROR: SPARK_HOME envar not defined" that shows up if you don't have spark? I do see it if I open the tutorial on both browser and electron (both on diego/electron branch)

**Comment by DiegoAlbertoTorres** [comment]
@scottdraves Were you able to reproduce this?

**Comment by DiegoAlbertoTorres** [comment]
Could not reproduce, the error seems to be reported correctly.
