### ISSUE TITLE
C/C++ Support

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#1908]
Notes on implementing a C/C++ plugin:

How to handle compilation? Do it all from the ground, similar to how Java is implemented, or simply create an interface to a pre-existing C/C++ interpreter such as Cling?

On Cling:
- https://root.cern.ch/drupal/content/cling
- Popular for data analysis, particularly with physicists (hence the CERN)

**Comment by scottdraves** [comment]
cool we should include the ROOT framework.

**Comment by DiegoAlbertoTorres** [comment]
I've looked a bit into what physicists prefer/are into. It seems that C++ fully replaced FORTRAN not too long ago in high energy physics. However, C++/ROOT doesn't have the favor of many beyond CERN: most other fields, like astronomy, use python (and you can interface with ROOT through pyROOT). Sounds like being able to use ROOT from python and C++ in a single notebook would be awesome.

**Comment by DiegoAlbertoTorres** [comment]
I have started development of the C++ plugin. The plan is to re-compile Cling as an embeddable library, and to then create the evaluator-backend using JNI. The reasoning for using JNI is that it will keep the server as similar as possible to the backend for other languages. The main disadvantage of using JNI instead of a Java-C++ server couple is that with JNI user code can corrupt the server's heap. However, if that happens we can reboot the server from Beaker's backend, so adding one more process for the sake of separation is not very important.
