### ISSUE TITLE
Saving on close from control panel does not save most recent changes

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#1909]
To reproduce:
1. Create new notebook
2. Create new cell, type something
3. Open control panel in different tab
4. Close the session of the notebook you created from the control panel tab
5. Accept to save changes, save to some file
6. Open file, see that the cell you created is missing

**Comment by samccone** [comment]
I am unable to reproduce these steps work for me

**Comment by samccone** [comment]
using the new instructions from @DiegoAlbertoTorres I was able to reproduce

**Comment by DiegoAlbertoTorres** [comment]
I think the control panel is using an outdated notebook model to save the notebook. Requesting the most recent model from the backend should do the trick.

**Comment by DiegoAlbertoTorres** [comment]
I am confused as to how this problem came to be. On save, the control panel simply tells the server to save the notebook. However, the control panel also gives the notebook data to the backend. Why is the backend passing notebook data? Shouldn't the backend be in charge of getting most recent data from the mainapp (notebook tab/window)?

**Comment by samccone** [comment]
@spot @ildipo how does this sound?

#### logic flow on close from the dashboard

## 1. get most recent backup

## 2. check edited state

## 2.a if edited state is true

## 2.a.1

request via WS to see if a notebook is open (it is possible this window has been closed) if the notebook is not open goto 2.b

## 2.a.2

request open notebooks contents via WS and save 

## 2.b if edited state is false

save most recent backup
