### ISSUE TITLE
electron instructions for JRE have issues

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1916]
`jdk1.7.0_55.jdk` -- please use jdk8

`Download JRE, zip it, and put it in this folder as 'jre.zip'.` this isn't complete it should say the folder has to be named "jre" before it is zipped, so that when gradle unzips it has the right name.

**Comment by scottdraves** [comment]
also seems like electron is downloaded automatically so that should be removed.

**Comment by DiegoAlbertoTorres** [comment]
Fixed in d20d000
