### ISSUE TITLE
Docker (Kitematic): nginx 400 Bad Request / Connection Refused

### ISSUE THREAD

**Issue by sharingtom** [twosigma/beakerx#1919]
When running the v1.3.1 Docker containter in [Kitematic](https://kitematic.com/) on Windows 8.1 the container logs contain this:

![kitematic](https://cloud.githubusercontent.com/assets/344822/8635215/c90f4212-2819-11e5-8a2f-2f23c50c015f.png)

```
 nginx instance (/home/beaker/src/core/nginx)
nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to https://084cd3d77113:8800/
Submit this password: h1uvAJ3fbIrvQOt
```

When going to the access URL http://192.168.99.100:32768/ provided by Kitematic I get

![nginx](https://cloud.githubusercontent.com/assets/344822/8635216/dc8462fa-2819-11e5-921f-6401538cadf5.png)

```
400 Bad Request

The plain HTTP request was sent to HTTPS port
nginx/1.8.0
```

Changing the http to https and disregarding Chrome's warning redirects 

https://192.168.99.100:32768/ to https://192.168.99.100:8800/login/login.html and then the connection is refused (ERR_CONNECTION_REFUSED in Chrome)

**Comment by scottdraves** [comment]
i haven't tried it with windows but why are you using port 32768?  you might have to open that port or do some kind of remapping, it listens with https on port 8800.

**Comment by sharingtom** [comment]
I only downloaded Kitematic and picked the Docker container from within the GUI. Seems Kitematic randomly selects a port. See kitematic/kitematic#164 and kitematic/kitematic#598.

Not sure if the merge in 598 will solve the it, but from what I can tell it won't make Beaker "just work", because it will require the user to know to change the port manually.

**Comment by sharingtom** [comment]
Switching

https://192.168.99.100:8800/login/login.html

to the random port

https://192.168.99.100:32768/login/login.html

brings up the login page, but nothing happens when submitting the password from the console. (Only reloads the page.)

**Comment by hydrosquall** [comment]
Had similar issues on windows 7, resolved after restarting the container several times. Still getting the error nginx can't open the log files, but at least beaker is running.

**Comment by bsamadi** [comment]
The problem is caused by using http instead of https. Try https://localhost:3277\* The number is the port number assigned to the container by Kitematic.
