### ISSUE TITLE
IPython IFrame broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1925]
nothing shows
http://sharing.beakernotebook.com/gist/anonymous/29a55567b35e5221bbc8

**Comment by morhekil** [comment]
same here, and it started happening after the last upgrade - it used to work for me before.

Not just iPython, but even if I do an html cell with iframe - the iframe gets removed from the output. Is it possible to disable this behaviour?

**Comment by scottdraves** [comment]
http://nbviewer.ipython.org/gist/scottdraves/85fb74d6f50c711177fe
