### ISSUE TITLE
Update travis to use the containerized env ⚡️

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1931]
This will speed up our build time significantly.

http://docs.travis-ci.com/user/workers/container-based-infrastructure/

I have started on an implementation here 
https://github.com/twosigma/beaker-notebook/sjs/update-travis-build

However I am waiting for action on this ticket before we can be done :ship: 
https://github.com/travis-ci/travis-ci/issues/4337

**Comment by tomca32** [comment]
Travis CI has changed their whitelist request format and repo so I opened new issues here:

zeroMQ: https://github.com/travis-ci/apt-package-whitelist/issues/1407
rruter: https://github.com/travis-ci/apt-package-whitelist/issues/1408

**Comment by tomca32** [comment]
Perhaps we can just use the new Travis infrastructure which allows us to use sudo: #2372
