### ISSUE TITLE
Implement linter to test styling consistency

### ISSUE THREAD

**Issue by anthonyjruffa** [twosigma/beakerx#1938]
To test the consistency of your styles and to enforce certain rules in them, it would be a good idea to use a linter for your SCSS files.  I can certainly set one up for this and open a PR.

Here is the stylint I was considering implementing:
https://www.npmjs.com/package/scsslint

Doing this would enforce a consistent style across your SCSS files.  For example, you could force hex notation with lowecase letters or a consistent amount of spacing for indentation with this.

I would set this up to make it so that there are no new or changed commands to run the tests, but the linter will run before the tests already in the project, to check if the styles are all consistent and follow the rules set by the linter.

**Comment by scottdraves** [comment]
no thanks
