### ISSUE TITLE
electron clean build missing plugins?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1943]
http://127.0.0.1:8801/a5dc09d/beaker/plugins/eval/ipythonPlugins/ipython/ipython.js Failed to load resource: the server responded with a status of 404 (Not Found)
beakerApp.js:1869 ObjectloadJob.reject @ beakerApp.js:1869
http://127.0.0.1:8801/a5dc09d/beaker/plugins/eval/r/r.js Failed to load resource: the server responded with a status of 404 (Not Found)
beakerApp.js:1869 Object

**Comment by DiegoAlbertoTorres** [comment]
Do you know how to reproduce? Is this just R failing to load?

**Comment by DiegoAlbertoTorres** [comment]
See ff8f2998810d

**Comment by DiegoAlbertoTorres** [comment]
Closed in https://github.com/twosigma/beaker-notebook/pull/1944
