### ISSUE TITLE
[Native Beaker] Font difference with Chrome

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1947]
The type in seems lighter in the native version
![screen shot 2015-07-15 at 3 41 02 pm](https://cloud.githubusercontent.com/assets/963093/8708130/290a9748-2b08-11e5-9048-4bdad9684552.png)
![screen shot 2015-07-15 at 3 41 07 pm](https://cloud.githubusercontent.com/assets/963093/8708131/29116884-2b08-11e5-84a5-7fdb31b5459c.png)

**Comment by DiegoAlbertoTorres** [comment]
Discovered that the difference is that Electron uses 'Courier New' for its monospace font, while Chrome/Firefox/Safari use 'Courier'.

**Comment by DiegoAlbertoTorres** [comment]
If we want a uniform look we should decide on a font and include it with Beaker.
