### ISSUE TITLE
support for groovy static imports

### ISSUE THREAD

**Issue by padreati** [twosigma/beakerx#1948]
I know that groovy shell/console is able to handle static imports. It is possible to add that support also for beaker notebooks? It would be really useful since I can avoid a lot of typing

**Comment by scottdraves** [comment]
Not sure what you mean.  This works fine:

```
import static Boolean.FALSE
print !FALSE
```

Can you be more specific about what you are trying to do?

**Comment by padreati** [comment]
Absolutely. This works from notebook scripts. I would like to work also from notebook's language setup. There you can import classes in such a way that you don't have to add them in each script. However when I tried to add a static import there the message looks like it can't import class static. As I mentioned already, this works from groovy tools like groovy shell.

**Comment by scottdraves** [comment]
OK think I get it, you are talking about the imports section in the language manager for groovy.
yes should be able to do that, thanks for the suggestion.

**Comment by altavir** [comment]
I confirm that it is a needed feature, particularly `import static Math.*`.

**Comment by scottdraves** [comment]
continued work: https://github.com/twosigma/beaker-notebook/issues/3121
