### ISSUE TITLE
further improve vertical density

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1950]
compare beaker advanced mode to ipy3:
<img width="205" alt="screen shot 2015-07-16 at 4 19 56 pm" src="https://cloud.githubusercontent.com/assets/963093/8734225/9ceec6d8-2bd6-11e5-9bb3-0e23c5c62f2c.png">
<img width="135" alt="screen shot 2015-07-16 at 4 19 40 pm" src="https://cloud.githubusercontent.com/assets/963093/8734224/9ced364c-2bd6-11e5-8e7f-79a1c03dee91.png">

**Comment by samccone** [comment]
from top to bottom the ipython cell is 55px tall, we are at 57px, 

will the drop by 2px be ok?

**Comment by scottdraves** [comment]
i measured ipython at 83 pixels vs beaker at 150...
