### ISSUE TITLE
Index problem between R and Python datasets

### ISSUE THREAD

**Issue by Rom1Garnier** [twosigma/beakerx#1956]
There seems to be an issue in how indexes are handled in the autotranslation between R and Python 2.7. 

When going from R to Python, the first column of the dataset is detected as the index of a Pandas dataframe. Conversely, when going from Python to R, the index column of the Pandas dataframe becomes an extra first column called "index".

I can't recall having had that issue before I upgraded to Beaker 1.3.1 and to R-3.2.1. Current pandas version is 0.16.2. 

See this notebook for instance (using the code from the autotranslation example notebook): http://sharing.beakernotebook.com/gist/anonymous/57892a71210821c71f05

**Comment by scottdraves** [comment]
thanks for the feedback
 can you say more specifically what the expected or desired result is?
in the last cell you dont want a column named "Index"?

**Comment by Rom1Garnier** [comment]
Two things should be different: 

1) in second cell, "Index" should be "X1". 
2) in last cell, there should not be an "index" column.

(1) is actually a lot more problematic than (2) as it may mean that a variable got "lost" in the process of translation. So far, the only workaround I've found is to add a dummy first column in R to avoid losing anything important. 
(2) is less of a problem - just drop a column in R and it's alright.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2185
