### ISSUE TITLE
IPython: Blocking Cross Origin API request

### ISSUE THREAD

**Issue by chehun** [twosigma/beakerx#1963]
Hi,

I am getting this error when starting IPython.

Running

```
0: C:\Programs\beaker\python\python
1: C:\Programs\beaker/config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin
2: 8804
Done starting IPython
IPython-stderr>[I 18:47:02.325 NotebookApp] Writing notebook server cookie secret to C:\Users\chehun\.beaker\v1\nginx372547
IPython-stderr>[I 18:47:02.331 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
IPython-stderr>[I 18:47:02.361 NotebookApp] Serving notebooks from local directory: C:\Programs\beaker
IPython-stderr>[I 18:47:02.361 NotebookApp] 0 active kernels
IPython-stderr>[I 18:47:02.361 NotebookApp] The IPython Notebook is running at: http://127.0.0.1:8804/
IPython-stderr>[I 18:47:02.361 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip conf
IPython-stderr>[I 18:47:02.622 NotebookApp] 302 POST /login?next=%2F (127.0.0.1) 1.00ms
IPython-stderr>[W 18:47:02.644 NotebookApp] Blocking Cross Origin API request.  Origin: http://127.0.0.1:8801, Host: 127.0.
IPython-stderr>[W 18:47:02.651 NotebookApp] 404 POST /api/sessions (127.0.0.1) 8.00ms referer=http://127.0.0.1:8801/beaker/
```

I am running Windows 7. Is there a config file in beaker where I can set the settings for ipython to allow cross origin?

**Comment by samccone** [comment]
Hi @chehun thanks for raising this issue
I think this is related to #1955

**Comment by samccone** [comment]
@chehun what browser were you testing this on?

**Comment by scottdraves** [comment]
thanks for the bug report, what version of IPython are you using?
it should just work, no special configuration is required.

**Comment by chehun** [comment]
Hi @scottdraves and @samccone.
I am running ipython 3.2.1.The browsers I tried it with are Chrome and Firefox.
Thanks for looking into it.

**Comment by chehun** [comment]
@scottdraves and @samccone 
Sorry I spoke to quickly. It does work on Firefox! 
Cheers

**Comment by scottdraves** [comment]
Looks like this was really https://github.com/twosigma/beaker-notebook/issues/2003

**Comment by hadyrashwan** [comment]
any workaround exists ??? I'm just copying the link from canopy to firefox every time I want to open a notebook

**Comment by scottdraves** [comment]
Sorry not sure what you mean this was fixed a long time ago.

**Comment by hadyrashwan** [comment]
`[W 09:46:18.809 NotebookApp] 404 GET /api/kernelspecs (127.0.0.1) 1.91ms referer=http://localhost:8888/tree
[W 09:46:38.477 NotebookApp] Blocking Cross Origin API request.  Origin: , Host: localhost:8888
[W 09:46:38.482 NotebookApp] 404 GET /api/sessions?_=1475567178296 (127.0.0.1) 5.27ms referer=http://localhost:8888/tree
[W 09:46:38.487 NotebookApp] Blocking Cross Origin API request.  Origin: , Host: localhost:8888
[W 09:46:38.490 NotebookApp] 404 GET /api/terminals?_=1475567178297 (127.0.0.1) 6.22ms referer=http://localhost:8888/tree
`
I used 
`jupyter notebook`

which opened automaticlly in chrome and gave me no view for my files then I ran on firefox and my notebooks appered and the kernel loaded when I opened the file 
`[I 09:50:20.173 NotebookApp] Kernel started: 24c93083-a605-4935-9382-5acec6bcffcb
[W 09:50:20.376 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20161004094607 (127.0.0.1) 2.53ms referer=http://localhost:8888/notebooks/Python101.ipynb
`
the version I'm using is 
`hady@hady-Lenovo-Z580:~/Downloads$ jupyter --version  
4.2.0`

Chromium Version is : 
Version 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
and firefox Version is : 49.0

**Comment by izk8** [comment]
I am getting similar issues:

```
[W 10:03:32.105 NotebookApp] Blocking Cross Origin API request.  Origin: , Host: localhost:8889
[W 10:03:32.121 NotebookApp] 404 GET /api/config/tree?_=1475589811942 (::1) 16.22ms referer=http://localhost:8889/tree
```

Using fedora 24, jupyter 4.2.0, and chrome 53.0.2785.143.

**Comment by izk8** [comment]
And I can confirm it works on firefox. It also works in incognito mode. It must be some extension.

**Comment by izk8** [comment]
After trying each extension, the one that failed out jupyter from working was this extension: http://lab.ejci.net/Chrome-Audio-EQ/.

**Comment by scottdraves** [comment]
Are you even running Beaker?

**Comment by snarski** [comment]
@thompsonisaacb Thanks for the suggestion. This problem appeared out of nowhere, I removed Chrome EQ and the problem immediately disappeared. Could you explain what you think might have happened? Either way, thanks a million for figuring it out.

**Comment by tomca32** [comment]
@scottdraves - I added this info to troubleshooting section of the wiki: https://github.com/twosigma/beaker-notebook/wiki/Blocking-Cross-Origin-API-request-error

Hope that's ok.

**Comment by justrp** [comment]
Just for those who googled this: fill into your jupyter_notebook_config.py  this line:
```
c.NotebookApp.allow_origin = '*'
```
or paste your own origin.

(wiki page updated)

**Comment by MInner** [comment]
> ```
> c.NotebookApp.allow_origin = '*'
> ```

(or pass `--NotebookApp.allow_origin='*'` as a command-line augment)
