### ISSUE TITLE
Switch to a local storage cross tab communication approach for sharing state in multiple windows

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#1975]
Currently we use a mix of REST calls and websockets to handle sharing state between open windows.

Serializing a notebook can be an expensive operation for large notebooks, a solution to this issue would be to implement cross tab communication http://ponyfoo.com/articles/cross-tab-communication to be able to get around this issue.

This would result in a simpler codebase and a "faster" application (since the network would no longer be the bottleneck)

**Comment by scottdraves** [comment]
i am dubious about introducing a whole new and relatively unused API into the application.
especially, since local storage is persistent, i can see it becoming corrupted and the app breaking permanently.
let's first explore how to fix this with comet on the other issue.
