### ISSUE TITLE
Unexplained Bayeux Null

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#1976]
Leads to having to catch an NPE in SessionBackupRest.java, which spits out:
Warning: Caught NPE of unknown origin.

**Comment by DiegoAlbertoTorres** [comment]
More information on origin of this NPE:
When using an electron client to switch to a pre-existing backend, all backend-Electron communications will fall unto this NPE, instead of properly posting on the cometd channel.

**Comment by DiegoAlbertoTorres** [comment]
The problem mentioned in the previous comment was caused because Faye was not being rebound to the new backend server. Then it seems that the NPE occurs when a publication is attempted on a channel on which nobody is listening, in which case this NPE is properly handled and no error should be output.

**Comment by maxyeg** [comment]
The only way I can reproduce it is:
In beaker(web version), when notebook is opened, click menu File -> Close.
It will call REST Api to close session:
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/java/com/twosigma/beaker/core/rest/SessionBackupRest.java#L190
and it tries to publish session update to Electron channel which was never created.
So I will separate api for closing electron session from web.

**Comment by scottdraves** [comment]
still getting these.

**Comment by maxyeg** [comment]
Could you describe test case?

**Comment by scottdraves** [comment]
you said you have seen these now...

**Comment by scottdraves** [comment]
these are visbile as:

```
Warning: Caught NPE of unknown origin.
```
