### ISSUE TITLE
Cannot save notebook from 'are you sure?' prompt

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#1977]
To reproduce:
1. Create a new empty notebook
2. Make changes
3. Close notebook from 'File' menu
4. Press yes on 'save before closing' dialog
5. No dialog pops up, console error is: TypeError: Cannot read property 'saveNotebook' of undefined

**Comment by samccone** [comment]
:white_check_mark: https://github.com/twosigma/beaker-notebook/pull/2074
