### ISSUE TITLE
release-refact - Cats plugin doesn't work

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#198]
1) Create new notebook
2) Open plugin manager and paste in http://jchendy.com/beaker/cats.js
3) Click 'add plugin from URL'

Nothing happens.

This plugin loads fine in 0.52

**Comment by anglee** [comment]
cat.js wasn't using the new plugin format, here is the diff of what needs to change:
https://github.com/twosigma/beaker-notebook/commit/81d561db31ed3d07ca2761e0f5c958daf2103bc1

**Comment by jchendy** [comment]
Okay cool, http://jchendy.com/beaker/cats2.js works.
