### ISSUE TITLE
Can't run R cells out of the box in Ubuntu 14.04

### ISSUE THREAD

**Issue by huffyhenry** [twosigma/beakerx#1982]
Hi,

I started to play with the Beaker Notebook on Ubuntu 14.04 today. I ran `install-dependencies.sh` as root, then `beaker.command` as a regular user. The notebook started fine and I could run Python cells, but R cells gave an error: `SEVERE Error starting Rserve` or similar. The problem disappeared after I ran `install.packages('devtools')` manually in an R console. I'm not 100% sure that this was the fix, since I tried a few things, but I am 100% certain that `devtools` wasn't installed even though `install-dependencies.sh` completed successfully.

My apologies for being vague - now that it works I can't reproduce and give you more details. Happy to run tests for you as directed though.

Many thanks for creating this excellent tool.

With best wishes,

Marek Kwiatkowski

edit: should at least have given the Beaker version, sorry:
build time: 2015-06-29 18:01 PDT
version: v1.3.1-0-g3072e5e

**Comment by scottdraves** [comment]
Thanks for the report, we are looking into it.

**Comment by scottdraves** [comment]
confirmed

**Comment by scottdraves** [comment]
need https://github.com/twosigma/beaker-notebook/commit/cd664b34ccd3bc19e365d4c1f7150694af02967c
