### ISSUE TITLE
incompatible with IPython v3.2.1 

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2003]
because of https://github.com/ipython/ipython/commit/1415a9710407e7c14900531813c15ba6165f0816
Beaker's IPython plugins do not work with the latest version of IPython.

That change breaks this call to api/sessions: https://github.com/twosigma/beaker-notebook/blob/master/plugin/ipythonPlugins/src/dist/ipython/ipython.js#L119

We need to add proxy_set_header to these rules:
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/java/com/twosigma/beaker/core/rest/PluginServiceLocatorRest.java#L111

**Comment by phuang7008** [comment]
This issue is not fixed as I still got the same error message in Chrom. However, it is fine in FireFox. The iPython I used is 4.2.0 and jupyter I used is 4.1.0

Peter

**Comment by scottdraves** [comment]
what error do you get?

**Comment by phuang7008** [comment]
[W 19:09:18.114 NotebookApp] Blocking Cross Origin API request.  Origin: http://python1-phuang7008.c9users.io, Host: python1-phuang7008.c9users.io:80
[W 19:09:18.118 NotebookApp] 404 POST /api/sessions (10.240.0.192) 4.10ms referer=http://python1-phuang7008.c9users.io/notebooks/first_try.ipynb

**Comment by scottdraves** [comment]
thanks -- python2 or python3?

**Comment by phuang7008** [comment]
(py3)phuang7008:~/workspace $ python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by scottdraves** [comment]
hm its working for me, what version of beaker do you have?

**Comment by phuang7008** [comment]
I use miniconda. Should I try beaker instead?

**Comment by scottdraves** [comment]
how did you install beaker?  what version do you have?

**Comment by phuang7008** [comment]
I don't have beaker installed. The tutorial didn't mention it! how do I check if I have beaker installed? I tried pip freeze, but can't find any

**Comment by scottdraves** [comment]
what tutorial?  this is the bug tracker for beaker, if you don't have beaker installed then this isn't the right place...

**Comment by phuang7008** [comment]
https://www.youtube.com/watch?v=b7CbZPwEjVw

**Comment by phuang7008** [comment]
I disagree! How come it works in FireFox without beaker?

**Comment by scottdraves** [comment]
this has nothing to do with beaker, please seek help elsewhere.
