### ISSUE TITLE
when sharing, convert file images to inline?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2006]
In this example: http://sharing.beakernotebook.com/gist/anonymous/0b96e5ee9682e7bc8981
the image is missing.  could do it on save too.  we cannot save all such files, but maybe rescuing some is better than being consistent.

related: https://github.com/twosigma/beaker-notebook/issues/798

**Comment by samccone** [comment]
When a user publishes to the web we can scrape all of the outputs looking for any image, base64 encode it and update the source before pushing to the sharing server. This should be a fairly straight forward task to do.
