### ISSUE TITLE
R corrplots ignored

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2020]
```
library(corrplot)
M <- cor(mtcars)
corrplot(M, method = "circle")
```

this should produce a plot, not a dataframe.  in fact, it produces both, but somehow R knows to show the graphics and ignore the regular result.  we should do the same.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/tree/spot/2020

**Comment by ildipo** [comment]
This is handled in 
https://github.com/twosigma/beaker-notebook/blob/master/plugin/r/src/main/java/com/twosigma/beaker/r/utils/RServerEvaluator.java#L511 to line 523 and by default it gets the returned data instead of the plot.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2046
