### ISSUE TITLE
Various permission denied when running notebooks using docker

### ISSUE THREAD

**Issue by Analect** [twosigma/beakerx#2023]
The Help .. About Beaker doesn't display a build time or version, for some reason .. but I built the docker image from source on Aug 2, so I'm presuming it's version 1.3.3.

When running the the SparkR example, the first cell errors out:

```
Error
 Downloading github repo amplab-extras/SparkR-pkg@master
Installing SparkR
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  '/tmp/RtmpOktOX8/devtoolse77537d500/amplab-extras-SparkR-pkg-e532627/pkg'  \
  --library='/usr/local/lib/R/site-library' --install-tests 
Error: ERROR: no permission to install to directory '/usr/local/lib/R/site-library'
```

![image](https://cloud.githubusercontent.com/assets/4063815/9033035/de641b70-39bb-11e5-9819-3c518cc005c9.png)

I thought the user was running as root by default from within a container, so I didn't anticipate these permissioning errors.

In playing around with another example *.bkr notebook yesterday, one of the python modules was missing.  I inserted a new cell above and tried:

```
!pip install mechanize
```

However, that failed on permission denied too ... I even tried

```
!sudo pip install mechanize
```

which also failed.

It seems from #1918, the fix was to go back and modify the dockerfile to include the relevant package at install, but rebuilding the image from scratch, given that it is already almost 4GB, takes a substantial amount of time.

Can you suggest any other fix to these permission denied problems?

Thanks.

**Comment by scottdraves** [comment]
The Docker container isn't set up to allow you to install your own libraries in it.
I recommend entering the container and installing them as root.
Do you know how to use `nsenter`?

**Comment by Analect** [comment]
@scottdraves 
Thanks. Yes, I'm familiar with nsenter.
I was able to install directly on the container.  I'll close this.  Rgds.
