### ISSUE TITLE
Cannot start up on Mac

### ISSUE THREAD

**Issue by ajanian** [twosigma/beakerx#203]
andrewjanian in ~
⚡ /Users/andrewjanian/Downloads/beaker-notebook-v0/beaker.command ; exit;
running nginx: ./nginx/bin/nginx -p /Users/andrewjanian/.beaker/v1/nginx3001808655511388013 -c /Users/andrewjanian/.beaker/v1/nginx3001808655511388013/conf/nginx.conf
nginx-stderr>dyld: Library not loaded: /usr/local/lib/libpcre.1.dylib
nginx-stderr>  Referenced from: /Users/andrewjanian/Downloads/beaker-notebook-v0/./nginx/bin/nginx
nginx-stderr>  Reason: image not found
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@0.0.0.0:8802

Connecting to http://andrews-air-2.lan:8801/beaker/

**Comment by jchendy** [comment]
Thanks for the report AJ. What version of Mac OS are you running?

**Comment by ajanian** [comment]
10.9.2

**Comment by scottdraves** [comment]
i can reproduce this with my personal laptop, i'll bring it in and fix this today.

**Comment by scottdraves** [comment]
AJ, you can fix this yourself quite easily without waiting for a new release.
Just edit the beaker.command script and change the path to the dynamic libs to ./nginx/bin from ./nginx (see the diff in the commit above).
Sorry for the trouble!

**Comment by ajanian** [comment]
No trouble at all.  Will fix tonight.  Very exciting stuff guys.  Glad to
file a bug to help.

**Comment by jchendy** [comment]
Scott deployed a new download with this fix as well: https://github.com/twosigma/beaker-notebook/releases/download/v0.52.1-beta/beaker-notebook-v0.52.1-beta-mac.zip
