### ISSUE TITLE
R - plot of object class 'drc' not working

### ISSUE THREAD

**Issue by Rom1Garnier** [twosigma/beakerx#2030]
Normally plot(model) when model is of class 'drc' (a package that allows fitting 4 parameters logistic curves) returns a plot of the datapoints and the best fit curve corresponding to the model. 

In beaker, the plot does not work and returns the two columns of the hidden dataset used to plot the curve. 

http://sharing.beakernotebook.com/gist/anonymous/88e26471c270cb8766d7

**Comment by scottdraves** [comment]
Thanks for the report.  I think this is the same as https://github.com/twosigma/beaker-notebook/issues/2020
I already have a prototype fix, I am going to finish it up now and we will release shortly.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2046
