### ISSUE TITLE
loading a missing library hangs R

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2033]
after you run this cell, no error is reported and R is dead.
![screen shot 2015-08-03 at 5 00 00 pm](https://cloud.githubusercontent.com/assets/963093/9047632/2f88f5f8-3a01-11e5-9f9a-e428403a36e9.png)

**Comment by maxyeg** [comment]
After I run such cell, I see error: 
"Error in library(asdfasf) : ��� ������ ��� ��������� 'asdfasf'"

![a6fc8-clip-6kb](https://cloud.githubusercontent.com/assets/2286032/9161954/5dd293e2-3f4c-11e5-8688-b4f865292520.png)

And after this error I still can successfully run other R code cells.

**Comment by scottdraves** [comment]
cannot reproduce
