### ISSUE TITLE
x axis needs months

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2042]
on the sharing server:
http://sharing.beakernotebook.com/gist/anonymous/4efeed247bd551efe48c

in master:
<img width="788" alt="screen shot 2015-08-04 at 11 12 06 pm" src="https://cloud.githubusercontent.com/assets/963093/9077627/3f563664-3afe-11e5-8e9c-52ec9916ce76.png">

**Comment by kpaharelau** [comment]
This issue has been fixed with https://github.com/twosigma/beaker-notebook/issues/2029. Please close it.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2075
