### ISSUE TITLE
Misalignment on output

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#2050]
![screen shot 2015-08-05 at 3 39 47 pm](https://cloud.githubusercontent.com/assets/3867399/9096087/0585e41c-3b89-11e5-8d2f-e8a8c5eda21a.png)

**Comment by DiegoAlbertoTorres** [comment]
Note how the "Hello world!" is shifted up

**Comment by samccone** [comment]
text output in advanced mode
