### ISSUE TITLE
release-refact - Sorting is backward on control panel

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#206]
Most recent notebook should be on top

**Comment by anglee** [comment]
I cannot reproduce this issue.

**Comment by jchendy** [comment]
Screenshot attached. This time it actually looks like random order rather than backward.

![screen shot 2014-05-02 at 4 18 38 pm](https://cloud.githubusercontent.com/assets/1740497/2867485/078f4710-d237-11e3-823f-e0cd976327eb.png)

**Comment by jchendy** [comment]
Added some more notebooks. Looks like sort is on ID column, not time.

**Comment by anglee** [comment]
This should be fixed by https://github.com/twosigma/beaker-notebook/commit/617210a1acc56cc7b95d68286194c889b2cbd19e on the release-refact branch.

**Comment by melmac48** [comment]
@anglee can you confirm that this is fixed for v0.55? thnx

**Comment by melmac48** [comment]
if it's not already fixed then move it to the v1 milestone.

**Comment by anglee** [comment]
Confirmed fixed by https://github.com/twosigma/beaker-notebook/commit/617210a1acc56cc7b95d68286194c889b2cbd19e
