### ISSUE TITLE
release-refact ipynb open URL changed

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#207]
example of old URL's
http://localhost:8801/beaker/#/open?uri=ipynb:%2F%2FUsers%2Falee%2F1_overview.ipynb
http://localhost:8801/beaker/#/open?uri=ipynb:%2Fhttp:%2F%2Fatwallab.cshl.edu%2Fteaching%2FQBbootcamp3.ipynb

example of new URL:
http://localhost:8801/beaker/#/open?uri=%2FUsers%2Falee%2F1_overview.ipynb&format=ipynb

**Comment by scottdraves** [comment]
i don't think we need to maintain compatibility of this behavior.
