### ISSUE TITLE
Build Failes: `gradle run`

### ISSUE THREAD

**Issue by suranands** [twosigma/beakerx#2072]
Please suggest.

```
gradle run

FAILURE: Build failed with an exception.

* What went wrong:
Task 'run' not found in root project 'beaker-notebook-v1.3.4-0-g37d7759-ubuntu'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                                                                          option to get more log output.

BUILD FAILED

Total time: 2.776 secs
```

And the command `gradle tasks` gives this output:

```
gradle tasks
:tasks

------------------------------------------------------------
All tasks runnable from root project
------------------------------------------------------------

Build Setup tasks
-----------------
init - Initializes a new Gradle build. [incubating]
wrapper - Generates Gradle wrapper files. [incubating]

Help tasks
----------
components - Displays the components produced by root project 'beaker-notebook-v1.3.4-0-g37d7759-ubuntu'. [incubating]
dependencies - Displays all dependencies declared in root project 'beaker-notebook-v1.3.4-0-g37d7759-ubuntu'.
dependencyInsight - Displays the insight into a specific dependency in root project 'beaker-notebook-v1.3.4-0-g37d7759-ubuntu'.
help - Displays a help message.
model - Displays the configuration model of root project 'beaker-notebook-v1.3.4-0-g37d7759-ubuntu'. [incubating]
projects - Displays the sub-projects of root project 'beaker-notebook-v1.3.4-0-g37d7759-ubuntu'.
properties - Displays the properties of root project 'beaker-notebook-v1.3.4-0-g37d7759-ubuntu'.
tasks - Displays the tasks runnable from root project 'beaker-notebook-v1.3.4-0-g37d7759-ubuntu'.

To see all tasks and more detail, run gradle tasks --all

To see more detail about a task, run gradle help --task <task>

BUILD SUCCESSFUL

Total time: 3.228 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
```

**Comment by scottdraves** [comment]
are you trying to compile Beaker as a developer or run it as a user?

**Comment by suranands** [comment]
I am definitely not a developer. I am learning data science. I just would like to use Beaker so I could create notebooks for some data analysis using Python and R simultaneously and share it with my trainer. I tried IRkernel for this purpose but couldn't get it to work. I use a dual boot system with Windows 10 and Ubuntu 14.04, if that helps. Thanks.

**Comment by scottdraves** [comment]
OK.  As a user you don't need gradle.  just run the script "beaker.command".

**Comment by suranands** [comment]
@scottdraves thanks for your time on this. But I seriously feel the help documentation on Beaker has to go a long long way. 

On github page, it clearly says the page is only for developers. Those who just want to use Beaker are directed to Beaker's website. On the website, the only thing useful for this purpose is the Getting Started page and all I get to see is to download the base installation. And all it does is downloading a zip file. I just couldn't understand how to use Beaker at all. What next after downloading the zip file. Should I run the install-dependencies.sh? I did as per the file name. It took quite some time to finish the work. But the end of it, I still cannot run the command you are specifying: `beaker.command`. I tried it from within the same folder where this file can be found.

`beaker.command: command not found`

This is what I see. Can you please help me understand how exactly should I use Beaker? With so many superior capabilities, I strongly believe Beaker should have a thorough documentation for reference. At least a set of installation instructions. Hope you take it positively. Thank you.

**Comment by scottdraves** [comment]
Just below the section on download is the section for running it says:

```
STARTING BEAKER
Use the beaker.command script to launch the application. It starts the server and opens your web browser with a connection to it.
```

In order to run a command in Linux, you normally have to give a path.  Try it like this:

```
./beaker.command
```

I agree we should have better documentation, thanks for your feedback.

**Comment by suranands** [comment]
Thank you very much. That's done. It is such a fantastic idea though. I can run some data analysis now using python in one cell and using R in the next, and so on. How brilliant! Thank you for your time and help.

**Comment by scottdraves** [comment]
thank you and good luck!
