### ISSUE TITLE
Plot can crash browser when output area is hidden

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2077]
create a notebook with groovy
create a cell containing:

``` groovy
def a = new Plot()
a
```

execute
hide the output area
execute again
-> the browser is dead. :skull:

**Comment by ildipo** [comment]
verified on Chrome Version 44.0.2403.130 (64-bit)

**Comment by samccone** [comment]
I am looking into this now thanks for the find @ildipo
