### ISSUE TITLE
🐛 plot x axis overflow 

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#2078]
<img width="611" alt="screen shot 2015-08-10 at 9 45 22 am" src="https://cloud.githubusercontent.com/assets/883126/9172909/94369bb6-3f44-11e5-8684-e8fc63b08148.png">

**Comment by scottdraves** [comment]
yea they should probably by default fill the cell.
this should be easier now that they can be resized.
but that's different from being pinned to the width of the browser window.
not sure what the right UX is here.
