### ISSUE TITLE
completions window should grow as wide as needed

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2098]
![screen shot 2015-08-12 at 8 39 03 am](https://cloud.githubusercontent.com/assets/963093/9224106/f8357d5a-40cd-11e5-882f-005bfd4c27be.png)

**Comment by ildipo** [comment]
maybe a scrollbar and/or resize handle would be best - it might grow outside the screen

**Comment by scottdraves** [comment]
if it is bigger than the screen then a scrollbar would be good, but normally we should not require an extra click.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2141
