### ISSUE TITLE
Plots should remember size after reevaluate cell

### ISSUE THREAD

**Issue by kpaharelau** [twosigma/beakerx#2099]
create a notebook with groovy
create a cell containing:

``` groovy
def a = new Plot()
a
```

resize
execute

-->Resize plot size lost.

It is induced from https://github.com/twosigma/beaker-notebook/issues/2077

**Comment by samccone** [comment]
sorry about this, totally did not know about this feature at all :(

**Comment by scottdraves** [comment]
it's OK, we Kanstantsin just put it in.
