### ISSUE TITLE
Memory regression introduced

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#2109]
Between these commits

<img width="1270" alt="screen shot 2015-08-12 at 2 36 48 pm" src="https://cloud.githubusercontent.com/assets/883126/9233165/9e1de08c-40ff-11e5-9d4b-7deaa67e6d5d.png">
### Before

<img width="515" alt="screen shot 2015-08-12 at 2 42 18 pm" src="https://cloud.githubusercontent.com/assets/883126/9233320/6bc19524-4100-11e5-8f24-e51052302467.png">
### After

<img width="606" alt="screen shot 2015-08-12 at 2 30 39 pm" src="https://cloud.githubusercontent.com/assets/883126/9233221/dbc4b08c-40ff-11e5-98b8-6630b802bcaa.png">

**Comment by kpaharelau** [comment]
I can not see serious memory leaks in the master

I used "Timeline" from chrome dev tools for an analysing

I created new empty notebook and did these actions 10 times
1. Insert JavaScript Cell
2. Add 1+1 to the code cell
3. Evaluate
4. Delete cell

I recorded this.

![image](https://cloud.githubusercontent.com/assets/13516511/11587899/de1be3b8-9a8d-11e5-91f2-8d28c032a2f5.png)

You can see that serious memory problems doesn' exist

P.S. I run GC before and after recording

**Comment by scottdraves** [comment]
thanks for checking

**Comment by samccone** [comment]
The listeners and nodes do seem to be elevated at the end, might be worth looking at what those node are via a heap snapshot before and after and dropping into compare more in dev tools.

but it does seem like most things are now cleaned up :+1:
