### ISSUE TITLE
cannot use beaker with remote server

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#212]
Because our quick fix to https://github.com/twosigma/beaker-notebook/issues/211 was to just disable all access from outside of localhost, you can no longer run Beaker on a server and access it remotely.  For example, on AWS.

We should add a command-line option to listen to the outside and take a password for authentication.  this should be checked by nginx.

**Comment by mforsyth** [comment]
Hi Scott,

You linked to this issue from the basecamp thread about Bunsen.  
Bunsen's use case wouldn't want there to be a password...  we'll eventually need security measures that will involve transmitting kerberos info via http headers/cookies.    So, for now, just want to make sure that the option to listen to the outside also allows NO password to be set.

**Comment by scottdraves** [comment]
Yup, that's no problem.

**Comment by scottdraves** [comment]
Here's the plan for networking options.  in beaker.conf.json:
https-certificate string  (use the named cert, if none given then generate one)
password-hash string (match login or deny access)
on the command line:
--public-server (listen to \* instead of localhost)
--no-password (do not prompt, otherwise public server requires a hash in beaker.conf.json)

**Comment by scottdraves** [comment]
btw do we have any problem with the server parsing and using beaker.conf.json?
right now i think it's just delivered to client and otherwise ignored.

**Comment by jchendy** [comment]
Using beaker.conf.json for both client and server sounds like the right thing to me. Ang, any thoughts?

**Comment by diraol** [comment]
Hi friends, any news about this? How could I expose my beaker instance to my local network? (I don't want to filter only to local addresses, it could just be any ip address).

**Comment by scottdraves** [comment]
It is currently under development with release target next week.

**Comment by scottdraves** [comment]
Here's the work in progress: https://github.com/twosigma/beaker-notebook/compare/public-server

Note especially how the login page and redirections work.
