### ISSUE TITLE
console error on page init

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2127]
https://pub.beakernotebook.com/user/v1/current_user Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by grin** [comment]
Just for the record, this error is not really an error. That request is used to probe the api to verify whether a user is currently signed in...that being said, I can make it so it doesn't show up the error on the javascript console if that's the intent of this issue.

**Comment by ildipo** [comment]
yes please
