### ISSUE TITLE
R notebook (subindex out of limits error)

### ISSUE THREAD

**Issue by ljcastro** [twosigma/beakerx#2129]
Hi all,

thank you very mucho for your fantastic environment, it's amazing!

I am working in a R notebook and when I execute a function, an error is returned. This is the error:

Error
 Error in l[[n[[i]]]] : sub'indice fuera de  los l'imites
Calls: <Anonymous> ... convertToJSON -> convertToDataTableDictionary -> paste -> gsub
 Interrupted

It's strange because the same code works in RStudio, and it's a very simple perceptron algorithm.

I suspect that the error comes directly from the environment, not from R.

If you need the code, I could send you the notebook.

Thanks!

**Comment by ljcastro** [comment]
More info about this issue. It seems that affects only at the presentation of the results from the cell, because I tried to use a model that contains the cell and it works. The only thing is that I can't show the model.

I attach more messages of the error:

Error
 Error in l[[n[[i]]]] : sub'indice fuera de  los l'imites
Calls: <Anonymous> ... convertToJSON -> convertToDataTableDictionary -> paste -> gsub
Adem'as: Warning messages:
1: In if (class(val) == "list") { :
  la condici'on tiene longitud > 1 y s'olo el primer elemento ser'a usado
2: In if (class(val) == "complex") { :
  la condici'on tiene longitud > 1 y s'olo el primer elemento ser'a usado
3: In if (class(val) == "data.frame") { :
  la condici'on tiene longitud > 1 y s'olo el primer elemento ser'a usado
4: In if (class(val) == "matrix") { :
  la condici'on tiene longitud > 1 y s'olo el primer elemento ser'a usado
5: In if (class(val) == "table") { :
  la condici'on tiene longitud > 1 y s'olo el primer elemento ser'a usado
 Interrupted

**Comment by ljcastro** [comment]
I shared the notebook: http://sharing.beakernotebook.com/gist/anonymous/5438193fed87dbb7faeb

**Comment by ildipo** [comment]
Hi, thanks for your report.
When you return a result from a cell this is converted to JSON to be properly displayed in beaker.
You hit a bug in the conversion process. I'm going to look at it ASAP.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2185
