### ISSUE TITLE
control-shift-a broken with offscreen cells

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2142]
Repro:
1) Make a new notebook
2) Add a code cell
3) Add a bunch of blank lines until the cell is longer than your screen
4) Scroll back to the top of the page
5) Click in the cell
6) Press ctrl-shift-a

Result:
A new cell is created, but the cursor remains where it was

Expected result:
The cursor moves to the next cell, and the page scrolls down so you can see it

surely this stems from lazy instantiation of cm

**Comment by alice-kroch** [comment]
Tested - not reproduced in current version, please check.

**Comment by scottdraves** [comment]
i still see it.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2768
