### ISSUE TITLE
Find a way to still show Run button while input cell is hidden.

### ISSUE THREAD

**Issue by thejohnfreeman** [twosigma/beakerx#2171]
Sometimes I've got my input all figured out, don't need any more refinements, so I want to collapse the input, but I still need to be able to re-run it periodically.

**Comment by scottdraves** [comment]
There is a little run button (triangle pointed to the right) just to the left of the expand/contract button.
Does that do what you need?

**Comment by thejohnfreeman** [comment]
I don't have that, but maybe I'm using a very old version. I will try with the latest version and re-open if it is still an issue.
