### ISSUE TITLE
Need a logout from beaker publication menu item 

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2194]
it should be under the publish and selectable only when you are logged in

**Comment by scottdraves** [comment]
it should probably show your logged-in identity "publishing as" with name + gravitar.
and have a link to log out.

**Comment by grin** [comment]
so we want the log out menu item or logged-in identity with logout link (in the publish modal) or both?

**Comment by ildipo** [comment]
I think both is better

**Comment by grin** [comment]
:+1:

**Comment by ildipo** [comment]
merged
