### ISSUE TITLE
create new account flow error

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2197]
1) start beaker and create/open a notebook
2) click publish (while not logged in)
3) click create new account
4) create the account
5) go back to beaker
6) click publish again -> beaker should be already logged in

**Comment by grin** [comment]
implemented in: https://github.com/twosigma/beaker-notebook/pull/2253

**Comment by ildipo** [comment]
@grin: This does not work very well. I think you should modify it.

The current behavior is:
1) put the login popup
2) click on 'new account' -> open it in a new window
3) in the new window you register and press ok
4) the new window tab is redirected to beaker
you endup with two beaker tabs pointing to the same notebook

The proper behavior should be:
1) put the login popup
2) click on 'new account' -> open it in a new window and close the popup in beaker
3) in the new window you register and press ok
4) close the new window tab

**Comment by grin** [comment]
how about if in the step 2 I open the publications sign up in the current beaker window...and then at the end redirect it back to beaker ?

**Comment by grin** [comment]
actually nevermind, I can implement the proper flow quite easily

**Comment by ildipo** [comment]
the issue is that if you use the same tab you'll have first to backup the current session and reload it when you came back

**Comment by ildipo** [comment]
I verified that if you simply close the new tab the old one is logged in properly

**Comment by grin** [comment]
Fixed in: https://github.com/twosigma/beaker-notebook/pull/2275

**Comment by ildipo** [comment]
merged
