### ISSUE TITLE
Consider using command-enter on mac

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#220]
control key is not very familiar to mac users, we might want to provide command-enter as an alias.

**Comment by jchendy** [comment]
We can also consider going all the way and replacing all CTRL shortcuts with CMD on Mac.

**Comment by tomlagatta** [comment]
Yes, I would much prefer this. I keep accidentally hitting Cmd-S instead of Ctrl-S.

**Comment by tomlagatta** [comment]
Also: I am now in the habit of hitting Ctrl instead of Cmd, which means I keep accidentally closing terminal processes (Ctrl-C) rather than copying text (Cmd-C).
