### ISSUE TITLE
Improve our installation and dependency experience

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#221]
Packr takes a .jar as input and produces native Win, Mac, and Linux executables with a bundled JVM.

https://github.com/libgdx/packr

**Comment by scottdraves** [comment]
For Mac:
http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/packagingAppsForMac.html
https://bitbucket.org/infinitekind/appbundler/overview

For Linux:
https://www.docker.io/ (dependencies could go in a container with option to use native from host).

**Comment by scottdraves** [comment]
relevant?
https://wiki.openjdk.java.net/display/OpenJFX/Main

**Comment by scottdraves** [comment]
For windows: http://launch4j.sourceforge.net/

**Comment by jchendy** [comment]
http://www.ej-technologies.com/products/install4j/features.html

Handles Window, Mac, and Linux including building native executables and bundling JRE.

They offer free licenses for open source projects: http://www.ej-technologies.com/buy/install4j/openSource/enter

**Comment by jchendy** [comment]
ps I found the install4j link here: http://www.excelsior-usa.com/articles/java-to-exe.html

**Comment by jchendy** [comment]
Confirmation that R intentionally doesn't modify the PATH on Windows: "The R installer does not put Rcmd.exe (nor any other R executable) on your PATH"

http://cran.r-project.org/bin/windows/base/rw-FAQ.html#Rcmd-is-not-found-in-my-PATH_0021

**Comment by jchendy** [comment]
Might be possible to find R through registry: http://stackoverflow.com/questions/7468061/finding-installation-directory-of-a-program-on-windows-from-python

**Comment by jchendy** [comment]
Confirmed that registry query works on my Win 8 VM: http://sharing.beakernotebook.com/gist/anonymous/60d7d6c61fefbb90f711

**Comment by jchendy** [comment]
See wiki for proposed plan: https://github.com/twosigma/beaker-notebook/wiki/Improving-the-install-and-launch-process

**Comment by scottdraves** [comment]
done for mac, punting windows to 2.0

**Comment by scottdraves** [comment]
next step would be to use our own windows instead of browser windows. here are a bunch of options:

macgap: http://macgapproject.github.io/
Chromium Embedded Framework https://code.google.com/p/chromiumembedded/
Atom shell (based on CEF) https://github.com/atom/atom-shell
Brackets Shell (also CEF based) https://github.com/adobe/brackets-shell
node-webkit https://github.com/rogerwang/node-webkit
TideSDK http://www.tidesdk.org/
http://www.trueinteractions.com/

from https://news.ycombinator.com/item?id=8694987

**Comment by scottdraves** [comment]
electron versions are done
