### ISSUE TITLE
allow publishing via website

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2211]
If a user has a bkr file but no beaker client they should still be able to publish it by simple form upload.

**Comment by scottdraves** [comment]
from this page https://pub.beakernotebook.com/#/create_publication

**Comment by planyon** [comment]
What are thoughts on, for users that are logged in, placing the "Create" button where the "Get Started" button is for users who are not logged in (since get started is not displayed for users logged in) and that button can lead to the upload publication form?

**Comment by sethkrasnianski** [comment]
:+1:
