### ISSUE TITLE
Feature request: LaTeX default text mode

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#222]
Having an option someplace which changes the LaTeX default environment to 'text mode' rather than 'math mode'. 

Also spelling: LaTeX not Latex

**Comment by scottdraves** [comment]
Thanks for the report.  This might be a different plugin.  IE, instead of just a LaTeX plugin we could have two plugins, "LaTeX Math" and "LaTeX Text".  Or, plugins can have state associated with them and UI elements like switches and text fields.  I am worried the latter would be confusing though.

**Comment by tomlagatta** [comment]
That's a possibility. If you implement it, make sure to track user usage of LaTeX Math Mode vs. LaTeX Text Mode. My feeling is that this results in plugin creep: most users will not take advantage of either capability (let alone both), so it's unnecessary information to show them.

One option is to make the default (math vs. text) a global preference for the user. My intuition is that most users will default to math mode (wanting to just whip up a quick formula they can export to a PowerPoint slide). I'm probably the exception here, wanting LaTeX to default to text mode.
