### ISSUE TITLE
updating a notebook you do not own

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2220]
Download a notebook (you do not own) from pub server
Open in beaker and change it
Press publish
Right now it tells you to update it but if you do it, it does not upload and does not tell you anything

Desired outcome:
1) if there's a notebook id inside but it is not yours then you should have only 'publish' and not 'update'
2) if there's a notebook id inside and it is yours then you should have 'publish as new' and also 'update'

**Comment by grin** [comment]
fixed in: https://github.com/twosigma/beaker-notebook/pull/2266 / a2f59c9
