### ISSUE TITLE
firefox still needs flash

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2225]
https://github.com/twosigma/beaker-notebook/pull/2179
seems not to work on firefox.  it does not crash but it does not work either.

**Comment by dlukyanyuk** [comment]
Seems like the flash plugin is disabled or blocked for the Beaker page. This functionality worked for me when I allowed flash plugin for the Beaker page and stopped working when I blocked this plugin.

**Comment by scottdraves** [comment]
https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/
