### ISSUE TITLE
easyform object needs toMap()

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2228]
need a way to convert an EasyForm object into the map of its names and values.
or is there a way to do this already?

**Comment by maxyeg** [comment]
EasyForm extends ObservableMap,
which implements Map<K, V>.
It was done to support groovy expressions(form["field"]) which can be written like form.get("field") in Java.

**Comment by scottdraves** [comment]
That's what I thought but it does not appear to work:
![screen shot 2015-09-01 at 9 50 17 am](https://cloud.githubusercontent.com/assets/963093/9605996/e1637070-508e-11e5-89ef-d797cf7e3d30.png)
