### ISSUE TITLE
Feature request: autosave

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#223]
Two autosave features would be nice: autosaving on a regular cycle (eg, every two minutes), as well as when the browser is closed and reopened. Thank you!

**Comment by tomlagatta** [comment]
FYI, if you go back to the previous page (Alt-Left), you lose all your recent work...

**Comment by scottdraves** [comment]
Hi Tom thanks for the feedback. The notebook is autosaved, you should be able to access a lost session from the control pannel (127.0.0.1:8801/beaker or click on "Beaker" in the upper left corner).  This should definitely be easier to find.  They also go to disk just in case, look in ~/.beaker.

**Comment by jchendy** [comment]
Thanks a lot for checking everything out Tom! 

In fact, the notebook is backed up to the server in both of the situations you listed (though I think it's every 30 seconds, not 2 minutes). When you got back to the control panel page, you should see all of your open notebooks, and selecting one of them will take you to the most recent backup.

The same should apply with the back button and CMD-Left.

In case you kill your server and forgot to actually save the notebook to disk, all of the backups are stored in ~/.beaker/v1/var/sessionBackups/

**Comment by tomlagatta** [comment]
That's great news. Fortunately I hadn't lost anything valuable. Upon reopening, can the server mention which was the last opened notebook?

Also, there are lots of copies of my current notebook open. Can the server auto-close / auto-merge those open notebooks?

![image](https://cloud.githubusercontent.com/assets/4721419/2895958/8895226c-d566-11e3-90ad-8d441a8f88b7.png)

**Comment by tomlagatta** [comment]
Minor feature request: when the user clicks on "edited", Beaker should save the document. (make it super duper easy to save)

**Comment by tomlagatta** [comment]
Also: the autosave does not remove the "edited" text, which is why I thought there was no autosave at first.

**Comment by jchendy** [comment]
The list is in reverse chronological order (ie, the most recently opened is on top)

**Comment by jchendy** [comment]
And there are two different concepts here, which can definitely be confusing:

_Save_ means write to the file you've specified on disk
_Backup_ means write to the directory in ~/.beaker

The auto\* is actually autobackup. It's writing to ~/.beaker, but not automatically writing over your file.

**Comment by tomlagatta** [comment]
I see. In that case, I would like to request an autosave feature, in addition to the automatic backup. I want what's on my screen to reflect the state of the file, and vice versa.

**Comment by tomlagatta** [comment]
Also, this is a normal state of affairs:

![image](https://cloud.githubusercontent.com/assets/4721419/2904393/3602a336-d5fb-11e3-8a6c-3fe70f55077f.png)

Ideally, there will only be one copy of my notebook open, and it will reflect the most current state of the file.

**Comment by jchendy** [comment]
We've filed #240 to simplify this behavior.
