### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#224]
The keyboard shortcut page is only for pc keyboards, not mac.

Please add Ctrl-S - Save notebook

**Comment by tomlagatta** [comment]
Ah, Ctrl-S does save. Please add to Keyboard Shortcuts

**Comment by scottdraves** [comment]
thanks for the bug report.

**Comment by jchendy** [comment]
Thanks Tom, I just added that to the list: https://github.com/twosigma/beaker-notebook/commit/d907eaacce5bba5007dd585c5753df14fce914ed

Also, you may be interested in following this issue. We're looking at using CMD instead of CTRL on Mac: https://github.com/twosigma/beaker-notebook/issues/220
