### ISSUE TITLE
Cannot create code cell from dropdown menu in FF

### ISSUE THREAD

**Issue by dlukyanyuk** [twosigma/beakerx#2243]
![2015-08-31 14 11 20](https://cloud.githubusercontent.com/assets/3629655/9577531/60eae81e-4fea-11e5-8dd6-86587c7069dc.png)

Trying to create new code cell by clicking on the item in dropdown list. But in FF the dropdown list disappears when I move the mouse on it.

**Comment by scottdraves** [comment]
confirmed.  thanks.
