### ISSUE TITLE
Feature request: default working directory in R

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#225]
Can you default an R cell's working directory to the directory where the notebook is saved?

eg, my R cell's current working directory (seen with getwd()) is "/private/tmp/Rserv/conn1091", rather than the location of the notebook.

**Comment by scottdraves** [comment]
that's a good idea.  Something like that...

**Comment by jchendy** [comment]
Looks like we currently have no consistency. Four different evaluators list four different PWDs, and none of them are actually the directory I launched Beaker from.

I'd recommend cwd in all plugins be set to the directory Beaker is launched in.

![screen shot 2014-05-05 at 11 12 56 pm](https://cloud.githubusercontent.com/assets/1740497/2885717/5d9665d4-d4cc-11e3-9ce0-09e8da1e842e.png)

**Comment by scottdraves** [comment]
i actually like the idea of setting CWD to where the bkr file is since that way you can have a folder that has data files and the notebook and move them all together and use relative paths.

**Comment by jchendy** [comment]
That's a good point. If we go that way, we'll need to come up with plans for things like:
- What's CWD for notebooks that aren't yet saved?
- If you 'save as' to a different directory, does CWD change (potentially breaking your code)?
- What about notebooks that are saved in cloud / remote storage?

**Comment by tomlagatta** [comment]
How about having a CWD info cell at the top of the sheet? If all languages are in the same CWD, then it just says `All Languages: [cwd]`. If the user starts changing the cwd in one language, the info cell could update to 

```
R: [cwd for R]
Remaining Languages: [cwd]
```
- What's CWD for notebooks that aren't yet saved?

I recommend a directory in the user's home folder called Beaker Notebooks. It could be the default working directory, as well as the default save-as directory. This would minimize user confusion as to where the notebook files are actually located. 

If you plan on having multiple filetypes in addition to just notebooks (e.g., common Beaker data files), then maybe a name like Beaker Laboratory would be better. 
- If you 'save as' to a different directory, does CWD change (potentially breaking your code)?

This could be asked in a popup to the user. It's not clear that one option is better than the other.
- What about notebooks that are saved in cloud / remote storage?

Good question.

**Comment by scottdraves** [comment]
I like the idea of a default folder for beaker, perhaps ~/Beaker.  this could be used as the CWD whenever the notebook doesn't have a well-defined location.  The directory beaker is launched in is not obvious if you are launching via double clicking some icon.
