### ISSUE TITLE
improve beaker object UI

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2256]
expose list of variables as method on beaker object?
then you can generate a simple map object from it and display with a table.
OR
you could also define our own json serializer method for the beaker object in the runtime (of each language) so you get at least a table UI instead of this:

<img width="432" alt="screen shot 2015-08-31 at 10 12 22 pm" src="https://cloud.githubusercontent.com/assets/963093/9594775/b4ae68de-502d-11e5-8ce2-1da69642d1a5.png">

**Comment by ildipo** [comment]
For the moment we support this only from JavaScript - the content is displayed using an OutputContainer with names.

**Comment by ildipo** [comment]
https://github.com/twosigma/beaker-notebook/pull/2481
