### ISSUE TITLE
R scan() function does not work

### ISSUE THREAD

**Issue by carloshdezv** [twosigma/beakerx#2263]
Hi,

Im trying to run this code on beaker notebook:

J <- 3
K <- 5 
X <- scan(n=J_K)
99.3 93.7 103.9 92.5 110.6
112.5 108.3 118.0 99.4 111.8
129.2 140.9 108.3 105.0 116.6
j <- rep(1:J, each=K)
j <- as.factor(j)
X.bar <- mean(X)
Xj.bar <- tapply(X, j, mean)
MSB <- sum((Xj.bar-X.bar)^2) \* K / (J-1)
MSW <- sum((X-rep(Xj.bar,each=K))^2)/J/(K-1)
print(MSB/MSW)
print(qf(0.95, J-1, J_(K-1)))
print(1-MSW/MSB)

And then I got this error:

Error
 eval failed, request status: R parser: syntax error

Is there any issue with scan function???, this code works fine in R or R studio.

Thanks!

**Comment by scottdraves** [comment]
Scan() works if it's set to read from a file or the web.
But you are right, scan() fails if you try to read from stdin.
Note though I tried this code in RStudio and it fails also....

This might be hard to fix but we will try.
Thanks for the report.

**Comment by scottdraves** [comment]
https://github.com/ipython/ipython/issues/8787
