### ISSUE TITLE
REPL mode

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#229]
Can there be a REPL mode where the cells evaluate sequentially in the background? (REPL= Read, Evaluate, Print, Loop) 

If a cell hasn't changed content, it makes sense to not evaluate it. However, if a cell changes, then the evaluation should propagate down the line: any cell which refers to variables/functions in previous cells should be reevaluated.

**Comment by scottdraves** [comment]
automatically determining dependencies isn't practical but something along these lines sounds promising.

**Comment by melmac48** [comment]
closing this for now as it's something that requires considerable work as a whole. We will reopen new bugs to address sub components of this that can be achieved in v2
