### ISSUE TITLE
stdout scrolls past bottom of the screen

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#23]
I can't see the last few lines of stdout. Screenshot attached.

![screen shot 2014-01-30 at 4 46 42 pm](https://f.cloud.github.com/assets/1740497/2045422/1e6aae84-89f8-11e3-81b3-c9c60d89e200.png)

**Comment by scottdraves** [comment]
i can't reproduce this on my own.
to follow you exactly i'll need that csv.

**Comment by jchendy** [comment]
I can't reproduce anymore. Closing.
