### ISSUE TITLE
Colors: hard to read

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#230]
I can't see the bright green parentheses with the dark blue R background. Is there a way for users to modify the color scheme?

**Comment by jchendy** [comment]
We're currently finalizing a set of mockups with a UI designer, which to every user's excitement, will eliminate background colors in cells.

**Comment by scottdraves** [comment]
as a workaround in the meantime you can edit config/plugins/eval/r/r.js, the background color is set on line 69.
