### ISSUE TITLE
ggvis broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2301]
as per http://ggvis.rstudio.com/cookbook.html
results in `ERROR: invalid object type ggvis` instead of opening the graph.
https://pub.beakernotebook.com/#/publications/55ee509e-5ec1-4ed8-9ff6-a6010841eb36

**Comment by scottdraves** [comment]
note: http://stackoverflow.com/questions/29386448/ggvis-in-jupyter-ipython-notebook

**Comment by scottdraves** [comment]
ideally we would define our own conversion rule so it just works, including showing the result in the cell, not opening a new page.

**Comment by ildipo** [comment]
https://github.com/twosigma/beaker-notebook/pull/2480
