### ISSUE TITLE
Feature request: stop evaluation

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#231]
I ran an R cell and it's stuck in an infinite loop. I don't know how to interrupt evaluation of a cell. 

I deleted the output, edited the cell to remove the bad line and reran it. Instead of evaluating, it just says "pending". In fact, any cell I try to evaluate says "pending".

**Comment by tomlagatta** [comment]
Closing the notebook did not fix the issue.

**Comment by tomlagatta** [comment]
Restarting beaker.command without restarting nginx did not fix the issue.

Restarting beaker.command & restarting nginx did fix the issue.

**Comment by melmac48** [comment]
@samccone can you let me know when this functionality goes into the new UI.
thnx

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/44
