### ISSUE TITLE
R not correctly suppressing output

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#232]
R is supposed to suppress the output of a command when:
- assigning a value to a variable name
- surrounding the command with invisible(...)

e.g., the commands
data1 <- 1:10
invisible(11:20)

should return no output, as in R terminal:

![image](https://cloud.githubusercontent.com/assets/4721419/2896283/1e926a14-d56b-11e3-8102-af52bc2cc115.png)

However, here is incorrect output in Beaker:

![image](https://cloud.githubusercontent.com/assets/4721419/2896289/2eb16da0-d56b-11e3-8612-ac725587582b.png)

Oddly, if I assign a list to a variable name, then it is correctly suppressed: 

![image](https://cloud.githubusercontent.com/assets/4721419/2896290/34446358-d56b-11e3-9c9d-7206fbb5ee1a.png)

**Comment by renkun-ken** [comment]
`base::withVisible()` might be helpful to solve the problem, the function returns a list including the value and whether it is returned visibly.

**Comment by scottdraves** [comment]
Thanks Kun, that might help.
