### ISSUE TITLE
Clojure code should run in a notebook unique namespace

### ISSUE THREAD

**Issue by farrellm** [twosigma/beakerx#2323]
Currently, all Clojure code runs in the "clojure.core" namespace, but this can cause problems when importing external code and allows bad interactions between notebooks. This can be avoided by giving each notebook a default namespace where code is evaluated by default.

Possible function to do this:

```
(defn load-string-in-ns [n s]
  (binding [*ns* (find-ns n)]
    (load-string s)))
```

References:
http://stackoverflow.com/questions/6443594/how-to-load-string-to-current-namespace-not-core

**Comment by scottdraves** [comment]
Thanks Matt, Clojure is due for an overhaul in about a month, we'll fix this then.
