### ISSUE TITLE
Issue using ipython 4.0

### ISSUE THREAD

**Issue by aongun** [twosigma/beakerx#2326]
Please support ipython 4.0. There is a work around by downgrading but new systems will use more up to date modules

---- Background

When running with IPython version 4.0 I was getting an error connecting to ipython. And then nothing would run.

9/11/15 2:58:56.723 PM Beaker[4371]: nginx-stderr>2015/09/11 14:58:56 [error] 4475#0: *71 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /37d7759/r.647116713575/rest/rsh/ready HTTP/1.1", upstream: "http://127.0.0.1:8805/rest/rsh/ready", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"

On it's own ipython worked correctly. A the time my system was: Python 3.4.3 |Anaconda 2.2.0 | IPython 4.0

--- Workaround

I read a closed ticket (https://github.com/twosigma/beaker-notebook/issues/1435) that mentioned downgrading to version 3.2.0 which worked after doing:
pip uninstall
pip install -I ipython==3.2.0

going through conda could work too.

**Comment by scottdraves** [comment]
thanks for the report.  this is already fixed.
it will be released with v1.4 at the end of the month.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/2146

**Comment by aongun** [comment]
I think that's the fastest resolution I've seen. Awesome
