### ISSUE TITLE
Beaker hangs during close & save

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#233]
I tried to close an unsaved notebook, clicked Save, and the process is hung:

![image](https://cloud.githubusercontent.com/assets/4721419/2896353/0c7fe454-d56c-11e3-8bce-700f528a72a9.png)

The in-browser instance of Beaker crashed ("aw, snap!" screen in Chrome)

When I reopened Beaker, the file had correctly closed and saved.

**Comment by melmac48** [comment]
Can't reproduce with Beaker V1
