### ISSUE TITLE
performance optimization: lazy sections

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2335]
davide's idea:
if a section is closed, then its dom elements can be skipped.
there are two angular ways of hiding content, ng-if and ng-show.
one of them does this, i am not sure which we use for sections.
we should define our own that skips the dom elements until the section is open.
once it is open then we might as well keep them dom.

**Comment by tomca32** [comment]
We use ng-show (ng-hide) which keeps the DOM around. We should change to ng-if.

**Comment by scottdraves** [comment]
since we do lazy instantiate on visibility, wasn't this done?

**Comment by tomca32** [comment]
The idea here was to not parse the HTML at all if the section is closed. We still parse the HTML in closed sections even though we don't display the output or instantiate CodeMirror.
I don't think doing this will have a big positive impact on performance although it might in extreme cases (tons of closed sections).

I think we should keep this one around but it's a pretty low priority. It's also relatively simple to do, we just need to wrap ng-if into some directive to prevent it from removing the dom once it was parsed.
