### ISSUE TITLE
performance improvements

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2336]
first, make sure we have a much larger notebook for performance testing, and it's in CI and the stats are collected by our dashboard.  something like:

200 cells, 100 lines of code each, 10MB total size, mix of plots, images, tables of differing sizes mostly small but some with 1000-10k of rows.

THEN let's try some stuff out:
https://github.com/twosigma/beaker-notebook/issues/2334
https://github.com/twosigma/beaker-notebook/issues/2335

**Comment by scottdraves** [comment]
old version: https://github.com/twosigma/beaker-notebook/issues/838

**Comment by tomca32** [comment]
#2771 - relevant
