### ISSUE TITLE
Feature request: autoevaluate on notebook open

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#234]
When opening a closed notebook, I would like for the cells to sequentially evaluate, so that I may immediately go to the bottom of the notebook and start playing.

**Comment by jchendy** [comment]
This is super-hidden in the current UI. I promise it will be better after the redesign.

Click the line to the farthest right on the screen and select 'initialization cell'. This will cause all cells to run when you reopen the notebook. You can also do this for individual sections and cells by clicking the corresponding bracket.

**Comment by melmac48** [comment]
@samccone once this functionality is complete, please close this out or let me know and I can do it, thnx.

**Comment by melmac48** [comment]
Fixed with new UI
