### ISSUE TITLE
Can't undo deleted cell

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#235]
I deleted a cell and wasn't able to undo it with either Ctrl-Z or Cmd-Z.

**Comment by scottdraves** [comment]
lack of undo is a huge problem.

**Comment by melmac48** [comment]
we definitely need to fix this but it's too risky for v1 at this point. Will fix early in v2

**Comment by melmac48** [comment]
actually, we can treat cell deletion as a cut and then map ctrlz to a paste functionality to provide some type of recourse to an use who accidentally deletes a cell.

**Comment by jchendy** [comment]
That sounds pretty risky. What about this scenario:

1) I cut a cell 
2) I delete a cell
3) I try to paste the cell that I cut, but get the one I deleted

**Comment by melmac48** [comment]
I agree this is risky.
what if we use a different clipboard for deleted cells - then ctrlz returns the delted cell and paste returns the cut cell?
