### ISSUE TITLE
allow beaker pub server to handle cells and sections

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2361]
instead of just whole notebooks.

remove the old share menu items.

**Comment by alice-kroch** [comment]
Should I update the information in tutorial.bkr ?
![screenshot_3](https://cloud.githubusercontent.com/assets/5072172/10691216/3345beb4-7990-11e5-85fc-6bdefe3fd97e.png)

**Comment by scottdraves** [comment]
yes please
