### ISSUE TITLE
Slow evaluation of R 

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#237]
This might be out of your control. Evaluating a certain process in an R cell took ~2 minutes (nrows= 458441). During the evaluation, I copied-and-pasted the code into an R terminal process, and it finished substantially sooner than the Beaker process.

Is this slowness coming from Beaker, from nginx, or from RServe?

**Comment by jchendy** [comment]
Would you be able to come up with a code sample we can run that shows this behavior?

**Comment by tomlagatta** [comment]
Sure. Here's the sample CSV file: https://www.dropbox.com/s/zwgjj8ec81vlekm/nyt1.csv

setwd("[download location]")
data1 <- read.csv("./nyt1.csv");
data1$ageCat <- cut(data1$Age, c(-Inf,0,18,24,34,44,54,64,Inf));

It took me 42 seconds in Beaker (and unnecessarily displayed the output). It took me 3 seconds in an R terminal.

**Comment by jchendy** [comment]
Thanks. I don't have time to test it right now, but my first guess would be that the extra time is sending the output from server to client. If you don't mind, it might be useful to see what happens if you add a line of code to the end that returns null or something.

**Comment by tomlagatta** [comment]
Good call. It took only 6 seconds when I followed it with sink(NULL). This level of slowdown is an acceptable tradeoff for the notebook functionality. Thanks!
