### ISSUE TITLE
Problem Adding new Language

### ISSUE THREAD

**Issue by prvst** [twosigma/beakerx#2373]
Sorry if this is not the correct place. I didn't found a forum or mail group to post questions.

I was trying to add a new language (Go) to beaker but I can't understand the requirements and which files to change, the documentation is not very clear to me. Is there a place to ask for new language support? or at least someone who could give me some directions.

Thanks

**Comment by scottdraves** [comment]
This is a good place to start at least.  Did you see https://github.com/twosigma/beaker-notebook/wiki/How-to-Add-a-Language-to-Beaker yet?

**Comment by prvst** [comment]
Yes, o copied the Groovy folder and changed the name to Golang. Also I
edited the two files inside, the .js and the python script, replacing all
groovy entries to golang.

**Comment by scottdraves** [comment]
what about core/src/main/web/plugin/init/addevalplugins.js did you update that?
what is not working?

**Comment by prvst** [comment]
got your e-mail

**Comment by ildipo** [comment]
If the language does not appear in the language plugin UI then the entry is missing from addevalplugin.js or the golang.js is not found or has an error inside
If the language does appear but the backend is not started then it might be that the COMMAND in the golang.js is incorrect or the path is built (server side) incorrectly. You should have a message on the console to see what happened.

**Comment by prvst** [comment]
I added the following line to the addevalplugin.js file:

"Golang": { url : "./plugins/eval/golang/golang.js", bgColor: "#005e99",
fgColor: "#FFFFFF", borderColor: "", shortName: "Go" }

Then, after starting the server and choosing Go on the language manager I
get this on the terminal:

Connecting to http://127.0.0.1:8801/

restart-nginx-Golang-stderr>nginx: [alert] could not open error log file:
open() "/var/log/nginx/error.log" failed (13: Permission denied)
restart-nginx-Golang-stderr>2015/09/17 13:48:03 [notice] 7150#0: signal
process started
Running
0: /home/felipevl/bin/beaker/config/plugins/eval/golang/golangPlugin
1: 8804
Golang-stderr>Traceback (most recent call last):
Golang-stderr>  File
"/home/felipevl/bin/beaker/config/plugins/eval/golang/golangPlugin", line
32, in <module>
Golang-stderr>    os.execlp(bin, bin, port)
Golang-stderr>  File "/usr/lib/python2.7/os.py", line 327, in execlp
Golang-stderr>    execvp(file, args)
Golang-stderr>  File "/usr/lib/python2.7/os.py", line 344, in execvp
Golang-stderr>    _execvpe(file, args)
Golang-stderr>  File "/usr/lib/python2.7/os.py", line 368, in _execvpe
Golang-stderr>    func(file, *argrest)
Golang-stderr>OSError: [Errno 2] No such file or directory
Done starting Golang
nginx-stderr>2015/09/17 13:48:03 [error] 7154#0: *78 connect() failed (111:
Connection refused) while connecting to upstream, client: 127.0.0.1,
server: , request: "GET /37d7759/golang.281063586231/rest/golangsh/ready
HTTP/1.1", upstream: "http://127.0.0.1:8804/rest/golangsh/ready", host: "
127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/09/17 13:48:03 [error] 7154#0: *78 connect() failed (111:
Connection refused) while connecting to upstream, client: 127.0.0.1,
server: , request: "GET /37d7759/golang.281063586231/rest/golangsh/ready
HTTP/1.1", upstream: "http://127.0.0.1:8804/rest/golangsh/ready", host: "
127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/09/17 13:48:03 [error] 7154#0: *78 connect() failed (111:
Connection refused) while connecting to upstream, client: 127.0.0.1,
server: , request: "GET /37d7759/golang.281063586231/rest/golangsh/ready
HTTP/1.1", upstream: "http://127.0.0.1:8804/rest/golangsh/ready", host: "
127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"

**Comment by ildipo** [comment]
Execute  "/home/felipevl/bin/beaker/config/plugins/eval/golang/golangPlugin 8804" on the command line and see why it is failing. It seems line 32 is wrong

**Comment by prvst** [comment]
Traceback (most recent call last):
  File "./golangPlugin", line 32, in <module>
    os.execlp(bin, bin, port)
  File "/usr/lib/python2.7/os.py", line 327, in execlp
    execvp(file, args)
  File "/usr/lib/python2.7/os.py", line 344, in execvp
    _execvpe(file, args)
  File "/usr/lib/python2.7/os.py", line 368, in _execvpe
    func(file, *argrest)
OSError: [Errno 2] No such file or directory

**Comment by prvst** [comment]
Hum, I have a file inside the bin/ folder, called Golang, there was a typo (s/Golang/golang/).
I got this from the Groovy folder, i guess its configured to the Groovy language only
