### ISSUE TITLE
explain missing param

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2385]
https://github.com/twosigma/beaker-notebook/pull/2369

**Comment by kpaharelau** [comment]
I see that _sessionId is set in bkSessionManager in 3 functions:'reset', 'setSessionId' and 'setup'. Obviously in some cases in tests function 'setEdited' is called before calling functions above. We can to avoid this collision calling function 'setSessionId' with null parameter in the setEdited function.
