### ISSUE TITLE
Pub server - some style changes to featured notebooks

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2396]
- [x] Increase margin between slides by 30px
- [x] Reduce height of slides to 240px
- [x] Eliminate 3rd line of text
- [x] Eliminate "author" label
- [x] Change font color for author name to #1478 Add 3px additional space above author name
- [x] lower padding of text box to 13px
- [x] move text box to bottom left corner
- [x] remove text shadow
- [x] reduce text box height to 95px

TBD - change text box background to gradient

**Comment by sethkrasnianski** [comment]
> change text box background to gradient

@ildipo, current color to transparent on y axis?
