### ISSUE TITLE
Unify session backups and save files

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#240]
Users have found the different concepts of session backups and save files difficult to understand. We should unify and simplify this. One option is to have the backup be a dot or tilde file alongside the normal file. This would be similar to emacs, Word, Netbeans, IPython, etc. We should do a comparison of how these other editors work before settling on a spec.

**Comment by jchendy** [comment]
See #223 for one user's thoughts.

**Comment by scottdraves** [comment]
ipython has a good system:

1) auto save every minute to the regular file name.
2) when user issues save command, save an extra copy into a checkpoint file.

location of checkpoint could be a dot file, added .bak suffix, or (like ipython) a subdir named "checkpoints".

let's discuss and decide before implementation.

**Comment by scottdraves** [comment]
davide convinced me that ipython's is not expected behavior, tabled it.

**Comment by sergeny** [comment]
I actually lost work with ipython when I accidentally deleted large amounts of code, and then the result was auto-saved and auto-checkpointed. I would gladly dedicate a gigabyte or two to be able to autosave without overwriting.

Variation: have a special git repository in ~/.beaker and auto-commit there every 30 seconds.
