### ISSUE TITLE
say not to use Rstudio to install R libs, use native R

### ISSUE THREAD

**Issue by swayson** [twosigma/beakerx#2401]
I am having difficulties connecting to the R interpreter.

Here is the config:

beaker.pref.json: 

``` Javascript
{
  "languages" : {
    "R" : {
      "path" : "C:/Program Files/R/R-3.2.1/bin"
    }
  }
}

```

The packages I installed

```
    Rserve  1.7.3
    ggplot2  1.0.1
    devtools  1.9.1
    RCurl   1.95. 4.7
    RJSONIO  1.3.0
```

OS: `Windows 8.1`

Console reads:

```
R-stderr>The input line is too long.
R-stderr>The syntax of the command is incorrect.
Done starting R
```

This is the error I get:

```
Language Error
Failed to start R.

Did you install it according to the instructions on BeakerNotebook.com?

If you already have it, then edit your preferences file to help Beaker find it on your system, and then restart Beaker and try again.

Any other languages in your notebook should still work.
```

Could someone please advise as to what I am missing here?

**Comment by scottdraves** [comment]
try this: https://github.com/twosigma/beaker-notebook/issues/1920

**Comment by scottdraves** [comment]
thanks for the report.  in short, this is a bug in the interaction between gradle and windows and java:
https://issues.gradle.org/browse/GRADLE-2992
there is a workaround that we will try for our next release.

in the meantime, you can edit that file as suggested in 1920, or rename the beaker folder from "beaker-notebook-v1.3.4-0-...." to just "bn" and move it to the top of your filesystem (C:\bn....).

**Comment by swayson** [comment]
@scottdraves Thanks, I followed your workaround which did solve that particular issue. Now, I have an issue with `Rserve` it seems. 

It does not connect.

```
Done starting R
R-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
R-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started Select
ChannelConnector@127.0.0.1:8804
R-stderr waiting over
R-stderr>Sep 20, 2015 2:00:40 PM com.twosigma.beaker.r.utils.RServerEvaluator$wo
rkerThread startRserve
R-stderr>SEVERE: exception starting RServe
R-stderr>org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection r
efused: connect
R-stderr>       at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java
:88)
R-stderr>       at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java
:60)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.sta
rtRserve(RServerEvaluator.java:421)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run
(RServerEvaluator.java:459)
```

**Comment by scottdraves** [comment]
Thanks for the report.  I don't see any explanation though.
Is there anything non-stock about your OS or R installation?

**Comment by swayson** [comment]
Ah, now I see! I used RStudio when installing Rserve etc., which resulted in the packages being installed in a different directory. When running base R, it never recognised those packages. I had to configure it explicitly.

I ended up changing the Rprofile, by appending the following line and this resolved the issue:
`.libPaths('C:/Users/<USERNAME>/Documents/R/win-library/3.2')`

Thank you so much for your help and patience – much appreciated!

**Comment by scottdraves** [comment]
Cool glad it works for you now.

In our instructions we should say to install the packages running base R or something.
I'll make sure to do that before the next release.

And ultimately Beaker should install the packages that it needs automatically,
this is on the agenda for later in the year:
https://github.com/twosigma/beaker-notebook/issues/1350

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/commit/1bf0e4188f780616d2205516334cfa6cc1906e40
