### ISSUE TITLE
No default extension (.bkr) when saving

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#241]
Scott had mentioned the extension .bkr for Beaker notebooks. This is not displayed when saving. The choice of extension is currently up to the user, and I hadn't realized it should be .bkr (for consistency) until mentioned on this forum.

**Comment by jchendy** [comment]
Thanks Tom. This is actually in our current sprint and should be completed by Monday afternoon.

**Comment by jchendy** [comment]
This will be fixed as part of #247.
