### ISSUE TITLE
Expanding R error message turns it blank

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#242]
I typed some bad code in R and got an error message:

![image](https://cloud.githubusercontent.com/assets/4721419/2911906/deb2ee82-d669-11e3-9d85-9e3218aa19da.png)

Pressing the [+] turned the error box blank:

![image](https://cloud.githubusercontent.com/assets/4721419/2911909/edbd27da-d669-11e3-95e7-da38a67c6975.png)

**Comment by scottdraves** [comment]
yup this is a bug.

**Comment by scottdraves** [comment]
looks like sam got this one, the bug does not manifest in the new UI, there is no toggle for R errors.
