### ISSUE TITLE
reindent selection

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2424]
a user says:
there should be a command so I can select a region of code and format it (as ctrl+shift+f  in eclipse, or M-x indent-region in emacs).
bind it to cmd-shift-j (ctrl-shift-j on pc).

**Comment by kpaharelau** [comment]
I found native codemirror functionality for the auto indent. Please open notebook,  select all ell content and click Shift-Tab. This is a native behaviour codemirror. Ctrl-Shift-J from issue is not a good idea. On my OS Ubuntu this command open development tools in a chromium-browser and firefox.

**Comment by scottdraves** [comment]
thanks you are right on all counts.  
i'll just document it.

**Comment by scottdraves** [comment]
well, it does not seem to always work.
this documents it at least: https://github.com/twosigma/beaker-notebook/pull/2956

**Comment by scottdraves** [comment]
5.8 does not fix it for me, so i think we need to reimplement this.
the native function seems to work reliably if you set the cursor to the beginning of the line,
so maybe we can just do that in a loop.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2964
