### ISSUE TITLE
nginx log files on Windows can't be deleted

### ISSUE THREAD

**Issue by lcota** [twosigma/beakerx#2425]
I installed beaker on a Windows 7 machine without admin rights. The log files generated in my %PROFILE%/.beaker/v1/nginx\* require admin rights to delete. Is there a way to prevent these files from being generated with admin rights?

**Comment by scottdraves** [comment]
Thanks for the report, I'll look into it and get back to you.

**Comment by lcota** [comment]
After looking at this more, CTRL+C doesn't kill the nginx process started in windows. After manually terminating the process from Task Manager I'm able to delete those log files.

**Comment by scottdraves** [comment]
i can't reproduce this, can you give a more detailed steps of what you are seeing?

from a powershell, i run "beaker.command.bat" then press ctrl-c, answer Y to Terminate batch job, and the nginx processes are gone from the task manager.

This is Windows 8 though seems unlikely that would make any difference.

**Comment by scottdraves** [comment]
Note that the Electron version should make this problem go away, I am pretty sure we will have one for windows for v1.4.

**Comment by lcota** [comment]
Hi - after running the version from master/ this problem went away. It may have had something to do with using jupyter/ipython 4 on an older release of beaker. When is the electron version expected to be ready?

**Comment by scottdraves** [comment]
cool. prerelease including electron builds available from http://beakernotebook.com/downloads
