### ISSUE TITLE
Trying to build from source and I get errors in dev:core:npmInstall

### ISSUE THREAD

**Issue by jsbachsonata** [twosigma/beakerx#2427]
I think the issue is that I can't get git://github.com/isaacs/readable-stream.git since it's been changed to git://github.com/nodejs/readable-stream.git

Is that an issue for you when building?

**Comment by scottdraves** [comment]
thanks for the report but no, i just tried with a fresh clone too.
what platform are you on?
can you post a log?

**Comment by jsbachsonata** [comment]
![capture](https://cloud.githubusercontent.com/assets/12835467/10018931/4845ddc6-6108-11e5-9aff-e26db4d0c3fd.PNG)

**Comment by jsbachsonata** [comment]
I'm running windows 7 enterprise.

**Comment by jsbachsonata** [comment]
It might be because I'm behind a firewall at work. I'm working from home today so will try to do that and see if the git connection establishes.

**Comment by jsbachsonata** [comment]
Just tried that and it still didn't work using a home connection. Looks like it's related to this issue: https://github.com/npm/npm/issues/8494 .

**Comment by ildipo** [comment]
you can try to put `strict-ssl = false` in `.npmrc`

**Comment by jsbachsonata** [comment]
Thanks!! Solved it. :)

**Comment by PBartrina** [comment]
Is there any solution without avoiding ssl verification? I'd rather to avoid deactivating it.

UPDATE: I tried this solution and it still doesn't work for me

**Comment by scottdraves** [comment]
idk, this is an npm issue, ask there.
