### ISSUE TITLE
Indicate deprecated notebooks upon forced quit

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#243]
If the Beaker server crashes, the notebooks are left open. I suggest doing something to indicate that the in-browser notebooks are disconnected from the server. e.g., turn the background dark grey and disable editing.

**Comment by jchendy** [comment]
It's subtle, but there's a red 'disconnected' message in the header when that happens. We could definitely make it more noticable.

**Comment by melmac48** [comment]
Hey @samccone is this scenario covered in the new UI changes? if not, can you chat with Lubo about it? thnx.

**Comment by scottdraves** [comment]
done
