### ISSUE TITLE
Meta-data section alignment is off on publications.

### ISSUE THREAD

**Issue by planyon** [twosigma/beakerx#2439]
See attached screenshot where the "About This Notebook" section is pushed too far to the left and the Average Rating stars overlap with the label. The section can stretch out further to the right and should have the same padding as the left side.
<img width="944" alt="screen shot 2015-09-22 at 10 44 12 am" src="https://cloud.githubusercontent.com/assets/5454235/10021675/17b7089c-6117-11e5-9e79-54ee20de03b7.png">

**Comment by sethkrasnianski** [comment]
The current problem is the fact that we're positioning the attachment image (not shown in your example) to the left, which wastes a lot of space. On small screens, that limited real estate which we previously had is even more limited. The below example offers continuity with the featured publication styles as well as 25% more area to work with (as we previously did). 

<img width="1252" alt="screen shot 2015-09-22 at 1 52 29 pm" src="https://cloud.githubusercontent.com/assets/1910114/10026693/3b7787ba-6131-11e5-83d9-8cc627408654.png">

without the green top border...

<img width="1244" alt="screen shot 2015-09-22 at 1 56 09 pm" src="https://cloud.githubusercontent.com/assets/1910114/10026791/bdfb2e62-6131-11e5-95e5-7eb20bee9273.png">

**Comment by sethkrasnianski** [comment]
@planyon @ildipo

**Comment by sethkrasnianski** [comment]
Also... without an attached image, it would just look as it was before we introduced that feature.

**Comment by ildipo** [comment]
@seth I think the issue is simply that there's not enough space for the stars in the css - just make the div containing the rating a little bit larger (and not scalable) and we are fine.
