### ISSUE TITLE
old notebook flashes during load

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2446]
to reproduce:
1) run fresh beaker
2) open the main tutorial
3) click on JavaScript to open that tutorial
4) click on logo to return to start page
5) click on "tutorial" in the list

notice the page returns to the JS tutorial and display that until the main tutorial loads.
this is a regression.

**Comment by scottdraves** [comment]
related? https://github.com/twosigma/beaker-notebook/issues/2406

**Comment by maxyeg** [comment]
I've checked and it's not related to #2406.
