### ISSUE TITLE
Clicking around adds strange tags

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#245]
Clicking nearby a cell adds some strange tags to the text:

![image](https://cloud.githubusercontent.com/assets/4721419/2911867/62b27f2e-d668-11e3-8ab8-2c1fa387ce0b.png)

![image](https://cloud.githubusercontent.com/assets/4721419/2911868/74fdf32a-d668-11e3-98aa-eb5d5cf1f952.png)

After some normal editing, I am no longer able to replicate the problem.

**Comment by scottdraves** [comment]
prob related to https://github.com/twosigma/beaker-notebook/issues/125

**Comment by melmac48** [comment]
@scottdraves were you able to repro this issue?

**Comment by scottdraves** [comment]
yes, see above, this is a dup of #125

**Comment by scottdraves** [comment]
actually no -- he says "clicking".  i've never seen that, i just spent a few minutes clicking all over and nothing happened.

but 125 is a real problem!

**Comment by melmac48** [comment]
okay, closing this one out due to no repro. @tomlagatta if you're able to reproduce this again please reopen and we'll take a look. thnx.
