### ISSUE TITLE
Julia plugin not working

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#246]
I'm writing what seems to be correct Julia code, but it's not working right. Simple expressions like 2+2 work fine, but more complicated stuff returns errors like this:

![image](https://cloud.githubusercontent.com/assets/4721419/2912332/9ed42378-d676-11e3-8e5e-979192447951.png)

I tested some Python code and it worked fine, so I'm pretty sure it's just a Python cell wearing Julia's clothes.

**Comment by jchendy** [comment]
Are you able to run ijulia notebook from the command line?

**Comment by scottdraves** [comment]
here's the command line to try:

ipython notebook --profile julia

**Comment by tomlagatta** [comment]
It opened up the usual iPython screen. I created a new notebook, tried some simple Julia code and got an error:

![image](https://cloud.githubusercontent.com/assets/4721419/2920512/da3709f0-d6e7-11e3-93d8-4a47bd33e596.png)

**Comment by scottdraves** [comment]
that means you haven't completed your install of ijulia.
did you say `Pkg.add("IJulia")` to julia?

**Comment by jchendy** [comment]
By the way, our roadmap definitely includes better error messages when plugin loading fails.

**Comment by tomlagatta** [comment]
Aha, that must be it. I hadn't realized I had to do more. Maybe an alert on the Plugin Manager page saying "Julia install not yet finished". Let me follow through with the instructions on the Getting Started page and I'll close this thread if there are no problems.

**Comment by tomlagatta** [comment]
Julia is working great. Thanks! 

BTW, I had to reload the Julia plugin after restarting the Beaker server.
