### ISSUE TITLE
Improve save/load behavior

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#247]
**Save as file dialog**
- Show full file path below input box (see mockups)
  - If user has input a relative path, expand PWD
- Append .bkr if user doesn’t include it
- If user selects a directory, show dialog with “{selected path} is a directory. Please choose a different location” Include a close button that takes user back to ‘save as dialog’ with the same state as right before the clicked save.
- If the file exists, show dialog with “{selected path} already exists. Overwrite?” with buttons ‘Overwrite’ and ‘Cancel’ Cancel should take user back to ‘save as dialog’

**Open file dialog**
- Checkbox to show only .bkr files, checked by detault (see mockup)

**Save errors**
- Show dialog with title ‘Save failed’, text save failed + short exception, scroll pane with full exception, and a ‘close’ button.

**Open errors**
- For errors accessing file, use the same type of dialog as save errors
- If the content isn’t a notebook, show a dialog to that effect (currently this is done with alert(), let’s use a Bootstrap dialog for consistency)

![save-as-file-pwd](https://cloud.githubusercontent.com/assets/1740497/2918913/8fb5d148-d6d5-11e3-8d88-d43a2c44953d.png)

![save-as-file-pwd-2](https://cloud.githubusercontent.com/assets/1740497/2918898/76966ca4-d6d5-11e3-9a23-828ebc93398b.png)

**Comment by scottdraves** [comment]
the thing that would help me navigate this faster the most would be using a different color for notebooks (vs unloadable files and folders).

**Comment by anglee** [comment]
When implementing this, found something tricky and worth mentioning.
In saving dialog, when user select a path that is a directory, according to the spec, ".bkr" will be appended, and thus unless there is another directory named "{{selectedDir}}.bkr", that "selected path is a directory" dialog box won't be displayed.
@jchendy could you confirm that this is desired? thx!

**Comment by jchendy** [comment]
Good catch, let's discuss when we see each other. Scott's suggestion should be considered as well.

**Comment by jchendy** [comment]
Some modifications based on Ang's observation:
- When user clicks a directory, for example, '/u/jchendy' the path box should fill with '/u/jchendy/'
- When the text in the box ends with '/', the full path text should say 'You've selected a directory, please add a file name' and the save button should be greyed out
- If user manually types in a directory name with no trailing /, assume it's a file name and add .bkr

Scott says that the 'show only .bkr files' checkbox is sufficient and he doesn't need different colors.

**Comment by anglee** [comment]
Flow diagram for file saving logic in mainapp.js
https://www.lucidchart.com/documents/view/d2c35b6f-cbb6-48bd-be0d-80c86bb97a04
