### ISSUE TITLE
Clojure autotranslation

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2475]
Clojure plugin needs access to beaker namespace interface both for functions and for variable access.

To read a value from beaker namespace we should write something like:
    (:name beaker)  - and/or - (beaker "name")    - and/or - (beaker :name)

To write a value in beaker namespace we should write something like:
    (beaker "name" value) - and/or - (beaker :name value)

To call a function on the beaker object:
    (beaker "fname" params) - and/or - (beaker :fname params)

Data types should be translated to appropriate clojure datatypes

**Comment by ildipo** [comment]
you can probably define the beaker object with deftype as per http://clojure.org/datatypes

**Comment by maksim-lauryk** [comment]
autotranslation added in following format
(beaker :set "x" [1 2 3 "something else"])
(beaker :get "x")
