### ISSUE TITLE
stick with java7 subset

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2488]
even though we use java8 we should stick with java7 subset.

```
beaker-notebook/plugin/sqlsh/src/main/java/com/twosigma/beaker/sqlsh/autocomplete/db/DbRequestCache.java:74: error: cannot find symbol
            if (uriCache.putIfAbsent(schemaName, schemaCache) != null) {
                        ^
 symbol:   method putIfAbsent(String,Map<String,List<String>>)
 location: variable uriCache of type Map<String,Map<String,List<String>>>
```

**Comment by siarhei-shvaiko** [comment]
Done

**Comment by jonassmedegaard** [comment]
Does this mean Beaker is supposed to work with Java7 VMs, and you just prefer to use Java8?

I ask because a Java7 implementation is the default on Debian, so for Debian packaging it is relevant if we can avoid pulling in multiple implementations.

**Comment by scottdraves** [comment]
yes, it works with 7

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-17 16:51:28)

> yes, it works with 7

Great!
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private
