### ISSUE TITLE
logo should be svg

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2495]
so it scales without blurring
<img width="266" alt="screen shot 2015-09-26 at 3 24 35 pm" src="https://cloud.githubusercontent.com/assets/963093/10119388/d1736ea8-6462-11e5-9427-66b779148efe.png">

**Comment by scottdraves** [comment]
on pub too!

**Comment by sethkrasnianski** [comment]
opened issue on bunsen to change for pubs and possibly bunsen.
