### ISSUE TITLE
disable bold in markdown codemirror as well

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2503]
making the matching paren bold when the cursor moves over it causes all the text to shift because of the proportional spacing.  this is annoying, like our code editor we should skip the bold here.
<img width="163" alt="screen shot 2015-09-26 at 11 31 55 pm" src="https://cloud.githubusercontent.com/assets/963093/10121037/07a79096-64a7-11e5-80be-ba84024cb86c.png">

**Comment by scottdraves** [comment]
![screen shot 2015-09-28 at 8 49 38 am](https://cloud.githubusercontent.com/assets/963093/10135722/514bd168-65be-11e5-8faf-4629b431dcca.png)

**Comment by maxyeg** [comment]
That's how I see it:
![markdown](https://cloud.githubusercontent.com/assets/2286032/10136136/7d0cbb7c-65fb-11e5-916c-560be2a40fc8.png)
