### ISSUE TITLE
default JDBC config?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2506]
Is there a way to have a default database for all the SQL cells in a notebook?

The "Data sources" field in the Language Manager allows me to define names which are then used like `%%beakerDB = H2MemDB2`.  but then still every cell needs `%%beakerDB` something.

There should either be another field for the default source, or if you enter a line in Data sources that does not have an "=", then it would be the default.  Or am I just missing how to do this?

**Comment by maksim-lauryk** [comment]
in current realisation we have three ways for defined data source, e.g: 
%%beakerDB="jdbc:h2:mem:db1"
-- loading of connection string from plugin settings
%%beakerDB = H2MemDB2
-- load connection string from beaker object
%%beakerDB=${H2MemDB2}

There's not any way for setup default notebook data source, but it can be realized if necessary.

**Comment by ildipo** [comment]
Please add a default database option in the language manager

**Comment by scottdraves** [comment]
new field should be "Default data source"
current field should be renamed "Named data sources"
