### ISSUE TITLE
"Delete all output cells" should remove "elapsedTime" fields

### ISSUE THREAD

**Issue by farrellm** [twosigma/beakerx#253]
Currently  "elapsedTime" fields are not removed, leading to diff noise for notebooks in version control.

**Comment by melmac48** [comment]
we'll address in v2

**Comment by alice-kroch** [comment]
Can't reproduce it in current version

**Comment by scottdraves** [comment]
after you delete the outputs, save the notebook, and then inspect the file.
the menu item to delete the cell output has the same problem.
