### ISSUE TITLE
SQL bad variable name needs better error

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2540]
![screen shot 2015-09-29 at 11 35 22 am](https://cloud.githubusercontent.com/assets/963093/10176061/7bf0abc0-66c0-11e5-8539-728e1dea3cb4.png)

**Comment by maksim-lauryk** [comment]
This task should be solved by PR #2533 SQL plugin improvements, and I'm open to suggestion about text of this error (first part, second part usually is an error from NamespaceClient)

![bad_name](https://cloud.githubusercontent.com/assets/13995034/10186464/e24101ec-6759-11e5-92fe-f3b1389760ca.PNG)
