### ISSUE TITLE
more formatting problems on pub

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2545]
https://pub.beakernotebook.com/#/publications/560b54da-3c14-4890-8b64-b204bc798320

missing bullets with indentation
missing block quote
missing {{}}

i thought this shared code with beaker, why do these new features have to be reimplemented?

**Comment by grin** [comment]
Only output cells are reused from Beaker. 
Missing bullets and block quotes are css issues.

**Comment by grin** [comment]
Regarding missing javascript evaluation, that's not yet implemented in Publications. Currently we only apply markdown and ktex, which you can see here: https://github.com/twosigma/bunsen/blob/master/web/assets/js/directives/_publication_notebook_cells.js#L17

if that js->ktex->marked transformation  (https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/components/notebook/markdown-editable-directive.js#L118) was exposed as a service in Beaker or a helper function that takes cell's body and returns transformed html we could reuse it in Publications without duplicating the code.

**Comment by scottdraves** [comment]
why isn't the css shared?

**Comment by scottdraves** [comment]
i'll look at exposing evaluateJS, is that the only one you need?
what about the math coming from Python?

**Comment by grin** [comment]
beaker css is shared, just some of it rules are being overriden by bunsen styles

**Comment by grin** [comment]
would it be possible to have just a single function that applies all three transformations (js, ktex, md) at once? It could take cell body and return html...seems to me it's almost exactly what `preview` function does: https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/components/notebook/markdown-editable-directive.js#L116

**Comment by ildipo** [comment]
css is shared but it should be namespaced

**Comment by grin** [comment]
lists bullets fixed in: https://github.com/twosigma/bunsen/pull/1200

**Comment by ildipo** [comment]
actually it does not fix it

**Comment by grin** [comment]
@ildipo are you talking about bullet points and indentation alone? If I go to https://pub.beakernotebook.com/#/publications/560b54da-3c14-4890-8b64-b204bc798320 it shows bullets properly indented...
for the issue with {{}} syntax and block quotes I'm working on a fix right now...

**Comment by grin** [comment]
Fixed in: https://github.com/twosigma/bunsen/pull/1218
