### ISSUE TITLE
Can't download a publication in Chrome

### ISSUE THREAD

**Issue by grin** [twosigma/beakerx#2551]
https://pub.beakernotebook.com/#/publications/560b54da-3c14-4890-8b64-b204bc798320?fullscreen=false

Chrome shows an error: ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION
Other publications are working fine.

**Comment by grin** [comment]
Fixed in: https://github.com/twosigma/bunsen/pull/1201

**Comment by ildipo** [comment]
This is working fine
