### ISSUE TITLE
Categories should display publications from their child nodes

### ISSUE THREAD

**Issue by planyon** [twosigma/beakerx#2554]
On production publications, click on Computer Science. 0 notebooks are displayed even though the count is 15. If you click on Beaker Tutorials, all 15 publications are displayed. See attached screenshot.
![screen shot 2015-09-30 at 10 50 08 am](https://cloud.githubusercontent.com/assets/5454235/10196501/3335b7f8-6761-11e5-84e7-bfc78d609fd5.png)

**Comment by ildipo** [comment]
This is working as expected for me

**Comment by planyon** [comment]
This is working now, Bartek fixed it.
