### ISSUE TITLE
improve error handling

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2558]
![screen shot 2015-09-30 at 12 07 00 pm](https://cloud.githubusercontent.com/assets/963093/10198844/e319b26e-676b-11e5-8374-adede8b5c8d7.png)

**Comment by maksim-lauryk** [comment]
added custom error processing for bad variable names
e.g.
![err_cases](https://cloud.githubusercontent.com/assets/13995034/10224029/c6287e48-6864-11e5-8fbb-b65d6b31ce55.PNG)
