### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2561]
Hi,

I have begun packaging of Beaker Notebook for Debian.

It seems the zip releases at http://beakernotebook.com/downloads contain pre-computed code, whereas source code is here at github. I fail to locate the exact source code corresponding to each of those zip releases, however.

Please tag zip releases here at github.

**Comment by scottdraves** [comment]
thanks for the feedback jonas.  the releases have git hashes that identify the source.
but you are right it's hard to find, IMO we should release src as well.  i could easily do it
from our own servers as zip, right next to the release bins you see.

we don't do "releases" on github since (i vaguely remember?) there was a size
limit but that seems to have gone away: https://help.github.com/articles/distributing-large-binaries/
i realize there are differing approaches to branch management. does debian have a standard?
when we first started using github we used releases but there was a problem and we switched
to just use branches.

do you have an automated system we can plug into?

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-01 04:11:37)

> thanks for the feedback jonas. the releases have git hashes that 
> identify the source.
> but you are right it's hard to find, IMO we should release src as 
> well. i could easily do it from our own servers as zip, right next to 
> the release bins you see.

I noticed the hashes, but failed to find a match:

hash=$(echo beaker-notebook-v1.3.4-0-g37d7759-ubuntu.zip | cut -d- -f5)
git clone https://github.com/twosigma/beaker-notebook
cd beaker-notebook
git log "$hash" --

...leads to "fatal: bad revision 'g37d7759'" :-(

> we don't do "releases" on github since (i vaguely remember?) there was 
> a size limit but that seems to have gone away: 
> https://help.github.com/articles/ distributing-large-binaries/

I don't use Github much myself so am not familiar with their 
constraints, nor the difference between their /tags and /releases - but 
what seems possible and I believe is fine for my needs is if you make a 
tag "v1.3.4" (or "v1.3.4-0" if that subversion isn't from same source) 
the same as you did "v1.3.3-electron": 
https://github.com/twosigma/beaker-notebook/tags

> i realize there are differing approaches to branch management. does 
> debian have a standard?

Most commonly, upstreams of Debian provide source tarballs (and often 
also binary tarballs/zips/rpms/debs that Debian simply ignore), but 
that's not a "standard": Other release styles are not inferior nor less 
correct, as long as source is provided.

> when we first started using github we used releases but there was a 
> problem and we switched to just use branches.

Perhaps ignore "releases" and care only about "tags" at Github?

> do you have an automated system we can plug into?

We have tools to monitor web pages with lists of tarball URLs.  The 
github /tags page and your own /downloads page are both fine for that 
tracking system of ours - but the latter seems to not be true source and 
the former lack (recent) tags.

We might just as easily trck some other data point of yours - it is just 
a guess from my side that the easiest is to tag at Github.  Maybe if you 
explain where that "g37d7759" hash belong I can better understand your 
workflow and align with it - you might not need to change a bit :-)
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by scottdraves** [comment]
previous: https://github.com/twosigma/beaker-notebook/releases/tag/1.3.4
current (as of today!): https://github.com/twosigma/beaker-notebook/releases/tag/1.4
going forward i will release src zip as well.

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-01 23:58:33)

> previous: https://github.com/twosigma/beaker-notebook/releases/tag/1.3.4
> current (as of today!): https://github.com/twosigma/beaker-notebook/releases/
> tag/1.4
> going forward i will release src zip as well.

Looks perfect!
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private
