### ISSUE TITLE
make search box more prominent 

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2563]
![screen shot 2015-09-30 at 10 42 05 pm](https://cloud.githubusercontent.com/assets/963093/10211754/a2f87c66-67c4-11e5-9e57-3506f2f02625.png)

the search box is pretty much lost on this page, but it's a really important element.

one solution: give it more vertical space, make text/icon bigger, replace "Search Published notebooks" with just "Search", give the whole thing a brighter border or something.

another is to give it a dark/color bg.

**Comment by sethkrasnianski** [comment]
Three color options per your label & bg color suggestion, @scottdraves.

<img width="324" alt="screen shot 2015-10-01 at 10 21 36 am" src="https://cloud.githubusercontent.com/assets/1910114/10223368/a317ce92-6826-11e5-8452-fa784c99ebfc.png">
<img width="322" alt="screen shot 2015-10-01 at 10 23 35 am" src="https://cloud.githubusercontent.com/assets/1910114/10223369/a31a174c-6826-11e5-8ccd-081805df4e1a.png">
<img width="311" alt="screen shot 2015-10-01 at 10 24 22 am" src="https://cloud.githubusercontent.com/assets/1910114/10223370/a31a488e-6826-11e5-8553-ae4354a5a9ab.png">

**Comment by sethkrasnianski** [comment]
Actually, the ellipsis in the label should be removed

**Comment by ildipo** [comment]
I like the first

**Comment by scottdraves** [comment]
1s is fine just put in "Enter a Keyword" instead of "Financial Statistics".
Or leave it blank.
