### ISSUE TITLE
widgets output missing (even the static part)

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2566]
the cells with widgets are blank.
they should show, though stuck and inactive, ideally in their last position.
but most important, the computed output should not be missing.
https://pub.beakernotebook.com/#/publications/560caa03-cbd1-4cd8-ac83-9e4e3e45875a

**Comment by scottdraves** [comment]
![screen shot 2015-09-30 at 11 39 00 pm](https://cloud.githubusercontent.com/assets/963093/10212389/7f4d69f4-67cc-11e5-92bc-e93325181aea.png)

**Comment by scottdraves** [comment]
should be
![screen shot 2015-09-30 at 11 39 50 pm](https://cloud.githubusercontent.com/assets/963093/10212397/9527a1fe-67cc-11e5-8b36-bd0a9dfaa8c6.png)

**Comment by grin** [comment]
The main issue is that widget state (including computed output) is not being persisted in the notebook bkr file (at least for me locally), here is an example where I evaluated the factorial cell and saved the notebook:

``` json
"input": {
    "body": [
        "i = interact(factorial, x=(0,100))"
    ]
},
"output": {
    "state": {},
    "result": "<div class=\"output_subarea output_html rendered_html\"><div class=\"ipy-output\" data-msg-id=\"03B94B9CA53C40EB9726901E644A9F04\"><div class=\"widget-area\"><div class=\"widget-subarea\"></div></div></div></div>",
    "selectedType": "Html",
    "pluginName": "Python3",
    "shellId": "FB3E7ACDA2104E6B90AD01D8CFAA1C86",
    "elapsedTime": 255
},
```

When I reopen this notebook the output cell is blank and I have to re-run it to see the widget and then move the slider to see the computed result. Is this correct behavior?

**Comment by scottdraves** [comment]
you are right & this depends on that.

**Comment by scottdraves** [comment]
similar to https://github.com/twosigma/beaker-notebook/issues/2565
