### ISSUE TITLE
image resize filter broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2567]
<img width="455" alt="screen shot 2015-10-01 at 1 06 55 am" src="https://cloud.githubusercontent.com/assets/963093/10213297/2b739f08-67d9-11e5-8124-4e5e532ee7d4.png">

correct vs pub.bn.com

**Comment by ildipo** [comment]
I'll do this one

**Comment by ildipo** [comment]
deployed in pub-staging

**Comment by grin** [comment]
Not sure if it was fixed, if not we could also change image scaling method to `ultra-quality`. Should be less likely to produce that noise pattern (if that was the issue). All available scaling methods are listed here: https://github.com/josephwilk/image-resizer/blob/master/src/image_resizer/scale_methods.clj

**Comment by ildipo** [comment]
did it already on pub-staging
