### ISSUE TITLE
nginx reverse proxy settings

### ISSUE THREAD

**Issue by florianm** [twosigma/beakerx#2570]
Hi, I'm trying to host a beaker notebook server as a docker container (whether that's a good idea or not, and not sure how I'll do multi-user management).

My setup:
- The VM runs nginx as reverse proxy, listening to port 80
- nginx reverse proxies requests to subdomains (rstudio., rshiny., beaker. etc.) to higher internal ports (5000 and up)

I'm trying to find the correct nginx config (for my VM's nginx, not beaker-notebook's internal nginx) to redirect requests to e.g. https://beaker.mydomain.org/ to the docker container.
Any pointers (or working nginx config settings) highly welcome!

**Comment by jeffsteinmetz** [comment]
I have a similar question, that may be related.
I ran your 1.4.2 docker image, and have been unable to figure out how the docker file sets up this directory

`/home/beaker/.beaker/v1/nginx2408163095435771827`

Under this directory, there is an `ssl_cert.pem`, `cert.tmp` and a `conf/nginx.conf`

Is the method by which these are created documented?  

The only place I see this referenced is here
https://github.com/twosigma/beaker-notebook/blob/master/Dockerfile#L42

How the remaining configuration files that show up is elusive.

**Comment by jeffsteinmetz** [comment]
After diving deep into the source, I found this

https://github.com/twosigma/beaker-notebook/blob/4e9a6c9b6a90c9e44c769b6ce7954f2f9f5f96f7/core/src/main/java/com/twosigma/beaker/core/module/config/DefaultBeakerConfig.java#L186

Is there documentation on the command line switches, found here -

https://github.com/twosigma/beaker-notebook/blob/4e9a6c9b6a90c9e44c769b6ce7954f2f9f5f96f7/core/src/main/java/com/twosigma/beaker/core/Main.java#L94

**Comment by mbacou** [comment]
@florianm I realize this is an old thread, but wondering if you ever found a good approach for rolling Beaker behind Nginx? I need a similiar setup with Apache. Thx.

**Comment by florianm** [comment]
@mbacou unfortunately not - beaker never worked nicely for me, so I simply run RStudio Server, RShiny Server, and have my Python-enabled users run Anaconda on their Windows desktops or iPython notebooks on a Ubuntu VM. Here are some docs: http://datawagovau.readthedocs.io/en/latest/workbench.html - hope that helps!

**Comment by mbacou** [comment]
Thanks, right I have RStudio server products installed as well. These are easy to set up, thankfully. Also tried JupyterHub behind apache, but no great success so far.
