### ISSUE TITLE
Rserve install instruction deprecated

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#258]
On the getting started page, the R instruction indicates `install.packages('Rserve',,'http://www.rforge.net/')`. Unfortunately, this yields:

```
> install.packages('Rserve',,'http://www.rforge.net/')
Warning: unable to access index for repository http://www.rforge.net/bin/macosx/mavericks/contrib/3.1

package ‘Rserve’ is available as a source package but not as a binary

Warning message:
package ‘Rserve’ is not available (for R version 3.1.0) 
```

This is misleading, since Rserve is available for this version. Instead, running `install.packages('Rserve')` twice works.

**Comment by jchendy** [comment]
Thanks Tom! We'll be sure to update the instructions ASAP.

**Comment by scottdraves** [comment]
compare with the dev instructions

ScottDraves.com
google.com/+ScottDraves

**Comment by tomlagatta** [comment]
Note: I also had to download XQuartz to get R to work.

**Comment by jchendy** [comment]
I updated the command. Don't have time right now to add the context info. I'll be sure to get to it this afternoon.

**Comment by jchendy** [comment]
Thanks again. Just added XQuartz. I totally dropped the ball when Scott reported these issues after y'all met.
