### ISSUE TITLE
html ul/li indented incorrectly

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2582]
![screen shot 2015-10-01 at 1 46 15 pm](https://cloud.githubusercontent.com/assets/963093/10228829/e5022e8a-6842-11e5-9c68-937d95b619e8.png)

**Comment by scottdraves** [comment]
fix the html in the tutorial, and make it display correctly.

**Comment by alice-kroch** [comment]
Looks like it's not relevant now.
![beaker-ul-li](https://cloud.githubusercontent.com/assets/5072172/11894660/c5fcb15c-a589-11e5-8fa3-849f11c2b76c.png)
