### ISSUE TITLE
need unlisted option for pub

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2588]
so that if you want to share privately or are just testing, you can post a notebook that can't be found search or browsing, only if you know the ID or URL.

should be just a checkbox in the pub form.

**Comment by scottdraves** [comment]
also consider: license grant checkbox to put the notebook itself under apache2.

**Comment by grin** [comment]
if apache2 license is granted, should it be visible in the UI for other users when browsing publications? or it should only be saved in the database for internal use?

**Comment by scottdraves** [comment]
don't implement the license stuff yet, that would need legal review.

**Comment by grin** [comment]
implemented in https://github.com/twosigma/bunsen/pull/1242
