### ISSUE TITLE
admin needs more edit powers over metadata

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2593]
need set category & owner.

<img width="879" alt="screen shot 2015-10-02 at 10 07 19 pm" src="https://cloud.githubusercontent.com/assets/963093/10260997/13538544-6952-11e5-9583-0268f3955b1d.png">

**Comment by ildipo** [comment]
and title and text

**Comment by grin** [comment]
What do you think about separate publication edit form for admins:
![image](https://cloud.githubusercontent.com/assets/12468/10310506/8c188554-6c42-11e5-8e86-6c4c83af9e01.png)
? 
...with category as a drop-down, author as a dropdown with all users (or text input with autocompletion based on name).
Then I could add the edit button next to "Delete publication" in publication metadata section which would open the form.

**Comment by grin** [comment]
Implemented in: https://github.com/twosigma/bunsen/pull/1235
