### ISSUE TITLE
R Error ... R language backend failed!

### ISSUE THREAD

**Issue by polaris-bioit** [twosigma/beakerx#2598]
stderr:
Oct 04, 2015 12:12:29 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:421)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:472)
Oct 04, 2015 12:21:13 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:421)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:472)
Oct 04, 2015 12:29:52 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:421)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:472)

**Comment by scottdraves** [comment]
Hi, thanks for the report.  What is your Operating System?  What version of Beaker are you running?
If you run base R (open a terminal and run `R`), not RStudio) and give the command

```
installed.packages()
```

what is the output?

**Comment by jslmann** [comment]
Hello! 

preliminaries:
os: OSX 10.11
beaker: 1.4.1 (1)

i get the same error, before I show the installed.packages() result, a bit of context:
I use brew and anaconda, not because I'm smart just cause that's how things happened
bouncing from one hack to another...
that said,  'which r' gives the anaconda path.
when I open r from a bash shell and try: "install.package('Rserve')"
I will get the following after compiling all the required files with some warnings: 

> ...
> *\* testing if installed package can be loaded
> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
>   unable to load shared object '/Users/jlatmann/anaconda/lib/R/library/Rserve/libs/Rserve.so':
>   dlopen(/Users/jlatmann/anaconda/lib/R/library/Rserve/libs/Rserve.so, 6): Library not loaded: libssl.1.0.0.dylib
>   Referenced from: /Users/jlatmann/anaconda/lib/R/library/Rserve/libs/Rserve.so
>   Reason: image not found
> Error: loading failed
> Execution halted
> ERROR: loading failed
> - removing ‘/Users/jlatmann/anaconda/lib/R/library/Rserve’
> - restoring previous ‘/Users/jlatmann/anaconda/lib/R/library/Rserve’

I did, however, install all the required libraries by pulling them off of the anaconda cloud.

context done.
here is installed.packages():

and thank-you in advance for any help you can provide!

> installed.packages()
>              Package        LibPath                                  Version  
> base         "base"         "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> base64enc    "base64enc"    "/Users/jlatmann/anaconda/lib/R/library" "0.1-3"  
> BH           "BH"           "/Users/jlatmann/anaconda/lib/R/library" "1.58.0-1"
> bitops       "bitops"       "/Users/jlatmann/anaconda/lib/R/library" "1.0-6"  
> boot         "boot"         "/Users/jlatmann/anaconda/lib/R/library" "1.3-17"  
> brew         "brew"         "/Users/jlatmann/anaconda/lib/R/library" "1.0-6"  
> class        "class"        "/Users/jlatmann/anaconda/lib/R/library" "7.3-14"  
> cluster      "cluster"      "/Users/jlatmann/anaconda/lib/R/library" "2.0.3"  
> codetools    "codetools"    "/Users/jlatmann/anaconda/lib/R/library" "0.2-14"  
> colorspace   "colorspace"   "/Users/jlatmann/anaconda/lib/R/library" "1.2-6"  
> compiler     "compiler"     "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> curl         "curl"         "/Users/jlatmann/anaconda/lib/R/library" "0.9.3"  
> datasets     "datasets"     "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> devtools     "devtools"     "/Users/jlatmann/anaconda/lib/R/library" "1.9.1"  
> dichromat    "dichromat"    "/Users/jlatmann/anaconda/lib/R/library" "2.0-0"  
> digest       "digest"       "/Users/jlatmann/anaconda/lib/R/library" "0.6.8"  
> evaluate     "evaluate"     "/Users/jlatmann/anaconda/lib/R/library" "0.8"  
> foreign      "foreign"      "/Users/jlatmann/anaconda/lib/R/library" "0.8-66"  
> ggplot2      "ggplot2"      "/Users/jlatmann/anaconda/lib/R/library" "1.0.1"  
> git2r        "git2r"        "/Users/jlatmann/anaconda/lib/R/library" "0.11.0"  
> graphics     "graphics"     "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> grDevices    "grDevices"    "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> grid         "grid"         "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> gtable       "gtable"       "/Users/jlatmann/anaconda/lib/R/library" "0.1.2"  
> httr         "httr"         "/Users/jlatmann/anaconda/lib/R/library" "1.0.0"  
> IRdisplay    "IRdisplay"    "/Users/jlatmann/anaconda/lib/R/library" "0.3"  
> IRkernel     "IRkernel"     "/Users/jlatmann/anaconda/lib/R/library" "0.4"  
> jpeg         "jpeg"         "/Users/jlatmann/anaconda/lib/R/library" "0.1-8"  
> jsonlite     "jsonlite"     "/Users/jlatmann/anaconda/lib/R/library" "0.9.17"  
> KernSmooth   "KernSmooth"   "/Users/jlatmann/anaconda/lib/R/library" "2.23-15" 
> labeling     "labeling"     "/Users/jlatmann/anaconda/lib/R/library" "0.3"  
> lattice      "lattice"      "/Users/jlatmann/anaconda/lib/R/library" "0.20-33" 
> magrittr     "magrittr"     "/Users/jlatmann/anaconda/lib/R/library" "1.5"  
> MASS         "MASS"         "/Users/jlatmann/anaconda/lib/R/library" "7.3-44"  
> Matrix       "Matrix"       "/Users/jlatmann/anaconda/lib/R/library" "1.2-2"  
> memoise      "memoise"      "/Users/jlatmann/anaconda/lib/R/library" "0.2.1"  
> methods      "methods"      "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> mgcv         "mgcv"         "/Users/jlatmann/anaconda/lib/R/library" "1.8-7"  
> mime         "mime"         "/Users/jlatmann/anaconda/lib/R/library" "0.4"  
> munsell      "munsell"      "/Users/jlatmann/anaconda/lib/R/library" "0.4.2"  
> nlme         "nlme"         "/Users/jlatmann/anaconda/lib/R/library" "3.1-122" 
> nnet         "nnet"         "/Users/jlatmann/anaconda/lib/R/library" "7.3-11"  
> parallel     "parallel"     "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> plyr         "plyr"         "/Users/jlatmann/anaconda/lib/R/library" "1.8.3"  
> proto        "proto"        "/Users/jlatmann/anaconda/lib/R/library" "0.3-10"  
> R6           "R6"           "/Users/jlatmann/anaconda/lib/R/library" "2.1.1"  
> RColorBrewer "RColorBrewer" "/Users/jlatmann/anaconda/lib/R/library" "1.1-2"  
> Rcpp         "Rcpp"         "/Users/jlatmann/anaconda/lib/R/library" "0.12.1"  
> repr         "repr"         "/Users/jlatmann/anaconda/lib/R/library" "0.3"  
> reshape2     "reshape2"     "/Users/jlatmann/anaconda/lib/R/library" "1.4.1"  
> RJSONIO      "RJSONIO"      "/Users/jlatmann/anaconda/lib/R/library" "1.3-0"  
> roxygen2     "roxygen2"     "/Users/jlatmann/anaconda/lib/R/library" "4.1.1"  
> rpart        "rpart"        "/Users/jlatmann/anaconda/lib/R/library" "4.1-10"  
> Rserve       "Rserve"       "/Users/jlatmann/anaconda/lib/R/library" "1.7-3"  
> rstudioapi   "rstudioapi"   "/Users/jlatmann/anaconda/lib/R/library" "0.3.1"  
> rversions    "rversions"    "/Users/jlatmann/anaconda/lib/R/library" "1.0.2"  
> rzmq         "rzmq"         "/Users/jlatmann/anaconda/lib/R/library" "0.7.7"  
> scales       "scales"       "/Users/jlatmann/anaconda/lib/R/library" "0.3.0"  
> spatial      "spatial"      "/Users/jlatmann/anaconda/lib/R/library" "7.3-11"  
> splines      "splines"      "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> stats        "stats"        "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> stats4       "stats4"       "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> stringi      "stringi"      "/Users/jlatmann/anaconda/lib/R/library" "0.5-5"  
> stringr      "stringr"      "/Users/jlatmann/anaconda/lib/R/library" "1.0.0"  
> survival     "survival"     "/Users/jlatmann/anaconda/lib/R/library" "2.38-3"  
> tcltk        "tcltk"        "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> tools        "tools"        "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> utils        "utils"        "/Users/jlatmann/anaconda/lib/R/library" "3.2.2"  
> uuid         "uuid"         "/Users/jlatmann/anaconda/lib/R/library" "0.1-2"  
> whisker      "whisker"      "/Users/jlatmann/anaconda/lib/R/library" "0.3-2"  
> xml2         "xml2"         "/Users/jlatmann/anaconda/lib/R/library" "0.1.2"  
>              Priority Depends  
> base         "base"   NA  
> base64enc    NA       "R (>= 2.9.0)"  
> BH           NA       NA  
> bitops       NA       NA  
> boot         NA       "R (>= 3.0.0), graphics, stats"  
> brew         NA       NA  
> class        NA       "R (>= 3.0.0), stats, utils"  
> cluster      NA       "R (>= 2.15.0), utils"  
> codetools    NA       "R (>= 2.1)"  
> colorspace   NA       "R (>= 2.13.0), methods"  
> compiler     "base"   NA  
> curl         NA       "R (>= 2.10.0)"  
> datasets     "base"   NA  
> devtools     NA       "R (>= 3.0.2)"  
> dichromat    NA       "R (>= 2.10), stats"  
> digest       NA       "R (>= 2.4.1)"  
> evaluate     NA       "R (>= 3.0.2)"  
> foreign      NA       "R (>= 3.0.0)"  
> ggplot2      NA       "R (>= 2.14), stats, methods"  
> git2r        NA       "R (>= 3.0.2)"  
> graphics     "base"   NA  
> grDevices    "base"   NA  
> grid         "base"   NA  
> gtable       NA       "R (>= 2.14), grid"  
> httr         NA       "R (>= 3.0.0)"  
> IRdisplay    NA       "\nR (>= 3.0.1)"  
> IRkernel     NA       "\nR (>= 3.0.1)"  
> jpeg         NA       "R (>= 2.9.0)"  
> jsonlite     NA       "methods"  
> KernSmooth   NA       "R (>= 2.5.0), stats"  
> labeling     NA       NA  
> lattice      NA       "R (>= 3.0.0)"  
> magrittr     NA       NA  
> MASS         NA       "R (>= 3.1.0), grDevices, graphics, stats, utils"
> Matrix       NA       "R (>= 3.0.1)"  
> memoise      NA       NA  
> methods      "base"   NA  
> mgcv         NA       "R (>= 2.14.0), nlme (>= 3.1-64)"  
> mime         NA       NA  
> munsell      NA       NA  
> nlme         NA       "graphics, stats, R (>= 3.0.0)"  
> nnet         NA       "R (>= 2.14.0), stats, utils"  
> parallel     "base"   NA  
> plyr         NA       "R (>= 3.1.0)"  
> proto        NA       NA  
> R6           NA       "R (>= 3.0)"  
> RColorBrewer NA       "R (>= 2.0.0)"  
> Rcpp         NA       "R (>= 3.0.0)"  
> repr         NA       "\nR (>= 3.0.1)"  
> reshape2     NA       NA  
> RJSONIO      NA       NA  
> roxygen2     NA       "R (>= 3.0.2)"  
> rpart        NA       "R (>= 2.15.0), graphics, stats, grDevices"  
> Rserve       NA       "R (>= 1.5.0)"  
> rstudioapi   NA       NA  
> rversions    NA       NA  
> rzmq         NA       NA  
> scales       NA       "R (>= 2.13)"  
> spatial      NA       "R (>= 3.0.0), graphics, stats, utils"  
> splines      "base"   NA  
> stats        "base"   NA  
> stats4       "base"   NA  
> stringi      NA       "R (>= 2.13.1)"  
> stringr      NA       "R (>= 2.14)"  
> survival     NA       "R (>= 2.13.0), graphics, stats"  
> tcltk        "base"   NA  
> tools        "base"   NA  
> utils        "base"   NA  
> uuid         NA       "R (>= 2.9.0)"  
> whisker      NA       NA  
> xml2         NA       "R (>= 3.1.0)"  
>              Imports  
> base         NA  
> base64enc    NA  
> BH           NA  
> bitops       NA  
> boot         NA  
> brew         NA  
> class        "MASS"  
> cluster      "graphics, grDevices, stats"  
> codetools    NA  
> colorspace   "graphics"  
> compiler     NA  
> curl         NA  
> datasets     NA  
> devtools     "httr (>= 0.4), curl (>= 0.9), utils, tools, methods, memoise,\nwhisker, evaluate, digest, rstudioapi (>= 0.2.0), jsonlite,\nroxygen2 (>= 4.1.0), rversions, stats, git2r (>= 0.11.0)"
> dichromat    NA  
> digest       NA  
> evaluate     "methods, stringr (>= 0.6.2)"  
> foreign      "methods, utils, stats"  
> ggplot2      "plyr (>= 1.7.1), digest, grid, gtable (>= 0.1.1), reshape2,\nscales (>= 0.2.3), proto, MASS"  
> git2r        "graphics, methods, utils"  
> graphics     "grDevices"  
> grDevices    NA  
> grid         "grDevices"  
> gtable       NA  
> httr         "digest, jsonlite, mime, curl (>= 0.6), R6, stringr (>= 0.6.1)"  
> IRdisplay    "\nrepr,\nbase64enc"  
> IRkernel     "\nrepr,\nmethods,\nevaluate (>= 0.5.4),\nIRdisplay,\nrzmq (>= 0.7.0),\njsonlite (>= 0.9.6),\nuuid,\ndigest"  
> jpeg         NA  
> jsonlite     NA  
> KernSmooth   NA  
> labeling     NA  
> lattice      "grid, grDevices, graphics, stats, utils"  
> magrittr     NA  
> MASS         "methods"  
> Matrix       "methods, graphics, grid, stats, utils, lattice"  
> memoise      "digest"  
> methods      "utils"  
> mgcv         "methods, stats, graphics, Matrix"  
> mime         "tools"  
> munsell      "colorspace"  
> nlme         "lattice"  
> nnet         NA  
> parallel     "tools"  
> plyr         "Rcpp (>= 0.11.0)"  
> proto        NA  
> R6           NA  
> RColorBrewer NA  
> Rcpp         "methods, utils"  
> repr         NA  
> reshape2     "plyr (>= 1.8.1), stringr, Rcpp"  
> RJSONIO      "methods"  
> roxygen2     "stringr (>= 0.5), brew, digest, methods, Rcpp (>= 0.11.0)"  
> rpart        NA  
> Rserve       NA  
> rstudioapi   NA  
> rversions    "curl, xml2, utils"  
> rzmq         NA  
> scales       "RColorBrewer, dichromat, plyr, munsell (>= 0.2), labeling,\nmethods, Rcpp"  
> spatial      NA  
> splines      "graphics, stats"  
> stats        NA  
> stats4       "graphics, methods, stats"  
> stringi      "tools, utils, stats"  
> stringr      "stringi (>= 0.4.1), magrittr"  
> survival     "splines, methods"  
> tcltk        "utils"  
> tools        NA  
> utils        NA  
> uuid         NA  
> whisker      NA  
> xml2         "Rcpp"  
>              LinkingTo  
> base         NA  
> base64enc    NA  
> BH           NA  
> bitops       NA  
> boot         NA  
> brew         NA  
> class        NA  
> cluster      NA  
> codetools    NA  
> colorspace   NA  
> compiler     NA  
> curl         NA  
> datasets     NA  
> devtools     NA  
> dichromat    NA  
> digest       NA  
> evaluate     NA  
> foreign      NA  
> ggplot2      NA  
> git2r        NA  
> graphics     NA  
> grDevices    NA  
> grid         NA  
> gtable       NA  
> httr         NA  
> IRdisplay    NA  
> IRkernel     NA  
> jpeg         NA  
> jsonlite     NA  
> KernSmooth   NA  
> labeling     NA  
> lattice      NA  
> magrittr     NA  
> MASS         NA  
> Matrix       NA  
> memoise      NA  
> methods      NA  
> mgcv         NA  
> mime         NA  
> munsell      NA  
> nlme         NA  
> nnet         NA  
> parallel     NA  
> plyr         "Rcpp"  
> proto        NA  
> R6           NA  
> RColorBrewer NA  
> Rcpp         NA  
> repr         NA  
> reshape2     "Rcpp"  
> RJSONIO      NA  
> roxygen2     "Rcpp"  
> rpart        NA  
> Rserve       NA  
> rstudioapi   NA  
> rversions    NA  
> rzmq         NA  
> scales       "Rcpp"  
> spatial      NA  
> splines      NA  
> stats        NA  
> stats4       NA  
> stringi      NA  
> stringr      NA  
> survival     NA  
> tcltk        NA  
> tools        NA  
> utils        NA  
> uuid         NA  
> whisker      NA  
> xml2         "Rcpp (>= 0.11.4.6), BH"
>              Suggests  
> base         NA  
> base64enc    NA  
> BH           NA  
> bitops       NA  
> boot         "MASS, survival"  
> brew         NA  
> class        NA  
> cluster      "MASS"  
> codetools    NA  
> colorspace   "KernSmooth, MASS, kernlab, mvtnorm, vcd, dichromat, tcltk"  
> compiler     NA  
> curl         "testthat, knitr, jsonlite, rmarkdown, magrittr"  
> datasets     NA  
> devtools     "testthat (>= 0.7), BiocInstaller, Rcpp (>= 0.10.0), MASS,\nrmarkdown, knitr, lintr (>= 0.2.1), bitops"
> dichromat    NA  
> digest       NA  
> evaluate     "testthat, lattice, ggplot2"  
> foreign      NA  
> ggplot2      "quantreg, Hmisc, mapproj, maps, hexbin, maptools, multcomp,\nnlme, testthat, knitr, mgcv"  
> git2r        NA  
> graphics     NA  
> grDevices    NA  
> grid         "lattice"  
> gtable       "testthat, plyr"  
> httr         "base64enc, httpuv, jpeg, knitr, PKI (>= 0.1-2), png, testthat\n(>= 0.8.0), XML"  
> IRdisplay    NA  
> IRkernel     NA  
> jpeg         NA  
> jsonlite     "curl (>= 0.5), plyr, testthat, knitr, rmarkdown, R.rsp"  
> KernSmooth   "MASS"  
> labeling     NA  
> lattice      "KernSmooth, MASS"  
> magrittr     "testthat, knitr"  
> MASS         "lattice, nlme, nnet, survival"  
> Matrix       "expm, MASS"  
> memoise      NA  
> methods      NA  
> mgcv         "splines, parallel, survival, MASS"  
> mime         NA  
> munsell      "ggplot2 (>= 0.9.2)"  
> nlme         "Hmisc, MASS"  
> nnet         "MASS"  
> parallel     NA  
> plyr         "abind, testthat, tcltk, foreach, doParallel, itertools,\niterators"  
> proto        "graph, Rgraphviz"  
> R6           "knitr, microbenchmark, pryr, testthat, ggplot2, scales"  
> RColorBrewer NA  
> Rcpp         "RUnit, inline, rbenchmark, highlight, pkgKitten (>= 0.1.2)"  
> repr         "\nhighr"  
> reshape2     "testthat (>= 0.8.0), lattice"  
> RJSONIO      NA  
> roxygen2     "testthat (>= 0.8.0), knitr"  
> rpart        "survival"  
> Rserve       "RSclient"  
> rstudioapi   NA  
> rversions    NA  
> rzmq         NA  
> scales       "testthat (>= 0.8)"  
> spatial      "MASS"  
> splines      NA  
> stats        NA  
> stats4       NA  
> stringi      NA  
> stringr      "testthat, knitr"  
> survival     "cmprsk"  
> tcltk        NA  
> tools        "XML"  
> utils        NA  
> uuid         NA  
> whisker      "markdown"  
> xml2         "testthat, curl"  
>              Enhances  
> base         NA  
> base64enc    "png"  
> BH           NA  
> bitops       NA  
> boot         NA  
> brew         NA  
> class        NA  
> cluster      NA  
> codetools    NA  
> colorspace   NA  
> compiler     NA  
> curl         NA  
> datasets     NA  
> devtools     NA  
> dichromat    NA  
> digest       NA  
> evaluate     NA  
> foreign      NA  
> ggplot2      "sp"  
> git2r        NA  
> graphics     NA  
> grDevices    NA  
> grid         NA  
> gtable       NA  
> httr         NA  
> IRdisplay    NA  
> IRkernel     NA  
> jpeg         NA  
> jsonlite     NA  
> KernSmooth   NA  
> labeling     NA  
> lattice      "chron"  
> magrittr     NA  
> MASS         NA  
> Matrix       "MatrixModels, graph, SparseM, sfsmisc"
> memoise      NA  
> methods      NA  
> mgcv         NA  
> mime         NA  
> munsell      NA  
> nlme         NA  
> nnet         NA  
> parallel     "snow, nws, Rmpi"  
> plyr         NA  
> proto        NA  
> R6           NA  
> RColorBrewer NA  
> Rcpp         NA  
> repr         NA  
> reshape2     NA  
> RJSONIO      NA  
> roxygen2     NA  
> rpart        NA  
> Rserve       NA  
> rstudioapi   NA  
> rversions    NA  
> rzmq         NA  
> scales       NA  
> spatial      NA  
> splines      NA  
> stats        NA  
> stats4       NA  
> stringi      NA  
> stringr      NA  
> survival     NA  
> tcltk        NA  
> tools        NA  
> utils        NA  
> uuid         NA  
> whisker      NA  
> xml2         NA  
>              License                          License_is_FOSS
> base         "Part of R 3.2.2"                NA  
> base64enc    "GPL-2 | GPL-3"                  NA  
> BH           "BSL-1.0"                        NA  
> bitops       "GPL (>= 2)"                     NA  
> boot         "Unlimited"                      NA  
> brew         "GPL-2"                          NA  
> class        "GPL-2 | GPL-3"                  NA  
> cluster      "GPL (>= 2)"                     NA  
> codetools    "GPL"                            NA  
> colorspace   "BSD_3_clause + file LICENSE"    NA  
> compiler     "Part of R 3.2.2"                NA  
> curl         "MIT + file LICENSE"             NA  
> datasets     "Part of R 3.2.2"                NA  
> devtools     "GPL (>= 2)"                     NA  
> dichromat    "GPL-2"                          NA  
> digest       "GPL-2"                          NA  
> evaluate     "MIT + file LICENSE"             NA  
> foreign      "GPL (>= 2)"                     NA  
> ggplot2      "GPL-2"                          NA  
> git2r        "GPL-2"                          NA  
> graphics     "Part of R 3.2.2"                NA  
> grDevices    "Part of R 3.2.2"                NA  
> grid         "Part of R 3.2.2"                NA  
> gtable       "GPL-2"                          NA  
> httr         "MIT + file LICENSE"             NA  
> IRdisplay    "MIT + file LICENSE"             NA  
> IRkernel     "MIT + file LICENSE"             NA  
> jpeg         "GPL-2 | GPL-3"                  NA  
> jsonlite     "MIT + file LICENSE"             NA  
> KernSmooth   "Unlimited"                      NA  
> labeling     "MIT + file LICENSE | Unlimited" NA  
> lattice      "GPL (>= 2)"                     NA  
> magrittr     "MIT + file LICENSE"             NA  
> MASS         "GPL-2 | GPL-3"                  NA  
> Matrix       "GPL (>= 2)"                     NA  
> memoise      "MIT + file LICENSE"             NA  
> methods      "Part of R 3.2.2"                NA  
> mgcv         "GPL (>= 2)"                     NA  
> mime         "GPL-2"                          NA  
> munsell      "MIT + file LICENSE"             NA  
> nlme         "GPL (>= 2)"                     NA  
> nnet         "GPL-2 | GPL-3"                  NA  
> parallel     "Part of R 3.2.2"                NA  
> plyr         "MIT + file LICENSE"             NA  
> proto        "GPL-2"                          NA  
> R6           "MIT + file LICENSE"             NA  
> RColorBrewer "Apache License 2.0"             NA  
> Rcpp         "GPL (>= 2)"                     NA  
> repr         "GPL-3"                          NA  
> reshape2     "MIT + file LICENSE"             NA  
> RJSONIO      "BSD_3_clause + file LICENSE"    NA  
> roxygen2     "GPL (>= 2)"                     NA  
> rpart        "GPL-2 | GPL-3"                  NA  
> Rserve       "GPL-2 | file LICENSE"           NA  
> rstudioapi   "MIT + file LICENSE"             NA  
> rversions    "MIT + file LICENSE"             NA  
> rzmq         "GPL-3"                          NA  
> scales       "MIT + file LICENSE"             NA  
> spatial      "GPL-2 | GPL-3"                  NA  
> splines      "Part of R 3.2.2"                NA  
> stats        "Part of R 3.2.2"                NA  
> stats4       "Part of R 3.2.2"                NA  
> stringi      "file LICENSE"                   "yes"  
> stringr      "GPL-2"                          NA  
> survival     "LGPL (>= 2)"                    NA  
> tcltk        "Part of R 3.2.2"                NA  
> tools        "Part of R 3.2.2"                NA  
> utils        "Part of R 3.2.2"                NA  
> uuid         "MIT + file LICENSE"             NA  
> whisker      "GPL-3"                          NA  
> xml2         "GPL (>= 2)"                     NA  
>              License_restricts_use OS_type MD5sum NeedsCompilation Built  
> base         NA                    NA      NA     NA               "3.2.2"
> base64enc    NA                    NA      NA     "yes"            "3.2.1"
> BH           NA                    NA      NA     "no"             "3.2.2"
> bitops       NA                    NA      NA     "yes"            "3.2.1"
> boot         NA                    NA      NA     "no"             "3.2.2"
> brew         NA                    NA      NA     NA               "3.2.2"
> class        NA                    NA      NA     "yes"            "3.2.1"
> cluster      NA                    NA      NA     "yes"            "3.2.2"
> codetools    NA                    NA      NA     "no"             "3.2.2"
> colorspace   NA                    NA      NA     "yes"            "3.2.2"
> compiler     NA                    NA      NA     NA               "3.2.2"
> curl         NA                    NA      NA     "yes"            "3.2.2"
> datasets     NA                    NA      NA     NA               "3.2.2"
> devtools     NA                    NA      NA     "yes"            "3.2.2"
> dichromat    NA                    NA      NA     NA               "3.2.2"
> digest       NA                    NA      NA     "yes"            "3.2.2"
> evaluate     NA                    NA      NA     "no"             "3.2.2"
> foreign      NA                    NA      NA     "yes"            "3.2.2"
> ggplot2      NA                    NA      NA     "no"             "3.2.2"
> git2r        NA                    NA      NA     "yes"            "3.2.2"
> graphics     NA                    NA      NA     NA               "3.2.2"
> grDevices    NA                    NA      NA     NA               "3.2.2"
> grid         NA                    NA      NA     NA               "3.2.2"
> gtable       NA                    NA      NA     NA               "3.2.2"
> httr         NA                    NA      NA     "no"             "3.2.2"
> IRdisplay    NA                    NA      NA     NA               "3.2.1"
> IRkernel     NA                    NA      NA     NA               "3.2.1"
> jpeg         NA                    NA      NA     "yes"            "3.2.2"
> jsonlite     NA                    NA      NA     "yes"            "3.2.2"
> KernSmooth   NA                    NA      NA     "yes"            "3.2.2"
> labeling     NA                    NA      NA     "no"             "3.2.2"
> lattice      NA                    NA      NA     "yes"            "3.2.2"
> magrittr     NA                    NA      NA     "no"             "3.2.2"
> MASS         NA                    NA      NA     "yes"            "3.2.2"
> Matrix       NA                    NA      NA     "yes"            "3.2.1"
> memoise      NA                    NA      NA     "no"             "3.2.2"
> methods      NA                    NA      NA     NA               "3.2.2"
> mgcv         NA                    NA      NA     "yes"            "3.2.1"
> mime         NA                    NA      NA     "yes"            "3.2.2"
> munsell      NA                    NA      NA     "no"             "3.2.2"
> nlme         NA                    NA      NA     "yes"            "3.2.1"
> nnet         NA                    NA      NA     "yes"            "3.2.2"
> parallel     NA                    NA      NA     NA               "3.2.2"
> plyr         NA                    NA      NA     "yes"            "3.2.2"
> proto        NA                    NA      NA     NA               "3.2.2"
> R6           NA                    NA      NA     "no"             "3.2.2"
> RColorBrewer NA                    NA      NA     "no"             "3.2.2"
> Rcpp         NA                    NA      NA     "yes"            "3.2.2"
> repr         NA                    NA      NA     NA               "3.2.1"
> reshape2     NA                    NA      NA     "yes"            "3.2.2"
> RJSONIO      NA                    NA      NA     "yes"            "3.2.2"
> roxygen2     NA                    NA      NA     "yes"            "3.2.2"
> rpart        NA                    NA      NA     "yes"            "3.2.2"
> Rserve       NA                    NA      NA     "yes"            "3.2.2"
> rstudioapi   NA                    NA      NA     "no"             "3.2.2"
> rversions    NA                    NA      NA     "no"             "3.2.2"
> rzmq         NA                    NA      NA     "yes"            "3.2.1"
> scales       NA                    NA      NA     "yes"            "3.2.2"
> spatial      NA                    NA      NA     "yes"            "3.2.2"
> splines      NA                    NA      NA     NA               "3.2.2"
> stats        NA                    NA      NA     NA               "3.2.2"
> stats4       NA                    NA      NA     NA               "3.2.2"
> stringi      NA                    NA      NA     "yes"            "3.2.2"
> stringr      NA                    NA      NA     "no"             "3.2.2"
> survival     NA                    NA      NA     "yes"            "3.2.2"
> tcltk        NA                    NA      NA     NA               "3.2.2"
> tools        NA                    NA      NA     NA               "3.2.2"
> utils        NA                    NA      NA     NA               "3.2.2"
> uuid         NA                    NA      NA     "yes"            "3.2.1"
> whisker      NA                    NA      NA     "no"             "3.2.2"
> xml2         NA                    NA      NA     "yes"            "3.2.2"

**Comment by filipstachura** [comment]
Same for me. Two days ago everything worked fine!

OS: Win 8.1
Beaker: beaker-notebook-1.4.2-0-ge55c059-windows
installed.packages: https://gist.github.com/filipstachura/b168e6838853ec618d42

_Edit:_ For me reinstalling required R packages under current user has solved the problem.

**Comment by vascoosx** [comment]
I am working on Win 7 and did @filipstachura suggestion but it did not work

**Comment by ArthurZ** [comment]
Hmm on Win 7 Pro.
Can't overcome this error.
IPython starts, not R. 
Points to issues with `Rserve`
I went to the base non-gui R of each bitness and did ` install.packages('Rserve')`
Restarted Beaker, same error:
`
stderr:
[Thread-11] INFO com.twosigma.beaker.r.module.ErrorGobbler - Error line not captured: 'Error in library(Rserve) : there is no package called 'Rserve''`

**Comment by scottdraves** [comment]
Hi Arthur, perhaps you have more than one version of R installed and the one you that's running in Beaker is different from the one where you are installing the  package.

On Windows Beaker uses the registry to find the executable:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/r/src/dist/rPlugin#L30
but the PATH has precedence.

**Comment by ArthurZ** [comment]
Hi @scottdraves,
you are right, I also have MS R Open, too:
![r reg settings](https://cloud.githubusercontent.com/assets/701808/20868886/dfceb0b0-ba34-11e6-9824-07ff0568d6b8.png)
I guess the top entry wins as the code stops at the 1st match.
But I would like Beaker to work under this setup. Is that possible?

**Comment by ArthurZ** [comment]
Attempting to answer my own question: 
I saw there is an option of adding a preference for a language in `.beaker\v1\config\beaker.pref.json`
So I did for R as:
`"R" : {
      "path" : "C:\\Program Files\\R\\R-3.3.2\\bin"
    }`
Alas, I see R is starting, but the same error referencing RServe persists:

> 'Error in library(Rserve) : there is no package called 'Rserve''

I created a [Gist](https://gist.github.com/ArthurZ/1fc55e89a1b434cffe04086a38e0b8a2) with more details preceding and after it occurs taken from the Beaker console (web server) output in hopes it will help resolving the issue.
Thank you!

**Comment by RoccoDAnt** [comment]
Dear ArthurZ, I had the same problem. I solved it:
1. checking that "RServe" was installed in the used version of R (in this case "R-3.3.2").
2. removing `\\bin` at the end of the path set in the file `.beaker\v1\config\beaker.pref.json`.
Best,
Rocco
