### ISSUE TITLE
what is effective license of classloader (GPL-3+ and/or Apache-2.0+)

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2600]
Most files (8 of 10) below plugin/jvm/src/main/java/com/twosigma/beaker/jvm/classloader/ contain license grant for both Apache-2.0+ and GPL-3+.

Written like that I would normally assume both licenses to be in effect - i.e. not a dual-licensing (a choice between one license _OR_ the other) but an integration (both one _AND_ the other).

...but the license of Beaker Notebook in general is licensed as Apache-2.0+ so this surprises me: The result of Apache-2.0 AND GPL-3+ is effectively GPL-3+ as documented e.g. at https://www.apache.org/licenses/GPL-compatibility.html

If the effective license of the classloader is Apache-2.0+ then I recommend to clarify how that is the case - e.g. whether Kamran Zafar has agreed to relicense (and if so, why not simply drop that irrelevant GPL-3.0+ license grant?)

**Comment by jonassmedegaard** [comment]
Whoops - it is LGPL,-3+, not GPL-3+

But question remains: How are they related, and doesn't that affect (binary) redistribution to effectively be GPL-3+?

Not a problem for Debian redistribution, but seems unintended by Two Sigma.

**Comment by jonassmedegaard** [comment]
...and it is Apache-2.0 (not Apache-2.0+) - not that it changes the question, just for the record.

**Comment by scottdraves** [comment]
I thought it was Apache2: https://github.com/kamranzafar/JCL
is that a later version?  You are right it does say LGLP in the code.

**Comment by scottdraves** [comment]
OK http://kamranzafar.github.io/JCL/
he says:

> The entire library, including it’s code-base and documentation is available under a dual-license, whereby it can be used under the terms and conditions of LGPL and Apache License 2.0.

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-03 22:23:21)

> OK http://kamranzafar.github.io/JCL/
> he says:
> 
> ```
> The entire library, including it’s code-base and documentation is available
> under a dual-license, whereby it can be used under the terms and conditions
> of LGPL and Apache License 2.0.
> ```

Uhm, but there's an annoying "and" at the end of that sentence :-P

README.md at https://github.com/kamranzafar/JCL mentions only 
Apache-2.0, not LGPL.  I guess intent was either-or but wording vague. 
It was recently clarified: 
https://github.com/kamranzafar/JCL/commit/f279287

If you wanna be on the safe side, I suggest you to update to newer 
relicensed code.  As mentioned already not a problem for Debian 
packaging.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by scottdraves** [comment]
You are right, "and" vs "or" in a sentence like that is ambiguous.  But "Dual-license" is a standard term, and it means you can pick which license to use.  We pick Apache 2.0.

**Comment by ildipo** [comment]
We are actually moving away from JCL. I think already in 1.4 it is not really used anymore in favor of a different mechanism.

**Comment by scottdraves** [comment]
Disagree:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/groovy/src/main/java/com/twosigma/beaker/groovy/utils/GroovyDynamicClassLoader.java#L29-L30

**Comment by scottdraves** [comment]
Davide pointed out that it's used by GroovyClassLoader but GroovyClassLoader is not used :)
So best solution is just to remove JCL code.
