### ISSUE TITLE
*65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.73210

### ISSUE THREAD

**Issue by rahulpathakgit** [twosigma/beakerx#2601]
Everytime I run the beaker then always shows "Initializing Ipython" and "Initializing R" . Both are already installed.

platform@platform-Vostro-3546:~/Downloads/beaker-notebook-1.4-0-gbb3ca3d-ubuntu$ ./beaker.command 
starting nginx instance (/home/platform/Downloads/beaker-notebook-1.4-0-gbb3ca3d-ubuntu/nginx)
nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

restart-nginx-IPython-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
restart-nginx-IPython-stderr>2015/10/04 11:02:47 [notice] 19992#0: signal process started
Running
0: /home/platform/Downloads/beaker-notebook-1.4-0-gbb3ca3d-ubuntu/config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin
1: 8804
Done starting IPython
nginx-stderr>2015/10/04 11:02:48 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:48 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:48 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:48 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:48 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:48 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:48 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:48 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:48 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
IPython-stderr>[W 11:02:49.269 NotebookApp] Unrecognized alias: '--ipython-dir=/home/platform/.beaker/v1/nginx3207186090641706069', it will probably have no effect.
IPython-stderr>[C 11:02:49.280 NotebookApp] Bad config encountered during initialization:
IPython-stderr>[C 11:02:49.280 NotebookApp] Invalid argument: '--ipython-dir=/home/platform/.beaker/v1/nginx3207186090641706069'
IPython-stdout>The Jupyter HTML Notebook.
IPython-stdout>This launches a Tornado based HTML Notebook Server that serves up an
IPython-stdout>HTML5/Javascript Notebook client.
IPython-stdout>Subcommands
IPython-stdout>-----------
IPython-stdout>Subcommands are launched as `jupyter-notebook cmd [args]`. For information on
IPython-stdout>using subcommand 'cmd', do: `jupyter-notebook cmd -h`.
IPython-stdout>list
IPython-stdout>    List currently running notebook servers in this profile.
IPython-stdout>Options
IPython-stdout>-------
IPython-stdout>Arguments that take values are actually convenience aliases to full
IPython-stdout>Configurables, whose aliases are listed on the help line. For more information
IPython-stdout>on full configurables, see '--help-all'.
IPython-stdout>--no-mathjax
IPython-stdout>    Disable MathJax
IPython-stdout>    MathJax is the javascript library IPython uses to render math/LaTeX. It is
IPython-stdout>    very large, so you may want to disable it if you have a slow internet
IPython-stdout>    connection, or for offline use of the notebook.
IPython-stdout>    When disabled, equations etc. will appear as their untransformed TeX source.
IPython-stdout>--script
IPython-stdout>    DEPRECATED, IGNORED
IPython-stdout>--generate-config
IPython-stdout>    generate default config file
IPython-stdout>--pylab
IPython-stdout>    DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
IPython-stdout>--no-browser
IPython-stdout>    Don't open the notebook in a browser after startup.
IPython-stdout>--debug
IPython-stdout>    set log level to logging.DEBUG (maximize logging output)
IPython-stdout>-y
IPython-stdout>    Answer yes to any questions instead of prompting.
IPython-stdout>--no-script
IPython-stdout>    DEPRECATED, IGNORED
IPython-stdout>--log-level=<Enum> (Application.log_level)
IPython-stdout>    Default: 30
IPython-stdout>    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
IPython-stdout>    Set the log level by value or name.
IPython-stdout>--notebook-dir=<Unicode> (NotebookApp.notebook_dir)
IPython-stdout>    Default: ''
IPython-stdout>    The directory to use for notebooks and kernels.
IPython-stdout>--certfile=<Unicode> (NotebookApp.certfile)
IPython-stdout>    Default: ''
IPython-stdout>    The full path to an SSL/TLS certificate file.
IPython-stdout>--browser=<Unicode> (NotebookApp.browser)
IPython-stdout>    Default: ''
IPython-stdout>    Specify what command to use to invoke a web browser when opening the
IPython-stdout>    notebook. If not specified, the default browser will be determined by the
IPython-stdout>    `webbrowser` standard library module, which allows setting of the BROWSER
IPython-stdout>    environment variable to override it.
IPython-stdout>--keyfile=<Unicode> (NotebookApp.keyfile)
IPython-stdout>    Default: ''
IPython-stdout>    The full path to a private key file for usage with SSL/TLS.
IPython-stdout>--ip=<Unicode> (NotebookApp.ip)
IPython-stdout>    Default: 'localhost'
IPython-stdout>    The IP address the notebook server will listen on.
IPython-stdout>--pylab=<Unicode> (NotebookApp.pylab)
IPython-stdout>    Default: 'disabled'
IPython-stdout>    DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
IPython-stdout>--transport=<CaselessStrEnum> (KernelManager.transport)
IPython-stdout>    Default: 'tcp'
IPython-stdout>    Choices: ['tcp', 'ipc']
IPython-stdout>--port=<Int> (NotebookApp.port)
IPython-stdout>    Default: 8888
IPython-stdout>    The port the notebook server will listen on.
IPython-stdout>--config=<Unicode> (JupyterApp.config_file)
IPython-stdout>    Default: ''
IPython-stdout>    Full path of a config file.
IPython-stdout>--port-retries=<Int> (NotebookApp.port_retries)
IPython-stdout>    Default: 50
IPython-stdout>    The number of additional ports to try if the specified port is not
IPython-stdout>    available.
IPython-stdout>To see all available configurables, use `--help-all`
IPython-stdout>Examples
IPython-stdout>--------
IPython-stdout>    ipython notebook                       # start the notebook
IPython-stdout>    ipython notebook --profile=sympy       # use the sympy profile
IPython-stdout>    ipython notebook --certfile=mycert.pem # use SSL/TLS certificate
nginx-stderr>2015/10/04 11:02:49 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:49 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:50 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:51 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:52 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:53 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:54 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:55 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:56 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:57 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:58 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:02:59 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:03:00 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:03:01 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:03:02 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:03:03 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:03:04 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/10/04 11:03:05 [error] 19996#0: *65 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /bb3ca3d/ipython.809813476192/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
^Cnginx-stderr>2015/10/04 11:03:06 [alert] 19895#0: *10 open socket #14 left in connection 9

**Comment by scottdraves** [comment]
Thanks for the report.
What version of Beaker do you have?  What version of IPython do you have?

**Comment by xiaoweiz** [comment]
@scottdraves 
I met a similar situation but in my case, beaker notebook can indeed work (just with annoying warnings). 

Setup: Ubuntu 15.04, not sure Beaker's version but I downloaded from [beakernotebook.com](beakernotebook.com) a couple of days ago. 

I installed all the dependencies by running the `install-dependencies.sh` except that I didn't use it to install `python3` since I have Anaconda distributed `python 3` installed. 

I start the beaker with 

``` shell
sudo ./beaker.command                                          [20:15:02]
starting nginx instance (/home/xiaoweiz/Software/beaker-notebook/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/
```

Then the languages `IPython`, `Python3`, `R`, or `Julia` _will_ work after some warnings like

``` shell
Running
0: /home/xiaoweiz/Software/beaker-notebook/config/plugins/eval/ipythonPlugins/python3/python3Plugin
1: 8804
Done starting Python3
nginx-stderr>2015/11/09 20:34:24 [error] 12654#0: *66 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/python3.905861122773/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/11/09 20:34:24 [error] 12654#0: *66 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/python3.905861122773/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/11/09 20:34:24 [error] 12654#0: *66 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/python3.905861122773/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/11/09 20:34:24 [error] 12654#0: *66 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/python3.905861122773/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/11/09 20:34:24 [error] 12654#0: *66 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/python3.905861122773/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
Python3-stderr>[I 20:34:24.219 NotebookApp] Serving notebooks from local directory: /home/xiaoweiz/Software/beaker-notebook
Python3-stderr>[I 20:34:24.219 NotebookApp] 0 active kernels 
Python3-stderr>[I 20:34:24.219 NotebookApp] The IPython Notebook is running at: http://127.0.0.1:8804/
Python3-stderr>[I 20:34:24.219 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Python3-stderr>[I 20:34:24.313 NotebookApp] 302 POST /login?next=%2F (127.0.0.1) 0.82ms
Python3-stderr>[I 20:34:24.341 NotebookApp] Kernel started: be322447-bca8-4842-a02a-3598c2b9e16a
```

**Comment by dberansky** [comment]
was there a resolution to this issue?  I seem to be experiencing similar symptoms.

**Comment by l1990790120** [comment]
wondering the same...

**Comment by scottdraves** [comment]
this is generally some other problem eg the previous person was really:
https://github.com/twosigma/beaker-notebook/issues/4034

Lulu if you are still unable to get Python working please open a new issue and include how you are running Beaker, how you installed IPython, your OS, and the error message you are getting.
