### ISSUE TITLE
possibly dead upstream: org.abstractmeta (a.k.a. compilation-toolbox)

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2603]
It seems compilation-toolbox (org.abstractmeta) is dead upstream - no commits in more than 2 years and no reaction to freeze of googlecode repo: https://code.google.com/p/compilation-toolbox/

I suggest to look into possibilities of changing to different actively maintained code, if possible, for javash plugin where it is used.

**Comment by scottdraves** [comment]
I can't find a replacement. We can either copy it into our codebase (it's only 35KB) or make a new github project with it that is packaged separately (we'll maintain it).  What do you recommend?

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-04 17:06:48)

> I can't find a replacement. We can either copy it into our codebase 
> (it's only 35KB) or make a new github project with it that is packaged 
> separately (we'll maintain it). What do you recommend?

If you won't develop that code, just use it, then I see no benefit in 
embedding it nor in creating a Github project for it.  Reason I raise it 
is not that Debian must have active upstream for all code, but that it 
is worrisome when upstream isn't active - it is no less worrisome if 
that fact is hidden ;-)

If you consider actually step up and maintain that code, then sure do 
create a Github project for it.  I notice there are already several 
instances of compilation-toolbox at Github, so probably a good idea to 
try get in touch with owners of those to join efforts - even if the aim 
is to keep as-is and only apply eventual bugfixes.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by scottdraves** [comment]
I am concerned that it is not maintained and its hosting may vanish.
There is only one entry on maven: http://search.maven.org/#search%7Cga%7C1%7Ccompilation-toolbox
And you are right there are several on github, but none have any stars.
I do see one fix among them but maybe more searching will find a better source.
This code seems to be pretty much static.
So let's 1) search harder but my assumption is 2) if none found, make a copy and maintain it.
IMO It is a lot less work (with more reliable result) to copy it into our tree compared to making a new project.
Would have to go as far as uploading to maven central for the "new project" route to work.
For static code it seems a bit much.

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-04 17:53:32)

> I am concerned that it is not maintained and its hosting may vanish.
> There is only one entry on maven: http://search.maven.org/#
> search%7Cga%7C1%7Ccompilation-toolbox
> And you are right there are several on github, but none have any stars.
> I do see one fix among them but maybe more searching will find a better source.
> This code seems to be pretty much static.
> So let's 1) search harder but my assumption is 2) if none found, make a copy
> and maintain it.
> IMO It is a lot less work to copy it into our tree compared to making a new
> project.
> Would have to go as far as uploading to maven central for the "new project"
> route to work.
> For static code it seems a bit much.

...but are you willing to become new upstream maintainer of the code?  
If not, then I think the least ugly is to include the file rather than 
create yet another inactive fork at Github.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private
