### ISSUE TITLE
beakerApp.css not generated?

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#2606]
Just downloaded the Beaker development version on a Linux machine. Got a 404 on beakerApp.css upon first launch: `http://127.0.0.1:8801/b137aad/beaker/app/dist/beakerApp.css Failed to load resource: the server responded with a status of 404 (Not Found).`

Did something happen to the job that generates it? I am launching using 'gradle run', also tried building using 'gradle build'. Also searched the entire file tree, could not find a single beakerApp.css.

**Comment by ildipo** [comment]
Hi Diego,
do you remember we had issues with gulp-sass? we switched to ruby-sass so you should run `sudo gem install sass` and rebuild.
Still it does not fail (but writes only an invisible error message) if you don't have sass installed...

**Comment by DiegoAlbertoTorres** [comment]
Cool, that did the trick (doesn't have to be sudo, as long as it is in the path)! I thought you guys ditched gulp-sass because it failed silently? Is there just no way around sass failing silently with gradle? (Also, I love the new animations in the UI!)

**Comment by scottdraves** [comment]
thanks.  the silent failures are a general gulp problem.
fixing that is still future work.
the big problem with node-sass was it needs to be compiled from C src.

**Comment by DiegoAlbertoTorres** [comment]
I see. Cool, now I can play around with it and see all the new stuff ;).
