### ISSUE TITLE
Exception during python autotranslation

### ISSUE THREAD

**Issue by dlukyanyuk** [twosigma/beakerx#2612]
Steps to reproduce:
1. Create an empty notebook, add iPython cell with code:

```
test = ['foo', 'bar']
beaker.test = test;

test2 = ['foo2', 'bar2']
beaker.test2 = test2;
```
1. Save it as .bkr and shutdown Beaker
2. Run Beaker again and open saved notebook (in Chrome). Run the code cell.
3. Copy the entire url to the other browser (Opera, Firefox)
4. Run the code cell 2 times

RESULT:
HTTP Error 500: Server Error

And in the Beaker log:

```
[qtp687059528-26] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/namespace/set
java.lang.RuntimeException: Namespace set, name mismatch.  Received test, expected test2
        at com.twosigma.beaker.core.rest.NamespaceService.set(NamespaceService.java:111)
        at com.twosigma.beaker.core.rest.NamespaceRest.set(NamespaceRest.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by scottdraves** [comment]
thank you dmitri, good catch.  it reproduced for me.
i think there is a problem with the autotranslation protocol, keeping sync between comet and rest.
maybe it needs some kind of sync when opening a client.  i think just discarding the bad value is dangerous.
