### ISSUE TITLE
How to set Latex output from a plugin?

### ISSUE THREAD

**Issue by axkr** [twosigma/beakerx#2629]
How can I set the cells output to Latex format?

This doesn't seem to work:

``` java
            @Override
            public void run() {
                // Object result;
                theOutput.setOutputHandler();

                IExpr result;
                final StringWriter buf = new StringWriter();
                try {
                    String trimmedInput = theCode.trim();
                    if (trimmedInput.length() > 1 && trimmedInput.charAt(0) == '?') {
                        result = Names.getNamesByPrefix(trimmedInput.substring(1));
                    } else {
                        result = (IExpr) shell.evaluate(theCode);
                    }
                    if (result.equals(F.Null)) {
                        theOutput.finished("");
                    } else {
                        final StringBuffer builder = new StringBuffer();
                        fTeXFactory.convert(builder, result, 0);
                        // change the following cell type
                        beaker.setCodeCellEvaluator("celltochange", "Latex");
                        // set a new body
                        beaker.setCodeCellBody("celltochange", builder.toString());
                        // execute it
                        beaker.evaluate("celltochange");

                        // theOutput.finished(beaker.evaluate("celltochange"));
                        theOutput.finished(result.toString());
                    }
                    // return buf.toString();
                } catch (Throwable e) {
                    if (e instanceof InterruptedException || e instanceof InvocationTargetException
                            || e instanceof ThreadDeath) {
                        theOutput.error("... cancelled!");
                    } else {
                        StringWriter sw = new StringWriter();
                        PrintWriter pw = new PrintWriter(sw);
                        e.printStackTrace(pw);
                        theOutput.error(sw.toString());
                    }
                }
                theOutput.clrOutputHandler();
            }
        };
```

**Comment by scottdraves** [comment]
Hi, thanks for contacting us.
Can you say more about what you are trying to do?

**Comment by axkr** [comment]
In this evaluator plugin:
https://bitbucket.org/axelclk/beaker-plugin/src

I try to output the evaluated expression in Latex instead of a plain text string:
![beaker2629](https://cloud.githubusercontent.com/assets/3109793/10314553/bc9746f8-6c55-11e5-85c1-2bfb012b986c.png)

Here is the description of the evaluation engine:
https://bitbucket.org/axelclk/symja_android_library/wiki/Home

**Comment by ildipo** [comment]
Just return a string containing:

`<div class="output_latex">$$F(k)$$</div>`

NOTE: works only in 1.4

for 1.3 you must return a JSON object that contains:

`{ type : 'Latex', result: 'F(k)' }`

**Comment by axkr** [comment]
Ok I've taken the 1.4 approach. See:
https://bitbucket.org/axelclk/beaker-plugin/commits/5284c4cb8a65ab8baa5a827566994c6295dc560a

![beaker2629b](https://cloud.githubusercontent.com/assets/3109793/10344938/6d74e2b6-6d26-11e5-91da-2702cf86cd59.png)

Is it possible to have a menu-option, where I can globally enable or disable TeX or Non-TeX output for my plugin?

**Comment by scottdraves** [comment]
that looks great!

you can create configuration widgets in the spec of your plugin, like how groovy allows the user to set the classpath.  look in the language manager for groovy to see it in action and then look in groovy.js to see how to implement it.
