### ISSUE TITLE
Javadoc for Plot API needed

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#2632]
I spent some time looking for API description of plotting classes for Java and Groovy. Finally, I looked through source code and there is now Javadoc there as far as I can see. Of course there are some examples, but it is hard to derive all available possibilities from them. I think that one definitely needs a Javadoc/Groovydoc or at least short tutorial on how to use these classes.

**Comment by scottdraves** [comment]
thanks for the feedback.  we don't have the resources to write documentation yet but we will get there.

**Comment by scottdraves** [comment]
If you have any specific questions about the API feel free to ask them here.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/1891
