### ISSUE TITLE
possible bogus dependency: scrollin

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2637]
Hi,

The javascript library scrollin is listed in cor/bower.json and included in core/src/main/web/vendor/bower_components - but seems unused anywhere.

**Comment by maxyeg** [comment]
Hi!
I see it's used here:
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/components/notebook/notebook-directive.js#L276
and here:
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/components/notebook/codecell-directive.js#L406
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/components/notebook/codecell-directive.js#L515

**Comment by jonassmedegaard** [comment]
Oh, indeed.

Silly me, I forgot to grep case-insensitively :-P
