### ISSUE TITLE
New section header after a collapsed section header in wrong place

### ISSUE THREAD

**Issue by farrellm** [twosigma/beakerx#264]
If I create a new section header (S2) below a collapsed section header (S1), S2 is created between S1 and S1's children rather than after S1's children

1) create a new section header (S1)

```
[-] S1
```

2) add a code cell below S1 (C)

```
[-] S1
    C
```

3) collapse S1

```
[+] S1
```

4) create a new section header (S2) (diagram for same level, any level works)

```
[+] S1
[-] S2
    C
```

Expected result:

```
[+] S1
[-] S2
```

Expanding S1:

```
[-] S1
    C
[-] S2
```

**Comment by melmac48** [comment]
@samccone can you verify that this will be fixed in the new UI? thnx.

**Comment by scottdraves** [comment]
I confirmed this is still a problem with new UI.  In fact the new section is created but is not visible because it is inside a collapsed section.

**Comment by melmac48** [comment]
the behavior I'm seeing is that if you create S2 after a collapsed S1 that contains a single code cell, S1 remainse collapsed and S2 is created below it but S2 now contains the code cell that was in S1. If you perform this action when the cell is not collapsed though, it works as expected, so punting to v2

**Comment by scottdraves** [comment]
I get

```
[+] S1
```

which if expanded reveals

```
[-] S1
[-] S2
    C
```

which is different from what's reported above, but that still differs from what I expect:

```
[+] S1
[-] S2
```

**Comment by buob** [comment]
Is "S1" an H1 and "S2" an H2?  If so, I believe this architecture was intentional, as there isn't really a concept of a level 2 section adjacent to a level 1 section, only inside of them.  If they are both level 1 sections, it looks like it yields the expected results.

**Comment by farrellm** [comment]
Shouldn't matter. If I create a new section header after a collapsed section header, the new header should come after all existing cells and headers in the collapsed header. This is particularly true when S1 and S2 are the same level, but should hold in general.

Intuitively, if I add a header at "the end" of the document, it should be the new bottom element of the notebook; it should not appear before other cells.

**Comment by buob** [comment]
Yeah, that's part of the slightly confusing implementation of the new cell button.  It's intrinsically linked with the cell itself, aside from the very last insert button.  So, if you insert anything "after a section header", it really means inside of the section.  And if the section is expanded, the button is above its contents, so right now there's no way to add a subsection at the end of a section, other than adding it then moving it down, regardless of whether it's expanded or collapsed (which certainly isn't ideal).

I think this will take some rethinking of the new cell button, specifically decoupling it from the cell before it, but I think it would be worth that given the current somewhat confusing UI. :+1:

**Comment by scottdraves** [comment]
i think the problem matt is having comes from the fact that there are two insert cell buttons at the end of the notebook, the big one and the small one, and they do different things in this situation.  the big one at the end does what matt wants.

i think my confusion was due to what jake points out, which is that an H2 after an H1 has to be inside it, and if the section is closed then you have inserted something which is not visible which makes it look like nothing happened.

we need to think about this more.

**Comment by farrellm** [comment]
I see. Is there any reason to ever show the small one when the associate section is collapsed? I'm not sure when I would ever not want the big one.

**Comment by buob** [comment]
I think that's true, at the very least if a section cell is collapsed, you shouldn't be able to insert a cell into it.
