### ISSUE TITLE
Firefox -  notebook list displays different order

### ISSUE THREAD

**Issue by sethkrasnianski** [twosigma/beakerx#2641]
<img width="672" alt="screen shot 2015-10-07 at 7 42 10 am" src="https://cloud.githubusercontent.com/assets/963093/10336523/52e12c8e-6cc7-11e5-9831-53a1bfca5d7c.png">
vs:
<img width="680" alt="screen shot 2015-10-07 at 7 42 17 am" src="https://cloud.githubusercontent.com/assets/963093/10336522/52df31ea-6cc7-11e5-98d6-c9b354e4b82a.png">

**Comment by sethkrasnianski** [comment]
This should be resolved in https://github.com/twosigma/bunsen/pull/1251#issuecomment-147706809

**Comment by grin** [comment]
should be fixed by: https://github.com/twosigma/bunsen/pull/1256
