### ISSUE TITLE
Please consider switch to Batik 1.8

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2648]
Issue 1878 was closed in august, with the workaround of rolling back to Batik 1.7.

Since then a workaround for 1.8 has been mentioned upstream at https://issues.apache.org/jira/browse/BATIK-1125 - please consider that.

**Comment by scottdraves** [comment]
That's what we do:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/r/build.gradle#L31

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-07 23:34:33)

> That's what we do:
> https://github.com/twosigma/beaker-notebook/blob/master/plugin/r/build.gradle#
> L31

You currently use Batik 1.8 rasterizer but Batik 1.7 codec.

I suggest to try use Batik 1.8 for both.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by scottdraves** [comment]
Oh you mean the 2nd workaround:

```
A workaround is to manually register the following registry entries:
final ImageTagRegistry registry = ImageTagRegistry.getRegistry();
registry.register(new PNGRegistryEntry());
registry.register(new TIFFRegistryEntry());
```

Sure we can do that.

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-08 00:30:59)

> Oh you mean the 2nd workaround:
> 
> A workaround is to manually register the following registry entries:
> final ImageTagRegistry registry = ImageTagRegistry.getRegistry();
> registry.register(new PNGRegistryEntry());
> registry.register(new TIFFRegistryEntry());
> 
> Sure we can do that.

Great :-)
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private
