### ISSUE TITLE
sorting of notebooks

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2650]
we would like a sort 'menu' for the list of notebooks.
This should apply sorting to the current list of notebook (before pagination).

The function should be available everywhere there's a list of notebooks (landing page, category, user and search results) - please propose some visual layout for it.

The sorting methods should be:
1) by rank - higher rank first (default)
2) by rank - lowest rank first
3) by publish date - most recent first
4) by publish date - least recent first
5) alphabetically on title

**Comment by grin** [comment]
CI in progress: https://circleci.com/gh/mojotech/bunsen/2971

**Comment by planyon** [comment]
@grin Sorting by highest rated isn't working on staging. The notebook "phytools failure" is first in the list, even though it has no rating.

Sorting by newest/oldest produce different sort orders, but I would expect them to list each item in the same order, just in reverse.

Sorting alphabetically puts "Comparing..." in the first spot, incorrectly. The rest of the items look good.

**Comment by grin** [comment]
should be fixed by: https://github.com/twosigma/bunsen/pull/1256 (https://github.com/twosigma/bunsen/commit/3c239f84c741e6a4c6545bd6586a8715775affd2 specifically)
