### ISSUE TITLE
JAVA_HOME in Ubuntu 14.04 should be set to what?

### ISSUE THREAD

**Issue by cjsulli** [twosigma/beakerx#2654]
Regardless of what I set my JAVA_HOME variable to, I get an error saying:

ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-8-oracle/jre/bin/java

(Alternatively, /usr/bin/java gave me the same error.)

What SHOULD I have it set to?

Thanks in advance!

**Comment by scottdraves** [comment]
you shouldn't set it at all, if you install Java from the oracle PPA it just works.

**Comment by cjsulli** [comment]
That is where I got it from.  (i.e. I just checked that I have oracle-java8-installer up to date via apt.)  Thoughts?

**Comment by scottdraves** [comment]
http://stackoverflow.com/questions/29269829/webupd8-java-home-not-set-after-installing-oracle-java8-set-default
says:

> Your JAVA_HOME will not be set by the webupd8 method, and you don't normally need it 

so my thoughts are whatever is setting it is doing so incorrectly, you should unset it and/or find what is setting it and remove it.

**Comment by cjsulli** [comment]
Ah ha!  Thanks for that link.  My JAVA_HOME was set to /usr/bin/java, which linked to /etc/alternatives/java, which in turn linked to /usr/lib/jvm/java-8-oracle/jre/bin/java.  But when I manually set JAVA_HOME to /usr/lib/jvm/java-8-oracle, that seems to have solved the problem

Thank you!
