### ISSUE TITLE
improve this text

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2656]
from https://pub.beakernotebook.com/#/create_publication
<img width="426" alt="screen shot 2015-10-07 at 11 00 55 pm" src="https://cloud.githubusercontent.com/assets/963093/10356790/cf3857d6-6d48-11e5-8521-b5d197cb6f6e.png">
<img width="766" alt="screen shot 2015-10-07 at 11 01 04 pm" src="https://cloud.githubusercontent.com/assets/963093/10356791/cf3a5e00-6d48-11e5-8afc-6ba79248ded4.png">

**Comment by planyon** [comment]
What sentiment would you like to express there @scottdraves ? I can write something and put it by you.

**Comment by scottdraves** [comment]
sorry i just made a quick note here and forgot to come back to write the text.

the 1st line needs commas.  it should read "Mac, Linux, and Windows and supports Chrome, Firefox, and Safari."

The 2nd line should read "It's easy to make your own notebooks, and share or publish them if you choose to."
