### ISSUE TITLE
why click to search?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2657]
https://pub.beakernotebook.com/#/publications
if you just start typing it should go into the search box (show cursor too?)

cmd-enter to open 1st hit?
cmd-digit to enter nth hit?

**Comment by sethkrasnianski** [comment]
:+1:

**Comment by sethkrasnianski** [comment]
This will remove chrome tabbing abilities. Is ctrl also expected as an alternative to cmd (particularly for windows)?

Also, do we want to capture numbers greater than 9 for page requests??
