### ISSUE TITLE
Can't use Grape.grab() from groovy cell

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#2658]
I am trying to attach a mathematical library from groovy environment:

```
import groovy.grape.Grape
Grape.grab(group:'org.apache.commons', module:'commons-math3', version:'3.5')
```

The only thing I get is an error:

```
java.lang.LinkageError: loader constraint violation: when resolving overridden method "com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.getParser()Lorg/xml/sax/Parser;" the class loader (instance of com/twosigma/beaker/jvm/classloader/DynamicClassLoaderSimple) of the current class, com/sun/org/apache/xerces/internal/jaxp/SAXParserImpl, and its superclass loader (instance of ), have different Class objects for the type org/xml/sax/Parser used in the signature
```

I believe that xerces is a part of JVM and it is definitely not loaded by commons-math. So it seems that the problem is in the Beaker class loader. I also tried to grab other libraries with the same result. 

It would be very sad if we could not use grapes from Beaker because it is very important tool. 

**EDIT:** since groovy imports does not work across cells (which is not very good), grapes should be included in language properties.

**Comment by scottdraves** [comment]
Thanks for your report, we will review it and get back to you.

**Comment by scottdraves** [comment]
confirmed: https://pub.beakernotebook.com/#/publications/56188486-7d2e-4bf3-8a18-b3977633eb38

our big plan is to add a package manager UI to the language manager: https://github.com/twosigma/beaker-notebook/issues/1350

in the meantime, this seems like a class loader bug, we'll look into it.

plus: https://github.com/twosigma/beaker-notebook/issues/2695

**Comment by KrzysztofKowalczyk** [comment]
This example runs now and grape can be used. I believe it has been fixed by:
https://github.com/twosigma/beaker-notebook/issues/3612

**Comment by scottdraves** [comment]
thanks for circling back!
