### ISSUE TITLE
make embedding of BokehJS configurable

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2659]
Beaker includes a tutorial notebook with BokehJS embedded in uglified form.

Some users, including Debian for whom I am currently packaging, prefer to track each upstream independently and track original sources (rather than compiled or uglified code).

BokehJS 0.11 (due in November, it was mentioned in #2651) will offer the choice of either embedding or referencing an external URL for its code. Please, when that version is released, consider switch to it and embrace that configurability - e.g. as a build-time flag of either a URL (e.g. to a CDN) or a path (full or relative to local install of Bokeh) or the empty string (for embedding).

**Comment by scottdraves** [comment]
thanks.  will do.
