### ISSUE TITLE
Top Contributors not working on search results

### ISSUE THREAD

**Issue by planyon** [twosigma/beakerx#2667]
See attached screenshot where "Berzelius Beaker" should be listed as a Top Contributor.
![screen shot 2015-10-08 at 10 36 18 am](https://cloud.githubusercontent.com/assets/5454235/10369496/8a58f7a0-6da8-11e5-953d-f3f24587ec6b.png)

**Comment by grin** [comment]
Fixed in https://github.com/twosigma/bunsen/pull/1248
