### ISSUE TITLE
Changing Category Names should not orphan the notebooks in the category

### ISSUE THREAD

**Issue by melmac48** [twosigma/beakerx#2673]
If I change the name of a category in the Admin panel, all notebooks in the category are no longer present in the newly named category. The correct behavior is that an Admin should be able to change a category name without any knock on repercussions.

**Comment by grin** [comment]
Seems like there is something else going on. Tried renaming "Demographics" to "Demographics2" on staging: https://pub-staging.beakernotebook.com/#/publications and it didn't orphan any notebook. Is there any category where you could reproduce this on staging? or that's only happening in production? (I only have admin on staging).

**Comment by grin** [comment]
@ildipo do you know if this is still happening? if yes, can we get some steps to reproduce it? (ideally on staging)

**Comment by ildipo** [comment]
still not able to reproduce - it goes away if you delete and recreate the category
