### ISSUE TITLE
cell buttons over code fix?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2676]
<img width="279" alt="screen shot 2015-10-08 at 11 03 47 pm" src="https://cloud.githubusercontent.com/assets/963093/10385006/4554b234-6e11-11e5-87b7-ab406c5d11ec.png">

only show the buttons on hover? adv mode?

**Comment by scottdraves** [comment]
move language button to the other side, and leave it up all the time.  mock:
<img width="733" alt="screen shot 2015-10-08 at 11 08 40 pm" src="https://cloud.githubusercontent.com/assets/963093/10385083/2ef8305a-6e12-11e5-9819-739bb2ba7376.png">

**Comment by sethkrasnianski** [comment]
What if the language icon stayed in place, but persisted? Would that be too visually intrusive?
