### ISSUE TITLE
[Native Beaker] disconnect frequently

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2677]
<img width="593" alt="screen shot 2015-10-08 at 11 09 28 pm" src="https://cloud.githubusercontent.com/assets/963093/10385047/ac56227e-6e11-11e5-97e4-7b775d616094.png">

**Comment by mnavasiolava** [comment]
reproduced for me only once after a night of idle. maybe other fixes to cometd problem worked here

**Comment by lolaclinton** [comment]
I'm using beaker for the first time with Scala and it constantly disconnects for me.

**Comment by scottdraves** [comment]
thanks for the report.

what platform/OS are you on?
does it reconnect?
can you reload and get your notebook back?
are you using the electron version?

**Comment by lolaclinton** [comment]
max osx v 10.11.2
it doesn't automatically reconnect .. 
I press reload, but it takes forever and it doesn't seem as stable after (can get stuck in starting scala /html)
I just did the brew install. So I'm using 1.4.2 (1)

**Comment by lolaclinton** [comment]
I'm using spark. Not sure if that makes a difference.

**Comment by lolaclinton** [comment]
I would be happy to share my screen with anyone if that helps diagnose.

**Comment by scottdraves** [comment]
thank you for offering, please email me to arrange.
