### ISSUE TITLE
Social Networking Category Not Showing

### ISSUE THREAD

**Issue by melmac48** [twosigma/beakerx#2681]
If I move a notebook into the Social Sciences Category then that Category shows up in the category list, however if I move the same notebook into the Social Networking sub category, then the Social Sciences category no longer shows ups.

**Comment by ildipo** [comment]
This seems to happen if you move it in a sub category that has an attached icon - if it does not have it then it works.
See https://pub.beakernotebook.com/#/publications/560eac5b-6e33-4850-b616-7547536cd8d0?fullscreen=false and try to put it inside Social Science -> Sociology or Psycology it works, but if you use Social Science (which has an icon) it does not.

**Comment by melmac48** [comment]
Seems to work for biology

**Comment by grin** [comment]
Trying to reproduce it locally, but with no luck. I created a simple category structure: 

Social Sciences -> Social Networking 

and tested moving notebook between the two categories with sub-category icon present/absent. All my tests were successful.

Is this still an issue on production?

**Comment by grin** [comment]
@ildipo do you know if this is still happening? if yes, can we get some steps to reproduce it? (ideally on staging)

**Comment by ildipo** [comment]
not able to reproduce
