### ISSUE TITLE
Cell dependencies?

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#2682]
Since all cells have their own identifiers and metadata, I think it would be interesting to have cell dependencies. For example if cell `A` is dependent on cell `B` and we try to run `A`, then if `B` is not calculated, it is being calculated automatically prior to `A`. One could organize whole chain of such dependent cells.
Also there could be two different type of dependencies. "Weak" ones to recalculate dependency only if it is not calculated at all, and "strong" one, which forces dependency recalculation in any case. Strong dependencies could be invaluable to avoid broken state errors.  
I don't believe that I've seen such mechanism in any notebook-style applications, but I think that it could add additional layer of flexibility.

By the way. I've just prepared a set of interactive examples for my students using Beaker and I am entirely satisfied with how it works. Great work!

**Comment by scottdraves** [comment]
Thank you!  I agree that dependencies would be useful, and we'll probably implement something eventually.
