### ISSUE TITLE
Drives over than C:\ are not available in viewer to open notebooks

### ISSUE THREAD

**Issue by wgajate** [twosigma/beakerx#2685]
On the main beaker screen, when I select file->open->open..(ipyb), the directory browser that pops up fails to show my locally partitioned mapped G:\ drive.

**Comment by scottdraves** [comment]
good point, we should make all the mounted drives accessible.

**Comment by altavir** [comment]
I also have this problem. Open dialog shows only the drive on which beaker is installed and user directory. I also could not find a way to manually specify working directory.
