### ISSUE TITLE
When I run the IPython tutorial I get - IPython initialization failed

### ISSUE THREAD

**Issue by wgajate** [twosigma/beakerx#2686]
![beaker_runtime](https://cloud.githubusercontent.com/assets/1097313/10397762/568e1d5e-6e77-11e5-9827-a57e8afde3b2.jpg)

**Comment by scottdraves** [comment]
thanks for the report.
i think you have python3 as your default python, is that right?
that tutorial is for python2.

**Comment by wgajate** [comment]
my default python is 2.7.4 on the 64 bit Anaconda 2.3.0

**Comment by scottdraves** [comment]
if you close the error, can you make a code cell and evaluate the following:

```
os.environ["PYTHONPATH"]
```

where do you have beaker installed?

**Comment by wgajate** [comment]
I ran os.environ["PYTHONPATH"] and it revealed two paths separated by a ':' not ';'. It looks like when beaker runs it adds itself to the pythonpath with a hardcoded ':' instead of using os.pathsep.

**Comment by scottdraves** [comment]
what version of beaker do you have? that was recently fixed.

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by wgajate** [comment]
v1.3.1-0-g3072e5e

**Comment by scottdraves** [comment]
OK, try downloading the latest release, 1.4.1.

**Comment by wgajate** [comment]
That worked. Thanks for your help.
