### ISSUE TITLE
control-space in groovy not triggering autocomplete

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2687]
exact circumstances are unclear.

**Comment by altavir** [comment]
In fact, I have at least partially working autocomplete for Groovy both in 1.4 and 1.4.1.

**EDIT** Win 10, beaker 1.4.1. Groovy aoutocomplete fully functional. It doesn't see closures defined in other cells, but I think it is not possible at all.

**Comment by scottdraves** [comment]
cannot reproduce on my home mac.

**Comment by scottdraves** [comment]
mystery solved: i had emacs editing mode set.

**Comment by Hubbitus** [comment]
Sorry, I also do not see groovy auto-completion in `beakerx` version 1.3.0. But I allo do not see tag 1.4.0 in that repository, nor docker containers with that number.

Could you please say which settings I should check to enable it?
