### ISSUE TITLE
Section number in hierarchy view

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#2689]
In hierarchy view there are numbers for each section. From common sense these numbers should be section numbers, but in fact they are cell numbers in section. For example if there are two cells and then subsection, the number will be `1.1.3` or something like that with no `1.1.1` and `1.1.2` before it.

Is it intended that way?

**Comment by scottdraves** [comment]
no that's just a bug, thanks for the report.

![screen shot 2015-10-09 at 1 41 10 pm](https://cloud.githubusercontent.com/assets/963093/10401212/861bf366-6e8b-11e5-9ce2-52152c76f212.png)

**Comment by scottdraves** [comment]
not a regression this has always been broken afaik.

**Comment by altavir** [comment]
I also found that hierarchy view is not restored on save/load.

**Comment by scottdraves** [comment]
Well it's not intended to be part of the document, but just a way of viewing documents.
I agree it should be more persistent (session to session).

**Comment by scottdraves** [comment]
Note: I could easily be convinced though to make the numbering (or not) part of the doc.

This change should account for improving the table-of-contents navigation in general, a larger future project.

So I an open to changing this, but want to make sure it's the right change.

**Comment by altavir** [comment]
It strongly depends on presumed usage of the notebook. In my case I use it as teaching material, and static chapters would be very nice since they could be easily referenced from other chapters (it would be also great to be able to create clickable link to cell or chapter from text cell).
