### ISSUE TITLE
admin edit of unlisted

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2693]
thanks for the fast implementation of the unlisted post feature :+1: 

that means we need this too:  admins can toggle unlisted bit of each notebook (add checkbox):
<img width="561" alt="screen shot 2015-10-09 at 9 49 31 pm" src="https://cloud.githubusercontent.com/assets/963093/10408589/ef1b39dc-6ecf-11e5-8874-52b754d40514.png">

**Comment by grin** [comment]
Fixed in: https://github.com/twosigma/bunsen/pull/1247
