### ISSUE TITLE
Groovy imports should persist across cells

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2695]
<img width="652" alt="screen shot 2015-10-09 at 11 27 58 pm" src="https://cloud.githubusercontent.com/assets/963093/10409049/a19066b6-6edd-11e5-8cd2-87bb005b8136.png">

**Comment by hadim** [comment]
Is that still a problem with the new Beakerx kernel? Because we have the same issue with the Scijava kernel.

Ping @ctrueden

**Comment by hadim** [comment]
I think it might a Groovy specific behavior.

**Comment by scottdraves** [comment]
just how groovy is.

**Comment by JoshuaCWebDeveloper** [comment]
Found this issue while trying to figure out how I am supposed to import classes in the Groovy kernel. Seems like that this is the expected way to do it (using a BeakerX magic):
```
%import com.twosigma.beakerx.groovy.kernel.Groovy
```
