### ISSUE TITLE
Pre-install spark on docker container?

### ISSUE THREAD

**Issue by cjsulli** [twosigma/beakerx#2696]
Just a suggestion, but I am trying to work through the tutorials and ran into the fact that Spark was not pre-installed on the docker container.  (At least when I updated my container a few hours ago.)  While I have come across several small issues with things not being installed (mostly python packages that were easily resolved with pip), it would be nice if some of these bigger things like Spark would come with the container.  Or are there reasons that it cannot?

**Comment by scottdraves** [comment]
Thanks for your feedback.  Spark is really gigantic to build but perhaps we could include a binary blob, just like we host on S3.  I don't see any fundamental reason why we couldn't.

**Comment by cjsulli** [comment]
I hear ya.  So I installed it myself via:

git clone git://github.com/apache/spark.git
build/mvn -DskipTests clean package

In doing so, I put the install into /src/spark.  So I set $SPARK_HOME to this value.  I ran the built-in spark examples in my container just fine to verify the successful build.

But when I try to run the PySpark example, I get an error saying that $SPARK_HOME is not set.  I tried after confirming in the language manager that the command to get $SPARK_HOME was set.  (I even tried to set it manually in the command list there.)  But I still get the error.

Suggestions?  TIA!

**Comment by scottdraves** [comment]
> So I set $SPARK_HOME to this value. But when I try to run the PySpark example

how did you set it?  how are you running beaker?

i believe it has to be set in .bash_profile...

but really if you tried to put the value right into the code, that should work, idk.

**Comment by cjsulli** [comment]
OK...a bit of progress.  Running beaker via:

sudo docker run -p 8800:8800 -t beakernotebook/beaker

I set $SPARK_HOME manually in the shell:

export $SPARK_HOME=/src/spark

Then, I added in the set language:

spark_home='/src/spark'

Now I get the following error:

ERROR: [Errno 2] No such file or directory: '/src/spark/python/pyspark/shell.py'

However, I have verified that shell.py is truly in that directory.  Thoughts?

**Comment by scottdraves** [comment]
are you really putting /src at the root of the filesystem?
should that be in the home dir?

**Comment by cjsulli** [comment]
Yeah.  That was a typo.  But I changed it to /home/beaker/src/spark and it still threw the same error about shell.py.
