### ISSUE TITLE
do grid and lattice pkgs work in R?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2697]
try this: http://alstatr.blogspot.ca/2015/02/r-how-to-layout-and-design-infographic.html

**Comment by scottdraves** [comment]
including posting the demo notebook to pub.beakernotebook.com

**Comment by tomca32** [comment]
Yes they do: https://pub.beakernotebook.com/#/publications/56211d8f-9b57-4419-b67a-85a52704ceb4
