### ISSUE TITLE
Add publication listing to admin menu

### ISSUE THREAD

**Issue by grin** [twosigma/beakerx#2700]
The list should have title, author, updated-date, featuredm list/unlist

**Comment by grin** [comment]
@ildipo what do you think about adding the unlisted check to publication search:
![image](https://cloud.githubusercontent.com/assets/12468/10513321/157d3b04-7347-11e5-984d-46667f6bbd95.png)
?
that would be visible to admins only and if checked it would only show unlisted publications (and allow filter/search).

**Comment by ildipo** [comment]
I think it is a good idea - while you are at it we should also display the unlisted notebook when you are logged in and you are looking at your notebooks. I would also add a menu entry "show my own notebook" that brings you to your author list

**Comment by grin** [comment]
@ildipo are we talking about this menu:
![image](https://cloud.githubusercontent.com/assets/12468/10518043/e6fcc4de-735f-11e5-9a05-62eb51d6af68.png)
for "show my own notebooks" option?

**Comment by ildipo** [comment]
@grin yes thanks

**Comment by grin** [comment]
implemented in https://github.com/twosigma/bunsen/pull/1280

**Comment by ildipo** [comment]
merged and avail on pub-staging
