### ISSUE TITLE
Add endpoint for returning publications updated/uploaded after given date 

### ISSUE THREAD

**Issue by grin** [twosigma/beakerx#2701]
This endpoint will be called periodically by cron and curl.

per @ildipo comments:

_I must get also the unlisted notebook list so we do need some kind of auth and special endpoint,
I think we can have a pre-shared secret I can set in an ENV var when I start the API docker container
and I can pass it via curl query string_

**Comment by grin** [comment]
@ildipo what format should the response have? text? html? should it just link to found publications?

**Comment by ildipo** [comment]
what about JSON with all fields (except the notebook data itself)?

**Comment by grin** [comment]
:+1:

**Comment by grin** [comment]
Implemented in https://github.com/twosigma/bunsen/pull/1343
