### ISSUE TITLE
Beaker menu creation refactoring

### ISSUE THREAD

**Issue by alice-kroch** [twosigma/beakerx#2716]
Need to refactor the way how Beaker menu is building. Some points of view:
- It should work through the **bkElectron** factory
- Need to find out if we need to use _'main-menu'_ module in electron because now it seems like it's not in use.
- Also need to override creation of 'About Beaker' menu item. There is example of right behaviour, so we need to rework it:
  - on mac: should be 1st item in the Beaker menu
  - on windows: should be last item in Help menu
  - on web: should remain as it is

**Comment by scottdraves** [comment]
:+1:

**Comment by alice-kroch** [comment]
I've noticed, that after main window is closed on mac os the new instance of menu appeared, including main Beaker menu and File menu with two subitems - new empty notebook and new default notebook. Is this a right behaviour? Shouldn't it include any other items?
