### ISSUE TITLE
QA languages on Safari (running on docker)

### ISSUE THREAD

**Issue by byndcivilization** [twosigma/beakerx#2719]
`docker run -p 8800:8800 -t beakernotebook/beaker`
Works fine but I get infinite initilizing languages for everything except html and latex. Is there a flag or process to load language backend?

**Comment by scottdraves** [comment]
thanks for the report.  no, they should work.  what version of beaker is in your container (look in the help->about)?

**Comment by scottdraves** [comment]
i just checked and didn't have any problems.  can you give more specific steps to reproduce?

**Comment by byndcivilization** [comment]
```
build time: 2015-10-06 20:50 UTC
version: 1.4.1-0-ge8427bf
```

I'm running this through docker-machine on an aws remote host which has been giving me problems on other images. Is there a specific port configuration that you recommend?

**Comment by scottdraves** [comment]
it just needs 8800 open.  if you get anything at all then it should work.

**Comment by byndcivilization** [comment]
This is weird. My session expired and i reconnected and R and JS work. Nothing else yet.

**Comment by scottdraves** [comment]
What browser are you using?

**Comment by byndcivilization** [comment]
Safari

**Comment by byndcivilization** [comment]
Its giving me logs that indicate IPython noteboodk is good

**Comment by byndcivilization** [comment]
althought it is giving me a 404 on an api request:

```
IPython-stderr>[W 18:14:20.613 NotebookApp] 404 GET /api/kernels83552e56-2407-4658-a3aa-5104d30328cc?_=1444846335144 (127.0.0.1) 1.70ms referer=https://192.168.99.100:8800/beaker/
```

**Comment by byndcivilization** [comment]
Seems to be working on chrome however.

**Comment by byndcivilization** [comment]
Oh okay so i think this is at least partially an issue on my end.
I was not running as daemon but was treating it as such.

**Comment by scottdraves** [comment]
Cool, glad you got it figured it out.

**Comment by scottdraves** [comment]
We should test more on Safari. it sounds like that may have confused the UI a bit.
