### ISSUE TITLE
Beaker fails to start when path to user directory contains non-ascii symbols

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#2732]
On windows user directory usually is C:\Users<user name>. The user name is not necessarily English and is encoded via system default charset (which is usually cp-something). Some of my students with Russian user names found that beaker would not start saying it can't find configuration file.

This problem is quite critical for me, so please tell me if there is some quick work-around for this problem.

**Comment by altavir** [comment]
Just checked it again from other computer with Russian user name. That's what I get when I start beaker via PowerShell:

```
starting nginx instance (D:\temp/nginx)
beaker.command.bat : [main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
строка:1 знак:21
+ .\beaker.command.bat <<<< 
   + CategoryInfo          : NotSpecified: ([main] INFO org....1.13.v20130916:String) [], RemoteException
   + FullyQualifiedErrorId : NativeCommandError

nginx-stderr>nginx: [alert] could not open error log file: CreateFile() "C:\Users\Лейла\.beaker\v1\nginx66271149500274446/logs/error.log" failed (3: The system cannot find the path specified)
nginx-stderr>2015/10/15 21:46:04 [emerg] 6572#7024: CreateFile() "C:\Users\╦хщыр\.beaker\v1\nginx66271149500274446/conf/nginx.conf" failed (3: The system cannot find the path specified)
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/
```

After that browser starts, but it fails to load the page.

**Comment by scottdraves** [comment]
Thanks we can get this into 1.4.2 early next week at best.
Unfortunately I can't think of a workaround.

**Comment by altavir** [comment]
Currently I recommended to create a user with English name for this purpose. It will hold for now, but I definitely looking forward for new release.

**Comment by scottdraves** [comment]
https://forum.nginx.org/read.php?21,239503,239510#msg-239510

this is a problem in nginx so it's not easy to fix.  we will have to move where we put the config file and i can't do that in 1.4.2, it's a big enough change it has to wait for 1.5, sorry.

**Comment by altavir** [comment]
I think it is a good idea to pass config file path and nginx working directory path via CLI so it could be manually reconfigured by editing start script. It will also allow to make a fully portable version ( by storing work files inside beaker installation directory).

**Comment by altavir** [comment]
Found a workaround for this problem: change user.home system property of JVM.
In `\build\install\core\bin\core.bat` add a new line like `set CORE_OPTS="-Duser.home="D:\\beaker-user""`. Instead of `beaker-user` one can use any ASCII name (do not forget to replace all `\` in path by `\\`). In this case all configurations and temporary files are stored in given directory and everything works fine. 

In case of Electron installation, one needs to edit core.bat with administrative privileges.
