### ISSUE TITLE
Wrong encoding on import of non-ascii .bkr file

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#2733]
Loading via File -> open works fine, but if I try to drag and and drop file to main window (both web-version and electron) or upload it, all Russian letters are replaced with `?`-s. The .bkr file itself is in UTF-8 (I've explicitly checked that) and system encoding is cp1251.

**Comment by scottdraves** [comment]
thanks for the report.  can you please provide notebook that reproduces this problem?
emailing an attachment to me or beaker-feedback at twosigma is fine.

**Comment by altavir** [comment]
Here it is: http://sharing.beakernotebook.com/gist/anonymous/d3bec42962f02963ebbf . I just published it to server to show to students who failed to install beaker.

**Comment by scottdraves** [comment]
indeed.  we'll get to this one later since there seems to be a decent workaround.
