### ISSUE TITLE
Account activation from email link failed

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#2743]
After registering a new account I was instructed to check my email and click an activation link there.

After clicking the activation link I was greeted with this screen:
![screen shot 2015-10-16 at 11 39 49 am](https://cloud.githubusercontent.com/assets/3384784/10546231/cb6ef868-73fa-11e5-89d5-45e7e68823e6.png)

After clicking the link a second time, it worked and I was able to log in.

**Comment by ildipo** [comment]
This is datomic crashing. looking int it

**Comment by ildipo** [comment]
seems fixed
