### ISSUE TITLE
Publishing a notebook through publications interface doesn't add the publication id

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#2744]
Publishing the notebook through the publications website doesn't save it's publication id. This makes it impossible update it from Beaker even if you download the publication and import it into Beaker.

Steps:
1. Create a notebook
2. Go to the publications website: [https://pub.beakernotebook.com](https://pub.beakernotebook.com)
3. Log in
4. Click on your profile image in the upper right and select "Publish"
5. Enter the publication details
6. Download your publication and open it in the text editor
7. scroll to the bottom and notice that "publication-id" metadata is missing

**Comment by grin** [comment]
Fixed in https://github.com/twosigma/bunsen/pull/1314
