### ISSUE TITLE
some files have "TWO SIGMA INVESTMENTS, LLC" as copyright holder

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2746]
Most files have "TWO SIGMA OPEN SOURCE, LLC" as copyright holder, but the following files instead have "TWO SIGMA INVESTMENTS, LLC":
 build-sharing-server/src/app/beaker_notebook.html
 plugin/jvm/src/main/java/com/twosigma/beaker/chart/serializer/AreaSerializer.java
 plugin/jvm/src/main/java/com/twosigma/beaker/chart/serializer/BarsSerializer.java
 plugin/jvm/src/main/java/com/twosigma/beaker/chart/serializer/CrosshairSerializer.java
 plugin/jvm/src/main/java/com/twosigma/beaker/chart/serializer/PointsSerializer.java
 plugin/jvm/src/main/java/com/twosigma/beaker/chart/serializer/StemsSerializer.java
 plugin/jvm/src/main/java/com/twosigma/beaker/chart/xychart/plotitem/Crosshair.java

Perhaps an oversight?

**Comment by scottdraves** [comment]
thanks, fix will be merged monday.
