### ISSUE TITLE
Broken Link: keyboardshortcuts.html should be keyboardShortcuts.html

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#2749]
I've got the latest beaker-notebook-1.4.1, and when I click Help > Keyboard shortcuts button, I'm taken to keyboardshortcuts.html, which doesn't exist. It looks like the first 's' should be capitalized, since keyboardShortcuts.html is in the source.

**Comment by scottdraves** [comment]
Thanks for the report.  This will go into 1.4.2 early next week.
