### ISSUE TITLE
avoid compile-time dependency on npm and bower

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#275]
They are not reliable enough, we should include our dependencies in our repo and update them manually as we see fit.

**Comment by scottdraves** [comment]
this is currently breaking testing on travis.

instead of checking into our repo, we could take snapshots and host anywhere, eg s3 or elsewhere on github.

in addition to npm and bower, this should go for the copy of python we have for windows and the selenium webdriver for testing.

**Comment by scottdraves** [comment]
currently breaking the build:

```
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2
Receiving...

Error requesting archive.
Status: 503
```

yes, in order to build beaker we have to build a web browser.
and the server that hosts it happens to be overloaded.
so our build is broken too.

**Comment by scottdraves** [comment]
i am thinking it would be best to zip them and keep them in our repo.
that simplifies building, we still only have to download from github, the expansion can be done by gradle.
as a test, i zipped the contents of `core/src/main/web/vendor` and it took less than 10MB.

**Comment by ildipo** [comment]
This has been fixed some time ago
