### ISSUE TITLE
Table display automatically sorts on index - should it?

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#2753]
I was recently confused by this behavior. I had a Pandas Dataframe with a string index (rather than integer) which was not sorted. When it was shown to screen, however, its rows were sorted by index. It would be great to be able to show a Dataframe without automatically sorting it. 

Might it be worth adding an option in the table display to just show 'as is', without any sorting?

**Comment by scottdraves** [comment]
thanks for the feedback, i think you are right, it should only sort if you click the column.

**Comment by dmtrius** [comment]
Default ordering is `[0,1,...columnsNumber+1]`
