### ISSUE TITLE
blueimp-load-image seems unused

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2754]
I fail to locate anywhere in the Beaker coad that blueimp-load-image is used.

If true, I (obviously) suggest to drop it from vendor code.

What I did was grep for load-image - the stem of all files in the blueimp-load-image project.

This relates to #2649 but should be far easier to address, so hopefully need not be postponed for a later release.

**Comment by scottdraves** [comment]
do you mean you need this in 1.4.2, not in 1.5?

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-19 19:47:13)

> do you mean you need this in 1.4.2, not in 1.5?

For your project development, it seems less complicated to drop 
references to already unused code than to refactor code for changes to 
libraries - hence I suggest to apply the change faster.

For my packaging, I simply would appreciate if you could confirm or deny 
my suspicion - no matter for which release you act on it: I will in any 
case need to cherry-pick (and take responsibility not to mess up in 
doing that!) for the already released version that my current packaging 
is tied to.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by scottdraves** [comment]
confirmed
