### ISSUE TITLE
license of data contained in ipython-examples tutorial is non-free

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2755]
ipython-examples.bkr seems to include data fetched via python-pandas from Yahoo SPY site.

Web page https://finance.yahoo.com/q?s=SPY contains that the bootom the following text:

> Quotes are real-time for NASDAQ, NYSE, and NYSE MKT. See also delay times for other exchanges. All information provided "as is" for informational purposes only, not intended for trading purposes or advice. Neither Yahoo! nor any of independent providers is liable for any informational errors, incompleteness, or delays, or for any actions taken in reliance on information contained herein. By accessing the Yahoo! site, you agree not to redistribute the information found therein.

Seems to me Beaker Notebook currently violates above implicit agreement - and by the feature described in said tutorial notebook of saving data also encourages its users to violate it as well.

**Comment by scottdraves** [comment]
thank you, you are right, we'll change the example.
