### ISSUE TITLE
RJSONIO licensing effectively non-free by Debian interpretation

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2758]
RJSONIO itself is licensed as BSD-3-Clause but links against libjson which has a license considered non-free by Debian and others: https://wiki.debian.org/qa.debian.org/jsonevil

Please consider switching to either r-cran-rjson or r-cran-jsonlite (i.e. revisit #472).

**Comment by jonassmedegaard** [comment]
For the record, this issue was kindly brought to my attention by a fellow Debian developer, Jonathon Love, when I filed a "request for packaging" of r-cran-rjsonio for Debian: https://bugs.debian.org/802263

**Comment by scottdraves** [comment]
argh, i heard about this.  thanks for the report.
Unfortunately https://cran.r-project.org/web/packages/rjson/index.html does not support unicode.
I will see if jsonlite can do the unboxed values right.

**Comment by jonathon-love** [comment]
> Unfortunately https://cran.r-project.org/web/packages/rjson/index.html does not support unicode

it _does_ support UTF-8

we originally baulked at using it for exactly the same reason, but it actually does.

**Comment by scottdraves** [comment]
Looks like the libjson included by RJSONIO is not the problematic one.
this license looks good: https://github.com/duncantl/RJSONIO/blob/master/src/libjson/License.txt

**Comment by jonathon-love** [comment]
look here:

https://github.com/duncantl/RJSONIO/blob/master/src/JSON_parser.c

**Comment by scottdraves** [comment]
https://github.com/duncantl/RJSONIO/issues/21

**Comment by scottdraves** [comment]
btw, thank you jonathon

**Comment by jonathon-love** [comment]
no worries :)

i only know about this because i once tried to package rjsonio for debian, and lintian automagically picked up that a bad license was in the source!

**Comment by scottdraves** [comment]
Looking at the code, R_readFromJSON does call into the evil code, but is itself only called from oldFromJSON.  The other reference in readJSON.R is protected by if(FALSE).  oldFromJSON is only called if a 2nd parameter is given to fromJSON, which we never do.  So I think we can rip it out.

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-11-10 17:46:54)

> Looking at the code, R_readFromJSON does call into the evil code, but 
> is itself only called from oldFromJSON.  The other reference in 
> readJSON.R is protected by if(FALSE).  oldFromJSON is only called if a 
> 2nd parameter is given to fromJSON, which we never do.  So I think 
> we can rip it out.

That sounds promising.

I can understand if upstream wants to keep backwards compatibility 
and therefore not (yet?) drop even deprecated functions.

Even so, we can in the Debian packaging of RJSONIO patch the code and 
add a warning to our packaging documentation that we've killed those 
functions due to its licensing problems.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by scottdraves** [comment]
sounds like this can be handled when rjsonio is packaged, not in beaker's code.
