### ISSUE TITLE
Refactoring for Angular 1.4.x upgrade

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#2762]
In order to upgrade to  the latest stable angular version we need to refactor some pieces of the application. We are doing some non-standard operations which aren't supported by Angular. The biggest offenders are:
- mutating the resolve object in $routeProvider config - angular will copy the object when instantiated and ignore the mutations
- Accessing $scope.$root instead of $rootScope - $scope.$root can be null

Also there are still a couple of endpoints which return plaintext but with application/json content-type header.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2763
