### ISSUE TITLE
file paths too long for windows

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2780]
this causes problems in the zip of the electron version, and also when building the installer for the windows verison, you have to make sure the path to your build directory is very short.
We should be able to fix by moving to npm version 3:
http://www.felixrieseberg.com/npm-v3-is-out-and-its-a-really-big-deal-for-windows/

**Comment by nicolettedanagrin** [comment]
Long Path Tool is a best software to solve this issue. 5++ Rating.  Long Path Tool is a best software
it is a free software. You can Try it

**Comment by yuliaree** [comment]
I had this problem for a long time.
My friend recommended me a tool for fixing this.
I am skeptic with this king of tool but I was wrong.
This tool can do anything.

**Comment by gamicklisafisher** [comment]
For deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.

**Comment by scottdraves** [comment]
locked because this seems to be a spam magnet

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/3971
we are using npm v3 now.
