### ISSUE TITLE
clojure imports?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2794]
is this field in the language manager used?
seems it has been replaced by require.
![screen shot 2015-10-22 at 11 46 29 am](https://cloud.githubusercontent.com/assets/963093/10670252/b4c44aa2-78b2-11e5-9fb3-23f10b1b30b1.png)
delete it if not.

**Comment by maksim-lauryk** [comment]
yes, they are used for different goals:
- the imports field for importing Java dependencies
- the require field for Clojure dependencies
