### ISSUE TITLE
R cells show output even on variable assignment. Should they?

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#2796]
Python cells show output only when there's a print statement, or the last statement is a variable: 

x = 2 # assing value
x # show value as cell output

R cells, though, seem to show cell output just on variable assignment. 

x <- 2 # shows output

This is fine for small values, but problematic for large dataframes since their output takes so long to generate and show to screen. 

For now, I just mask the output by assigning a variable and then including a dummy assignment statement, so it gets shown to screen instead of a large dataframe. 

x <- my.large.dataframe
dummy <- ""

**Comment by scottdraves** [comment]
I see what you mean about the dataframe showing up, compared to what the native R console does.
We have had some trouble reproducing its behavior, and I would be happy to see a definitive rule
about what to show and when with R.  For me, the simpler case x <- 2 works correctly.
In the meantime you can suppress the output with just "" or 0 like this:

```
x <- my.large.dataframe
0
```

and save a few chars.
