### ISSUE TITLE
Autotranslation is slow for large dataframes

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#2799]
For a large dataframe (50k rows and 2 columns), I'm finding it takes a very long time (several minutes) to write to the Beaker object in R and then read it in Python. This takes under a second when I write to and read from a csv. Is this a known performance limitation, or perhaps some issue specific to me? I've checked that I'm not memory-constrained when this issue occurs. 

If this is a known performance limitation, then perhaps it should be included in the documentation.

**Comment by scottdraves** [comment]
Yes I have heard complaints about this.  I believe the problem is the translator was written as an R class, and the R interpreter is very slow.  It should be replaced by one written in Java or C.  We also have a longer-term plan to switch to HDF5 and shared memory segments, so we might just skip the intermediate step.

**Comment by dela3499** [comment]
Sounds exciting! Is there any wisdom in having the beaker object read/write
dataframes to/from disk, at least until a proper setup is in place? For
example:

### Python Cell

beaker.x = mydataframe # saves to temp file

### R Cell

my.data.frame <- beaker::get('x') # reads the dataframe as a csv

In the meantime, it may be worthwhile to add a prominent warning to the
autotranslation example notebook that highlights this performance issue,
and the suggested workarounds for different languages. Even better would be
to have this message appear when someone attempts to autotranslate a large
dataframe. Maybe there should just be an autotranslation timeout, and a
message like this: "Autotranslation timed out. It's often faster writing to
and reading from a file. See these [examples](link to autotranslation
notebook). Faster autotranslation is on the roadmap."

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/2814

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/3062#issuecomment-162992860
