### ISSUE TITLE
Refactor Beaker routing URL's

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#28]
Now that we switched to use query parameters for path (https://github.com/twosigma/beaker-notebook/commit/ae60c5b645037325389a5d674bffbc2876bcc74f), however, the path is still composed with prefixes that could indicate file format (ipynb, bkr) and/or file location (file system, http, dropbox, or other proprietary storages), which is undesirable.

I propose that the beaker URL should reflect the following info to be used in the session model with query parameters:
1. **path**, (e.g. /User/PyaneDiaz/myNotebook.bkr, or http://raw.github.com/abc/xyz.ipynb)
2. **pathType** (e.g. "file", "http", _optional_, if not provided, beaker should infer from the path)
3. **fileType** (e.g. bkr, ipynb. _optional_, if not provided, ideally beaker should read the file then guess)

More details about the proposal:
- The “/open” URL should be transient, it should load the file specified to be opened then create a session by redirecting to “/session”.
- The /open URL should use query parameters: path, pathType(optional), fileType(maybe optional),
- Alternatively, /open URL can be “/open/:uri” which should fall back to treat the uri arg as path and opts out on pathType and fileType. Also, the uri can be ‘new’ which opens a new session by loading the default notebook.
- The session URL should be as simple as “/session/:id”, user should refer to other part of UI (other than the browser address bar) for location of the file loaded.

**Comment by melmac48** [comment]
@anglee please verify that this has been done and close, thnx

**Comment by anglee** [comment]
The query parameters and session URL parts in the proposal is in place now. The transient /open URL still need work.
