### ISSUE TITLE
try these libraries

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2800]
http://vispy.org/
http://bl.ocks.org/bunkat/1962173
http://marmelab.com/EventDrops/
http://romsson.github.io/dragit/example/nations.html
http://philogb.github.io/

**Comment by dela3499** [comment]
It's probably not relevant here, but Mathbox 2 from Steve Wittens is really awesome. 
Blog Post: http://acko.net/blog/mathbox2/
Conference talk: http://acko.net/tv/pixelfactory/
Code: https://gitgud.io/unconed/mathbox

**Comment by scottdraves** [comment]
agreed :) https://github.com/twosigma/beaker-notebook/issues/2735

**Comment by maxyeg** [comment]
1. VisPy for webGL is unstable. I don't succeed running their webGL examples. They have issues and don't include webGL support yet (vispy.ipython) in distribution.
2. [Swimlane chart](http://bl.ocks.org/bunkat/1962173) example is [here](https://github.com/twosigma/beaker-notebook-examples/blob/master/SwimlaneChart/swimlane-chart.bkr)
3. [EventDrops chart](http://marmelab.com/EventDrops/) example is [here](https://github.com/twosigma/beaker-notebook-examples/blob/master/EventDrops/eventDrops.bkr)
4. [Wealth & Health of nations](http://romsson.github.io/dragit/example/nations.html) chart is [here](https://github.com/twosigma/beaker-notebook-examples/blob/master/WealtAndHealthOfNations/wealth_and_health_of_nations.bkr)
5. Philogb lacks sources, so no examples from there
