### ISSUE TITLE
jar in clojure tutorial, do not show stack trace

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2801]
remove this example and the jar from the settings.
<img width="288" alt="screen shot 2015-10-23 at 12 34 04 am" src="https://cloud.githubusercontent.com/assets/963093/10684727/d157e888-791e-11e5-8b41-7c01717e5242.png">

do not display stack trace in error panel (show only in cell output):
<img width="870" alt="screen shot 2015-10-23 at 12 46 21 am" src="https://cloud.githubusercontent.com/assets/963093/10684791/8f9a74b4-791f-11e5-8dd2-0a46bc62147e.png">

**Comment by maksim-lauryk** [comment]
Clojure tutorial was updated.
about stack trace, this is an exeption while initializing the clojure plugin, therefore it is shown in common error panel.
but if we will execute the cell without appropriate import then exception will shown only in cell output.
