### ISSUE TITLE
Long lines of text are obscured by cell menu

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#2808]
Long lines (usually with inline comments) are obscured by the right-justified cell menu. I often work with a split screen which highlights the issue. Perhaps the menu should only be shown when hovering over a cell, or the right side of it. 

![screenshot from 2015-10-23 12 04 56](https://cloud.githubusercontent.com/assets/5673550/10702540/365b2104-797f-11e5-847a-84f53300af13.png)

**Comment by scottdraves** [comment]
yup https://github.com/twosigma/beaker-notebook/issues/2676
