### ISSUE TITLE
Support for Real Time Data

### ISSUE THREAD

**Issue by sirinath** [twosigma/beakerx#281]
Is it possible to add special support for real time streaming data.

Nice use of real time data: http://www.ankhor.com/en/

**Comment by sirinath** [comment]
Maybe you can support data from http://www.reactive-streams.org/ as well.

**Comment by jchendy** [comment]
Thanks a lot for the suggestions. We'll be sure to check them out!

**Comment by sirinath** [comment]
Also this might give you some additional ideas http://www.dadisp.com/

**Comment by sirinath** [comment]
Some references that might give you ideas:

http://noflojs.org/
http://noflojs.org/noflo-ui/
https://github.com/kuujo/vertigo
http://verticleflow.partypeer.de/ui/
http://verticleflow.partypeer.de/
http://www.nextflow.io/
http://en.wikipedia.org/wiki/Dataflow_programming
http://en.wikipedia.org/wiki/Flow-based_programming

**Comment by scottdraves** [comment]
moved this here: https://github.com/twosigma/beaker-notebook/wiki/Future-Ideas
