### ISSUE TITLE
reimplement R autotranslation 

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2815]
https://github.com/twosigma/beaker-notebook/blob/master/plugin/r/src/dist/beaker/R/beaker.r
this is too slow for large objects https://github.com/twosigma/beaker-notebook/issues/2799
most of this should be implemented in Java via http://www.rforge.net/rJava/index.html
or C http://cran.us.r-project.org/doc/manuals/r-release/R-exts.html#Interface-functions-_002eCall-and-_002eExternal

**Comment by maxyeg** [comment]
consider branch maxy/2815

**Comment by scottdraves** [comment]
one of the motivations for this has been otherwise closed, so this has been deprioritized.
see https://github.com/twosigma/beaker-notebook/issues/2758#issuecomment-154172969

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/2814

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/1514
