### ISSUE TITLE
Separate UI From Processing

### ISSUE THREAD

**Issue by sirinath** [twosigma/beakerx#282]
It would be good if you can have Beaker Notebook in 2 tiers. A processing tier and a UI tier. The processing tier should be kept a speed demon while UI can work on a sampling basis on lower data frequencies. The processing tier should be kept gitter free as much as possible with high throughput and low latency of computations. If this is ultimately implemented you can get this accepted upstream too.

**Comment by scottdraves** [comment]
Thanks for your suggestion.  Processing of high-frequency data is best done within a code cell.

**Comment by sirinath** [comment]
The main concerns here:
1) GC Pause and gitter
2) Latency and speed
3) Inter cell data transfer and serialization performance
4) System stability and ability to handle bursts in data arriving at a higher frequency and volume (Able to process few GB of streaming data per second at least.)

Beaker Notebook has to take steps to improve on all 4 fronts above over IPython Notebook.
