### ISSUE TITLE
String columns that start with NaN are shown as all NaNs

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#2824]
String columns in a Pandas dataframe are shown correctly when the first row's value is a string, rather than a NaN. When the first value is NaN, all subsequent values are shown as NaNs. Each statement below is an observation that's either shown as table output or as text from a print statement. These observations seem to show the rich table output is the culprit, and the problem only affects string columns. 

``` python
good = pd.DataFrame({'a': ['A',np.nan]}) 
good # correct
good['a'] # correct
print good # correct

bad =  pd.DataFrame({'a': [np.nan,'A']}) 
bad # both values are NaNs
bad['a'] # correct (showing a series, rather than a dataframe, seems to work)
print bad # correct (print statements also work)

both = pd.DataFrame({'a': ['A',np.nan], 'b': [np.nan, 'A']}) 
both # column that starts with NaN shows all Nans
print both # correct

numeric = pd.DataFrame({'a': [10,np.nan], 'b': [np.nan, 10]}) 
numeric # correct (numeric data works fine)
```

**Comment by scottdraves** [comment]
confirmed: https://pub.beakernotebook.com/#/publications/562ebfec-8ae3-49d3-979c-31f22588abf4
thanks again, carlos!

**Comment by dela3499** [comment]
You're absurdly fast. Thanks for being so responsive Scott.

**Comment by scottdraves** [comment]
:) thanks -- fast at confirming bugs, that is :P
