### ISSUE TITLE
gradle run failed!

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [twosigma/beakerx#2828]
Hi there,
I'm trying to install beaker notebook on my ubuntu 15 . Here is the error I get  after running the following command :  `sudo gradle run`

```
npm ERR! Linux 3.19.0-31-generic
npm ERR! argv "node" "/usr/bin/npm" "run-script" "compile"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! beaker@0.0.0 compile: `gulp compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beaker@0.0.0 compile script 'gulp compile'.
npm ERR! This is most likely a problem with the beaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls beaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/herimanitra/beaker-notebook/core/npm-debug.log
:dev:core:compileAssets FAILED
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileAssets'.
> Process 'command 'npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.294 secs

```

Is It me or a possible bug? What can I do to solve this issue?
Thanks in advance,

**Comment by scottdraves** [comment]
we don't support ubuntu 15, we only use 14.04.  that said, it will probably work if you can get the dependencies installed.  did you do that?

i would not recommend doing the build as root.

**Comment by scottdraves** [comment]
btw, are you trying to _use_ beaker or _develop_ beaker?

users should not need gradle.

**Comment by RanaivosonHerimanitra** [comment]
I'm a user :) I've already  installed dependencies

**Comment by scottdraves** [comment]
OK so you should download our zip file and just run "beaker.command" script.

**Comment by RanaivosonHerimanitra** [comment]
you mean this one: beaker-notebook-1.4.2-0-ge55c059-ubuntu.zip ?

**Comment by scottdraves** [comment]
yes.

**Comment by RanaivosonHerimanitra** [comment]
I downloaded, unzipped  it before cloning the git file. It gave me :  `command not found`
I also ran `python beaker.command`. It gave me:

```
Traceback (most recent call last):
  File "beaker.command", line 21, in <module>
    os.chdir(os.path.dirname(self_path))
OSError: [Errno 2] No such file or directory: ''

```

**Comment by scottdraves** [comment]
In order to run command-line programs on Linux you usually need to provide the full path to them, so try "./beaker.command".  are you sure you have the dependencies though?  did you use the script to install them?

**Comment by RanaivosonHerimanitra** [comment]
ha! thank you  `./beaker.command`  works! newbie to command line :)

**Comment by scottdraves** [comment]
cool thanks.
