### ISSUE TITLE
Multiple cursors: only last selection is deleted on backspace

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#2829]
Given two lines of text,

```
one
two
```
- `ctrl + click` the end of each line to create two cursors
- `shift + left arrow` to select last letter of each line
- `backspace` to delete all selections, but only second line's selection is deleted

**Comment by scottdraves** [comment]
funny, i had no idea codemirror had multiselect :)
and indeed it is a bit broken.

**Comment by dela3499** [comment]
This codemirror issue seems relevant: https://github.com/codemirror/CodeMirror/issues/2470
