### ISSUE TITLE
Embedded Use

### ISSUE THREAD

**Issue by sirinath** [twosigma/beakerx#283]
It it possible to make this embeddable and customisable within other application to the maximum possible extend.

May be you can get some ideas from: http://www.uberfireframework.org/

**Comment by sirinath** [comment]
Since the flexibility of Beaker may be it can be also used a CMS to build rich web frontends for analytics / big data platforms.

**Comment by sirinath** [comment]
Incase you decide to use UF make sure you use a lightweight server like Jetty for the workbench components.

**Comment by scottdraves** [comment]
We are quite happy writing the client UI in native Javascript, but thanks for the suggestion.

**Comment by sirinath** [comment]
What I meant is to be able to use this within out applications.
1) To have Beaker Notebook instance be launched and run within the application
2) Customise the GUI and add as components to our applications

If willing to go the extra mile make it customizable enough to be able to design out applications in it like a CMS but not required.
