### ISSUE TITLE
Table columns misaligned with long cell entry

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#2832]
It seems like a (very) long cell entry causes the table layout to break. 

``` python
n = 1000 # correct layout for 1000, but broken for 10,000
pd.DataFrame({'a': ['val','val'], 'b': ['2',''.join(['2' for _ in range(n)])]})
```

![1](https://cloud.githubusercontent.com/assets/5673550/10831829/063f0e16-7e45-11e5-8139-93e4568d7d50.jpg)
![2](https://cloud.githubusercontent.com/assets/5673550/10831830/07b6d5bc-7e45-11e5-9a24-1f97592e482d.jpg)

**Comment by scottdraves** [comment]
yup https://pub.beakernotebook.com/#/publications/5632cc53-9fc2-4ef9-8efe-a24face90423

this is similar to cells that generally return very large strings or structures and break the browser.
thanks.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/1888
