### ISSUE TITLE
Password-protected / nonpublic notebook publishing

### ISSUE THREAD

**Issue by JoshLipschultz** [twosigma/beakerx#2834]
Currently, the 'Publish' feature can only publish notebooks publically. It would be extremely useful to have the option for password-protection or a user-based ACL system on published notebooks.

**Comment by scottdraves** [comment]
agreed, it's on the agenda.  in the meantime, if you use "unlisted" then it's fairly secret, people will only know about it if you give them the URL, which is impossible to guess.

**Comment by scottdraves** [comment]
This should be in the FAQ.

**Comment by JoshLipschultz** [comment]
Cool. Thanks for the quick response!

It looks like [this page](https://github.com/twosigma/beaker-notebook/wiki/Options-for-notebook-sharing) should be updated as well. By the way, Google Drive integration would solve this problem, actually, because of its Google account-based sharing features.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/commit/4a0bbef85b08457852bf2bbfa9628eae23cfcc51
