### ISSUE TITLE
Disable debug mode in production

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#2847]
By default AngularJS attaches information about binding and scopes to DOM nodes, and adds CSS classes to data-bound elements. This negatively affects performance and should be only enabled when we run Beaker in debug mode: https://code.angularjs.org/1.4.7/docs/guide/production

Unfortunately it's not possible to reliably test the performance gain from removing the debug data as Protractor relies on it and will forcibly enable the debug mode.

**Comment by scottdraves** [comment]
also let's not deliver the map files along with the js, they are expensive.
