### ISSUE TITLE
Blank Screen on startup

### ISSUE THREAD

**Issue by clokey** [twosigma/beakerx#285]
When I download the pre-compiled beaker notebook and run the beaker-command shell fire, chrome launches and i get a blank page. There are no error messages in the shell window. When I do a view source on the blank page I can see a valid HTML document, so i assume one of the Javascript files isn't working correctly.

I then viewed the Javascript console and have the following error message:
Failed to load resource: net::ERR_CONNECTION_REFUSED  http://127.0.0.1:8801/beaker/rest/util/getInitPlugins

I installed the pre-requisites by hand and built from source, and get a valid front page and am able to create the tutorial notebook. So must be something about how the pre-compiled version is packaged

**Comment by scottdraves** [comment]
Thanks for the bug report.  I haven't seen that before -- but we can try remote debugging if you are game.  Email spot@draves.org and we can set up an IM session or screen-sharing.

**Comment by clokey** [comment]
I think i've completely broken my install whilst i've been trying to fix it. let me start over with the pre-requisites and see if i can get back to the blank page :-(

**Comment by melmac48** [comment]
@clokey were you able to reproduce this?

**Comment by clokey** [comment]
Hi Mel,

I tried and failed. I am having some other issues getting it running, but that is entirely down to my setup. I think I am going to wait for a few more builds to come out and then try again.

Sorry I wasn't more useful

M

**Comment by melmac48** [comment]
no prob, thanks for giving it a shot. I'm going to close this as not reproducible but if you see it again with a future build feel free to reopen.
