### ISSUE TITLE
Unable to download docker beakernotebook

### ISSUE THREAD

**Issue by ScottPJones** [twosigma/beakerx#2857]
I have a totally new installation of docker, on OS X El Capitan (on a MBP with 284GB free).
I ran the command as per instructions, but got the following errors:

> Scotts-Retina-MBP:~ scott$ docker ps
> CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
> Scotts-Retina-MBP:~ scott$ docker pull beakernotebook/beaker
> Using default tag: latest
> latest: Pulling from beakernotebook/beaker
> 50d64b1c89ba: Verifying Checksum
> ...
> Pulling repository docker.io/beakernotebook/beaker
> 3568599a7654: Error pulling image (latest) from docker.io/beakernotebook/beaker, Untar re-exec error: exit status 1: output: write /usr/lib/python2.7/dist-packages/scipy/optimize/_cobyla.so: no space left on device ptimize/_cobyla.so: no space left on device
> ...
> b25029b674f2: Error downloading dependent layers
> Error pulling image (latest) from docker.io/beakernotebook/beaker, Untar re-exec error: exit status 1: output: write /usr/lib/python2.7/dist-packages/scipy/optimize/_cobyla.so: no space left on device

Any help?  Thanks!

**Comment by scottdraves** [comment]
this sounds like a docker problem, not a beaker problem.

**Comment by ScottPJones** [comment]
OK, thanks!
