### ISSUE TITLE
Better way of installing breakpoints

### ISSUE THREAD

**Issue by clokey** [twosigma/beakerx#286]
Anaconda doesn't play very well if people use the homebrew package manager on Mac OS X. There are alternative ways of getting IPython to work that play nicely with homebrew.

Perhaps all of the dependencies can be listed so people can follow whatever means is necessary to get pre-req's set up

**Comment by scottdraves** [comment]
What's the problem with Anaconda and Homebrew?   What way would you recommend for getting IPython?

The dependencies are listed here: https://github.com/twosigma/beaker-notebook/wiki/Mac-build-and-run

It's definitely too much work to install Beaker, the discussion of this is here: https://github.com/twosigma/beaker-notebook/issues/221

**Comment by clokey** [comment]
After I had installed anaconda, i did a brew doctor (something I do on a fairly regular basis). There are a lot of warnings as homebrew didn't install python and other dependencies. Furthermore, when I performed a qmake (sorry can't remember whether this was in the context of trying to get beaker running) it picked up the Anaconda versions of the qspec's rather than the one's installed by brew.

IPython itself has a large number of dependecies, not all of which are mandatory. Therefore the the request was, which bits of IPython do you need to get it to work, as the install Anaconda seems quite heavy weight.

Hope that makes sense

**Comment by scottdraves** [comment]
Going to assume this is part of our general dependency cleanup slated for 2.0
