### ISSUE TITLE
Click add code cell button expand menus on the whole page

### ISSUE THREAD

**Issue by maxyeg** [twosigma/beakerx#2868]
When you click 'code' or 'section' menu button to choose what cell to add, all such menus are toggled in the whole notebook.

Steps to replicate:
1. Create notebook
2. Add two or more cells(any)
3. Press 'section' or 'code' button to add a code or a section cell
You can see all menus opened. Screenshot attached.
![untitled](https://cloud.githubusercontent.com/assets/2286032/10969713/23e272e6-83db-11e5-9657-ef03c8e5088f.png)

**Comment by tomca32** [comment]
I'm sure I introduced this yesterday. I remember encountering that bug and then I was pretty sure I fixed it in the next commit.

Apparently not. Anyway, I believe I know what the issue is and will try to fix it today

**Comment by maxyeg** [comment]
@tomca32 great! Thanks!

**Comment by tomca32** [comment]
Nope I was wrong. I didn't introduce this (phew), it seems that it actually always worked this way but previously we never had more than one Insert Cell menu shown on the screen at the same time (bottom one was faded out). 

It seems that we always opened all Insert Cell menus but only one was visible on the screen so it didn't matter.
