### ISSUE TITLE
Adding Python Packages to Docker?

### ISSUE THREAD

**Issue by hydrosquall** [twosigma/beakerx#2872]
I wanted to add the beautifulsoup4 library to my ipython code, so I ran pip install beautifulsoup4 on the container, and successfully installed the module. 

``` shell
docker exec -it beaker bash
pip install beautifulsoup4
```

However, when I run ipython, it doesn't pick up on the installed package. Anyone have ideas about how to properly add python packages in docker so that beaker notebook detects the additions?

**Comment by danpolanco** [comment]
Same issue here when I installed synapse client.

**Comment by scottdraves** [comment]
it worked for me.  make sure you do the pip install before you start any python.
