### ISSUE TITLE
Cannot find julia on OS X

### ISSUE THREAD

**Issue by xiaoweiz** [twosigma/beakerx#2878]
julia version: 0.4
python version: 3.5 from Anaconda 2.4

`IJulia` is installed and `julia` can be used with `jupyter-notebook`. 

`R`, on the other hand, can be found by beaker. I've add the path info of `julia` in `beaker.pref.json` but it still doesn't work.

**Comment by scottdraves** [comment]
Thanks for the report.  Unfortunately Julia put the version number into the kernel name, and Beaker is requesting version 0.3.  You can hack around this by editing julia.js line 89, which you can find inside the application.  I can tell you how more precisely if you say your OS and if you are using our Electron version.

Really Beaker should query the Jupyter backend so it can always match.

**Comment by xiaoweiz** [comment]
Just found a similar issue #1602. 

Revising the line [https://github.com/twosigma/beaker-notebook/blob/master/plugin/ipythonPlugins/src/dist/julia/julia.js#L89] to change the kernel name from `julia-0.3` to `julia-0.4` solves the problem.

**Comment by xiaoweiz** [comment]
Thanks for your quick response. I was typing my own finding while you're replying! :)

**Comment by scottdraves** [comment]
no problem, thanks for the report.  since julia has moved 0.4 up to their default download we should at least update our default, if not query.

**Comment by scottdraves** [comment]
cit, please find the API call jupyter uses to get the list of available kernels, and call find find a kernel that starts with "julia" and then use that to start our backend.
