### ISSUE TITLE
file save dialog can go off the bottom of the window

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#288]
If you open a folder with a lot of subfolders or if you just make your window short, the bottom of the dialog, including the Open/Canel buttons goes off the bottom of the window and becomes inaccessible.

**Comment by melmac48** [comment]
@anglee is it reasonable to assume that this will go away with the new UI changes? if not, we should fix it

**Comment by anglee** [comment]
I am actually not sure if file choosers are already included of the new UI design? I couldn't seem to find them in the doc. If not, I think they should.

**Comment by melmac48** [comment]
I've asked Lub to mock some up.

**Comment by scottdraves** [comment]
This did not go away, it still drives me nuts when it happens, it is hard to workaround too.  It's very common on a laptop.
@samccone if you don't have time for this one please let me know.

**Comment by scottdraves** [comment]
In file close, when i scroll it to the bottom, i there are still entries from the file list that are hidden behind the footer of the modal window (you can see a sliver of one of the last ones).  In fact the thumb part of the scrollbar is not visible at all because it is also behind the footer.
![screen shot 2014-09-09 at 7 32 25 pm](https://cloud.githubusercontent.com/assets/963093/4210651/f73914e6-3879-11e4-886a-5df8e97a41ce.png)

also this bug has been introduced: https://github.com/twosigma/beaker-notebook/issues/597

Also, whatever fix we finally get for save needs to be applied to open as well.

**Comment by samccone** [comment]
I think we should revert this until a proper fix can be done

**Comment by scottdraves** [comment]
ok, reverted.

**Comment by samccone** [comment]
:dancers:

**Comment by scottdraves** [comment]
:dolphin:
