### ISSUE TITLE
old python confuses beaker on windows

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2882]
a user had a generic python (not ipython) installed and in their system path.
they installed anaconda python to use beaker.
they started beaker and started python and it crahes right away, when trying to compute the hash.

**Comment by scottdraves** [comment]
the workaround was to remove old python from the path, but we should not fail at all.
seems like the simplest way would be to avoid calling python, only call ipython.
there must be a way to hash the password from within ipython...

this probably isn't a windows specific problem.

**Comment by hydrosquall** [comment]
Thanks @scottdraves for fixing this problem on my computer! Just leaving a comment so I can find it again if it happens on a friends' computer / to know when the bug gets patched :)

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2910
