### ISSUE TITLE
output table in closed section not visible on open

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2887]
looks like i merged https://github.com/twosigma/beaker-notebook/pull/2879
too fast.  try this notebook: https://pub.beakernotebook.com/#/publications/563e4f52-572d-47d5-84db-31a8b58581dd
open the section, see there is no table.  delete the section, then the table appears.

**Comment by tomca32** [comment]
interesting, will take a look at this now

**Comment by scottdraves** [comment]
please IM me on slack.

**Comment by tomca32** [comment]
I believe this is fixed. Do you want to close this @scottdraves ?
