### ISSUE TITLE
make plot and table interactions programmable

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2888]
from groovy (initially but also js/python/r) you should be able to attach actions to various elements in the plots and tables, so you can have a closure be called or a cell tag be executed when you user clicks on a cell in a table, or clicks on a data point in a plot.

The plotitems classes like Line() and Bars() should have another parameter onClick that takes a closure that gets called when you click on that item.  The closure receives an object with the x/y coordinates of the item you clicked on (values from the xs, ys arrays), as well as the index into the xs/ys arrays, and the line object itself, and general event info (with things like mouse coordinates and modifier keys).  also allow onKey().  also allow a string instead of a closure, then it runs cells with that tag and defines a global with the event object.  see the implementation of EasyForm for an example of how to get a closure called from JS.

**Comment by scottdraves** [comment]
plots done.  tables soon!

**Comment by Pandaski** [comment]
Hi @scottdraves 
Could you let me know if the programmable interactions is implemented in Python based Plots?
I am trying to implement an interactive action in Python BeakerX Plot like the Groovy version done. But i cannot find any document about that, even I cannot find related attribute in the Line object.

I know this branch is closed in 2 years ago. So your (or any other people's) reply will be highly appreciated. Thx!

**Comment by scottdraves** [comment]
Thanks for the report, I opened https://github.com/twosigma/beakerx/issues/7523
