### ISSUE TITLE
Duplicate input area in code mirror

### ISSUE THREAD

**Issue by maxyeg** [twosigma/beakerx#2891]
In every code cell now I see two input areas in code mirrors.
When I reopen notebook stored in session, empty code cells looks correct.
![e40e6-clip-6kb](https://cloud.githubusercontent.com/assets/2286032/11032639/14c454b2-86ee-11e5-8295-d7aa95ed4dfc.png)
I see this in Chrome and it works well in FF.

**Comment by scottdraves** [comment]
confirmed.
