### ISSUE TITLE
Create Live / Realtime Books 

### ISSUE THREAD

**Issue by sirinath** [twosigma/beakerx#291]
This is just a idea. Perhaps it would be good to make this something there you can easily create books like in https://www.gitbook.io/

**Comment by scottdraves** [comment]
yea that's really cool also this just came across my desk:
https://github.com/mbutterick/pollen

and there is a great history of myriad literate programming systems

**Comment by sirinath** [comment]
Another example I stumbled upon: https://github.com/javiereguiluz/easybook

Perhaps you can get some ideas from this also.

**Comment by scottdraves** [comment]
Thanks for the links, I don't see this as directly actionable however.

**Comment by sirinath** [comment]
It would be good to have a open source alternative to http://www.wolfram.com/cdf/. So please reconsider.
