### ISSUE TITLE
moving past last line crashes

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2913]
if you press down arrow on the last line of a code cell, it should move to the next cell.
instead i get this stack trace:

```
Uncaught TypeError: scope.bkNotebook.getFocusable(...).focus is not a function
moveFocusDown @ core.js:503
goDownOrMoveFocusDown @ core.js:491
...
```

same for up arrow

**Comment by maxyeg** [comment]
@scottdraves , the same is for up arrow, when you in the first line of a cell and it should move you to the previous cell. Getting 't.focus is not a function'.
