### ISSUE TITLE
Need help with beaker notebook on remote server

### ISSUE THREAD

**Issue by mathsong** [twosigma/beakerx#2920]
Hello,

newbie with almost everything here and tried to install beaker notebook on aws ec2.  
when building from source code following the instruction ( install-dependencies.sh + gradle run ),
I stuck at "beaker Building 0% > :run > :dev:run" after "starting nginx instance ";
when running the docker image, I got a weird ip like "https://321b94ebff76".

I was also wondering if there were an option similar to "c.NotebookApp.open_browser = False" on jupyter notebook, which disables launching a browser on a remote server.

As I couldn't find answers from google, I have to come here. Any help is greatly appreciated.

Ian

**Comment by scottdraves** [comment]
docker is probably best.  once it starts, just ignore the IP/URL that it prints out.  you should know the IP or hostname of your instance, just use that (but do copy the port number).  the open_browser option is not needed, it does that automatically.

**Comment by mathsong** [comment]
Thanks a lot. Docker image works fine now and beaker notebook is kind of cool.

But as an R user, I prefer not running docker image because of the ability to add R packages.. 
Here is where I stuck when building from source (any suggestion is appreciated)
...
:dev:core:build
:dev:core:copyGGVis
:dev:core:copyJQueryUIImages
:dev:core:copyKatex
:dev:core:copyRequireJS
:dev:core:copyVendorStuff
:dev:core:installApp
:dev:build
:dev:run
starting nginx instance (/home/ubuntu/beaker-notebook/core/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

> Building 0% > :run > :dev:run

I guess beaker has opened a browser now and is listening to localhost, but I am on a headless remote server..

**Comment by mathsong** [comment]
I guess beaker has opened a browser now and is listening to localhost, but I am on a headless remote server..
