### ISSUE TITLE
code mirror line spacing too small on pub

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2944]
on pub.beakernotebook.com:
<img width="204" alt="screen shot 2015-11-13 at 3 08 36 pm" src="https://cloud.githubusercontent.com/assets/963093/11156217/802fbad4-8a18-11e5-8351-70d76f467582.png">
in the live application:
<img width="219" alt="screen shot 2015-11-13 at 3 03 09 pm" src="https://cloud.githubusercontent.com/assets/963093/11156216/7fd2c784-8a18-11e5-81cd-56169a93d498.png">

**Comment by ildipo** [comment]
this is fixed on current pub server
