### ISSUE TITLE
matrix display in R

### ISSUE THREAD

**Issue by mathsong** [twosigma/beakerx#2947]
sth. wrong with matrix dimnames in R.
e.g.

```
l <- list(c("-1","1"), c("-1","1"))
matrix(c(200,34,41,225), nrow=2, dimnames=l)
```

I suppose to get

```
    -1   1
-1 200  41
1   34 225
```

but beaker gave me

```
     -1    1
0 200.0000  41.0000
1 34.0000   225.0000
```

https://pub.beakernotebook.com/#/publications/5647ddcd-a9ae-4367-baa2-a427f22f85e5

**Comment by scottdraves** [comment]
thanks for the report.  we got row names but i did not know about dim names.
will look into fixing it.
