### ISSUE TITLE
Only one login allowed?

### ISSUE THREAD

**Issue by mathsong** [twosigma/beakerx#2955]
If running beaker with --public-server and have a active session on one computer, I can't login on any other machines. Googled, but got no answers. (jupyter allows multiple login.)

**Comment by scottdraves** [comment]
thanks for the report.
it should allow multiple logins, what kind of error did you get?

**Comment by mathsong** [comment]
Thanks for quick reply as always.
I tried on 3 other computers with no success -- no matter what password I submit, the right one with great care or some random input. I only got the reload button, in the top-left corner of chrome, rotate one round. There is no any error message.

**Comment by scottdraves** [comment]
is this still a problem?

**Comment by mathsong** [comment]
You may close this case. Tks!
