### ISSUE TITLE
try plotly

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2962]
https://github.com/plotly/plotly.js

**Comment by filipstachura** [comment]
Are there any plans on getting plotly supported in beaker?

**Comment by scottdraves** [comment]
this is done, actually.  plotly already works for Python just fine:
https://pub.beakernotebook.com/#/publications/56675e19-d844-47a1-ac03-100aef8a68c1?fullscreen=false
R works but requires an IFrame, we'll fix that shortly.
