### ISSUE TITLE
IPython fails to start

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#2966]
Steps:
1. Open Beaker landing page
2. Click New Default Notebook
3.  Wait for IPython to start
4. Observe the error alert

![screen shot 2015-11-18 at 10 28 40 am](https://cloud.githubusercontent.com/assets/3384784/11245138/30986f32-8ddf-11e5-9936-7e1aae6396b3.png)

**Comment by tomca32** [comment]
Also in the browser console we get the following error:
http://127.0.0.1:8801/93017c3/ipython.732108985775/api/sessions/ Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by tomca32** [comment]
Seems to first happen in this commit: ed5a0ec37aa42452c21fab5a230b006a302627c9

**Comment by kpaharelau** [comment]
I found little problem with windows quotes and fixed it.  Problem still exists for MacOS. I   have not  MacOS at the current moment

**Comment by kpaharelau** [comment]
see my PR with fixes for windows os

https://github.com/twosigma/beaker-notebook/pull/2975

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2975
