### ISSUE TITLE
shift-tab does not show docs

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2967]
In Python this should show the documentation.
this is a regression, it worked before.

**Comment by mnavasiolava** [comment]
note: works fine on master f13013e5a112aab44e324b98e94d61e9b928a376 (windows, ipython 3.0.0)

**Comment by mnavasiolava** [comment]
after fixing the problem with ipython hash (#2966), works also on Mac OS
![image](https://cloud.githubusercontent.com/assets/12935591/11294174/7080f42c-8f72-11e5-8cc5-16c07570ab6b.png)
