### ISSUE TITLE
Plot state is not saved on Ctrl/Cmd+S

### ISSUE THREAD

**Issue by mnavasiolava** [twosigma/beakerx#2971]
Open interactive chart tutorial, select File->Save, open .bkr file - you can see that plots states are saved:
`"state": {
                    "focus": {
                        "xl": 0.4738095238095238,
                        "xr": 0.5261904761904762
                    },...`
Open interactive chart tutorial, press Ctrl/Cmd+S, open .bkr file - plots states are empty:
`"state": {}`

P.S. checked on commit f13013e5a112aab44e324b98e94d61e9b928a376 because states saving was removed by mistake from master, but it will be reverted when issue #2963 is fixed

**Comment by scottdraves** [comment]
sounds very weird, glad you found this bug!
