### ISSUE TITLE
Error when making q variable visible to other languages

### ISSUE THREAD

**Issue by himoacs** [twosigma/beakerx#2989]
Hi,

I am getting this error when I try to run the kdb tutorial:

/ Make the trades table visible to the notebook.
.bk.s[`trades; trades]

Error
 kx.c$KException: .j.j

Any idea what I need to do to get this to work? I am using mac and have python/kdb installed. 

Thanks!

**Comment by scottdraves** [comment]
thanks for the report, i'll look into this.
what version of beaker are you running and on what OS?

**Comment by himoacs** [comment]
I am running version: 1.4.2-0-ge55c059 on mac os (el capitan)

**Comment by scottdraves** [comment]
i justed tested on a mac (10.10.5) with kdb v3.3 32bit version from http://kx.com/software-download.php and it worked fine.

are you using the 64bit version?

**Comment by scottdraves** [comment]
did you run the cells leading up to that one in the kdb notebook?

**Comment by himoacs** [comment]
i had run all the code before.

I was running kdb 3.1. I upgraded to 3.3 and it works now. Thanks for your help!
