### ISSUE TITLE
note use of  #!/usr/bin/python in install docs

### ISSUE THREAD

**Issue by cldougl** [twosigma/beakerx#3012]
It may be helpful to mention the use of `#!/usr/bin/python` in `beaker.command` (and elsewhere) OR that python must be installed at `/usr/bin` in the install docs. I didn't have a python version located at `/usr/bin` and it took me quite a while to realize what the problem was. It wasn't very clear to me why the build was failing. 
<img width="413" alt="screen shot 2015-12-01 at 10 56 35 pm" src="https://cloud.githubusercontent.com/assets/2789078/11521895/30e622ea-987f-11e5-82da-0539a10ac1c5.png">

**Comment by scottdraves** [comment]
Thanks for the report.  I believe Python at this location is a standard part of Mac OS X though.
How did you not have it?

**Comment by cldougl** [comment]
It's possible I removed it a while back due to an anaconda-related problem. I haven't previously had any issues related to this absence - I mostly work in virtual environments and have python at `/usr/local/bin`.

**Comment by scottdraves** [comment]
OK well if you delete part of your OS things are going to break.
Sorry it was confusing.
