### ISSUE TITLE
Can't get the docker container to work

### ISSUE THREAD

**Issue by ismail** [twosigma/beakerx#3014]
This is on openSUSE Linux x86-64:

λ docker --version
Docker version 1.9.0, build 76d6bc9

λ docker run -p 8800:8800 -t beakernotebook/beaker
starting nginx instance (/home/beaker/src/core/nginx)
nginx-stderr>nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to https://5f7b485e7de1:8800/
Submit this password: eYgRWFJw5azVWuU

Notice that hostname just doesn't make any sense. Trying to browser to https://localhost:8800 in Chrome just hangs.

Trying to connect with curl hangs too:

λ curl -v https://localhost:8800
- Rebuilt URL to: https://localhost:8800/
-   Trying ::1...
- Connected to localhost (::1) port 8800 (#0)
- ALPN, offering http/1.1
- Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
- TLSv1.2 (OUT), TLS header, Certificate Status (22):
- TLSv1.2 (OUT), TLS handshake, Client hello (1):

**Comment by scottdraves** [comment]
Thanks for the report, we'll look into it and get back to you.

**Comment by ashishbajpai** [comment]
Had the same issue and the following worked for me - 
At Docker Quick Start terminal on startup I see the following message - 

```
                    ##         .
              ## ## ##        ==
           ## ## ## ## ##    ===
       /"""""""""""""""""\___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
       \______ o           __/
         \    \         __/
          \____\_______/
```

docker is configured to use the default machine with IP **192.168.99.100**
For help getting started, check out the docs at https://docs.docker.com

I am able to use beaker notebook when i use the IP address above.(in bold).

Hope this works for you.

**Comment by ismail** [comment]
Just tried again today and it works now, thanks!

**Comment by pgensler** [comment]
#4829
