### ISSUE TITLE
Scala plugin fails to initialize, but no errors, spinner runs indefinitely

### ISSUE THREAD

**Issue by Zavster** [twosigma/beakerx#3018]
I just downloaded the latest base installation and tried creating a Scala cell. From the Language Manager, I clicked on Scala, the LED went orange, but never goes green. I've let it run for an hour, not errors come up, so not clear what is going on.

**Comment by scottdraves** [comment]
Thanks for the bug report, sorry it didn't work for you.  It should only take a second or two, so definitely seems broken.  Do any of the other built-in languages work (like groovy and java)?  What OS are you on and what browser?

**Comment by Zavster** [comment]
I managed to get both Groovy and Java working. The latter appeared to be more temperamental as I needed to try it a few times after restarting the notebook kernel, then eventually it worked. I am on Windows 7, using the latest version of Chrome. I will try install beaker on my mac tonight to see if it is perhaps something that is machine specific. When you start a new language, does it essentially start another web server process in the background on a distinct port? It looks like something starts on port 8084 after I start the Scala language, but when I navigate to http://localhost:8084 it challenges me for a password using http basic authentication.

**Comment by scottdraves** [comment]
Yes, it starts a server but it's password protected and behind our reverse proxy.  To the web application, everything just appears in one namespace.  Are there any errors on the JavaScript console, or in the terminal where you ran Beaker?

**Comment by Zavster** [comment]
No errors in the terminal. I see the following messages on stdout...

Running
0: C:\X\libs\beaker-notebook-1.4.2\python\python
1: C:\X\libs\beaker-notebook-1.4.2/config/plugins/eval/scala/scalaPlugin
2: 8804
Done starting Scala
Scala-stdout>*\* Note that as of 2.8 scala does not assume use of the java classpath.
Scala-stdout>*\* For the old behavior pass -usejavacp to scala, or if using a Settings
Scala-stdout>*\* object programmatically, settings.usejavacp.value = true.

Then I see lots of blank lines, and then...

Scala-stdout>*\* Note that as of 2.8 scala does not assume use of the java classpath.
Scala-stdout>*\* For the old behavior pass -usejavacp to scala, or if using a Settings

In the Chrome console, I see the following...

![image](https://cloud.githubusercontent.com/assets/9557117/11546934/349a7a18-991e-11e5-8e6e-ed607f9a5fee.png)

**Comment by Zavster** [comment]
I also see the progress meter saying Starting language Scala... and the spinner is active, indefinitely.
![image](https://cloud.githubusercontent.com/assets/9557117/11546965/76587a18-991e-11e5-9986-799c034c226a.png)

**Comment by Zavster** [comment]
I installed it on my macbook at home, and it seems to run the Scala plugin just fun...obviously machine specific, but the distribution definitely doesn't seem to work on my machine at the office. Could there be some issue with port blocking, or the anti virus system that is getting in the way?
![image](https://cloud.githubusercontent.com/assets/9557117/11547619/575edc74-9923-11e5-8b8c-f212a5248610.png)

**Comment by scottdraves** [comment]
cool, thanks for the update.  the ports don't seem to be blocked, since you were able to get it to ask you for a password.  maybe could be anti-virus, idk...  can you disable it temporarily and try?  i haven't heard of anyone else having this problem.

**Comment by Zavster** [comment]
I'll try again tomorrow when I'm back in the office. At least it seems to be machine specific. Either way, would be good for something to time out or provide some error message as not much to go on. Thanks for your help.

**Comment by Zavster** [comment]
Sadly no luck this morning. I have tried it with latest IE, FireFox and Chrome, all with the same result. I think the back-end is starting fine, but for some reason the web client seem to connect. Is there a way I can run this in debug mode or look at some log files?

**Comment by Zavster** [comment]
Looks like the call that is blocking is setShellOptions() and for some reason that doesn't complete.
![image](https://cloud.githubusercontent.com/assets/9557117/11561754/74f8f552-9997-11e5-9e84-6ad9fca228e2.png)

**Comment by Zavster** [comment]
Apologies for the spam - seems like another call is blocking on cometd...

![image](https://cloud.githubusercontent.com/assets/9557117/11561823/e7ae5b96-9997-11e5-9935-d15da73c3b86.png)

**Comment by Zavster** [comment]
Not sure if this helps, but there are two entries in the log for the nginx instance started for the Scala plugin as below. I tried to connect to these urls from the browser, but get an authentication challenge, which suggests those end points are alive.

2015/12/03 09:17:43 [error] 11556#11720: *31 CreateFile() "C:\Users\witdouckx.beaker\v1\nginx9111498757986866537/html/restart.288645106451/present.html" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: , request: "GET /restart.288645106451/present.html HTTP/1.1", host: "127.0.0.1:8803"
2015/12/03 09:17:44 [error] 11100#11296: *33 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/scala.429564207648/rest/scalash/ready HTTP/1.1", upstream: "http://127.0.0.1:8804/rest/scalash/ready", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"

**Comment by scottdraves** [comment]
:( sorry i am still baffled...

**Comment by scottdraves** [comment]
hi, can you try again with v1.5 think this was fixed...
https://github.com/twosigma/beaker-notebook/issues/3292

**Comment by Zavster** [comment]
Hi mate,

I did try the 1.5 version yesterday, and it works! Thanks very much, I will
definitely be promoting it at our firm. Great piece or work!

Cheers,
Zav
