### ISSUE TITLE
we use a hacked version of d3

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3033]
in order to avoid the amd madness, we had to hack d3:

https://github.com/twosigma/beaker-notebook/blob/688968b15f606ed36ffb6cb92a03d9cfb828864b/core/src/main/web/vendor/bower_components/d3/d3.js#L9549-L9551

https://github.com/mbostock/d3/issues/2606

not sure yet how hard it is to avoid this

@jonassmedegaard

**Comment by tomca32** [comment]
To explain exactly what's happening:

When d3 is loaded it will try to detect if we have RequireJS loaded (RequireJS is a module loader). If D3 detects RequireJS, it will export itself as an AMD module. If not it will just attach itself to global object (window).

So far so good. We have RequireJS so we should be able to load D3 as a module.
Unfortunately, RequireJS will throw an exception if it tries to load a source from a script tag as a module:
"Be sure to load all scripts that call define() via the RequireJS API. Do not manually code script tags in HTML to load scripts that have define() calls in them." - http://requirejs.org/docs/errors.html#mismatch

Now we can load D3 through RequireJS API but that would require us to dynamically load it which we want to avoid.

**Comment by jonassmedegaard** [comment]
Quoting Tomislav Pesut (2015-12-04 21:56:04)

> To explain exactly what's happening:
> 
> When d3 is loaded it will try to detect if we have RequireJS loaded 
> (RequireJS is a module loader). If D3 detects RequireJS, it will 
> export itself as an AMD module. If not it will just attach itself to 
> global object (window).
> 
> So far so good. We have RequireJS so we should be able to load D3 as a 
> module.
> Unfortunately, RequireJS will throw an exception if it tries to load a 
> source from a script tag as a module:
> "Be sure to load all scripts that call define() via the RequireJS API. 
> Do not manually code script tags in HTML to load scripts that have 
> define() calls in them." - 
> http://requirejs.org/docs/errors.html#mismatch
> 
> Now we can load D3 through RequireJS API but that would require us to 
> dynamically load it which we want to avoid.

Would it perhaps make sense to ask d3 developers if they can provide a 
mechanism to force suppress their RequireJS auto-detection?

I imagine you are not unique in (if I understand it correctly) needing 
to preload d3 while using RequireJS for other parts.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by scottdraves** [comment]
yes IMO d3 should deliver a plain version of their lib via a build step, similarly to how they deliver minified and concatenated versions.  i want to review the situation before i file an issue there though.  since the modification is quite simple i think it could be reliably done by sed during packaging regardless of the response.

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-12-05 22:18:09)

> yes IMO d3 should deliver a plain version of their lib via a build 
> step, similarly to how they deliver minified and concatenated 
> versions.  i want to review the situation before i file an issue there 
> though.  since the modification is quite simple i think it could be 
> reliably done by sed during packaging regardless of the response.

Other (re)distributors of d3 than (vendor dir of) Beaker would benefit 
from such a mechanism as well.  I agree that any (re)distributor could 
juggle with sed themselves as needed, but would sure be better if done 
once upstream and supported by them.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by mnavasiolava** [comment]
faced with the same issue for big.js when running beaker electron version for MacOS.
so big.js will be also hacked (https://github.com/twosigma/beaker-notebook/pull/3213)
