### ISSUE TITLE
Changes to IPython setup code not present when creating new notebook

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#3037]
I'd expect the setup code to consist of imports that every analysis should have. But, changes to setup code aren't present when starting a new notebook. Only the default setup code is there. Perhaps I've set things up incorrectly or misunderstood the purpose of setup code.

**Comment by scottdraves** [comment]
the setup code is per notebook, so every time you make a new notebook, you get the default setup code.

sounds like what you want to do is update your default notebook.  set your setup code and active plugins and any boilerplate all saved in a regular notebook file, and then copy it to ~/.beaker/v1/config/default.bkr and then next time you click "new default noteobok" you'll get what you want.
