### ISSUE TITLE
opening easyform tutorial

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3038]
produces stderr

```
Client is trying to subscribe to nonexisting object ace9d52f-f694-460d-974c-cd33bb90fedf
lient is trying to subscribe to nonexisting object ace9d52f-f694-460d-974c-cd33bb90fedfClient is trying to subscribe to nonexisting object d178101b-1f54-4d22-b363-8f4a04193f62
lient is trying to subscribe to nonexisting object d178101b-1f54-4d22-b363-8f4a04193f62Client is trying to subscribe to nonexisting object d178101b-1f54-4d22-b363-8f4a04193f62
lient is trying to subscribe to nonexisting object d178101b-1f54-4d22-b363-8f4a04193f62Client is trying to subscribe to nonexisting object b726ad08-7102-4c81-a810-cc278de23319
```

**Comment by scottdraves** [comment]
if form is instantiated without object, it should show an error state (red box?) and be nonfunctional until properly connected.

**Comment by mnavasiolava** [comment]
reproduced both on mac and windows: you should just run the 1st cell of the tutorial and then scroll the page to the end.

**Comment by scottdraves** [comment]
i see it sometimes and not others.  it's not reliable.  every time i see a bunch of

```
TypeError: value.forEach is not a function
    at writeNgOptionsMultiple [as writeValue] (beakerVendor.js:66548)
    at ngModelCtrl.$render (beakerVendor.js:68572)
    at Object.ngModelWatch (beakerVendor.js:65477)
    at Scope.$digest (beakerVendor.js:55872)
    at Scope.$apply (beakerVendor.js:56151)
    at beakerVendor.js:57918
    at completeOutstandingRequest (beakerVendor.js:45561)
    at beakerVendor.js:45838
```

errors and i have to think it's the same basic cause: the form GUI is trying to sync with an object that no longer exists.  if you look into easyform.bkr you can see

```
"update_id": "ace9d52f-f694-460d-974c-cd33bb90fedf"
...
"update_id": "d178101b-1f54-4d22-b363-8f4a04193f62"
```

this should probably not be saved into the file at all since it will never make sense later.

when the file is opened and you read it in, and instantiate the form, you should not bother trying to sync it back to the JVM.  in this state, with an update_id, the form should be displayed in a read-only state,
with all the widgets disabled.

**Comment by mnavasiolava** [comment]
yes, you are right about "update_id" in .bkr

how it works now: when easy form is instantiated from .bkr file it tries to subscribe to update_object channel with the object update_id taken from .bkr file.
the reason that you don't see the error every time is that instance of UpdateManager (the one who throws the error) is not created until e.g. any cell will be executed.
