### ISSUE TITLE
multiple disconnected dialogs

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3040]
if you remain disconnected, then multiple disconnected dialogs keep getting opened and they stack up so you have to dismiss many of them to get back to the notebook.

**Comment by scottdraves** [comment]
this is still a problem.

**Comment by sshkalikov** [comment]
steps:
1. open notebook, wait until it loads
2. click on beaker logo
3. open another notebook it the same tab
4. repeat 2,3 as many times as you want
5. kill beaker app
