### ISSUE TITLE
cell width minimum too large

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3042]
if you narrow your browser window on the publication server, the cells have a minimum width
and so the language badge and show/hide toggle controls are truncated.  text content is also
truncated.

<img width="845" alt="screen shot 2015-12-06 at 1 34 38 pm" src="https://cloud.githubusercontent.com/assets/963093/11614893/a642525a-9c1e-11e5-981d-ef1dcfe6f137.png">

**Comment by ildipo** [comment]
deploying
