### ISSUE TITLE
Time series autotranslation bug

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3044]
https://pub.beakernotebook.com/#/publications/5664a5f8-80d8-4091-89f8-df63b16f3df0

**Comment by maxyeg** [comment]
![pnd](https://cloud.githubusercontent.com/assets/2286032/11629178/a441d1e4-9d07-11e5-9f23-09115546f184.png)

Here is what I see.
What should be the result like?

**Comment by scottdraves** [comment]
here's a clearer explanation:
https://pub.beakernotebook.com/#/publications/56666486-57fe-4411-9e55-4b1a1efd7f60

**Comment by scottdraves** [comment]
i get different results depending on what order i run the cells in, sometimes Python3->IPython works, sometimes i get the [object object], for R somtimes I get an error and somtimes I get an object object.

**Comment by maxyeg** [comment]
It still the same for me with the new notebook.[object object]
