### ISSUE TITLE
Integrate with Big Data Processing Systems

### ISSUE THREAD

**Issue by sirinath** [twosigma/beakerx#305]
Provide direct integration to:
https://mahout.apache.org/
http://www.elasticsearch.org/
http://www.flexsearch.net/
http://0xdata.com/
http://spark.apache.org/
http://stratosphere.eu/

**Comment by scottdraves** [comment]
Access to these systems is already on our agenda, thank you for the suggestion.

**Comment by sirinath** [comment]
OK. Great.
