### ISSUE TITLE
plot date range incorrect

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3052]
https://pub.beakernotebook.com/#/publications/566627d4-7558-49dd-9432-a561d5c05d6a

**Comment by kpaharelau** [comment]
I did not find javascript in the https://pub.beakernotebook.com/#/publications/566627d4-7558-49dd-9432-a561d5c05d6a.  But after analysing I think problem doesn't exist
![image](https://cloud.githubusercontent.com/assets/13516511/11653448/607a792c-9daf-11e5-98d3-a0b1ded886fc.png)

See on screenshot.  Date range is correct. But on the sharing notebook '2007' must be 2004 Dec 31, 23:59:59 000.  Problem only in the date formatting. I changed format (only for a test) and we can see

![image](https://cloud.githubusercontent.com/assets/13516511/11653547/fd7f75c4-9daf-11e5-88b8-b40ab7887961.png)
