### ISSUE TITLE
Racket / Redex and Derived Language Support

### ISSUE THREAD

**Issue by sirinath** [twosigma/beakerx#306]
Hi,

Racket / Redex Support would be really awesome as you can define other languages within Racket / Redex.

Suminda 

http://redex.racket-lang.org/
http://racket-lang.org/

**Comment by scottdraves** [comment]
hi Suminda, we dont need a new issue for every language. If you could consolidate yiur ideas on a wiki page i would appreciate it. thanks.

**Comment by sirinath** [comment]
OK.
