### ISSUE TITLE
Issues using read.csv in R

### ISSUE THREAD

**Issue by jsbachsonata** [twosigma/beakerx#3062]
Hi Scott/Beaker development team,

I have had some issues running R's read.csv on big text files that take less than a second to run in R 3.2 GUI itself. 

R used in Beaker: 3.2.1
Latest Rserve installed
Beaker: latest release 1.4.2

code:
all_comments<-read.csv("all_comments_20151208.csv")

The above code is producing two outcomes inconsistently:

1) I see the elapsed message and the time counter never ends. I then have to force quit beaker in order to run anything in R again.
2) I get the error ...R language backend failed.

Could you provide an email address so I can send this file over to you securely?

**Comment by scottdraves** [comment]
the result is too big to display as a table.
just terminate the cell with a small result like "0".

**Comment by jsbachsonata** [comment]
Using this i now consistently get R language backend failed:

all_comments<-read.csv("all_comments_20151208.csv")
0

2015-12-08 12:56 GMT-05:00 Scott Draves notifications@github.com:

**Comment by scottdraves** [comment]
ok please email the file to me so i can try to reproduce.
address is on my profile.

**Comment by scottdraves** [comment]
worked fine for me if i put the 0 after it.
can you please publish the notebook with the "R language backend failed" error in it, and link to it here?
or just save it and email it to me also.

**Comment by jsbachsonata** [comment]
Hmmm.. strange.

Here you go:

2015-12-08 13:58 GMT-05:00 Scott Draves notifications@github.com:

**Comment by scottdraves** [comment]
i don't believe you can email attachments to a github issue, if that's what you just tried to do.

**Comment by jsbachsonata** [comment]
Hi Scott,

I reinstalled Rserve with the latest version and it worked with the code you suggested. All set. Thanks for the help!

**Comment by scottdraves** [comment]
xlnt thank you for your report.
