### ISSUE TITLE
Can't cancel an R job

### ISSUE THREAD

**Issue by jsbachsonata** [twosigma/beakerx#3063]
Hi there,

When an R job starts runnning, I am unable to cancel the job by pressing the cancel button next to the elapsed time counter. It says "canceling" but never does so.

**Comment by scottdraves** [comment]
what are your OS and browser versions?

**Comment by jsbachsonata** [comment]
Windows 7 and Google Chrome

2015-12-08 12:56 GMT-05:00 Scott Draves notifications@github.com:

**Comment by scottdraves** [comment]
i was just thinking about this.  it's an old problem: https://github.com/twosigma/beaker-notebook/issues/542
will review, thanks for the reminder.

**Comment by jsbachsonata** [comment]
Thanks Scott!

2015-12-08 13:01 GMT-05:00 Scott Draves notifications@github.com:

**Comment by scottdraves** [comment]
this is just a dup now
