### ISSUE TITLE
R dataframe autotranslation breaks on control-character in string

### ISSUE THREAD

**Issue by jsbachsonata** [twosigma/beakerx#3065]
Hi Scott,

Now that cell A is runnign fine, I tried to set my all_comments dataframe as a beaker object "test" in cell B but the time elapsed counter keeps on going indefinitely when I run cell B. Is there something wrong with my autotransalation code or is this a bug?

cell A:
all_comments<-read.csv("\all_comments_20151208.csv")
0

cell B:
beaker::set('test',all_comments)
0

**Comment by jsbachsonata** [comment]
keep me posted on the timeline for the fix. I'm looking to give a presentation on Beaker with my analytics group at Boston Consulting Group since we often go between R, Python, and Spark.It'll def be a useful tool for us once we can create R beaker objects reliably :)

**Comment by scottdraves** [comment]
thanks, i am pretty sure this is a dup of https://github.com/twosigma/beaker-notebook/issues/2799
please watch it there.

**Comment by scottdraves** [comment]
actually there's an additional problem here.  it is really really slow, which is the bug mentioned.
but there is also another bug, because after about 15 minutes the autotranslation of this dataframe does finish, but with an error.  it says

```
Error
 Error : Server Error
```

in the cell and I get the following stack trace from java:

```
org.codehaus.jackson.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 3)): has to be escaped using backslash to be included in string value
 at [Source: java.io.StringReader@6ab4fc74; line: 1, column: 2877113]
```

**Comment by scottdraves** [comment]
which you can easily reproduce with

```
beaker::set('test','\003')
```
