### ISSUE TITLE
Support for More Languages

### ISSUE THREAD

**Issue by sirinath** [twosigma/beakerx#307]
It would be great if you can support additional languages which have IPython back ends.

Some of the major languages worthwhile supporting are:
- Kotlin
- Clojure
- Racket / Redex
- Haskell
- OCaml
- F#
- etc

Also it might be worthwhile exploring how to generate backends automatically for languages targeting the JVM, CLI and LLVM IR. This would help support many more languages without explicitly having to write the back end.

This consolidates:
https://github.com/twosigma/beaker-notebook/issues/306
https://github.com/twosigma/beaker-notebook/issues/304
https://github.com/twosigma/beaker-notebook/issues/303
https://github.com/twosigma/beaker-notebook/issues/302
https://github.com/twosigma/beaker-notebook/issues/300
https://github.com/twosigma/beaker-notebook/issues/299
https://github.com/twosigma/beaker-notebook/issues/280

**Comment by scottdraves** [comment]
These are good targets for 3rd party code contributions.
We would be really happy to receive pull requests that implement plugins for these (and other) languages.

**Comment by sirinath** [comment]
What about this suggestion. (Then for many languages there will be no need for code contribution.)

"Also it might be worthwhile exploring how to generate backends automatically for languages targeting the JVM, CLI and LLVM IR. This would help support many more languages without explicitly having to write the back end."
