### ISSUE TITLE
Deprecated directives from Angular UI

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#3071]
We seem to be using deprecated directives in Angular UI. Did we upgrade Angular UI recently?

In any case, we should switch to the new directives:

![screen shot 2015-12-09 at 8 55 05 am](https://cloud.githubusercontent.com/assets/3384784/11687127/c996b242-9e52-11e5-9e17-ea0a5ada078d.png)

**Comment by maxyeg** [comment]
Right. We upgraded in https://github.com/twosigma/beaker-notebook/pull/3013
Issue about warnings already exists: https://github.com/twosigma/beaker-notebook/issues/3064

**Comment by tomca32** [comment]
OK thanks, I missed that...closing this since it's a duplicate.
