### ISSUE TITLE
No theme selected by default

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#3081]
When opening beaker in a new tab and creating a new notebook, no theme is selected:
![screen shot 2015-12-10 at 11 14 21 am](https://cloud.githubusercontent.com/assets/3384784/11720861/3385a992-9f2f-11e5-8345-b6177f3d1c83.png)

This causes CodeMirror to not highlight the syntax anymore:

![screen shot 2015-12-10 at 11 09 17 am](https://cloud.githubusercontent.com/assets/3384784/11720708/7c5a3f30-9f2e-11e5-985f-6ade3b70074e.png)

For reference, this is what it highlighting used to look like:
![screen shot 2015-12-10 at 11 10 10 am](https://cloud.githubusercontent.com/assets/3384784/11720751/a65ed732-9f2e-11e5-8b4f-8a9d584bb319.png)

Introduced in this commit: 947ab80dbe53178c83368443fc6748a97cafb490

Reproduction:
1. Open Beaker control panel in a new tab (default page)
2. Click New Empty Notebook
3. Neither theme is selected and syntax highlighting doesn't work

**Comment by scottdraves** [comment]
if theme is not set, or is set to an illegal value, then revert to default theme.
