### ISSUE TITLE
add small run button to sections

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3083]
just to the left of the trashcan, add a small run button like on code cells.
for sections, this would "run all cells" (put that in the tooltip), just like the menu item.

![screen shot 2015-12-10 at 11 42 11 am](https://cloud.githubusercontent.com/assets/963093/11721695/184560ba-9f33-11e5-8d46-a82baf8c74da.png)

**Comment by alice-kroch** [comment]
and by the way - why do we have 'run cell' button in markdown cells? it even has no click action

**Comment by scottdraves** [comment]
running a markdown cell just leaves edit mode and formats it for display.
there are other ways to do this but it is more consistent to have a run button.
