### ISSUE TITLE
After collapsing all sections and sharing on server results in no code displayed in shared notebook

### ISSUE THREAD

**Issue by jsbachsonata** [twosigma/beakerx#3098]
Hi Scott,

It looks like when i collapse all the sections of my notebook and then share to server, the shared notebook no longer contains code in the cells once I expand sections in the shared notebook. This seems language agnostic since my python and R code disappeared consistently.

**Comment by scottdraves** [comment]
can't reproduce can you link me to the publication URL (by private email if you prefer)

**Comment by scottdraves** [comment]
thanks for your feedback.
sharing server is deprecated in favor of the publication server.
