### ISSUE TITLE
README.md for TreeMap

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3122]
https://github.com/twosigma/beaker-notebook/tree/master/plugin/jvm/src/main/java/net/sf/jtreemap/swing
where did this code come from, where is the original license?
are there any changes to it from when it was injested?

**Comment by scottdraves** [comment]
For example I am confused because I see the latest source:
http://sourceforge.net/p/jtreemap/code/HEAD/tree/trunk/JTreeMap/src/main/java/net/sf/jtreemap/swing/TreeMapNode.java#l183

```
public List<TreeMapNode> getChildren()
```

but in our tree I see

```
public Vector<TreeMapNode> getChildren()
```

**Comment by kpaharelau** [comment]
I see that you are using newer version of JTreeMap
![image](https://cloud.githubusercontent.com/assets/13516511/11835140/5c167040-a3e3-11e5-8573-ab52f0a930d1.png)
