### ISSUE TITLE
Custom event binding needs to unbind to prevent detachedDOM nodes

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#313]
For instance these two methods are never unbound on `$destroy` thus causing a large memory leak across the lifespan of the application.

The solution for this is to listen for `$destroy` and remove the listener, thus enabling the DOM node to be GCed.

https://github.com/twosigma/beaker-notebook/blob/1e95a231ee1da6b84c95fbd2c0672c565d1954f4/core/src/main/web/app/mainapp/components/notebook/cell-directive.js#L152

https://github.com/twosigma/beaker-notebook/blob/1e95a231ee1da6b84c95fbd2c0672c565d1954f4/core/src/main/web/app/mainapp/components/notebook/cell-directive.js#L162

**Comment by melmac48** [comment]
@anglee was this fixed as part of your mem leak sweep?

**Comment by anglee** [comment]
This should have been resolved with other memory leak in https://github.com/twosigma/beaker-notebook/pull/400

**Comment by samccone** [comment]
:+1:
