### ISSUE TITLE
Language manager throws error in the console

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#3132]
![screen shot 2015-12-15 at 9 07 56 am](https://cloud.githubusercontent.com/assets/3384784/11812700/60decee8-a30b-11e5-9a9a-ee0dcc92b4be.png)

Steps to reproduce:
1. Go to beaker control panel
2. Click New Default Notebook
3. Open developer tools console
4. Click Notebook -> Language Manager dropdown menu

**Comment by tomca32** [comment]
For some reason it doesn't happen in the empty notebook

**Comment by tomca32** [comment]
It seems to happen only when you include IPython.
Try this:
1. Open an empty notebook.
2. Open Language manager. (no error in console)
3. Start R (no error in console)
4. Start Groovy (no error in console)
5. Start IPython (error)

**Comment by maxyeg** [comment]
Looks like it reveals after we upgraded angular from 1.2.x (https://github.com/twosigma/beaker-notebook/pull/2844).
I've built version before this commit and it didn't have that bug.

There are reported bugs with similar stacktrace:
https://github.com/angular/angular.js/issues/12004
http://stackoverflow.com/questions/30578722/typeerror-illegal-invocation-when-trying-to-upgrade-from-v1-2

I will keep searching.

**Comment by tomca32** [comment]
removing refreshRootScope will not fix this. The error will get thrown on the next digest loop anyway.

Problem is that there is some code in ipython.js that does something "weird" that shouldn't be allowed. For example $watching a DOM node - we're not doing this but that's the example that also causes illegal invocation.

**Comment by tomca32** [comment]
This line is the cause: https://github.com/twosigma/beaker-notebook/blob/b3c6931e401a4da4de0a0d473dd4cd0ce288638c/core/src/main/web/app/mainapp/components/pluginmanager/pluginmanager-directive.js#L212

Angular has a method for this: [$watchCollection](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watchCollection)

OK, now why is this happening? 
In the current implementation we are doing a deep watch of a collection. This is very expensive and the collections that we are comparing lead back to native WebSocket objects.

The way angular does comparison is to first copy the objects. Now some objects don't react well to be copied, especially those that have methods inside it - bonus points for bound methods or properties with getters/setters (like WebSocket).

Here's how you can reproduce what's happening:
1. open beaker
2. open dev tools console
3. type: 

``` javascript
a = new Websocket('ws://localhost'); //ignore the error
b = angular.copy(a);
b.url; // There's our error
b; //bonus - inspect b and click the three dots in the parens (...)

```
