### ISSUE TITLE
ipython plugin broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#315]
Failed to load resource: the server responded with a status of 403 (Forbidden) http://127.0.0.1:8801/ipython.159557365705/api/sessions/

**Comment by scottdraves** [comment]
the problem was switching from python to ipython for password hashing:
https://github.com/twosigma/beaker-notebook/commit/749583135e52e410c6732f0e915df52531313e02
so this has been reverted.

however, i made this change because for ang python does not have access to the hashing lib.
i think the reason is because during anaconda install it gives you the option of putting it on the path.
i said yes and ang said no.  as a result i have the following in my .bash_profile:

```
# added by Anaconda 1.6.1 installer
export PATH="//anaconda/bin:$PATH"
```

and that means i get the version of python that works.  so it sounds like we need to change our dependency instructions to include this path change.  @anglee  can you confirm that this change fixes the plugin for you?

**Comment by scottdraves** [comment]
btw, i find it extremely disturbing that ipython and python give different results for the hash function.

**Comment by anglee** [comment]
Yes, I confirm that moving the path of anaconda/bin to the beginning of PATH fixed it for me.

**Comment by scottdraves** [comment]
great then we just have to make our install doc clear.
i need a virgin machine to review them.

**Comment by scottdraves** [comment]
I added some clarification to our mac instructions to be sure users get this right.
