### ISSUE TITLE
ambiance bugs

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#3152]
In the About window, the Close text is far too dark and has some weird background.

On mouseover the background gets weirder in blue color.

![screen shot 2015-12-16 at 2 14 57 pm](https://cloud.githubusercontent.com/assets/3384784/11851208/79ef206e-a3ff-11e5-9506-190d2e7f519d.png)

![screen shot 2015-12-16 at 2 17 45 pm](https://cloud.githubusercontent.com/assets/3384784/11851276/cd78f840-a3ff-11e5-9385-45d99372d6fd.png)

**Comment by scottdraves** [comment]
python widgets need to be themed.
and the text came out black here, why?
<img width="562" alt="screen shot 2015-12-23 at 1 08 52 am" src="https://cloud.githubusercontent.com/assets/963093/11971874/ff0b7312-a911-11e5-8f8e-c1e9edce3c36.png">
