### ISSUE TITLE
new plotitems

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3155]
ConstantBand
ConstantLine

**Comment by scottdraves** [comment]
```
def p = new Plot ()
p << new Line(y:[-1, 1])
p << new ConstantLine(x:0.5, style:StrokeType.DOT, color:Color.blue)
p << new ConstantLine(y:0, style:StrokeType.DOT)
p << new ConstantLine(x: 0.3, y:0.4, color:Color.magenta, width:5)
```

**Comment by altavir** [comment]
As far as I remember, you do not have a function plotitem. Like `new FunctionPlot(Closure function)`. It also would be good an additional utility constructor `FunctionPlot(Closure function, lower, upper, numpoints)` to limit number of calculated points to avoid large number of function calculations in case the function is hard to calculate (numerical integral for example).

**Comment by scottdraves** [comment]
true we don't have that, but plotitems are graphical elements, which are at a lower levels of abstraction than that.
FunctionPlot is something a user could build on top of our library.
