### ISSUE TITLE
how are featured notebooks sorted?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3165]
seems to be by post-time?  should be by average rating.

why is "Ratings" field always blank?
why is "Average Rating" all gray?

bonus: admin able to set "average rating" to any value.

<img width="864" alt="screen shot 2015-12-18 at 11 31 07 pm" src="https://cloud.githubusercontent.com/assets/963093/11911297/94d24dde-a5df-11e5-9e28-a6bc359f95f9.png">

**Comment by ildipo** [comment]
deploying
