### ISSUE TITLE
still disconnecting?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3172]
i left groovy running the charting tutorial overnight and got:
`beakerVendor.js:101419 Uncaught TypeError: Cannot read property 'close' of null`
which refers to

```
if (close)
        {
            _webSocket.close(1000, 'Disconnect');
        }
```

**Comment by tomca32** [comment]
Interesting. Did the disconnect message pop up?

**Comment by scottdraves** [comment]
yes it did.

**Comment by scottdraves** [comment]
could not reproduce on another laptop.
