### ISSUE TITLE
tutorial d3.js example broken?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#318]
when i get to evaluating the JS cell, it produces an [Object object] but nothing happens.

**Comment by melmac48** [comment]
Ang, have you had a chance to look into this yet?

**Comment by anglee** [comment]
I talked to @scottdraves . Both of us couldn't reproduce this now.

I suspect when this happened, it could came from an known issue of old version of pandas causing IPython evaluator returning html instead of a table.

**Comment by scottdraves** [comment]
i can reproduce it on my ubuntu box at home, but not on my mac here.
haven't yet tried ubuntu in a vm here.

**Comment by scottdraves** [comment]
i am not able to reproduce this with ubuntu 14.04 and a fresh build.

**Comment by scottdraves** [comment]
![screenshot from 2014-06-14 21 15 40](https://cloud.githubusercontent.com/assets/963093/3279913/debea752-f42a-11e3-8c30-0877521638bd.png)

so this is what i get with python-pandas version 0.7.0-1

**Comment by scottdraves** [comment]
even with a total update of all packages on this machine, the bug persists.
this is ubuntu 12.04 -- indeed more recent versions of ubuntu have more recent versions of pandas.
eg 13.04 has 0.10.1 http://packages.ubuntu.com/raring/python-pandas
and 14.04 has 0.13.1 http://packages.ubuntu.com/trusty/python-pandas

i am going to close as we don't need to support old versions of pandas.

**Comment by scottdraves** [comment]
looks like there's a workaround available too:
http://askubuntu.com/questions/70883/how-do-i-install-python-pandas
use anaconda to get more recent versions
