### ISSUE TITLE
ambiance bugs

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3183]
box around legend should be same as cell border color, not bbbbbb.
<img width="251" alt="screen shot 2015-12-23 at 12 35 29 am" src="https://cloud.githubusercontent.com/assets/963093/11971528/7b588568-a90d-11e5-800b-2630a8d0803d.png">

**Comment by scottdraves** [comment]
<img width="251" alt="screen shot 2015-12-23 at 12 35 29 am" src="https://cloud.githubusercontent.com/assets/963093/11971528/7b588568-a90d-11e5-800b-2630a8d0803d.png">

**Comment by scottdraves** [comment]
and easyform scrollbars should have the same dark bkg as the horizontal codemirror scrollbar.
<img width="157" alt="screen shot 2015-12-23 at 12 58 21 am" src="https://cloud.githubusercontent.com/assets/963093/11971776/66ff09ea-a910-11e5-86dc-31e1ec2f4477.png">

and easyform checkboxes and radio buttons should have the dark bkg (until they are selected and then they go blue, keep that).

<img width="213" alt="screen shot 2015-12-23 at 12 59 36 am" src="https://cloud.githubusercontent.com/assets/963093/11971787/930dbdec-a910-11e5-9c4a-1c494cb0e0c2.png">

**Comment by scottdraves** [comment]
python widgets need to be themed.
and the text came out black here, why?
<img width="562" alt="screen shot 2015-12-23 at 1 08 52 am" src="https://cloud.githubusercontent.com/assets/963093/11971874/ff0b7312-a911-11e5-8f8e-c1e9edce3c36.png">

**Comment by scottdraves** [comment]
progress reporting bar bkg should be dark gray.
<img width="436" alt="screen shot 2015-12-23 at 1 13 03 am" src="https://cloud.githubusercontent.com/assets/963093/11971898/64b70672-a912-11e5-94fe-8cbf12bfc68a.png">

**Comment by scottdraves** [comment]
tab char should be med-light gray or normally visible.
<img width="172" alt="screen shot 2015-12-23 at 1 15 06 am" src="https://cloud.githubusercontent.com/assets/963093/11971933/c62f9806-a912-11e5-8285-ccdcd770b335.png">

**Comment by scottdraves** [comment]
in OutputContainerCell, GridOutputContainerLayoutManager, lines should be cell border gray.
<img width="168" alt="screen shot 2015-12-23 at 1 28 43 am" src="https://cloud.githubusercontent.com/assets/963093/11972058/a660a8c4-a914-11e5-98ce-13bb1783c1ba.png">

**Comment by scottdraves** [comment]
dataframe UI:   "Show 25 entries" should be std fg text.
The highlighted tab-button "1" in this pic should have dark gray button bkg for its highlight, not white.
And all the text "Previous 1 2 3 4 5 ... 10 Next" should be std fg text.

![screen shot 2015-12-23 at 12 24 39 pm](https://cloud.githubusercontent.com/assets/963093/11981440/91feca08-a970-11e5-9141-88b330661d12.png)

**Comment by scottdraves** [comment]
the little triangles, before they get clicked on, should be about 50% gray.
![screen shot 2015-12-23 at 12 38 56 pm](https://cloud.githubusercontent.com/assets/963093/11981741/51f46118-a973-11e5-8047-35633119e345.png)

**Comment by scottdraves** [comment]
change to std error red

<img width="130" alt="screen shot 2015-12-19 at 12 40 47 am" src="https://cloud.githubusercontent.com/assets/963093/11911613/33366452-a5e9-11e5-8d33-18e9ae461b1d.png">
<img width="283" alt="screen shot 2015-12-19 at 12 40 34 am" src="https://cloud.githubusercontent.com/assets/963093/11911614/33401718-a5e9-11e5-983c-10748676ebc7.png">

**Comment by alice-kroch** [comment]
Select scrollbars style can't be changed with css. We can do that only with the help of jQuery plugins. So should I find something suitable for that?

**Comment by scottdraves** [comment]
please submit the PR for the ones you can do the usual way and explain your idea for the other ones.

**Comment by scottdraves** [comment]
i looked at the branch for this issue.  it's pretty good, but it looks like a few items are not done yet, and the checkboxes and radio buttons look good, but they are broken and do not respond to clicks.

**Comment by scottdraves** [comment]
finishing the scrollbars: https://github.com/twosigma/beaker-notebook/issues/3214
