### ISSUE TITLE
static files are cached

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#320]
This causes problems for users when they get an upgrade and have to clear their browser cache to prevent getting a possibly-inconsistent state.

Developers also sometimes forget to clear their cache, and it would be great o remove this step from our process.

**Comment by scottdraves** [comment]
for unknown reasons, we still have cache problems.

we need to take more extreme measures.

**Comment by melmac48** [comment]
@scottdraves we should add a note to the install page for users who've previously used the beta to refresh their cache.
