### ISSUE TITLE
octave backend

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3208]
we have the basic ingredients:
http://askubuntu.com/questions/194151/how-do-you-install-the-latest-version-of-gnu-octave
https://github.com/Calysto/octave_kernel
http://www.mathworks.com/matlabcentral/fileexchange/33381-jsonlab--a-toolbox-to-encode-decode-json-files-in-matlab-octave
https://www.gnu.org/software/octave/doc/interpreter/URL-Manipulation.html

**Comment by yassinebha** [comment]
That would be awesome. Thanks

**Comment by yassinebha** [comment]
Do you think this will happen soon or not?

**Comment by scottdraves** [comment]
idk, but a pull request sure would help.

**Comment by scottdraves** [comment]
https://anneurai.net/2015/11/12/matlab-based-ipython-notebooks/

**Comment by claramoreau9** [comment]
Yes it could be really nice to have octave. Do you think it will happen one day?

**Comment by scottdraves** [comment]
yes, totally.
