### ISSUE TITLE
geometry in ambiance.scss

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3215]
only colors should go in this file, right?

https://github.com/twosigma/beaker-notebook/blob/8abae4a5863a1a34b6845e8c61ce101a9a16494c/core/src/main/web/app/styles/theme/ambiance.scss#L516

**Comment by tomca32** [comment]
It should be only colors unless we plan to change UI positioning between themes, which I'm pretty sure we don't.
I wonder if this means that we actually move some elements around in this theme or we just duplicated these rules in both theme styles.

I'll investigate and move this somewhere more appropriate.

**Comment by tomca32** [comment]
This is fine. It's part of a hack to style radio buttons and checkboxes. Those elements cannot be styled, so instead the original is hidden and a "fake" radio button is drawn. We need the geometry there and really there is no better place for it currently.

When we introduce another theme, we should move this to a base theme from which other themes inherit (except the default one).
