### ISSUE TITLE
text line arrowhead missing on pub

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3275]
Text example in main plotting tutorial looks like 
![screen shot 2016-01-07 at 3 20 35 pm](https://cloud.githubusercontent.com/assets/963093/12181784/4f5569a8-b552-11e5-812c-cf23cde05483.png)
should be
![screen shot 2016-01-07 at 3 21 04 pm](https://cloud.githubusercontent.com/assets/963093/12181786/54e1293e-b552-11e5-9655-94fa46deece6.png)

**Comment by ildipo** [comment]
Must change the marker url from `/beaker/#Triangle` to `/#Triangle`

**Comment by scottdraves** [comment]
that breaks it in beaker, will find the right way later.
