### ISSUE TITLE
sort the languages

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3277]
it's too hard to find languages in the list, so put them in alphabetical order.

**Comment by scottdraves** [comment]
<img width="575" alt="screen shot 2016-01-07 at 10 33 32 pm" src="https://cloud.githubusercontent.com/assets/963093/12189769/017c4c32-b58f-11e5-8e32-260478174e9f.png">

**Comment by scottdraves** [comment]
this is a regression, maybe from lodash upgrade?

**Comment by maxyeg** [comment]
It was introduced in angular update(from 1.2 to 1.4). They changed `ng-repeat` behavior.
You can see it in angular's repo here: https://github.com/angular/angular.js/commit/c260e7386391877625eda086480de73e8a0ba921#diff-f7b537c61e90325996f3c86b13cd53c4L345

They removed `collectionKeys.sort();`

If we are interested only in how buttons look in dialog we can leave my changes(https://github.com/twosigma/beaker-notebook/commit/e60c1a8ed3f2d1494e7b9dabecbbc9701b46947d)

Another solution will be to sort maps with evaluators definitions:
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/beaker.js#L394
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/plugin/init/addevalplugins.js
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/plugin/init/embeddedBeakerConfig.js#L37

**Comment by tomca32** [comment]
Why can't we just use 'orderby' filter?

```
ng-repeat="(pluginName, pluginStatus) in evalTabOp.getEvaluatorStatuses() | orderBy: 'pluginName'"
```

https://docs.angularjs.org/api/ng/filter/orderBy

**Comment by maxyeg** [comment]
I think `orderBy` filter works with arrays.
Adding just `| orderBy: 'pluginName'` doesn't work. I have to convert object which looks like `{'HTML' : '...', 'Latex' : '...'}` into array.
But keys and values from original object are used within `ng-repeat` loop.

**Comment by maxyeg** [comment]
I see an example of using orderBy with objects here(added intermediate toArray filter): http://stackoverflow.com/questions/26474920/order-by-object-key-in-ng-repeat
What do you think?

**Comment by tomca32** [comment]
Interesting, that does complicate things. Do we need sorting by object key anywhere else in the project? If so then maybe we can implement that filter.

**Comment by tomca32** [comment]
I thought of maybe implementing our own 'orderByKey' filter, should be easy enough but there's no need for it since this is the only place where it would be used.
