### ISSUE TITLE
Language kernels don't re-establish lost websocket connections

### ISSUE THREAD

**Issue by mforsyth** [twosigma/beakerx#328]
This is definitely true of iPython, probably other languages as well.

If the websocket is terminated (like, server closes connection, you go offline for a second), the notebook will be permanently unusable until you refresh the page.

This is only a real issue for cases where Beaker would need to be accessed over the internet, as when accessing beaker over loopback connection, not much could happen that would break the websocket connection.

**Comment by melmac48** [comment]
ui should behave similar to #243

**Comment by scottdraves** [comment]
closed along with #243.
