### ISSUE TITLE
create folder button broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3320]
in the file save dialog, if you click the button to create a folder ("Make new directory") then the app crashes with the following trace:

```
TypeError: Cannot read property 'split' of undefined
    at newStrategy.manualEntry (http://127.0.0.1:8801/abd9c72/beaker/app/dist/beakerApp.js:990:44)
```

which refers to:

```
newStrategy.manualName = this.input.split('/').pop();
```

**Comment by mnavasiolava** [comment]
cannot reproduce. make directory forks fine for me
