### ISSUE TITLE
Cannot Set Up Python 3 & IPython on Windows Machine (please help)

### ISSUE THREAD

**Issue by mmalaguti** [twosigma/beakerx#3323]
All these languanges cannot initialize, getting a "Language Error" message
Heres my beaker.pref.json

{   "languages" : {
    "IPython" : {
      "path" : "C:\Users\[username]\Anaconda3\envs\py27"
    },
    "Python3" : {
      "path" : "C:\Users\[username]\Anaconda3\envs\py3k"
    }
    "R" : {
      "path" : "C:\Program Files\R\R-3.2.3\bin\x64"
    }
}

**Comment by scottdraves** [comment]
you should try beaker v1.5, now in beta, or wait a couple of days and get the final version of it: http://beakernotebook.com/downloads

it fixes some problems starting python on windows.

for R you should not need to put it in your preferences as it should be found via a windows resource that the R installer leaves (how did you install R?)

**Comment by mmalaguti** [comment]
Hi scott, I sent you a video through email of my screen so that you can see exacly what I am seeing. I couldn't find the attachment here, that's why I replied through email. 

Oh btw, I have downloaded the latest version after your comment.

Thanks!

**Comment by dariobig** [comment]
+1

[documentation ](https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences) says to provide path of python and ipython, but on anaconda 3, these two commands are in two different folders: 

![image](https://cloud.githubusercontent.com/assets/4755/17840711/0b4cf162-67c3-11e6-8937-b368b6c2dc1b.png)

I'm running version: 1.6-0-gb7c81a9 and anaconda 3 and here is my config file:

``` json
{
  "autocomplete-parameters" : "true",
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : false,
  "languages" : {
    "IPython" : {
      "path" : "C:\\Anaconda3"
    }
  },
  "edit-mode" : "default",
  "advanced-mode" : true
}
```

**Comment by altavir** [comment]
Python 3 + Python 2 configuration:

```
"languages" : {
      "IPython" : {
          "path" : "C:\\Anaconda3\\envs\\py2\\"
      },
      "Python3" : {
          "path" : "C:\\Anaconda3\\"
      }
  }
```

Anaconda has python 3 installed as default and python 2 installed in `py2` environment.

**Comment by dariobig** [comment]
@altavir I've setup a new env with py2 + ipython-notebook and tried your exact config just to be sure, still doesn't work for me :( 

Which version of anaconda do you have? Do you need extra packages / software? Are you using web or electron interface? Where is your config file located (mine is under C:\Users<username>.beaker\v1\config) ?

**Comment by altavir** [comment]
I am using anaconda 3. Web or electron does not matter since they use the same backend (the only problem with electron that it freezes on non-critical error like already posted in #4364 ). I have anaconda, anaconda scripts and anaconda library bin directories on system path. But I don't think it should matter. I believe that beaker expects that IPython path points to Python 2 environment whereas Python3 points to Python 3. Both of them use IPython console. 
By the way beaker also crashes or freezes if it does not find required Python packages like `pandas`.

**Comment by altavir** [comment]
@bigonazzi The configuration path is default: `C:\Users\<username>\.beaker\v1\config\beaker.pref.json`. I believe that portable version uses different config path since there was a problem with invalid user directory paths.

**Comment by dariobig** [comment]
@altavir I've tried all of the above, including adding scripts folder to my path. Any other idea to try out?

**Comment by altavir** [comment]
Just tried it on another computer with the same configuration. It loads Python 3 kernel and crashes on IPython with message that pandas not installed.
