### ISSUE TITLE
Feature request: printing to cell output from Javascript

### ISSUE THREAD

**Issue by emilydolson** [twosigma/beakerx#333]
As far as I can tell, it isn't currently possible to write to the console from Javascript (typing console.log("test") has no effect. This would be a very useful feature to have.

**Comment by scottdraves** [comment]
Thanks for the suggestion.

console.log in a javascript cell goes to the javascript console in your web browser.
On a mac in chrome, you can open that with command-option-j.

Would you like to be able to log messages to the terminal where you started Beaker?

**Comment by emilydolson** [comment]
Oh, that's great to know! Thanks! I'd find it more convenient to be able to log messages to some sort of in-notebook console (like the way stdout and stderr are displayed from python), but if the browser console will display them it's not too important.

**Comment by scottdraves** [comment]
Sounds like a good idea.  We'll keep it in mind for the roadmap.

**Comment by k-dahl** [comment]
Any progress on this? It would be much more in line typical notebook iterative development scenarios, as the output could then be preserved in the notebook - whereas the developer console in any web browser wouldn't.

**Comment by scottdraves** [comment]
Nothing has happened but we actually have been making some other improvements to our JS experience and I think this would fit right in.

However I am thinking it would be better to keep console.log as it is, and introduce a new function beaker.print() that has this new behavior.
