### ISSUE TITLE
Saving notebook removes letter from page title

### ISSUE THREAD

**Issue by emilydolson** [twosigma/beakerx#334]
I'm running beaker in Chromium on Linux Mint 16. Every time I make a change and then save my notebook, another letter is removed from the page title displayed in the tab and at the top of the browser. After all of the letters are gone, the title becomes the full address (e.g. "http://127.0.0.1:8801/beaker/#/open?uri=file:config%2Ftutorial.bkr"). If I then make another change and save again, the title is replaced with a single asterisk, which remains in place no matter how many subsequent changes and saves I make. Presumably this is a bug in removing the "unsaved changes" asterisk.

**Comment by scottdraves** [comment]
Thanks for the bug report.
This has already been fixed and is in github development builds.
It will be released shortly.
