### ISSUE TITLE
instantiate UI before it reaches the screen

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3354]
when you scroll down the notebook it is distracting that UI is instantiated as it comes into view, and elements jump.  seems like this could be avoided by instantiating sooner, eg anywhere within a few inches away from the bottom of the screen.

**Comment by samccone** [comment]
@tomca32 patches welcome for https://github.com/samccone/scrollin/issues/11

I will also throw together one, it just might be a tiny bit of :clock1:  :+1:

**Comment by tomca32** [comment]
@samccone cool. I'll take a look and send you a PR.

**Comment by tomca32** [comment]
Submitted a PR for this functionality: https://github.com/samccone/scrollin/pull/14

As soon as it's merged and released it will be trivial to fix this in Beaker.
