### ISSUE TITLE
kdb plugin not working on windows

### ISSUE THREAD

**Issue by artaritj** [twosigma/beakerx#3371]
The path for the q binary is wrong for windows
In 
beaker-notebook/plugin/kdb/src/main/java/com/twosigma/beaker/kdb/KdbProcess.java

```
  if (SystemUtils.IS_OS_WINDOWS) {
    binaries.add("q.exe"); --> should be "w32/q.exe"
```

**Comment by scottdraves** [comment]
thanks!  fix will appear with 1.5 next week.
