### ISSUE TITLE
sharing output/input object between different languages

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [twosigma/beakerx#3379]
Is it on your roadmap?
It would be nice to have an ouptut for example from  an R computation which can be accessed with a python syntax seamlessly..

**Comment by tomca32** [comment]
You can use the Beaker object for that. There is a tutorial for that under Feature Overviews in the tutorial notebook.

Tutorial notebook is available from the Help dropdown menu.

**Comment by scottdraves** [comment]
right.  here's an online version of that tutorial:
https://pub.beakernotebook.com/#/publications/560b5680-9a96-4fc1-a7f2-a4916c8de7e3?fullscreen=true

and another with more examples of doing autotranslation:
https://pub.beakernotebook.com/#/publications/560b5722-f287-43a3-b48d-f6ab06befc8f?fullscreen=true

and moving a dataframe between R and Python:
https://pub.beakernotebook.com/#/publications/56648fcc-2e8e-41a6-aa4a-1249ee39023c?fullscreen=true

**Comment by RanaivosonHerimanitra** [comment]
Ah cook.many thanks. Jupyter does not have that yet i think
