### ISSUE TITLE
ESC or clicking away the "File Exists" dialog is broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3395]
it takes that as "Overwrite" instead of "Cancel".
<img width="585" alt="screen shot 2016-01-18 at 2 24 36 pm" src="https://cloud.githubusercontent.com/assets/963093/12400641/54cddbfe-bdef-11e5-9e58-c6a233977cae.png">

**Comment by mnavasiolava** [comment]
@scottdraves i'm looking into this. can't answer you in slack - it doesn't work for me
