### ISSUE TITLE
Initialization and evaluation times

### ISSUE THREAD

**Issue by codingbutstillalive** [twosigma/beakerx#3404]
Dear fellows,

I am used to jupyter notebooks and I am surprised to see that evaluations in beaker take so long. First of all, it takes a minute until some evaluators are initialized. Then, when I run 'hist(rnorm(100))', for example, it takes pretty long until the image is displayed. Why is this the case, and will this be sped up soon?

The thing is. Jupyter runs much more smoothly. I can imagine that the technology level behind beaker is much more advanced, but in practice I would need a tool that runs as smoothly as jupyter.

Best

**Comment by scottdraves** [comment]
thanks for your feedback.
idk, R evaluator takes about 3 seconds to start on my laptop, and hist(rnorm(100)) runs instantly.
what kind of hardware are you on?

**Comment by codingbutstillalive** [comment]
I am running on Ubuntu in a VM on a Dell laptop.

**Comment by scottdraves** [comment]
what CPU does the laptop have?  how are you running the VM?
and how long does hist(rnorm(100)) take in beaker vs jupyter?
in beaker, the cell output menu tells you how long the cell took to run.

**Comment by codingbutstillalive** [comment]
The plotting of the histogram takes 5 seconds. Initializing of the evaluators can take more than a minute.

**Comment by codingbutstillalive** [comment]
The laptop has a core i7 (dual core) with 16gb ram (8 gb reserved to the VM).

**Comment by scottdraves** [comment]
my laptop is also an i7 (from 2013) with 8GB ram, and in an ubuntu vm (i use vmware) it took 6 seconds to start R and that cell runs in 0.1s.  so it seems something is wrong but hard to say what.
