### ISSUE TITLE
upgrade mac xcode project jre ref to 1.8

### ISSUE THREAD

**Issue by dkobylarz** [twosigma/beakerx#3418]
The mac os build instructions
https://github.com/twosigma/beaker-notebook/wiki/Mac-build-and-run
mention jdk1.8 installation whereas the embedded jre version is 1.7:
https://github.com/twosigma/beaker-notebook/blob/master/launcher/mac/README.md
When building the projects with gradle and jdk1.8 all compiled classes are incompatible with 1.7:
(java throws unsupported major.minor version 52.0). Mac version may only be built with jdk 1.7, not to mention it also requires copying jdk tools.jar into target jre. An updated xcode project for jre1.8 would be nice.

PS I tried updating the xcode project jre references by myself but failed miserably. I got lots of "image not found" errors.

**Comment by scottdraves** [comment]
the embedded jre is 1.8 the readme is wrong.

**Comment by dkobylarz** [comment]
I haven't checked 1.5.1 bundle but in 1.5.0 there's still jre1.7.0_60, same in xcode project (master branch)

**Comment by scottdraves** [comment]
you are just being confused by the name of the folder it's in.

**Comment by dkobylarz** [comment]
thanks! that explains everything

**Comment by scottdraves** [comment]
sorry, it is horrible but the plan is to get rid of this launcher asap and replace it with the electron version.

**Comment by hadfield** [comment]
perhaps modify the readme to capture this in the meantime?

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/commit/a36e21ec4405c4fe0ba7f7683efd9571b66c536a

**Comment by hadfield** [comment]
thanks!

**Comment by scottdraves** [comment]
and thank you for the feedback.  i will have a closer look at Dariusz's PR this week, had to get 1.5.1 out.
