### ISSUE TITLE
mac xcode project: lots of missing resources (files)

### ISSUE THREAD

**Issue by dkobylarz** [twosigma/beakerx#3419]
After unzipping the build output into ./launcher/mac/dist and opening the xcode project there's lots of missing file (attached image). Is it normal or something we should be worried about? I imagine this is  a snapshot of the webapp when the xcode project was created.
![beakernotebook_mac_missing_resources](https://cloud.githubusercontent.com/assets/607090/12526321/a3cc109c-c16c-11e5-8a71-49ae37d896c8.png)

**Comment by scottdraves** [comment]
xcode is just used to make the launcher, not for development of the dist directory.

**Comment by dkobylarz** [comment]
thanks!
