### ISSUE TITLE
Need word wrap in markdown mode

### ISSUE THREAD

**Issue by theideasmith** [twosigma/beakerx#3423]
Beaker is awesome. I'm a die hard fan. 

One minor problem I'm having is the lack of word wrap when in markdown edit mode. This prevents me from writing long sentences or paragraphs without adding a newline each time the cursor hits the end of the edit box, which is mighty annoying.

**Comment by scottdraves** [comment]
thanks!  glad you are into it.

i can see your point, thanks for the suggestion.  we'll have to try it and see, but i think you are right it will be an improvement.

probably for code cells too.

**Comment by altavir** [comment]
I agree, it is not crucial, but indeed annoying.

**Comment by theideasmith** [comment]
Thanks. Can I try making the change and submitting a pull request?

**Comment by scottdraves** [comment]
sure, it's just a flag in codemirror.  we would need a CLA to accept a PR (see the readme, it's a standard form).
