### ISSUE TITLE
Scaling of Electron UI

### ISSUE THREAD

**Issue by RhysU** [twosigma/beakerx#3426]
Running the 1.5 Electron build on a 2560x1440 display produces very small fonts.  In the browser, zooming can scale things up to a readable level.  If possible, please permit UI scaling with Electron.

**Comment by scottdraves** [comment]
you are right, i think this used to work, but it's broken now.
thanks for the report.
should be on same cmd key as in browser,
plus in view menu, add items "zoom in", "zoom out", and "actual size".

**Comment by scottdraves** [comment]
so actually the cmd keys  do work, but only on the notebook windows, not on the "start page".

**Comment by scottdraves** [comment]
the cmd keys do not work if you are editing a text or code cell.
