### ISSUE TITLE
Nodejs nodePlugin doesn't work on Windows bin

### ISSUE THREAD

**Issue by bcaller** [twosigma/beakerx#3438]
The variable `bin` is not assigned to the value from the config file. Instead it points to the function `bin(x)`. Therefore the `subprocess.call` does not work.

`subprocess.call([bin, "app/app.js", port, "127.0.0.1"], shell=True)`

https://github.com/twosigma/beaker-notebook/blob/master/plugin/node/src/dist/nodePlugin#L27

**Comment by bcaller** [comment]
More permanent link: https://github.com/twosigma/beaker-notebook/blob/ed8fd62cdb6d2207beb3bbb3f990e14311ece337/plugin/node/src/dist/nodePlugin#L27

**Comment by scottdraves** [comment]
thanks for the report, should not be hard.
