### ISSUE TITLE
tick event missing from GA tracking

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#344]
This tracking event
https://github.com/twosigma/beaker-notebook/blob/cbaad41743d489f14fec5dad9a82fc34954ccba8/core/src/main/web/app/beaker.js#L234

Is lost here
https://github.com/twosigma/beaker-notebook/blob/cbaad41743d489f14fec5dad9a82fc34954ccba8/core/src/main/web/plugin/init/track.js#L41

there needs to be another else clause to handle ticks.

and update the wiki to include it:
https://github.com/twosigma/beaker-notebook/wiki/Analytics

**Comment by scottdraves** [comment]
Note that it should not log the user!

**Comment by anglee** [comment]
The purpose of the tick event was to measure the time user spent in beaker. Using GA, such measurements are available in Google Analytics reports by default:
In the Audience/Overview report, it reports 'Sessions' and 'Avg.Session Duration'
In the Audience/Behavior/Engagement' report, it has session duration breakdown.
For details about how session is calculated see:
https://support.google.com/analytics/answer/1006253?hl=en
https://support.google.com/analytics/answer/2731565?hl=en
Note that we probably want to sent more engagement hit though(by sending events that doesn't has the flag nonInteraction set to true) see:
https://developers.google.com/analytics/devguides/collection/analyticsjs/events

The way we log the heartbeat event with a naive setInterval() is going to include all non-active time (user keep multiple tabs open, leave beaker open over night), and thus not going to be very useful, especially without breaking it down with other dimensions.

I will close this issue for now. We can reopen or log a new issue once we have decided on more action items about how we want to take advantage of using Google Analytics.

**Comment by scottdraves** [comment]
the heartbeat "tick" event is only sent if there was some activity in the notebook.
see how it works with lastAction?
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/beaker.js#L233
that means it does not suffer from leaving beaker open overnight or having multiple tabs open.

otoh i would have to be convinced that GA is getting sessions right given how few page-view events we send as a single-page web app, for example that doc doesn't say that custom events are used, and if they aren't then i would say this task is impossible.  plus, there are some situations, for example if the user spends a long time editing the prose in a notebook, or a user spends a long time reading and interacting with output visualizations (but not evaluating cells), where we do not currently send any events to GA and it could not correctly get a session.  That's the purpose of this event.

**Comment by anglee** [comment]
You are right about the long non-active session. I will add the tick event to GA.
