### ISSUE TITLE
Enabling LaTeX?

### ISSUE THREAD

**Issue by jsermeno** [twosigma/beakerx#3441]
There doesn't seem to be a way to enable LaTeX. The only option is to use TeX through KaTeX. It appears that there used to be LaTeX support?

Separate, but possibly related. What's with the CLA? What sort of open source project requires you to sign a document to contribute?

**Comment by scottdraves** [comment]
Hi Justin, right we support TeX through KaTeX.  That plugin used to be named LaTeX but it never actually supported the LaTeX commands, so it was just misleading, sorry.  What feature of LaTeX are you looking for?

CLAs are standard for many open source projects including all of those run by the [GNU FSF](http://www.gnu.org/licenses/why-assign.en.html) and [google](https://cla.developers.google.com/about/google-individual).

**Comment by jsermeno** [comment]
Ok, I see. I was trying to create an equation that has a single left-hand side, and multiple right-hand sides over multiple lines.

```
\begin{align}
lefthand &= righthand1 \\ &= righthand2
\end{align}
```

I see that an align environment has recently been added to KaTeX. Is this support coming soon? Thanks.

**Comment by scottdraves** [comment]
yes it will be in the next release
https://github.com/twosigma/beaker-notebook/issues/3113
