### ISSUE TITLE
Working, but still see "unable to get IPython hash"

### ISSUE THREAD

**Issue by KnowledgeGarden** [twosigma/beakerx#3446]
I seem to have resolved issues with iPython and R. It runs tutorials, allows to open an empty notebook, and will open a default notebook. Looking at the console, I detected the failure below.
I just returned to the system, re-opened the default notebook, and got the "unable to start IPython" message. The window stayed open, so I typed in some python code in that cell and clicked run. New crash as reported here: https://gist.github.com/KnowledgeGarden/1e6e566e96dc35ddc0eb
which had this message (not shown): ipython-hash-stderr>OSError: [Errno 2] No such file or directory

[qtp687059528-21] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/plugin-s
ervices/IPythonipython-hash-stderr>  File "C:\projects\SolrWatson\BeakerNotebook
APACHE\python\lib\os.py", line 344, in execvp
ipython-hash-stderr>    _execvpe(file, args)
ipython-hash-stderr>  File "C:\projects\SolrWatson\BeakerNotebookAPACHE\python\l
ib\os.py", line 380, in _execvpe
ipython-hash-stderr>    func(fullname, *argrest)
ipython-hash-stderr>OSError: [Errno 2] No such file or directory
java.lang.RuntimeException: unable to get IPython hash
        at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.hashIPythonPas
sword(PluginServiceLocatorRest.java:609)

**Comment by scottdraves** [comment]
did you install anaconda?

**Comment by KnowledgeGarden** [comment]
Anaconda 2 and 3 are now installed. It seems to be working fine! Many thanks!
