### ISSUE TITLE
Strings with double slash ("//"), e.g., URLs, broken in Java language cells

### ISSUE THREAD

**Issue by expz** [twosigma/beakerx#3449]
Strings with a double slash break the Java interpreter. The double slash is apparently interpreted as the beginning of a comment?
### Correct Behavior in Terminal

Open a command line with java. Create `Test.java`:

``` java
public class Test {
  public static void main(String[] argv) {
    String url = "http://www.example.com";
    System.out.println("--- Bug not found ---");
  }
}
```

Then it should run correctly:

```
$ javac Test.java
$ java Test
--- Bug not found ---
```
### Bug in Beaker Notebook

Create a Notebook with Java enabled. Create a Java cell with the code:

``` java
String url = "http://www.example.com";
System.out.println("--- Bug not found ---");
```

Running the cell produces the error:

```
ERROR: java.lang.IllegalStateException: ';' expected
n("--- Bug not found';' expected
 not found ---");}
}unclosed string literal
 found ---");}
}
reached end of file while parsing
 ---");}
}
```

**Comment by expz** [comment]
This will break tons of existing Java code that users would copy and paste, but it has an easy workaround for users just writing a little bit of code for themselves:

``` java
String url = "http:/" + "/www.example.com";
System.out.println(url);
```

**Comment by scottdraves** [comment]
Thanks for the report, we'll get right on it.
