### ISSUE TITLE
Jackson version/classpath mismatch

### ISSUE THREAD

**Issue by harkanJ** [twosigma/beakerx#3450]
When importing jars that depend on more modern versions of Jackson (eg. 2.6.3 for scala 2.11), the version that is bundled with beaker is used rather that the correct Jackson verion.

Is there a way to remove the beaker jackson jar from the classpath of the notebook?

**Comment by scottdraves** [comment]
dealing with the classpath for the language backends is something we have made some progress on but is definitely needs more work.  see eg https://github.com/twosigma/beaker-notebook/issues/2276

if you could be more specific about what you want to use it would be helpful.  thanks.

**Comment by harkanJ** [comment]
Sorry the issue turned out to be a conflict with spark not the notebook itself.   Closing the issue.
