### ISSUE TITLE
no-password option on startup is ignored

### ISSUE THREAD

**Issue by harkanJ** [twosigma/beakerx#3451]
Starting beaker with the no-password option is ignored:

$ ./beaker.command --public-server --no-password
starting nginx instance (....)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to https://XXXXXX:8800/
Submit this password: gkFgEafVcLKgFXC

**Comment by dberansky** [comment]
I'm seeing the same issue.

**Comment by scottdraves** [comment]
sorry the option is not implemented.  maybe someday...
