### ISSUE TITLE
Create Email List for users and developers of Beaker

### ISSUE THREAD

**Issue by hadfield** [twosigma/beakerx#3455]
Create public community email lists for users and/or developers of Beaker on google groups / nabble / or similar.

Creating an issue in github isn't the ideal way to surface this -- which is a nice example of why a mailing list is needed.

If a mailing list exists and I just missed it somehow, please point me to it as well as update the beaker website to reference it.

**Comment by scottdraves** [comment]
hi marc, there is no community email list, just the announcement email list. however the community can post here on github, on facebook, and on twitter, so I'm not convinced we need more places. for example, this github issue seems fine to me.  what do you feel like we are missing?

**Comment by hadfield** [comment]
there is currently no way to communicate with the beaker community at large for user questions or development discussion.

all the same reasons that these exist:
https://zeppelin.incubator.apache.org/community.html
https://groups.google.com/forum/#!forum/jupyter
http://spark.apache.org/community.html
etc.

in particular, user questions for "how do i do X?", "advice regarding Y?", "can't get X to work, help!" do not have a forum, especially in a way that is archived and searchable.

i believe the perceived lack of a community (and community support) is holding back adoption of beaker.

questions like this on StackOverFlow would have a proper channel: http://stackoverflow.com/questions/34769103/how-to-load-node-modules-in-beaker-notebook
and would not go unanswered.

**Comment by scottdraves** [comment]
github issues like this indicate demand:
https://github.com/twosigma/beaker-notebook/issues/3472

**Comment by scottdraves** [comment]
https://groups.google.com/forum/#!forum/beaker-user

**Comment by hadfield** [comment]
great!

**Comment by hadfield** [comment]
to be added as a link on http://beakernotebook.com/community ?

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/commit/7688d3d1ad647cd03466fa6b32b832a9d738ba6d

**Comment by hadfield** [comment]
thanks!
