### ISSUE TITLE
Attempting to run Beaker 1.5 on Windows IE 11 - the site comes up blank, Ver 1 works

### ISSUE THREAD

**Issue by ArthurZ** [twosigma/beakerx#3461]
Downloaded the 1.5 release and attempted to run (on Windows) - the site comes up blank in IE 11 whereas Ver. 1 works.

The command line (shell) interface does not report on errors

starting nginx instance (C:\Beaker\beaker-notebook-1.5.1-0-g6e6bdd3-windows/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

**Comment by tomca32** [comment]
Is this Internet Explorer 11?

**Comment by ArthurZ** [comment]
Yes @tomca32, corrected the abbreviation

**Comment by tomca32** [comment]
Thanks for reporting, I'll check this out.

**Comment by scottdraves** [comment]
We only support Chrome, Firefox, and Safari.

**Comment by altavir** [comment]
Works fine in Edge.

**Comment by ArthurZ** [comment]
@scottdraves it wasn't immediately apparent, but I think makes sense, some folks will get affected though as so many places locked the users out of the other browsers than IE.
