### ISSUE TITLE
nginx temp dirs left behind on linux

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3462]
similar problem as windows.

**Comment by scottdraves** [comment]
verified i still see directories growing with this:
gradle run, control-c, ls -l ~/.beaker/v1

**Comment by kpaharelau** [comment]
It is very strange
See my screencast
https://www.dropbox.com/s/v7gqr1izhqg04p3/nginx.mkv?dl=0

Really. I can not reproduce this problem

I am using Ubuntu 14.04.03

and java version

kpaharelau@kpaharelau:~/dev/2Sigma/beaker-notebook$ java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
