### ISSUE TITLE
Cell side-by-side view

### ISSUE THREAD

**Issue by jsermeno** [twosigma/beakerx#3469]
Loving beaker. It would be great if there was an option to show the input, and output cells side-by-side. Perhaps a per-cell option that appears in the cell menu, or in the cell options window, with an option in the view menu to enable it for all cells. I've noticed that when using beaker, I often make changes to a cell, scroll down to see output, scroll up, and repeat. For example, in RStudio, plots are always available to see. 

I'd be willing to work on this if it sounds good to you guys, or perhaps you have more ideas of your own.

**Comment by scottdraves** [comment]
Thanks for the feedback, glad you are into it.  What kind of screen are you on?
I would be surprised if dividing it like that left the code part wide enough to show much in the way of results.

I do agree with you that more flexible layout, including 2D, would be useful.

Some questions:

what do you do if the input and output are different heights, just taking the max seems like it would waste space.

seems like you would also need a way to adjust the division between input and output.

finally: have you tried advanced mode?  it actually cuts down on the vertical space a lot, maybe that's all that's required for you to avoid scrolling up and down.

**Comment by jsermeno** [comment]
Hm interesting. I'm using a 13" retina screen. Perhaps it's from long adhering to the 80 chars per line guideline in code, but most of my input cells are just a little under 2/3 blank. I admit some of my desire for this type of feature comes from often using split screen mode to code (86 characters fit in each column in split screen mode, with my settings).

**Regarding the questions**:
1. In absolute terms I had imagined that the height would be the max of the two, but that the shorter of the two would scroll. For example, let's say the top of the cell is just visible. You begin to scroll the page downwards. The shorter of the two would stay fixed until you reached the end of the content, then it would start to scroll while you scroll, until it has reached the bottom of the cell. This way, assuming that the output cell is entirely visible within a single screen, the output cell remains entirely visible while you scroll the length of the input cell.
   
   I had thought about making each cell scrollable, but then you would have many scroll contexts, which could confuse people.
2. Good point. If you hover over the divider perhaps you could select it, then drag to adjust the proportion each cell takes up.
3. I have used—and am using—the advanced mode, but I still have the scrolling up and down issue.

**Other options**

_Output window_: What I'm looking for, is a way to speed up the feedback loop between input and output. Let's say we keep cells the way they are now. But, in the view menu there is a "Show output" option. This window pops up in the same way as the stdout/err window. It could be the start of a "developer's console". If you select either "Show output", or "Show stdout/err", this window pops up, with tabs pre-selected based on which option you chose.

This window just shows the output of the most recently executed input cell. The more I think about it, this option sounds better.

In addition, similar to chrome's developer's console, you could change the orientation of the console between horizontal and vertical. I'm thinking that the window would simply overlay the current notebook's content in both orientations.

**Comment by scottdraves** [comment]
i think we are going to try to find a more general way to solve this.
