### ISSUE TITLE
Cannot find Nodejs installation on Windows

### ISSUE THREAD

**Issue by mjs2020** [twosigma/beakerx#3470]
I've installed Beaker on a Windows7 x64 laptop and am having issues getting Beaker to see Node.js.
The node installation path (C:\Program files\node) is in %path%. I've also tried adding it in `~/.beaker/v1/config/beaker.pref.json`:

```
{
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : false,
  "languages" : {
    "node" : {
      "path" : "C:\\Program Files\\nodejs"
    }
  },
  "edit-mode" : "default"
}
```

I've also tried nodejs, Node.js and Node with no success.

Interestingly I had an older portable version (v1.1.2-2) on the same machine which can see node without any extra configuration in the beaker.pref.json file.

**Comment by scottdraves** [comment]
hi francesco, it's just a bug we introduced sorry.
it has been fixed on master and i can tell you how to patch it in when i
get back to a keyboard.

**Comment by scottdraves** [comment]
Here's the first report: https://github.com/twosigma/beaker-notebook/issues/3438

To fix it, find the file nodePlugin and replace it with the fixed version which you can find here:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/node/src/dist/nodePlugin
