### ISSUE TITLE
Leiningen support

### ISSUE THREAD

**Issue by keorn** [twosigma/beakerx#3471]
It would be extremely clunky to use Beaker for Clojure development now, as it is not possible to access namespaces within the current project. [Leiningen](http://leiningen.org/) makes it easy to avoid dealing with classpath and manage dependencies.
Currently [Gorilla Repl](http://gorilla-repl.org/) notebook supports it.

**Comment by scottdraves** [comment]
You definitely can download jars with `lein`, add them to the classpath, and use those libraries.
I agree we could provide more UI for this, and it's on the agenda: https://github.com/twosigma/beaker-notebook/issues/1350
So while I agree it's clunky, I am not aware of what is not possible.  Can you be more specific what you mean about namespaces?

**Comment by keorn** [comment]
I think that UI for Leiningen is definitely unnecessary, it's already very easy to use.
Let's say I have a file `my_code.clj` with my code in `src` directory of my Leiningen project. This file specifies namespace `my-code` . Normally, I could `require` that namespace from any other file within that project, or a Gorilla notebook that is located within that project (Gorilla notebook files are just regular .clj files).
The same is for libraries. Leiningen let's you not deal with moving jars around. The namespaces of libraries you added to your `project.clj` file, become available to `require`, the same way your local namespaces did.
Now, I guess the only way to deal with that would be to have the whole project in one notebook (not in .clj files) and get libraries in the way you mentioned, which is an impassible usability boundary for most people I know working with Clojure.

**Comment by scottdraves** [comment]
how about this:  in the language manager, there's a field where you edit the dependencies field of a project.clj for this notebook (with autocompleting search, like the JS module picker).  the deps are stored in the notebook, and every time you load or reset a shell, it runs lein to download any dependencies, and then you run lein classpath.

we would have to call out to lein either as an executable or via API.

**Comment by keorn** [comment]
That should work. I see that you want to keep the notebook self contained, but it would be nice to sometimes share the `project.clj` file with an existing project (the one in which the notebook file is).

Not sure how the architecture is set up but maybe using an existing [nrepl middleware](https://github.com/clojure-emacs/cider-nrepl) would be easier? There are a lot of nice things which would come with it such as code reloading, stack trace analysis etc.

**Comment by tuddman** [comment]
in the interim for leiningen support to be implemented, I'm using this script to load jar dependencies from a `project.clj` into Beaker:

https://gist.github.com/tuddman/50bc6b048f92a655af7c29a94cb5644f

**Comment by jhemann** [comment]
That gist was helpful for seeing what was expected in the "Class path" field. For what it is worth, I did this as a one-liner on a Mac (no node or JS needed) as:  

`bash> lein classpath | tr ':' '\n' | pbcopy`

and then pasting into the field.

I am not sure what format required libs needed to be entered into the Require field though.
