### ISSUE TITLE
Exception in output container tutorial

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#3480]
Opening the output container tutorial scrolling down to instantiate all the cells causes a following error:

```
ReferenceError: element is not defined
at bko-tabledisplay.js:729
at Scope.$broadcast (angular.js:16311)
at HTMLDivElement.cycle (cyclingoutputcontainerlayout-directive.js:67)
at HTMLDivElement.opt.complete (jquery.js:8506)
at fire (jquery.js:2913)
at Object.self.add [as done] (jquery.js:2959)
at Animation (jquery.js:8032)
```

Also, cycling container (the one at the bottom of the notebook) has broken table output:

![screen shot 2016-02-08 at 11 55 59 am](https://cloud.githubusercontent.com/assets/3384784/12892617/ff8030bc-ce5a-11e5-861f-6ad4e89595be.png)

**Comment by mnavasiolava** [comment]
the error with undefined element was fixed in this PR https://github.com/twosigma/beaker-notebook/pull/3468.
also on this branch i don't see problems with cycling container

**Comment by kpaharelau** [comment]
I agree with Marina/ I retested this issue on the latest master. problem doesn't not occurred

**Comment by tomca32** [comment]
Yup, you're right. This seems to have been fixed. Thank you.
