### ISSUE TITLE
How to delete a cell?

### ISSUE THREAD

**Issue by andtheWings** [twosigma/beakerx#349]
I feel stupid asking this, but how do I delete a cell?

**Comment by melmac48** [comment]
To the right of a cell are a number of brackets, each bracket encompasses hierarchical groupings of cells, click on the bracket that spans the cell you want to delete and a menu will appear. There should be an option to delete the cell in that menu.

It's not the most intuitive at the moment, but we'll be releasing a UI update shortly which will make these types of actions much more clear.

**Comment by andtheWings** [comment]
Thanks!
