### ISSUE TITLE
virtualenv for python2

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3510]
a user reports that on ubuntu, they installed anaconda python3, then created a virtualenv with python2, put the path in prefs.json, and were not able to start IPython.

**Comment by altavir** [comment]
In windows I managed it to work. At least in 1.4. Have not checked in 1.5.

**Comment by kpaharelau** [comment]
I have opinion that user did not create full python2 env. 

I used commands

virtualenv ~/py2k -p python
~/py2k/bin/pip install ipython jinja2 tornado pyzmq pandas jsonschema jupyter
sudo ~/py2k/bin/ipython kernelspec install-self
~/py2k/bin/pip install matplotlib scipy

Also I added to the my prefs

"IPython" : {
      "path" : "/home/kpaharelau/py2k/bin"
    }

And all ok

**Comment by scottdraves** [comment]
thanks but please use a fresh VM and test with anaconda on ubuntu, we don't normally use that so it could be different.

**Comment by kpaharelau** [comment]
All works fine

For a new system:
- execute install-runtime-core-dependencies.sh
- execute

```
sudo apt-get install -y python g++ make
sudo apt-get install -y python-software-properties
sudo apt-get install -y git
sudo add-apt-repository --yes ppa:cwchien/gradle
sudo apt-get update
sudo apt-get install -y gradle-2.4
curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
sudo apt-get install -y nodejs
sudo apt-get install -y clang
sudo add-apt-repository --yes ppa:chris-lea/zeromq
sudo apt-get update
sudo apt-get install -y libzmq3-dbg libzmq3-dev libzmq3
sudo add-apt-repository -y ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install -y ruby2.1 ruby2.1-dev libtool
sudo gem install iruby
sudo gem install sass
iruby register

```
- from https://www.continuum.io/downloads download Anaconda3-4.0.0-Linux-x86_64.sh and execute
  bash  Anaconda3-4.0.0-Linux-x86_64.sh
- execute

`conda create -n py2k python=2.7 anaconda`

`conda install -n py2k ipython jinja2 tornado pyzmq pandas jsonschema jupyter matplotlib scipy`

(all must be installed by previous command)

`sudo /home/{username}/anaconda3/envs/py2k/bin/ipython kernelspec install-self`
- add to pref file

```
 "languages" : {
    "IPython" : {
        "path" : "/home/osboxes/anaconda3/envs/py2k/bin"
    }
  }
```

**Comment by cgivre** [comment]
It works!  Thanks for your help!

**Comment by scottdraves** [comment]
awesome
