### ISSUE TITLE
vim mode cursor width in text cell

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3518]
our text cells use proportional fonts, but the cursor is fixed width, for a space.
a space is narrower than most of the letters and the result looks bad.
ideally the cursor should change size based on what it's over.
if that's too hard, then just make it an "n" width.

https://github.com/codemirror/CodeMirror/issues/3256

**Comment by scottdraves** [comment]
![screen shot 2016-02-11 at 10 27 33 am](https://cloud.githubusercontent.com/assets/963093/12980490/9e326058-d0aa-11e5-9248-4422e31b67fe.png)

**Comment by tomca32** [comment]
I believe this was fixed and can be closed

**Comment by scottdraves** [comment]
text cells only, not code.
