### ISSUE TITLE
I'd like globals in each cell to be automatically global in all cells

### ISSUE THREAD

**Issue by csells** [twosigma/beakerx#3527]
The beaker object as a universal hub for objects in all languages is PFM, but I find that I'm mostly using a single language and it quickly becomes tiresome to type "beaker." for access to all objects shared between cells, including cells of the same language (I primarily work in JS and HTML). I'd really love it if objects declare in global scope in each cell become global to the notebook and for each cell's scope resolution algorithm to include Beaker globals. That would make Beaker a joy to use.

**Comment by scottdraves** [comment]
thanks. agreed https://github.com/twosigma/beaker-notebook/issues/797
unclear how to fix though maybe ES6 will help.

**Comment by scottdraves** [comment]
@tomca32 got any ideas?

**Comment by tomca32** [comment]
I will take a look at the JS evaluator to see what's possible.

**Comment by csells** [comment]
I'd love this to work for other languages, too, but this one change made Beaker + HTML + JavaScript a joy!

**Comment by scottdraves** [comment]
not sure what you mean, afaik the only language that had a problem sharing a regular variable between cells was JS.  Here are some examples: https://pub.beakernotebook.com/#/publications/56c7c197-f2b8-4233-bb6f-b6c0c1463d45

**Comment by csells** [comment]
I didn’t know that. Every better!

On Feb 19, 2016, at 5:28 PM, Scott Draves <notifications@github.com<mailto:notifications@github.com>> wrote:

not sure what you mean, afaik the only language that had a problem sharing a regular variable between cells was JS. Here are some examples: https://pub.beakernotebook.com/#/publications/56c7c197-f2b8-4233-bb6f-b6c0c1463d45
