### ISSUE TITLE
Elapsed timer will not end

### ISSUE THREAD

**Issue by planyon** [twosigma/beakerx#354]
I ran a Python cell that never finished executing and the elapsed timer has just continued to count up, it's been going for 20 hours now.

I have attempted to interrupt the process but it has not worked. Interrupting other cells within the notebook works.

I can re-run the cell and receive the results I expect, but once I refresh the notebook the timer returns and continues counting.

![screen shot 2014-06-24 at 2 41 03 pm](https://cloud.githubusercontent.com/assets/5454235/3375884/230f987a-fbcf-11e3-8eae-f4a807b321f2.png)

**Comment by melmac48** [comment]
fixed. @planyon  if you see this behavior with v1.0 please reopen
