### ISSUE TITLE
R Error 

### ISSUE THREAD

**Issue by kartikdesikan** [twosigma/beakerx#3553]
I am facing the following issue while trying out R language on beaker. I am using Windows 8.1 Pro , 64-bit system. I had installed R earlier 3.2.0 version.
Edit: Beaker version is **beaker-notebook-1.5.1-0-g6e6bdd3-windows**
I am able to launch Beaker and use Python without any difficulty.
Following is stderr output
`stderr:
Feb 19, 2016 11:58:25 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused: connect
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:431)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:469)`

I have installed all R packages as mentioned in http://beakernotebook.com/getting-started?windows&scroll, using Base R and not Rstudio.

I also tried modifying beaker.pref.json to see if that worked as follows:
`{
  "pref-format": "1"
    "languages" : {
    "R" : {
      "path" : "C:/Program Files/R/R-3.2.0/bin"
    }
  }
}
`

Please suggest what I could to make R work in beaker

**Comment by scottdraves** [comment]
you don't need the beaker.pref.json thing, this is a missing R package, see https://github.com/twosigma/beaker-notebook/issues/3422
install roxygen2.

**Comment by kartikdesikan** [comment]
I had installed all the packages (incl. roxygen2)
On further troubleshooting I discovered that all newly installed packages go to a different folder called win-library (where it has perms to write), and NOT C:/Program Files/R/R-3.2.0/library.
Perhaps this is the cause of the issue?

**Comment by scottdraves** [comment]
yea looks like something is funny about your R, maybe uninstall and reinstall?

**Comment by scottdraves** [comment]
so, does anyone know about where R installs packages?

long term, beaker should be able to install automatically: https://github.com/twosigma/beaker-notebook/issues/1350

**Comment by kartikdesikan** [comment]
Uninstalling & re-installing (R 3.2.3) worked for me.
Thanks very much for the help!
