### ISSUE TITLE
IRuby installation problem on the OS X El Capitan (10.11)

### ISSUE THREAD

**Issue by kpaharelau** [twosigma/beakerx#3555]
I set up my laptop according https://github.com/twosigma/beaker-notebook/wiki/Mac-build-and-run and got error for command 'sudo gem install iruby' 

ERROR:  Error installing iruby:
    iruby requires Ruby version >= 2.1.0.

bash-3.2$ ruby -v
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

**Comment by kpaharelau** [comment]
I have update https://github.com/twosigma/beaker-notebook/wiki/Mac-build-and-run
see section 'Ruby'

**Comment by scottdraves** [comment]
thanks for updating the doc, that looks fine.

users may need this too.
