### ISSUE TITLE
Significant memory issues 

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#356]
Leaving beaker up and running for an extended period of time starts to peg out my CPU.

![](http://dl.dropbox.com/u/36928599/Screenshots/0dp.png)

**Comment by samccone** [comment]
This screenshot shows constant reflows through the lifespan of an open notebook.

![](http://dl.dropbox.com/u/36928599/Screenshots/0eo.png)

**Comment by scottdraves** [comment]
Could not reproduce this with the default notebook.

Can you try with that and see if it happens then too and if not, then attach the offending notebook.

**Comment by samccone** [comment]
I have tested this on the master branch with the default notebook with no changes from me.

![](http://dl.dropbox.com/u/36928599/Screenshots/0ep.png)

The reflows are gone however it still looks like we are slamming composite layers, which still results in a significant memory / CPU hit after several minutes.

**Comment by scottdraves** [comment]
major memory leaks were fixed
