### ISSUE TITLE
pub admin: featuring error

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3564]
i clicked "edit" on a notebook, checked the feature box, and clicked update.
got an error:
<img width="415" alt="screen shot 2016-02-21 at 4 11 15 pm" src="https://cloud.githubusercontent.com/assets/963093/13205433/f69f434c-d8b5-11e5-8ac0-573ecb38eb35.png">

**Comment by scottdraves** [comment]
PUT https://pub.beakernotebook.com/notebook/v1/publications/56b4eb93-c2c3-4487-b975-0d10b3fd3cad 500 (Server Error)(anonymous function) @ beakerVendor.js:50778sendReq @ beakerVendor.js:50571serverRequest @ beakerVendor.js:50278processQueue @ beakerVendor.js:54801(anonymous function) @ beakerVendor.js:54817Scope.$eval @ beakerVendor.js:56045Scope.$digest @ beakerVendor.js:55856Scope.$apply @ beakerVendor.js:56153(anonymous function) @ beakerVendor.js:63610jQuery.event.dispatch @ beakerVendor.js:18058$event.dispatch @ beakerVendor.js:104594elemData.handle @ beakerVendor.js:17742

**Comment by ildipo** [comment]
outdated issue - now the db is properly clean
