### ISSUE TITLE
Should we check in node_modules?

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#3565]
We've had some problems with npm install randomly failing and it's quite annoying so I'm thinking about checking in all of our npm dependencies. I kind of like that idea but I'm not 100% sure about it.

More technical info about that idea here: http://www.letscodejavascript.com/v3/blog/2014/03/the_npm_debacle

Any thoughts?

**Comment by scottdraves** [comment]
yes this has always bothered me.  but core/node_modules is about 116MB so this is non-trivial.

**Comment by ildipo** [comment]
This has been done before - we used to checkin a zip file with all vendor npm stuff...
I did that and it was working fine.

**Comment by ildipo** [comment]
We could also store it on our AWS space.

**Comment by tomca32** [comment]
The problem is that npm dumps build artifacts in node_modules and those end up taking a lot of space. We can just store the sources in the repository and then do npm rebuild as part of the build script. Details about that are in that link above ^

**Comment by scottdraves** [comment]
before we did it for bower not for npm.

**Comment by scottdraves** [comment]
how big are just the sources?
and can we use npm3 to eliminate duplication and make it smaller?

**Comment by tomca32** [comment]
No idea, I'll check that out.

I don't know what's npm3

**Comment by scottdraves** [comment]
https://docs.npmjs.com/how-npm-works/npm3

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/2780
