### ISSUE TITLE
JS indirect eval breaks tests

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3569]
something has gone wrong with the beaker object, master is failing the test suite with:

```
[firefox #1-2]   autotranslation
[firefox #1-2]     ✗ handles JVM notebook
```

**Comment by tomca32** [comment]
Yeah this happens because now the eval runs in global context and doesn't see the Beaker object.

What's not helping is that we also have a different beaker object, window.beaker, for use by our code. 

I'll see if we can create a clean context for eval

**Comment by scottdraves** [comment]
yea window.beaker should be renamed for sure
https://github.com/twosigma/beaker-notebook/issues/1725

**Comment by tomca32** [comment]
OK, now for one of the hardest problems in CS, what should we rename it to? :)

It seems to deal mostly with registering different components (directive, factory, output display, ...) so: window.beakerRegister I guess.

**Comment by scottdraves** [comment]
sure whatever you want
