### ISSUE TITLE
Improve metrics collecting

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#360]
After the notebook opening refactoring, the 'open' notebook book event shall be revisited to include more metrics about the notebook, e.g. max section level and cell count to guide future UX design. Also, we might consider collecting metrics about which output displays are used the most.

If we do this, we want to make sure http://beakernotebook.com/privacy/ is still good.

**Comment by scottdraves** [comment]
i don't see any issues for the privacy policy, which does not purport to list all data collected.
however i really have to question how much effort we should put into collecting more info versus fixing the many obvious problems we have.

**Comment by anglee** [comment]
Closing this one now. If more need to be done, we can open an new issue.
