### ISSUE TITLE
Beaker Matplotlib Export

### ISSUE THREAD

**Issue by jpryda** [twosigma/beakerx#3601]
Running the example code at http://matplotlib.org/examples/pylab_examples/simple_plot.html, Juptyer successfully exports the image.  When running it from Beaker, the image appears inline but nothing is exported.  Am I doing something wrong?

**Comment by scottdraves** [comment]
thanks for your feedback.  what do you mean exported?

**Comment by jpryda** [comment]
plt.savefig("test.png")  doesn't create the file at all.

**Comment by scottdraves** [comment]
since beaker is a GUI application, the relative path is ending up somewhere unexpected.
use an absolute path, like `plt.savefig("/tmp/test.png")`.

**Comment by jpryda** [comment]
Great, I thought I tried that but it does indeed work. Thanks Scott

**Comment by scottdraves** [comment]
cool glad to hear it.  i think the current working directory should be set to the notebook itself, so this will be more obvious in the future but absolute paths should be fine until then https://github.com/twosigma/beaker-notebook/issues/225
