### ISSUE TITLE
atom editor plugin with beaker-notebook as server

### ISSUE THREAD

**Issue by danpolanco** [twosigma/beakerx#3604]
I love beaker's autotranslation, however, I miss the editing power I have in [Atom](https://atom.io). There is a [Jupyter](https://jupyter.org) plugin for Atom called [Hydrogen](https://atom.io/packages/hydrogen), but - as far as I know - it doesn't have anything like autotranslate.

Any thoughts as to how difficult this would be to create? Or if it's a good idea?

My first thought to talk to a beaker-notebook docker container.

**Comment by scottdraves** [comment]
hey this is a great idea, thanks for the link to hydrogen.
glad you like autotranslation :)

this is doable now but it will be easier after our 2.0 refactor:
https://github.com/twosigma/beaker-notebook/issues/2835
that will simplify the client and allow things like batch execution of notebooks.

the container is a good way to run a beaker server, but i think any way of getting the server running will work for this, it's just another client.

**Comment by danpolanco** [comment]
Nice! Ok. I'm excited.
