### ISSUE TITLE
[SQL]: Not clear how to establish connection via JDBC driver

### ISSUE THREAD

**Issue by pdex777** [twosigma/beakerx#3630]
Hi!

I'm trying to connect to Postgres database via JDBC. The problem I'm facing is that I'm not sure what I need to input in the fields "Default data source" and "Named data sources" at Notebook -> Language Manager -> SQL .

As for the field "Class path (jar files, one per line)", I have a full path to the jdbc driver by postgres, namely to postgresql-9.4.1208.jar. Do I need to have an additional jar file which will setup a connection to the database and publish the driver class to beaker?

I've tried to search this info in the Wiki and FAQs but I couldn't find it. In case I've missed it, I will appreciate if you could point me at the URL with some instructions on how to setup a JDBC connection.

Thanks!

**Comment by scottdraves** [comment]
put the jdbc string in the "default data source"

**Comment by scottdraves** [comment]
did you see the SQL tutorial notebook? it's linked from the main tutorial.

**Comment by scottdraves** [comment]
here's the static published version of it: https://pub.beakernotebook.com/#/publications/560b4a2f-546b-4929-acd7-0d47365b896e?fullscreen=false

**Comment by scottdraves** [comment]
hi @pdex777, did you get this working?

**Comment by pdex777** [comment]
Hi Scott!

Thank you for the helpful hints. I've succeeded in connecting to all databases I'm currently working with, namely, to Oracle, Postgres and Cloudera's Impala. Currently, I have a separate .bkr file for each database vendor, so the next step is to start using all databases from within a single .bkr project. For this, the box "Named data sources" seems helpful, but I'm not sure what exactly one should input there. 

I've seen the trick of using strings like %%beakerDB="jdbc:h2:mem:people" but it seems there is better way which uses "Named data sources". I will appreciate any hints / howtos on that. Thank you!

**Comment by scottdraves** [comment]
Yes, I expanded the SQL tutorial to document using named data sources:
https://pub.beakernotebook.com/#/publications/560b4a2f-546b-4929-acd7-0d47365b896e
