### ISSUE TITLE
table with timezone of GMT+02:00 showing up as -2

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3649]
https://pub.beakernotebook.com/#/publications/56e1a3f3-7040-417a-afd7-d3e1fb8db021

**Comment by scottdraves** [comment]
```
var time = moment(633726000000)
time.tz("GMT+02:00")
time.format("ZZ")
```

produces "-0200" so instead of "+0200" why?

**Comment by maxyeg** [comment]
This sample gives correct result:

`
var time = moment(633726000000)
time.utcOffset("GMT+02:00")
time.format("ZZ")`

http://momentjs.com/docs/#/manipulating/utc-offset/

**Comment by scottdraves** [comment]
cool so if zone starts with "gmt" then call that.
goes for plots too.
need a helper fn.
