### ISSUE TITLE
Table width is broken after redraw

### ISSUE THREAD

**Issue by mnavasiolava** [twosigma/beakerx#3663]
On 2-column table (key/value) try to change e.g. column alignment.
Table gets 100% width

**Comment by scottdraves** [comment]
i cannot reproduce this, can you explain in more detail please?

**Comment by mnavasiolava** [comment]
1. create table

```
 var v = {};
 for(var i=0; i<20; i++){
   v["k" + i] = Math.random();
 }
 v;
```

![image](https://cloud.githubusercontent.com/assets/12935591/13771173/12822504-ea9d-11e5-9392-60e98c68d5a2.png)
1. change 'Key' column alignment
2. table width is changed

![image](https://cloud.githubusercontent.com/assets/12935591/13771153/f0b7852c-ea9c-11e5-80ea-ec8ebd18c13e.png)

**Comment by scottdraves** [comment]
hm still didn't reproduce for me.  @tomca32 can you see it?

**Comment by tomca32** [comment]
No. Can't reproduce

**Comment by tomca32** [comment]
But trying this in ambience theme displayed a new bug: #3690
