### ISSUE TITLE
Notebook: in case if output consists of big data - it should be wrapped to fit the cell size

### ISSUE THREAD

**Issue by aryzhykova** [twosigma/beakerx#3666]
1. log in to app
2. open new java notebook
3. type code 
   int i =0;
        int num =0;
        //Empty String
        String  primeNumbers = "";
   
   ```
    for (i = 1; i <= 10000; i++)         
    {              
       int counter=0;      
       for(num =i; num>=1; num--)
   {
          if(i%num==0)
      {
     counter = counter + 1;
      }
   }
   if (counter ==2)
   {
      //Appended the Prime number to the String
      primeNumbers = primeNumbers + i + " ";
   } 
    }    
    System.out.println("Prime numbers from 1 to 100 are :");
   ```
   
   System.out.println(primeNumbers); 
4. run cell

expected result: scroll should be added to the output cell in case if the output text is bigger than cell size

actual result: output text is shown incorrectly - out from the cell. see http://joxi.ru/8An6bDQIqnlZMA

**Comment by tomca32** [comment]
I couldn't reproduce, looks fine here:

![screen shot 2016-03-14 at 11 08 00 am](https://cloud.githubusercontent.com/assets/3384784/13748856/150a54c2-e9d5-11e5-8acd-435bdc4b45ba.png)
![screen shot 2016-03-14 at 11 08 12 am](https://cloud.githubusercontent.com/assets/3384784/13748858/1641794c-e9d5-11e5-91fa-9b626cbe3927.png)

Can somebody else confirm?

**Comment by scottdraves** [comment]
dup of https://github.com/twosigma/beaker-notebook/issues/4161
