### ISSUE TITLE
flatten column menu

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3672]
redo the column menu to have less hierarchy and move the items around a bit.
entries should be, in order:
- Hide Column
- Filter...
- Search...
- Format ->
- Sort Ascending
- Sort Descending
- No Sort
- Align Left
- Align Center
- Align Right
- Heatmap
- Data Bars
- Fix Left
- Fix Right

**Comment by mnavasiolava** [comment]
maybe it also makes sense to show shortcuts for Heatmap and Data Bars menu items?

**Comment by scottdraves** [comment]
yes, please show the shortcuts
