### ISSUE TITLE
error when canceling calculations

### ISSUE THREAD

**Issue by maksim-lauryk** [twosigma/beakerx#3679]
when one cell is running and another cell is pending we have following error on canceling dialog after File -> New:

```
"Error: _queue[idx].output.output is undefined
jobQueue.cancelAll@http://127.0.0.1:8801/fe380fa/beaker/app/dist/beakerApp.js:5134:13
.cancelAll@http://127.0.0.1:8801/fe380fa/beaker/app/dist/beakerApp.js:5267:9
.controller/</<@http://127.0.0.1:8801/fe380fa/beaker/app/dist/beakerApp.js:4814:19
bkCoreManager.show2ButtonModal/callback@http://127.0.0.1:8801/fe380fa/beaker/app/dist/beakerApp.js:1844:13
bkCoreManager.showModalDialog/callbackAction@http://127.0.0.1:8801/fe380fa/beaker/app/dist/beakerApp.js:1782:13
bkCoreManager.showModalDialog/<@http://127.0.0.1:8801/fe380fa/beaker/app/dist/beakerApp.js:1788:11
processQueue@http://127.0.0.1:8801/fe380fa/beaker/app/dist/beakerVendor.js:54801:28
```

![error on cancel in beaker](https://cloud.githubusercontent.com/assets/13995034/13770992/c40bea3c-ea9b-11e5-9845-6697aa5e6f7a.png)

**Comment by scottdraves** [comment]
could not reproduce, i got 
https://pub.beakernotebook.com/#/publications/56e86fc7-d83e-40ad-89ec-3dbebf90fd72
without any console errors

**Comment by maksim-lauryk** [comment]
Let me check way of reproducing, the problem appears only if we are switching to other notebooks (or try to create new) and then select Ok on "Switching notebooks; all running and pending cells will be cancelled." dialog. 
Canceling via Language Manager works correct.
I tested it on bunsen (latest master version), and also beaker distr from bansen that was executed by 'gradle run' and on http://lab.beakernotebook.com too.

**Comment by scottdraves** [comment]
thanks, confirmed, if you use "new notebook" menu item, then i get this error.
if i cancel with the red X then it works.
