### ISSUE TITLE
Using realtime synchronizing service in Beaker

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#369]
**What**

A realtime synchronization service is a database services that, upon receiving updates, push the change to all clients and then make all connected clients in sync. An example is Firebase. Firebase offers aREST API and libraries in multiple languages including a JavaScript (Node and browser) and AngularJS.

This issue is a proposal of how beaker can take advantage of such services.

**What are the benefits**
1. Long running evaluation issue solved
2. Cross-plugin communication via `bk_out[]`  (related to: #89)
3. Robust session backup
4. Google docs style notebook collaboration (#128)

**Proposed Changes**
1. A new `bkSync` AngularJS module/service that wraps and can be configured to different realtime service provider and library at run time.
2. `bkEvaluateJobManager`, instead of pass the output cell reference to particular evaluators, allocates a space from the realtime syncing (e.g firebase) and passes a reference(ID) to the evaluator. The ID is recorded in the output cell data structure.
   ![beaker_sync](https://cloud.githubusercontent.com/assets/1767921/3458134/7300a556-01fe-11e4-80b2-f59a77139288.png)
3. Each evaluator, upon arrival or updates of evaluation result, find the target space with the ID, and update its content (preferably done by the backend). Since the results are cached, this solves the long running evaluation issue.
4. When resuming a session, beaker shall go through all the output cells and reconnect to the corresponding spaces with the IDs. The reconnection ensures the output keep receiving updates. This make things like dashboard possible in Beaker.
5. Since all the evaluation are stored as a list on the syncing service, plugins can retrieve of all evaluation results and form `bk_out[]`, in the prototype, this is done by taking snapshots before each evaluation.
6. Beside having the realtime sync service watch the evaluation arrays, the whole notebook model can be put monitored by the realtime syncing service too. `bkNotebookModelManager` will handle incoming and outgoing updates. This results in Google Docs style notebook collaboration.
7. Also the `bkSessionManager` can keep session model (notebook model plus session info) to the syncing space.  Since the session is stored outside of the beaker server, this can be add a layer of robustness to the backup mechanism. Moreover, in the case of moving toward stand alone evaluations services, the sessions could resume going through core server restarts.

A working prototype is available on the [alee/beaker-on-fire](https://github.com/twosigma/beaker-notebook/tree/alee/beaker-on-fire) branch.

video:
[![Beaker using Firebase](http://i.vimeocdn.com/video/481023762_640.jpg)](https://vimeo.com/99745318)

**Comment by scottdraves** [comment]
Looks great, thanks for the proposal Ang.

I don't see how IPython is going to do step 3.  Can you clarify?

Also, in step 5, can you expand how bk_out gets defined in each language?

**Comment by anglee** [comment]
In the prototype and considered how the IPython plugin works today (without wrapping the backend), the updating still needs to be done by the client. This of course will still suffer the long running eval problem. This is why I put 'Preferably done by the backend". I am not sure how IPython plugin can be changed so updates are sent by the backend. Also, there are client only plugins (HTML/LaTex/JavaScript) that will have similar issues.

As for `bk_out[]`, what would be good ways to make it reflect the _evaluations[] array in the synced space is open to discussion. In the prototype, like I mentioned, they either construct or overwrite a temp or global variable right before each evaluation. For example:
Node: https://github.com/twosigma/beaker-notebook/blob/alee/beaker-on-fire/plugin/node/src/dist/app/app.js#L63
Python: https://github.com/twosigma/beaker-notebook/blob/alee/beaker-on-fire/plugin/ipythonPlugins/src/dist/ipython/ipython.js#L120

I should also point out that there are some obvious drawbacks and unresolved issues about this. For example, now this involves 2 traffics to send the eval result to UI (first to synced space, then to front-end) instead of 1. Also, in the case of offline use, how beaker fallback to old behavior? In the collaboration use case, how to address race conditions? ... etc.

**Comment by scottdraves** [comment]
my gut feeling is that instead of changing all our plugins and wrapping backends,  the core server can do this for all the plugins, and be implemented in one place.

so the core server would have a copy of the notebook model (per session, updated via the sync svc). let's call it the "model manager". edits to code would be initiated from the client, as usual.  but for evaluations, the client would pass a request to the model manager, which would then contact the backend using its native protocol.  when it gets the result, it would update its copy of the model and sync it to the other copies, including the one in the client.  for example it could also write it to disk, which researchers might find reassuring.

the key change here is that the ipython code that talks websocket to their backend would run in the model manager (which means it would be implemented with node.js).  this is less complicated than wrapping.

an open question is how evaluation works exactly -- does the code to be evaluated come from the client, or does it use its local copy in the notebook model?  the problem is, there's a race condition where we have two channels between the client and the model manager, one through the sync svc and one opened by us.  code update followed by evaluation would have to arrive in the same order.  this can be resolved best i think if there were a way to identify a version of the model (so "evaluation" means "wait until you have version X of the model, then evaluate cell Y").  or "eval" could include an extra copy of the code.

**Comment by anglee** [comment]
When I mentioned wrapping the backend, I actually meant moving the websocket traffic to the backend, that is, the new backend act as proxy that does what your 'model manager' will do. So, about moving the native protocol traffic to backend, I think we are on the same page.

Different plugins can use different protocols and some plugin doesn't have backends, so I don't see the point of a single central manager. I think each plugin should have its freedom to do different kinds of evaluation, so beaker only defines API at the JavaScript level, that is, the plugins need to provide a evaluate function, and then when the beaker client calls it, it will provide a container (sync-space ID, the same as the evaluation ID mentioned below), and it is the plugin's responsibility to fill or update that container one way or another.

I am not sure when you mentioned notebook model if you were talking about the cell hierarchy or something else. Since a single cell can be evaluate multiple times, I think it make sense to keep all the evaluation results in an array,  `_out[]`, but not just the last (i.e. we only keep output.result).

Keeping all the evaluations in an array, then each evaluation will essentially have an ID (index to the array) and the index is determined(maybe by calling bkHelper.getNextID() and point cell.output to it) at the time the evaluation is make (that is, when beaker calls evaluator.evaluate()), so the evaluation ID is only generated from the client and we can mutex lock on the service bkHelper.getNextID() uses in the case of multiple clients presence. This way, all plugin will communicate via _out[] and can reference to the elements in _out[](get the latest value of _out[x]).

**Comment by scottdraves** [comment]
dup
