### ISSUE TITLE
screenshot in README.md broken

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#3692]
We have a broken image in the readme. The first and only image in the Screenshots section. Seems to have gone 404.

**Comment by scottdraves** [comment]
the url is defunct: http://twosigma.github.io/beaker-notebook/images/bk6.png
should check in the image and link to it like

```
![screenshots](https://raw.githubusercontent.com/twosigma/beakernotebook/master/screenshot.png)
```

**Comment by scottdraves** [comment]
ditto https://github.com/twosigma/beaker-notebook/wiki/Architecture
