### ISSUE TITLE
Cursor position is unintuitive when switching cells

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#3695]
To reproduce: 
1. Create two multi-line cells
2. Click somewhere in the middle of the text on the second cell
3. Click somewhere on the first cell
4. Move the cursor down with keyboard arrows until you enter second cell
5. Now cursor is not at beginning of text in second cell, it is in the last place

It becomes a bit weird when I'm editing one cell, use the arrow keys to move down, accidentally enter a new cell, and then I have to press up arrow 10 times, say, to get back to the other cell.

**Comment by scottdraves** [comment]
thanks for the report.  agreed.  when you use the down-arrow key from the last line of one code cell, and it moves to the next code cell, it should move to the first line.

ditto for moving up.
