### ISSUE TITLE
Flicker when adding new cell - result section appears and is hidden

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#3696]
When adding a new cell, it seems the results section is visible, and then hidden. This transition is visible, and makes all cells under added cell move down by the height of the combined input/output cell, and then move up by the height of the now-hidden output section of the added cell. When adding a cell, there shouldn't be this two-step down-up movement. 

Just a small UI quibble. :)

**Comment by scottdraves** [comment]
thanks, good catch.  for me this is most visible in chartingTutorial.bkr
