### ISSUE TITLE
Revisit Google Analytics

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#371]
After learning more about GA, I found that the custom metrics/dimensions we use are mostly redundant, meaning GA already record the equivalent and those are available in the report anyway.

It looks like only dimension3: beakerVersion need to stay. All custom metrics and custom dimension 1,2 can be removed.

When this issue is addressed, the [wiki](https://github.com/twosigma/beaker-notebook/wiki/Analytics) will need updates too.

**Comment by scottdraves** [comment]
sorry this isn't clear to me.  please list what you plan to remove.

**Comment by anglee** [comment]
All custom metrics:
1. file open
2. evaluation count
3. beaker app start count
4. tick
custom dimension
1. notebookType
2. pluginName

**Comment by scottdraves** [comment]
ang showed me what this means in the code.  basically we are passing the information twice, the 2nd should be eliminated.

**Comment by scottdraves** [comment]
@anglee did this ever get done?
does something still need to be done?
is it targeted for 1.0 or 2.0?

**Comment by anglee** [comment]
This was not done. We still want the redundant code to be removed, which should be trivial to do. That said, nothing bad happens without changing anything, so it doesn't really matters if it is 1.0 or 2.0 IMO.
