### ISSUE TITLE
Show Column menu item with many columns

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3723]
if there are more than ~20 columns then the Show Column menu in the main table menu doesn't work because it goes off the bottom of the screen.

can it be a 2d grid?  or maybe we need to switch to something completely different like a search box.

**Comment by djaddison** [comment]
It would probably useful to have the menu never extend past the bottom of the screen.
- Have the menu stop at the bottom of the screen
- Add a scroll bar
- Add a search to the top of the menu. This will provide an alternative to scrolling through a list should it grow to a large number of columns (ex. 5000 columns).

**Comment by scottdraves** [comment]
sounds like a good plan.  the scroll bar and search box should only appear if the menu is truncated.
the search box should filter the menu items as you type.
