### ISSUE TITLE
Issues rendering matrices

### ISSUE THREAD

**Issue by Chris1221** [twosigma/beakerx#3754]
The following code

``` tex
$$ \vec{J} = \begin{bmatrix} \frac{\partial f}{\partial{V}} & \frac{\partial f}{\partial{W}} \\ \frac{\partial g}{\partial{V}} & \frac{\partial g}{\partial{W}} \end{bmatrix} $$
```

returns

```
KaTeX parse error: Expected 'EOF', got '\begin' at position 16: vec{J} = \begin̲{bmatrix} \fra...
See: KaTeX website and its list of supported functions.
```

on the latest release of Beaker on OSX 10.10.4. The code renders fine on the KaTeX website:

![image](https://cloud.githubusercontent.com/assets/8516981/13954391/f25147b8-f016-11e5-81b9-8780e0943e94.png)

The same error is returned whether the expression is contained within `$$` in "text mode" or without in a dedicated `TeX` code block.

I'm wondering if I've confused the syntax or whether there is an issue in rendering matrices.

**Comment by scottdraves** [comment]
thx for the report.  we upgraded katex, this works now: https://github.com/twosigma/beaker-notebook/issues/3113
should come out in the next release in a couple of weeks.

![screen shot 2016-03-22 at 11 04 02 am](https://cloud.githubusercontent.com/assets/963093/13956165/fbfb12ba-f01d-11e5-9b2d-8cde79e7a264.png)

**Comment by Chris1221** [comment]
Thanks @scottdraves
