### ISSUE TITLE
safeHeight safeWidth

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3756]
these should go away once jquery 3.0 comes out.

**Comment by kpaharelau** [comment]
see https://github.com/jquery/jquery/issues/2889

> Thanks for the report! I wasn't aware of these plans and while we don't officially support SVG in most APIs, we've recently switched to getBoundingClientRect(), see #1724. This will land in jQuery 3.0.0, you can test the beta at https://code.jquery.com/jquery-3.0.0-beta1.js. We did that mostly to avoid rounding width/height to integers but it's good to know it has other advantages.

**Comment by scottdraves** [comment]
source: https://github.com/twosigma/beaker-notebook/issues/3621

**Comment by scottdraves** [comment]
this too? https://github.com/twosigma/beaker-notebook/pull/3792/files
