### ISSUE TITLE
class "Foo" confuses Java??

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3757]
https://pub.beakernotebook.com/#/publications/56f16616-2566-471e-b97f-28073e2b2e68

**Comment by tomca32** [comment]
Apparently it's already defined somewhere. Takes no arguments and contains only hashcode.
![screen shot 2016-03-22 at 11 58 06 am](https://cloud.githubusercontent.com/assets/3384784/13958157/71783f2a-f025-11e5-9cbc-a47584f5b7db.png)

**Comment by scottdraves** [comment]
yes it's used in javash.  it should have a more obscure name that users will never use.
