### ISSUE TITLE
java errors garbled

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3760]
https://pub.beakernotebook.com/#/publications/56f1a654-ed98-4714-85b3-2ab96fcac9a1

open the error to see:

```
ception {
syntax}
}
';' expected
n {
syntax}
}
```

other errors are also broken eg https://pub.beakernotebook.com/#/publications/56f1acb9-9532-436d-bd91-518554941451

```
java.lang.IllegalStateException: method getDateTxt() is already defined in class test.beaker.BeakerTest
ng();  }  public String getDateTxt() {    return _date.toString();  }  public S
```

**Comment by sshkalikov** [comment]
Compilation error messages will be better now. 
But they may be **much** better if we won't remove all line breaks in code (now we're compiling very long line of code (here's an example https://i.gyazo.com/d5558b3429023cfdf957780d518e8074.png))
