### ISSUE TITLE
Notebook: cell is moved up in case if changing cell id

### ISSUE THREAD

**Issue by aryzhykova** [twosigma/beakerx#3771]
Notebook: cell is moved up in case if changing cell id
1. open new notebook
2. add few code cells (Java Script for example)
3. click Option in context menu of the lowest cell
4. change id to the value "123"

expected result: cell position wasn't changed
actual result: cell was moved to the first place in notebook

**Comment by tomca32** [comment]
Confirmed. It seems that cells get ordered by celId
