### ISSUE TITLE
In some cases Run button doesn't work

### ISSUE THREAD

**Issue by mnavasiolava** [twosigma/beakerx#3795]
- open charting tutorial
- expand code cell for Custom Plot Example
- set cursor to the 1st line
- scroll down so Run button becomes visible
- click Run

**result:**
cursor was set to the last line
the code wasn't executed

**Comment by scottdraves** [comment]
i get the cursor going to the last line which is a bug, but the code is executed fine.
clicking in the bkg of the code cell below the cm should move the cursor to the end.
i think this is misfiring if user clicks on run button.
