### ISSUE TITLE
sync xhr produces warning

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3798]
https://github.com/twosigma/beaker-notebook/blob/d904181051bea71f3adc93fc490c88b692218a0a/core/src/main/web/outputdisplay/bko-plot/plotutils.js#L693

```
getFileSynchronously: function(file) {
        var xhr = new XMLHttpRequest();
        xhr.open("GET", file, false);
        xhr.overrideMimeType("text/plain; charset=x-user-defined");
        xhr.send(null);
        return xhr.responseText;
      },
```

this call produces this warning now:

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

1) does this really need to be synchronous?
2) we should use a higher level xhr, like why isn't this $http.get?

**Comment by mnavasiolava** [comment]
i wrote a comment about using this synchronous call here https://github.com/twosigma/beaker-notebook/pull/2662
