### ISSUE TITLE
improve file save dialog: handle dirs

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3808]
if you enter a directory, instead of producing a stack trace, just open it up and keep browsing.

**Comment by tomca32** [comment]
Maybe this lib? https://github.com/Kloudless/file-explorer

I never used it but it looks interesting. It also supports integration with a bunch of cloud services which might be useful. We might want to give users the option of saving to Google Drive for instance.

**Comment by scottdraves** [comment]
<img width="579" alt="screen shot 2016-03-28 at 3 13 47 pm" src="https://cloud.githubusercontent.com/assets/963093/14087362/b5d5f938-f4f7-11e5-845d-65930267be42.png">

**Comment by scottdraves** [comment]
kloudless looks cool let me move that to another issue

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/3818
