### ISSUE TITLE
research replacing file browser with a std lib

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3818]
https://github.com/Kloudless/file-explorer

**Comment by scottdraves** [comment]
i could have sworn we had an issue for this already but i can't find it.

**Comment by scottdraves** [comment]
looks like kloudless support for local filesystems is an upsell, so we are looking at https://github.com/Studio-42/elFinder instead (but using a Java server instead of PHP).

**Comment by djaddison** [comment]
This seems like a good option if we can skin / restyle it.
