### ISSUE TITLE
beaker does not work with ipython3 (installed via homebrew and pip)

### ISSUE THREAD

**Issue by bodokaiser** [twosigma/beakerx#3827]
I followed the tutorials in the wiki where it lists required python dependencies and how to edit `beaker.pref.json`:

``` json
{
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : false,
  "edit-mode" : "default",
  "theme" : "default",
  "languages": {
    "IPython": {
      "path": "/usr/local/bin/ipython3"
    },
    "Python3": {
      "path": "/usr/local/bin/python3"
    }
  }
}
```

When I visit the local website I see in the chrome console a **502 Bad Gateway** towards `http://127.0.0.1:8805/b1553d1/ipython.988422750461/login`

I tried latest 5.1.2 and 5.1.3 from beaker

**Comment by scottdraves** [comment]
See the wiki: https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences

In Beaker, IPython means Python2, so you should remove that, and not try to start it in Beaker (or also install it, so you can run the documentation).

and the path you have for Python3 is wrong, it should be to the directory, not to the executable.

**Comment by bodokaiser** [comment]
I changed to:

``` json
{
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : false,
  "edit-mode" : "default",
  "theme" : "default",
  "languages": {
    "Python3": {
      "path": "/usr/local/bin"
    }
  }
}
```

but I still get 502 Gateway Error.

Is there something I can do to see what happens on the server side for debugging purpose?

**Comment by scottdraves** [comment]
yes, open the Console application and search for "Beaker"

**Comment by bodokaiser** [comment]
So I built the server from scratch and I see:

```
0: /private/tmp/beaker-notebook/core/config/plugins/eval/ipythonPlugins/python3/python3Plugin
1: 8820
Python3-stderr>Traceback (most recent call last):
Python3-stderr>  File "/private/tmp/beaker-notebook/core/config/plugins/eval/ipythonPlugins/python3/python3PluginStart.py", line 19, in <module>
Python3-stderr>    from IPython import start_ipython
Python3-stderr>ImportError
```

Because home-brew per default installs python 3 as `python3` I also done a `ln -s` to `python`.

**Comment by scottdraves** [comment]
that looks like an incomplete python, make sure pip install all the dependencies:
ipython jinja2 tornado pyzmq pandas jsonschema jupyter

**Comment by scottdraves** [comment]
also possible: what version of ipython do you have?
maybe a newer version has removed this function.

**Comment by bodokaiser** [comment]
yeah deps are installed - ipython version is `4.1.2`

**Comment by kpaharelau** [comment]
I tried  on the mac os 10.11.4
bash-3.2$ ipython -V
4.1.2

All works fine. Did you use anaconda for installing python?

**Comment by bodokaiser** [comment]
No I used home brew guess there are some differences in how both install Python?

**Comment by kpaharelau** [comment]
Try to use
- python 2.7

```
brew install python
pip install ipython jinja2 tornado pyzmq pandas jsonschema jupyter
pip install numpy matplotlib scipy
```
- python 3.5

```
brew install python3
pip3 install ipython[notebook] jupyter
pip3 install numpy matplotlib scipy jinja2 tornado pyzmq pandas pyaml
```
- in pref file

```
 "Python3" : {
      "path" : "/usr/local/Cellar/python3/3.5.1/bin"
    }
```

**Comment by bodokaiser** [comment]
Ah yep this works for me now (editing the pref file). Maybe we can update the wiki to this?

**Comment by kpaharelau** [comment]
I need more time for additional research. I think wiki will be updated on monday.

**Comment by bodokaiser** [comment]
Okay thank you!
