### ISSUE TITLE
Sharing may be slow, needs "in progress" notice

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#383]
it took ~20s for the window to appear, after about 3s i decided it was broken.

**Comment by scottdraves** [comment]
repeated shares come up in ~2s so maybe server was just cold.

**Comment by bradicdesign** [comment]
@scottdraves Are you talking about File / Share to Web menu option?
I think we should include this into the dialog that collects the sharing metadata. I'll rev the mocks for that.

**Comment by scottdraves** [comment]
yup that's what i mean.  the time is pretty variable i have seen everything from 1s to 30s.

**Comment by scottdraves** [comment]
more evidence that we need some indicator that something is happening...
https://github.com/twosigma/beaker-notebook/issues/928

**Comment by scottdraves** [comment]
So when you click share a dialog should come up.  Eventually it will ask for meta info but right now it will just say "Share XXX to public web page?" where XXX is either "whole notebook", "section", or "cell".  And give an OK/cancel option.  If they click OK then they get a spinner until the page arrives.

**Comment by buob** [comment]
The above commit adds the progress indicator.  We can split out the confirmation if we want that as well in the future.
