### ISSUE TITLE
clicking on x should remove fields

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3831]
in the table search/filter fields, clicking on X should not just clear the fields, but also hide them.

**Comment by mnavasiolava** [comment]
do you mean **column** search/filter fields? because **table** search/filter fields do hide when you click on X.
about hiding column filter fields. don't you think it'll be confusing for users? the standard behaviour of an X btn in a search field is removing the value not the field itself.

**Comment by scottdraves** [comment]
let me think about that...

**Comment by scottdraves** [comment]
cannot reproduce
