### ISSUE TITLE
table missing controls

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3832]
https://pub.beakernotebook.com/#/publications/56fc4ef2-003d-4191-a06f-e2b0a8302343

you can reproduce this notebook with the python2&3 tutorial or just download the above to view.
the problem is the pagination controls are missing, ditto for the scrollbar.  but if you click on the
value column, or you filter, you can see there are many more rows.
<img width="318" alt="screen shot 2016-03-30 at 6 10 10 pm" src="https://cloud.githubusercontent.com/assets/963093/14159244/c0e3521a-f6a2-11e5-9bde-bca5d37751ae.png">

**Comment by mnavasiolava** [comment]
we show pagination controls only if there are more than 25 items in a table. otherwise we fix table height to 350px and add scroll. this table has 23 items and there is a scroll

**Comment by mnavasiolava** [comment]
about scrollbar. if you use chrome on mac and you have property 'Show scroll bars' set to 'Automatically based on mouse or trackpad' you may not see scrollbar thumb until you start scrolling. but in any case you are able to scroll the table

**Comment by scottdraves** [comment]
then please change the limit from 25 to 15 so you can either see all the elements, or the regular nav UI shows.

**Comment by scottdraves** [comment]
wait cancel that, let me experiment with this....

**Comment by scottdraves** [comment]
yea we should not have special behavior, if it exceeds the height then the full controls should appear.
