### ISSUE TITLE
text cell stuck in TeX mode  

### ISSUE THREAD

**Issue by Chris1221** [twosigma/beakerx#3857]
I'm having some unexpected results when trying to render some TeX inline. For example, the following code

``` tex
For a population of $n$ oscillators $\Omega$, with members $N_i, i \in N, 1 \leq i \leq n$. If $x, x\subset\Omega$ projects onto $N_i$ then the gap junctional current to $N_i$ is $\sum_{x} G_{x,i} H( 0.3 - V_x)$
```

Renders as follows:

![image](https://cloud.githubusercontent.com/assets/8516981/14230129/94144d92-f919-11e5-9873-fc4c649079c8.png)

This has been done on the most recent version of Beaker on OSX 10.10.4. The expression renders correctly in LaTeX and MathJax, though I cannot find a way to validate it in KaTex.

![image](https://cloud.githubusercontent.com/assets/8516981/14230137/0427f480-f91a-11e5-9fff-8b511a890bb4.png)

Any assistance would be appreciated.

**Comment by scottdraves** [comment]
thanks, confirmed, we'll look into this.  seems like a bug.

**Comment by scottdraves** [comment]
https://pub.beakernotebook.com/#/publications/57007c03-503e-4732-8e9a-1949ecf6c86c

**Comment by Chris1221** [comment]
Thanks!

**Comment by Chris1221** [comment]
This is probably a related issue but the following is also causing issues:

``` tex
For cell $i$ of $n$, define pro-necrotic burden as $\nu_i$, with total burden of the system equal to $\frac{1}{n} \sum^n_{i=1} \nu_i$. Note that $\nu_{1}, ..., \nu_{n} \in [0,1]$ and is a monotonically increasing function with respect to time. 
```

renders as 

![image](https://cloud.githubusercontent.com/assets/8516981/14232718/3b724f50-f981-11e5-8bbf-228023bf6233.png)

Though it renders correctly in MathJax:

![image](https://cloud.githubusercontent.com/assets/8516981/14232720/4b114308-f981-11e5-8164-37ecbf2fe4ec.png)

Same specs as above.

**Comment by Chris1221** [comment]
And another one:

``` tex
**Proof:** Let $\Omega$ be a population of $n$ neurons called $N_1, N_2, ..., N_{n-1}, N_n$. For any $1 \leq i \leq n$, if $\nu_i=1$, $1-\nu_i=0$, and accordingly $(1-\nu_i) G_g H(0.3 -V_{i+1}) + z_i=0$ because $z_i=0$ for any time above the initial impulse. Thus, $I_{m} = (1-\nu_i) G_g H(0.3-V_{i+1}) + z_i = 0$ or the effective membrane current which is acting on the system is $0$ for any $\nu_i=1$. Following this logic, if $I_m=0$ for any neuron $i$, $N_i$ will have a negative real component to its eigenvalue $\lambda$, and thus will have only one steady fixed point solution and not enter a stable limit cycle. Because $N_i$ will be fixed, $N_{i+1}$ will become fixed, and the effect will propegate throughout the system $\Omega$. In this way, $\nu_i=1$ for any $1 \leq i \leq n$ will be a trivial solution to the system.
```

Renders as 

![image](https://cloud.githubusercontent.com/assets/8516981/14232780/ebc679c0-f982-11e5-88a9-d9e1bd0f0ebc.png)

I included more than is necessary here, just because I'm not sure where the error is occurring.

Renders in LaTeX (obviously with `\textbf{}` instead of `**`):

![image](https://cloud.githubusercontent.com/assets/8516981/14232792/53a6858a-f983-11e5-9f72-4d108b8116eb.png)
![image](https://cloud.githubusercontent.com/assets/8516981/14232793/5a871e96-f983-11e5-8627-66d51ec59047.png)

And in MathJax

![image](https://cloud.githubusercontent.com/assets/8516981/14232786/2852a4f4-f983-11e5-83c5-095c48d0ae33.png)

Sorry for the spam, just want to give you guys as much info as possible.

**Comment by scottdraves** [comment]
Thanks for the extra info.  Definitely not spam!

**Comment by kpaharelau** [comment]
For a population of $n$ oscillators $\Omega$, with members $N_i, i \in N, 1 \leq i \leq n$. If $x, x\subset\Omega$ projects onto $N_i$ then the gap junctional current to $N_i$ is $\sum_{k=1}^n G_{x,i} H( 0.3 - V_x)$
