### ISSUE TITLE
FSharp plugin on Docker initialization failure

### ISSUE THREAD

**Issue by aolney** [twosigma/beakerx#3859]
I can build FsBeaker on Windows for Beaker 1.5.2 and it works great.

I'm trying to do a build that works on the 1.5.2 Docker image. 

So far I can pass the expected Nunit tests, deploy to docker, and load the plugin using the language manager.

During the init function  in fsharp.js, the locatePluginService finds the plugin, but then it appears to fail on a call to evaluate with `let beaker = new NamespaceClient(\"" + bkHelper.getSessionId() + "\")"`

I've create a new unit test with the code and it evaluates fine when not running with Beaker, so I don't think this is the culprit (also confirmed with the successful use on Windows).

Instead I wonder if there is something specific about nginx or similar infrastructure between the Windows and Docker releases.

Here is the console output (from Chrome):

```
beakerVendor.js:21227 POST https://127.0.0.1:8800/6e6bdd3/fsharp.916803482512/fsharp/evaluate 500 (Internal Server Error)
send @ beakerVendor.js:21227
jQuery.extend.ajax @ beakerVendor.js:20683
FSharp.evaluate @ fsharp.js:66
cb @ fsharp.js:191
(anonymous function) @ beakerVendor.js:50306
processQueue @ beakerVendor.js:54801
(anonymous function) @ beakerVendor.js:54817
Scope.$eval @ beakerVendor.js:56045
Scope.$digest @ beakerVendor.js:55856
Scope.$apply @ beakerVendor.js:56153
done @ beakerVendor.js:50602
completeRequest @ beakerVendor.js:50800
requestLoaded @ beakerVendor.js:50741
```

There's another error message for evaluate

```
Stream ended unexpectedly

System.Exception: Stream ended unexpectedly at FsBeaker.Kernel.ConsoleKernelClient.Execute (FsBeaker.Kernel.ExecuteRequest req) <0x40289220 + 0x0007b> in :0 at FsBeaker.Server+evaluate@108-2.Invoke (System.String code) <0x40288d90 + 0x00083> in :0 at FsBeaker.Server.required@78 (Suave.HttpRequest request, System.String parameterName, Microsoft.FSharp.Core.FSharpFunc`2 f) <0x4027a170 + 0x00055> in :0 at FsBeaker.Server.required@78 (Suave.HttpRequest request, System.String parameterName, Microsoft.FSharp.Core.FSharpFunc`2 f) <0x4027a170 + 0x00055> in :0 at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2 func, Microsoft.FSharp.Core.T arg1, Microsoft.FSharp.Core.TResult arg2) <0x4025ad70 + 0x00099> in :0 at FsBeaker.Server+app@144-11.Invoke (Microsoft.FSharp.Core.FSharpOption`1 _arg1) <0x40286790 + 0x00043> in :0 at Microsoft.FSharp.Control.AsyncBuilderImpl+args@835-1[a,b].Invoke (a a) <0x40258000 + 0x000af> in :0
```

Previously I thought this meant there was a problem with the NamespaceClient code (BayardRock/FsBeaker#5) but as I said the test case for this works, so I think this is just a trickle down exception from somewhere in Beaker.

**Comment by scottdraves** [comment]
maybe ask here https://github.com/BayardRock/FsBeaker

**Comment by scottdraves** [comment]
https://github.com/BayardRock/FsBeaker/issues/5
