### ISSUE TITLE
table in scroll mode has extra arrow

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3882]
there's a weird double arrow icon showing up in the bottom-right for no reason.
![screen shot 2016-04-05 at 4 15 13 pm](https://cloud.githubusercontent.com/assets/963093/14296774/ae0c701c-fb49-11e5-98b8-32787b356ed5.png)

**Comment by mnavasiolava** [comment]
yes, it looks not very good, but it has reason. this is a drag icon to control number of display rows when there is no pagination (https://github.com/twosigma/beaker-notebook/issues/3494)

**Comment by mnavasiolava** [comment]
yes, it looks not very good, but it has reason. this is a drag icon to control number of display rows when there is no pagination (https://github.com/twosigma/beaker-notebook/issues/3494)

**Comment by scottdraves** [comment]
thanks i forgot about that!  but yea it's not working for me.
please remove it and instead put a menu item in the main table menu
"Rows to Show" with subitems same as we have in the regular pop-up (10, 25, 50, 100, all).
