### ISSUE TITLE
Teradata Connection jdbc for sql  fails as driver not found

### ISSUE THREAD

**Issue by atulkakade** [twosigma/beakerx#3893]
Connecinting to teradata via jdbc fails using docker container

Included Paths 
/tmp/tdgssconfig.jar
/tmp/terajdbc4.jar

connection string format  used in sql cell 

%%beakerDB="jdbc:teradata://HOST/database=SANDBOX,tmode=ANSI,charset=UTF8,User=loginname,password=PW"
SELECT \* FROM dbc.tables;

Error 
com.twosigma.beaker.sqlsh.utils.DBConnectionException: Connection URI:jdbc:teradata://HOST/database=SANDBOX,tmode=ANSI,charset=UTF8,User=loginname,password=PW; No suitable driver

**Comment by scottdraves** [comment]
hi sorry i missed this issue before.
did you put the JAR with the driver into the classpath in the langauge manager settings?

**Comment by dclong** [comment]
@atulkakade @scottdraves 

I wanna try the SQL kernel to query Teradata. Are there doc to follow now? 

@atulkakade 
Would you share how your steps on how you made it work?

**Comment by scottdraves** [comment]
You should be able to just download the latest driver:
https://downloads.teradata.com/download/connectivity/jdbc-driver
and then use the `%classpath add jar` magic to load it.

**Comment by dclong** [comment]
Thank you, Scott! I'll give it a try.
