### ISSUE TITLE
Beaker Notebook setup files required for Red Hat Linux ver 6.x (Hadoop Servers)

### ISSUE THREAD

**Issue by jaimurugesh** [twosigma/beakerx#3901]
Hi,

Need setup files to install Beaker Notebook in Red Hat Linux ver 6.x (for Hadoop Servers)...
Please suggest some link/url

Thanks

Regards,
Jai Murugesh

**Comment by scottdraves** [comment]
Hi, sorry we don't support Red Hat Linux, but it's probably pretty easy to adapt https://github.com/twosigma/beaker-notebook/blob/master/launcher/ubuntu/install-runtime-core-dependencies.sh
for a minimal setup, and the other dependencies file in that directory for a complete runtime.
