### ISSUE TITLE
How do I start writing a plugin to integrate my data-analysis library?

### ISSUE THREAD

**Issue by ashleydavis** [twosigma/beakerx#3914]
I've been working on a data analysis toolkit and I really want to be able to use in beaker notebook.

https://github.com/data-forge/data-forge-js

I'm looking for help getting started with writing a plugin.

I'd like to be able to use Data-Forge directly in beaker notebook and have it's data-frames and series objects rendered as tables.

**Comment by scottdraves** [comment]
the easy way to get started would be with bkHelper.loadList, like in this example: https://pub.beakernotebook.com/#/publications/560ca047-eccd-4585-9b96-0d0708c49781?fullscreen=true

to get your own type displayed with the interactive UI, the just write a converter function (see our JS tutorial for the API to create an interactive table).
we don't yet have an API for extending what can be displayed like that.

**Comment by ashleydavis** [comment]
Is there any API docs yet for bkHelper?

Do you have a link handy for the tutorial with the interactive table?

**Comment by scottdraves** [comment]
That's the only function in bkHelper, most of them are in the beaker object.  the documentation is in the JavaScript tutorial https://pub.beakernotebook.com/#/publications/560b4b36-1510-48f6-970c-418c0526d58c?fullscreen=true and the Progress Reporting API, Notebook Control API, and Notebook Reflection API tutorials.

The JavaScript tutorial has example JS code that creates small tables that are easy to understand.  To see the raw data-structures you can select "Text" from the cell output menu:

<img width="425" alt="screen shot 2016-04-10 at 9 54 20 am" src="https://cloud.githubusercontent.com/assets/963093/14410652/474ccf18-ff02-11e5-8b8a-bc4ebe65d6b8.png">

and then you can see the data structure to return:

```
{"type":"TableDisplay","subtype":"TableDisplay","hasIndex":"false","values":[["up",2300000,2],["charm",1275000000,2],["top",173070000000,2],["down",4800000,-1],["strange",95000000,-1]],"types":["string","double","integer"],"columnNames":["name","mass","charge3"]}
```

**Comment by scottdraves** [comment]
this should make that clearer: https://pub.beakernotebook.com/#/publications/570a6a33-7636-41d5-886d-ed1c9c48e8b2
