### ISSUE TITLE
How can I use beaker-notebook with MongoDB?

### ISSUE THREAD

**Issue by ashleydavis** [twosigma/beakerx#3915]
I have a MongoDB database full of data that I want to analyse. How can I access this data in beaker-notebook?

Are there any plugins for this?

If not, I'm happy to contribute a plugin if someone can help me understand where to start.

**Comment by scottdraves** [comment]
you don't need a plugin to access mongo, just use the regular driver for your language of choice: https://docs.mongodb.org/ecosystem/drivers/

**Comment by ashleydavis** [comment]
So If I install something like [promised-mongo](https://www.npmjs.com/package/promised-mongo) globally beaker notebook will be able to pick that up?

Do I have to use use a beaker deferred object to pass the data onto the next cell? Or can I use any promise?

I thought it might look like this if I have to use the beaker deferred object:

```
var d = beaker.newDeferred();

var pmongo = require('promised-mongo');
var db = pmongo('mylocaldb', ['mycollection']);
db.mycollection.find().toArray().then(function (dbDocuments) {
     d.resolve(dbDocuments);
});
```

Or it could be simpler if beaker natively works with normal promises: 

```
var pmongo = require('promised-mongo');
var db = pmongo('mylocaldb', ['mycollection']);
db.mycollection.find().toArray();

```

**Comment by ashleydavis** [comment]
BTW your artwork is awesome ;)

**Comment by scottdraves** [comment]
thanks glad you are into the sheep!

beaker's deferred objects are for JS not for node.  i haven't tried installing stuff with npm and accessing it from the node plugin, but i did see this report: http://stackoverflow.com/questions/34769103/how-to-load-node-modules-in-beaker-notebook

we have barely used node beyond the demo tutorial, most people use python, R, or a JVM language.

if you could help us flesh out the node support I would be thrilled.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/4092
this should do it.  please LMK if accessing mongo is still a problem...
