### ISSUE TITLE
Problems running Node under Beaker on Windows.

### ISSUE THREAD

**Issue by ashleydavis** [twosigma/beakerx#3917]
I'm having trouble getting Node running under Beaker on Windows 8.1.

I'm running it from the command line which opens the Beaker window automatically in the browser. I create a new empty notebook then open the Language Manager and attempt to switch to Node. I get the following error:

![image](https://cloud.githubusercontent.com/assets/625126/14408795/a3bca276-ff45-11e5-8df5-404eeae35edc.png)

I already have Node installed (v5.6.0). So I updated my preferences to point to it and I still can't start Node. I'm not sure if I have this correct: 

```
{
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : false,
  "languages" : {
    "Node" : {
      "path" : "C:\\Program Files\\nodejs"
    }
  },
  "edit-mode" : "default"
}
```

I've checked the console where I'm running Beaker and don't see anything that looks like an error message.

Any idea where I've gone wrong?

**Comment by scottdraves** [comment]
I haven't tried the recent versions, for development we use v0.12, so I think that's your best bet.
Node isn't one of the major languages used for data science so we haven't had much demand for it and it's not well supported eg no autotranslation.
I would like to correct that!

**Comment by scottdraves** [comment]
looks like it's worse than that, the XSRF fix i put in a while ago appears to have broken node: https://github.com/twosigma/beaker-notebook/issues/3918

**Comment by scottdraves** [comment]
note that bug does not explain node not starting, it just means that after it starts you can't contact it as a server from beaker JS.

**Comment by scottdraves** [comment]
fyi we have updated to node v5 for development and i confirmed it runs node plugin on windows.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/3971

**Comment by ashleydavis** [comment]
Thanks for looking into this. Sorry I haven't gotten back Beaker-Notebook yet. It's very important to me to get an integration working between this and Data-Forge.
