### ISSUE TITLE
"Error: R language backend failed!"

### ISSUE THREAD

**Issue by jolespin** [twosigma/beakerx#3951]
I'm using Yosemite

I can't figure out how to configure my setting to get `R` to work in `Beaker`? I tried both with the experimental `beaker-notebook-1.5.3-0-gb1553d1-electron-mac.dmg` version because I really don't want to use the browser for my programming.  I also tried the normal `beaker-notebook-1.5.2-0-g34d512f-mac.dmg` but got the same issue when running `R`. 
# Checked where my R is located

```
    $ which R
    /usr/bin/R
```
# Checked which version of R i'm using

```
    $ R

    R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
    Copyright (C) 2014 The R Foundation for Statistical Computing
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
```
# My preferences .json file

```
    #~/.beaker/v1/config/beaker.pref.json
    {
      "languages" : {
        "IPython" : {
          "path" : "/Users/Mu/anaconda/bin"
        },
        "Python3" : {
          "path" : "/Users/Mu/anaconda/envs/python3/bin"
        }
        "R" : {
          "path" : "/usr/bin"
        }
      },
      "pref-format" : "1",
      "advanced-mode" : false,
      "allow-anonymous-usage-tracking" : true
    }

```

[![enter image description here](http://i.stack.imgur.com/BCKX5.png)](http://i.stack.imgur.com/BCKX5.png)

`IPython` is working fine...

[![enter image description here](http://i.stack.imgur.com/DZDfb.png)](http://i.stack.imgur.com/DZDfb.png)

I asked it here, if someone figured it out please migrate the answer to stakoverflow: 

http://stackoverflow.com/questions/36612451/cant-use-r-language-with-beaker-notebook-error-r-language-backend-failed

**Comment by scottdraves** [comment]
Thanks for the report.  How did you install R?

**Comment by scottdraves** [comment]
and what happens when you click on R in the language manager, does the button go green?

**Comment by jolespin** [comment]
They are all yellow.  I don't remember when/how I installed R.  I think it was when I installed RStudio. 
![screen shot 2016-04-15 at 11 35 55 am](https://cloud.githubusercontent.com/assets/9061708/14571522/83288d2e-02fe-11e6-8d13-fd9224bc5e03.png)

**Comment by scottdraves** [comment]
did you use R from within RStudio to install the packages that Beaker uses (Rserve, devtools, RCurl, RJSONIO, etc)?

**Comment by jolespin** [comment]
hey that worked ?!  why would running the commands from RStudio opposed to R in the terminal work? Thanks a lot.  Excited to try out Beaker now.

**Comment by scottdraves** [comment]
good question, I have no idea, if anyone can explain (and ideally prevent this) then please let us know.
