### ISSUE TITLE
Customize/create a default notebook to open?

### ISSUE THREAD

**Issue by jolespin** [twosigma/beakerx#3952]
Is there a way to customize the default notebook that is on the homepage? I want to set it to load up python and import a few modules that I use for every notebook.

**Comment by scottdraves** [comment]
yes, create a notebook you like and save it to `~/.beaker/v1/config/default.bkr`. This will be loaded when you click the 'New Default Notebook' button, or use the Control-Shift-N keyboard equivalent.

The default notebook that comes with Beaker has Python and R cells as well as some tips for beginners. It would be normal for advanced users to customize the included languages (for example, adding a standard JAR to their Groovy classpath), remove the tips, and add a signature cell with their contact information.

from http://beakernotebook.com/faq
