### ISSUE TITLE
Version beaker-notebook-1.6b1-0-g5c1e80e-electron won't start on Windows

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#3965]
No entry point. web version from the same installation works fine.

Also consider removing JDK from installation package. All modern computers have at least jvm 7 installed.

**Comment by scottdraves** [comment]
thanks for the report.  is this the error you get?
![screen shot 2016-04-18 at 4 04 45 pm](https://cloud.githubusercontent.com/assets/963093/14618209/72eb0b98-057f-11e6-8b28-ccbc332693ce.png)

**Comment by altavir** [comment]
Yes, this one.

**Comment by kpaharelau** [comment]
The latest version of electron uses node js v5.10.0 instead v0.12 from our application. We will increase version node js ASAP and new version installer will be created soon

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/3974

**Comment by scottdraves** [comment]
confirmed a freshly built installer with node v5 fixes this.
