### ISSUE TITLE
Feature Requests: (i) Middle of string add quotes and (ii) Cell Label for Hide/Show

### ISSUE THREAD

**Issue by jolespin** [twosigma/beakerx#3967]
**Feature 1:**
In Jupyter there is a feature where one can have text written out (single word) where you can click in the middle and press [SHIFT]-['] (i.e. ") and it adds quotations around the entire word
_#Step 1_
`var = tobestring`

_#Step 2_
`var = tobest | ring (| indicates where cursor is)`

_#Step 3_
# Press "

`var = "tobestring"`

A really small feature but it would be pretty useful!

**Feature 2:**
The Hide/Show Cell is AMAZING.  It really helps unclutter my notebooks but sometimes I'm not exactly sure what's in the collapsed cell.  It would be awesome if I could have a label for the Hidden Cell so I could know which one to open.

**Comment by scottdraves** [comment]
Feature 1 We have sublime edit mode but it doesn't implement this feature.  Seems like it should though:

' with a selection: surround selection with apostrophe
" with a selection: surround selection with quote
[ with a selection: surround with square brackets
{ with a selection: surround selection with curly brace
( with a selection: surround selection with brackets

from https://gist.github.com/bdargan/2705812

I think I would be surprised by this so let's start out with it just in sublime mode.

Feature 2 thank you, I agree and I was thinking we should just show the 1st line which could be a comment.  For outputs, you can summarize the contents:  https://github.com/twosigma/beaker-notebook/issues/3159
