### ISSUE TITLE
comments and multiline strings in json

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#397]
we should allow comments and multiline strings in our various json files (prefs and notebooks) in addition to the default notebook.

people need to document their preferences.

and multiline strings are very handy in notebooks, since then the code in cells doesn't get compressed to one line.  right now, diffs for source control of notebooks are almost useless, this would fix that.

we have a function clean() defined in UtilRest.java that handles the reading (though it could be improved).

writing would have to recognize multiline strings and substitute our syntax.

the downside of this is our files are no longer standard json but i think the upside outweighs that.

**Comment by scottdraves** [comment]
maybe config files should be http://yaml.org/

notebooks could be multiline and still be pure json if the format allowed for a list of strings to be converted into a string with linebreaks added, when the code of a cell is read, before it is used.

**Comment by melmac48** [comment]
take change to vectorize json but leave yaml for v2
