### ISSUE TITLE
ipython kernelspec deprecated

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3973]
https://github.com/twosigma/beaker-notebook/blob/master/launcher/ubuntu/install-dependencies.sh#L66

we should switch to jupyter kernelspec.

**Comment by sshkalikov** [comment]
'jupyter kernelspec install-self' is deprecated in ipython 4.x, too) discussion:  https://github.com/jupyter/jupyter/issues/23
and looks like replacement is 'ipython kernel install' (https://github.com/ipython/ipykernel/pull/43) which does the same and isn't deprecated **but** it doesn't work in ipython 3.x at all, so i'm going to use it in install-dependencies.sh, but for Docker images we should keep using 'ipython kernelspec install-self' (it isn't deprecated in ipython 3.x which we're using in docker)

**Comment by scottdraves** [comment]
still need to remove it from the Dockerfile
