### ISSUE TITLE
[Select all text] -> [Right Arrow] does not go to end of text

### ISSUE THREAD

**Issue by jolespin** [twosigma/beakerx#3975]
I noticed that when you select all the contents of a cell (in Python3 environment at least) and press the right arrow key, it doesn't go to the end of the text.  It works if I press the left arrow key or up arrow key (to go to beginning) . 

Down or Right doesn't work to go to the end :(

**Comment by jolespin** [comment]
It would be really cool if:
[Left Arrow] went to Top Left of text block
[Up Arrow] went to Top Right of text block
[Down Arrow] went to Bottom Left of text block
[Right Arrow] went to Bottom Right of text block

but as of now, most things (on OSX at least) are Left = Up = Top Left, (start) Right = Down = Bottom Right (end)

**Comment by scottdraves** [comment]
thanks for the bug report.  i think we'll go with the std behavior.
