### ISSUE TITLE
Toggle out of [Shift]-[Tab] for doc string is not working

### ISSUE THREAD

**Issue by jolespin** [twosigma/beakerx#3987]
When you press [Shift]-[Tab] on an object it brings up the doc string in a little pop-up window.  It does not work to Toggle out of the pop-up doc window by 1) [Shift]-[Tab] again; 2) moving mouse off pop-up; or 3) clicking on text outside of pop-up window.  The only way I can get the pop-up window to go away is by clicking the menu bar. 

![screen shot 2016-04-20 at 11 55 40 am](https://cloud.githubusercontent.com/assets/9061708/14686756/180435ee-06ef-11e6-803b-eaa084b91f4e.png)

**Comment by tomca32** [comment]
ESC works I believe.

But I agree, Shift+Tab should work as well. Will take a look at this.

**Comment by jolespin** [comment]
Good to know about ESC.  It will definitely work in the meantime. Thanks!

**Comment by scottdraves** [comment]
other options: if you click on the bkg of the notebook it closes, or if you type any key in the code cell it closes.

but yea seems like it should toggle.
