### ISSUE TITLE
new backend fails

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4002]
it seems to just exit on mac

**Comment by mnavasiolava** [comment]
yes, i could reproduce it. for me the problem was in unavailable ports. when we can't find available port we just exit the app. for some reason i had many R processes that were hanging in a memory and were using ports that we checked. after i killed them new backend started normally

**Comment by scottdraves** [comment]
i cleaned up all processes and still had the same problem.
if it does happen then a decent error has to be reported.

**Comment by mnavasiolava** [comment]
could you please show your console output when you're starting new backend?
