### ISSUE TITLE
mac version leaks processes

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4006]
nginx and java and even python.

**Comment by mnavasiolava** [comment]
what version of beaker did you try? the latest master? could you please give me more details because i can't reproduce this on latest master. after quitting the application all started processes are killed (https://www.dropbox.com/s/x8qgd0f5w39ws83/beaker_mac_processes.zip?dl=0)

**Comment by scottdraves** [comment]
image was made with old code somehow.
