### ISSUE TITLE
Feature Request: "Copy" and "Highlight" text on (Pandas) table columns value

### ISSUE THREAD

**Issue by jolespin** [twosigma/beakerx#4008]
I like the dynamic tables that pop-up when you make a pandas dataframe.  Sometimes I like to select the text in the columns to copy and paste instead of manually typing in something like this `Last Update (d/m/yyyy hh:mm:ss)` . 

*_Can you add a feature where you can actually highlight the text on Pandas DataFrame objects? *_

**Comment by scottdraves** [comment]
sorry i don't really understand, you should be able to click and drag to select text within a cell in the table.
or use the menu to copy multiple cells in CSV format (to paste into excel for example).

make sure you are using Beaker 1.6 which we just released and has a new table UI: http://beakernotebook.com/downloads

**Comment by jolespin** [comment]
Hi Scott, my apologies for not being specific.  I just downloaded the new UI (the electron version) and it works great...very smooth and seamless.  

So I'm able to select the text on all of the cells except for the Column labels.  Right-Clicking doesn't have a response and "Copy" isn't available as an option in the Column Menu.

Thanks,
-Josh

![screen shot 2016-04-23 at 10 10 28 am](https://cloud.githubusercontent.com/assets/9061708/14762953/2385df04-093c-11e6-8960-ba0797631728.png)

**Comment by scottdraves** [comment]
copy to CSV is in the table menu (leftmost column)

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves
