### ISSUE TITLE
Running beaker.command results in error Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by ArthurZ** [twosigma/beakerx#4010]
Beaker 1.6: attempting to start with beaker.command results in
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/twosigma/beaker/core/Main : Unsupported major.minor version 52.0
When running sudo beaker.command it can start, although I see an error 
ERROR reading file /root/.beaker/v1/config/beaker.pref.json
I have an impression I am unable to get a clean start.
I am on javac 1.8.0_77

**Comment by scottdraves** [comment]
which OS are you on? maybe unset JAVA_HOME?

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by ArthurZ** [comment]
Ubuntu 14

**Comment by scottdraves** [comment]
you must have an old version of java installed.
java8 _is_ version 52, so if it says version 52 is not supported then you are not really running java8.

**Comment by sshkalikov** [comment]
maybe you have 2 jre installed. just check what '$JAVA_HOME/bin/java -version' and 'java -version' says when you run it without superuser permissions
