### ISSUE TITLE
update install docs to include new R packages

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#402]
there are developer docs and user docs.
dev docks updated on merge,
user docs on release.
this bug is mostly about for the 1.0 release.
They are:

```
RCurl
RJSONIO
devtools
```

**Comment by scottdraves** [comment]
devtools requires R v3.0.2 or higher we should say so in our doc

**Comment by scottdraves** [comment]
developer docs/prereq scripts updated.

**Comment by melmac48** [comment]
handling this on the website
