### ISSUE TITLE
"circular objects are not supported" Error

### ISSUE THREAD

**Issue by dberansky** [twosigma/beakerx#4022]
My notebook has three cells: an HTML cell that defines the report, a Python cell that preps the data, and finally a Javascript cell that uses data passed from Python to create D3.js charts in the HTML cell.  Everything is running just fine, but the Javascript section always shows this error: "circular objects are not supported".   What's causing it?

**Comment by scottdraves** [comment]
objects that contain pointers to themselves (even via a deeply nested object) are infinite in a way and so they can't be displayed.  in this case, just end the code cell with `"ok"` or any constant to avoid the error.

**Comment by dberansky** [comment]
thanks
