### ISSUE TITLE
notebook doesn't reconnect

### ISSUE THREAD

**Issue by dberansky** [twosigma/beakerx#4023]
I'm running Beaker on a dedicated server rather than on my laptop.  Whenever the laptop is disconnected from the network for some time (e.g. in sleep mode while in-between work sessions or VPN times out), an open notebook won't reconnect on its own.  In order to be able to continue editing I have to go back to the beaker control page and restart work from there.  Is there a way to force reconnecting from an open notebook (like the reconnect option in iPython's Notebook)?

**Comment by scottdraves** [comment]
thanks for the report i will try this out.  it should work the same.

**Comment by scottdraves** [comment]
what OS is your laptop?

**Comment by scottdraves** [comment]
add a button to the disconnected dialog with the label "reconnect" that tries to do so.
make it the default if you just hit return (blue).

change the red offline text from "offline, click to download a copy" to "offline, click reconnect or download a copy"

**Comment by dberansky** [comment]
Didn't get a notification of your OS question.  If it still matters, I'm running Windows 7.
