### ISSUE TITLE
UI for tagging cells

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#403]
This issue is about implementing that UI that makes users able to associate tag or tags to a cell so that one can run evaluate() on a tag can cause all the cells with that tag to be queued to the eval queue.

**Comment by melmac48** [comment]
@bradicdesign this is the cell tagging we were talking about today. Things to consider: How does a cell get tagged (an item on the cell hamburger menu should suffice)
Is there a way to show the user that a cell has been tagged and what the tag name is.

**Comment by scottdraves** [comment]
We have a UI now, but the dialog needs to be cleaned up.
