### ISSUE TITLE
cell printing

### ISSUE THREAD

**Issue by dberansky** [twosigma/beakerx#4043]
Is there an (easy) way to print the content of a single cell, especially HTML cells (say, containing a mix of HTML, CSS and D3-generated SVG).

**Comment by scottdraves** [comment]
no but that's a good idea.

**Comment by scottdraves** [comment]
addition to: https://github.com/twosigma/beaker-notebook/issues/709

**Comment by dberansky** [comment]
Here's a workaround I'm using, which might be helpful in figuring out the solution:
1. wrap the content of the cell I want to print in a div with an id (e.g. "`myReport`")
2. add this CSS rule:

```
@media print {
  .notebook-container {
     padding: 0;
     margin: 0;     
  }
}
```
1. run the following javascript (I'm doing this from the console):
   `$('#myReport').parents().siblings().hide(); $('#myReport').siblings().hide();`
2. print
