### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by johnbwilliams** [twosigma/beakerx#4048]
beaker cell runs an old version of R (3.1.2) when a is newer version is installed & available (3.2.5)

**Comment by scottdraves** [comment]
what OS are you on?

**Comment by johnbwilliams** [comment]
Win7

**Comment by scottdraves** [comment]
How did you install R?  On Windows the normal installer should set a resource.  Beaker then uses that to find the most recently installed binary https://cran.r-project.org/bin/windows/base/rw-FAQ.html

I recommend you install R again, and see if Beaker picks up the location.
Or, uninstall the old version.

If it still doesn't work then you can manually give Beaker a path to find R with your prefs file: https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences

**Comment by johnbwilliams** [comment]
I use the standard R installer. Rstudio finds the updated R.  will set prefs file  Thanks
