### ISSUE TITLE
Consider using composite build gradle feature

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#4054]
Gradle 2.13 introduces [composite project feature](https://docs.gradle.org/current/release-notes#tooling-api-support-for-creating-composite-builds) which allows to combine all separate modules in one build instead of elaborate redirects. I am still trying to figure how this feature works (since there is not much documentation), but it is possible that it could simplify beaker build logic.

**Comment by scottdraves** [comment]
thanks for the tip.

**Comment by altavir** [comment]
Gradle composite build dsl is fully released in [gradle 3.1](https://docs.gradle.org/current/userguide/composite_builds.html). It is working fine from gradle console, but for now there is no full support in IDEA (compillation is working, but included builds are not loaded as modules).
