### ISSUE TITLE
Upgrade to Katex 0.6.0 environment

### ISSUE THREAD

**Issue by wllmtrng** [twosigma/beakerx#4055]
Katex 0.6.0 introduces support for the latex aligned environment, amongst others:

[https://github.com/Khan/KaTeX/releases/tag/v0.6.0](https://github.com/Khan/KaTeX/releases/tag/v0.6.0)

New Features:
Introduce the aligned environment.
Add \gt and \lt.
Bundle CSS and fonts in npm package.
Fix sub- and super-scripts not being centered inside of math display.
Add \underline support.

**Comment by scottdraves** [comment]
thanks for the tip
