### ISSUE TITLE
Lock individual cells

### ISSUE THREAD

**Issue by rionda** [twosigma/beakerx#4061]
It would be nice to have a feature to only lock text cells but not code cells.

Even more generally, one can envision wanting to lock cells on a cell by cell basis.

**Comment by scottdraves** [comment]
hi, thanks for the suggestion.i like the idea of being able to lock any cell.  it would be easy to have another item with a checkmark in the cell menu.

**Comment by scottdraves** [comment]
actually hold off on this one.
once you lock a cell how do you unlock it?
the menu vanishes on lock.

**Comment by rionda** [comment]
From a notebook menu entry? "Unlock all locked cells"? Clunky perhaps.

**Comment by scottdraves** [comment]
best idea so far: when locked the unlock menu appears on hover.
this may not be visible enough, it has a big problem with touch screens.
on the plus side, it is similar to https://github.com/twosigma/beaker-notebook/issues/2676

**Comment by scottdraves** [comment]
add to the cell menu a new item "Lock" that has a check mark, like inittialization.  this is like "Lock notebook" but for each cell.
If a cell is locked then the menu should still appear on hover.
