### ISSUE TITLE
Using a not-installed-by-default Python package in beaker lab

### ISSUE THREAD

**Issue by rionda** [twosigma/beakerx#4065]
I would like to use a third-party package (Berkeley's datascience, https://github.com/data-8/datascience, available in pip) in a Beaker lab notebook.

Is there any way to accomplish this?

**Comment by scottdraves** [comment]
the long-term plan is to develop a package manager GUIs that works for all the languages.
so far we have JavaScript working, the other languages will follow.
In the meantime we have a workaround for R (see below).
Davide is going to try to come up with a workaround for Python next week.

## 

To install R packages:

1)      Open scratch space, click BROWSE and create a directory rpackages
2)      Create a blank R notebook
3)      Type “install.packages(‘packagename’, ‘/mnt/scratch/rpackages’, repos=’http://cran.us.r-project.org’)” and run the cell
4)      Wait for installation to finish
5)      If installation hangs for some time it means that something malfunction -> reload browser, close notebook, reopen notebook and redo the install command. This will continue from where it arrived before blocking.

To use installed packages:
In your R notebook – first cell do:
“.libPaths(c(‘/mnt/scratch/rpackages’,.libPaths()))”
And run the cell

**Comment by DashaMer** [comment]
I am wondering whether you had any luck coming up with a solution to this issue?

**Comment by ildipo** [comment]
Hi,
the datascience package is already present in Python3 on BeakerLab.

To install other packages you can check:
https://lab.beakernotebook.com/publications/3c73a144-3ec1-11e6-935b-8ff81ae480a3?fullscreen=false

and

https://lab.beakernotebook.com/publications/2ff702e6-3ebf-11e6-b0e2-5f05deb51e12?fullscreen=false
