### ISSUE TITLE
How to use Nodejs variables from one cell to another?

### ISSUE THREAD

**Issue by ashleydavis** [twosigma/beakerx#4068]
Beaker now works with latest version of Nodejs. Thanks for that.

How do I share data from one cell to another?

Is it possible to have the cells run in the same memory space so that variables can be shared?

I don't seem to be able to do this:

![image](https://cloud.githubusercontent.com/assets/625126/15005729/ba9ecd88-120b-11e6-93d8-15ff8c611223.png)

**Comment by tomca32** [comment]
Use the global namespace. Since the code is in strict mode, the only way to declare global variables is to attach them to the global context. In the browser that is window, and in node that is global object.

``` javascript
global.x = 3;
// Now you can access global.x in another cell
```

Let me know if this works for you.

**Comment by ashleydavis** [comment]
Yes that works thanks.

Although it would be more convenient not to use the 'global' object.

Is there a way to disable _strict mode_?

**Comment by tomca32** [comment]
Not at the moment, but I agree completely. Strict mode should be disabled by default, I just pushed a commit that fixes that.

**Comment by ashleydavis** [comment]
Great. Where can I see the commit? I'm keen to see what is going on here, would like to understand more and possibly contribute in the future.

Do you know when your commit might be included in a release?

**Comment by tomca32** [comment]
Sure. Take a look at the PR: https://github.com/twosigma/beaker-notebook/pull/4078/files
Basically we were evaling in the current context which had the strict mode on.

I'm not sure when is the next release coming. @scottdraves might know.

**Comment by ashleydavis** [comment]
Thanks

**Comment by scottdraves** [comment]
we make quarterly releases.  the next one would be maybe july 1st.
