### ISSUE TITLE
Node Express server dies on error

### ISSUE THREAD

**Issue by tomca32** [twosigma/beakerx#4077]
1. Open the Node tutorial.
2. Run the first cell.
3. Run the first cell again. (You should get an Address in Use error)
4. Run the first cell again. (Express responds with 404, screws up the styles and dies).
5. You cannot run Node again unless you restart Beaker, even in different notebooks.

![screen shot 2016-05-05 at 2 16 51 pm](https://cloud.githubusercontent.com/assets/3384784/15052553/441455b8-12cc-11e6-8bdb-fbc45b7a2f7e.png)

**Comment by sshkalikov** [comment]
i fixed this issue while working on autotranslation for nodejs - now all executions are wrapped with '[trycatch](https://www.npmjs.com/package/trycatch)' module so error in one cell doesn't lead server to crash
Btw, node tutorial was also changed, and now it tries to stop previously started http server so it's possible to run it multiple times
