### ISSUE TITLE
Mac OS X 10.7.5 - Beaker 0.55 missing nib file?

### ISSUE THREAD

**Issue by randompi** [twosigma/beakerx#408]
The application won't launch for me.  When run from the command line:

localhost:MacOS user$ ./Beaker 
2014-07-25 14:04:26.601 Beaker[12959:707] Unable to load nib file: MainMenu, exiting

**Comment by scottdraves** [comment]
Thanks for the bug report.  We didn't have a 10.7 machine to test on, just 10.9 and 10.8.
Sorry it didn't work for you.
I did use what I thought were XCode settings to work with 10.6 and above but there must be more to it, I will look into it.

This article http://apple.slashdot.org/story/14/02/27/1513248/apple-drops-snow-leopard-security-updates-doesnt-tell-anyone
says that 20% of general users still have 10.6 so I would guess even more have 10.7.

**Comment by melmac48** [comment]
currently don't support back beyond 10.8. Will look into expanding text matrix and support in v2

**Comment by eubrandt** [comment]
I have a 10.6 machine if you'd like reports of trial runs there.

(I can take a crack at it myself, but my guess is Xcode 3 may not cut it either.)

**Comment by doctorbrassica** [comment]
Can confirm this error in 10.7.4, late 2011 machine.  Also confirmed there are plenty of 10.7 machines out there.

**Comment by scottdraves** [comment]
Thx Jonathan.  This is definitely moving up our agenda.

**Comment by scottdraves** [comment]
eubrandt, is that you eli?

**Comment by powderly** [comment]
Hey Scott,

just to thricely confirm

MacOS User$ ./Beaker
2014-12-28 03:29:02.558 Beaker[77935:707] Unable to load nib file: MainMenu, exiting

on 10.7.5
2012 macbook pro

**Comment by scottdraves** [comment]
thanks james will def get this one in the next release.

**Comment by scottdraves** [comment]
turn off Base Internationalization?
http://stackoverflow.com/questions/18917278/base-lproj-mainmenu-xib-is-not-available-when-compiling-for-targets-before-mac-o

**Comment by scottdraves** [comment]
well that doesn't work, it just leaves out the nib files completely, so the app fails to run even on the machine where it was built.  i can probably figure out how to copy them into the right place though, one way or another.  the right place is Contents/Resources (not in Base.lproj subdir where Xcode was putting them).

As an experiment I made this change on the finished app file on a 10.7 machine and it does in fact start (yea!) but then nginx fails to start with this error:

```
3/10/15 11:50:10.453 AM ReportCrash: Failed to create CSSymbolicatorRef for jspawnhelper[88454]
3/10/15 11:50:10.561 AM ReportCrash: Failed to create dSYM-less CSSymbolicatorRef for jspawnhelper[88454]
```

which means that nginx hasn't been compiled to work on old versions of the OS
http://stackoverflow.com/questions/11298922/failed-to-create-cssymbolicatorref

**Comment by scottdraves** [comment]
OK I was able to build the nginx binaries on the old mac, and with the nib files in the right place, it works.
and the old bins work on a new mac.  finally some good news :)
