### ISSUE TITLE
Low priority: Disable inline italicizing of text cells when inside a latex block denoted by $....$

### ISSUE THREAD

**Issue by wllmtrng** [twosigma/beakerx#4081]
For the latex block: 

$entropy = \sum-p_i log_2(p_i)$

The characters between the _'s are italicized inline. They shouldn't be in this case since it is in a latex block.

**Comment by scottdraves** [comment]
agreed, & we already have an issue for this: https://github.com/twosigma/beaker-notebook/issues/3280
thanks
