### ISSUE TITLE
Low priority: Existence of long file path name for beaker notebook covers the first cell in Advanced mode.

### ISSUE THREAD

**Issue by wllmtrng** [twosigma/beakerx#4084]
If the file path of the notebook wraps to two lines, the first cell is covered as shown with the attached image.

<img width="710" alt="screen shot 2016-05-08 at 12 43 14 pm" src="https://cloud.githubusercontent.com/assets/1335855/15099980/842392ea-151a-11e6-8f8f-01e63c58f1e4.png">

**Comment by scottdraves** [comment]
thanks.  confirmed.

the filename should not jump down to the next line, and it should not hide the notebook.
