### ISSUE TITLE
long filename breaks save dialog

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4085]
<img width="870" alt="screen shot 2016-05-08 at 10 24 24 pm" src="https://cloud.githubusercontent.com/assets/963093/15102294/9a710266-156b-11e6-9143-4ee0ce717fb0.png">

**Comment by scottdraves** [comment]
skip this for https://github.com/twosigma/beaker-notebook/issues/3818

**Comment by scottdraves** [comment]
how does our current dialog handle this?

**Comment by sshkalikov** [comment]
save dialog looks good
![](https://i.gyazo.com/c7f10835ff4328d9aea7d53482d6d118.png)

**Comment by scottdraves** [comment]
i find the really wide column and the vanishing of the other fields kind of confusing.
not sure what the right solution is though.   wrap?  ellipsis?
