### ISSUE TITLE
Scala-Spark tutorial has problem on MacOS

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#4086]
The line `val logFile = "../../../../../LICENSE"` refers to an actual file on Linux, but not on MacOS.  I think the problem is going one too many levels up.

`org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/Applications/Beaker.app/Contents/Resources/LICENSE`

**Comment by scottdraves** [comment]
thanks for the bug report.  i'll probably just delete that example as the other one proves the point, and referring to a file like that is just poor.
