### ISSUE TITLE
System shell commands should output with colors

### ISSUE THREAD

**Issue by wllmtrng** [twosigma/beakerx#4089]
Under Mac OS X, using shell commands within the ipython cell results in improperly colored output. Characters are shown instead of the proper colors. Below is an example with using the `ls` command.

<img width="715" alt="screen shot 2016-05-09 at 7 49 29 pm" src="https://cloud.githubusercontent.com/assets/1335855/15134318/d88f8c70-161f-11e6-9849-879f45a09adc.png">

**Comment by scottdraves** [comment]
thanks for the bug report
