### ISSUE TITLE
The table displayed by pandas::DataFrame::sort_value() method is not sorted by the specified column

### ISSUE THREAD

**Issue by wllmtrng** [twosigma/beakerx#4095]
<img width="861" alt="screen shot 2016-05-11 at 7 49 37 am" src="https://cloud.githubusercontent.com/assets/1335855/15185254/37d2db28-174d-11e6-9b93-13d622cfd80d.png">

In the image, the second table shown should be sorted by column 'A'.

```
>>> import pandas as pd
>>> import numpy as np
>>> df = pd.DataFrame(np.array([[2, 3, 4], [1, 1, 1], [4, 1, 0]]), columns=['A', 'B', 'C'])
>>> df
   A  B  C
0  2  3  4
1  1  1  1
2  4  1  0
>>> df.sort_values('A')
   A  B  C
1  1  1  1
0  2  3  4
2  4  1  0
>>>
```

This bug is related to issue #2753

**Comment by scottdraves** [comment]
Thanks for the bug report.  I think the solution to both of these is in the ability to deliver formatting info to the client.  We are adding this now for JVM languages (https://github.com/twosigma/beaker-notebook/issues/3596), and it's the same idea to add it to the serializer for Pandas as well.

**Comment by dmtrius** [comment]
In core/src/main/web/outputdisplay/bko-tabledisplay/bko-tabledisplay.js we have 
`if (!scope.colorder) {
  scope.colorder = _.range(scope.columnNames.length + 1);
}
...
scope.refreshCells();
...
for (i = 1; i < $scope.columns.length; i++) {
  $scope.getCellIdx.push(i - 1);
  var order = $scope.colorder[i];
...
}`
That means that default ordering should be set and is set to sequence from 0 to columns count + 1.

Determine ordering by data is not possible - for this case we have `[[4, 1, 0], [2, 3, 4], [1, 1, 1]]` - server ordering and no hint by which column and direction.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/commit/41314c42db6d5e0f2894c8bbe81c6d7251395a46
