### ISSUE TITLE
Javascript Objects do not display well

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#412]
Beaker does not display objects well:
![screen shot 2014-07-28 at 11 03 03 am](https://cloud.githubusercontent.com/assets/963093/3722268/59c4078a-1668-11e4-9dd6-0446fd58020b.png)
Here's an example of the chrome console doing better:
![screen shot 2014-07-28 at 11 04 43 am](https://cloud.githubusercontent.com/assets/963093/3722296/952bd7b2-1668-11e4-910d-99bc999788c6.png)

**Comment by melmac48** [comment]
@scottdraves this would be very useful. Do you want to keep it? or I can assign to Sam for investigation.

**Comment by ildipo** [comment]
This has been fixed in the last serialization changes

**Comment by scottdraves** [comment]
only a first step of this problem.  try the following object:

```
var o = {a:{a:1}, b:2};
o;
```

**Comment by samccone** [comment]
We can look into using something like this
https://github.com/thejameskyle/pretty-format

**Comment by scottdraves** [comment]
what we really need is an interactive browser, so you can click open nested objects.
davide's changes do present a decent text.
