### ISSUE TITLE
Change Docker port

### ISSUE THREAD

**Issue by jhaski** [twosigma/beakerx#4126]
Is there support to change the Docker port from the default 8800? It appears that this port is hard-coded.

**Comment by scottdraves** [comment]
no but i believe you can base your own image on ours and change it.
why do you want to?

**Comment by jhaski** [comment]
I am running it on a Mesos cluster and I want to make sure that the port doesn't interfere with other apps. I see that there is an option for port-base to change the port.

I'm getting another error now (su: System error) but I'm not sure if this is connected.

**Comment by scottdraves** [comment]
hi LMK if this didn't get sorted...
