### ISSUE TITLE
Connecting beaker to existing ipython kernel

### ISSUE THREAD

**Issue by kozikow** [twosigma/beakerx#4143]
I need to be able to connect beaker to existing ipython kernel.

I explored the alternatives, and adding the "startup" ipython code in the default beaker notebook can't solve my problem.
Normally, you can start ipython by connecting to existing kernel like described in this post: http://stackoverflow.com/questions/31382405/ipython-notebook-how-to-connect-to-existing-kernel.

Is there a way of making beaker connect to an existing ipython kernel?

**Comment by kozikow** [comment]
I thought about programaticaly overriding the /home/rkoziko/.beaker/v1/config/beaker.pref.json to launch to newly launched kernel, but that sounds like a bad hack.

**Comment by scottdraves** [comment]
we don't have any support for this feature, like IPython the kernel is started from the client.
i am not opposed to it, but i am not aware of widespread demand either.
what would the UI look like?

**Comment by kozikow** [comment]
Our current use case is launching ipython from a GUI based tool. Based on the state of the GUI tool, the ipython session will have some variables added to the global scope.

You can connect to the existing kernel using command like: `ipython console --existing kernel-509.json`.
Are ipython sessions launched by "shell"?  If yes, then I imagine that being able to pass command line flags to ipython from the GUI could solve more problems than just this.

For future reference, end to end command line workflow for daemon/client:
In shell 1:

```
#!/usr/bin/env python
import os
from IPython.zmq.ipkernel import IPKernelApp

app = IPKernelApp.instance()
app.initialize([])
app.start()
```

This will print to stdout something like:

```
To connect another client to this kernel, use:
    --existing kernel-32504.json
```

Then in shell 2:

```
ipython console --existing kernel-32504.json
```

**Comment by scottdraves** [comment]
so you want to add a cmd line option here:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/ipythonPlugins/src/dist/python3/python3PluginStart.py#L21
?
is there any other way to get that config in?  could it be done with a magic?
