### ISSUE TITLE
Failure to save notebook

### ISSUE THREAD

**Issue by Bloodb0ne** [twosigma/beakerx#4144]
After installing and working with a notebook, and there are not output cells the notebook saves without a problem, but when i have at least one output ( like a python graphic ) it throws in an error.
Permission denied.

`
nginx-stderr>2016/05/22 15:47:08 [crit] 1094#0: *502 open() "/opt/Beaker/.beaker/v1/nginx5466317162625981430/client_temp/0000000381" failed (13: Permission denied), client: 192.168.1.123, server: , request: "POST /b7c81a9/beaker/rest/session-backup/backup/EAFi8l HTTP/1.1", host: "192.168.1.77:8801", referrer: "http://192.168.1.77:8801/beaker/"
`

I run it as a service using start-stop-daemon.
Something like this:
`
 start-stop-daemon --start --background --chuid root  --no-close --make-pidfile --pidfile $PID_FILE --exec $APP_PATH -- $ARGS
`

**Comment by scottdraves** [comment]
i would guess this is some kind of access problem with how start-stop-demon is running beaker, ie the user, umask, etc.  client_temp files are used by nginx when a transfer exceeds a certain size.

**Comment by Bloodb0ne** [comment]
Ok, i managed to fix it. So the issue was essentially that folder needed to be accessible by the `nginx` user account. Because the process used the current user for start-stop-daemon is not the same as the `nginx` user i had to change the directories in `/.beaker` to be owned by `www-data` with read/write permission.
