### ISSUE TITLE
Beaker LDAP integration

### ISSUE THREAD

**Issue by rkiq** [twosigma/beakerx#4147]
Would it be possible to create a server with LDAP integration?  Something similar to the functionality of JupyterHub https://jupyterhub.readthedocs.io/en/latest/  or .  The current cloud based environment won't work well for security-minded firms that need to keep all of their data on their own networks.  I have investigated the current Beaker password functionality and it is not an ideal solution in a multi-user environment.  If there already exists a solution that works, please point me in the correct direction, thank you.

**Comment by scottdraves** [comment]
solutions for this situation are under consideration, but a privately hosted version isn't likely soon.
we might be able to improve the password situation though.  what would work for you?
