### ISSUE TITLE
Implement file chooser state machine from the spec for control panel

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#415]
Unlike the file choosers in the mainapp (notebook app), some file chooser opened from the control panel (e.g. clicking the save button when closing an edited session from the existing sessions list) doesn't have the nice behavior as specified in #247.

The state machine:
https://www.lucidchart.com/documents/view/d2c35b6f-cbb6-48bd-be0d-80c86bb97a04/0

Another related issue is #370

**Comment by melmac48** [comment]
@bradicdesign we need to redesign our file menus - both the file menu and the file open and save dialog boxes

**Comment by bradicdesign** [comment]
@melmac48 Check out the mock in https://github.com/twosigma/beaker-notebook/issues/830
