### ISSUE TITLE
disabling password authentication

### ISSUE THREAD

**Issue by dberansky** [twosigma/beakerx#4152]
Is there a way to run Beaker without having to provide a password?

**Comment by scottdraves** [comment]
the cmd line option for this never got implemented but yea it's a good idea.
not sure if there already an issue for it, just this:
https://github.com/twosigma/beaker-notebook/blob/0a42d9718c583e5e69c39367910c66fd6f596717/core/src/main/java/com/twosigma/beaker/core/Main.java#L94

**Comment by mcdoyaji** [comment]
Hi @scottdraves  I see your comment and Main.java code. and try to give command options to Dockerfile inside running container like below.

```
###################
#       Run       #
###################

EXPOSE 8800
WORKDIR /home/beaker/src
CMD su -m beaker -c "export PATH=$PATH:/usr/sbin && /home/beaker/src/core/beaker.command --public-server --no-password --open-browser"
```

I saved it. and above contents still after restart docker container.

But, container still asks me password.

I'm stuck. and i need help.
