### ISSUE TITLE
CSS for print media

### ISSUE THREAD

**Issue by dberansky** [twosigma/beakerx#4153]
beakerApp.css has a stylesheet that removes background and color from all elements:

```
@media print {
  *,
  *:before,
  *:after {
    background: transparent !important;
    color: #000 !important;
    box-shadow: none !important;
    text-shadow: none !important;
  }
```

It shouldn't be doing this, as this is messing with generated content (reports) that I want to print in color and/or save as PDF.

**Comment by scottdraves** [comment]
can you be more specific about how you generate the content and what goes wrong?
ideally, publish your notebook and paste the link to it here.  then you just use the web browser's print function?

**Comment by dberansky** [comment]
For some reason I'm unable to activate the account for publishing.  But this is really easy to reproduce.  Here's content for an HTML cell:

```
<section id="report">
  <header>
    <h1>My Report</h1>
  </header>
</section>

<style>
   h1 {
     color: white;
     background-color: #90C3D4;
     padding: 10px;
     -webkit-print-color-adjust: exact;
   }
</style>

```

Do this in Chrome.  When this gets rendered, you should see "My Report" in white against blue background.  Now, hit Ctrl+P to print.  Select a color printer or 'Save to PDF".  At this point the blue background shouldn't be visible in the preview.  

Now, in `src/main/web/app/dist/beakerApp.css` find the rule I included in the description (should be around line 5786 and comment out `background-color` and `color` styles.  Save the file, reload the notebook and do print preview again.  This time around you should see the blue background in the preview.

**Comment by scottdraves** [comment]
here's how this HTML looks in Beaker and when printed:

![screen shot 2016-05-25 at 9 43 40 am](https://cloud.githubusercontent.com/assets/963093/15542189/b4a6142e-225d-11e6-985b-b8e50d655599.png)

<img width="625" alt="screen shot 2016-05-25 at 9 43 58 am" src="https://cloud.githubusercontent.com/assets/963093/15542190/b4ac29ea-225d-11e6-9688-a1a0e1c0bbe0.png">

**Comment by dberansky** [comment]
Yep, that's right.  Did the fix/workaround of removing the background color from the `@media print` rule work for you?

**Comment by scottdraves** [comment]
yes.  the problem is bootstrap has special styles for printing that do this.

i think just deleting _print.scss will do the trick.
