### ISSUE TITLE
stdout lines limited in length

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4167]
https://pub.beakernotebook.com/publications/a9b327be-2357-11e6-b118-dbb510980c7a
seems like they cut cut off at 240 chars

**Comment by scottdraves** [comment]
how/why is this happening?

**Comment by sshkalikov** [comment]
in com.twosigma.beaker.jvm.object.SimpleEvaluationObject methods doAppendOutput/doAppendError have code that inserts line breaks into lines with length > 240, here's the commit https://github.com/twosigma/beaker-notebook/commit/d6975b8d63af05885f395dd6733545aa0c192a18

should i delete this code?

**Comment by scottdraves** [comment]
leave it for now.  the IO sync is about to be redone anyway.
