### ISSUE TITLE
version control

### ISSUE THREAD

**Issue by dberansky** [twosigma/beakerx#4170]
This is a feature request somewhat related to #3548.  What I'd like to see is local integration with version control.  For Git, for example, if a notebook is stored in a local git repo, every save should result in a commit.  The UI should have an option for pushing local commits to the origin. And maybe a UI option to pull the latest commit from the origin.

**Comment by scottdraves** [comment]
Beaker Lab has version control.
And there are already a lot of nice git UIs.
So while this is possible I don't see it happening anytime soon in standalone Beaker.
Thanks for the suggestion.

**Comment by dberansky** [comment]
That's a shame because Beaker Lab isn't a viable solution to me because of corporate policies.  I'm sure many business users are in the same boat.
