### ISSUE TITLE
date weirdness

### ISSUE THREAD

**Issue by dberansky** [twosigma/beakerx#4172]
Any explanation for the following:

![image](https://cloud.githubusercontent.com/assets/290050/15621651/2a71a226-2417-11e6-86f8-af99db3ddeba.png)

**Comment by ildipo** [comment]
timezone different between server and client?
does it happen at any time or only at  specific time of the day? :-)

**Comment by dberansky** [comment]
what about this?

![image](https://cloud.githubusercontent.com/assets/290050/15621750/0f96f7de-2418-11e6-82f8-1e19161b5f51.png)

Does date formating in this case also happen on the client?

**Comment by ildipo** [comment]
it does when you return a datetime object (and that is a datetime object I think). Try `print today`

**Comment by dberansky** [comment]
I see.  Yeh, with `print` it's showing the expected date.

But the date object has no timezone associated with it.  Shouldn't whatever conversion happens on the client side assume local TZ?

**Comment by ildipo** [comment]
good question. seeing above it uses -07:00. Which timezone are you in?

**Comment by dberansky** [comment]
that's the right timezone, I think.  I'm in PDT

**Comment by ildipo** [comment]
we'll have to look at it. I mark this as a bug and someone will work on it after memorial day
