### ISSUE TITLE
Less.js support

### ISSUE THREAD

**Issue by dberansky** [twosigma/beakerx#4186]
Thoughts on less.js as a supported language?  I'm doing complex reporting on top of Beaker and having Less for CSS maintenance would be very helpful.

**Comment by scottdraves** [comment]
direct support for CSS as a language is already on the agenda: https://github.com/twosigma/beaker-notebook/issues/848
though we would probably opt for sass instead of less.
would also enforce a namespace so users don't restyle the application itself.
