### ISSUE TITLE
Removing unused evaluators from a notebook

### ISSUE THREAD

**Issue by eric-heiden** [twosigma/beakerx#4229]
Beaker tries to initialize languages that are not used by any code cell. This might confuse the user especially when beaker tries to load an unknown language and shows an error.
Instead, the user should get asked if that evaluator should be removed from the notebook.

**Comment by scottdraves** [comment]
maybe better to just dispense with the idea of a set number of available languages per notebook and just start all  backends lazily https://github.com/twosigma/beaker-notebook/issues/513 instead of when the notebook is opened.
