### ISSUE TITLE
lightning graphs break on publication

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4246]
when the DOM is copied back into the notebook model something is lost (maybe CSS), and the graphics overflow the cell output.  `pip install lightning-python` to run.
https://pub.beakernotebook.com/publications/7dea76aa-2e56-11e6-a13e-9f02b9707941

**Comment by sshkalikov** [comment]
Lightning output svg is wrapped with div, and this div has some css classes including class "push". We don't have this class in beaker css, but beaker lab has, and in beaker lab this class sets height to 166px, breaking layout
![](https://i.gyazo.com/30666825edf897554496ef214f24b991.png)
