### ISSUE TITLE
html cell with script tag blows up sharing

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#425]
make a notebook with an HTML cell with a script tag like this:
![screen shot 2014-07-30 at 5 54 32 pm](https://cloud.githubusercontent.com/assets/963093/3756989/376d360c-1834-11e4-94c4-b14545c15ccd.png)

and then share the notebook.  you get a result like this:
http://sharing.beakernotebook.com/gist/anonymous/0f2970e8247fdb8a1d3d
which looks like:
![screen shot 2014-07-30 at 5 56 10 pm](https://cloud.githubusercontent.com/assets/963093/3757010/6bcfc3a6-1834-11e4-9e2f-3d5c22570f80.png)

**Comment by anglee** [comment]
fixed by https://github.com/twosigma/beaker-sharing-server/commit/e720ef3b8e607d2aa1b7bd0311b9a566b345c339
