### ISSUE TITLE
improve emoji doc

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4258]
https://github.com/twosigma/beaker-notebook/pull/4251/commits/f2d6a27ae320634285c21c3961e33a74445d4bc6

should include windows.  idk about ubuntu, is this the only way? http://www.omgubuntu.co.uk/2016/02/emoji-picker-app-for-ubuntu-desktop

**Comment by mnavasiolava** [comment]
i've updated docs for windows. regarding linux, looks like EmojiOne picker you've mentioned is the best option for now
