### ISSUE TITLE
need a way for users to host JS

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#430]
see https://github.com/twosigma/beaker-notebook/issues/421

the user should not copy files deep into the app.
instead, they should configure the app to find the user's files.
ie there should be a JS loadpath and all directories in the path should be served by the core.

**Comment by scottdraves** [comment]
actually, i am not sure a JS loadpath is the only solution to this.
in particular, that would not work for sharing notebooks, or saving and loading elsewhere.
to handle that, the image would need to be stored in the notebook.
we already plan on supporting drag-n-drop of images into the notebook, but the plan was they would show up as a cell.  there could be a drop-target to just put them in the namespace, and then there could be a way to get them into a data URI for an img.

**Comment by scottdraves** [comment]
So whereas the native way of doing this is through the notebook namespace, users need to import code that refers to files using their regular APIs.  There is ample demand to provide files for beaker's internal web server.

Perhaps beaker.mapDirectoryToWeb(path, mountPoint) that maps a directory into the namespace of Beaker's web server?  Then your files get stored in a location that you make and manage,
and so you can generate the files there, and then you can refer to them in your html as "mymount/myfile.csv".

Perhaps Beaker should always just map "tmp" to ~/beaker/v1/nginxXXXX/web?
And the location of this directory is also made available by beaker.tmp().

This also brings up the cwd issue.  If it were always set to the location of the notebook itself,
then perhaps that directory could always be mapped from "notebook"?  then your python
code could write a file with a local name "xxxx" and you could refer to it in html as "notebook/xxxx",
no configuration required?  dangerous?

**Comment by scottdraves** [comment]
Unfortunately Java has very weak support for setting the CWD so I don't see how we can make it track the current notebook unless we use a different JVM for each notebook.  And using ~/.beaker/v1/nginxXXX/web means it would be different every time you run Beaker, which means you couldn't just throw some files in there and load them at your leisure.  That leaves beaker.mapDirectoryToWeb or a constant location like ~/.beaker/v1/web.  Or JVM/notebook...

**Comment by scottdraves** [comment]
We talked about this and came up with the following plan for v1.3:

1) when the rest of the dot files are created also create ~/.beaker/v1/web and use nginx to serve the contents of this directory from http://127.0.0.1:8801/user, hence in HTML in a notebook can say something like `<img src="/user/foo.png">` (absolute). Contents are managed by user.

2) with every session, create ~/.beaker/v1/nginxXXX/web/$sessionID and use nginx to serve its contents from http://127.0.0.1:8801/beaker/#/session/sWTIJo/notebook.  Then in a notebook you can say `<img src="notebook/foo.csv">` (relative) and to generate that file you need the absolute path to that directory which you can get with a new API `beaker.getWebPath()`.

**Comment by DiegoAlbertoTorres** [comment]
The plan's part 1 was implemented and has been merges. Part 2 is very tricky: My diego/430 branch already creates the per-session directories, and uses a cookie to tell nginx the session-id, so that nginx can route to the correct session temporary directory. However, cookies are not a reasonable solution, since multiple tabs on different sessions would fight for control of the cookie. The true solution is adding the session-id to the notebook's relative path (i.e. instead of /'hash'/beaker/notebook/, use /'hash'/'session-id'/beaker/notebook/)/

**Comment by scottdraves** [comment]
Part 2 will have to wait for v1.4

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/1371
