### ISSUE TITLE
Feature: Out of box Matlab and IDL support

### ISSUE THREAD

**Issue by guyest** [twosigma/beakerx#4305]
In my experience, which I don't think is unique in this case, the move to python within data science applications is marred by dependence on large code bases in other languages. Two of the most common ones I encounter in physics are Matlab and IDL. Both Mathworks (for Matlab) and Exelis (for IDL) have official support for a Jupyter kernel for their respective languages. Out of box support for these languages would, I think, lead to broad adoption of this tool within the physics community. I know for my part it has already become my primary tool and adding both IDL and Matlab as a new language is my main priority, but not everyone would be so willing to clear that hurdle. 

What is the feasibility of this?

**Comment by scottdraves** [comment]
Hi, thanks for the suggestion. Matlab is feasible.  I don't know IDL, so I can't say.  We would be thrilled if Mathworks did a Beaker plugin.  It's probably not hard to import the code to Beaker, as we have done that for a few languages already (Python, Julia, Ruby).  But a native version would be better, perhaps and would take more effort.  I don't have Matlab expertise myself and we don't have the staff to develop it unfortunately.

**Comment by scottdraves** [comment]
related https://github.com/twosigma/beaker-notebook/issues/3208
https://anneurai.net/2015/11/12/matlab-based-ipython-notebooks/
https://www.harrisgeospatial.com/docs/IDL_Kernel.html

**Comment by scottdraves** [comment]
https://anneurai.net/2015/11/12/matlab-based-ipython-notebooks/

**Comment by scottdraves** [comment]
https://www.harrisgeospatial.com/docs/IDL_Kernel.html

**Comment by guyest** [comment]
I see. I gave the procedure for adding a new language a quick passover and it looked to me like the main implementation barrier is the layer which translates between types originating from either language. Does that seem accurate?

In that case, apart from laying out the proper json metadata, the native language modules to provide the bridge need to be brought into the proper format for Beaker. This has indeed been demonstrated as feasible in relation to Python and is officially supported by the IDL (http://www.harrisgeospatial.com/docs/python.html) and Matlab (http://www.mathworks.com/help/matlab/matlab-engine-for-python.html?searchHighlight=python) maintainers in addition to several open source implementations that preceded them. 

Each language also has an official Jupyter kernel that I have easily installed on OSX for Matlab and with a lot more effort for IDL. I had originally thought that this meant the job was mostly done but it seems this may be off base. Depending on if it is within my capacity and I could find the time, this is something I may  consider taking on if I knew what the next steps were.

**Comment by scottdraves** [comment]
Here is the guide for doing it like that: https://github.com/twosigma/beaker-notebook/wiki/Importing-Plugins-from-IPython
it has been partly automated since https://github.com/twosigma/beaker-notebook/issues/3707
