### ISSUE TITLE
Rename pluginmanager-directive.js

### ISSUE THREAD

**Issue by eric-heiden** [twosigma/beakerx#4316]
The file "core/src/main/web/app/mainapp/components/pluginmanager/pluginmanager-directive.js" implements a controller and should be renamed ("pluginmanager.js"?).

**Comment by scottdraves** [comment]
and pluginmanager.js is empty!

**Comment by dmtrius** [comment]
It seems like content of pluginmanager-directive.js should be copied to pluginmanager.js and pluginmanager-directive.js should be deleted. Also core/src/main/web/app/template/index_template.html should be updated to proper path to js.
There is launcher/mac/Beaker.xcodeproj/project.pbxproj that has pluginmanager references. What about them?

**Comment by scottdraves** [comment]
sounds good, please proceed.

don't worry about launcher/mac.
