### ISSUE TITLE
leaving large text cell to code cell jumps

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4335]
if you are editing a tall text cell, and then click on a code cell below it to edit it, the notebook jumps under the mouse and you have to click again to get to where you want to.

possible solution: text cells don't immediately automatically render, instead you have to it control-enter or click the little run button.  maybe later at idle, it can format automatically with a vanishing animation to make it smooth.  also, since their state is not stored in the notebook model, when the notebook is opened, they will all be formatted.  that may suffice.

**Comment by djaddison** [comment]
The solution seems reasonable. Other solutions could be: 
1. make text cells function exactly like code cells. With a markup input and the formatted text in the output cell.
2. Offset the cell to keep location
   - when a user clicks away from the text editor
   - track the clicked cell before the text renders
   - calculate the difference in the text editor vs rendered text
   - scroll the screen to keep the clicked cell in the same location

**Comment by scottdraves** [comment]
Thanks Dave. Will think this over and collect more data.
