### ISSUE TITLE
keybindings to raise and lower section heading level

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4338]
cmd-shift < and >

and maybe cmd-shift 1-4 to insert-after

help page too.

**Comment by mnavasiolava** [comment]
cmd-shift 3-4 are used for taking screenshots on Mac, so we need other shortcuts to insert after.
maybe ctrl/alt 1-4?

**Comment by scottdraves** [comment]
raise and lower done, still need insert-after.
cmd-option (on mac)  sounds good (ctrl-alt on PC).

**Comment by sluhtoja** [comment]
cmd-n opens a tab with the specified index. Example, you have 3 tabs open, you click cmd-2, second tab opens. Browsers tried: Safari, Chrome.  Is ctrl/cmd-alt-n acceptable?

n is the section number.

**Comment by scottdraves** [comment]
yes
