### ISSUE TITLE
gradle bowerInstall

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4346]
results in

```
CONFLICT Unable to find suitable version for jquery
```

**Comment by mnavasiolava** [comment]
i can't see the problem with jquery version. but there is a problem with "angular-route",  "angular-animate",  "angular-touch", "angular-mocks" which require angular 1.5.0 version while we have angular 1.5.5. after increasing their version `gradle bowerInstall` works fine for me
