### ISSUE TITLE
research phantom for pdf printing

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4363]
https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/4348 https://github.com/twosigma/beaker-notebook/issues/4347

**Comment by sshkalikov** [comment]
It's showing best results so far)
https://dl.dropboxusercontent.com/u/9241337/phantomjs/topLavelTutorial.pdf
https://dl.dropboxusercontent.com/u/9241337/phantomjs/categoryPlot1.pdf
