### ISSUE TITLE
Persist 'View' state

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#437]
Ideally,
the 'Advanced Mode' state should be persisted at the user pref level.
the 'Show Hierarchy' state should be persisted at the session level.

for V1, if we don't have time for this, it is ok to persist both at either level.

![pasted_image_8_6_14__4_31_pm](https://cloud.githubusercontent.com/assets/1767921/3833589/02816754-1da9-11e4-83af-77b91cd8a0e0.png)

**Comment by scottdraves** [comment]
really need advanced mode at user pref level please!

**Comment by anglee** [comment]
Fixing the adv mode part, create https://github.com/twosigma/beaker-notebook/issues/613 for the show hierarchy part
