### ISSUE TITLE
Bioconductor R packages can't be installed

### ISSUE THREAD

**Issue by redmode** [twosigma/beakerx#4382]
Bioconductor R packages can't be installed. For instance:

```
source("https://bioconductor.org/biocLite.R")
biocLite("RBGL")
```

Returns error:

```
Error in get(".BioC_version_associated_with_R_version", envir = asNamespace("tools"),  :
unused arguments (envir = asNamespace("tools"), inherits = FALSE)
```

**Comment by scottdraves** [comment]
thanks for the report, yup i get this too.

**Comment by HarlanH** [comment]
I think this is an issue if you've loaded a package that overloads `base::get`. Solution is to do this step before loading that package. (And BioC should fully qualify their call to `get`!)
