### ISSUE TITLE
Resources for published notebooks are not imported back to Beaker Lab

### ISSUE THREAD

**Issue by redmode** [twosigma/beakerx#4383]
For published notebooks it's possible to open them in Beaker Lab for edit. 

But in this case resources (like images or other files) are not imported back. So, it's impossible to reproduce the notebook in edit mode. 

However indirect way is possible: save images from published notebook and add them manually.

For instance, open in Beaker Lab this unlisted published notebook:
https://lab.beakernotebook.com/publications/02f7e8ae-3fc9-11e6-9eef-078c16a175ab?fullscreen=false

Demo image 'demo_image.png' is not imported.

**Comment by ildipo** [comment]
Thanks for the report.
This is the correct behavior for the currently released solution.
We are about to release version 1.0 which will allow you to publish files from your project space together with the notebook and to get them back when you open it in beaker lab.
