### ISSUE TITLE
Interactive JavaScript cells are not working for published notebooks

### ISSUE THREAD

**Issue by redmode** [twosigma/beakerx#4384]
Interactive JavaScript cells are not working for published notebooks. For instance, this notebook: https://lab.beakernotebook.com/publications/46ef630a-319d-11e6-a9b0-dfed9035ff33?fullscreen=false

If opened in Beaker Lab interactive JS cell will be working.

**Comment by scottdraves** [comment]
to run the cells, open the notebook in beaker lab (or download it and use a standalone beaker).
this is working as intended.

**Comment by redmode** [comment]
Aren't they should work in published version?
If no, this is not issue, of course.

**Comment by scottdraves** [comment]
to run code you need to open the notebook.
