### ISSUE TITLE
How to publish evaluation result into redis (R interpreter for example)

### ISSUE THREAD

**Issue by nguyenxuantuong** [twosigma/beakerx#4388]
Hi,

I am trying to get a better understanding about beaker. I was implementing a R-interpreter which basically receive a "code" to evaluate and publish beaker-compatible object into redis (for example)(My user case is a bit different). For now beaker comes with a R-server plugin. The current flow is:
1. Client send a request to /rest/rsh/getShell -> it will start Rserver and create a worker poll.
2. Client then send a request to /rest/rsh/evaluate -> it will push a 'evaluation' job into worker queue and return a "update-id" for getting result later.
3. When worker job is done; it call SimpleEvaluationObject.finished() -> which notify changes for any observers. Then cometd will register the changes and somehow push result (JSON format of SimpleEvaluationObject) into JS client cometd callback.

I couldn't able to understand step3 (how the observer is implemented observe the finished() event and to serialize data + send back to client once job finish).

In my case, I want to implement some thing simpler which simply push all R-evaluation result into redis channel instead. That way, i have more freedom to use another websocket / non-java library. I know that my user case is not common but it would be very helpful if you can explain to me how to do this?

The simpleEvaluationObject implement a Serliazer which using @Inject UpdateManager and BeakerObjectConverter. If i want to get a Json stringify of the SimpleEvaluationObject, is there a good way to do this?

Thanks you so much for your help. I would really want to contribute effort for beaker but for now the code base is big and i am still trying to understand it bit by bit. Some code snippet is appreciated.

**Comment by scottdraves** [comment]
Hi thanks for your question.  Not sure what you are really looking for but here is where we get the result back from R:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/r/src/main/java/com/twosigma/beaker/r/utils/RServerEvaluator.java#L524

you could put the result into redis there, if I understand you correctly.
