### ISSUE TITLE
Scrollbar in cell output?

### ISSUE THREAD

**Issue by alexeymorgunov** [twosigma/beakerx#4398]
Does this exist and I just haven't figured out how to enable it? `beaker.prefs.outputLineLimit = N` sets the number of lines, which is useful, but if the output is very long and I want to be able to see all of it on screen rather than just the last N lines, at the moment the only available options are either show all the output or toggle to hide it all. The former is not always convenient when switching attention between various cells. Jupyter notebooks, for example, allow scrolling through the output of the cell. Does this exist for Beaker?

**Comment by scottdraves** [comment]
Hi Alexey we don't have this feature, sorry.  Instead you can just set the limit very large, and then use the hide/show toggle to control either using the main scrollbar for the output, or for the rest of the notebook.  I know this isn't ideal but I am not a big fan of nested scrollbars either.  I think eventually we will probably adopt them but not until after the notebook model has been moved to the server https://github.com/twosigma/beaker-notebook/issues/2835 so large amounts of text can be streamed to the client as needed (ditto for tables and plots).

**Comment by alexeymorgunov** [comment]
I see, thanks for the clarification!
