### ISSUE TITLE
conda package manager

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4399]
users need to manage packages, and we need to verify that the packages that we require are installed.

this is the next instance of https://github.com/twosigma/beaker-notebook/issues/1350

depends on https://github.com/twosigma/beaker-notebook/issues/4395

questions: are dependencies in the language manager (and hence per notebook)?  we use the conda version specs right?  how do multiple notebooks with different specs run at the same time?  how does this work with lab where there is a readonly virtualenv with many packages, can additions to that be stored locally?

**Comment by scottdraves** [comment]
the abstraction provided by conda is the virtualenv. our MVP should just expose this.
create/name/delete/addlib/removelib, with autocomplete.  this would be a java wrapper around the std conda API (https://github.com/conda/conda-api), exposing it to a dialog on the front end.  A menu item "Package Manager", right under Language Manager in the Notebook menu.

a future version can relate the virtual envs to notebooks perhaps via package dependencies in the notebooks.

another future version can have a Tab for R with a similar UI.

**Comment by leifwalsh** [comment]
> are dependencies in the language manager (and hence per notebook)?

When you say "dependencies" do you just mean conda dependencies, or does Beaker define this word too?

> how do multiple notebooks with different specs run at the same time?

You need separate processes for each notebook, I'm not sure what the Beaker noun here is but it jupyter it's "kernel".  Once the conda env is created, running the python binary inside it will automatically have the right PYTHONPATH and stuff.
- Sidenote, I think managing the lifetimes of conda envs is probably an interesting/hard problem here, especially in Lab.  You don't want to have conda compute the dependency resolution during startup each time, it can be quite slow.  So you want to cache envs.  But, they should expire at some point, probably, and you need a mechanism for users to update them.

> the abstraction provided by conda is the virtualenv. our MVP should just expose this.

When you say "virtualenv", do you mean [virtualenv the product](https://virtualenv.pypa.io/en/stable/installation/) or the abstract concept which conda mimics?  Conda envs are similar to [virtualenv the product](https://virtualenv.pypa.io/en/stable/installation/) environments, but not exactly the same.

> std conda API (https://github.com/conda/conda-api)

Protip, `conda_api` is kind of weak from an API standpoint, it's a relatively thin and incomplete wrapper around shelling out to the `conda` binary and parsing the results.  You would probably do better to interact with the `conda` binary yourself, as `conda_api` doesn't add much and might introduce its own idiosyncracies.

> this would be a java wrapper around the std conda

I think this approach makes sense, for python/conda at least.  Expose a list of envs, with the ability to show the packages and versions in one, update all packages in one, add/remove packages from one, delete an env, and create new env.

**Comment by leifwalsh** [comment]
One feature request I'd add, and this shouldn't be in the first milestone, is "clone an existing env with additional packages added".  I have seen conda sort of corrupt envs by adding new packages after creation, I prefer to treat my envs as immutable and I think encouraging that behavior will be helpful.  One issue with that is that in order to do it, you need to know more than conda stores about the env (it only knows the currently installed packages): you need the user's original creation intent for an env, if you want to clone it and add some stuff.  That is, if I create an env with `conda create -n myenv python numpy pandas` and then realize I forgot sklearn, I'd rather run `conda create -n myenv2 python numpy pandas scikit-learn` than `conda install -n myenv scikit-learn`.
