### ISSUE TITLE
empty plot cannot be panned

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4418]
create an empty plot with:

```
new Plot()
```

then click and drag on it.  it should pan.

**Comment by samdbrice** [comment]
Is this a fix to be implemented in the code-cell? or somewhere in the Angular code?

**Comment by scottdraves** [comment]
somewhere in here: https://github.com/twosigma/beaker-notebook/tree/master/core/src/main/web/outputdisplay/bko-plot
