### ISSUE TITLE
Show language plugin indicator on code cells in 'Advanced mode' 

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#443]
In Advanced mode, right now there is no easy way to tell which language was used for a particular code cell.

**Comment by samccone** [comment]
@melmac48 @anglee @scottdraves is there a priority label for this?

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/599
https://github.com/twosigma/beaker-notebook/issues/601
