### ISSUE TITLE
Virtual environments

### ISSUE THREAD

**Issue by datascienceit** [twosigma/beakerx#4434]
I would like to have a way to connect to a virtual environment, using pip workarounds is not comfortable.
It will also have all the virtual environment pros, and make it easier to export my old project to beaker.

Cheers

**Comment by scottdraves** [comment]
Do you mean Beaker that you download? Or Beaker lab?

**Comment by datascienceit** [comment]
Downloaded,mac osx.

**Comment by scottdraves** [comment]
You can put a path to any virtualenv into your beaker prefs: https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences
