### ISSUE TITLE
Define the behavior of 'empty' and 'hidden' output

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#444]
Right now, with the first batch of implementation of the new design, when an evaluator returns (sets output.result) to "" (i.e. empty string), the output cell is hidden, this can be confusing to users by making them think the evaluation didn't take place. we should offer an explicit flag for programmatically hiding output (e.g. OutputCell.HIDDEN) and display empty strings as `""` by default.

**Comment by anglee** [comment]
Note that if you want to reproduce this, try the Groovy plugin. (The IPython plugins currently returns HTML code for empty string).

**Comment by scottdraves** [comment]
yea something like that.

**Comment by scottdraves** [comment]
Similarly, if a groovy cell evaluates to 0, the output is hidden.

**Comment by scottdraves** [comment]
Before we create something like OutputCell.HIDDEN, can we just return this to its previous behavior?
Didn't it work before the new UI?

**Comment by melmac48** [comment]
this requires some design decisions, punting to v2

**Comment by pburka** [comment]
It's not just 0 or empty results. Groovy output is also suppressed for any case variation of the string "False" (e.g. "FaLsE").

**Comment by scottdraves** [comment]
i think we should consider returning to old-UI behavior for 1.1

**Comment by scottdraves** [comment]
confirmed v0.55 does not have this problem.

**Comment by scottdraves** [comment]
this is the problem: https://github.com/twosigma/beaker-notebook/commit/dc7f137baadca783cbc7668bb3b8a917343adb02

**Comment by scottdraves** [comment]
note that a python cell like

```
x = 1
```

now has a visible empty output, as does a completely empty input cell.  to get a truly invisible output we would need OutputCell.HIDDEN as described above.

**Comment by samccone** [comment]
`OutputCell.HIDDEN` Makes a ton of sense, and will mean that we are way less dependent on the actual output of cells, which will make it much more explicit.
