### ISSUE TITLE
Java: Imports and variables not evaluated in subsequent cells:

### ISSUE THREAD

**Issue by jarmoni** [twosigma/beakerx#4444]
I tried the following:
- cell 1:

```
import java.io.File;
String s = "hello";
```
- cell 2:

```
System.out.println(new File("/tmp/xyz").exists());
System.out.println(s);
```

When I run cell 2 I get:

```
error at line 1: cannot find symbol
  symbol:   class File
  location: class com.twosigma.beaker.javash.bkrfd4175be.BeakerWrapperClass1261714175
 System.out.println(new File("/tmp/xyz").exists())
                        ^   ^                       

error at line 2: cannot find symbol
  symbol:   variable s
  location: class com.twosigma.beaker.javash.bkrfd4175be.BeakerWrapperClass1261714175
 System.out.println(s)
```

So it seems that when writing Java-Code any import and variable-declaration only has effect in the current cell. In other languages (Python, JScript, Groovy,...)  everything works fine...

**Comment by scottdraves** [comment]
I think this is just the nature of Java.  It's not a scripting language, so it does not accumulate state the same way.  someday java9 will give us a REPL https://github.com/twosigma/beaker-notebook/issues/3585
