### ISSUE TITLE
preload file dialog

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4472]
if you have a large home directory or a slow file system, then the file dialog takes a long time to open up since it stats every file.  after that it loads quickly because of caching (i am not sure if it's cached in the JVM or just by the filesystem).  since it is likely users will click "open", we can improve their experience by warming up the cache when the application starts.  a background thread should be used so as not to slow it down in general.

**Comment by dmtrius** [comment]
There is path2hash() function in core/src/main/web/app/helpers/helper.js. It has

`while(!_cached_(hash)){ ... hashes.push(hash); }`

so caching is done at client level.
We could do elfinder.path2hash(path) in init.

**Comment by dmtrius** [comment]
Server side:
`com/twosigma/beaker/core/module/elfinder/impl/commands/OpenCommand::execute()
Map<String, FsItemEx> files = new LinkedHashMap<>();
...
`

**Comment by scottdraves** [comment]
this is the spinner that i am trying to avoid.  sometimes i get it as long as a minute!
![elfinder-open-folder-spinner](https://cloud.githubusercontent.com/assets/963093/16927447/69a81d28-4cfb-11e6-97b3-5878fab3fb21.PNG)
will be diving into your above comments next.

**Comment by scottdraves** [comment]
there does not appear to be a cache in the client or the server, so it's relying on the filesystem.
that makes this issue easy, in the elfinder module after it finishes with its current initialization it should simulate an "open" call from the client.  that way the server's filesystem cache will be warmed up for when the user issues this command.

**Comment by scottdraves** [comment]
still needs to stat every file.

**Comment by scottdraves** [comment]
still needs to run in a spawned off thread.

**Comment by scottdraves** [comment]
the fixes merged above do not seem to really solve the problem.
maybe it improves the situation.... but maybe not.
i have seen some 10s delays iwth the "Open folder" spinner dialog, even with this cache warming thread.  I can see the thread does its work in just a fraction of a second when the application starts.
So far I have not seen a really long pause, like a minute, but that was always pretty rare, so I am not convinced this change has done much.

I would like to know more about what really happens during that "open" rest call.

**Comment by scottdraves** [comment]
OK I did some debugging.  The problem is it reads a lot more than just the home directory.
Not only does it stat every file, but it opens up every directory and lists the contents.
https://github.com/twosigma/beaker-notebook/blob/fd361dace6c374bd420ded9c7a8a1955b3fbfcc6/core/src/main/java/com/twosigma/beaker/core/module/elfinder/impl/AbstractCommand.java#L143

Try to mimic this behavior in the warm-up thread.
