### ISSUE TITLE
Need easier way to tell if a cell is 'initialization cell' in new UI design

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#448]
Right now, one can click to open the cell menu and see if the 'initialization cell' item is checked or not. In the previous version of the UI, one can tell by the cell bracket color.
before
![image](https://cloud.githubusercontent.com/assets/1767921/3891367/474d9036-2229-11e4-838f-9094a32d8f5f.png)
after
![image](https://cloud.githubusercontent.com/assets/1767921/3891374/546f56a0-2229-11e4-9416-ebafd92db75d.png)

**Comment by jchendy** [comment]
I'm not sure if y'all modified the design on purpose, but that was the intent of the I/O button in the bottom right corner on cells in the original design:

![bkinit](https://cloud.githubusercontent.com/assets/1740497/3891464/42224920-222a-11e4-8106-91bb894d790b.PNG)

**Comment by anglee** [comment]
Ah, thanks for pointing it out, @jchendy! I didn't see that I/O button in the current implementation. @samccone, was this implemented or I missed something?

**Comment by samccone** [comment]
It was not implemented, I think it must have been lost in one of the design iterations. 

currently you can tell if a cell is ready based on the fact that there is no spinner in the top right menu of each cell.

Perhaps that is not enough.

**Comment by anglee** [comment]
A cell being ready and being an 'initialization cell' are different ideas. 'Initialization cell' is a tag that one can use to tag a cell. The cells that are tagged as "initialization cell" will be evaluate upon notebook open.

**Comment by melmac48** [comment]
agreed, this was part of the initial design, we should add it back in. @samccone  please check with Ang if you need further clarification on how to identify an cell which is marked to run on open.

**Comment by scottdraves** [comment]
in addition, would be nice to show tags more clearly than in the options dialog.
i am thinking small gray text just above the cell box, on the right, maybe with some UI for adding and removing.

**Comment by scottdraves** [comment]
still need:
1) if the code is hidden, then show this indicator in the summary of the code, to the right of the number of lines.
2) if you click on the indicator, bring up a menu with one item that says "disable initialization"
