### ISSUE TITLE
big tables start out in preview?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4486]
with just one page of results, as a simple html/css table (default style would mimic the interactive version).
the column formatting JS has to run to get it to look right.
but the result is non-interactive -- except if you click, then the regular table appears.

**Comment by scottdraves** [comment]
question: does this improve performance?
trial can be just showing all tables like this.

**Comment by scottdraves** [comment]
results of testing are that tables with many columns still crash the client.
so, if there are more than 30 columns, truncate to 30 and show a final column
with header "..." and all cell contents "..."

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/tree/sergey/4486

**Comment by scottdraves** [comment]
```
import pandas as pd
import numpy as np
pd.DataFrame(np.random.randn(1000, 1000))
```

this code produces no result.

**Comment by sluhtoja** [comment]
working until pd.DataFrame(np.random.randn(600, 600)) sometimes a bit higher even. If the value is greater and is not showing a code output, it doesn't even get the preview table. Is not related to this issue.
