### ISSUE TITLE
cell button menu aligned too low

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#449]
there is whitespace above it, and it runs into stuff below it.  should be moved up.

![screen shot 2014-08-12 at 11 19 31 am](https://cloud.githubusercontent.com/assets/963093/3892753/a2ff37a8-2234-11e4-8da5-1752c3a9676a.png)

**Comment by samccone** [comment]
@scottdraves what kind of cell is this?

**Comment by scottdraves** [comment]
that's a markdown cell in the tutorial but all cells have this problem.

**Comment by scottdraves** [comment]
here's an html cell where the misalignment is pretty clear.
![screen shot 2014-08-12 at 11 44 32 am](https://cloud.githubusercontent.com/assets/963093/3893090/ecb89440-2237-11e4-9e7c-91a08c16a284.png)

**Comment by samccone** [comment]
@scottdraves can you try in an incognito window with a clear cache. I think the html templates are biting you here

**Comment by scottdraves** [comment]
same result, let me see if the others can repro

**Comment by samccone** [comment]
ah i see it on the top part of the cell for html now, I just do not see the first case that you posted
