### ISSUE TITLE
KDB 64-bit version is not detected on Windows

### ISSUE THREAD

**Issue by andylynch** [twosigma/beakerx#4518]
(related to #3371 ) - attempting to use the 64-bit  version of KDB on Windows results in a NullPointerException.  

```
Kdb-stderr>[qtp1259769769-20] WARN org.eclipse.jetty.servlet.ServletHandler - /rest/kdb/evaluate
Kdb-stderr>java.lang.NullPointerException
Kdb-stderr>     at com.twosigma.beaker.kdb.KdbShell.evaluate(KdbShell.java:82)
Kdb-stderr>     at com.twosigma.beaker.kdb.rest.KdbRest.evaluate(KdbRest.java:100)
```

Similarly to MacOS,  w64/q.exe  should be  added to the list of binaries to search for in `KdbProcess.java`

**Comment by scottdraves** [comment]
thx for the report, will check that out.

**Comment by scottdraves** [comment]
Hi Andy it looks like this was added in January:
https://github.com/twosigma/beaker-notebook/commit/ab9418d24636bf1ab7ce65bc20317b7728920a02

What version of Beaker are you running?
