### ISSUE TITLE
tab heading text badly rendered in ffox 

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4523]
chrome is clear:
![screen shot 2016-07-19 at 11 33 23 am](https://cloud.githubusercontent.com/assets/963093/16956020/c968b228-4da4-11e6-9f8b-c955a03c6f99.png)
firefox is too bold:
![screen shot 2016-07-19 at 11 33 43 am](https://cloud.githubusercontent.com/assets/963093/16956021/c96951d8-4da4-11e6-9059-a40a6f089592.png)

both are too small, text should be at least as large as the body text.

**Comment by scottdraves** [comment]
in this repo: https://github.com/twosigma/beaker-notebook-www

**Comment by sluhtoja** [comment]
body text is size 18px if I set it as big, "getting started" tab will be on two lines.

how it is in chrome and firefox:

![image](https://cloud.githubusercontent.com/assets/19967713/17328575/11fc6d90-58c7-11e6-8f02-dc9a50342649.png)

Chrome is on top.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/commit/fee4a018125dad6aa369672dc88dfa53c8192e06
