### ISSUE TITLE
`Failed to start Python3.` Python3 installed with anaconda.  No Python2 or virtualenv

### ISSUE THREAD

**Issue by jolespin** [twosigma/beakerx#4524]
Tried following this but I don't have virtualenvs since I only installed Python3 (made the big shift from 2): https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences

Tried this help but he also has virtualenvs setup: 
https://github.com/twosigma/beaker-notebook/issues/1435

Here's my Python3 path:

```
$ which python
/Users/jespinoz/anaconda/bin/python
$ python --version
Python 3.5.2 :: Anaconda custom (x86_64)
```

R is installed with anaconda as well... 

Here's my config file with my R path and Python(3) path:
`$cat /Users/jespinoz/.beaker/v1/config/beaker.pref.json` 

```
{
"languages" : {

    "Python3" : {
        "path" : "/Users/jespinoz/anaconda/bin"
    },
    "R" : {
        "path" : "/Users/jespinoz/anaconda/bin"
    }
},
  "autocomplete-parameters" : "true",
  "pref-format" : "1",
  "edit-mode" : "default",
}
```

Here's the error I get when I try to start Beaker:

```
Language Error
Failed to start Python3.

Did you install it according to the instructions on BeakerNotebook.com?

If you already have it, then edit your preferences file to help Beaker find it on your system, and then restart Beaker and try again.

Any other languages in your notebook should still work.
```

**Comment by jolespin** [comment]
Reinstalled anaconda and it worked

**Comment by scottdraves** [comment]
thx for the followup
