### ISSUE TITLE
markdown cells too large in display mode and change size vertically

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#454]
when in display mode, markdown cells have extra vertical space below the text.  there is too much even when editing.

![screen shot 2014-08-12 at 12 42 26 pm](https://cloud.githubusercontent.com/assets/963093/3894106/13d9e688-2241-11e4-8b34-95c99b7c68e1.png)
![screen shot 2014-08-12 at 12 43 06 pm](https://cloud.githubusercontent.com/assets/963093/3894107/13dedb34-2241-11e4-9cce-c7095b386cf4.png)

**Comment by samccone** [comment]
Yep, it is really strange thing with epic editor that happens :( I will look into how to fix it tho

**Comment by scottdraves** [comment]
possibly use new markdown lib.
syntax highlighting would be good tool.
