### ISSUE TITLE
Freezing/crashing when displaying table with many columns

### ISSUE THREAD

**Issue by jolespin** [twosigma/beakerx#4548]
![screen shot 2016-07-22 at 10 15 15 am](https://cloud.githubusercontent.com/assets/9061708/17065564/5c30cb1e-4ff7-11e6-810d-b65f30e206cf.png)

When I load my DataFrame, (not terribly large [20, ~18k]) it loads perfectly fine but when I try to view it, my Beaker server crashes every time.  It works in Jupyter so I don't believe it's anything going on with the DataFrame.  Any ideas on how I could get around this?

**Comment by scottdraves** [comment]
Hi thanks for the report.  Taking just the head should be no problem as far as size goes.
Is there any kind of stack trace from the application?
What platform are you on and how are you running Beaker?
If I could get a copy of the tsv file, I would be happy to try to reproduce and debug.

**Comment by jolespin** [comment]
Here's the dataframe, it's tab separated and indexed by string values not numbers

[gex.tsv.zip](https://github.com/twosigma/beaker-notebook/files/379191/gex.tsv.zip)

I put it up here too. 
https://drive.google.com/file/d/0Bx2FlTJ8g3XRNFU1RE1xNDEzVDg/view?usp=sharing

Lol, it's such a tease right now.  I finally need to start using `R` (I've been avoiding it) for some packages but I do all my preprocessing in `Python`.  Can't wait to get Beaker working again.

**Comment by jolespin** [comment]
My beaker is `Version 1.6 (1)`

My Mac is `MacBook Pro (Retina, Mid 2012)` and `El Capitan 10.11.5`

**Comment by scottdraves** [comment]
thx, i will check it when i get back into town on monday.

**Comment by jolespin** [comment]
I can try to debug it as well.  Any ideas on what could make it freeze everytime?

**Comment by scottdraves** [comment]
wow that does crash hard, have to use chrome's task manager to exit, debug tools also crashed.
i would guess it is in https://github.com/twosigma/beaker-notebook/tree/master/core/src/main/web/outputdisplay/bko-tabledisplay
perhaps there is a bad datum or column, you could simplifying the input to find the trigger.
thanks again.

**Comment by jolespin** [comment]
Thanks for checking that out scott, I'm wondering if the size is breaking the DF viewer?

**Comment by scottdraves** [comment]
wow, looks like that table has 18926 columns.
yea can't handle that many.
https://github.com/twosigma/beaker-notebook/issues/4486 will handle this but not sure when it will be done and released.
in the meantime, try this:

```
DF_raw.head().transpose()
```

big but manageable.

**Comment by jolespin** [comment]
Do you guys do `beta-builds` w/ prototype versions?
