### ISSUE TITLE
Theme Editor

### ISSUE THREAD

**Issue by drJAGartner** [twosigma/beakerx#4549]
The default Ambient Theme has black text on dark background.  Allowing users to edit themes would completely solve any such issues.
![screen shot 2016-07-22 at 1 18 25 pm](https://cloud.githubusercontent.com/assets/7129327/17066900/cccc9e04-500e-11e6-9218-14f1bea2ac63.png)

**Comment by scottdraves** [comment]
it should look like this:
![screen shot 2016-07-22 at 2 21 16 pm](https://cloud.githubusercontent.com/assets/963093/17066989/9da9f7f8-5017-11e6-9cb0-985383ae16e0.png)
if it doesn't then something else has gone wrong.
try reloading the page, and looking in the JS console for errors.
