### ISSUE TITLE
no way to insert a cell before the first cell

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#455]
there is no handy blue insert button up there.
but strangely, i can get two at the bottom...

**Comment by samccone** [comment]
@scottdraves there was no design for this but I agree it seems like we do need this. Lub any thoughts?

**Comment by melmac48** [comment]
we should do this.

**Comment by scottdraves** [comment]
maybe get rid of final big insert cell button too.

all insert buttons should be the same size and there should be no dups.

related https://github.com/twosigma/beaker-notebook/issues/264
