### ISSUE TITLE
add whitespace to file permissions dialog

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4551]
![screen shot 2016-07-22 at 4 03 49 pm](https://cloud.githubusercontent.com/assets/963093/17069694/f8c29f42-5025-11e6-8491-80f520ed088a.png)

add a blank line between the "Execute" line and the "Owner" line.

**Comment by konstantinTarletski** [comment]
template location :
/core/src/main/web/app/template/filepermissionsdialog.jst.html
