### ISSUE TITLE
fix ipywidgets

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4570]
see the widgets.bkr demo.
check it for all versions of widgets.

**Comment by dmtrius** [comment]
Could you be more specific?

**Comment by dmtrius** [comment]
logging:

Starting WebSockets: ws://127.0.0.1:8801/9b4519f/ipython.930229544126/api/kernels/6e2a452a-f5e9-44b9-98bd-5cb3561cc953
utils.js:38 Loading extension: jupyter-js-widgets
jupyter-js-widgets.js:155 loaded widgets
kernel.js:106 Kernel: kernel_connected (6e2a452a-f5e9-44b9-98bd-5cb3561cc953)
comm.js:69 register_comm
comm.js:70 8C2946B2344C4363937D809DD4E77FC9
comm.js:44 new _comm
comm.js:45 undefined
kernel.js:106 Kernel: kernel_ready (6e2a452a-f5e9-44b9-98bd-5cb3561cc953)
...
comm_open
comm.js:88 f36dea624c5443e78b6a14c970c1dac8
...
Could not open comm  --  Error: Class ipython.widget not found in registry
...
WrappedError {stack: "Error: Could not open comm↵    at new Error (nativ…al/ipythonPlugins/vendor/ipython4/utils.js:785:33", message: "Could not open comm", error_stack: Array[2]}

Here we have comm register `8C2946B2344C4363937D809DD4E77FC9` and comm open `f36dea624c5443e78b6a14c970c1dac8`. That should be a problem.

**Comment by dmtrius** [comment]
Update to previous revision 6 months ago did not help, widgets do not work. I shall get back to javascript errors.

**Comment by dmtrius** [comment]
I updated to last versions, it worked for me with ipython and python3.

`ipython                   5.1.0                    py27_0  
ipython-notebook          4.0.4                    py27_0  
ipywidgets                5.2.2                    py27_0 
jupyter                   1.0.0                    py27_3 
notebook                  4.2.2                    py27_0
widgetsnbextension        1.2.6                    py27_0

ipython                   5.1.0                    py35_0  
ipywidgets                5.2.2                    py35_0
jupyter                   1.0.0                    py35_3
notebook                  4.2.2                    py35_0
widgetsnbextension        1.2.6                    py35_0`

**Comment by dmtrius** [comment]
Also if you try

from ipywidgets import register, DOMWidget, Widget
@register('my.Widget')
class Foobar(DOMWidget):
    pass

Widget.widget_types

you will get

---

{'IPython.Accordion': ipywidgets.widgets.widget_selectioncontainer.Accordion,
 'IPython.BoundedFloatText': ipywidgets.widgets.widget_float.BoundedFloatText,
 'IPython.BoundedIntText': ipywidgets.widgets.widget_int.BoundedIntText,
 'IPython.Box': ipywidgets.widgets.widget_box.Box,
 'IPython.Button': ipywidgets.widgets.widget_button.Button,
 'IPython.Checkbox': ipywidgets.widgets.widget_bool.Checkbox,
 'IPython.ColorPicker': ipywidgets.widgets.widget_color.ColorPicker,
 'IPython.Controller': ipywidgets.widgets.widget_controller.Controller,
 'IPython.ControllerAxis': ipywidgets.widgets.widget_controller.Axis,
 'IPython.ControllerButton': ipywidgets.widgets.widget_controller.Button,
 'IPython.Dropdown': ipywidgets.widgets.widget_selection.Dropdown,
 'IPython.FlexBox': ipywidgets.widgets.widget_box.FlexBox,
 'IPython.FloatProgress': ipywidgets.widgets.widget_float.FloatProgress,
 'IPython.FloatRangeSlider': ipywidgets.widgets.widget_float.FloatRangeSlider,
 'IPython.FloatSlider': ipywidgets.widgets.widget_float.FloatSlider,
 'IPython.FloatText': ipywidgets.widgets.widget_float.FloatText,
 'IPython.HTML': ipywidgets.widgets.widget_string.HTML,
 'IPython.Image': ipywidgets.widgets.widget_image.Image,
 'IPython.IntProgress': ipywidgets.widgets.widget_int.IntProgress,
 'IPython.IntRangeSlider': ipywidgets.widgets.widget_int.IntRangeSlider,
 'IPython.IntSlider': ipywidgets.widgets.widget_int.IntSlider,
 'IPython.IntText': ipywidgets.widgets.widget_int.IntText,
 'IPython.Latex': ipywidgets.widgets.widget_string.Latex,
 'IPython.PlaceProxy': ipywidgets.widgets.widget_box.PlaceProxy,
 'IPython.Proxy': ipywidgets.widgets.widget_box.Proxy,
 'IPython.RadioButtons': ipywidgets.widgets.widget_selection.RadioButtons,
 'IPython.Select': ipywidgets.widgets.widget_selection.Select,
 'IPython.SelectMultiple': ipywidgets.widgets.widget_selection.SelectMultiple,
 'IPython.Tab': ipywidgets.widgets.widget_selectioncontainer.Tab,
 'IPython.Text': ipywidgets.widgets.widget_string.Text,
 'IPython.Textarea': ipywidgets.widgets.widget_string.Textarea,
 'IPython.ToggleButton': ipywidgets.widgets.widget_bool.ToggleButton,
 'IPython.ToggleButtons': ipywidgets.widgets.widget_selection.ToggleButtons,
 'IPython.Valid': ipywidgets.widgets.widget_bool.Valid,

##  'my.Widget': **main**.Foobar}

so widgets are activated but when you run actual code there would be an error
`Error: Class ipython.widget not found in registry`.
Sometimes you have error about javascript versions are different on back-end and front-end.
