### ISSUE TITLE
Pasting images from Clipboard into Beaker

### ISSUE THREAD

**Issue by ssadedin** [twosigma/beakerx#4602]
I have a lot of situations where it would be really useful to be able to put a pre-existing image into a Beaker notebook. The most common situation is that I want to grab a screen shot of something - a snippet from a paper I'm reading, a plot someone else made, or a web page with relevant content. These often add extremely useful / important contextual information about the problem I'm working on in the notebook. Currently I have some workarounds but they are all quite awkward.

I notice that tools like GitLab have got an extremely nice ability to capture and upload images straight from the clipboard. This would be an incredibly nice feature to have in Beaker!

**Comment by scottdraves** [comment]
Beaker supports drag-and-drop of images into the notebook.  But you are right, doing it from the clipboard with be good too.

**Comment by scottdraves** [comment]
actually paste already works as well!
it will be released in v1.7

**Comment by scottdraves** [comment]
needs to be documented

**Comment by ssadedin** [comment]
Thanks, this is going to be awesome!

**Comment by scottdraves** [comment]
thx :) you can run 1.7pre1 from the prerelease docker container:
https://hub.docker.com/r/beakernotebook/beaker-prerelease/
it has this feature.

**Comment by scottdraves** [comment]
OK actually I found a bug:
https://github.com/twosigma/beaker-notebook/issues/4737

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/4738
