### ISSUE TITLE
Null handling in JavaScript cell output

### ISSUE THREAD

**Issue by sztobar** [twosigma/beakerx#4605]
Right now JavaScript cells don't have any way to handle payload / output with `null` value.

fun fact: `(typeof null === 'object') === true`

Also when output from cell is promise that resolves to undefined it get mapped by `beakerObj.transform()` from `payload: undefined` to `payload: null` and this makes further errors as result / payload is checked only for being `undefined` and not for being `null`.

**Comment by scottdraves** [comment]
<img width="614" alt="screen shot 2016-08-05 at 12 28 10 pm" src="https://cloud.githubusercontent.com/assets/963093/17443348/34e267ae-5b08-11e6-868e-4cb109e7a639.png">
