### ISSUE TITLE
 Beaker should handle error from beaker lab - now BeakerLab returns an error for empty title

### ISSUE THREAD

**Issue by aryzhykova** [twosigma/beakerx#4615]
Beaker should handle error from beaker lab - now BeakerLab returns an error for empty title

Please see description of the initial issue in https://github.com/twosigma/bunsen/issues/2323

In case if user selected white space symbol as a title - notebook wasn't published at all
i see endless loader in beaker desktop
and no any errors or additional data any were
please see attached video
https://drive.google.com/a/ecisys.com/file/d/0B3uZDh6ZOrqYNGpLZ0hycFVEM0E/view?usp=sharing

**Comment by scottdraves** [comment]
not sure what you mean i just tried it and it worked fine:
https://pub.beakernotebook.com/publications/38d5015a-5e9b-11e6-909b-e790ec4876b0?fullscreen=true

But yea, Beaker should be much better at coming up with a title, so it is empty less often.
right now it just takes a section header, but if there is none, it should look for a text cell,
and if none then code cells.  That should almost always work.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/4634
