### ISSUE TITLE
notebook path hard to select

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4616]
if you click and drag to select the path to the current notebook in the top bar,
it is almost impossible.

i should be able to click to the right of the filename, and drag left, and select either just the filename, or keep dragging and select the whole path.

**Comment by sluhtoja** [comment]
Don't understand the task, visual reference needed.

**Comment by scottdraves** [comment]
![capture](https://cloud.githubusercontent.com/assets/963093/17623056/24da4d7c-606c-11e6-936f-f32846b940a9.PNG)

if you click at the red X and drag to the left, i should be able to select "wats.bkr"
