### ISSUE TITLE
'notebook' and 'view' menu plugin files need to be properly named

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#462]

**Comment by scottdraves** [comment]
can you elaborate please?
what's wrong with the names and what should they be?

**Comment by anglee** [comment]
I am already working on it, it will be clear once the PR is up in a minute.

**Comment by anglee** [comment]
rename  `/core/src/main/web/plugin/menu/notebook_edit.js`
to `/core/src/main/web/plugin/menu/notebook.js`

rename `/core/src/main/web/plugin/menu/notebook.js`
to `/core/src/main/web/plugin/menu/view.js`
