### ISSUE TITLE
Move data between different notebooks

### ISSUE THREAD

**Issue by VahidTehrani** [twosigma/beakerx#4639]
Assuming we have multiple notebooks for different tasks. For example, one notebook to build a regression model and another one to build a decision tree. My plan is having a main notebook and calling other notebooks to build models and then their performance measures again in the main notebook. I know how to run other notebooks within a notebook but it looks it does not return anything. Is it possible to do it? If so, I appreciate if can give a pointer to some examples. Thanks!

**Comment by scottdraves** [comment]
thank you for your question, Vahid.
do you mean calling other notebooks with the `beaker.loadLibrary()` function?
are you using Beaker Lab or standalone Beaker?

you can use the beaker object or a global variable to return a value from a notebook.

**Comment by VahidTehrani** [comment]
Thanks a lot Scott for your quick response. I'm using standalone Beaker. As far as I understand `beaker.loadLibrary()` is good to share a piece of code between different notebooks. Am I right? 
However what I need is a way to have access to the value of an object defined in another notebook. For example, If I define a beaker object called `a` in notebook `n1` and assign a value to it, I want to have access to the value of `a` in another notebook like `n2`. 
BTW, do you have any example of using `beaker.loadLibrary()`? It is a really nice feature and I want to use it.
Thanks a lot!

**Comment by scottdraves** [comment]
sure, here's an example: https://pub.beakernotebook.com/publications/9b733546-6550-11e6-95c0-6fdae1f6d0ab

loadLibrary() hasn't been released in standalone Beaker yet, it is only available on http://lab.beakernotebook.com.

but when it is released you will be able to load other notebooks and get values from them, either the beaker object or global variables.

**Comment by VahidTehrani** [comment]
Great! Thanks a lot Scott! Looking forward to use it in standalone Beaker.
