### ISSUE TITLE
publication showing a 503

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4640]
https://pub.beakernotebook.com/publications/45f15f50-617a-11e6-ac06-07ca454172bb
<img width="767" alt="screen shot 2016-08-13 at 1 21 38 pm" src="https://cloud.githubusercontent.com/assets/963093/17644604/21133b34-6159-11e6-9b0f-806f0e435e5e.png">

before i published it looked like this:
<img width="765" alt="screen shot 2016-08-13 at 1 23 04 pm" src="https://cloud.githubusercontent.com/assets/963093/17644606/293144be-6159-11e6-9fcb-140aa6f319a1.png">

**Comment by ildipo** [comment]
ref https://github.com/twosigma/bunsen/issues/3038
