### ISSUE TITLE
Writing csv files in Pandas

### ISSUE THREAD

**Issue by gregpoore** [twosigma/beakerx#4649]
Hello,

I am trying to write a simple Pandas dataframe to a csv file using the following:

`myDF.to_csv( './myDFPath.csv')`

The issue is that no file is created in my directory. The same occurs when trying to change the path argument. Is Beaker-specific syntax required for writing files?

**Comment by scottdraves** [comment]
The CWD is not the same as the notebook itself.
Use an absolute path for writing files.

**Comment by gregpoore** [comment]
Hi Scott,

Thanks for the heads-up! If anyone else runs into the same issue, it might be worth mentioning that the "home" directory for all Beaker notebooks is:

`/Applications/Beaker.app/Contents/Resources/dist`

I found the other csv files there before writing the full path.

Greg
