### ISSUE TITLE
make clicking on background of code cell move cursor to beginning/end of the text area.

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#466]

**Comment by scottdraves** [comment]
ditto for markdown

**Comment by scottdraves** [comment]
i had a problem that would have been solved by this today:
from the defaulte notebook i wanted to add a line of python below the commented line, a line with code.
so i clicked just below the comment line that it comes with, between that line and the Run button.
But the click does nothing, since it is outside the text box.
But I don't know that because there is no line.

what if instead of a box, we used very light gray for the text-editor background instead of full white?

**Comment by samccone** [comment]
1 thought .. obviously not red

![](http://dl.dropbox.com/u/36928599/Screenshots/0iw.png)

**Comment by scottdraves** [comment]
yup, light gray and it's good to go

**Comment by melmac48** [comment]
How about instead of a box we make it such that when you click on any (or most, within reason) of the currently non functional whitespace in the code cell, it puts the cursor at the end of the last line of code?

**Comment by scottdraves** [comment]
that's a good idea, i think it would solve the problem.

**Comment by jchendy** [comment]
Way to think outside the box Mel. Puns aside, I think it's a great idea because there are so many grey rectangles already.

**Comment by scottdraves** [comment]
one extra detail: there is whitespace which is above the text edit box, not just below.
if you click there, the cursor should go the first char of first line (pos 0).

**Comment by scottdraves** [comment]
in progress: https://github.com/twosigma/beaker-notebook/tree/spot/466
