### ISSUE TITLE
side effects with DOM manipulation inside HTML cell

### ISSUE THREAD

**Issue by GlulkAlex** [twosigma/beakerx#4668]
`document.body.innerHTML = "any_String_Here";`  
inside `script` tag in HTML cell 
destroyed all current notebook view . 
Maybe I missed a `undo` keyboard shortcut, 
or versioning option 
to run last stable notebook will be handy .
Sorry, my bad, 
I have being able to use `Notebook history` 
while `Notebook` cells are evaluated, 
before it reaches the buggy cell and clear all page content .
Not very convenient, but I can live with that solution .
I wonder if is it possible to disable cells auto run by default ?
When this Notebook/cell behavior is setted explicitly then I think it becomes more predictable .

**Comment by scottdraves** [comment]
indeed, yes it's possible to write a JavaScript or HTML cell that destroys the application.

there is an undo command (control or command z) but if the application is destroyed, then it's not available.

notebooks are checkpointed every minute into ~/.beaker/v1/var/sessionBackups, you may be able to recover your work there, if you lost something.

not sure what you mean "cells auto run by default"....

**Comment by GlulkAlex** [comment]
Thank you for the quick reply. 
To be honest I just started to use beaker-notebook 
and at the moment when I wrote my post 
I do not read documentation yet (sorry 'bout that) .
By "cells auto run by default" I mean that 
in comparison to IPython/Jupiter notebook, 
as it seems to look for me, 
when beaker-notebook page loaded (at the first time) it is 
starting to reevaluate cells content, 
not just show the last saved state. 
And this allow (not preventing) a cell with specific (non-safe) code 
crash the entire notebook. 
Please, correct me if I am wrong. 
By the way, 
I do not think that this is a real issue, 
just a notebook's feature (more freedom / less restriction ?).

**Comment by scottdraves** [comment]
there is an option to have beaker cells be evaluated automatically when a notebook is opened (Initialization cells, it's in the cell menu), but by default it is off.  Otherwise it's the same.

Thank you for your feedback.
