### ISSUE TITLE
IPython doesn't display cells with unicode as a table...

### ISSUE THREAD

**Issue by mig2** [twosigma/beakerx#4673]
Evaluate {'a': 'a'} and {'a': u'a'} in IPython. The first displays as a table, the second as text. This doesn't happen with Python 3.

**Comment by scottdraves** [comment]
confirmed: https://pub.beakernotebook.com/publications/5bab39ac-6d72-11e6-a631-8f25c1b38f1a
Python2 isn't handling unicode correctly.
