### ISSUE TITLE
cell types markdown & text vs the plugin languages is confusing

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#468]
there should just be one menu for choosing the cell type instead of two (when you create a cell and later with the language menu).

furthermore in the current design there appears to be no way to change a cell from say markdown to text after it has been created, or markdown to latex, etc because one of the two menus is not accessible to edit.

**Comment by scottdraves** [comment]
it's also confusing that you click on text and markdown to edit (ie input/output are superimposed), but not html and latex.

**Comment by ildipo** [comment]
What about if we include a WYSIWYG editor such as
http://xing.github.io/wysihtml5/ or http://sandbox.scriptiny.com/tinyeditor/ for HTML cells?

**Comment by bradicdesign** [comment]
@scottdraves you are correct. This is very confusing.

The original intent was that:
1. You can change the language on any cell
2. All "descriptive" cells i.e. non-language cells (markdown / html / latex), have inline editing with no output cell.

My recommendation is as follows:
- Include all language options under language dropdown
- Markdown, HTML and Latex cells should all behave the same (like Markdown today + Ok/Done button when editing)

Two questions:
1.   Can we remove Text as cell type (not sure where this came from - isn't markdown sufficient?)
2.  Is there a common case where you'd want to see both the html and its rendering together?

Over to Mel for prioritization.

**Comment by bradicdesign** [comment]
Design posted on basecamp https://basecamp.com/1779787/projects/4958832/messages/33525021#events_message_33525021

**Comment by scottdraves** [comment]
text is gone.
