### ISSUE TITLE
Is there a way to setup beaker without sudo permissions? 

### ISSUE THREAD

**Issue by mohit-shrma** [twosigma/beakerx#4686]
I tried installing dependencies of the beaker on my ubuntu machine, but it requires sudo access. I don't have sudo access on my machine. Is there a way to set it up locally? I can do that easily for jupyter.

**Comment by scottdraves** [comment]
yes the core dependencies are just nginx and java8.  while the script for installing them automatically uses apt-get (https://github.com/twosigma/beaker-notebook/blob/master/launcher/ubuntu/install-runtime-core-dependencies.sh), any way that you can download and get them into the PATH should be fine.
