### ISSUE TITLE
No Markdown plugin installed with "gradle run"

### ISSUE THREAD

**Issue by charlesreid1** [twosigma/beakerx#4687]
When I follow the instructions at the [Mac build and run page](https://github.com/twosigma/beaker-notebook/wiki/Mac-build-and-run) to install Beaker Notebook on a Mac (10.11.5), there is no working Markdown plugin. When I try and add it using the Language Manager, there is no item in the list for Markdown. I don't have a URL for a Markdown plugin and could not find any URLs for plugins with some Google searching.

My question is: what is required beyond the steps listed on the [Mac build and run page](https://github.com/twosigma/beaker-notebook/wiki/Mac-build-and-run) in order to get Markdown working with Beaker Notebook?

**Comment by scottdraves** [comment]
it's called "text"

**Comment by scottdraves** [comment]
and it's not in the language manager, it's one of the blue buttons when you add cells.
