### ISSUE TITLE
Plugin Manager design needs to be simplified

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#469]
- Remove the "menus" panel (this can be set from the prefs file).
- Get rid of the text field next to "Add plugin from URL".
- When a user clicks one of the plugin buttons, it just loads.  ideally it would have a status light that cycled from gray to yellow to green.  even more ideally, if you click it again, and it is already loaded, then it unloads.
- The "Add plugin from URL" button becomes just another button in the big list (on the far right) with label "Open from URL...", which opens a dialog where you enter the URL and confirm.
- change the accordion list into tabbed panels.  plugins with no parameters do not create a panel.

**Comment by anglee** [comment]
The "menus" panel let you let you load menu plugins dynamically. This cannot be done from the prefs file.
