### ISSUE TITLE
Windows 7 64bit, Beakernotebook portable and Miniconda3: Python3 and IPython not found

### ISSUE THREAD

**Issue by jknaus** [twosigma/beakerx#4697]
Hi,
I am having trouble to set the correct preferences in the language file to get my beaker portable installation to work with my Python3 installation.
I use the [Miniconda](http://conda.pydata.org/miniconda.html) python distribution.
I solely use Python3.

Here is my language file `beaker.pref.json` (in `C:\Program Files\beaker-notebook\resources\.beaker\v1\config`):

```
{
    "languages": {
        "IPython": {
            "path": "C:\\Miniconda3\\Scripts"
        },
        "Python3": {
            "path": "C:\\Miniconda3"
        },
        "R" : {
            "path" : "C:\\Program Files\\R\\R-3.3.1\\bin"
        }
    }
    ,
    "autocomplete-parameters": "true",
    "pref-format": "1",
    "allow-anonymous-usage-tracking": false,
    "edit-mode": "default"
}
```

I had to add R to make it work. 
Although the paths for the to python.exe and ipython.exe are correct, the code blocks fail to initialize.
Note that in C:\Miniconda3\Scripts there is both an ipython.exe and an ipython3.exe.

How can I make that work?

**Comment by joschnitzbauer** [comment]
I have exactly the same problem here. Bump?
