### ISSUE TITLE
need more Hierarchy Lines, and align them

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#470]
Need horizontal lines, from each cell, left out to the line dropping down from its parent.

The vertical line should come closer to the +- toggle, and be aligned with the vertical line of the +.

If the horizontal line is coming into a section, then it should be aligned with the horizontal line of the +-

and the lines should be heavier

**Comment by samccone** [comment]
<img width="353" alt="screen shot 2015-08-03 at 11 59 32 am" src="https://cloud.githubusercontent.com/assets/883126/9041644/294c5344-39d7-11e5-86d3-91b56aa9f989.png">

Here is the first, pass, the lines can get heaver once we have this in code form, should be a simple tweak. How do you feel about the alignment of the lines @scottdraves ?

**Comment by scottdraves** [comment]
great, that's the right idea.  yea heavier, like as thick as the lines in the +.

**Comment by samccone** [comment]
resolved :white_check_mark:

**Comment by scottdraves** [comment]
![screen shot 2015-08-07 at 11 07 30 pm](https://cloud.githubusercontent.com/assets/963093/9148816/27cefb9a-3d59-11e5-9051-481311b09150.png)

:dolphin: :dolphin:
