### ISSUE TITLE
need a way to remove box and decorations

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#471]
hiding just the iput isn't enough especially for markup, latex, html, text cells.
![screen shot 2014-08-13 at 11 29 29 pm](https://cloud.githubusercontent.com/assets/963093/3915601/5e5c892c-2363-11e4-88e5-f9824c4656ad.png)

**Comment by samccone** [comment]
@scottdraves have you seen advanced mode?

**Comment by scottdraves** [comment]
yes, that doesn't remove the box and it's a global mode.

**Comment by melmac48** [comment]
will leave this for now and consider latex in markdown

**Comment by scottdraves** [comment]
we have latex in markdown now, so this is nearly irrelevant.

**Comment by samccone** [comment]
@scottdraves is this still something that you would like?
