### ISSUE TITLE
Docker hub is not updated with the latest version

### ISSUE THREAD

**Issue by daniloascione** [twosigma/beakerx#4714]
Please update docker public repository (https://hub.docker.com/r/beakernotebook/beaker/) with the latest version of the beaker docker image.
Current docker image version is:
build time: 2016-03-08 03:01 UTC
version: 1.5.2-0-g34d512f

**Comment by scottdraves** [comment]
that docker image is only updated at releases, not to master.

**Comment by daniloascione** [comment]
Sure, and the latest version 1.6 (https://github.com/twosigma/beaker-notebook/releases/tag/1.6) is not in hub.docker.com.

**Comment by scottdraves** [comment]
that would a bug, will check it

**Comment by scottdraves** [comment]
you are right, thank you!
should be fixed now, please reopen if not.

we have done a ton of work since 1.6, aiming for 1.7 in 1-2 months.

**Comment by scottdraves** [comment]
fyi i just updated the prerelease container with master, now called 1.7pre1:
https://hub.docker.com/r/beakernotebook/beaker-prerelease/
