### ISSUE TITLE
Clear namespace data

### ISSUE THREAD

**Issue by daniloascione** [twosigma/beakerx#4733]
Is there any way to clear beaker namespace data? Maybe an api call from the notebook?
Since it is saved with the notebook file, this could get very big. 
Also it made versioning  problematic.
Thank you.

**Comment by scottdraves** [comment]
yes, in JavaScript just evaluate "beaker", and a GUI will appear that shows all the values and each one has a menu where you can delete or rename it.

**Comment by daniloascione** [comment]
@scottdraves thank you for the tip! Could you please point me to some documentation about the "beaker" api?

**Comment by scottdraves** [comment]
https://pub.beakernotebook.com/publications/5334c830-fb88-11e5-b894-e3872df02acb?fullscreen=true

it's called "The Beaker Object" in the table of contents of the main tutorial.
