### ISSUE TITLE
sluggish menus and everything

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4739]
if i open the catalog of plot features and then move the mouse over the top menus, the highlight lags behind the mouse motion by about 0.5s.  i think this is a recent regression but not sure yet.

**Comment by dmtrius** [comment]
This issue appeared after https://github.com/twosigma/beaker-notebook/issues/4702 was merged.

**Comment by sluhtoja** [comment]
not related to issues #4702 and #4740

**Comment by dmtrius** [comment]
in core/src/main/web/app/helpers/dropdown.js

`$(document)
    .on('keydown.bs.dropdown.data-api', toggle, $.fn.dropdown.Constructor.prototype.keydown)
    .on('keydown.bs.dropdown.data-api', '.dropdown-menu', $.fn.dropdown.Constructor.prototype.keydown)
    .on('mouseenter.bs.dropdown.data-api', '.dropdown-menu, .dropdown', clearMenus);`

if you comment out mouseenter binding performance would be perfect.
That's what I found so far.

**Comment by dmtrius** [comment]
Actually only `$('.dropdown-menu a').blur();` should be removed.

**Comment by sluhtoja** [comment]
Related to issue #3852   28.04.2016 .
Thank you.
