### ISSUE TITLE
make the maximum number of columns configurable

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4749]
instead of always 50, should be able to configure the max the same way other settings can be configured through the beaker object, like `beaker.prefs.maxTableColumns = 100`.  see groovy-examples.bkr for some other prefs like this.

if the pref is -1 then that means no maximum.

**Comment by caseyjconger** [comment]
Apologies for the dumb question. But how do I actually set this option? I tried adding it in the CodeMirror Settings JSON:
```
{
    "styleActiveLine": true,
    "outputColumnLimit": false
}
```
But I still get that my table will not show up if it has more than 100 columns.
