### ISSUE TITLE
New UI implementation doesn't support notebook with no section cells

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#475]
Open the default notebook, click on the cell menu of the section cell and say delete heading and keep contents.
![image](https://cloud.githubusercontent.com/assets/1767921/3922273/bb7d3042-23c8-11e4-881d-7a9c8d74d379.png)

The Chrome console shows error

![image](https://cloud.githubusercontent.com/assets/1767921/3922231/63aeaf6c-23c8-11e4-85dd-a7daad46b50b.png)

And the hierarchy mode says `undefined`

![image](https://cloud.githubusercontent.com/assets/1767921/3922244/8702f950-23c8-11e4-8dcd-ba8ba3dac107.png)

Note that a notebook with no section cell is a valid use case and should be supported.

**Comment by samccone** [comment]
So I am going to say if we are at a depth of undefined (no depth) we should just say that the depth is 0 if someone goes into this mode.

I will implement it and we can take it from there.

Good catch @anglee :+1:
