### ISSUE TITLE
beaker bug with R data.table and big file

### ISSUE THREAD

**Issue by waschult** [twosigma/beakerx#4751]
Hallo,

i am testing beaker notebook and I have a problem with R kernel and package data.table.

Doing this in jupyter notebook with 2,27 G testfile and R kernel works without problems in ~ 14 Sec. 

library(data.table)
library(bit64)
DT <- fread("/home/r-312-dev/share/test.txt", header = TRUE)

Doing the same in beaker notebook (same environment, same user, ubuntu 16.04, same R, python, ...
gives an endless loop.

   Elapsed: 6m43s  
running...

```
Read 0.0% of 10866775 rows
Read 12.1% of 10866775 rows
Read 24.8% of 10866775 rows
Read 36.4% of 10866775 rows
Read 48.2% of 10866775 rows
Read 60.1% of 10866775 rows
Read 72.0% of 10866775 rows
Read 83.9% of 10866775 rows
Read 96.1% of 10866775 rows
Read 10866775 rows and 15 (of 15) columns from 2.279 GB file in 00:00:11
```

The code doesn't stop running. Reading small files with fread from data.table works.

Thanks,

Walter

**Comment by scottdraves** [comment]
try finishing the cell with a small value like "ok".
translation in R has a performance problem.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/2815
