### ISSUE TITLE
shift-click below code cell

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4762]
should select from the current cursor to the end of the code, but it just moves the cursor to the end (ignoring shift).

the exact place to click is to the right of the "Run" button.  this area is outside the code mirror, but inside the code cell.

**Comment by scottdraves** [comment]
similarly if you click in this area of a code cell, and then drag up into the code, it should select from the bottom.

**Comment by scottdraves** [comment]
first part looks good & merged, but still need:

> similarly if you click in this area of a code cell, and then drag up into the code, it should select from the bottom.

**Comment by uluaiv** [comment]
Hi @scottdraves 

I checked this part and the behaviour of SHITF+click w.r.t. specifications seems correct to me. What needs still to be done?
