### ISSUE TITLE
scala plugin doesn't start in beaker-electron 1.6-0-gb7c81a9 on Windows

### ISSUE THREAD

**Issue by dlaflamme** [twosigma/beakerx#4781]
The same non-electron version does start on the same machine. The message that appears when I try to start the scala plugin is:

Language Error
Failed to start Scala.

Did you install it according to the instructions on BeakerNotebook.com?

If you already have it, then edit your preferences file to help Beaker find it on your system, and then restart Beaker and try again.

Any other languages in your notebook should still work.

**Comment by scottdraves** [comment]
Thanks for the report I will look into it.

**Comment by scottdraves** [comment]
it started for me.

**Comment by dlaflamme** [comment]
I'll remove, reboot, and reinstall. Any logs that will be helpful to check?

**Comment by scottdraves** [comment]
i believe if you run it from a terminal instead of just by double clicking, the log and errors are visible but not sure.

**Comment by dlaflamme** [comment]
Here is what I see when I try to start Scala in the Language Manager:

starting nginx instance (D:\Users\Dan\software\beaker-notebook-electron-1.6-0-gb7c81a9\resources\dist/nginx)

Beaker hash b7c81a9
Beaker listening on http://127.0.0.1:8801/
note: probing until backend is ready, an error here is normal

Running
0: D:\Users\Dan\software\beaker-notebook-electron-1.6-0-gb7c81a9\resources\dist\python\python
1: D:\Users\Dan\software\beaker-notebook-electron-1.6-0-gb7c81a9\resources\dist/config/plugins/eval/scala/scalaPlugin
2: 8804
Done starting Scala
Scala-stderr>The input line is too long.
Scala-stderr>The syntax of the command is incorrect.

**Comment by scottdraves** [comment]
thanks that's a good clue.  i will take a closer look tomorrow when I have access to Windows.
is this the portable electron version or did you run the installer?

**Comment by dlaflamme** [comment]
This is the portable version. Tested on 2 different machines--same result.

**Comment by scottdraves** [comment]
try this with a fix:
https://s3.amazonaws.com/beaker-distributions/beaker-notebook-cit-4091-0-gad1d6de-electron-windows.zip

**Comment by dlaflamme** [comment]
Whatever change you made in https://s3.amazonaws.com/beaker-distributions/beaker-notebook-cit-4091-0-gad1d6de-electron-windows.zip fixed the problem for me.
