### ISSUE TITLE
race condition in autocomplete

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4784]
during autocomplete, if you press down arrow and then before the new function's parameters and documentation are fetched and displayed, if you hit return then you get mangled code inserted into the code cell and the documentation window gets stuck open and can't be closed.

this can be difficult to reproduce, probably to really debug it you should hack the server to slow down the autocomplete service.

**Comment by konstantinTarletski** [comment]
Yes, it is difficult to reproduce : I slow down JAVA plugin and GROOVY, but was not succeeded.
Get some another behavior, but not any "stuck".
In Java there is no any "AutocompleteDocumentation", but it is in Groovy. I tried bouth in different variants.
Need more information.

P.S.
May be it is not our bug, but some framework bug. I tried lot of variants. 
I think it is some event lose.
