### ISSUE TITLE
IPython/Python3 hangs after initialization

### ISSUE THREAD

**Issue by sparkofreason** [twosigma/beakerx#4799]
Sounds similar to several other issues, IPython appears to hang after starting. Output below. Running on Ubuntu 15.10, installed from archive. I installed anaconda after beaker. Beaker 1.6.0, IPython 5.1.0. Tried both Chrome and Firefox, same result. I have updated language prefs. I think the plugin is still trying to run an older version of IPython, because the console output below looks a lot different than what is shown when I run "ipython notebook". Since language prefs are updated, and the path is set in .profile, not sure what else to try.

IPython-stderr>[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
IPython-stderr>[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
nginx-stderr>2016/10/05 09:50:57 [error] 11246#11246: *61 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /b7c81a9/ipython.496191452899/login HTTP/1.1", upstream: "http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
IPython-stderr>[W 09:50:57.189 NotebookApp] Unrecognized alias: '--ipython-dir=/home/dave/.beaker/v1/nginx6278180628023317055', it will probably have no effect.
IPython-stderr>[C 09:50:57.195 NotebookApp] Bad config encountered during initialization:
IPython-stderr>[C 09:50:57.195 NotebookApp] Invalid argument: '--ipython-dir=/home/dave/.beaker/v1/nginx6278180628023317055'
IPython-stdout>The Jupyter HTML Notebook.
IPython-stdout>This launches a Tornado based HTML Notebook Server that serves up an
IPython-stdout>HTML5/Javascript Notebook client.
IPython-stdout>Subcommands
IPython-stdout>-----------
IPython-stdout>Subcommands are launched as `jupyter-notebook cmd [args]`. For information on
IPython-stdout>using subcommand 'cmd', do: `jupyter-notebook cmd -h`.
IPython-stdout>list
IPython-stdout>    List currently running notebook servers.
IPython-stdout>Options
IPython-stdout>-------
IPython-stdout>Arguments that take values are actually convenience aliases to full
IPython-stdout>Configurables, whose aliases are listed on the help line. For more information
IPython-stdout>on full configurables, see '--help-all'.
IPython-stdout>--script
IPython-stdout>    DEPRECATED, IGNORED
IPython-stdout>--pylab
IPython-stdout>    DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
IPython-stdout>--debug
IPython-stdout>    set log level to logging.DEBUG (maximize logging output)
IPython-stdout>--no-browser
IPython-stdout>    Don't open the notebook in a browser after startup.
IPython-stdout>-y
IPython-stdout>    Answer yes to any questions instead of prompting.
IPython-stdout>--no-mathjax
IPython-stdout>    Disable MathJax
IPython-stdout>    MathJax is the javascript library Jupyter uses to render math/LaTeX. It is
IPython-stdout>    very large, so you may want to disable it if you have a slow internet
IPython-stdout>    connection, or for offline use of the notebook.
IPython-stdout>    When disabled, equations etc. will appear as their untransformed TeX source.
IPython-stdout>--no-script
IPython-stdout>    DEPRECATED, IGNORED
IPython-stdout>--generate-config
IPython-stdout>    generate default config file
IPython-stdout>--certfile=<Unicode> (NotebookApp.certfile)
IPython-stdout>    Default: u''
IPython-stdout>    The full path to an SSL/TLS certificate file.
IPython-stdout>--ip=<Unicode> (NotebookApp.ip)
IPython-stdout>    Default: 'localhost'
IPython-stdout>    The IP address the notebook server will listen on.
IPython-stdout>--pylab=<Unicode> (NotebookApp.pylab)
IPython-stdout>    Default: 'disabled'
IPython-stdout>    DISABLED: use %pylab or %matplotlib in the notebook to enable matplotlib.
IPython-stdout>--log-level=<Enum> (Application.log_level)
IPython-stdout>    Default: 30
IPython-stdout>    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
IPython-stdout>    Set the log level by value or name.
IPython-stdout>--port-retries=<Integer> (NotebookApp.port_retries)
IPython-stdout>    Default: 50
IPython-stdout>    The number of additional ports to try if the specified port is not
IPython-stdout>    available.
IPython-stdout>--notebook-dir=<Unicode> (NotebookApp.notebook_dir)
IPython-stdout>    Default: u''
IPython-stdout>    The directory to use for notebooks and kernels.
IPython-stdout>--keyfile=<Unicode> (NotebookApp.keyfile)
IPython-stdout>    Default: u''
IPython-stdout>    The full path to a private key file for usage with SSL/TLS.
IPython-stdout>--client-ca=<Unicode> (NotebookApp.client_ca)
IPython-stdout>    Default: u''
IPython-stdout>    The full path to a certificate authority certifificate for SSL/TLS client
IPython-stdout>    authentication.
IPython-stdout>--config=<Unicode> (JupyterApp.config_file)
IPython-stdout>    Default: u''
IPython-stdout>    Full path of a config file.
IPython-stdout>--port=<Integer> (NotebookApp.port)
IPython-stdout>    Default: 8888
IPython-stdout>    The port the notebook server will listen on.
IPython-stdout>--transport=<CaselessStrEnum> (KernelManager.transport)
IPython-stdout>    Default: 'tcp'
IPython-stdout>    Choices: [u'tcp', u'ipc']
IPython-stdout>--browser=<Unicode> (NotebookApp.browser)
IPython-stdout>    Default: u''
IPython-stdout>    Specify what command to use to invoke a web browser when opening the
IPython-stdout>    notebook. If not specified, the default browser will be determined by the
IPython-stdout>    `webbrowser` standard library module, which allows setting of the BROWSER
IPython-stdout>    environment variable to override it.
IPython-stdout>To see all available configurables, use `--help-all`
IPython-stdout>Examples
IPython-stdout>--------
IPython-stdout>    jupyter notebook                       # start the notebook
IPython-stdout>    jupyter notebook --certfile=mycert.pem # use SSL/TLS certificate

**Comment by scottdraves** [comment]
1.6 is not compatible with IPython 5.  please try our 1.7 prerelease (easy to run with docker) https://github.com/twosigma/beaker-notebook/wiki/Running-the-Docker-Container
That has all the languages built-in, including IPython v5.1

note: leave off the "--connect-host" argument the implementation of that has not been pushed to docker hub yet.

**Comment by sparkofreason** [comment]
Thanks. Can I install from an archive? I'm working on a new version of a Clojure plugin, seems easiest to run and test just running directly from the filesystem.

**Comment by scottdraves** [comment]
We don't have a prerelease as an archive.
If you are doing development i would recommend using master from github, which has this fix among many.
Very curious about your plugin, please email me our our user email list...
