### ISSUE TITLE
Can't create multiple notebooks that are using Mesos cluster

### ISSUE THREAD

**Issue by elyast** [twosigma/beakerx#4800]
I am getting following exception when trying to open new notebook and initiate SparkContext that points to mesos master

java.lang.UnsatisfiedLinkError: Native Library /usr/lib/libmesos-1.0.1.so already loaded in another classloader

**Comment by scottdraves** [comment]
thanks for the report, please try our 1.7 prerelease (easy to run with docker) https://github.com/twosigma/beaker-notebook/wiki/Running-the-Docker-Container
What version of Spark are you loading?

note: leave off the "--connect-host" argument the implementation of that has not been pushed to docker hub yet.

**Comment by elyast** [comment]
I will try that, for now I am using Spark 2.0.0, scala version is 2.11, its run as a docker image in our mesos cluster and then its using spark settings to run spark executors as docker images too.

2 notebooks starts like that:

import org.apache.spark.sql._
val conf = new SparkConf().setAppName("xxx").setMaster("mesos://leader.mesos:5050")
val spark = SparkSession.builder.config(conf).getOrCreate()

first works ok, second one not really, it fails with the exception above.

Is there a way to force scala plugin to spawn new process for every notebook?

One more issues that we are facing when trying to run Spark job with Mesos through Beaker using docker images, that actual cell code is not being sent to executors and we are getting ClassNotFoundException (however when we try to replicate similar code using PySpark (so python) it works without problem

**Comment by elyast** [comment]
Just tried 1.7 still the same issue

**Comment by scottdraves** [comment]
Ah I know what you mean.  Indeed Spark Context has the annoying problem of being able to exist only once per JVM.  We have a vague plan for an option for starting a new JVM for each notebook but it will be some time.

**Comment by elyast** [comment]
I see, we could take a look how we can help on our end I will keep you updated.

One more unresolved story is following, lets assume we have just one notebook for spark scala cluster access, then after initialization of SparkSession I can write following code:

```
val NUM_SAMPLES = 10000000
val count = spark.sparkContext.parallelize(1 to NUM_SAMPLES).map{i =>
  val x = Math.random()
  val y = Math.random()
  if (x*x + y*y < 1) 1 else 0
}.reduce(_ + _)
println("Pi is roughly " + 4.0 * count / NUM_SAMPLES)
```

but I am getting following exceptions:

```
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
  at org.apache.spark.rdd.RDD.reduce(RDD.scala:965)
  ... 25 elided
Caused by: java.lang.ClassNotFoundException: $anonfun$1
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
```

it seems that closures are not passed easiest way would be to add notebook jar to spark context or sth similar, the very same code works in pyspark
