### ISSUE TITLE
Difficulties using SQLite / JDBC Access

### ISSUE THREAD

**Issue by ssadedin** [twosigma/beakerx#4804]
I'm trying to use SQLite from Groovy and am running into issues with class loaders. (I assume other JVM languages will be the same). Here's some example code and output:

``` groovy
import groovy.sql.*
Sql.newInstance("jdbc:sqlite:/tmp/test.db")
```

produces

```
java.sql.SQLException: No suitable driver found for jdbc:sqlite:/tmp/test.db
    at script14757801029271848146897.run(script14757801029271848146897.groovy:3)
    at com.twosigma.beaker.groovy.utils.GroovyEvaluator$workerThread$MyRunnable.run(GroovyEvaluator.java:382)
```

Note that the SQLite jar file is added in the Language settings for  Groovy. So it is not because the class is not found, but rather that the Sql classloader is isolated from the child classloader that contains the JDBC driver. For the case of SQLite I can work around it by directly accessing the driver to create a connection:

``` groovy
conn = new org.sqlite.JDBC().connect("jdbc:sqlite:/tmp/test.db", new Properties())

db = Sql.newInstance(conn)
```

Unfortunately this only works once. If I start up a second Groovy instance and try to load SQLite:

```
java.lang.UnsatisfiedLinkError: Native Library /private/var/folders/48/47c_t9mx7qbccq3jhylvxkj40000gp/T/sqlite-3.8.6-x86_64-libsqlitejdbc.jnilib already loaded in another classloader
 -java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
    at org.sqlite.core.NativeDB._open(Native Method)
    at org.sqlite.core.DB.open(DB.java:161)
    at org.sqlite.core.CoreConnection.open(CoreConnection.java:145)
```

I'm not sure the right way to go about solving this. For SQLite you could perhaps just bundle the Jar file Beaker so that it is in the top level classloader, along side Groovy itself. I think SQLite is pretty widely used in data analysis so it could be justifiable for that case. I'm not sure where that leaves other JDBC drivers that would presumably have the same problem though.

**Comment by scottdraves** [comment]
does this work? http://www.kfu.com/~nsayer/Java/dyn-jdbc.html

**Comment by scottdraves** [comment]
i would be happy to include sqlite but would prefer fixing all of them as you point out
