### ISSUE TITLE
Feature request: spreadsheets

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#4817]
Perhaps I missed it and it is already implemented somewhere, but it would be great to be able to insert data right into notebook via spreadsheet. 

The example is the following. There is laboratory practice and I want to prepare a notebook, to which students can just put data and run it to produce result. Also I want to edit it inside the notebook to see if change in data will give change to the result.

Probably one needs a specific ouptut window widget which is essentially a spreadsheet with `commit` button. The button changes internal state of underlying data table. So creating new spreadsheet could be done as follows:

```
Spreadsheet spr = new Spreadsheet(<column configuration>)
```

and editing existing one like simply `spr` at the end of code block

**Comment by scottdraves** [comment]
Agreed.  I think this would best be an extension of our existing table UI.
