### ISSUE TITLE
Save to csv not working

### ISSUE THREAD

**Issue by Irubelsky** [twosigma/beakerx#4836]
Copy to Clipboard: Chrome - OK, Firefox - OK, Safari - doesn't work
Download All as CSV: Chrome - OK, Firefox - doesn't work, Safari - OK
Download Selected as CSV: Chrome - OK, Firefox - doesn't work, Safari - OK 
Referenced to [2899](https://github.com/twosigma/bunsen/issues/2899)

**Comment by sluhtoja** [comment]
Referenced issue does not exist.

**Comment by scottdraves** [comment]
It exists but you do not have permissions on it.  Don't worry about that though, just try these table features on firefox and safari.

**Comment by sluhtoja** [comment]
Copy to Clipboard: Chrome - OK, Firefox - OK, Safari - doesn't work:

clipboard API support to browsers:
http://caniuse.com/#feat=clipboard
I upgraded my mac safari to 9.1.2 and still doesn't allow. Possible reason is that the OS doesn't allow it.
firefox take on browser compatibility
https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

Accepted answer gives sufficient answer:
http://stackoverflow.com/questions/34045777/copy-to-clipboard-using-javascript-in-ios

this gives insight how you can manipulate cut,copy,delete(in handler), when user has called the event manually.
https://developer.apple.com/library/content/documentation/AppleApplications/Conceptual/SafariJSProgTopics/CopyAndPaste.html

right now zeroclipboard.js is used
possible exchange libraries:
https://clipboardjs.com/

but not sure if the clipboard.js will fix the issue though

**Comment by sluhtoja** [comment]
Download All as CSV, Download Selected as CSV:
Firefox doesn't allow click() with jQuery, manual click on the element is required attributes already assigned.
One possibility is to add attributes to the dropdown element when creating table, notebooks tables, especially big tables could have performance issues. 
Second one is to create a popup to confirm download.

**Comment by scottdraves** [comment]
Thanks.  Please use the popup (in ffox only).

**Comment by scottdraves** [comment]
How about this way of doing downloads on firefox?
http://stackoverflow.com/questions/20303682/file-download-not-working-on-firefox

**Comment by sluhtoja** [comment]
Firefox 4 and earlier does not have a click() method on anchors at all.
Firefox 5 and 6 do have such a method, and the method dispatches an untrusted click event, but they do not allow untrusted events to trigger a link's href.
Firefox 7 and later allow untrusted click events to trigger a link.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click
"..... One exception: The click() method will not cause an <a> element to initiate navigation as if a real mouse-click had been received."

but calling click trigger like that could work. Will give it a try

**Comment by scottdraves** [comment]
cool thx merged that.  now how about safari?
