### ISSUE TITLE
Question: Is it possible to use react in beaker ?

### ISSUE THREAD

**Issue by romans127** [twosigma/beakerx#4837]
Greetings, 

Is it possible to use Facebook's React.js in beaker ?

**Comment by scottdraves** [comment]
Hi Ryan, thanks for your question.
In Beaker 1.7 (https://github.com/twosigma/beaker-notebook/wiki/Running-the-Docker-Container)
it's easy to load react.js with the cdnjs browser built into the language manager.
i haven't tried to see what building a UI with it would be like though.

in previous versions you can still load it, but it's more awkward, see the p5.js tutorial for how.

**Comment by romans127** [comment]
Thank you ,

Is there an electron version available for 1.7

**Comment by scottdraves** [comment]
no it will be released maybe next week.  until then you can use the technique demonstrated in the p5.js tutorial: https://lab.beakernotebook.com/publications/802130de-fccf-11e5-bcec-cbc342fbfaba?fullscreen=false

**Comment by romans127** [comment]
Thank you, 

I tried the docker approach unfortunately this doesn't seem to be working on windows

**Comment by romans127** [comment]
more specifically the path variable as well as the volume mapping .

**Comment by scottdraves** [comment]
on windows you would need a different syntax for home, maybe %HOME%, not sure I haven't tried that yet.
