### ISSUE TITLE
gap between menu item and drop-down

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#484]
![screen shot 2014-08-15 at 5 01 06 pm](https://cloud.githubusercontent.com/assets/963093/3938875/596aecee-24bf-11e4-9a28-17e391949122.png)

**Comment by anglee** [comment]
Screen shot from the design:
![image](https://cloud.githubusercontent.com/assets/1767921/3938897/b3412bc0-24bf-11e4-8829-c73a1abf540f.png)
