### ISSUE TITLE
pub broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4846]
when i go to file -> publish menu, log in, and click "publish"
it opens a new window and redirects to

`https://pub.beakernotebook.com/publications/featured#%2Fpublications%2Fe4f95c6a-9861-11e6-9fbd-e32d9c88b3a8`

but it should be

`https://pub.beakernotebook.com/publications/e4f95c6a-9861-11e6-9fbd-e32d9c88b3a8`

the server changed the format for the URLs, the client needs to follow suit.

**Comment by konstantinTarletski** [comment]
Actually It goes to this URL:
https://pub.beakernotebook.com/#/publications/505753de-99f4-11e6-9806-83a60007c496
but "pub.beakernotebook.com" redirects it to :
https://pub.beakernotebook.com/publications/featured#%2Fpublications%2Fe4f95c6a-9861-11e6-9fbd-e32d9c88b3a8
But I change URL to :
https://pub.beakernotebook.com/publications/505753de-99f4-11e6-9806-83a60007c496

**Comment by scottdraves** [comment]
and https://github.com/twosigma/beaker-notebook/pull/4854
