### ISSUE TITLE
restart needed to update default notebook

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4861]
to reproduce:
- run beaker
- from the start page click on "new default notebook"
- copy a notebook to ~/.beaker/v1/config/default-notebook.bkr
- from the start page click on "new default notebook"

result: you get a 2nd copy of the default.
expected: the notebook you copied in should appear instead

the server should read the file every time the rest/util/getDefaultNotebook should deliver new version.  it should not be cached.  maybe just change to post?

**Comment by konstantinTarletski** [comment]
Do not understand the issue:
when I change "/core/config/default-notebook.bkr"
And after the clicking "new default notebook" application opens the new version.
No need to recompile the project.
Seams all work OK.
