### ISSUE TITLE
Investigate order of control panel menu plugin loading issue

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#49]
For control panel, it looks like the custom menu plugin is loaded before the default one.

**Comment by scottdraves** [comment]
@anglee is this still a problem?
can you clarify what the visible effect for the user is?

**Comment by anglee** [comment]
Unfortunately yes. I still see the Help menu and the settings menu appear in different order from time to time. I will need to look into the code for details.

**Comment by melmac48** [comment]
@anglee if this is just a question of the menus showing up in a different order on occasion, but the user can still do everything then I think we're okay to punt this to v2

**Comment by ildipo** [comment]
This has been fixed through explicit menu item ordering
