### ISSUE TITLE
Duplicate dependancies in groovy and other jvm plugins

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#4901]
Here is the list of libraries in `config\plugins\eval\groovy\lib\` (by the way, I don't understand why the directory is called config; it is a bit confusing):

```
antlr4-runtime-4.5.jar
aopalliance-1.0.jar
asm-3.1.jar
bayeux-api-2.7.0.jar
bcmail-jdk14-1.38.jar
bcmail-jdk14-138.jar
bcprov-jdk14-1.38.jar
bcprov-jdk14-138.jar
bctsp-jdk14-1.38.jar
cglib-2.2.1-v20090111.jar
cometd-java-annotations-2.7.0.jar
cometd-java-client-2.7.0.jar
cometd-java-common-2.7.0.jar
cometd-java-server-2.7.0.jar
cometd-websocket-jetty-2.7.0.jar
commons-cli-1.1.jar
commons-codec-1.9.jar
commons-lang3-3.3.jar
commons-logging-1.2.jar
commons-math3-3.5.jar
cxf-bundle-jaxrs-2.7.7.jar
fluent-hc-4.5.1.jar
geronimo-javamail_1.4_spec-1.7.1.jar
geronimo-servlet_3.0_spec-1.0.jar
graxxia-0.9.jar
groovy-2.3.4.jar
groovy-all-2.4.3.jar
groovy-pathing.jar
groovy.jar
groovycsv-1.0.jar
guava-18.0.jar
guice-3.0.jar
guice-servlet-3.0.jar
httpclient-4.5.1.jar
httpcore-4.4.3.jar
itext-2.1.7.jar
ivy-2.2.0.jar
jackson-core-asl-1.9.13.jar
jackson-jaxrs-1.9.13.jar
jackson-mapper-asl-1.9.13.jar
javax.inject-1.jar
javax.servlet-3.0.0.v201112011016.jar
javax.ws.rs-api-2.0-m10.jar
jaxb-impl-2.1.13.jar
jersey-core-1.17.1.jar
jersey-guice-1.17.1.jar
jersey-server-1.17.1.jar
jersey-servlet-1.17.1.jar
jetty-client-7.6.13.v20130916.jar
jetty-continuation-8.1.13.v20130916.jar
jetty-http-8.1.13.v20130916.jar
jetty-io-8.1.13.v20130916.jar
jetty-jmx-7.6.13.v20130916.jar
jetty-security-8.1.13.v20130916.jar
jetty-server-8.1.13.v20130916.jar
jetty-servlet-8.1.13.v20130916.jar
jetty-util-8.1.13.v20130916.jar
jetty-websocket-7.6.13.v20130916.jar
jsr250-api-1.0.jar
junit-4.4.jar
jvm.jar
log4j-1.2.17.jar
opencsv-2.1.jar
org.abego.treelayout.core-1.0.1.jar
shared.jar
slf4j-api-1.7.6.jar
slf4j-simple-1.7.6.jar
stax2-api-3.1.1.jar
woodstox-core-asl-4.2.0.jar
wsdl4j-1.6.3.jar
xmlschema-core-2.0.3.jar
```

There are two different versions of groovy as well as copies of the same library with different name (the library itself is quite outdated). There is `Junit` there, which makes no sense. Half of the libraries are duplicated in other jvm plugins and in core.

**Comment by scottdraves** [comment]
thanks for the bug report.  there is more duplication between the core and the plugins.

**Comment by scottdraves** [comment]
should share jars between our jvm plugins

**Comment by altavir** [comment]
In my opinion, the whole build system and structure needs a lot of work. Some examples:
1) The build includes JRE. Why? It is easier to install separate one. By the way it is strongly outdated. I understand it for docker builds ot portable builds, but for local builds it is redundunt and drastically increases distribution size.
2) The build includes python... err. And If I am not using python or using external python which is more probable.
3) The distribution contains 80 Mb of source files... It is good for developer, but... it is distribution.
4) Plugins are placed in `config/plugins/eval`. Isn't it too obvious?
5) Execution script is in `build\install\core\bin\core`. I would not found it if not for link in the root directrory.
6) And the most annoying: plugins are not plugins. They are statically compiled and presented as a choice even if you do not have appropriate platform installed. I believe that it is planned  feture, but it still annoying. Could you at least check for plugin platform availability at startup. But in future it would be good to have OSGI.
