### ISSUE TITLE
Plot items should have default initialization for data

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#4904]
Plot items should by default have empty lists for `x` and `y`. This is convenient if one wants to first create plot item and then fill it. Also there should be convenience methods to plot functions and points with errors, but it probably better to separate them from plot items implementation.

**Comment by scottdraves** [comment]
hi, thanks for the suggestion.  can you provide the code that you think should work, so i can understand exactly?

**Comment by altavir** [comment]
I mean that [this line](https://github.com/twosigma/beaker-notebook/blob/master/plugin/jvm/src/main/java/com/twosigma/beaker/chart/xychart/plotitem/XYGraphics.java#L31) should be like this:

```
private List<Number> xs = new ArrayList<>();
```

In this case I can do something like that:

```
Line = new Line();
for(d in data){
  line.x << d.x;
  line.y << d.y;
}
```

For now this code throws error since x and y are not initialized. Of course one can always write `new Line(x: [], y: [])`, but it is not obvious.

**Comment by scottdraves** [comment]
yea this is a good idea, thx.
