### ISSUE TITLE
"TeX" cell type misleading - rename to "KaTeX"?

### ISSUE THREAD

**Issue by kno10** [twosigma/beakerx#4907]
It is misleading because the cells neither support TeX, nor LaTeX, only a rather small subset of the **math mode** of TeX supported by KaTeX. This should IMHO be reflected by a name change.

I am also not a fan of KaTeX, because it apparently does not support the `align*` environment of `amsmath`, which has become my preferred environment. Also, I prefer using it inside of e.g. markdown cells, rather than having standalone cells, where MathJax seems to be standard.

**Comment by scottdraves** [comment]
hi Erich, thank you for your comment.  Sorry you don't like KaTeX, we found the performance made up for the incomplete implementation.  

TeX does work in markdown cells, which are called text cells in beaker.  enclose your math in $ characters. 

While I agree naming it "katex" would be more precise, i think more people would be confused compared to now.

**Comment by scottdraves** [comment]
btw support for real LaTeX is on the agenda: https://github.com/twosigma/beaker-notebook/issues/4816
is that what you are looking for?
results could then be rendered on the page as iframe/pdf right in cell output,
and also exported to multipage report.

**Comment by kno10** [comment]
The confusion about **the "TeX" cell type not being TeX** but only KaTeX will become a larger problem once you have LaTeX! I would rather rename it early...

I understand that KaTeX is faster than MathJax, but it would need similar integration into Markdown and more features to be a replacement for it. And having both just increases memory use of the browser (and this is already my largest problem with Beaker, it won't display on some of my machines because it needs too much memory and loads too much JavaScript). Even on my i7-3770 with 16 GB RAM, e.g. this example notebook https://lab.beakernotebook.com/publications/61602c68-38bb-11e6-8fd1-8f920368b61a?fullscreen=true causes "unresponsive script" warnings; so I wonder how scalable Beaker Notebooks are.

I don't see LaTeX cells as a key use case for me; LaTeX export for printing quality is more interesting to have. PDF export is not sufficient, as it does not allow editing anymore; I am not as much interested in 1:1 visual identity, but rather I would prefer e.g. having tables turned into LaTeX tables. The use case is more along the lines of producing a _draft_, rather than a final document. LaTeX cells could then be used to contain LaTeX fragments that are already written with the final version in mind. But here, KaTeX falls short, e.g. by not supporting `\begin{align*}` or `\intertext` or custom operators, or even just this basic case for teaching linear algebra:

```
\newcommand{\one}{\mathbbm{1}}
\one^T A \one
```

Granted: Mathjax also doesn't support mathbbm, but the newcommand with e.g. mathbb or mathcal font works fine, as does this workaround (and this is exactly why you want some basic `\newcommand` support):

```
\newcommand{\one}{1\!\!1}
\one^T A \one
```

Same readable equation source; just with the one vector rendered differently. For the final print version, I could then use the mathbbm definition instead.
