### ISSUE TITLE
Issues using read.csv in R or possibly other language

### ISSUE THREAD

**Issue by siatpat** [twosigma/beakerx#4908]
Hi Beaker development team, 

I am new to beaker, having being using Jupyter for a while. Now I know a similar issue was closed already (#3062), but would it be possible to always show only head 10 or 100 if someone forget to put the small result like "0" when reading huge files?
Whenever I forget this,  beaker just stop working, cancelling the long operation is not possible and I have to start a fresh notebook.

Thank you

**Comment by altavir** [comment]
I bumped into it myself. `TableDisplay` as far as I can understand loads all data simultaneously. For large data sets it is quite inconvenient. It would be good to have a limit of, say, 1000 rows. Then there could be a warning message and button to show the rest of the data.

**Comment by scottdraves** [comment]
This isn't the table, it's a problem specific to interpreting the results of R, before it gets to the client at all.  See https://github.com/twosigma/beaker-notebook/issues/2815.
It hasn't been closed, these are just duplicates.
