### ISSUE TITLE
Add support for multiple output cells with new UI

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#492]

**Comment by scottdraves** [comment]
@samccone @melmac48 
what is this bug about?

**Comment by samccone** [comment]
If I recall @scottdraves, @anglee pointed out that the old UI used to support multiple outputs per cell.
In the new UI this is not possible.

**Comment by scottdraves** [comment]
@anglee do you have code that reproduces this problem?

**Comment by anglee** [comment]
we don't have APIs to do this in the languages plugins we have yet. This can reproduced by returning the result as type of "OutputContainerCell" and a list of "items", for example: http://sharing.beakernotebook.com/gist/anglee/a589ca698dd3c8f9ecbc

**Comment by melmac48** [comment]
related to #511

**Comment by scottdraves** [comment]
dup of https://github.com/twosigma/beaker-notebook/issues/2997
