### ISSUE TITLE
Custom translators / serialization for JVM languages

### ISSUE THREAD

**Issue by kno10** [twosigma/beakerx#4925]
How do I add custom translators / serialization for JVM languages?

I'd like to use beaker for driving ELKI. But for this, data types such as `DoubleVector`, tabular formats such as `MultipleObjectsBundle`, but also the `Database` and its `Relation`s would need some serialization to allow A) easier data exchange to other languages (e.g. convert a python data frame into a bundle to load into ELKI for analysis) and B) better inspection of the data (e.g. explore a bundle as table to check if preprocessing worked as desired, explore and visualize a relation)

I could not find documentation on how to add such serialization and translation, in particular when there is more than one option (e.g. `DoubleVector` which is an interface around `double[]`; so when translating back sometimes you will want to automatically convert `double[]` into `DoubleVector`).

**Comment by scottdraves** [comment]
There isn't a yet user-level API for this but it has been discussed
https://github.com/twosigma/beaker-notebook/issues/1673
https://github.com/twosigma/beaker-notebook/issues/1674

until that gets done, you can add your own class here:
https://github.com/twosigma/beaker-notebook/blob/f96b6c3d3e4d4b8f2e02c4ff3fc175fa720343ec/plugin/jvm/src/main/java/com/twosigma/beaker/jvm/module/SerializerModule.java
