### ISSUE TITLE
Can't load groovy library

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#4926]
I am trying to load groovy library via language manager by providing full path to its jar, but it does not work. The groovy plugin starts but it can't resolve any class in that jar. Java jars in the same notebook are resolved just fine. 

It could be connected to #4903 since there are extension modules inside jar.

**Comment by scottdraves** [comment]
thanks for the report if you can provide a specific example (eg the jar and how you are trying to call it) it would help.

**Comment by altavir** [comment]
Here is small top level jar: 
[groovymath-0.4.0 - SNAPSHOT.jar.zip](https://github.com/twosigma/beaker-notebook/files/588496/groovymath-0.4.0.-.SNAPSHOT.jar.zip)

It depends on Commons Math, but Commons Math should be included in beaker class path.

By the way, I am going to expand this library to make some analogue for scipy in Groovy and use it in Beaker. The main problem is lack of public interfaces for beaker output containers such as plots and `TableDisplay`.

**Comment by scottdraves** [comment]
and what code should work after the jar is loaded?

**Comment by altavir** [comment]
At least import. Last time I checked I could not see any classes from this jar. I can't check right now. Will write an example as soon as I can.
