### ISSUE TITLE
typescript typings?

### ISSUE THREAD

**Issue by marisbest2** [twosigma/beakerx#4948]
Does anyone have / want to have Typescript typings for the JS stuff? This would include defining Beaker types in TS and thus make it easier to develop a TS plugin (and JS too)

**Comment by scottdraves** [comment]
hi, thanks for your question.
not sure what you mean but supporting typescript in the JS plugin in on the agenda:
https://github.com/twosigma/beaker-notebook/issues/4012

**Comment by marisbest2** [comment]
I mean like a beaker.d.ts. It would just specify the API + the types of the JS exports. No special code needed.

**Comment by marisbest2** [comment]
(obviously you would need to add a TS compile step, but I was just thinking about typing transform.js and also the beaker object API

**Comment by scottdraves** [comment]
thanks for the suggestion but we are not doing TS yet.
