### ISSUE TITLE
research hotswap for frontend files

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#4953]
does installing a grunt watcher work?

**Comment by ghost** [comment]
If this is what I think it is , you might want to integrate browserSync within the watch. I managed to integrate it with gulp and it worked perfectly fine.

**Comment by scottdraves** [comment]
thx for the tip but i think this got done, at least to the satisfaction of kuba.  i don't use it myself:
https://github.com/twosigma/beaker-notebook/commit/0e43699bf2a77fc670a8aabe3b704f69728c3ac5
