### ISSUE TITLE
"The application “Beaker.app” can’t be opened." on Mac

### ISSUE THREAD

**Issue by jolespin** [twosigma/beakerx#4968]
I downloaded http://d299yghl10frh5.cloudfront.net/beaker-notebook-1.7.1-0-g6dac09a-electron-mac.dmg and I got this error once I tried to use it 
<img width="420" alt="screen shot 2016-11-30 at 11 58 28 am" src="https://cloud.githubusercontent.com/assets/9061708/20768889/857c83b4-b6f4-11e6-8e65-4eac2fe5a6a5.png">

My Mac specs are: 
![image](https://cloud.githubusercontent.com/assets/9061708/20768912/9c0eedc4-b6f4-11e6-9453-b428ce68ca23.png)

**Comment by scottdraves** [comment]
Hi thanks for the report.  Do you see any errors if you run it in a terminal, like this:
```
/Applications/Beaker.app/Contents/MacOS/Electron
```
?

**Comment by jolespin** [comment]
Wow, that worked... Any idea why clicking the App doesn't work?

**Comment by scottdraves** [comment]
no idea

**Comment by mdmadhu** [comment]
Hi, I am also unable to start the Electron version of Beaker Notebook (beaker-notebook-1.7.1-0-g6dac09a-electron-mac). Clicking the Beaker app icon from the Applications folder opens Beaker in the dock, but nothing else happens. If I click on the Beaker dock icon, the icon just disappears.

I tried starting the app from Terminal using the path given in the thread above, and again the app icon appears on the dock, but nothing else happens. Below are the warning messages I get:
` /Applications/Beaker.app/Contents/MacOS/Electron`
`(electron) companyName is now a required option to crashReporter.start`
`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`
`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`
`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`
`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`
`Using port 32326 for main thread IPC`

But when I click on the app icon on the dock, the app bails out and here is what I see in the terminal:
`(electron) 'activate-with-no-open-windows' event is deprecated. Use 'activate' event instead.`
`[TypeError: Error processing argument at index 0, conversion failure from undefined]` 

Any idea what's going on and how to fix this? Thanks!

**Comment by scottdraves** [comment]
sorry does not look familiar
