### ISSUE TITLE
Visual artifact about Input cell hidden in Lock mode

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#498]
Hide the input cell by click on the cell menu, uncheck `show input cell`.
Lock the notebook by Menu Bar->Notebook->Lock
The text "Cell Output" and the evaluator name are overlapped.
![image](https://cloud.githubusercontent.com/assets/1767921/4013388/b8aed296-2a15-11e4-986f-02e3c4109391.png)

**Comment by samccone** [comment]
fixed in #499
