### ISSUE TITLE
Beaker does not compile java

### ISSUE THREAD

**Issue by ivan047** [twosigma/beakerx#4995]
Whenever I try to create java cell and compile it by pressing "Run" it starts evaluation and does not end

**Comment by scottdraves** [comment]
hi ivan, thanks for the report.
what version of beaker are you running (electron version?  portable version?)
what is your OS version?

**Comment by ivan047** [comment]
Hi,

I am running desktop version 1.7.1 on windows 10,  using beaker.command.bat
I am downloading elctron to see how it is there

**Comment by scottdraves** [comment]
thx we will look into it.

**Comment by ivan047** [comment]
Same issue arises in electron version btw
