### ISSUE TITLE
Display PNG from Clojure

### ISSUE THREAD

**Issue by dcmcshan** [twosigma/beakerx#4999]
Hi there.  I am going to be featuring Beaker in an upcoming paper on computational biochemistry.  Everything seems to work as expected, but I am unwise in the ways of displaying images.  So, I have a java method I call in clojure (.exportToObject n "png:w300,h300,b32,#00ffff00").  It outputs an array of bytes for a PNG image.  How do I get Beaker to display this? 

Thanks much!
Dan

**Comment by scottdraves** [comment]
Hi Dan thanks for your question.  In groovy/java it's done like this:
```
import java.awt.image.BufferedImage
BufferedImage im = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB)
g2 = im.createGraphics()
g2.drawLine(0,0,100,100)
im
```
the last line is returning `im` the `BufferedImage`, which Beaker recognizes and displays.
Here it is in action in a tutorial:
https://pub.beakernotebook.com/publications/04ced174-fba9-11e5-b8c1-df4d629d60e2?fullscreen=false

I believe if that were translated to clojure, and you substituted filling in your raster for drawing a line, then it would work.  Please let me know if that works for you.  Thanks, -Scott

**Comment by dcmcshan** [comment]
Cool.  That works well.  Thanks.   Now, what if I want a table of images... possible?

**Comment by scottdraves** [comment]
Yes OutputContainers have a variety of formats including a 2D table:
https://lab.beakernotebook.com/publications/caf44ede-fb8a-11e5-b837-3f4e9394881e?fullscreen=false
