### ISSUE TITLE
recent files menu has duplicates and formatting

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5]
![screen shot 2014-01-24 at 10 57 28 pm](https://f.cloud.github.com/assets/963093/2000925/25b8e304-8575-11e3-8145-1e3f3fe92df9.png)

**Comment by scottdraves** [comment]
$ cat ~/.beaker/conf/recentDocuments 
file:julia-and-python.bkr
file:/Users/spot/beaker-notebook/julia-and-python.bkr
file:/Users/spot/beaker-notebook/julia-and-python.bkr

**Comment by scottdraves** [comment]
![screen shot 2014-01-24 at 11 13 29 pm](https://f.cloud.github.com/assets/963093/2000947/171387ee-8577-11e3-8ea9-759ed9b62d6e.png)

**Comment by scottdraves** [comment]
this can still happen.

**Comment by melmac48** [comment]
please try to get a consistent repro for this and if no close it. thnx.
