### ISSUE TITLE
Create a unified way of recording/reading user preferences

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#50]
Create a unified way of recording/reading user preferences and avoid hardwiring code.

**Comment by scottdraves** [comment]
doesn't beaker.conf.json do this?

**Comment by melmac48** [comment]
@anglee what are the issues here? thnx

**Comment by anglee** [comment]
Indeed beaker.conf.json was introduced to address this issue. https://github.com/twosigma/beaker-notebook/commit/6f20df19ab71ff8645c0a261227218a28d98fb6b
