### ISSUE TITLE
Cannot render OpenAI Gym

### ISSUE THREAD

**Issue by icyblade** [twosigma/beakerx#5000]
I'm working on deep reinforcement learning, using OpenAI Gym and Beaker Notebook. However, Beaker cannot render Gym successfully.

Jupyter doesn't have native support yet, but [this script](http://nbviewer.jupyter.org/github/patrickmineault/xcorr-notebooks/blob/master/Render%20OpenAI%20gym%20as%20GIF.ipynb) works for me.

I tried to record the frames `frames.append(env.render(mode='rgb_array'))`, pass to beaker `beaker.frames = frames`, and render it using [jsgif](https://github.com/antimatter15/jsgif), but it took me more than 15 minutes on the single line `beaker.frames = frames`

As Beaker is awesome, maybe there's an efficient way?

Thanks in advance!

Related links:
http://nbviewer.jupyter.org/github/patrickmineault/xcorr-notebooks/blob/master/Render%20OpenAI%20gym%20as%20GIF.ipynb
http://stackoverflow.com/questions/40195740/how-to-run-openai-gym-render-over-a-server

**Comment by scottdraves** [comment]
Hi Thanks glad you like it, that sounds really cool.

We have a demo where in R you create and display an animated gif.  I believe it would work in Python as well: https://pub.beakernotebook.com/publications/560c55c5-1ef7-41fa-ab8c-71b0b3aa68c3?fullscreen=true

The animated results don't show up in the published version, but they appear inline correctly when you run the notebook.

**Comment by icyblade** [comment]
Thanks for the help, it's brilliant to save the animation into local drive, and load it from HTML ! Here's my code:


Python cell:
```python
import env
from PIL import Image

env = gym.make('Breakout-v0')
env.reset()
frames = []
while True:
    frames.append(Image.fromarray(env.render(mode='rgb_array')))  # save each frames
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        if reward:
            print(reward)
        break
        
with open('/root/.beaker/v1/web/openai_gym.gif', 'wb') as f:  # change the path if necessary
    im = Image.new('RGB', frames[0].size)
    im.save(f, save_all=True, append_images=frames)
```
HTML cell:
```html
<img id="gif" src=""/>
<script>document.getElementById("gif").src="/user/openai_gym.gif?"+new Date().getTime();</script>
```

I wish it helps :-)
