### ISSUE TITLE
Export closures

### ISSUE THREAD

**Issue by nviennot** [twosigma/beakerx#5011]
I think it would be useful to export closures in the global `beaker` object.
In the following, the language that exports a closure is called the _server_, and the language that calls that exported closure is called the _client_.

The way it would work is to expose a proxy-rpc object in client language. When a call on the client side is issued, the proxy-rpc object serializes the arguments and pass the invocation to beaker, which then invokes the closure on the _server_ language side. Upon return, the return value is serialized, and passed to the client.

Is this a good idea? How hard is this to implement? Should I take a stab at it?

**Comment by scottdraves** [comment]
Hi yes that sounds very cool.  I think it would!  it gets complicated when the functions are higher-order but I don't see a problem with it.  Please email me as there are some changes brewing that might effect the implementation.

**Comment by altavir** [comment]
There are some possible problems here. While regular closure is executed immediatly and in most cases is not interruptable, the rpc call is long operation and could be interrupted and throw a lot of bizare exceptions. Also closure execution is usually blocking operation which could rise performance issues. It is possible that it ould be better to develop a specific wrapper for such requests, which could be called as a regular closure, but which provides some additional control options.
