### ISSUE TITLE
List of ggplots not displayed

### ISSUE THREAD

**Issue by aolney** [twosigma/beakerx#5015]
I'm following the tutorial [here](http://www.strengejacke.de/sjPlot/sjp.glmer/) which creates ggplot2 based plots.

The problem is when the `sjp.glmer` produces a series of plots rather than a single faceted plot.

A single faceted plot is rendered fine by beaker.

However, when a series of plots is produced, only one is displayed (I believe the last of the series).

Is there a way to display a list of ggplots in a beaker output cell?

To replicate:
```
# load packages
library(sjPlot)
library(sjmisc)
# load sample data set.
data(efc)
set_theme(theme = "forest", 
          geom.label.size = 3, 
          axis.textsize = .9, 
          axis.title.size = .9)

# fit model
library(lme4)
# create binary response
sleepstudy$Reaction.dicho <- 
  dicho(sleepstudy$Reaction, dich.by = "median")
# fit model
fit <- glmer(Reaction.dicho ~ Days + (Days | Subject),
             sleepstudy, family = binomial("logit"))

# sort all predictors
sjp.glmer(fit,
          facet.grid = FALSE,
          sort.est = "sort.all",
          y.offset = .4)
```
Only one graph is displayed; the example shows two.

**Comment by aolney** [comment]
I have a solution for this package, which also suggests a more general workaround.

For this package, one can use `plot_grid`:

```
# load packages
library(sjPlot)
library(sjmisc)
# load sample data set.
data(efc)
set_theme(theme = "forest", 
          geom.label.size = 3, 
          axis.textsize = .9, 
          axis.title.size = .9)

# fit model
library(lme4)
# create binary response
sleepstudy$Reaction.dicho <- 
  dicho(sleepstudy$Reaction, dich.by = "median")
# fit model
fit <- glmer(Reaction.dicho ~ Days + (Days | Subject),
             sleepstudy, family = binomial("logit"))

# sort all predictors
p <- sjp.glmer(fit,
          facet.grid = FALSE,
          sort.est = "sort.all",
          y.offset = .4)
plot_grid(p$plot.list)
```

The more general solution **which I have not tried** is to use another R package that provides a grid and can capture a list of ggplots. `gridExtra` appears to be a good candidate for such a package, and an example for handling a list of plots is [here](http://stackoverflow.com/questions/10706753/how-do-i-arrange-a-variable-list-of-plots-using-grid-arrange). 

Assuming that one more conventionally had ggplots stored in multiple individual variables, `gridExtra` could be used [in the standard way](http://www.imachordata.com/extra-extra-get-your-gridextra/).

**Comment by scottdraves** [comment]
cool thanks for the report and resolution i appreciate your circling back.
