### ISSUE TITLE
Clojure classpath problem

### ISSUE THREAD

**Issue by dcmcshan** [twosigma/beakerx#5016]
I am trying to access a clojure lein project in beaker.  I can do this in a simple form by including the uberjar (in beakertest/target/beakertest-0.1.0-SNAPSHOT-standalone.jar), but when I want to use an external jar, it seems to have issue and can't find the external jar.

[qtp1131040331-20] ERROR com.twosigma.beaker.clojure.util.ClojureEvaluator - java.lang.ClassNotFoundException: org.joda.time.ReadableDateTime, compiling:(clj_time/core.clj:1:1)

Wondering what I am missing.  org.joda.time.ReadableDateTime is in the jar file, but seems to not be in the classpath as per (println (seq (.getURLs (java.lang.ClassLoader/getSystemClassLoader))))

I have created a simple project by way of example:
https://github.com/dcmcshan/beakertest

Thanks for your help!  Really liking Beaker!

**Comment by dcmcshan** [comment]
After some futher investigation, adding ALL the classes manually...

I get to this error:

ERROR com.twosigma.beaker.clojure.util.ClojureEvaluator - java.lang.Exception: namespace 'clj-time.format' not found, compiling:(clj_time/coerce.clj:1:1)

This might be a bit of clojure weirdness - the class name is "cli-time" but the file name is "cli_time".  Perhaps this is confusing your loader?

Thanks!

**Comment by dcmcshan** [comment]
I have sorted that out, only to be confronted with

[qtp1131040331-17] ERROR com.twosigma.beaker.clojure.util.ClojureEvaluator - java.lang.IllegalAccessError: from-date does not exist, compiling:(beakertest/core.clj:1:1)

core.clj compiles normally in emacs/lein

**Comment by dcmcshan** [comment]
I can now report that fully qualifying the references does "solve" the problem.  Still, this seems like something that should be fixed.

clj-time.coerce/from-long

**Comment by scottdraves** [comment]
thank you for the report and follow-up explanation.
sorry i don't have the bandwidth to handle this right now.
will look at it later.
