### ISSUE TITLE
Clojure autotranslate  maps

### ISSUE THREAD

**Issue by dcmcshan** [twosigma/beakerx#5017]
[{:A 1, :B 2} {:A 3, :B 4} {:A 5, :B 6}]

almost auto translates correctly, - it results in a table of the right dimensions, but there are no values in the cells...

Thanks!

**Comment by scottdraves** [comment]
thank you, will get back to you about this.

**Comment by dcmcshan** [comment]
As additional data point,

['(1 2) '(3 4) '(5 6)]  

works as expected.

**Comment by scottdraves** [comment]
hi sorry i won't have time to look at this for a while, we are focused on the core architecture right now.

**Comment by dcmcshan** [comment]
Totally appreciate that you are focused on core architecture.  This is a bit of a show stopper for me, though. I have a presentation on applying Beaker to the computational biology domain next Monday.  Everything works as expected, except for the output of maps, which is pretty fundamental to Clojure.  I can't imagine this is a particular complicated problem.  Can you maybe give me a clue as to where I should be looking?  I'll see if I can't figure it out.

**Comment by dcmcshan** [comment]
As a further data point,

[{"A" 1, "B" 2} {"A" 3, "B" 4} {"A" 5, "B" 6}]

works as expected.  

So I think it's probably something to do with how you interpret keywords...
"A" works, :A does not.

**Comment by dcmcshan** [comment]
Finally, this appears to be a functional work-around (if entirely kludgey)

(clojure.set/rename [{:A 1, :B 2} {:A 3, :B 4} {:A 5, :B 6}] {:A "A", :B "B"})
