### ISSUE TITLE
How to embed an existing webpage in beaker notebook?

### ISSUE THREAD

**Issue by hlslxy** [twosigma/beakerx#5018]
Hi,

I am new in beaker, so sorry for asking such question.

I am trying to embed a webpage in my beaker html cell, but I don't know how to do it.
In normal html page I do this by something like:
    <html>
        <head>
            <script src="jquery.js"></script>
            <script>
                $(function(){
                    $("#includedContent").load("mypage.html");
                });
            </script>
        </head>
        <body>
           <div id="includedContent"></div>
        </body>
    </html>

Thanks for any suggestion!

**Comment by scottdraves** [comment]
hi, no problem glad you are here and thank you for asking.
do you mean like with an iframe?  those should work.
