### ISSUE TITLE
Beaker object hanging and throwing errors after accessing from Scala ... storing bad state to disk?

### ISSUE THREAD

**Issue by mkac** [twosigma/beakerx#5019]
I'm new to Beaker and was able to successfully run the following snippet in a Python3 cell:

```{python}
beaker.x = 1
```

and then load it in an R cell with this snippet:

```{R}
beaker::get("x")
```

Finally, I tried loading this in Scala:
```
beaker.get("x")
```

and I got this error:
```
java.lang.NullPointerException
  at com.twosigma.beaker.NamespaceClient.get(NamespaceClient.java:183)
  at beaker$.selectDynamic(:53)
  ... 50 elided
```

so I restarted Beaker and tried again and got an error when I ran the R snippet:
```
Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input
```

I restarted one more time and now the first cell hangs indefinitely:
```{python}
beaker.x = 1
```

This seems like Beaker is persisting some corrupted state somewhere since the problem persisted and got worse with each restart.

Anyone have insights here? I'm running on Mac OS X and I used the base installer located [here](http://beakernotebook.com/getting-started?osx&scroll).

**Comment by mkac** [comment]
ping ... anyone have any thoughts?

**Comment by scottdraves** [comment]
hi sorry we are focused on the core architecture right now i don't have the bandwidth to look at this.

**Comment by mkac** [comment]
Understood, thanks for responding.
