### ISSUE TITLE
Connect Beaker to Aster Database using JDBC

### ISSUE THREAD

**Issue by metromark** [twosigma/beakerx#5021]
I'm trying to connect Beaker to Aster DB using SQL in Language Manager. Here's my setup:

Default data source: jdbc:ncluster://hostname:port/database?user=username&password=password

Driver: /home/drivers/noarch-aster-jdbc-driver.jar

To which it results to an error, "com.twosigma.beaker.sqlsh.utils.DBConnectionException: Connection URI:" No suitable driver
I was able to connect other platform using the above setup, but unable using beaker.

Additional info:
Driver name (inside the jar) for this is com.asterdata.ncluster.Driver

**Comment by scottdraves** [comment]
unfortunately jdbc has bug (or design flaw?) where it ignores the classpath for loading jars.
postgres (you asked about it on facebook, right?) should be fine though as it comes preloaded.
the next version of beaker will have more jdbc jars, but still, not this aster one.
however you can at least load them by putting the jar into a specific directory.
https://github.com/twosigma/beaker-notebook/commit/5e5d6c26dc1d4b1b8ee8288b51671007d48799ce

**Comment by scottdraves** [comment]
Here's the JDBC code with the problem:
http://www.lookatsrc.com/source/java/sql/DriverManager.java?a=java:java
see line 640
```
ClassLoader callerCL = caller != null ? caller.getClassLoader() : null;
```

**Comment by scottdraves** [comment]
It seems likely there is a workaround; if so please let us know!
