### ISSUE TITLE
External CSS

### ISSUE THREAD

**Issue by dcmcshan** [twosigma/beakerx#5022]
How would I add an external stylesheet to a notebook? 

Thanks!

**Comment by aolney** [comment]
Are you trying to style an html cell, or are you trying to change the appearance of beaker itself?

**Comment by dcmcshan** [comment]
html cell.  I have some javascript (yasqe.js) that has some svg that isn’t rendering correctly.

**Comment by aolney** [comment]
Perhaps you got further than me, but in the dev console I'm getting "YASQE not defined" with the code below. Sorry I'm not a dev here but thought I might be able to help.

```
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Example</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/yasqe/2.11.9/yasqe.min.css">
  <script src="https://cdn.jsdelivr.net/yasqe/2.11.9/yasqe.min.js"></script>
  <script type="text/javascript">
    var yasqe = YASQE(document.getElementById("showcase"), {
    sparql: {
      showQueryButton: true, 
      callbacks:{
        success: function(data){
          console.log("success", data);
        }
      }
    }
  });
</script>
</head>
<body>

<div id="showcase"></div>

</body>
</html>
```
