### ISSUE TITLE
Refreshing jars

### ISSUE THREAD

**Issue by dcmcshan** [twosigma/beakerx#5026]
Is there a way to refresh jars once loaded?  I am working in clojure, and it would be super helpful if there were an easy way to reload the jar to reflect the changes I am making on the native clojure side.

Thanks!

**Comment by aolney** [comment]
You should be able to do this from `Notebook -> Language manager`

There will be a tab for each language plugin that has been loaded in your notebook.

Typically there is a `Reset environment` button that will clear things. Also, if you have your jar listed in the class path box under this tab, you should be able to press `Set` next to that box to reload everything in the classpath.
