### ISSUE TITLE
Docker performance decline between version 1.6 and 1.7.1

### ISSUE THREAD

**Issue by aolney** [twosigma/beakerx#5028]
The current docker image seems slow in the UI (Chrome)

I timed the start up as well

- 1.6 got to "Submit this password" in 3 seconds
- 1.7.1 got to it in 12 seconds

`docker stats` shows virtually identical resource usage for both containers at idle. On start up `docker stats` doesn't show anything other that 1.7.1 seemingly not consuming much until right before "Submit this password appears"

`Linux monkmonk 4.7.0-1-amd64 #1 SMP Debian 4.7.8-1 (2016-10-19) x86_64 GNU/Linux`

**Comment by scottdraves** [comment]
hi that is interesting ty for the report.  unfortunately i don't have time to debug it right now.
