### ISSUE TITLE
Python and iPython issues

### ISSUE THREAD

**Issue by kalmdown** [twosigma/beakerx#5031]
When trying to enable Python and iPython Beaker gives me the "Language Error
Failed to start \<Language\>." error popup.

**I have attempted to add Python and iPython to the beaker.pref.json file based on the following _which_ queries:**
/Users/212316291/anaconda/bin
==> which python
/Users/212316291/anaconda/bin/python

/Users/212316291/anaconda/bin
==> which ipython
/Users/212316291/anaconda/bin/ipython

**With that I edited my beaker.pref.json to:**
{
   "languages" : {
    "IPython" : {
      "path" : "/Users/212316291/anaconda/bin"
    },
    "Python3" : {
      "path" : "/Users/212316291/anaconda/bin"
    }
  },
  "autocomplete-parameters" : "true",
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : true,
  "edit-mode" : "default"
}

**This is the Console output I get when I try to turn on Python and iPython:**
Feb 20 17:02:24 SFO1212316291P Beaker[35403]: Beaker App start JVM and launch browser
Feb 20 17:02:37 SFO1212316291P Beaker[35403]: [main] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - starting nginx instance (/Applications/Beaker.app/Contents/Resources/dist/nginx)
Feb 20 17:02:37 SFO1212316291P Beaker[35403]: [Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (2: No such file or directory)
Feb 20 17:02:37 SFO1212316291P Beaker[35403]: [main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
Feb 20 17:02:37 SFO1212316291P Beaker[35403]: [main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted A: LocalFsVolume [/Users/212316291]
Feb 20 17:02:37 SFO1212316291P Beaker[35403]: [main] INFO com.twosigma.beaker.core.module.elfinder.impl.DefaultFsService - mounted B: LocalFsVolume [/]
Feb 20 17:02:37 SFO1212316291P Beaker[35403]: [main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802
Feb 20 17:02:38 SFO1212316291P Beaker[35403]: 
	Connecting to http://127.0.0.1:8801/
Feb 20 17:02:39 SFO1212316291P Google Chrome[744]: objc[744]: __weak variable at 0x618002a34e50 holds 0x2121212121212121 instead of 0x6100036307a0. This is probably incorrect use of objc_storeWeak() and objc_loadWeak(). Break on objc_weak_error to debug.
Feb 20 17:03:04 SFO1212316291P Beaker[35403]: [qtp406765571-21] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - Running
	[qtp406765571-21] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - 0: /Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/ipythonPlugins/python3/python3Plugin
	[qtp406765571-21] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - 1: 8810
Feb 20 17:03:04 SFO1212316291P Beaker[35403]: [qtp406765571-21] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - Done starting Python3
Feb 20 17:03:04 SFO1212316291P Beaker[35403]: [Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>2017/02/20 17:03:04 [error] 35424#0: *33 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /6dac09a/python3.739584461917/login HTTP/1.1", upstream: "http://127.0.0.1:8810/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
Feb 20 17:03:05 --- last message repeated 5 times ---
Feb 20 17:03:05 SFO1212316291P Beaker[35403]: [Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>2017/02/20 17:03:05 [error] 35424#0: *33 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /6dac09a/python3.739584461917/login HTTP/1.1", upstream: "http://127.0.0.1:8810/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
Feb 20 17:03:06 --- last message repeated 3 times ---
Feb 20 17:03:06 SFO1212316291P Beaker[35403]: [Thread-17] INFO com.twosigma.beaker.core.rest.StreamGobbler - Python3-stderr>[I 17:03:06.298 NotebookApp] Serving notebooks from local directory: /Applications/Beaker.app/Contents/Resources/dist
	[Thread-17] INFO com.twosigma.beaker.core.rest.StreamGobbler - Python3-stderr>[I 17:03:06.298 NotebookApp] 0 active kernels 
	[Thread-17] INFO com.twosigma.beaker.core.rest.StreamGobbler - Python3-stderr>[I 17:03:06.298 NotebookApp] The Jupyter Notebook is running at: http://127.0.0.1:8810/
	[Thread-17] INFO com.twosigma.beaker.core.rest.StreamGobbler - Python3-stderr>[I 17:03:06.298 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Feb 20 17:03:06 SFO1212316291P Beaker[35403]: [Thread-17] INFO com.twosigma.beaker.core.rest.StreamGobbler - Python3-stderr>[W 17:03:06.489 NotebookApp] 403 POST /login?next=%2F (127.0.0.1): '_xsrf' argument missing from POST
	[Thread-17] INFO com.twosigma.beaker.core.rest.StreamGobbler - Python3-stderr>[W 17:03:06.493 NotebookApp] 403 POST /login?next=%2F (127.0.0.1) 4.87ms referer=http://127.0.0.1:8801/beaker/
Feb 20 17:03:11 SFO1212316291P eospreflightagent[35515]: objc[35515]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x7fffb6d4f6e0) and /usr/lib/libFDR_osx.dylib (0x1043bdad8). One of the two will be used. Which one is undefined.
Feb 20 17:03:11 SFO1212316291P eospreflightagent[35515]: objc[35515]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x7fffb6d4f6e0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x104321de8). One of the two will be used. Which one is undefined.
Feb 20 17:03:39 SFO1212316291P Beaker[35403]: [qtp406765571-19] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - Running
	[qtp406765571-19] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - 0: /Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin
	[qtp406765571-19] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - 1: 8807
Feb 20 17:03:39 SFO1212316291P Beaker[35403]: [qtp406765571-19] INFO com.twosigma.beaker.core.rest.PluginServiceLocatorRest - Done starting IPython
Feb 20 17:03:39 SFO1212316291P Beaker[35403]: [Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>2017/02/20 17:03:39 [error] 35424#0: *33 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /6dac09a/ipython.184458512148/login HTTP/1.1", upstream: "http://127.0.0.1:8807/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
Feb 20 17:03:40 --- last message repeated 6 times ---
Feb 20 17:03:40 SFO1212316291P Beaker[35403]: [Thread-4] INFO com.twosigma.beaker.core.rest.StreamGobbler - nginx-stderr>2017/02/20 17:03:40 [error] 35424#0: *33 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /6dac09a/ipython.184458512148/login HTTP/1.1", upstream: "http://127.0.0.1:8807/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
Feb 20 17:03:41 --- last message repeated 2 times ---
Feb 20 17:03:41 SFO1212316291P Beaker[35403]: [Thread-21] INFO com.twosigma.beaker.core.rest.StreamGobbler - IPython-stderr>[I 17:03:41.228 NotebookApp] Serving notebooks from local directory: /Applications/Beaker.app/Contents/Resources/dist
	[Thread-21] INFO com.twosigma.beaker.core.rest.StreamGobbler - IPython-stderr>[I 17:03:41.228 NotebookApp] 0 active kernels 
	[Thread-21] INFO com.twosigma.beaker.core.rest.StreamGobbler - IPython-stderr>[I 17:03:41.228 NotebookApp] The Jupyter Notebook is running at: http://127.0.0.1:8807/
	[Thread-21] INFO com.twosigma.beaker.core.rest.StreamGobbler - IPython-stderr>[I 17:03:41.228 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Feb 20 17:03:41 SFO1212316291P Beaker[35403]: [Thread-21] INFO com.twosigma.beaker.core.rest.StreamGobbler - IPython-stderr>[W 17:03:41.410 NotebookApp] 403 POST /login?next=%2F (127.0.0.1): '_xsrf' argument missing from POST
Feb 20 17:03:41 SFO1212316291P Beaker[35403]: [Thread-21] INFO com.twosigma.beaker.core.rest.StreamGobbler - IPython-stderr>[W 17:03:41.416 NotebookApp] 403 POST /login?next=%2F (127.0.0.1) 6.66ms referer=http://127.0.0.1:8801/beaker/

**Comment by scottdraves** [comment]
hi, the next release will have a new architecture that solves this problem. i don't have the bandwidth to debug this one right now, sorry.
