### ISSUE TITLE
Failed to start IPython

### ISSUE THREAD

**Issue by olivermel** [twosigma/beakerx#5032]
I'm currently installing beaker on Centos 6
and i have manually installed the dependencies (install-dependencies.sh)

currently my beaker.pref.json file looks like this

{
  "languages" : {
    "IPython" : {
      "path" : "/usr/bin"
    },
    "Python" : {
      "path" : "/usr/bin"
    }
  },
  "pref-format": "1",
  "advanced-mode" : false,
  "allow-anonymous-usage-tracking" : true
  "autocomplete-parameters": "true"
}

as ipython is located in my /usr/bin 

any ideas as to how to fix this?

**Comment by scottdraves** [comment]
dup of https://github.com/twosigma/beaker-notebook/issues/5034
