### ISSUE TITLE
Beaker fails to start Python3 and Julia

### ISSUE THREAD

**Issue by lissonc** [twosigma/beakerx#5033]
I have been unsuccessfully trying to get Beaker to work with Python3 and Julia for about a week now. Perhaps you can help me out.

I followed the instructions [here](http://beakernotebook.com/getting-started) and have even reinstalled both Julia and Beaker since – without success. The error message when trying to start the Python kernel in Beaker (same with Julia) is the following:

![5oi9g](https://cloud.githubusercontent.com/assets/4765944/23345118/b269a006-fc80-11e6-9f94-c65b8b9d6a2a.png)

`which python3` returns `/Users/username/anaconda/bin/python3`. I initially used this path in my `beaker.pref.json` but it did not work. Following some advice on StackExchange I then did a separate installation of Python3 at `/Users/username/anaconda/envs/py35/bin` – just to match the path in the example on the website more closely – and pointed `beaker.pref.json` to it (see below).

My `beaker.pref.json` file looks like this:

```
{
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : true,
  "languages" : {
    "IPython" : {
      "path" : "/Users/constantin/anaconda/bin"
    },
    "Python3" : {
      "path" : "/Users/constantin/anaconda/envs/py35/bin"
    }
  },
  "advanced-mode" : false,
  "edit-mode" : "default"
}
```

Note that the directory really is called `/py35/` instead of `/py3k`. The same error message still appears and I have run out of ideas. I'd greatly appreciate any help you can provide!

**Comment by scottdraves** [comment]
hi, the next release will have a new architecture that solves this problem.  i don't have the bandwidth to debug this one right now, sorry.

**Comment by lissonc** [comment]
Thanks for letting me know.
