### ISSUE TITLE
failed to start IPython

### ISSUE THREAD

**Issue by olivermel** [twosigma/beakerx#5034]
I'm currently installing beaker on Centos 6
and i have manually installed the dependencies (install-dependencies.sh)

currently my beaker.pref.json file looks like this

{
  "languages" : {
    "IPython" : {
      "path" : "/usr/bin"
    },
    "Python" : {
      "path" : "/usr/bin"
    }
  },
  "pref-format": "1",
  "advanced-mode" : false,
  "allow-anonymous-usage-tracking" : true
  "autocomplete-parameters": "true"
}

as ipython is located in my /usr/bin 

any ideas as to how to fix this?

**Comment by scottdraves** [comment]
hi, this wiki might help: https://github.com/twosigma/beaker-notebook/wiki/Using-a-Preexisting-Python

btw "Python" is not a language in Beaker, it's either IPython (for python2) or Python3 (for python3).

the next release will have a new architecture that solves this problem.
