### ISSUE TITLE
Docker server with Electron client

### ISSUE THREAD

**Issue by abejenaru** [twosigma/beakerx#5037]
Hi, I tried the option to connect to another server - the Docker container - in the "Electron" Beaker, but it doesn't seem to do anything; the Change server popup just remains open (Beaker 1.7.1 Windows).
Is this a supported use case?

I started the container using:
`docker run -v /c/Users/me/docker_volumes/beaker:/home/beaker/host -p 127.0.0.1:8801:8801 -t beakernotebook/beaker su -m beaker -c "export PATH=$PATH:/usr/sbin && /home/beaker/src/core/beaker.command --connect-host 127.0.0.1 --listen-interface \*"`

**Comment by scottdraves** [comment]
hi, thanks for the report.  i am not sure why it doesn't work but i don't have the bandwidth to look into it, sorry.
