### ISSUE TITLE
make java side of ipywidgets implementation complete

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5041]
we got IntSlider (yea!) now fill in the rest, and handle every attribution.

**Comment by konstantinTarletski** [comment]
useful links:
https://github.com/jupyter-widgets/ipywidgets
http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html

unimplemented 20 items from 42:

Accordion			--- READY
BoundedFloatText	--- READY
BoundedIntText	--- READY
IntText			--- READY
ButtonStyle		---SKIPPED
**Represents a game controller**
Controller			---SKIPPED
**Represents a gamepad or joystick axis.**
ControllerAxis		---SKIPPED
**Represents a gamepad or joystick button.**
ControllerButton	---SKIPPED
FloatRangeSlider	--- READY
FloatText			--- READY
HTMLMath		--- READY
IntRangeSlider		--- READY
Play				--- READY
ProgressStyle		---SKIPPED
SelectionSlider		--- READY
SliderStyle			---SKIPPED
ToggleButtons		--- READY
Valid				--- READY
DirectionalLink		--- READY
Link				--- READY


**Improvements:**

In "ValueWidget" added methods like "getInteger(Object input)" 
It allow to use widgets more flexible, not only with certain types.
Example : 
```
import com.twosigma.beaker.widgets.integers.IntRangeSlider
w = new IntRangeSlider()
w.value = ["10",49.6]
w.orientation = "horizontal"
//w.orientation = "vertical"
display(w)
```
As You can see it is "Int" slider.
but I put to value String and Float and it is automaticlly converted to "Int"

or even:
`w.value = ["10",[49.6]]`
also to value can be passed not array but `java.util.Collection`:

```
import com.twosigma.beaker.widgets.integers.IntRangeSlider
import java.util.Collection

Collection<Object> list = new ArrayList<>()
list.add(["19"])
list.add("53")

w = new IntRangeSlider()
w.value = list
w.orientation = "horizontal"
//w.orientation = "vertical"
display(w)
```
This conversion works not only with "Int" but also with "String", "Double" (Float) and Boolean
Also it works not only with `value` but with other properties like `min` , `max` , `step`

**Comment by soerenklingner** [comment]
How do i observe a IntSlider widget? When the slider value changes i want a function to be called.

Where can i find a good documentation of the beakerx java?
