### ISSUE TITLE
configure view for junit tests results on jenkins

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5042]
junit generate “$buildDir/test-results/TEST-*.xml and this is we can set on jenkins configuration. ( https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Plugin ).

**Comment by EfimovVladimir** [comment]
in our case : **/build/test-reports/*.xml

**Comment by EfimovVladimir** [comment]
![image](https://cloud.githubusercontent.com/assets/17744188/26587502/329b5774-455b-11e7-8c14-148e877d4f13.png)

**Comment by scottdraves** [comment]
looks like it should be `**/build/test-results/test/*.xml`
but i tried it and what you wrote and it does not find any results:
```

BUILD SUCCESSFUL

Total time: 3 mins 37.262 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
Recording test results
None of the test reports contained any result
[JaCoCo plugin] Collecting JaCoCo coverage data...
```

**Comment by scottdraves** [comment]
here's why i think that's the right path:
```
$ ls -l ./kernel/base/build/test-results/test/TEST-com.twosigma.beaker.chart.ChartTest.xml
-rw-r--r--  1 spot  staff  1662 Jun  7 14:19 ./kernel/base/build/test-results/test/TEST-com.twosigma.beaker.chart.ChartTest.xml
```

**Comment by scottdraves** [comment]
hm weird on the server there is no "test" directory, the right path was `**/build/test-results/*.xml`
