### ISSUE TITLE
implement %%python for groovy kernel

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5051]
remaining from https://github.com/twosigma/beaker-notebook-private/issues/97
this is harder because we have to refer to another kernel

https://jupyter-client.readthedocs.io/en/latest/api/manager.html#multikernelmanager-controlling-multiple-kernels

https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/multikernelmanager.py#L42

**Comment by scottdraves** [comment]
Can the JVM fork off a Python process that starts the kernel?

**Comment by jmsdnns** [comment]
I may be lacking important context for answering this, but there's a python package called javabridge which seems to allow a JVM to start a Python process and versa vice.

[Calling Python from Java](http://pythonhosted.org/javabridge/java2python.html)

[Starting and Killing the JVM](http://pythonhosted.org/javabridge/start_kill.html)

**Comment by scottdraves** [comment]
closing in favor of https://github.com/twosigma/beakerx/issues/7124
