### ISSUE TITLE
implement %%groovy magic for python

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5052]

**Comment by fishera123** [comment]
@gnestor do you have any update on this?

**Comment by scottdraves** [comment]
work in progress:
https://github.com/twosigma/beakerx/blob/fishera123/issue-5052/beaker/kernelMagics.py

**Comment by scottdraves** [comment]
@blink1073 pointed me at this, which seems to be just what we want, but implemented for metakernel instead of for ipykernel, but should be adaptable:

https://github.com/Calysto/metakernel/blob/master/metakernel/magics/kernel_magic.py
