### ISSUE TITLE
reconsider using metakernel 

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5056]
would solve some issues like:
magics, interrupt, passing parameters to JVM, the classpath race condition.
likely source of jank, plus an extra copy/process to cross.

**Comment by dsblank** [comment]
This would be great! Please let me know if you need any help.

Also, metakernal has %set and %get that is designed to be a generic way for making "auto translation" work across all languages. I think we could build on Beaker's JSON-like format and make it a cross-kernel standard.

**Comment by dsblank** [comment]
Notifying @blink1073 so he'll be aware too.

**Comment by blink1073** [comment]
Agreed that this shows promise!

**Comment by gnestor** [comment]
@dsblank and @blink1073 Thanks for your feedback! 

@dsblank I'd love your help on this as I haven't had any experience developing kernels yet. Perhaps we can start by migrating one of the kernels in this repo? I know that we're having [some issues](https://github.com/twosigma/beakerx/issues/5052) with the Groovy kernel.

**Comment by dsblank** [comment]
Sure! I'd like to make sure that there is an understanding of what is lost and gained in such a move. This would move to talking to the running kernels through a expect-like interface, where the JVM-based code would run as a process. Python (via metakernel and friends) would provide all of the Jupyter-related bits for  talking to the kernel. No one here would have to maintain the low-level code (except for perhaps the widgets, if that stayed in Java). However, there would need to be some hooks to manage multimedia (eg, images) output and standard input. Not only would you get all of the metakernel magics for free, but also things like parallel processing. You could have a cluster of code running Clojure, or the next random JVM-based language that comes along. It also would make it easy to call the JVM-based languages from IPython.

BTW, I wrote all of the infrastructure in C# before coming to the conclusion that I should just use a metakernal-like system in Python for languages like Boo, F#, etc.

**Comment by gnestor** [comment]
@dsblank Thanks! This is great! If I'm reading you correctly, then the only trade-off of using metakernel is:

> However, there would need to be some hooks to manage multimedia (eg, images) output and standard input.

It sounds like it would be better to manage that vs. all the low-level parts.

**Comment by dsblank** [comment]
@gnestor I think that sums it up pretty well; there may be other specific hooks to add (like an API for getting completions from the JVM-language) but images are the hardest I think. This does require a bit of original thinking... for example, to make this efficient, one needs a way to relay perhaps large, binary data from the JVM language to the Python kernel. Matlab is probably the most evolved metakernel-based language so far, and that has been a source of challenges for @blink1073 . 

See:
https://github.com/Calysto/matlab_kernel/blob/master/matlab_kernel/kernel.py#L100

**Comment by blink1073** [comment]
The biggest challenge for Octave and Matlab is that the `print()` command is not as well supported as the live figures.  Also, `IPython` `display` is limited to `png`, `jpg`, and `svg` output.

**Comment by gnestor** [comment]
> The biggest challenge for Octave and Matlab is that the print() command is not as well supported as the live figures.

I don't really understand... Can you elaborate?

> Also, IPython display is limited to png, jpg, and svg output.

Ok, so you were able to get images working 👍 It seems like the other string-based mime types (HTML, Markdown, JSON) should be easier?

**Comment by gnestor** [comment]
Based on [this discussion](https://github.com/ipython/ipython/issues/6352), it suggests that there is no good way to add magics to a wrapper kernel. Is that still the case? Was that the motivation for creating metakernel?

**Comment by blink1073** [comment]
The `print()` command in Octave/Matlab saves the graphics context (interactive figure) to an image file, but it is poorly implemented.  Once you have the data in the correct format (one supported by `IPython.display`), the rest is easy.

Yes, that one of the reasons for `metakernel`.  See also https://github.com/twosigma/beakerx/issues/5052#issuecomment-294939672.

**Comment by scottdraves** [comment]
current thinking is we can solve these problems without metakernel.
