### ISSUE TITLE
need a better way to detect our kernels

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5058]
https://github.com/twosigma/beakerx/blob/master/beakerx/js/src/extension.js#L71

here we need different behavior for our kernels.
this isn't the right way.

**Comment by konstantinTarletski** [comment]
Also added messages in JS console :
![default](https://cloud.githubusercontent.com/assets/10614633/24547825/6ea68d4e-161a-11e7-8652-3bf24a20367b.png)
