### ISSUE TITLE
install python package for runtime

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5067]
eliminate use of PYTHONPATH in "gradle environmentVariables"
the runtime should be installed with pip or conda.

**Comment by hadim** [comment]
Would it make sense to make a conda force package of beakerx ?

**Comment by scottdraves** [comment]
yes thank you.  this issue would be a key part of that, but i think it deserves its own issue, which i just made:
https://github.com/twosigma/beakerx/issues/5134
