### ISSUE TITLE
js console errors

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#507]
Failed to load resource: the server responded with a status of 404 (Not Found) http://127.0.0.1:8801/beaker/app/vendor/bower_components/bootstrap/docs/assets/img/glyphicons-halflings.png
Failed to load resource: the server responded with a status of 404 (Not Found) http://127.0.0.1:8801/beaker/app/vendor/bower_components/bootstrap/docs/assets/img/glyphicons-halflings-white.png

**Comment by samccone** [comment]
on this
