### ISSUE TITLE
Table content omitted in TabbedOutputContainerLayout

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5070]
![screenshot from 2017-03-15 11-10-59](https://cloud.githubusercontent.com/assets/3425710/23955486/6540dcb6-0970-11e7-8943-859aa4553616.png)
![screenshot from 2017-03-15 11-11-28](https://cloud.githubusercontent.com/assets/3425710/23955495/6aa30ae4-0970-11e7-9ab0-d1d634e5dd58.png)

The table behaves well individually. However the content is ommited, showing "Table xxx.." when it is integrated into the TabbedOutputContainter. Output like arrays have the same issue, but the graphs work properly.

The file could reproduce the issue is https://github.com/twosigma/beaker-notebook-private/blob/tiezheng/mapdemo/demoFiles/map_shortestpath.ipynb

**Comment by MariuszJurowicz** [comment]
@scottdraves 
Now inside the `map_shortestpath.ipynb` file the table created by `Table.createFromCsv(fileName);` is not rendered in the last cell `// final visualization of everything `. Actually it renders only the short summary like `Table UScity.csv: Size = 174 x 6`
I'm not sure if the table should be rendered there.

**Comment by scottdraves** [comment]
The tablesaw automatic widget display was removed.
I think correcting the rendering of tables was already fixed in another PR.
