### ISSUE TITLE
make the plot widgets accessible with JS api

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5073]
in classic beaker you can 
<img width="530" alt="screen shot 2017-03-18 at 12 28 02 pm" src="https://cloud.githubusercontent.com/assets/963093/24073962/a0b49482-0bd6-11e7-860a-90ef3c103749.png">

make this work with our javascript magic:
<img width="352" alt="screen shot 2017-03-18 at 12 35 31 pm" src="https://cloud.githubusercontent.com/assets/963093/24073998/474da46e-0bd7-11e7-8ae0-dc3b735e2bba.png">
by defining our JS API on the beaker object:
https://github.com/twosigma/beaker-notebook-private/blob/master/beaker-nbextension/main.js#L29

**Comment by scottdraves** [comment]
this works if i reload the page.
but if i just open a notebook, then i get the "not a constructor" error.
the problem is the beaker object is empty.

**Comment by jszalek** [comment]
@scottdraves it should work with this fix: https://github.com/twosigma/beakerx/pull/5284
