### ISSUE TITLE
repository size is too large

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5074]
Repository weights above 350 mb whereas the code itself is about 20 mb. 
It is happening because the repository is cloned from the old beaker repo. It is very inconvenient, so I believe you need to either create a new repository or manipulate git history to cut old beaker history.

**Comment by scottdraves** [comment]
good point, will fix.

**Comment by scottdraves** [comment]
this is blocked on some internal issues, should not be long though.

**Comment by scottdraves** [comment]
<img width="453" alt="screen shot 2017-05-01 at 11 29 04 pm" src="https://cloud.githubusercontent.com/assets/963093/25602971/e527f480-2ec5-11e7-952d-e14ef6869386.png">

**Comment by scottdraves** [comment]
somehow even after force pushing with no history, the .git directory did not shrink.

**Comment by hadim** [comment]
Maybe you should create a new folder, run `git init` on it, add all the files, then run `git add . && git commit -am "Init commit"`. Add the remote github repo and force push ?

**Comment by scottdraves** [comment]
that's what i did.

**Comment by hadim** [comment]
I just did it and the repo size is only 18 Mo after the `git commit`. Did you take care not copying the old `.git` repo in the new folder ?

**Comment by scottdraves** [comment]
i did it with `rm -rf .git`

**Comment by hadim** [comment]
here is what I exactly did : 

```bash
git clone https://github.com/twosigma/beakerx.git
cp -R beakerx/ new_beakerx/
cd new_beakerx/ 
rm -fr .git
git init
git add .
git commit -am "Init commit"
du -sh .
```
returns
```
18M	.
```

**Comment by scottdraves** [comment]
yes that's what i did.  and then force pushed.  and yet on github, it is not replaced and remains 350MB.

**Comment by hadim** [comment]
oh wait, it's probably because of the ~800 branches.

**Comment by hadim** [comment]
Are they all useful? Maybe you should convert the ones you want to keep in PR and delete the other ones.

**Comment by scottdraves** [comment]
i think you are right, deleting almost all of them...

**Comment by scottdraves** [comment]
800 branches gone, only our ~25 release branches remain.
it seems to have helped a bit, but not solved.

**Comment by hadim** [comment]
My last guess is that the others branches carry the complete history and so the size won't reduced before those are deleted/merged.

**Comment by scottdraves** [comment]
all branches gone, still not fixed.

**Comment by hadim** [comment]
Tags are still here I guess they also carry git history.

**Comment by scottdraves** [comment]
deleting all tags and branches did the trick.  11MB :) ty Hadrien.
