### ISSUE TITLE
interrupt should not query kernel

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5098]
https://github.com/twosigma/beakerx/blob/master/beakerx/js/src/extension.js#L103

this code has 2 problems:
```
function interrupt() {
    getControllCommandList(function(resp) {
      if (undefined != resp.content.data) {
```

the first thing this does is query the kernel for its capabilities.  this is wrong.
this was already done when the kernel started up.  the result should be stored locally in this module,
and then used here when its needed.

also "getControllCommandList" has a typo, it should be "getControlCommandList"

**Comment by konstantinTarletski** [comment]
Fixed. 
But one problem stay :
if we have our "beakerx" kernel then no problem.
But on python like this : I ask for "control commands" and do not get any answer.
And I can not define does I already asked for  "control commands" or not.
So on python kernels I asked for them everytime when I push interrupt.

To fix this we need to add callback handler with empty command list in python kernel.
