### ISSUE TITLE
do not require restart for new plugin

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#51]
if you load a plugin that hasn't been seen before, then beaker requests a restart.
instead it should rewrite nginx config and then just send it a HUP.
if this leaves existing connections unmodified then it should work.
if it works we can eliminate the ~/.beaker/plugins file.

**Comment by anglee** [comment]
More details:
http://nginx.org/en/docs/control.html
http://www.cyberciti.biz/faq/howto-unix-linux-gracefully-reload-restart-nginx-webserver/
http://stackoverflow.com/questions/7943684/nginx-can-i-add-a-new-virtual-host-without-restarting-the-server
and it should work on Windows too
http://nginx.org/en/docs/windows.html

**Comment by anglee** [comment]
This has been addressed with #86
