### ISSUE TITLE
OutputContainer should show a overall menu and a menu for each content cell

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#511]
A [OutputContainer](https://github.com/twosigma/beaker-notebook/blob/925f14b4dd9ae65ccfd1e50a99264023bd12ff11/core/src/main/web/app/mainapp/components/notebook/outputdisplay/outputdisplayfactory-service.js#L82) should show a overall menu and a menu for each content cell

**Comment by scottdraves** [comment]
can you clarify what you mean?
which items go in which menus?
if there is just one content cell, then its menu is hidden?

**Comment by melmac48** [comment]
@bradicdesign this deals with the case where a cell output has multiple outputs - for example if I output a table and a chart, side by side in the same output display.

**Comment by ildipo** [comment]
remaining part is #1002
