### ISSUE TITLE
locking notebook breaks section toggle

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#512]
1) open a new notebook.  put in some code and evaluate some of the cells.
2) lock the notebook.
3) click the section toggle on "hello beaker"
4) try to click it again -- you can't!
5) and very strangely, the checkmark next to lock also vanishes.

**Comment by melmac48** [comment]
@samccone This seems pretty serious, as it has the potential to make the user think they've lost data. Can you move this to the top of the stack?

**Comment by anglee** [comment]
I couldn't reproduce this with current master (HEAD 9049e0d)

**Comment by scottdraves** [comment]
ditto
