### ISSUE TITLE
java crashes on static imports

### ISSUE THREAD

**Issue by konstantinTarletski** [twosigma/beakerx#5126]
if we add static import to java like "shell option",

![default](https://cloud.githubusercontent.com/assets/10614633/24761037/f6d54f16-1af2-11e7-8b57-c55f56d5124b.png)

 then java cell crashes while executing:

![default](https://cloud.githubusercontent.com/assets/10614633/24761073/123dc35a-1af3-11e7-8fec-fee47d4ce44f.png)

also fix this:
com.twosigma.beaker.javash.JavaDefaultVariables
```
  public JavaDefaultVariables() {
    //TODO delete when issue #5126 "java crashes on static imports" will be fixed 
    removeImports(
      "static com.twosigma.beaker.widgets.DisplayAnyWidget.display"
      );
```

**Comment by jpallas** [comment]
The stuff going on in `*Evaluator.setShellOptions` is confusing.  `getAsString` takes a list of imports and turns them into a newline-separated string.  `GroovyEvaluator.setShellOptions` splits that string again into lines, but `JavaEvaluator`, `ClojureEvaluator` and `ScalaEvaluator` appear to split the string just at spaces, which turns what was originally a single "static foo.bar.Baz.something" into two separate imports.

**Comment by scottdraves** [comment]
can avoid parsing and deparsing?  just keep the imports a list everywhere.
