### ISSUE TITLE
start backends lazily

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#513]
right now starting beaker is slower than starting my native, single-language system because it always loads R and ipython, even if you use only one or neither.

if we fix the plugin manager so reclicking a plugin disables it and deletes it from the notebook,
then it would be possible for a user to do that, remove the language(s) they don't use, and then save the result as the default notebook.

i think that's too much work -- it should just do the right thing out of the box for naive users, and that means it doesn't start a python backend until you use it.

that means the default notebook is more empty.

the problem remaining is that the add cell menu will be empty, but it should be populated with all available backends (verified working on this instance, saved as a pref).

**Comment by melmac48** [comment]
@bradicdesign there are a few issues floating around that all deal with the same thing - beaker supports multiple languages but not every language is installed on a users machine and of the ones that are installed not all of them are loaded by default. We need to balance:
A good installation experience - the easier it is for a new Beaker user to get a language installed, the better
Speed of loading - the user should be able to start editing their notebook as soon as possible (which means we shouldn't be loading languages they aren't using in that notebook)
Discoverability - A user should know that languages are available, installed and loaded into the notebook

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/703
