### ISSUE TITLE
get onto conda forge

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5134]

**Comment by hadim** [comment]
About package distribution, I have developed a small Python script to install a kernel https://github.com/hadim/scijava-jupyter-kernel/blob/master/install-kernel.py. You are using Gradle to do it.

I still don't know what is the best way to do that. I think what we want is an easy way for the user to be able to download the required Java libraries (without the need of cloning the repo and compiling the code) and install the Jupyter kernel with the `jupyter` command. Users should be able to specify both the Python path and the Java path. For example in ImageJ we have our own Java shipped, so the user would have to specify this Java installation and not the default one. I think this use-case is not ImageJ specific and will probably apply to other situations.

**Comment by gnestor** [comment]
@hadim It looks like your `install-kernel.py` link is broken! We are working on containing all installation and build commands into a single `setup.py` and calling `python setup.py install --single-version-externally-managed --record record.txt` from conda-build. We are installing kernels by running gradle commands from Python. Please chime in if you have any better ideas about how to handle kernel installation from Python.

**Comment by hadim** [comment]
With the Scijava kernel I am using a Java class to do the job: https://github.com/conda-forge/scijava-jupyter-kernel-feedstock/blob/master/recipe/post-link.sh

But doing it in Python should work too.

**Comment by hadim** [comment]
You can also use custom `buil.sh` file as I do https://github.com/conda-forge/scijava-jupyter-kernel-feedstock/blob/master/recipe/build.sh

**Comment by scottdraves** [comment]
>  We are installing kernels by running gradle commands from Python. 

true however i think it should be done just with python.
we definitely do not want to distribute gradle.

**Comment by scottdraves** [comment]
blocked by https://github.com/pypa/packaging-problems/issues/95

**Comment by scottdraves** [comment]
we skipped pypi and are using github to host the tarball for conda.
