### ISSUE TITLE
magic error is stderr

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5138]
<img width="415" alt="screen shot 2017-04-07 at 11 36 22 pm" src="https://cloud.githubusercontent.com/assets/963093/24825352/26e712c2-1beb-11e7-9eb5-d1966541d39d.png">

that is stderr but it should be an error cell like you get from 1/0

**Comment by fishera123** [comment]
in python kernel it is displayed as stderr as well.

![image](https://cloud.githubusercontent.com/assets/9304560/24862993/c65a91c6-1e07-11e7-910b-5a7101c695b0.png)

**Comment by scottdraves** [comment]
indeed -- seems like a bug but let's just match ipykernel for now.  thx.
