### ISSUE TITLE
update default notebook

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#514]
"will turn light blue when plugin loads successfully"

not anymore

how about

```
# type some python on the next line and click "Run" to evaluate it and display the result.  for example, try: 1+1
```

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/527

**Comment by anglee** [comment]
Thanks for pointing out the default notebook is outdated. However, we should review this as part of the default notebook plan.

It has been determined that the current default notebook serves 2 purposes now:
1) as a brief intro of how to use notebook for new users
2) as a empty point that is good for starting a research notebook.
And it was decided by @melmac48 that we will have 2 notebooks for the 2 purposes for V1.

**Comment by scottdraves** [comment]
I don't see any Issue or email with this new plan and since we are in the final stages of code freeze for 1.0 we should make the smaller change which is this PR #527
