### ISSUE TITLE
Figaro, Edwared and WebPPL on Beaker Notebook

### ISSUE THREAD

**Issue by krylov48** [twosigma/beakerx#5140]
What is the easy way to deploy Figaro (Scala based), Edward (Python based) and WebPPL (NodeJS based) libraries on Beaker Notebook? I use this Probabilistic Programming Languages separately and on Jupyter. It's necessary to support data exchange between the modules. I see the Beacker as the best tool. Please help to find a solution.

**Comment by scottdraves** [comment]
hi, thank you for your question.

it should not be hard to create a kernel for figaro using the new jvm base kernel in beakerx.
afaik Edward is just a lib and should just work with the normal ipykernel, or is there a missing integration.

not sure about WebPPL.
