### ISSUE TITLE
run gradle only from top, use gradlew

### ISSUE THREAD

**Issue by dsblank** [twosigma/beakerx#5141]
Looks like you need a modern gradle to build. Gives weird errors with no hint as to what is wrong. gradle 3.4.1 works.

**Comment by scottdraves** [comment]
thanks for the report.  which version did you have before?
i have 2.4 on this machine and it's fine, but i think most of my others are 3.x

**Comment by dsblank** [comment]
I am on Ubuntu 16.10 and I think it had gradle 2.13 before I upgraded via:

```shell
sudo add-apt-repository ppa:cwchien/gradle
sudo apt-get update
sudo apt-get install gradle-ppa
```

**Comment by altavir** [comment]
And why not use gradle wrapper? You can select any version you want and ship it with code without altering the system.

**Comment by scottdraves** [comment]
i made it clear that v3+ is required: https://github.com/twosigma/beakerx/commit/7afc0754d77d776c90d093de3fa34f78b9c691ec

didn't use gradlew because we have a bunch of project directories and as i understand it there would have to be a gradlew/jar in each of them.

**Comment by altavir** [comment]
> didn't use gradlew because we have a bunch of project directories and as i understand it there would have to be a gradlew/jar in each of them.

No, you are not. The wrapper is required only for the root project (the one with `settings.gradle`). Of course it means that you can call gradle only from the root, but that is how it meant to be.

By the way, you are using constructs like: 
```
  doLast {
    project('beakerx').tasks.install.execute()
  }
```
whereas the proper way is `task linkBeakerNbextension(dependsOn: ":beakerx:install")`. This notation allows gradle to build task tree properly.

**Comment by scottdraves** [comment]
there should be one top-level target that installs all the kernels.
we should use gradlew.
we should use dependsOn, not doLast.

**Comment by altavir** [comment]
`kernelInstall` task currently not working from the root. I will try to look into it and post a PR. Also it would be good to incorporate all of npm commands in gradle. I will try to look into it myself, but I am not very familiar with npm.

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beakerx/issues/5167
