### ISSUE TITLE
Add the possibility to specify options to the kernel JSON file

### ISSUE THREAD

**Issue by hadim** [twosigma/beakerx#5144]
In the previous kernel I was developing, language was set as an option when calling the kernel : 

```json
{
"argv": [
    "/your/system/jdk1.8.0_66/jre/bin/java",
    "-classpath",
    "/path/to/kernel/scijava-jupyter-kernel-0.1.0-SNAPSHOT.jar:/your/java/jars/files/*",
    "org.scijava.jupyterkernel.kernel.Session",
    "-k", "python",
    "-f", "{connection_file}"
],
"display_name": "Jython",
"language": "python"
}
```

Options could also be used for other things such as setting verbose or debug mode.

It should be implemented into `KernelConfigurationFile` and I already have some code that do the job : https://github.com/hadim/scijava-jupyter-kernel/blob/master/src/main/java/org/scijava/jupyterkernel/kernel/Session.java#L256

Would you be interested by a PR ?

**Comment by hadim** [comment]
I forgot to mention that BeakerX current kernel crash because of the following : https://github.com/twosigma/beakerx/blob/master/kernel/base/src/main/java/com/twosigma/jupyter/KernelConfigurationFile.java#L48

**Comment by hadim** [comment]
Something similar to that : https://github.com/hadim/scijava-jupyter-kernel/blob/beakerIntegration/src/main/java/org/scijava/jupyter/DefaultKernelConfigurationFile.java#L57

**Comment by scottdraves** [comment]
Thank you Hadrien, we are working on providing control of options.
here's the current plan: https://github.com/twosigma/beakerx/issues/5145
not sure what you mean, though i am getting 404s from the links.

**Comment by hadim** [comment]
Sorry for the 404 . Here is the correct link https://github.com/hadim/scijava-jupyter-kernel/blob/master/src/main/java/org/scijava/jupyter/DefaultKernelConfigurationFile.java#L57
