### ISSUE TITLE
[Native Beaker] Unable to find IPython binaries on windows

### ISSUE THREAD

**Issue by lcota** [twosigma/beakerx#5155]
Has there been any issues with the latest Jupyter / IPython versions? I'm unable to start any python kernels from Beaker. My installation directory (Anaconda python 2) is:

c:/usr/bin/python

IPython.exe is located in:
c:/usr/bin/python/Scripts

I've tried using both of the above directories in the beaker.pref.json file without any success. Has anyone else encountered this recently?

**Comment by scottdraves** [comment]
Hi Luis, thanks for the report, I haven't tried the old beaker with the new jupyter.
We have a new architecture for Beaker (called BeakerX) that better integrates with Jupyter and solves this kind of problem permanently: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/beaker-user/nFvqwHfyMbg/oflyWJ9tBgAJ

Until then you are probably better off sticking with Jupyter v4.
