### ISSUE TITLE
table menus truncated by short output cell

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5168]
![screen shot 2017-04-12 at 2 20 44 pm](https://cloud.githubusercontent.com/assets/963093/24973025/4f598f2a-1f8b-11e7-9f2b-900344c1c0d1.png)

**Comment by jszalek** [comment]
@scottdraves I changed overflow-y to 'auto'. It will be safer than removing standard 'overflow:hidden' from phosphor container.
