### ISSUE TITLE
jupyter receives kbd commands from table

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5170]
if you click on a table and then enter a keyboard command like "h" or "1",
then it gets interpreted by both the table widget and jupyter.
the table should eat the event.

**Comment by LeeTZ** [comment]
Just met with similar problems today. For any self-defined widget, `Jupyter.keyboard_manager.register_events(your_element);` disable all Jupyter keyboard shortcut in `your_element`.
