### ISSUE TITLE
[gradle] move python and js output to gradle build directories

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5172]
I think it would be better to follow gradle project structure for navigation and cleaning:

- place `beakerx\beakerx` in `beakerx\build\beakerx\` or beakerx\build
- the same for `beakerx.egg-info`
- the same for `:beakerx:js` output
- move `beaker` to 'src/beaker`

The one can apply `base` plugin for all non-java modules and get `clean` task for free.

**Comment by scottdraves** [comment]
this part of the project is going to be built with pip and setuptools.
gradle will build just the java.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/issues/5060
