### ISSUE TITLE
table menu stays up

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5173]
click on a table menu it opens.
then click in a code cell.  the menu stays up.
it should close.

clicking elsewhere, like on another output, or in the bkg it does close.
clicking again on a code cell it does close.

**Comment by jszalek** [comment]
I cannot reproduce this bug.
Please provide more details.

**Comment by scottdraves** [comment]
http://www.giphy.com/gifs/xUA7aVMUoc02KHioA8
