### ISSUE TITLE
Changed in version 5.0: Busy and idle messages should be sent before/after handling every request, not just execution.

### ISSUE THREAD

**Issue by hadim** [twosigma/beakerx#5192]
My kernel (https://github.com/hadim/scijava-jupyter-kernel) only work in console and notebook but not in jupyter lab : https://github.com/hadim/scijava-jupyter-kernel/issues/21

Do you have the same issue ?

Are you planning to switch to Jupyter messaging protocol v5.1 ?

**Comment by scottdraves** [comment]
I haven't tried our kernel in JL yet. I did notice a protocol version warning, which must be what you are walking about.  i will look into it.

**Comment by hadim** [comment]
I confirm the Beakerx kernel shows the same issue as mine. It works in Notebook but not in JL.

Jupyter lab is probably the next "main" Jupyter client (but not now yet, probably in few months and even more). So I would suggest you do your tests in both Notebook and JL.

And it's also a fantastic piece of software :-) I use it very often for my analysis.

**Comment by scottdraves** [comment]
confirmed kernels fail to run in JL.

**Comment by dsblank** [comment]
Do you know about the kernel test project:

https://github.com/jupyter/jupyter_kernel_test

Should help test for conformance.

**Comment by hadim** [comment]
I didn't. That looks very interesting !

**Comment by hadim** [comment]
Also runipy is super useful to execute notebook on the command line.

**Comment by scottdraves** [comment]
http://jupyter-client.readthedocs.io/en/latest/messaging.html (search for 5.1 for various change notes)

here's where Groovy reports 5.0 protocol (vs 5.1):
https://github.com/twosigma/beakerx/blob/master/kernel/groovy/src/main/java/com/twosigma/beaker/groovy/handler/GroovyKernelInfoHandler.java#L47

**Comment by scottdraves** [comment]
this has some kind of kernel tester but maybe only supports 5.0 so far:
https://github.com/ipython/ipython/wiki/Dev:-Testing-kernels-against-message-specification

**Comment by blink1073** [comment]
Ah, I believe the issue is "Changed in version 5.0: Busy and idle messages should be sent before/after handling every request, not just execution."  from this [section](http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-status).   The classic notebook does not enforce this fact.

**Comment by hadim** [comment]
@scottdraves did you identify what need to be done here to upgrade to version 5.1?

**Comment by hadim** [comment]
About kernel testing, I am using this script to execute notebooks automatically with a given kernel. It works very well with CI such as Travis : https://github.com/hadim/scijava-jupyter-kernel/blob/master/scripts/runipy.py

**Comment by scottdraves** [comment]
hopefully you and steve identified what needs to be done.  jaroslaw is working on it.

**Comment by scottdraves** [comment]
the kernel side is looking good, but the JS extension APIs are different so a lot of stuff still doesn't work in jupyter lab.  we will fix that next.

**Comment by scottdraves** [comment]
next up: make the JS extensions compatible w/Lab https://github.com/twosigma/beakerx/issues/5268

**Comment by scottdraves** [comment]
🐬 🐬

**Comment by hadim** [comment]
I am trying 264a96d at the moment and the Scijava kernels don't work anymore... With both Jupyter Notebook and Jupyter Lab.

The first cell is executed and then the kernel hangs forever... I can't bisect it since all the history is now gone (I guess to reduce the size of the repo).

Any ideas ? Is it working for you ?

**Comment by hadim** [comment]
Ok I found that I need to call `executeCodeCallback()` :-) Working now ! Nice work.

**Comment by scottdraves** [comment]
glad you figure it out, thx, all credit to @jaroslawmalekcodete

**Comment by scottdraves** [comment]
thanks for reporting the issue in the first place!

**Comment by hadim** [comment]
Thanks @jaroslawmalekcodete .

About the new git history, the `.git` folder is still huge : 

```bash
$ du -sh .git
340M	.git
```

Weird ?
