### ISSUE TITLE
Some bug using Jupyter console

### ISSUE THREAD

**Issue by hadim** [twosigma/beakerx#5195]
`jupyter console --kernel=YOUR_KERNEL` is a great way to quickly test a freshly compiled kermel but I have noticed some bugs using it.

1. The `Out[1]:` line is always displayed even when the returned result is `null`. See https://github.com/hadim/scijava-jupyter-kernel/issues/23

2. After the first line has been executed, the other lines shows multiples prompts to the user. See https://github.com/hadim/scijava-jupyter-kernel/issues/18

**Comment by scottdraves** [comment]
Hi thanks for the bug report.

1) I think null should be displayed.  we have another value OutputCell.HIDDEN that gets rid of the Out.  there are a bunch of runtime functions that should return this and so I agree there are too many circumstances where you see Out.  see https://github.com/twosigma/beakerx/issues/5102

2. I will look into this thank you very much.

**Comment by hadim** [comment]
Thanks @scottdraves

**Comment by scottdraves** [comment]
1 is done https://github.com/twosigma/beakerx/pull/5199

**Comment by hadim** [comment]
I still have the issue with my kernel. Here is the code that set the result object to `SimpleEvaluationObject` : https://github.com/hadim/scijava-jupyter-kernel/blob/master/src/main/java/org/scijava/jupyter/kernel/evaluator/Worker.java#L102

I don't think I am doing anything wrong because the equivalent code in your Groovy kernel is still the same.

**Comment by hadim** [comment]
It should be fixed with https://github.com/twosigma/beakerx/pull/5205

**Comment by scottdraves** [comment]
I am seeing this:
```
$ jupyter console --kernel=Groovy
[main] INFO com.twosigma.jupyter.KernelConfigurationFile - Path to config file : /Users/spot/Library/Jupyter/runtime/kernel-17278.json
[Thread-0] INFO com.twosigma.beaker.groovy.handler.GroovyKernelInfoHandler - Processing kernel info request
[Thread-0] INFO com.twosigma.beaker.groovy.handler.GroovyKernelInfoHandler - Processing kernel info request
/Users/spot/anaconda/envs/beakerx/lib/python3.5/site-packages/jupyter_console/ptshell.py:94: UserWarning: No lexer found for language ''. Treating as plain text.
  warn("No lexer found for language %r. Treating as plain text." % name)
Jupyter console 5.1.0

BeakerX kernel for Apache Groovy


In [1]: 1+2/Users/spot/anaconda/envs/beakerx/lib/python3.5/site-packages/jupyter_console/ptshell.py:599: UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kern.
  warn('The kernel did not respond to an is_complete_request. '
In [1]: 1+2
[groovy worker] ERROR com.twosigma.beaker.jupyter.msg.MessageCreator - Unhandled status of SimpleEvaluationObject : RUNNING
Out[1]: 3

In [2]: 2+3
      :
      :
[groovy worker] ERROR com.twosigma.beaker.jupyter.msg.MessageCreator - Unhandled status of SimpleEvaluationObject : RUNNING
Out[2]: 5
```
There are a couple of problems:
1) excessive info logging "Processing kernel info request" I just fixed this.
2) "no lexer found".  this is a bug, will fix: https://github.com/twosigma/beakerx/issues/5206
3) the multiple prompt problem.  i will have to look at 5205 and see how to get its fix without changing the null behavior.  thank you very much for the PR.
4) the Error from MessageCreator, this is another bug, will fix: https://github.com/twosigma/beakerx/issues/5200

**Comment by hadim** [comment]
I don't have error 1 and 2 (I guess it's because the scijava kernel is doing things little differently).

Good for 3.

Also, there a Python UserWarning when the first cell is executed : `UserWarning: The kernel did not respond to an is_complete_request. Setting `use_kern.warn('The the kernel did not respond to an is_complete_request. '`

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/issues/5251 for the is_complete_request

**Comment by scottdraves** [comment]
these are all fixed now, @hadim do you agree this can be closed?

**Comment by scottdraves** [comment]
```
$ jupyter console --kernel=Groovy
Jupyter console 5.1.0

BeakerX kernel for Apache Groovy


In [1]: 1+2
Out[1]: 3

In [2]: 3+4
Out[2]: 7

In [3]:
Do you really want to exit ([y]/n)? y
Shutting down kernel
```

**Comment by hadim** [comment]
Good for me !
