### ISSUE TITLE
cleanup kernel/base deps

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5196]
i don't think kernel/base uses any of h2, fluent-hc, antlr4, guava.  there may be more.

**Comment by fishera123** [comment]
currently, we can remove guava. h2, fluent-hc is used by SQL kernel. We can move h2 to SQL kernel Gradle, but as @jaroslawmalekcodete told me we wanted to have the ability to create JDBC connection from all plugins in future.  we can leave antlr4 in kernel/base and remove from other kernels
