### ISSUE TITLE
Consider using PyGradle and node plugin instead of native scripts

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5197]
I know, that it is decided to use python as a main build platform, but there is another way that could be used at least for testing purposes. There is this [PyGradle](https://github.com/linkedin/pygradle) plugin which allows to build virtual python environments inside gradle. Have not tried it myself because I do not work in Python, so do not know whether it is a good solution.

Also one could use one of numerous gradle **node** and **npm** plugins like [this one](https://github.com/srs/gradle-node-plugin) to complete the picture.

I know, I am a gradle fan, but I prefer when I run a build with one command from one build system without using 3 different ones (there are still troubles on Windows, I managed to install everything on one computer, but failed on another one).

**Comment by scottdraves** [comment]
Thanks for the tip, but setup.py is more familiar to the jupyter dev community that we are working with.

After https://github.com/twosigma/beakerx/issues/5060 it should all be run from one command as you prefer.
