### ISSUE TITLE
Unhide evaluation time

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#520]
There's plenty of space to display evaluation time, it doesn't need to be hidden in a menu. Here's one option:

![eval-time](https://cloud.githubusercontent.com/assets/1740497/4092045/97891652-2f8e-11e4-8ef7-6df404ef2759.PNG)

**Comment by scottdraves** [comment]
i think this is a good idea

**Comment by melmac48** [comment]
this was part of the original design, not sure why it was dropped

**Comment by samccone** [comment]
@scottdraves @anglee do you know where i can get this info from?

**Comment by samccone** [comment]
got it^
