### ISSUE TITLE
UI for namespaces

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#521]
The namespace stuff is awesome. Unfortunately, it's really easy to miss if you're not looking for it. What if every output had a button with something like "share to language..." that would assign that output a name in the namespace and automatically generate a cell in the new language with a line of code that reads in the value.

In addition to this potentially being a valuable feature on its own, it would add a huge amount of visibility to the namespace.

**Comment by scottdraves** [comment]
thanks.  i like this idea.

it would have to automatically trigger evaluation of the hidden cell too, so that when you reevaluate, the new results get pushed to the new language.  and to get the value into the namespace you would have to append some code to the main cell.

**Comment by scottdraves** [comment]
this reminds me of another UI connected to cell evaluation that i have been thinking about, which is dependencies between cells.  so somehow link cells, and say when you evaluate one, automatically trigger evaluation of the other.

**Comment by scottdraves** [comment]
The other main UI that namespaces need is a table that displays the names and values themselves.
I can see this being in an extra window that you open from a menu item, or possibly just at the bottom of the notebook, like an extra cell (or perhaps a cell type).
This window would list all the values and here would be a good place to click on them and import/export them to whatever languages, and provide other operations on them that we might need later.

On the cell menu there could be an item "autotranlsate output of this cell" which would prompt you for a name, and add it to the namespace.
