### ISSUE TITLE
Use namespaces without explicitly saving

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#522]
You don't always know that you want to add something to the namespace before you see the result. What if each output was given a name, so instead of saying "Cell Output" the UI would say something like "output_14". Then in code you could do "beaker.get('output_14')" and the namespace server could ask the client for that value.

**Comment by scottdraves** [comment]
this would be hard to make work.  by the time the value is in the output cell, it's too late.  think about R.
also hard for the user to type or think something like output_14.

**Comment by melmac48** [comment]
Aside from the namespace, I do like the idea of adding identifiers to cell output labels.

**Comment by ildipo** [comment]
I think this is rendered obsolete by the getCodeCell api, which allows you to get the current cell output.

**Comment by scottdraves** [comment]
OK I think we could use a better UI so they can just assign a name but we have https://github.com/twosigma/beaker-notebook/issues/521 for that.  Your recent work definitely solves the problem about "too late" above.
