### ISSUE TITLE
text to slider

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5222]
https://github.com/twosigma/beakerx/blob/master/demoFiles/interactive.ipynb
the plot demo should have a slider and draw a line with the slope of a float slider 1-10 in the plot.

**Comment by konstantinTarletski** [comment]
Did 2 examples:
There is picture of one of it, but our widgets do not support "update", so it is blinking while recreating.

![default](https://cloud.githubusercontent.com/assets/10614633/26309935/a01f3e96-3f07-11e7-8d97-bea6bc112598.png)
