### ISSUE TITLE
Insert cell menu is confusing

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#523]
I don't think people will realize that two different actions are possible. The button looks like a normal ComboBox, which has only one action. I'd guess that people who haven't seen Beaker before will just click on the big part and never realize that there are other types of cells you can insert.

**Comment by scottdraves** [comment]
yes this is a big problem, thank you for pointing it out, Jeff.
How about adding a bit of separation (like 10px) as a quick fix?

**Comment by scottdraves** [comment]
Could also add the gap and put "Cell type" or "Language" or "Choose type" on the button with the triangle.
Plenty of space here.

**Comment by jchendy** [comment]
I think your second idea is on the right track. To make it crystal clear, you could clearly label both buttons with the first being "Insert Groovy Cell" (or whatever language it will be) and the second something like what you said.

**Comment by samccone** [comment]
Do we want to see what @Ljub can come up with for this?

**Comment by scottdraves** [comment]
sure all ideas are welcome

On Wed, Sep 3, 2014 at 11:43 AM, Sam Saccone notifications@github.com
wrote:

> Do we want to see what @Ljub can come up with for this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twosigma/beaker-notebook/issues/523#issuecomment-54316935
> .

## 

ScottDraves.com http://www.ScottDraves.com
google.com/+ScottDraves

**Comment by melmac48** [comment]
unless you guys are describing something different I don't see this as a big problem, As Jeff said, it looks like a combo box, I'd find it hard to believe that people wouldn't at least try to click on the arrow. I've also watched two other people do this now and they had no prob with the arrow. Happy to have have Lub take a look at it but moving to V2 for now, it's not a blocker.

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/589

**Comment by bradicdesign** [comment]
Combo box  is a very common ui pattern, especially for more advanced software. I'd close this one until we hear from users that this is a problem.
