### ISSUE TITLE
Extend MIMEContainer.MIME

### ISSUE THREAD

**Issue by hadim** [twosigma/beakerx#5242]
I know you are currently working on this, but I would like to highlight the fact that it's not currently possible to extend the mimetypes declared in `MIMEContainer.MIME` (https://github.com/twosigma/beakerx/blob/master/kernel/base/src/main/java/com/twosigma/beaker/mimetype/MIMEContainer.java#L31).

For now, I am extending the class `MIMEContainer` to be able to define custom mimetypes but it's not the best solution I think.

**Comment by hadim** [comment]
I think `MIME` should be something else than an `enum`.

**Comment by scottdraves** [comment]
thanks, i agree.  this should get fixed as part of https://github.com/twosigma/beakerx/issues/5120
