### ISSUE TITLE
make repr of null configurable

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5247]
some users prefer null to be displayed as an empty result instead of "null"
maybe https://github.com/twosigma/beakerx/pull/5120 can handle that?

**Comment by hadim** [comment]
You mean #5120 I guess :-)

**Comment by scottdraves** [comment]
What do you think a good way to configure it is?

**Comment by hadim** [comment]
As an attribute I can set overwriting `Kernel` ?

**Comment by hadim** [comment]
See https://github.com/hadim/scijava-jupyter-kernel/blob/master/src/main/java/org/scijava/jupyter/kernel/ScijavaKernel.java#L53
