### ISSUE TITLE
Error message: This site cannot be reached   127.0.0.1 refused to connect

### ISSUE THREAD

**Issue by AntonioSaragga** [twosigma/beakerx#5258]
Hello all

Just installed Beaker on Windows 7 but I am unable to launch it. The error message I am getting is "This site cannot be reached" "127.0.0.1 refused to connect"..."ERR_CONNECTION_REFUSED".  There is no problem however, for example, launching IPython/Jupyter from Python (Anaconda)

The ``beaker.pref.json`` file is the following:
``{
  "autocomplete-parameters" : "true",
  "pref-format" : "1",
  "edit-mode" : "default"
}
``
I am also attaching a file with the beaker console information received.

![beaker-console](https://cloud.githubusercontent.com/assets/1664912/25449131/b00b4aac-2ab2-11e7-9b8c-e3cb60116e0e.png)

Thank you!

**Comment by scottdraves** [comment]
I am sorry to say the accent in your name confuses nginx.  maybe you can create a different user on your computer?

**Comment by AntonioSaragga** [comment]
Thank you. Creating a different user indeed solved the problem

**Comment by scottdraves** [comment]
first reported: https://github.com/twosigma/beakerx/issues/2732
