### ISSUE TITLE
why not an official documentation available for beaker

### ISSUE THREAD

**Issue by suredream** [twosigma/beakerx#5263]
ignore me if I make mistakes.

I didn't see too much documentation page except some overview and get-started?

Also some dead-link in the wiki.

if I want to contribute a doc/wiki,  how to start?

**Comment by scottdraves** [comment]
Hi you are right but the doc really needs to be written from scratch, or ported from the old tutorials.
Beaker has recently transformed to become BeakerX and a lot of stuff is out of date.

In BeakerX, I would start by comparing the demoFiles directory with the tutorials from old Beaker and using the converter and copy/paste to flesh out the demoFiles.  Some will need to be deleted or substantially rewritten, but much content especially prose was lost in the port and it needs to be restored.
