### ISSUE TITLE
[Native Beaker] Cells work in sequence, but not together

### ISSUE THREAD

**Issue by sergeny** [twosigma/beakerx#5279]
Beaker version: electron, build time: 2016-11-21 19:41 EST version: 1.7.1
OS: OS X El Capitan 10.11.6

I have several ipython cells that work when executed one-by-one, but hang if I join them into a single cell. One-by-one they run instantaneously, there is almost no output, and not much going on overall.

I can't share the prioprietary data I am using, but I am experimenting with a<100M word2vec file from gensim, with <50K topics and a few hundred coordinates.

    from gensim.models import Word2Vec
    model = Word2Vec.load('my_model')
    L = ... # pick a few hundred strings from model.vocab
    
    # Actually obtain a vector for the key.
    def word2vec(model, key):
        return model.syn0norm[model.vocab[key].index]

    def f(mylist):
        output = []
        for d in mylist:
            output.append(word2vec(model, d))
            print d

Now if I run

    f(L[:10])

it works great. If I run

    f(L[10:20])

it also works great. I have such cells until

    f(L[160:170])

and they work fine.
But if I try to place several of them in the same cell,

    f(L[:10])
    f(L[10:20])
    f(L[20:30])

etc. or just have a cell

    f(L[:130])

then it hangs. 

I suspected that it had an output limit of 125 strings or so, so I changed the function to

    def f(mylist):
        output = []
        for d in mylist:
            output.append(word2vec(model, d))
            if len(d) % 5 == 0:            
                print d

which drastically reduced the amount of output, but it does not help at all.

When it hangs, I still have >2Gb of available memory (in top), out of 16Gb total. If I run ipython from the terminal, the same code works perfectly and instantaneously.

I really have no idea, what is going on.

Update: using the same electron version, if I open it in the browser, I get the same issue.

I also tried converting numpy arrays to lists, as in

    def f(mylist):
        output = []
        for d in mylist:
            output.append(word2vec(model, d).tolist())
            print d

to no effect. I am wondering if it's due to some code beaker is injecting...

**Comment by scottdraves** [comment]
Hi Sorry, not sure what's wrong, but all our attention is on BeakerX now.
I think this upcoming version will not have this problem.
