### ISSUE TITLE
many entries missing from Notebook menu

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#528]
![screen shot 2014-08-31 at 10 46 36 am](https://cloud.githubusercontent.com/assets/963093/4102177/ab3a8a4c-311d-11e4-961f-d99d7ecd4a47.png)

eg Show stdout/err, Delete all output cells, etc.

**Comment by scottdraves** [comment]
Oh OK "Show stdout" moved to the view menu.
But where is Delete all output, Share, and Edit mode?

**Comment by samccone** [comment]
I just followed what was outlined in the design I know Ljub put a bunch of thought into the items that are shown. Perhaps he has some insight into this.
