### ISSUE TITLE
The link in the Wiki seems invalid

### ISSUE THREAD

**Issue by HeGaoYuan** [twosigma/beakerx#5281]
ALL links in the Wiki seems invalid.
Could you fix it as soon as possible?
Thank you very much!!!

**Comment by scottdraves** [comment]
sorry the wiki has been broken by moving to beakerx.
trying to figure it out...

thx for bringing that up.

**Comment by scottdraves** [comment]
wiki has been restored here afaik.
if you still see bad links please provide the details.
thanks again.
