### ISSUE TITLE
adjust table formatting defaults

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5286]
1. instead of showing 4 digits it should show 3
2. dates should be shown with yyyyMMdd hh:mm:ss.SSS instead of yyyy-MM-dd hh:mm:ss.SSS Z
3. tighten up the spacing.  there was an "advanced mode" in classic beaker that does not exist in BeakerX. please use advanced mode for tables.  if we already are using it, then tighten it up some more. maybe make the text 1 point smaller.

**Comment by jszalek** [comment]
@scottdraves I couldn't find anything about 'advanced mode' in js code.
I only found class in css so I changed defualt height of tr from 27px to 22px.
