### ISSUE TITLE
Java imports need to be further adjusted for Scala

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#5287]
Since the Scala kernel is using the default JVM imports, two adjustments are needed beyond the already implemented changing of the wildcard.  They are:

1. Remove `static`
2. Escape the package name `object`, which is a Scala keyword.  (This is used in one of the default import paths, `com.twosigma.beaker.jvm.object.OutputCell`.)

On the second point, it's conceivable that other Scala keywords that aren't Java keywords might show up in package names, but no others seem very likely, so a one-off replacement is probably fine.

**Comment by scottdraves** [comment]
Thank you Joe.  Agreed.

**Comment by jpallas** [comment]
I've got some code for this in my workspace.  Working on a unit test.
