### ISSUE TITLE
reduce horizontal space in table columns

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5301]
![screen shot 2017-05-12 at 10 46 41 am](https://cloud.githubusercontent.com/assets/963093/26003426/a66c5284-3700-11e7-8cef-9c02e0c6f491.png)

**Comment by MariuszJurowicz** [comment]
@scottdraves 
Isn't that a space reserved for the hamburger menu? The hamburger menu is shown on cell hover so if i reduce the space the menu icon will overlap the header text.

**Comment by scottdraves** [comment]
good point i forgot that.  but i think some overlap will be a smaller bug than this space,
can you give it a try?

**Comment by scottdraves** [comment]
![screen shot 2017-05-17 at 11 37 14 am 2](https://cloud.githubusercontent.com/assets/963093/26162763/a1019842-3af5-11e7-8b8b-108608070289.png)


there seems to be too much space even accounting for the menu.

**Comment by MariuszJurowicz** [comment]
Ok, i'll fix this one.
