### ISSUE TITLE
easyform's editable combo box broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5309]
open EasyFormDemos.ipynb and run the cell with `g.addComboBox("Editable Combo", options, true)`

the resulting field does not respond to the mouse.  it should pop up a menu if you click on the drop-down triangle, and the text should be editable if you click on it.  it works in classic beaker for comparison.

**Comment by MariuszJurowicz** [comment]
It seems that the `Dropdown` widget that is implemented by `ComboBox` has been reverted to the native select control:
https://github.com/jupyter-widgets/ipywidgets/pull/1057
That is why the ComboBox is not using it's previous view.

**Comment by michalgce** [comment]
`exports.DropdownModel = DropdownModel;

// TODO: Make a phosphor dropdown control, wrapped in DropdownView. Also, fix

// bugs in keyboard handling. See

// https://github.com/ipython/ipywidgets/issues/1055 and

// https://github.com/ipython/ipywidgets/issues/1049

// For now, we subclass SelectView to provide DropdownView

// For the old code, see commit f68bfbc566f3a78a8f3350b438db8ed523ce3642`
