### ISSUE TITLE
on windows on hover, geometry vanishes

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5322]
![image](https://cloud.githubusercontent.com/assets/963093/26137914/6ea35096-3a93-11e7-99fa-601281515b01.png)

**Comment by scottdraves** [comment]
i am pretty sure i have seen this on mac too.
the bug is hard to reproduce though, unclear what the trigger is.

**Comment by LeeTZ** [comment]
No longer reproducable
