### ISSUE TITLE
Review default notebook

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#533]
We should review the default notebook, identify what's is important (e.g. include a JS cell or not). And address the concern of the purposes of the default notebook
related:
https://github.com/twosigma/beaker-notebook/issues/514

**Comment by scottdraves** [comment]
Yup, what we do now is messy.  Advanced users expect a truly empty document.  

Beginners should be more easily redirected to the tutorial, maybe by making that  a button next to "New Notebook".  And we should make the first tutorial smaller and include more links to follow-up tutorials on various subjects.

The hard part is, what languages does the tutorial cover?  It seems like it should be targeted to what's available....

**Comment by scottdraves** [comment]
how about this: https://github.com/twosigma/beaker-notebook/issues/574

**Comment by melmac48** [comment]
Review has been complete. #574 has been created to track the fix
