### ISSUE TITLE
[Native Beaker] Unable to initializing Julia 0.5 on Windows 7

### ISSUE THREAD

**Issue by Iscalc** [twosigma/beakerx#5357]
On Windows 7 after setting``beaker.pref.json`` as:

``"languages" : {
    "IPython" : {
      "path" : "C:\\Users\\Iscalc\\Anaconda2"
    },
    "Python3" : {
      "path" : "C:\\Anaconda3\\python"
    },
    "Julia" : {
      "path" : "C:\\JuliaPro-0.5.0.5\\Julia-0.5.0\\bin"
    },
    "R" : {
      "path" : "C:\\R\\R-3.4.0\\bin\\x64"
    },
    "Kdb" : {
      "path" : "c:\\q\\w32"
    }
  },``

I am unable to initialize either Julia, Python or Kdb. However, it is possible to run R and SQL.

**Comment by scottdraves** [comment]
hi, thaks for the report.
we are working on a new version of Beaker called BeakerX that should fix this problem, among many others.  please see the README of this repository for more info.
