### ISSUE TITLE
Unable to load python and R plugin on latest master

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#538]
![](http://dl.dropbox.com/u/36928599/Screenshots/0ig.png)

**Comment by scottdraves** [comment]
sam is this still an issue for you?
i am not able to reproduce.

**Comment by samccone** [comment]
It still is for me,  not sure

**Comment by melmac48** [comment]
@samccone we can't reproduce this interanally.. can you see if you can reproduce this with a different system at MT and if not, lets close it for now.

**Comment by samccone** [comment]
Closing for now, will so a fresh wipe on my system

**Comment by samccone** [comment]
Odd, a fresh install of beaker-notebook fixed this issue.
