### ISSUE TITLE
clang not listed as dependency for building

### ISSUE THREAD

**Issue by dsblank** [twosigma/beakerx#5420]
I had been trying to figure out how to build beakerx on Ubuntu for quite some time. I thought maybe it was version of java, or a config issue. Finally figured out that I needed:

```
sudo apt install clang
```

**Comment by dsblank** [comment]
Also `npm` is needed. Getting close...

**Comment by dsblank** [comment]
Also needed `nodejs-legacy`

**Comment by dsblank** [comment]
After getting all of the install commands to run, `jupyter notebook` then failed with this cryptic message:

```
[C 12:23:36.529 NotebookApp] Bad config encountered during initialization:
[C 12:23:36.529 NotebookApp] The 'kernel_spec_class' trait of <jupyter_client.kernelspec.KernelSpecManager object at 0x7f51ff5e00f0> instance must be a type, but 'beaker.kernel_spec.BeakerXKernelSpec' could not be imported
```

I tried the commands to Update after changes, and discovered that I needed to:

```
cd beakerx/js
npm rebuild node-sass --force
yarn webpack
```

Perhaps this was because I did not have nodejs-legacy installed initially.

I then went back and re-ran all of the install commands again, and... some things work! (Running master, and can never run two cells... one cell works, but not the second...)

**Comment by scottdraves** [comment]
Hi Doug thanks for bringing this up.  Clang makes sense, though maybe best solved by skipping C++ since it's not really working yet anyway.

But doesn't npm come with node?  And why would we need legacy node?  The latest works afaik.  It seems like something has gone.  Several of our developers use Linux, and they have not brought this up.  Can you say more about the system you are building on?

Maybe we should bring our Docker container back, that should solidify the Linux deps and build process.

**Comment by dsblank** [comment]
I'm really only trying to build Java, but just following the instructions on your README. I couldn't get anything to build unless I installed clang, npm, and nodejs-legacy, etc. I'm not that familiar with the java nor node development environments. 

I'm working on a standard Ubuntu 16.04 64-bit system. 

I prefer to work in a non-Docker system, because I would like to deploy on a standard JupyterHub server. At least for now. 

What is the state of master right now? Things generally working? Or are the running problems I describe typical?

**Comment by scottdraves** [comment]
I mention Docker because that will clarify exactly what is required to build from fresh Ubuntu, not because you would use it.

Master is good we use it all the time.

Let me ask those who use Ubuntu to chime in, and get clarity on Ubuntu deps.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/issues/5421

should probably just take C++ out of default.

**Comment by dsblank** [comment]
Yes, it would be good to see the Docker build, or be able to use it. 

That is great that master is working; but that means that something is very wrong with my build. 

Is there any place where the beakerx Java semantics are defined? To answer questions like:

* can you redefine classes?
* what is the relationship between beakerx Java and jshell? Differences?

**Comment by dsblank** [comment]
Should `jupyter console --kernel java` work? This is what I see:

```
$ jupyter console --kernel java --debug
[ZMQTerminalIPythonApp] Searching ['/home/dblank', '/home/dblank/.jupyter', '/home/dblank/miniconda3/envs/beakerx/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[ZMQTerminalIPythonApp] Looking for jupyter_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /home/dblank/miniconda3/envs/beakerx/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /home/dblank/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in /home/dblank
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /usr/local/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /home/dblank/miniconda3/envs/beakerx/etc/jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /home/dblank/.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in /home/dblank
[ZMQTerminalIPythonApp] Connection File not found: /run/user/1000/jupyter/kernel-6086.json
[ZMQTerminalIPythonApp] Found kernel java in /home/dblank/miniconda3/envs/beakerx/share/jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel sql in /home/dblank/miniconda3/envs/beakerx/share/jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel groovy in /home/dblank/miniconda3/envs/beakerx/share/jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel cpp in /home/dblank/miniconda3/envs/beakerx/share/jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel clojure in /home/dblank/miniconda3/envs/beakerx/share/jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel scala in /home/dblank/miniconda3/envs/beakerx/share/jupyter/kernels
[ZMQTerminalIPythonApp] Found kernel python3 in /home/dblank/miniconda3/envs/beakerx/share/jupyter/kernels
[ZMQTerminalIPythonApp] Starting kernel: ['java', '-jar', '/home/dblank/beakerx/kernel/java/build/libs/java.jar', '/run/user/1000/jupyter/kernel-6086.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:44278
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:34714
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:34714
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:49302
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:49302
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:36430
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:36430
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:51198
Jupyter console 5.1.0

BeakerX kernel for Java

[ZMQTerminalIPythonApp] Starting the jupyter console mainloop...

In [1]: 1
[Thread-0] INFO com.twosigma.beaker.jupyter.msg.MessageCreator - Execution result ERROR: The kernel was not ready, run the cell again.
The kernel was not ready, run the cell again.

In [2]: 2
[Thread-0] INFO com.twosigma.beaker.jupyter.msg.MessageCreator - Execution result ERROR: The kernel was not ready, run the cell again.
The kernel was not ready, run the cell again.

In [3]:                                                                                                                                      
Do you really want to exit ([y]/n)? 
Shutting down kernel
(beakerx) dblank@hadaly:~$
```

**Comment by scottdraves** [comment]
console is currently broken, notebook works. https://github.com/twosigma/beakerx/issues/5330

**Comment by scottdraves** [comment]
actually even in the notebook, you are right, java has the problem of hanging after 1 cell :(

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/commit/7a32cf6a6f2706dcb422adba1e989bf717394d47

java notebook fixed thx to @michalgce for working late.

**Comment by scottdraves** [comment]
To answer your questions above, I don't know much about jshell afaik it's coming with Java 9 which is still not released.

Yes BeakerX java allows redefining classes, if I understand you correctly.  Eg run the 1st cell of demoFiles/javaTutorial.ipynb, then change the code (eg the "Today" string) and run that cell again.
Then run the 2nd cell.  It uses the new definition.
