### ISSUE TITLE
Regenerate our Dockerfile

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5421]
We used to have this: https://github.com/twosigma/beaker-notebook-archive/blob/1.7.1/Dockerfile
get it working again.

Use a base image like we did before:
https://github.com/twosigma/beaker-notebook-archive/blob/1.7.1/base_docker_image/Dockerfile

**Comment by scottdraves** [comment]
base it on ubuntu 16.04 LTS

**Comment by prskr** [comment]
Hi,

I created a Dockerfile of beakerx [https://github.com/baez90/beakerx-docker](https://github.com/baez90/beakerx-docker).
I took the scripts from [https://github.com/jupyter/docker-stacks](https://github.com/jupyter/docker-stacks) and adopted them to beakerx.

I'm not an docker expert so it might be necessary to do some optimization but it might help you and it's working for me.
