### ISSUE TITLE
Can't build on Ubuntu 17.04

### ISSUE THREAD

**Issue by dsblank** [twosigma/beakerx#5423]
Successfully built on Ubuntu 16.04. Everything was building fine on a Ubuntu 17.04 Linux 64-bit computer until I got here:

```
$ ./gradlew :beakerx:install
:beakerx:install FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/dblank/beakerx/beakerx/build.gradle' line: 31

* What went wrong:
Execution failed for task ':beakerx:install'.
> Could not get unknown property 'install' for task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
I suspect that I have a version of something that is too modern:

```
(beakerx) dblank@ASUS-Laptop:~/beakerx$ echo $JAVA_HOME 
/opt/jvm/jdk1.8.0_131
(beakerx) dblank@ASUS-Laptop:~/beakerx$ ./gradlew --version

------------------------------------------------------------
Gradle 3.5
------------------------------------------------------------

Build time:   2017-04-10 13:37:25 UTC
Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6

Groovy:       2.4.10
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Linux 4.10.0-21-generic amd64

(beakerx) dblank@ASUS-Laptop:~/beakerx$ node --version
v5.12.0
(beakerx) dblank@ASUS-Laptop:~/beakerx$ npm --version
3.8.6
(beakerx) dblank@ASUS-Laptop:~/beakerx$ javac -version
javac 1.8.0_131
(beakerx) dblank@ASUS-Laptop:~/beakerx$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
(beakerx) dblank@ASUS-Laptop:~/beakerx$ yarn --version
0.27
```

**Comment by altavir** [comment]
It should work. You probably just have a broken repository. 
Line 31 in `beakerx/beakerx/build.gradle`: `project('js').tasks.install.execute()`. It should be replaced by task dependency like `dependsOn ':beakerx:js:install'`

**Comment by dsblank** [comment]
That gives:

```
Cannot call Task.dependsOn(Object...) on task ':beakerx:install' after task has started execution.
```

**Comment by dsblank** [comment]
How would my repository get broken?

**Comment by altavir** [comment]
@dsblank `dependsOn` must be in the main task body of the task (outside of `doLast`) or in task properties (in round brackets like `task install(dependsOn: ':beakerx:js:install')`). The way it is currently written is not the correct gradle way since it does not create task dependency tree and must be fixed, but it still should work. It does not find `install` task in [this file](https://github.com/twosigma/beakerx/blob/master/beakerx/js/build.gradle). Check if it is there.

**Comment by dsblank** [comment]
It appears that the problem is in what `beakerx:js:install` is attempting to run: `yarn install`. There are significant changes between yarn 0.24.5 and yarn 0.27. 

Some details:

* On Ubuntu 16.04, yarn 0.24.5 appears to be written in Javascript and requires `nodejs` and Node.js 4.0 or greater
* On Ubuntu 17.04, yarn 0.27 appears to be written in Python 2.7 and acts differently than earlier versions.

**Comment by scottdraves** [comment]
link?

**Comment by dsblank** [comment]
Link to what? This is just my personal investigation.

**Comment by scottdraves** [comment]
could be this?
https://github.com/yarnpkg/yarn/issues/3189

**Comment by dsblank** [comment]
Yes, thanks, that is it! I'm working on proper installation...

**Comment by dsblank** [comment]
Ok, after many months of attempting to build and run beakerx, I now have a (mostly) working system! Thank you very much for the hints. Now, maybe I can help answer the questions on differences between, say, https://github.com/Bachmann1234/java9_kernel and beakerx Java... 

Notes on what I needed to do on Ubuntu 17.04 for installation:

```
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install yarn
unset JAVA_HOME # was incorrect; I use "update-alternatives" to manage defaults
```
plus the other notes mentioned in https://github.com/twosigma/beakerx/issues/5420
