### ISSUE TITLE
brackets missing from list in table

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5425]
```
def myMap = [:]
def myList = []
myList << [1, 2, 3]
myList << [2, 3, 4]
myMap.put(1, myList)
println(myList)
myMap
```
produces
![screen shot 2017-06-02 at 6 30 50 pm](https://cloud.githubusercontent.com/assets/963093/26747099/a4d86d14-47c1-11e7-9e27-574df70aad21.png)

but the value in the table should have brackets like it does when printed.

**Comment by scottdraves** [comment]
same as https://github.com/twosigma/beakerx/issues/5426

**Comment by jszalek** [comment]
@scottdraves 
fixed in https://github.com/twosigma/beakerx/pull/5503
