### ISSUE TITLE
objects not display right in table

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5426]
run this groovy:
```
def myMap = [:]
def myList = [num1:1, num2:2]
myMap.put(1, myList)
println(myList)
myMap
```
the results in

![screen shot 2017-06-02 at 6 39 22 pm](https://cloud.githubusercontent.com/assets/963093/26747303/da6c2136-47c2-11e7-8e6e-d6257965ba0a.png)

but it should show the normal representation in the table.

**Comment by scottdraves** [comment]
the data is correct in the model, just need to convert to string.
<img width="213" alt="screen shot 2017-06-11 at 9 55 00 pm" src="https://user-images.githubusercontent.com/963093/27016707-c62b3f2e-4ef0-11e7-90f2-801d00ca03e9.png">

it is OK for now for to use JSON here.

**Comment by jszalek** [comment]
@scottdraves fixed in https://github.com/twosigma/beakerx/pull/5503
