### ISSUE TITLE
Java: as soon as there is one error, next cell hangs

### ISSUE THREAD

**Issue by dsblank** [twosigma/beakerx#5427]
Using the Java kernel, if I have any error, the next cell hangs forever:

![screenshot from 2017-06-03 09-05-28](https://cloud.githubusercontent.com/assets/168568/26753764/d389f0a4-483b-11e7-88ec-227e2a5406e1.png)

**Comment by dsblank** [comment]
Actually, it is the cell that errors never finishes.

**Comment by dsblank** [comment]
Cancelling a cell also doesn't return to a useable state:

![screenshot from 2017-06-03 09-17-55](https://cloud.githubusercontent.com/assets/168568/26753848/997094f2-483d-11e7-8d72-c24e60c55b75.png)

**Comment by scottdraves** [comment]
thx, probably another case like the last one.

**Comment by scottdraves** [comment]
should be good now.  thx again.
