### ISSUE TITLE
error in cell run by plot action goes to wrong location

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5441]
open plotActions.ipynb and run just the 3rd cell, then click on the line.  the plot vanishes and the following error appears on the console:

```
Exception in thread "Thread-0" groovy.lang.MissingPropertyException: No such property: abc for class: script1496843416196163566422
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:51)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:304)
        at script1496843416196163566422$_run_closure1.doCall(script1496843416196163566422.groovy:6)
...
```
and the kernel is stuck and cannot evaluate any more cells (any cell will hang).

1) the error should appear on the cell output, not on the console.
2) the kernel should not get stuck.

**Comment by konstantinTarletski** [comment]
The same problem was in "inractive" , I fixed it.
Inractive works fine now, but not table/plot API.
Now kernel not get stuck at all casees.
But there is the problem with displaying something in console (table/plot API). 
The problem is "parrent message": we need to pass correct parent message, to get ability print anything to the jupyter console.
I afraid it is not simple task.
Need to check what message passed in "interactive" and pass same in plot/table API.

**Comment by scottdraves** [comment]
👍 cool does not get stuck.
what's the difference between errors for tables and plots though?
i am seeing the ones for tables correctly but not plots.

**Comment by konstantinTarletski** [comment]
TableDisplay.setDoubleClickAction() works so : 
if Yoou put tag, it deletes handler
if You put handler, it deletes tag
this behavior was taken from "old beaker"

```
  public void setDoubleClickAction(Object listener) {
    this.doubleClickTag = null;
    this.doubleClickListener = listener;
  }

  public void setDoubleClickAction(String tagName) {
    this.doubleClickListener = null;
    this.doubleClickTag = tagName;
  }
```

About same happens in 
`TableDisplay.addContextMenuItem()`

In Plots it is possible to assign muptiple actions to `Graphics`
Graphics --- Base object, Plot line for example

Now "update" works for Table/Plot API

**Comment by konstantinTarletski** [comment]
Now Table/Plot API supports any code in handlers :

![default](https://user-images.githubusercontent.com/10614633/27132368-53a009b6-5117-11e7-811e-e339fa0834e4.png)

Also it prints to console, if there is error in handler:

![default](https://user-images.githubusercontent.com/10614633/27132408-7fec27e8-5117-11e7-8243-179af8182a7c.png)

It is possible to create more interesting demo, but it takes time.
