### ISSUE TITLE
improve groovy magic

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5442]
following https://github.com/twosigma/beakerx/pull/5398 we still need:

1. return complex results, not just making a string of everything.  try evaluating `new Plot()` or `println("stdout")` and make those work the same as in a regular groovy notebook.  ditto for errors.  Essentially, it's a Comm proxy.
2. reuse the kernel.  looks like a new one is being created for each cell:
![screen shot 2017-05-30 at 2 51 40 pm](https://cloud.githubusercontent.com/assets/963093/26599816/ef44aba0-4547-11e7-9918-9cade989cb4a.png)

and

3. do not start the kernel until a groovy cell is evaluated.
4. why are there two source files (beakerx/groovy_magic.py and beakerx/beakerx/groovy_magic.py).  seems it should all go in one.

**Comment by michalgce** [comment]
@scottdraves Ad.2 is done. Kernel is initialised once
