### ISSUE TITLE
magic/empty code return value

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5477]
if the jar has already been loaded and this is a noop, then it should be like output.hidden, as if you ran an empty cell for example.

if the jar has not been loaded, then it should print as if it were stdout "added *jar-name*"

![screen shot 2017-06-14 at 9 29 31 am](https://user-images.githubusercontent.com/963093/27134590-09d4fb62-50e4-11e7-803a-fd2c82f10094.png)

**Comment by jaroslawmalekcodete** [comment]
The issue was fixed in PR https://github.com/twosigma/beakerx/pull/5553, please verify.

**Comment by scottdraves** [comment]
> if the jar has not been loaded, then it should print as if it were stdout "added jar-name"

not seeing this part...

**Comment by michalgce** [comment]
May we close this issue @scottdraves ?
