### ISSUE TITLE
The Sharing menu has duplicate entries

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#548]
![image003](https://cloud.githubusercontent.com/assets/883126/4154211/bf79a052-345f-11e4-93f1-b502bbbd4113.jpg)

**Comment by samccone** [comment]
Hmm unable to reproduce on local master

@anglee @scottdraves can your produce?

**Comment by melmac48** [comment]
@anglee any chance this is an internal only issue? if so, move to v2

**Comment by melmac48** [comment]
sounds like this is fixed
