### ISSUE TITLE
Execution failed for task ':kernel:cpp:makeCRunLib'

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#5489]
When I run command `./gradlew --no-daemon build` I will get error:
````sh
:kernel:cpp:makeCRunLib FAILED
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':kernel:cpp:makeCRunLib'.
A problem occurred starting process 'command 'clang++'
````
How to fix: install clang++
To check version: `clang++ --version`
How to reproduce: remove clang++, remove folder beakerx/kernel/cpp/build, remove autogenerated files (cpp, cpp.bat, CppKernel.h, libCRun.jnilib) on folder beakerx/kernel/cpp/src/main/resources 

I propose to add clang++ to [Dependencies](https://github.com/twosigma/beakerx#dependencies)

**Comment by scottdraves** [comment]
dup of https://github.com/twosigma/beakerx/issues/5429
