### ISSUE TITLE
Unnecessary line feeds added to markdown cell

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#549]
unnecessary line feeds added to markdown cell after you finish editing, in both regular and advanced mode (Version 1). Also (this could be my lack of experience with markdown editors) but when I add line breaks, for example writing a line, hitting enter and writing another line. It gets rendered as a single line.
![image004](https://cloud.githubusercontent.com/assets/883126/4154232/fb43c888-345f-11e4-93ce-9d784ceb99de.jpg)

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/454

**Comment by melmac48** [comment]
we'll address the markdown cell in v2

**Comment by melmac48** [comment]
dup of 454
