### ISSUE TITLE
Add a “last edited” line to the notebooks on control pane

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#550]
Add a “last edited” line to the notebooks on control panel? and the text should read Opened on

![image005](https://cloud.githubusercontent.com/assets/883126/4154314/8f68e9d0-3460-11e4-9a46-bc1a3f82aaf0.jpg)

**Comment by samccone** [comment]
Currently we do not store the last Edited time in the app

@scottdraves @anglee what do you guys think?

**Comment by melmac48** [comment]
if we can't do this easily then lets push to v2
