### ISSUE TITLE
Scala evaluator gives no feedback for some malformed input

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#5508]
The Scala interpreter has three return cases: success, error, and "incomplete".  If the input has unclosed braces, parentheses, or quotes, it is incomplete.  Right now that case gives no feedback to the user, because it is handled the same as an error but there is no error message.

Coming PR will distinguish all three cases and generate an "incomplete input" message when appropriate.

**Comment by scottdraves** [comment]
👍  many thanks
