### ISSUE TITLE
apply fonts to outputs

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5535]
monospace outputs should be roboto mono also:
![screen shot 2017-06-22 at 4 08 13 pm](https://user-images.githubusercontent.com/963093/27453669-442a3c96-5765-11e7-8df3-fe07c85311d6.png)
and html outputs should be Lato.
![screen shot 2017-06-22 at 4 11 33 pm](https://user-images.githubusercontent.com/963093/27453763-856c4212-5765-11e7-8268-02ee306e8a0f.png)

**Comment by scottdraves** [comment]
html outputs done but monospace outputs are still rendering up as monospace.  should be roboto mono.  try that "1*1" example.

**Comment by jszalek** [comment]
@scottdraves please test it again after apply 'custom' directory
