### ISSUE TITLE
make bold fonts bolder

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5543]
the new fonts, when they are bold, are not bold enough.  is there a way to boost the weight?

**Comment by jszalek** [comment]
changed Bold to Black on branch `kuba/5537_removejs`
![zrzut ekranu 2017-06-28 o 15 01 21](https://user-images.githubusercontent.com/6450797/27638411-74d250e2-5c13-11e7-8d19-ed503f1df3dc.png)
![zrzut ekranu 2017-06-28 o 15 01 56](https://user-images.githubusercontent.com/6450797/27638410-74bf5a1e-5c13-11e7-9d99-b39f0a0217df.png)

**Comment by scottdraves** [comment]
What about for code (ie Roboto Mono)?
Try a Python 3 notebook that has cell like `def f(x):`
"def" should be bold.
