### ISSUE TITLE
Markdown cells overflow the border when hierarchy is shown

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#555]
![image008](https://cloud.githubusercontent.com/assets/883126/4154543/74ed3bf4-3462-11e4-9f1b-78be38caa958.png)

**Comment by samccone** [comment]
I have dug into this one for a while and it is an issue of epic editor and its sizing logic.
Since epic editor is basically unmaintained now I think the solution is to either investigate another markdown editor or go in and fork epic editor

**Comment by melmac48** [comment]
will address markdown as a whole in v2

**Comment by scottdraves** [comment]
fixed when we dropped epic and the iframe
