### ISSUE TITLE
output in container is wrong typeface

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5552]
results in outputcontainer should be the same as when not in the container.
at least the typeface has changed.
![screen shot 2017-06-26 at 10 05 09 am](https://user-images.githubusercontent.com/963093/27543013-f59ae11c-5a56-11e7-9f5e-728cbe2a4aef.png)

**Comment by jszalek** [comment]
@scottdraves please test it again after apply 'custom' directory

**Comment by scottdraves** [comment]
still a problem, result is unchanged.

**Comment by jszalek** [comment]
First example (OutputContainer) uses HTML-display widget, so its font is 'Lato'.
Second example prints output directly into `<pre>` tags so it is a "Roboto Mono".

Which font-family would you like to change?

**Comment by scottdraves** [comment]
The first example should be in Roboto Mono.

**Comment by scottdraves** [comment]
make sure an outputcontainer of an html mime result display correctly though (in lato).

**Comment by scottdraves** [comment]
1st cell is correct in lato.  2nd cell has 3 errors:
* there is extra text "com.twosigma.beakerx.mimetype.MIMEContainer$MIME@7c14dcb3[mime=text/html] CODE ="
* "title" should be lato
* other outputs in the container should be roboto mono (described above) 
![screen shot 2017-07-05 at 10 12 31 am](https://user-images.githubusercontent.com/963093/27868349-7b2738f2-616a-11e7-8852-d8e3968a263b.png)
