### ISSUE TITLE
update demos to D3 v4

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5559]
the autotranslation demos use an old version:
<img width="529" alt="screen shot 2017-06-27 at 7 40 48 am" src="https://user-images.githubusercontent.com/963093/27585869-d9a1d230-5b0b-11e7-8057-e15f06fe1bf6.png">

**Comment by jszalek** [comment]
`beakerx.graph` is undefined after any change in notebook
I cannot run chart.
