### ISSUE TITLE
Table header alignment is incorrect 

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#556]
![image009](https://cloud.githubusercontent.com/assets/883126/4154579/b3be771c-3462-11e4-8525-b867ce19d7e1.png)

**Comment by melmac48** [comment]
Discussed with Sam, this is a non trivial fix. We can live with the off by one error on the header for now.

**Comment by melmac48** [comment]
fixed as part of new output display

**Comment by samccone** [comment]
:+1:
