### ISSUE TITLE
CombinedPlot JS fails

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5568]
in plotDemo, cell 17 or so:

<img width="622" alt="screen shot 2017-06-28 at 11 27 04 pm" src="https://user-images.githubusercontent.com/963093/27670175-2b26e520-5c59-11e7-8341-d3619888cc7b.png">

**Comment by jszalek** [comment]
@scottdraves added missing method
@konstantinTarletski Annotations say that is your change. Please check if this method is necessary in CombinedPlots.
