### ISSUE TITLE
JSON MIMEContainer should be received as JSON and not string on the client side

### ISSUE THREAD

**Issue by hadim** [twosigma/beakerx#5573]
I am trying to display Vega plot using the Scijava kernel:

```groovy
import com.twosigma.beakerx.mimetype.MIMEContainer;
fname = "/home/hadim/.doc/Code/Notebooks/Sandbox/Vega Plots/bar-chart.vg.json"
fileContents = new File(fname).text
new MIMEContainer("application/vnd.vega.v2+json", fileContents)
```

I am using Jupyter lab from `master` which can render Vega string (`application/vnd.vega.v2+json`) without issue from a file. Here I am trying to render Vega plot from a notebook in a cell.

The plot does not render and the console shows the following:

```
[W 11:06:45.861 LabApp] 404 GET /%7B%20%20%22width%22:%20400,%20%20%22height%22:%20200,%20%20%22padding%22:%20%7B%22top%22:%2010,%20%22left%22:%2030,%20%22bottom%22:%2030,%20%22right%22:%2010%7D,%20%20%22data%22:%20[%20%20%20%20%7B%20%20%20%20%20%20%22name%22:%20%22table%22,%20%20%20%20%20%20%22values%22:%20[%20%20%20%20%20%20%20%20%7B%22x%22:%201,%20%20%22y%22:%2028%7D,%20%7B%22x%22:%202,%20%20%22y%22:%2055%7D,%20%20%20%20%20%20%20%20%7B%22x%22:%203,%20%20%22y%22:%2043%7D,%20%7B%22x%22:%204,%20%20%22y%22:%2091%7D,%20%20%20%20%20%20%20%20%7B%22x%22:%205,%20%20%22y%22:%2081%7D,%20%7B%22x%22:%206,%20%20%22y%22:%2053%7D,%20%20%20%20%20%20%20%20%7B%22x%22:%207,%20%20%22y%22:%2019%7D,%20%7B%22x%22:%208,%20%20%22y%22:%2087%7D,%20%20%20%20%20%20%20%20%7B%22x%22:%209,%20%20%22y%22:%2052%7D,%20%7B%22x%22:%2010,%20%22y%22:%2048%7D,%20%20%20%20%20%20%20%20%7B%22x%22:%2011,%20%22y%22:%2024%7D,%20%7B%22x%22:%2012,%20%22y%22:%2049%7D,%20%20%20%20%20%20%20%20%7B%22x%22:%2013,%20%22y%22:%2087%7D,%20%7B%22x%22:%2014,%20%22y%22:%2066%7D,%20%20%20%20%20%20%20%20%7B%22x%22:%2015,%20%22y%22:%2017%7D,%20%7B%22x%22:%2016,%20%22y%22:%2027%7D,%20%20%20%20%20%20%20%20%7B%22x%22:%2017,%20%22y%22:%2068%7D,%20%7B%22x%22:%2018,%20%22y%22:%2016%7D,%20%20%20%20%20%20%20%20%7B%22x%22:%2019,%20%22y%22:%2049%7D,%20%7B%22x%22:%2020,%20%22y%22:%2015%7D%20%20%20%20%20%20]%20%20%20%20%7D%20%20],%20%20%22scales%22:%20[%20%20%20%20%7B%20%20%20%20%20%20%22name%22:%20%22x%22,%20%20%20%20%20%20%22type%22:%20%22ordinal%22,%20%20%20%20%20%20%22range%22:%20%22width%22,%20%20%20%20%20%20%22domain%22:%20%7B%22data%22:%20%22table%22,%20%22field%22:%20%22x%22%7D%20%20%20%20%7D,%20%20%20%20%7B%20%20%20%20%20%20%22name%22:%20%22y%22,%20%20%20%20%20%20%22type%22:%20%22linear%22,%20%20%20%20%20%20%22range%22:%20%22height%22,%20%20%20%20%20%20%22domain%22:%20%7B%22data%22:%20%22table%22,%20%22field%22:%20%22y%22%7D,%20%20%20%20%20%20%22nice%22:%20true%20%20%20%20%7D%20%20],%20%20%22axes%22:%20[%20%20%20%20%7B%22type%22:%20%22x%22,%20%22scale%22:%20%22x%22%7D,%20%20%20%20%7B%22type%22:%20%22y%22,%20%22scale%22:%20%22y%22%7D%20%20],%20%20%22marks%22:%20[%20%20%20%20%7B%20%20%20%20%20%20%22type%22:%20%22rect%22,%20%20%20%20%20%20%22from%22:%20%7B%22data%22:%20%22table%22%7D,%20%20%20%20%20%20%22properties%22:%20%7B%20%20%20%20%20%20%20%20%22enter%22:%20%7B%20%20%20%20%20%20%20%20%20%20%22x%22:%20%7B%22scale%22:%20%22x%22,%20%22field%22:%20%22x%22%7D,%20%20%20%20%20%20%20%20%20%20%22width%22:%20%7B%22scale%22:%20%22x%22,%20%22band%22:%20true,%20%22offset%22:%20-1%7D,%20%20%20%20%20%20%20%20%20%20%22y%22:%20%7B%22scale%22:%20%22y%22,%20%22field%22:%20%22y%22%7D,%20%20%20%20%20%20%20%20%20%20%22y2%22:%20%7B%22scale%22:%20%22y%22,%20%22value%22:%200%7D%20%20%20%20%20%20%20%20%7D,%20%20%20%20%20%20%20%20%22update%22:%20%7B%20%20%20%20%20%20%20%20%20%20%22fill%22:%20%7B%22value%22:%20%22steelblue%22%7D%20%20%20%20%20%20%20%20%7D,%20%20%20%20%20%20%20%20%22hover%22:%20%7B%20%20%20%20%20%20%20%20%20%20%22fill%22:%20%7B%22value%22:%20%22red%22%7D%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%7D%20%20%20%20%7D%20%20]%7D (127.0.0.1) 3.67ms referer=http://127.0.0.1:8888/lab
```

Here is the error from the JS console:

![screenshot from 2017-06-29 11-09-56](https://user-images.githubusercontent.com/528003/27694921-88d4da58-5cbb-11e7-8820-98ffc3975a3b.png)

I am not absolutely sure the error is coming from the kernel. Maybe you'll have an opinion about it.

(Note that GIF or other image types render correctly using `image/gif`)

ping @scottdraves

**Comment by hadim** [comment]
The following:

```
nb.displayMimetype("application/vnd.vega.v2+json", "test")
```

returns this into the terminal:

```
404 GET /test (127.0.0.1) 1.77ms referer=http://127.0.0.1:8888/lab
```

Why is the content `test` use as an URL? Is it a normal behaviour?

**Comment by scottdraves** [comment]
hey thanks for the report but not sure what you mean.
i tried
```
new MIMEContainer("application/vnd.vega.v2+json", "test")
```
with our groovy kernel and didn't see any 404.

**Comment by hadim** [comment]
I just checked the Scijava kernel where:

```
this.seo.finished(output);
```

and `output` is a `MIMEContainer` object (in the case I am running the cell shown in my first post).

If `seo.finished` received a `MIMEContainer` object, ca you confirm it is supposed to send the data to the client, labeled according to the `MIMEContainer` mimetype?

**Comment by hadim** [comment]
The 404 message only happens with Jupyter Lab.

**Comment by hadim** [comment]
I confirm the issue is coming from the kernel. I checked with JLab guys and it appears that the message sent to the kernel is a serialized string of a serialized JSON string. See the gitter discussion related: https://gitter.im/jupyterlab/jupyterlab?at=595bdcf6f5b3458e30114a17

**Comment by hadim** [comment]
For example see the message object in JS when using a Python kernel (with the Altair lib):

![altair](https://user-images.githubusercontent.com/528003/27840582-301d8b6a-60c8-11e7-9f5a-161a428f95b7.png)

Now using this code with the Scijava kernel:

```
import com.twosigma.beakerx.mimetype.MIMEContainer;
fname = "/home/hadim/.doc/Code/Notebooks/Sandbox/Vega Plots/chart.vl.json"
fileContents = new File(fname).text
new MIMEContainer("application/vnd.vegalite.v1+json", fileContents)
```

![scijava](https://user-images.githubusercontent.com/528003/27840589-43534472-60c8-11e7-8281-a55ded940b99.png)

**Comment by hadim** [comment]
The later is a JSON string, it should be a JSON object.

**Comment by hadim** [comment]
I tried to have a look at the beakerx code to fix it but it didn't work. I think strings that represent JSON has to be serialized in a different way than regular string.

**Comment by scottdraves** [comment]
Thanks for the research, I see what you mean.  I can see two ways of fixing this:
* Since the mime type is custom it doesn't know if the value is string or json.
It would be easy enough to make a subclass or add a parameter.
* Leave it to the user to quote the string if they intend it to be a string, ie assume json.
Then they would say something like
```
new MIMEContainer('text/html', '"<h1> Hello World!</h1>"')
```
instead of currently
```
new MIMEContainer('text/html', '<h1> Hello World!</h1>')
```

Looking at https://github.com/ipython/ipython/blob/master/IPython/core/display.py
seems like there's a "raw" flag for this.

I will do a little more research.  Hadrien, in order to make sure we are doing this right can you tell us where to get a file with relevant json?  And is there a way to do this in classic jupyter instead of lab?

**Comment by ellisonbg** [comment]
I am having trouble finding the right code, but I don't think this is what the `raw` argument is for. I think we actually use a regular expression to see if `json` is in the MIME type. @rgbkrk or @minrk do you remember where the code is for handling JSON based MIME types?

**Comment by ellisonbg** [comment]
Here is the function in JupyterLab that checks this:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/coreutils/src/nbformat.ts#L116

**Comment by ellisonbg** [comment]
And the very bottom of this section of the documentation:

https://jupyter-client.readthedocs.io/en/latest/messaging.html#display-data

says "Changed in version 5.0: application/json data should be unpacked JSON data, not double-serialized as a JSON string."

**Comment by ellisonbg** [comment]
That should apply to any json based MIME type

**Comment by hadim** [comment]
Thanks @scottdraves for looking into that and thanks @ellisonbg for all your help.

I think the right way to detect if a string is JSON is to use the jupyterlab method and check the mimetype:

```
const jsonTest = /^application\/(.*?)+\+json$/;
```

Here is a Vega lite file that should render a plot: https://gist.github.com/hadim/e090611531721dba9448deedad9eb8bc . Note that you need to use the Vega Lite mimetype here and not the Vega one: `application/vnd.vegalite.v1+json`

At the moment you need to use the last `master` of Jupyter Lab but soon it will be shipped by default with the next release. Notebook support will come next.

**Comment by scottdraves** [comment]
OK can I see the Python/Altair example?

**Comment by hadim** [comment]
Here you have:

```python
from altair import Chart, load_dataset

# load data as a pandas DataFrame
cars = load_dataset('cars')

Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)

```

**Comment by hadim** [comment]
@scottdraves if you point me to the right direction I can make a PR.

**Comment by scottdraves** [comment]
i am on vacation, will look at this tomorrow.
i need to study the python code.

**Comment by rgbkrk** [comment]
As an aside, make sure to check out [vegas](https://github.com/vegas-viz/Vegas) for vega plotting from Scala. Still needs to adapt to the mimetype'd vega though.

**Comment by hadim** [comment]
Did you have time to have a look @scottdraves ?

**Comment by minrk** [comment]
To match what IPython does, it would look something like this (pseudocode):

```java
import com.twosigma.beakerx.mimetype.MIMEContainer;
fname = "/home/hadim/.doc/Code/Notebooks/Sandbox/Vega Plots/bar-chart.vg.json"
fileContents = new File(fname).text
parsedContents = json.parse(fileContents)
new MIMEContainer("application/vnd.vega.v2+json", parsedContents)
```

and then make sure that MIMEContainer handles passing a JSONable object around, not just strings. Where exactly you do the parsing of the file (e.g. inside MIMEContainer or outside) is up to you for what serves your users expectations best. In IPython, it's on the user because more often the data structure is produced in memory, rather than read directly from a file. So if the data happens to come from an already-json file, the user has to parse that out before passing it to IPython.

**Comment by scottdraves** [comment]
hi sorry i am really focused on just getting the first release out the door.
thank you for adding explanation, though I am not sure I understand, why isn't just a string OK?
I thought we just had to know when to quote it or not.

**Comment by minrk** [comment]
Sorry, it depends a bit on what you are asking. It's AOK if the *user API* accepts strings. What matters is the message that ultimately gets sent over the wire. Since messages themselves are JSON, JSON outputs (those that match `*+json`) should be included in the JSON structure, not double-serialized as JSON strings.

That is, a display_data message with JSON output should look like:

```python
"data": {
 "text/plain": "<some plain-text repr>",
 "application/vnd.vega.v2+json": {
  "vega": "stuff...",
 }
}
```

And *not* double-encode JSON outputs as JSON strings within JSON messages:

```python
"data": {
 "text/plain": "<some plain-text repr>",
 "application/vnd.vega.v2+json": "{\"vega\": \"stuff...\"}", # <- double-encoded JSON
}
```

Otherwise, handlers would need to double-parse JSON messages.

We can't automatically treat string values in JSON fields as serialized JSON, because JSON strings are also valid JSON values. If we allowed JSON to be double-serialized, there would be no way to tell if the string `"{}"` should actually be the string `"{}"` or the empty dict `{}`.

The benefit of JSON parsing is that when you are working with outputs, either in messages or in documents, you can address data directly without having to address the output, then parse, then address data. i.e. the following works:

    notebook.cells[0].outputs[0].data['application/vnd.vega.v2+json']['key']

and output data can be addressed with xpath-style matching in the notebook document, etc.

**Comment by scottdraves** [comment]
This is working on master, @hadim can you confirm this works for you?
<img width="508" alt="screen shot 2017-07-28 at 10 00 16 am" src="https://user-images.githubusercontent.com/963093/28720579-99c6e4e2-737b-11e7-8f4a-ad80da01d3fe.png">

**Comment by scottdraves** [comment]
Or does it have to be a String?

**Comment by hadim** [comment]
Thank you very much for adding this feature.

I think that would be nice to also be able to submit a string. If it's not too much work for you guys.

I'll test that soon.

**Comment by hadim** [comment]
It works very nicely!

I confirm that having a method signature that allows submitting the JSON as a string would be helpful. That would allow me to remove the `groovy-json` dependency that I use only for this.

**Comment by scottdraves** [comment]
cool, will continue on another issue.
