### ISSUE TITLE
plot legend can be cropped

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5606]
in the main plot in chartingTutorial.ipynb, the legend is not visible.
if you drag the chart to make it more narrow then it appears.

seems like the legend is not counted in the width calculation.  the whole plot should fit in the given width, including the legend.

**Comment by MariuszJurowicz** [comment]
@scottdraves i can't reproduce this issue. The plot legend is visible when set.

`EDIT`: I can see the problem in layout manager with grid.

**Comment by scottdraves** [comment]
Here is what I get if I just run the cell:
![screen shot 2017-07-17 at 8 54 29 am](https://user-images.githubusercontent.com/963093/28268805-a1a8bd68-6acd-11e7-8ef7-6ddf9830e9a3.png)

and then i use the thumb to drag to make it more narrow:

![screen shot 2017-07-17 at 8 55 31 am](https://user-images.githubusercontent.com/963093/28268820-baeab998-6acd-11e7-95e2-339a945f459e.png)
