### ISSUE TITLE
R should not be required to start a notebook

### ISSUE THREAD

**Issue by rgerkin** [twosigma/beakerx#561]
When I run the v0.55 build on a Mac, I get the error below.  This is probably related to the fact that I do not have R installed.  If it is not related to that, please advise.  Otherwise, I would suggest making Beaker runnable out of the box without requiring an installation of R.  

`Acknowledge R plugin started
Done starting R
R-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
R-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8803
R-stderr waiting over
R-stderr>[qtp151452127-16] WARN org.eclipse.jetty.servlet.ServletHandler - 
R-stderr>javax.servlet.ServletException: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
R-stderr>   at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420)
R-stderr>   at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
R-stderr>   at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
R-stderr>   at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
R-stderr>   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
R-stderr>   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
R-stderr>   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
R-stderr>   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
R-stderr>   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
R-stderr>   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
R-stderr>   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1465)
R-stderr>   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
R-stderr>   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
R-stderr>   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
R-stderr>   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
R-stderr>   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
R-stderr>   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
R-stderr>   at org.eclipse.jetty.server.Server.handle(Server.java:370)
R-stderr>   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
R-stderr>   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
R-stderr>   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
R-stderr>   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
R-stderr>   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
R-stderr>   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
R-stderr>   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
R-stderr>   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
R-stderr>   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
R-stderr>   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
R-stderr>   at java.lang.Thread.run(Thread.java:744)
R-stderr>Caused by: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
R-stderr>   at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
R-stderr>   at java.lang.Runtime.exec(Runtime.java:617)
R-stderr>   at java.lang.Runtime.exec(Runtime.java:528)
R-stderr>   at com.twosigma.beaker.r.rest.RShellRest.startRserve(RShellRest.java:113)
R-stderr>   at com.twosigma.beaker.r.rest.RShellRest.newEvaluator(RShellRest.java:245)
R-stderr>   at com.twosigma.beaker.r.rest.RShellRest.getShell(RShellRest.java:148)
R-stderr>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
R-stderr>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
R-stderr>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
R-stderr>   at java.lang.reflect.Method.invoke(Method.java:606)
R-stderr>   at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
R-stderr>   at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
R-stderr>   at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
R-stderr>   at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
R-stderr>   at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
R-stderr>   at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
R-stderr>   at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
R-stderr>   at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
R-stderr>   at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1511)
R-stderr>   at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1442)
R-stderr>   at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
R-stderr>   at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
R-stderr>   at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
R-stderr>   ... 28 more
R-stderr>Caused by: java.io.IOException: error=2, No such file or directory
R-stderr>   at java.lang.UNIXProcess.forkAndExec(Native Method)
R-stderr>   at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
R-stderr>   at java.lang.ProcessImpl.start(ProcessImpl.java:130)
R-stderr>   at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
R-stderr>   ... 50 more`

**Comment by scottdraves** [comment]
Thanks for the bug report.  Indeed this is a problem though it's not as bad as it looks, you can just ignore the error and the other languages should work fine.

If you want to avoid producing it at all (it is annoying), you can but it is a bit tricky.  What you want is to update your default notebook with one that doesn't have R in it.  The default notebook is stored in `~/.beaker/v1/config/default.bkr`.  Just make a notebook that looks like you want it, save it as a file, and then copy it to this location.

There is one problem though, and this is the tricky bit:  in addition to removing the R cell from the default notebook, you have to remove the plugin, and there is no UI for doing that.  This is a longstanding bug that will be fixed soon (https://github.com/twosigma/beaker-notebook/issues/77, https://github.com/twosigma/beaker-notebook/issues/469, https://github.com/twosigma/beaker-notebook/issues/513).

To remove it manually from the notebook, open the bkr file up in a text editor, and in the "evaluators" section, find and delete the following block:

```
    {
        "name": "R",
        "plugin": "R",
        "view": {
            "cm": {
                "mode": "r"
            }
        }
    },
```

That should do it -- if you have any trouble please don't hesitate to continue this thread.
