### ISSUE TITLE
merge new content into plot features demo

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5610]
update doc/contents/PlotFeatures.ipynb with new content from doc/contents/plotDemo.ipynb
and fix the rates table to be read from the csv like in doc/contents/chartingTutorial.ipynb

part of #5487

**Comment by samwincott** [comment]
Can I take this on? I'd love to contribute to the project.

**Comment by scottdraves** [comment]
sure, send us a completed CLA. i would be happy to describe the issue in more detail.

**Comment by samwincott** [comment]
Great, I'll fill one out now. I think I understand fixing the rates table, but may need more clarification on the first part.

**Comment by scottdraves** [comment]
that would be awesome thank you

**Comment by scottdraves** [comment]
note I will not be able to see the form or test your PR until Monday, but I can answer any questions you have here at any time.

**Comment by samwincott** [comment]
What new content was it that you wanted moved from plotDemo to plotFeatures?

**Comment by scottdraves** [comment]
the raster demos, anything else new

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by samwincott** [comment]
I have finalised the pull request (#5615) for this issue, and hope it was what you were looking for. I'm happy to change anything if needs be.

**Comment by scottdraves** [comment]
thanks will lool at it tomorrow
