### ISSUE TITLE
Small start tutorial and detailed roadmap is needed

### ISSUE THREAD

**Issue by torwag** [twosigma/beakerx#5614]
Coming from Jupyter, I tested beaker a few days ago, to notice that it seems in the middle of moving towards Jupyter.
I really liked the eye-candy and many functions of beaker and I hope they will appear soon in Jupyter.
Meanwhile I tried the plugin. It seems to work, but there seems to be not a single line of documentation how to start.
Even the screenshots are not reproducible as they require to use beakers auto-translate function but the corresponding beaker modules/classes/etc/ are not any longer imported automatically. 
Furthermore, I couldn't figure out what functions of beaker are already in beakerx and which are still missing. In a post you claimed beakers function will be ported by time but I did not find a roadmap to give me an idea whether this takes weeks, months or years. 
Furthermore, you claimed that some functions will be lost forever. Could you describe in detail what kind of functions will be lost?

A very first How-To for beakerx (beside the given install instructions) and a more detailed roadmap e.g. listing all features which will and which will not be ported, with a rough indication of the priority would be really appreciated.

**Comment by scottdraves** [comment]
hi thank you for your feedback. I totally agree. When I get back to my desk tomorrow I can provide some of this, and some of it is under development. it should all be in place by the time of our first release.

**Comment by scottdraves** [comment]
Here's our roadmap: https://github.com/twosigma/beakerx/wiki/Roadmap
mostly it's links to github milestones with the specific issues.

The start tutorial is just started here: https://github.com/twosigma/beakerx/blob/master/doc/StartHere.ipynb
it's under active development mostly getting all the demos we already have cleaned up and linked.

yea the screenshots are way out of date, see the autotranslation demo notebooks.

the documentation should be all set by the time we get to our first release.
