### ISSUE TITLE
Build instructions from ReadMe.md don't work on Windows

### ISSUE THREAD

**Issue by Jaykul** [twosigma/beakerx#5616]
1. The line `source activate beakerx` needs to be just `activate beakerx`

2. The line: `./gradlew --no-daemon :beakerx:install` has to be run as administrator in order to make symlinks...

3. The line `python -m beakerx.install --enable --prefix="${CONDA_PREFIX}"` would need to be `python -m beakerx.install --enable --prefix="%CONDA_PREFIX%"

**Comment by Jaykul** [comment]
Here's a PowerShell version that definitely works (assuming `conda` and `yarn` are pre-installed, _and that you're running elevated_):

```posh
conda create -y -n beakerx python=3.5 jupyter pandas
# activate beakerx # seems to work, but doesn't leave CONDA_PREFIX set
cmd.exe /c "activate beakerx && set > beaker.env"
gc .\beaker.env | ForEach { $name,$value = $_ -split "=",2; sc Env:$name $value }

conda install -y -c conda-forge openjdk
./gradlew --no-daemon build
./gradlew --no-daemon kernelInstall
./gradlew --no-daemon :beakerx:install 
cd beakerx
pip install -e .
python -m beakerx.install --enable --prefix="${CONDA_PREFIX}"
jupyter notebook
```

I think this works for DOS:

```dos
conda create -y -n beakerx python=3.5 jupyter pandas
activate beakerx
conda install -y -c conda-forge openjdk
./gradlew --no-daemon build
./gradlew --no-daemon kernelInstall
./gradlew --no-daemon :beakerx:install
cd beakerx
pip install -e .
python -m beakerx.install --enable --prefix="%CONDA_PREFIX%"
jupyter notebook
```

**Comment by altavir** [comment]
Here is the slightly modified version that allows to skip tests and not to reset gradle daemon each time:
```
conda create -y -n beakerx python=3.5 jupyter pandas
# activate beakerx # seems to work, but doesn't leave CONDA_PREFIX set
cmd.exe /c "activate beakerx && set > beaker.env"
gc .\beaker.env | ForEach { $name,$value = $_ -split "=",2; sc Env:$name $value }

conda install -y -c conda-forge openjdk
./gradlew --no-daemon build kernelInstall :beakerx:install -x test
cd beakerx
pip install -e .
python -m beakerx.install --enable --prefix="${CONDA_PREFIX}"
cd ..
#jupyter notebook
```
I've created a file named `install.ps1` and now can run it from installation directory. For now the only problem is that groovy kernel fails to build.

**Comment by altavir** [comment]
I've performed some additional searches. It seems to be this problem with changing environments: https://github.com/conda/conda/issues/1519

**Comment by Jaykul** [comment]
Yes @altavir, that's exactly it.

People need to _**stop** using cmd_ -- especially people who're trying to write cross-platform things.

I have Bash on Windows, and I even have PowerShell on Linux -- but CMD is dead to me 😉  I gave them a tip to do _roughly_ the same thing I showed above to slurp up the environment changes from the cmd process...

Fwiw, my groovy kernel works and everything. The only thing that made me sad was realizing that the `%%magic` commands wouldn't automatically pickup all my kernels and let me mix-and-match whatever I wanted 😖 

I'm working on a cross-platform [PowerShell kernel for Jupyter](https://github.com/Jaykul/Jupyter-PowerShell/), but I love the polyglot story of Beaker -- are there docs of how you implemented the communication? I mean, what would a Beaker-compatible kernel need to do beyond what Jupyter requires?

**Comment by altavir** [comment]
The same for me. I also have bash installed on windows, though I mostly use it for ssh only, since powershell is much more... well... powerful and concise (it also supports pretty large POSIX subset not to feel any difference). I want to use Powershell on Linux also, but I am waiting for a repository debian release.

**Comment by scottdraves** [comment]
Thanks for the report.  we are stuck with what conda does but we can make it correct and document the windows workarounds at least.

**Comment by pescadorbob** [comment]
> Here's a PowerShell version that definitely works (assuming `conda` and `yarn` are pre-installed, _and that you're running elevated_):
> 
> ```powershell
> conda create -y -n beakerx python=3.5 jupyter pandas
> # activate beakerx # seems to work, but doesn't leave CONDA_PREFIX set
> cmd.exe /c "activate beakerx && set > beaker.env"
> gc .\beaker.env | ForEach { $name,$value = $_ -split "=",2; sc Env:$name $value }
> 
> conda install -y -c conda-forge openjdk
> ./gradlew --no-daemon build
> ./gradlew --no-daemon kernelInstall
> ./gradlew --no-daemon :beakerx:install 
> cd beakerx
> pip install -e .
> python -m beakerx.install --enable --prefix="${CONDA_PREFIX}"
> jupyter notebook
> ```
> 
> I think this works for DOS:
> 
> ```
> conda create -y -n beakerx python=3.5 jupyter pandas
> activate beakerx
> conda install -y -c conda-forge openjdk
> ./gradlew --no-daemon build
> ./gradlew --no-daemon kernelInstall
> ./gradlew --no-daemon :beakerx:install
> cd beakerx
> pip install -e .
> python -m beakerx.install --enable --prefix="%CONDA_PREFIX%"
> jupyter notebook
> ```

I've tried this, but, the gradlew doesn't exist anywhere for me. Is it supposed to be executed from a particular directory or something? where are the build.gradle files we're hoping for?

**Comment by Jaykul** [comment]
[gradlew](https://github.com/twosigma/beakerx/blob/master/kernel/gradlew) is part of the source 😉
