### ISSUE TITLE
integer table column formats ignored

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5626]
![screen shot 2017-07-10 at 8 50 23 pm](https://user-images.githubusercontent.com/963093/28046416-7654baca-65b1-11e7-8a35-8bb60d60dc3a.png)

if you select formats from "datetime" to "milliseconds" they have no effect (the checkmark does not even move).

**Comment by scottdraves** [comment]
it looks like in classic beaker they are broken the same way.
what they should do is treat the integer as time, and display like a time column of the given time,
see the table API cell that calls
```
display.setStringFormatForTimes(TimeUnit.MINUTES)
```

**Comment by jszalek** [comment]
@scottdraves I changed data-time parsers for integers to parse it as unix timestamp (in seconds).
