### ISSUE TITLE
bad tooltip on easyform button

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5658]
1. open the EasyFormDemo.ipynb
2. run the 1st cell
3. hover over the button labeled "Go!"

result: a tooltip that says "null" appears
expected: no tooltip

**Comment by jszalek** [comment]
@jaroslawmalekcodete 
We need to change property 'tooltip' on backend to empty string.
Example from ipywidgets docs:
```
widgets.Button(
    description='Click me',
    disabled=False,
    button_style='', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Click me',
    icon='check'
)
```
