### ISSUE TITLE
modify python setup.py kernels command

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5663]
currently `python setup.py kernels` installs the kernelspecs, including expanding that `__PATH__` variable to point to the jars.  it works by calling the gradle task to do it.

we need to rewrite it in python, avoiding gradle.  

depends on https://github.com/twosigma/beakerx/issues/5662 

the `__PATH__` should get substituted with the classpath which has the jars of the base kernel, plus the jars of the kernel.  one of mine currently looks like:
```
{
  "argv": [
    "java", "-cp", "/Users/spot/src/beakerx/kernel/groovy/build/install/groovy/lib/*:/Users/spot/src/beakerx/kernel/base/build/baseLibs/*", "com.twosigma.beakerx.groovy.kernel.Groovy",  "{connection_file}"
  ],
  "display_name": "Groovy",
  "language": "groovy",
  "env": {
    "PS1": "groovy>"
  }
}
```
we need a similar result except the paths to the jars will be different.

**Comment by scottdraves** [comment]
part of https://github.com/twosigma/beakerx/issues/5134

**Comment by gnestor** [comment]
I have 2 commands:

```py
def install_kernel(kernelspec_path='', kernelspec_name=''):
    """Install a Jupyter kernelspec.
    
    Parameters
    ----------
    kernelspec_path: str
        The path to the kernel.json.
    kernelspec_name: str, optional
        The kernel ID name.
    """

    class InstallKernel(BaseCommand):
        description = 'nstall a Jupyter kernelspec'

        def run(self):
            name = ["--name", kernelspec_name] if kernelspec_name else []
            run(['jupyter', 'kernelspec', 'install', '--sys-prefix', '--replace', *name, kernelspec_path], cwd=path)

    return InstallKernel
    
def install_kernels(kernels_dir=''):
    """Install all kernels in a directory.
    
    Parameters
    ----------
    kernels_dir: str
        The path of a directory containing kernels.
    """

    class InstallKernels(BaseCommand):
        description = 'Install all kernels in a directory'

        def run(self):
            for dir, subdirs, files in os.walk(kernels_dir):
                if 'kernel.json' not in files:
                    continue
                install_kernel(pjoin(dir, 'kernel.json'))

    return InstallKernels

```

We can call `install_kernels(pjoin('beakerx', 'static', 'kernel'))` to walk the directory and call `install_kernel` on each `kernel.json`/.

I assume that https://github.com/twosigma/beakerx/issues/5662 will replace `__PATH__` with the classpath?

**Comment by scottdraves** [comment]
this command needs to replace the path. this command is what runs at install time and knows the path on the user's machine to the static directory.  it can't be done at dev time.

**Comment by gnestor** [comment]
Another thing: `python setup.py java` currently runs a `gradlew --no-daemon build`. Do we need to create a Python command/script for this?

**Comment by scottdraves** [comment]
no that's gotta be done with gradle.  gradle is fine for developers when the java is compiled.
