### ISSUE TITLE
Python Magic to run Groovy broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5677]
run groovyCellMagic.ipynb 
<img width="1050" alt="screen shot 2017-07-16 at 3 15 31 pm" src="https://user-images.githubusercontent.com/963093/28250569-afd0b894-6a39-11e7-817d-dbdab89ab9aa.png">

**Comment by rbidas** [comment]
I try run groovyCellMagic.ipynb and new notebook and result is the same
![load_groovy_magic](https://user-images.githubusercontent.com/5703222/29119726-9e37f562-7d07-11e7-8c71-006006393c83.png)
