### ISSUE TITLE
spinner should be bubbling beaker

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#570]
instead of or in addition to the usually arrows that go around, the bubbles in our beaker logo in the upper left should move up and pop, as of the substance were boiling/cooking.

**Comment by melmac48** [comment]
@bradicdesign this would be pretty cool

**Comment by bradicdesign** [comment]
Sounds cool. Let me think about this and some other related beaker analogies that could make a more interesting waiting / working animation.
