### ISSUE TITLE
remove tablesaw

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5702]
we are picking up some dependencies from tablesaw (like jackson).
so part of removing it is these explicit in our build.gradle files.

another part is making sure we keep the ability to read csv files.

users can load it with %classpath.  the only thing they lose is ability to auto display their tables with the UI. we can add that in later.

**Comment by scottdraves** [comment]
Joe Pallas @jpallas 20:00
FYI: All published spark 2.x versions seem to be using jackson-databind version 2.6.5.

**Comment by benmccann** [comment]
Jackson and numerous other dependencies been removed from tablesaw (in master. we still need to publish a new version to Maven Central)

When we publish a new version of tablesaw, would you want to try adding tablesaw back?

**Comment by scottdraves** [comment]
Even if all the dependency problems were fixed, It's quite large so It's better as an option that can be loaded by those who want it.

**Comment by benmccann** [comment]
Sure, makes sense.

I think it's not quite so large anymore though. We've been doing lots of work on slimming it down. We've removed lots of unnecessary dependencies and are modularizing the rest so that you can pull in just the parts that are relevant to you. Let me know if there's anything left that makes it feel heavyweight to you and I'll see if I can remove.

**Comment by scottdraves** [comment]
awesome.  my goal is to remove as much as possible from the core kernels and make everything a loadable module, so we have no plans to go back, but sounds like those changes will make it work better for those who choose to load it.

**Comment by benmccann** [comment]
One question for you. When we modularized it, we stopped building a shaded uber jar. Will that cause you problems? I'm guessing it'll need more `%classpath add` lines now. Potentially a good handful and users will have to figure out how to download all the dependencies transitively.

I'm not sure if you have this or not, but it'd be cool if you could say something like `%loadFromMaven com.github.lwhite1:tablesaw:0.8` and it would download the dependencies for you and include them. (If you need code to do this I have some [here](http://www.benmccann.com/using-an-ivy-resolver/))

**Comment by scottdraves** [comment]
yes we had an issue for that but it got lost in the shuffle when it was patly done. 
 made a new one for the remaining work: https://github.com/twosigma/beakerx/issues/5836

**Comment by scottdraves** [comment]
thx for the pointer that may well be useful i added it.
