### ISSUE TITLE
when stdout or stderr is disabled, the other one should fill the window

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#572]
![screen shot 2014-09-05 at 2 59 43 pm](https://cloud.githubusercontent.com/assets/963093/4170094/d9e0ef2a-352e-11e4-851c-6dbd7f02305c.png)

**Comment by scottdraves** [comment]
to avoid wrapping like this one does

**Comment by melmac48** [comment]
@scottdraves reassigning based on priority and Sam's availability at the moment
