### ISSUE TITLE
add dependencies to conda package

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5721]

**Comment by gnestor** [comment]
It does: https://github.com/twosigma/staged-recipes/blob/master/recipes/meta.yaml#L33

**Comment by scottdraves** [comment]
ok well somehow if you create an env without it, and install beakerx, it fails.
and then you install it and install beakerx and it works.

**Comment by gnestor** [comment]
Oh it looks like the README already instructs users to create an environment with jupyter: `conda create -y -n beakerx python=3.5 jupyter pandas`

**Comment by scottdraves** [comment]
the readme is for developers not users.

**Comment by scottdraves** [comment]
create a new section for users now that that is possible https://github.com/twosigma/beakerx/issues/5726

**Comment by scottdraves** [comment]
our readme says:
```
conda create -y -n beakerx python=3.5 jupyter openjdk pandas
source activate beakerx
conda install -y -c conda-forge ipywidgets=7.0.0 widgetsnbextension beakerx
```
but it should just be
```
conda install -c conda-forge beakerx
```

**Comment by scottdraves** [comment]
https://github.com/conda-forge/beakerx-feedstock/blob/master/recipe/meta.yaml#L23
