### ISSUE TITLE
support python 3.6

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5723]
i see python3.5 hardcoded in our setup.py

**Comment by scottdraves** [comment]
conda forge does this for users, might have to fix it for devs.
the more basic problem is we have duplication of effort between setup.py and beakerx-install.

**Comment by gnestor** [comment]
Feel free to create a new issue to clean up `setup.py` and `install.py` and assign Robert or I.

EDIT: You already did!
