### ISSUE TITLE
text arrow-heads lost on saved plot

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5731]
in the app:
<img width="161" alt="screen shot 2017-07-24 at 10 45 51 am" src="https://user-images.githubusercontent.com/963093/28529004-5253cf4c-705d-11e7-90ec-b4d305dd7914.png">
after right-click save-as
<img width="215" alt="screen shot 2017-07-24 at 10 45 42 am" src="https://user-images.githubusercontent.com/963093/28529005-5276a2f6-705d-11e7-99da-5b8768a8a1d3.png">
this is one of the cells in the catalog of plot features.

**Comment by MariuszJurowicz** [comment]
@scottdraves I can't reproduce this issue.
