### ISSUE TITLE
jars are always installed in environment instead of locally

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5739]
unlike the python and js, the jars are always installed in $env/lib/python3.5/site-packages/beakerx/static/kernel/....
this is a problem for developers who have to copy them after each build.

also the cmd we have to build is too long:
```
(cd beakerx; python setup.py install --single-version-externally-managed --record record.txt && python setup.py kernels)
```

**Comment by scottdraves** [comment]
fixed by https://github.com/twosigma/beakerx/pull/5797

**Comment by jpallas** [comment]
Should the readme be updated now?

**Comment by gnestor** [comment]
@jpallas Which part of the README specifically? Users should only need to do a `pip install beakerx` to install the kernels and Python library and `jupyter nbextension install beakerx --py --sys-prefix` to install the Javascript/notebook extension.

**Comment by scottdraves** [comment]
I think he means this line:

> Note this is currently broken and you need to do a complete rebuild after a java change. See #5739.

and the answer would be yes :) after i finish the release!
