### ISSUE TITLE
default notebook final fixes

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#574]
1) change the initial heading from "Hello Beaker" to "Hello Notebook"
2) on the control panel, change "new notebook" to "new default notebook" (2x)
3) add next to it a new button "new empty notebook", make it a secondary choice (off to the right, slightly smaller text), so people don't click on it by mistake (2x)
4) add a line of python code before the 1st "# This is a code cell."
5) On the control panel,  change the text to read "Click below to get started coding with Python, R, Julia, Groovy, JavaScript, and Ruby.<br>Beginners should check out the menu above, Help → Tutorial notebook" 
6) change the heavy triangles to → in the default notebook

**Comment by melmac48** [comment]
should ensure that file/new creates the more advanced notebook. New Users will typically start off on the control panel page and will see the basic notebook.
