### ISSUE TITLE
syntax highlighter does not understand magics

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5742]
<img width="610" alt="screen shot 2017-07-25 at 5 22 40 pm" src="https://user-images.githubusercontent.com/963093/28594433-f0ac2184-715d-11e7-846a-85b500ba3920.png">

**Comment by piorek** [comment]
Probably should be done with custom mode (http://marijnhaverbeke.nl/blog/codemirror-mode-system.html) 
will need a list of magics or some general rule how to distinguish them from the rest of the code

**Comment by scottdraves** [comment]
let's say any line that starts with a %
