### ISSUE TITLE
get rid of warnings from kotlin errors

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5746]
<img width="341" alt="screen shot 2017-07-26 at 8 44 11 am" src="https://user-images.githubusercontent.com/963093/28621364-b0609502-71de-11e7-9184-62afad1a4b98.png">

every kotlin error has these unrelated warnings

**Comment by michalgce** [comment]
@scottdraves is it still up to date cause i cannot reproduce it?
![image](https://user-images.githubusercontent.com/1582983/28708955-7a1da0ec-737e-11e7-80c5-b01c2eb84ef2.png)
