### ISSUE TITLE
Link to sample notebooks from README

### ISSUE THREAD

**Issue by shamiknm** [twosigma/beakerx#5756]
Linking to https://github.com/twosigma/beakerx/blob/master/doc/StartHere.ipynb in the README.md would be very helpful for new users. 

Also updating the [examples page](http://beakernotebook.com/examples) on the site to point to doc/StartHere.ipynb too (the current links are broken) would be great.

**Comment by scottdraves** [comment]
Good idea, thanks.

The website will be replaced when we first release BeakerX.
