### ISSUE TITLE
allow extra whitespace in magics

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5758]
```
%classpath  add  jar demoResources/demo.jar
```
this magic seems to do nothing (note the extra spaces).  it should work the same as one without extra spaces.

```
%import  com.twosigma.beakerx.widgets.integers.IntSlider
```
this magic crashes the kernel.   it should work the same as one without extra spaces.

the same goes for all magics.  whitespace should just be a separator.

**Comment by michalgce** [comment]
@scottdraves may we close it?
