### ISSUE TITLE
Autotranslation doesn't work on java

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#5768]
We can see this on javaTutorial.ipynb notebook.

![image](https://user-images.githubusercontent.com/17744188/28816744-8eb2204a-76ae-11e7-85d9-3c0db3c7ee05.png)

**Comment by scottdraves** [comment]
thx.  this is dup of https://github.com/twosigma/beakerx/issues/5487 and https://github.com/twosigma/beakerx/issues/5039
