### ISSUE TITLE
fix our jitpack build

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5792]
https://jitpack.io/#twosigma/beakerx

it's red.  @hadim i thought you said it was working for you.  am i missing something?

**Comment by hadim** [comment]
It's working when using commits more recent than my last PR that fix the build. Look under the "Build" tab on jitpack. The last commit is green. It will be the case with the next release (if the build system does not change).

Jitpack only builds a commit when at least one request is made on it. So the first person making the request will have to wait for few minutes for the build to be built. Then the build is cached.
