### ISSUE TITLE
Python plots won't work with pandas Series

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5799]
Just tried to use python version of beakerx plots.
I have pandas object `data`. This code does not work and throws some bizarre python "not implemented" exception (I am not very familiar with python) :
```python
plot = Plot()
plot.add(Line(x = data.Uset, y = data.CR))
```
On the other hand this code works just fine:
```python
plot = Plot()
plot.add(Line(x = data.Uset.tolist(), y = data.CR.tolist()))
```
The python plots example looks confusing, there is a pandas file read, but it is not used anywhere.
Also I have not found python to groovy autotranslation example, is it working yet?

**Comment by scottdraves** [comment]
Hi thanks for the report, we will look at making the Python API for plots work better with Pandas after our release.

Autotranslation is only working to JavaScript so far: https://github.com/twosigma/beakerx/issues/5039
