### ISSUE TITLE
Unable to load evaluators on Mac

### ISSUE THREAD

**Issue by rgerkin** [twosigma/beakerx#581]
The evaluators never load in a fresh installation of Beaker on OS X 10.9.4.  Here is the Chrome developer tools debug info:  

```
isNewSession? Object {isNewSession: function} mainapp.js:575
Using ipython 1.x compatibility mode: false ipython.js:318

POST http://127.0.0.1:8801/ipython.450339346309/login?next=%2Fbeaker 502 (Bad Gateway) angular.js:7962
(anonymous function) angular.js:7962
sendReq angular.js:7794
$http.serverRequest angular.js:7528
wrappedCallback angular.js:10905
wrappedCallback angular.js:10905
(anonymous function) angular.js:10991
Scope.$eval angular.js:11906
Scope.$digest angular.js:11734
Scope.$apply angular.js:12012
done angular.js:7818
completeRequest angular.js:7991
xhr.onreadystatechange angular.js:7947

TIMED OUT - waiting for ipython kernel to start ipython.js:111
spin ipython.js:111
3Uncaught TypeError: Cannot read property 'execute' of undefined ipython.js:99
(anonymous function) ipython.js:99
```

Note also that I've taken out R as per #561, but if I don't do that I get the same issue, except with messages for both R and IPython instead of just IPython, and in that case I also get the R error web console output I described in #561.  IPython works fine in a terminal.

**Comment by scottdraves** [comment]
What version of Beaker is this? How did you install IPython?
What happens if you run the command on the terminal "ipython notebook"?
In the tutorial notebook, do the Groovy cells run?

Are you running Beaker with the native app?  If so, run the Console app and search for "Beaker" in the logs.  What do you get there?

**Comment by rgerkin** [comment]
Solved by re-installing Tornado.  I am assuming there was an IPython error behind the scenes... it might be helpful if that error was visible in the web console.
