### ISSUE TITLE
extension building or loading broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5812]
<img width="510" alt="screen shot 2017-08-08 at 11 48 04 pm" src="https://user-images.githubusercontent.com/963093/29104527-27b5e264-7c94-11e7-9415-3e63ad5a86dc.png">
<img width="579" alt="screen shot 2017-08-08 at 11 46 38 pm" src="https://user-images.githubusercontent.com/963093/29104526-27ab29d2-7c94-11e7-9766-4fb1f10e506f.png">

**Comment by MariuszJurowicz** [comment]
@scottdraves 
If you are installing the beakerx as `Developer Install` the `beakerx` extension is not installed in jupyter.
You need to manually run the:
```
jupyter nbextension install beakerx --py --sys-prefix
jupyter nbextension enable beakerx --py --sys-prefix
``` 
after the `Developer Install` steps, to install and enable the extension.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/commit/25934940adf4dcf6040a3761a0ac38b998dc8bb5
