### ISSUE TITLE
publish notebooks to gist

### ISSUE THREAD

**Issue by LeeTZ** [twosigma/beakerx#5817]
Add a menu item in Files to publish the current notebook as gist.
A GitHub personal access token may be needed.
In the open dialog user may specify the filename to publish. If the notebook is already published, user may overwrite it, or make a new copy.
Publishing information should be saved in notebook metadata for further use. (e.g. manage, or search in my published notebooks etc.)
After publishing, open up a window with nbviewer on this gist.

**Comment by scottdraves** [comment]
For our initial feature, let's keep it simple:
1) skip github accounts, just make an anonymous gist
2) no dialog is required, since gist has no metadata
3) no need to save metadata in the notebook since there isn't any
