### ISSUE TITLE
tip gets stuck

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5826]
same setup as https://github.com/twosigma/beakerx/issues/5825

sometimes the tip gets stuck on the screen.  i am not talking about the "pin" feature.
without clicking, moving the mouse and zooming in and out over these lines and labels,
eventually a tip gets stuck up, even when i move the mouse away.  the tip remains up
until the mouse crosses over the line again, and the tip reappears in the new location.

**Comment by MariuszJurowicz** [comment]
@scottdraves can you check if it still occurs? I can't reproduce this bug. I think it was fixed in the https://github.com/twosigma/beakerx/pull/6006
