### ISSUE TITLE
document column size limit

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5829]
big_table_test.ipynb

document that cells that are more than 1000 chars wide get truncated with ...

show a table with a column of really long strings that gets truncated like this, and explain it.

https://github.com/twosigma/beakerx/blob/e9b2e94800e504cd7c34e29a9fe0815d47db6966/beakerx/js/src/tableDisplay/tableScope.js#L2302

**Comment by jmsdnns** [comment]
What path would you like for the doc?

**Comment by scottdraves** [comment]
put it in here:
https://github.com/twosigma/beakerx/blob/master/doc/groovy/big_table_test.ipynb

**Comment by jmsdnns** [comment]
Done. PR coming up.
