### ISSUE TITLE
allow loading from mvn with dependencies

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5836]
finish the design from https://github.com/twosigma/beakerx/issues/5434, in particular
```
%classpath add mvn org artifact version
```

**Comment by scottdraves** [comment]
maybe useful: http://www.benmccann.com/using-an-ivy-resolver/

**Comment by benmccann** [comment]
I've been thinking about this more. I'm not sure that the `%classpath add mvn org artifact version` syntax will really work. Normally when you resolve the dependencies in a pom.xml, you're resolving all the dependencies for the whole project at once. That allows the resolver to do things like evict older versions of a library for newer versions when multiple versions are pulled in transitively. I'm not quite sure how that would work with `%classpath add mvn org artifact version`. Also, a pom.xml will let you do things like exclude conflicting dependencies, which you wouldn't be able to do with `%classpath add mvn org artifact version`

I'm not quite sure what the solution is here. Could we point beaker at a pom.xml and then invoke Maven on it?

**Comment by jpallas** [comment]
The [ammonite REPL](http://ammonite.io) for Scala uses Ivy for dynamic resolution, and it seems to manage okay without doing anything special to deal with multiple versions.  On the other hand, the fork used by jupyter-scala, [ammonium](https://github.com/jupyter-scala/ammonium), adds support for exclusions, but that doesn't seem like it addresses version conflicts.  Maybe it can be used to manually deal with conflicts?  I guess the point is that ammonite and jupyter-scala don't directly address the problem but they seem to be useful anyway.

**Comment by benmccann** [comment]
Interesting. Actually, it ammonite.io says is supports exclusions if you call `interp.load.ivy`. It looks like they use [coursier](https://github.com/coursier/coursier): https://github.com/lihaoyi/Ammonite/commit/662859f84f5a77efca3e7e4d3074626570a992cf  This seems like a great example to follow. We should probably do whatever they do

**Comment by scottdraves** [comment]
Thank you both very much your your analysis and links.  I agree we should stick to pre-existing techniques and guaranteed correctness, while desirable isn't a requirement.  It sounds like you both know more about it than I do and I look forward to your continued input as we implement this.  I think it's going to be a couple of weeks before we get to it, but we can continue planning and research during that time.  In particular I would like our design to work for all our languages, though certainly there might be some specialization for scala and clojure.

**Comment by jpallas** [comment]
`coursier` seems to be very complete, but the API is not designed with non-Scala clients in mind.  That may not be fatal, but the dependency on Scala libraries and runtime might be; it would pull them into all the JVM kernels.

I've found examples of Java code that uses Ivy directly ([StackOverflow](https://stackoverflow.com/a/22455451/3851755), https://makandracards.com/evgeny-goldin/5817-calling-ivy-from-groovy-or-java).  For whatever reason, there don't seem to be readily findable examples of code calling into Maven directly—they all defer to the obsolete Eclipse Aether library.  Perhaps the Maven APIs are just very awkward to use directly?  (On further investigation, Aether has apparently become the `maven-resolver` library.  So, it's not dead, it's been absorbed.)

I definitely agree with Scott's final point: the core mechanism should work with any JVM kernel.  Scala (or, more specifically, SBT and coursier) has a convention for dealing with its ABI instability across minor versions, and it would be nice to support that if it's convenient, but in the worst case manually tacking the Scala version onto the artifact name is sufficient.

**Comment by altavir** [comment]
Ivy can work with maven repositories, but I think it needs some additional configuration to do so. Groovy has [`Grapes`](http://docs.groovy-lang.org/latest/html/documentation/grape.html), which is essentially what you need, but I am not sure it could be disentangled from Groovy itself.

**Comment by benmccann** [comment]
You can easily use Ivy directly. See the link to my blog above that Scott posted

**Comment by jpallas** [comment]
Looks like [the bulk of the Grape implementation](https://github.com/apache/groovy/blob/master/src/main/groovy/grape/GrapeIvy.groovy) is itself written in Groovy.  So, not useful directly, although maybe as a model for calling Ivy.

**Comment by altavir** [comment]
I just tried to use `Grape` itself in groovy kernel and it does not work which is strange.
This code:
```groovy
// https://mvnrepository.com/artifact/commons-io/commons-io
@Grapes(
    @Grab(group='commons-io', module='commons-io', version='2.5')
)
import org.apache.commons.io.Charsets
println Charsets.US_ASCII 
```
produces an error:
```
java.lang.NoClassDefFoundError: org/apache/ivy/core/report/ResolveReport
	at com.twosigma.beakerx.groovy.evaluator.GroovyEvaluator$workerThread$MyRunnable.run(GroovyEvaluator.java:461)
```

It worked in the old beaker.

**Comment by jpallas** [comment]
I don't know much about the old beaker, so I couldn't say why Grape worked in it.  The BeakerX Groovy kernel is built using the `groovy-all` artifact, which has Ivy marked as an optional dependency, and the current kernel build does not explicitly add an Ivy dependency.  So the failure above would be expected.

**Comment by altavir** [comment]
Then it is probably good idea to add it at least until appropriate magic will work (it probably will depend on Ivy anyway). Ability to load remote artifacts is very important for java-based kernels, since java does not have local managed environment like python (and in my opinion it is very good).

I also remember that there was a problem of imports consistency across cells because each cell was considered a separate script.

**UPDATE** OK, problem with imports is solved with `%import` magic. Good to know!

**Comment by scottdraves** [comment]
Thanks altavir I filed another issue about fixing Grape, as you note it was fine in classic Beaker and it should work in BeakerX.  Thanks thanks Joe for suggesting a fix!

**Comment by benmccann** [comment]
That's awesome!! I'm very excited about this!

Any thoughts on when a release containing this feature might go out or what version it will be in?

**Comment by scottdraves** [comment]
thanks :) should go out at the beginning of next week in 0.3
