### ISSUE TITLE
failure installing beakerx via conda channel

### ISSUE THREAD

**Issue by tnn1t1s** [twosigma/beakerx#5838]
conda install -c beakerx beakerx

... 

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'beakerx::beakerx-0.1.0.dev0-py35h5a3ff1a_0'.
LinkError: post-link script failed for package beakerx::beakerx-0.1.0.dev0-py35h5a3ff1a_0
running your command again with `-v` will provide additional information
location of failed script: /Users/user/anaconda3/envs/openai/bin/.beakerx-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

LinkError: post-link script failed for package beakerx::beakerx-0.1.0.dev0-py35h5a3ff1a_0
running your command again with `-v` will provide additional information
location of failed script: /Users/user/anaconda3/envs/openai/bin/.beakerx-post-link.sh
==> script messages <==
<None>

**Comment by scottdraves** [comment]
hi, sorry i missed this before.
we are supporting pip until we figure out conda.  
dup of https://github.com/twosigma/beakerx/issues/5720
