### ISSUE TITLE
Magic to list classpath.

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5846]
If I understand correctly, `%classpath` should do that, but it does not (does nothing in fact).

I found the code to list classpath [here](https://www.mkyong.com/java/how-to-print-out-the-current-project-classpath/). System class loader should probably be replaced by thread class loader.

**Comment by scottdraves** [comment]
It is intended to only list the jars added to the classpath by the user, not the jars used internally by the kernel.

**Comment by altavir** [comment]
OK, it is reasonable. User can still list all jars by hand, or you can add something like `%classpath all` for that.

By the way, there are both `groovy` and `groovy-all` on a classpath. I believe that `groovy-all` includes `groovy`. In theory it could cause version clashes.

**Comment by scottdraves** [comment]
thx.  the groovy.jar on the classpath is our kernel, not a dependency.
