### ISSUE TITLE
html/ipynb link in tutorial broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#585]
i get an error box with this string:
    ipynb:/http://atwallab.cshl.edu/teaching/QBbootcamp3.ipynb was not found

**Comment by anglee** [comment]
it needs to be updated to use the new URL scheme
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/beaker.js#L216
something like:
http://127.0.0.1:8801/beaker/#/open?uri=http://atwallab.cshl.edu/teaching/QBbootcamp3.ipynb&format=ipynb

**Comment by melmac48** [comment]
should document link format

**Comment by anglee** [comment]
couldn't find links to 'ipynb' files as tutorials have been updated. If this is still happening, please reopen and list the occurrences.

**Comment by anglee** [comment]
link format: https://github.com/twosigma/beaker-notebook/wiki/open-url-scheme

**Comment by scottdraves** [comment]
thanks for the doc.
i removed the link because even when it was fixed, the import was still broken
https://github.com/twosigma/beaker-notebook/issues/592
we need to at least assess how broken -- is it for all imports?
