### ISSUE TITLE
in advanced mode, html output top margin too small

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#586]
![screen shot 2014-09-07 at 4 58 56 pm](https://cloud.githubusercontent.com/assets/963093/4179702/26490f06-36d2-11e4-883b-348fb94cc2cd.png)

should be about the same as left margin.

**Comment by melmac48** [comment]
P2

**Comment by scottdraves** [comment]
![screen shot 2014-09-12 at 6 01 21 pm](https://cloud.githubusercontent.com/assets/963093/4257804/62970202-3ac8-11e4-91d5-540ad7522d4a.png)

**Comment by samccone** [comment]
ok checkout master now, it is fixed

**Comment by scottdraves** [comment]
xlnt
