### ISSUE TITLE
Feature request priority (for education purposes)

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5866]
Now that installation is finally working, I would like to make a list of feature priorities (at least for my education purposes). I hope you will find it helpful.

1. Saving plots in notebooks (I believe it is this one: #5541 ). This feature is really needed if one wants to save notebooks as exercise material for students.
2. Loading artifacts from maven/ivy. #5836 . Definitely needed to fast load remote libraries. Creating uberjars for everything is a headache.
3. Direct autotranslation between Python and JVM( #5039 ). Need it for people accustomed with python to move to beakerx. Also python still has a lot more visualization capabilities. Sometimes it is convenient to use it.
4. Modularization. Can't find issue for that, but it was discussed that kernels should be installed one-by one, not all together. It is just not very pretty to have all the kernels (including SQL) when you do not need them. Distribution size is not of great importance, but still it would look better to have 15 Mb distribution instead of 70+Mb.
5. GUI panel for beakerx configuration. I am aiming for students who do not have programming experience, so it us much easier for them to work with gui.

I myself will try (as far as my schedule allows) to work on groovy and/or kotlin utility libraries to simplify math operations using my [already written code](https://bitbucket.org/Altavir/dataforge/src/47ba608314f43ee62c7779b2661ea74dd1901125/grind/groovymath/?at=default).

**Comment by scottdraves** [comment]
Thank you altavir, this kind of feedback is very useful.
1. ~~I just merged the fix (#5481), though~~ I am seeing a bug where reconstituted widgets are appearing twice.
2. ~~This should happen soon (1-2) weeks.~~
3. This is closer to 1-2 months away.
4. More like 2-3 months (#5688)
5. Not sure what you mean in this case, possibly https://github.com/twosigma/beakerx/issues/5678?

**Comment by scottdraves** [comment]
PS. please share your math graphing libs if you can!

**Comment by altavir** [comment]
I currently do not have JS-based graphing. I intended to use beakerx backend for that. I use JFreeChart based plots via JavaFX, so it probably could be started from groovy notebook, but I am not sure there are any reasons to have non-JS-based graphing in the notebook. 
What I am talking about is some libraries to work with TableDisplay and other utilities like plotting functions with beakerx API.

>Not sure what you mean in this case, possibly #5678?

Yes. It is the one.
