### ISSUE TITLE
<strong> not strong enough

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#588]
with the font settings in the new ui, the strong tag hardly makes any difference.
![screen shot 2014-09-08 at 1 01 29 pm](https://cloud.githubusercontent.com/assets/963093/4189198/dd86c24c-3779-11e4-8c31-c3208373bde5.png)
the words "New Notebook" are supposed to be bold but it is pretty much invisible to me.
if you zoom it way up, you can see there is a small difference but it is not enough.

**Comment by melmac48** [comment]
P2
