### ISSUE TITLE
scala should auto-display tables the same as groovy

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5895]
![screen shot 2017-08-30 at 11 36 42 am](https://user-images.githubusercontent.com/963093/29881086-8cf8a028-8d77-11e7-9b71-0fc5d153884a.png)

**Comment by jpallas** [comment]
I've been playing with using the jvm-repr stuff to make Scala `Map`s display as tables the way Java's do.  I added an override of `configJvmRepr` and did this:
```
    Displayers.register(AbstractMap.class, new Displayer<AbstractMap>() {
      @Override
      public Map<String, String> display(AbstractMap abstractMap) {
        TableDisplay td = new TableDisplay(abstractMap);
        td.display();
        HashMap<String, String> displayMap = new HashMap<>();
        displayMap.put(MIMEContainer.MIME.HIDDEN, "");
        return displayMap;
      }
    });
```

I'm not sure if this is the best or right way to do it, but the same approach should work with the Scala `TableDisplay` class.
