### ISSUE TITLE
Standardize example naming

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#5897]
https://github.com/twosigma/beakerx/tree/master/doc/contents

Some are capitalized. Some are lowercase
Some use underscores. Some use camel case

It would be nice to standardize. E.g. right now the two tablesaw examples aren't next to each other because they start with different case letters

**Comment by scottdraves** [comment]
agreed.  and subdirs for each kernel.
some are defunct/redundant and should be deleted.

**Comment by benmccann** [comment]
When you say "for each kernel" is that essentially the same as each programming language? E.g. maybe we'd have a `java` subdirectory containing `javaTutorial.ipynb`, `tablesawDemo.ipynb`, etc.

**Comment by scottdraves** [comment]
right, a subdir for java, a subdir for scala, a subdir for groovy, etc.

tablesawDemo.ipynb is groovy though.

**Comment by scottdraves** [comment]
dup of https://github.com/twosigma/beakerx/issues/6369
