### ISSUE TITLE
Notebook validation failed - updateData

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#5919]
I'm seeing this message
```
Notebook validation failed: {'updateData': {'stringFormatForTimes': 'HOURS'}} is not valid under any of the given schemas:
{
 "updateData": {
  "stringFormatForTimes": "HOURS"
 }
}
```
running the `tableApi` notebook.  (First saw it on the Scala version, but the Groovy one has the same behavior.)  It happens some time after cell 3 is executed, apparently when there is an autosave.

**Comment by scottdraves** [comment]
https://github.com/jupyter-widgets/ipywidgets/issues/1305
maybe related or similar?

**Comment by jaroslawmalekcodete** [comment]
I think the problem is related with sending display_data msg instead of comm_msg, I'm working on it.

**Comment by scottdraves** [comment]
thanks joe!
