### ISSUE TITLE
Plot export error - Entity 'nbsp' not defined

### ISSUE THREAD

**Issue by jszalek** [twosigma/beakerx#5943]
Example:
```
Random random = new Random();
data1 = [];
data2 = [];

(1..10000).each {
  data1 << random.nextGaussian();
  data2 << 2*random.nextGaussian() + 1.0;
}

new Histogram(data: data1, binCount: 25);
```
When I export this plot as svg, the svg file contains an error - Entity 'nbsp' not defined.
I can save .svg file but it is not correct. There is screenshot of the svg file opened in browsers:
Chrome:
![image](https://user-images.githubusercontent.com/6450797/30171856-5bc68326-93f3-11e7-87f8-de996ccce9a2.png)
Firefox:
![image](https://user-images.githubusercontent.com/6450797/30171905-7d27c4e4-93f3-11e7-9d71-1d6af8b9e51c.png)

When this error occurs exporting as png doesn't work.

This bug affects only a few examples. For example this presented below works well:
```
Random random = new Random();
data1 = [];
data2 = [];

(1..10000).each {
  data1 << random.nextGaussian();
  data2 << 2*random.nextGaussian() + 1.0;
}

new Histogram(initWidth:800, initHeight:200,
              title:"Wide Histogram with Manual Parameters",
              xLabel:"Size",
              yLabel:"Count",
              rangeMin: -8, 
              rangeMax: 8, 
              data: data1 + [7]*200,
              binCount: 99, 
              color: new Color(0, 154, 166));
```

**Comment by scottdraves** [comment]
thx -- i can't reproduce though.  maybe related to locale?

**Comment by scottdraves** [comment]
OK I got the SVG from kuba and it contains:
```
<text>1&nbsp;000</text>
```
so he has a locale that is formatting numbers with this nbsp.  possible solutions:
replace nbsp with `&#160;` or " " (since we don't care about breaking).
