### ISSUE TITLE
Kotlin cell does not return a result

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5958]
For a simple cell like
```kotlin
val a = 2.2
val b = 14

val f = {x: Double -> a*x + b}

println(f(2.0))
f(2.0)
```
println works fine, but the result in the output field is null.

**Comment by scottdraves** [comment]
thx yup, even simpler:
![screen shot 2017-09-11 at 10 44 31 am](https://user-images.githubusercontent.com/963093/30280619-3795a2c8-96de-11e7-894f-00bf91737e62.png)

**Comment by scottdraves** [comment]
like java, kotlin requires "return" to get the value from the cell.

**Comment by altavir** [comment]
Kotlin requires return from methods but for lambdas it works like Groovy. So it is probably could be managed in some way. I will look into it some time later. Sadly ma schedule is full for next two weeks.

**Comment by scottdraves** [comment]
that's a good point.  we are constructing a function with the cell contents to run it:
https://github.com/twosigma/beakerx/blob/ae3ddcc0d91af1adb1727a979ddae0cfbb9d2754/kernel/kotlin/src/main/java/com/twosigma/beakerx/kotlin/evaluator/KotlinWorkerThread.java#L110
maybe we could construct a lambda instead.
