### ISSUE TITLE
When the cell returns `null` it should not be rendered

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5962]
It looks ugly if some custom output is used in the cell, this null pops up after it.

**Comment by scottdraves** [comment]
does this API address this issue? https://github.com/twosigma/beakerx/blob/73ac34418eeed06df280b774dc51d44857dd5730/doc/contents/showNullExecutionResult.ipynb

**Comment by altavir** [comment]
Thanks, it does indeed. Though I believe it should be false by default.

**Comment by scottdraves** [comment]
There is disagreement about which is better.  While our API allows switching, if you are someone who wants to always turn off showing "null" it is annoying to switch in every notebook.  Maybe there's a good way to make it a more permanent switch...
