### ISSUE TITLE
widgets no longer publishable

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5970]
if you publish a notebook to github gist, the nbviewer page that opens up should show interactive widgets.  it does not.  probably just need to release new version of embedded widgets to npm.

**Comment by scottdraves** [comment]
https://nbviewer.jupyter.org/gist/anonymous/0bb7c0ff960dafb921a71176a6c617bd
still not working after updating npmjs (https://www.npmjs.com/package/beakerx)

**Comment by scottdraves** [comment]
still not working https://nbviewer.jupyter.org/gist/anonymous/eb5040ec12883049ad5b7969723512b0

**Comment by scottdraves** [comment]
i did an explicit "save with widget state" and got a different result, this one at least tries to load a module: https://nbviewer.jupyter.org/gist/anonymous/b43640b4afac176add81476d871c9830 it has a JS console error.

**Comment by MariuszJurowicz** [comment]
The problem is that it tries to load the version `1.0.0` of beakerx while the latest one is the `https://unpkg.com/beakerx@0.0.8/dist/index.js` (`0.0.8`)
