### ISSUE TITLE
not working features for IntSlider and IntProgress widgets

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#5980]
We can see that in JavaWidgets.ipynb notebook.
For com.twosigma.beakerx.widgets.integers.`IntSlider` doesn't work the properties:
- slider_color
- visible
![image](https://user-images.githubusercontent.com/17744188/30583825-b59f5d5a-9d30-11e7-96f2-cd869a715af7.png)

For com.twosigma.beakerx.widgets.integers.`IntProgress` doesn't work the properties:
- visible
- disabled 
![image](https://user-images.githubusercontent.com/17744188/30583994-1b513060-9d31-11e7-9a28-e3a7cb6cc47d.png)

**Comment by michalgce** [comment]
@scottdraves @EfimovVladimir 
Ad. 1
* slider_color is deprecated to change handle color you have to use 
```
w.style.handle_color = 'lightgreen'
```

to change visibility you have to use 
```
invisibleSlider.layout.visibility = "hidden"
```

Ad. 2
Properties disabled block of interaction with user, im not sure how it should works with Progressbar @mjurowicz-xsolve could you verify this one?
