### ISSUE TITLE
The value doesn't interact with UI of RadioButtons widget.

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#5982]
We can see this on JavaWidgets.ipynb notebook 

The selected value is not showed :
- when we create com.twosigma.beakerx.widgets.selections.`RadioButtons` 
- when we set value 
      
![image](https://user-images.githubusercontent.com/17744188/30583565-11ca964a-9d30-11e7-8051-76d53a461d73.png)

Also we can select some option manually and this doesn't change ```value``` property of widget.

**Comment by michalgce** [comment]
It's look like we're updating value after setup but there are missing some frontend action @mjurowicz-xsolve please take a look on this
