### ISSUE TITLE
plotting API requires import

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#600]
![screen shot 2014-09-09 at 7 55 44 pm](https://cloud.githubusercontent.com/assets/963093/4210897/6ad4f9c6-387d-11e4-99cd-4b3ab9e49309.png)

**Comment by anglee** [comment]
The prerequisite of this is the Groovy plugin needs to support set Imports.

**Comment by scottdraves** [comment]
depends on https://github.com/twosigma/beaker-notebook/issues/627
