### ISSUE TITLE
depend on ipywidgets v7

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6024]
this didn't work https://github.com/conda-forge/beakerx-feedstock/pull/2

**Comment by altavir** [comment]
I think the same problem with numpy. It should be installed by default in conda, but probably something was broken in my installation, so first time it failed with exception about unresolved numpy dependency. After I manually installed it, everything works fine.

**Comment by scottdraves** [comment]
Not sure what you mean.  How did you create your env, and how did you install BeakerX, and then what error did you get?

**Comment by altavir** [comment]
I did not use any environment, just root anacodna installation. Tried to install via `conda install -c conda-forge ipywidgets beakerx`. And got error about unsatisfied dependency on `numpy`. After I've installed numpy manually, everything is fine.
