### ISSUE TITLE
Error restoring widget state after shutdown

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#6035]
If I save a notebook with tables and/or plots, shut it down and then open it again, I get
```
Error rendering Jupyter widget. Widget not found: {"model_id":"a05785fb-34a8-4d81-a972-8f5d2974026a","version_major":2,"version_minor":0}
```
for each cell result where I expect a plot or table to be.

I've made a clean install with Anaconda 5.

UPDATE: If I explicitly save widget state before exit, everything works fine. Is it intended this way?

**Comment by scottdraves** [comment]
Yes, "save with widget state" is annoying requirement of jupyter.
