### ISSUE TITLE
Beaker 1.7.1 not initializing in Windows 10

### ISSUE THREAD

**Issue by isaac2lord** [twosigma/beakerx#6083]
Here is what I get when running beaker.command:

![image](https://user-images.githubusercontent.com/7535009/31196422-b63f8e14-a91b-11e7-96fc-74f477da12d7.png)

Bunches of lines saying `ERROR setting file permissions: file system does not support the PosixFileAttributeView`.

Please advise!

**Comment by scottdraves** [comment]
Sorry it doesn't work for you, but we are unable to debug it since we have moved on to developing BeakerX (see http://BeakerX.com) which solves many problems like this, and is the replacement for Beaker Notebook.
