### ISSUE TITLE
Standalone plots and tables?

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#6107]
Is it possible to plots front-end without jupyter? 
What I want to do is to create a JavaFX webview container to use beaker plots and tables without web browser. 
In case it is possible, I  am quite familiar with JavaFX, but I have no experience with front end development, so I would appreciate an html template for standalone plot container and instructions about how to being together javascript part.

Of course, I will share the results if it would work out.

**Comment by scottdraves** [comment]
Yes we have an NPM package that you can load like any JS library: https://www.npmjs.com/package/beakerx
This has embedded version of the widgets that work without jupyter.
This is used by nbviewer, if you want an example.
Here is the doc: http://ipywidgets.readthedocs.io/en/stable/embedding.html

**Comment by altavir** [comment]
Super! Thank you very much. I will try to implement this standalone viewer thing. Probably it will be possible to run groovy scripts saved from jupyter in it.
