### ISSUE TITLE
beakerx.showProgressUpdate() from background thread

### ISSUE THREAD

**Issue by joewalnes** [twosigma/beakerx#6110]
When calling `beakerx.showProgressUpdate()` from a background thread, a NullPointerException is raised.

Cause is `SimpleEvaluationObject` being looked up using a `ThreadLocal`:
https://github.com/twosigma/beakerx/blob/de1aee046a6a7ccb7064b418f56730b11ed11c35/kernel/base/src/main/java/com/twosigma/beakerx/NamespaceClient.java#L58-L61
https://github.com/twosigma/beakerx/blob/de1aee046a6a7ccb7064b418f56730b11ed11c35/kernel/base/src/main/java/com/twosigma/beakerx/evaluator/InternalVariable.java#L34

Being able to call `showProgressUpdate()` from other threads is very useful in notebooks that parallel process over large datasets and wish to report progress.

**Comment by scottdraves** [comment]
Hi Joe thanks for the feedback.  Will have to think about how to fix this, something like ThreadGroupLocal (except it doesn't exist).

**Comment by joewalnes** [comment]
I've worked around it for the moment by having background threads write to an `AtomicInteger` and the foreground thread regularly poll that and report progress.

One thought is would it be possible to make `InternalVariable` an instance of `NamespaceClient` and get rid of the ThreadLocal?

**Comment by joewalnes** [comment]
(btw, thanks for beakerx - it's sooo good!)

**Comment by scottdraves** [comment]
You are very welcome.  Your feedback is most welcome.

**Comment by jaroslawmalekcodete** [comment]
Hi 
@joewalnes could you provide more details ( scenario, code or example.ipynb ) to reproduce this problem?

**Comment by joewalnes** [comment]
Here's an example that walks through the scenario. Demonstrates the problem, and the workaround I'm using.

* View: https://nbviewer.jupyter.org/2c102adfbaa0efb2125cebd318643a73
* Download ipynb: https://gist.githubusercontent.com/anonymous/2c102adfbaa0efb2125cebd318643a73/raw/25cd8df2d53a521eb585b23cea2b7fb601978d4d/example-beakerx-6110.ipynb

**Comment by scottdraves** [comment]
thanks for the complete explanation of the situation!

**Comment by scottdraves** [comment]
we are almost done with 0.6.0 release, and 0.6.1 (including this fix) should happen soon after, like early next week.

@EfimovVladimir please make an e2e test from joe's notebook.

**Comment by scottdraves** [comment]
thanks again for bringing this to our attention.

**Comment by joewalnes** [comment]
👍

**Comment by scottdraves** [comment]
fix has been released in version 0.6.2 available by conda and pip.
