### ISSUE TITLE
easyform textfield too small

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6114]
text field is not the right width:
![screen shot 2017-10-10 at 11 12 50 am](https://user-images.githubusercontent.com/963093/31394311-0027e884-adac-11e7-9eb7-d914e46baa34.png)

**Comment by scottdraves** [comment]
not sure how this got past https://github.com/twosigma/beakerx/issues/6055

**Comment by MariuszJurowicz** [comment]
@scottdraves this is a python example. As i remember i have added a comment about the python implementation here: https://github.com/twosigma/beakerx/pull/6086.
We have added some new properties to the widgets and we need the python implementation to be overwritten as well (to point to beakerx widgets and to add the col and rows and size property to reflect the widget attributes). 
After all the width is set in pixels. If you want to set the width in characters you need to use the size property for inputs (TextWidget) and rows and cols property for textareas. Same as the html attributes for those elements.
But if you don't like this change, i can revert it and implement those widgets to set size and rows and cols from width and height properties.
