### ISSUE TITLE
grapes broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6118]
<img width="847" alt="screen shot 2017-10-10 at 11 05 03 pm" src="https://user-images.githubusercontent.com/963093/31420479-c0fc8854-ae0f-11e7-8dd8-c9f238cd5721.png">

**Comment by jaroslawmalekcodete** [comment]
The error goes from https://github.com/twosigma/beakerx/blob/master/kernel/groovy/src/main/java/com/twosigma/beakerx/groovy/evaluator/GroovyCodeRunner.java#L57 it means that passed code is incorrect for groovy compiler.

As I understand the grape has to be used together with the code http://docs.groovy-lang.org/latest/html/api/groovy/lang/Grab.html (with import statement) and from http://groovy-lang.org/grape.html -> section 3.1 (with class or method definition)
`One or more groovy.lang.Grab annotations can be added at any place that annotations are accepted to tell the compiler that this code relies on the specific library`


try these examples:

1.
> @Grapes(
    @Grab(group='com.google.code.gson', module='gson', version='2.2.4')
)
import org.apache.commons.io.Charsets

2.

> @Grab(group='commons-lang', module='commons-lang', version='2.4')
def printInfo() {
} 
printInfo()
