### ISSUE TITLE
gap between input and output in advanced mode

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#612]
![screen shot 2014-09-10 at 5 41 28 pm](https://cloud.githubusercontent.com/assets/963093/4225997/5189cb8e-3933-11e4-83ab-2ca6595841fc.png)
a couple of pixels in the border

**Comment by samccone** [comment]
![](http://dl.dropbox.com/u/36928599/Screenshots/0j6.png)

seems to be working for me?

**Comment by scottdraves** [comment]
could not reproduce
