### ISSUE TITLE
Errors when installing via conda-forge

### ISSUE THREAD

**Issue by tnn1t1s** [twosigma/beakerx#6178]
$ conda install -c conda-forge ipywidgets beakerx

...

CondaVerificationError: The package for beakerx located at /Users/user/anaconda3/pkgs/beakerx-0.6.2-py35_0
appears to be corrupted. The path 'lib/python3.5/site-packages/notebook/static/custom/fonts/lato/Lato-Regular.ttf'
specified in the package manifest cannot be found.

**Comment by scottdraves** [comment]
hi thx DP, what platform is this?  i just tested 3.5 on mac and seemed fine.
maybe blow away your pkg cache and try again? 
`rm -rf ~/anaconda/pkgs/beakerx*`

**Comment by tnn1t1s** [comment]
that did the trick. I've installed every version of beakerx on that machine so maybe just got into a weird state. thanks!
