### ISSUE TITLE
cannot select text in cell output that's an error

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#618]
the first line you can highlight but it does not stay selected so that i can copy it.
the expanded msg cannot be highlighted at all.

**Comment by scottdraves** [comment]
this effects all cells moving to 1.0 p1

**Comment by anglee** [comment]
This was introduced by https://github.com/twosigma/beaker-notebook/pull/610

**Comment by scottdraves** [comment]
sorry!
