### ISSUE TITLE
scala table example broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6204]
in tableApiScala.ipynb
<img width="564" alt="screen shot 2017-10-25 at 10 24 30 pm" src="https://user-images.githubusercontent.com/963093/32032125-7767f834-b9d3-11e7-8564-c3453fa9b9ff.png">

**Comment by jpallas** [comment]
What exactly is broken here?  We're not expecting a List of Maps to autodisplay as a table.

**Comment by scottdraves** [comment]
Groovy works that way
https://github.com/twosigma/beakerx/blob/f46e84d7b8d3e6fd5406cbb01fcad00562f66e4f/doc/contents/MapLikeTable_GroovyExample.ipynb
hopefully it's a convenience for you...

**Comment by jpallas** [comment]
Sorry, I misunderstood:  I thought this was reporting a regression.

We've previously discussed some challenges with using jvm-repr to handle the display of Scala collections (in #5920).  Maps and collections of Maps are a special case in `SerializeToString` that can't be adequately handled by jvm-repr.  It looks like `DisplayerDataMapper.convert` might be the only reasonable path in the current code if one is looking to change all Scala Maps and sequences of Maps to Java Maps and collections of Maps.
