### ISSUE TITLE
Problem with classpath add mvn and transitive dependencies

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#6207]
I've been playing with using Spark's ML library in a Scala notebook.  The library's linear algebra package depends on Breeze and netlib, and I've been running into things like

    Caused by: java.lang.ClassNotFoundException: org.netlib.blas.Daxpy

from inside the linear algebra package.

I narrowed it down to a problem with netlib core:

    %classpath add mvn com.github.fommil.netlib core 1.1.2
    Added jars: [core.jar, arpack_combined_all-javadoc.jar]
    new org.netlib.blas.Daxpy()
    <console>:80: error: type Daxpy is not a member of package org.netlib.blas
           new org.netlib.blas.Daxpy()
                               ^    
    %classpath add mvn net.sourceforge.f2j arpack_combined_all 0.1
    Added jar: [arpack_combined_all.jar]
    new org.netlib.blas.Daxpy()
    org.netlib.blas.Daxpy@5ab7837

I managed to find something relevant: sbt/sbt#861 blames it on a bug in Ivy.  Notice that the first command loads the javadoc jar instead of the code jar.  [This comment](https://github.com/sbt/sbt/issues/861#issuecomment-25919731) says it is "similar to" another Ivy bug that has been fixed, but I didn't get as far as figuring whether there is another Ivy bug filed for precisely this issue.

I'm not sure if there's a way to work around this in the implementation, but I want to get the bug filed here because it is likely to affect people trying to use Spark's ML library with the `add mvn` feature, and at least there is a workaround at notebook level by explicitly loading the missing dependency.

**Comment by scottdraves** [comment]
thanks for the report, we have experienced similar problems and will look at replacing ivy with maven itself.
