### ISSUE TITLE
Console error when inserting markdown cell

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#622]
An error appears in the console when a markdown cell is inserted:
![image](https://cloud.githubusercontent.com/assets/1767921/4237306/b63006da-39cd-11e4-94ab-d50c5fad850e.png)
introduced by #594

**Comment by samccone** [comment]
This is related to epic editor being really silly again a simple patch to epic editor to fix this if we want.

**Comment by melmac48** [comment]
@samccone , if we patch epic will this fix the other issue with markdown cells losing content when they're moved up and down? #594

**Comment by samccone** [comment]
yep, I am just going to fork it like 5 bugs are directly related to this :(

**Comment by scottdraves** [comment]
the cause of this was reverted
