### ISSUE TITLE
add redshift drivers

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6222]
http://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html
did we lose the other ones, what are these commented out?
https://github.com/twosigma/beakerx/blob/df758816b10f38922fb6f8c41c9e9ef615a34b20/kernel/sql/src/main/java/com/twosigma/beakerx/sql/autocomplete/db/DbExplorerFactory.java#L36
what happened to the list of jars/dependencies?
there should be more than h2
https://github.com/twosigma/beakerx/blob/df758816b10f38922fb6f8c41c9e9ef615a34b20/kernel/sql/build.gradle#L38
what about mysql, mssql, postgres?

also we need to document how to add your own, since last i checked %classpath didn't work because jdbc overrides our class loader.  maybe this is a good reason for https://github.com/twosigma/beakerx/issues/5661

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/issues/6272

**Comment by scottdraves** [comment]
still need mysql, mssql, postgres

**Comment by michalgce** [comment]
Added within https://github.com/twosigma/beakerx/pull/6281
