### ISSUE TITLE
table copy to clipboard broken

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6227]
instead of the table contents i am getting the code of the cell that generated the table.
doesn't matter if 1 or more cells are selected.

**Comment by Madhu94** [comment]
@mjurowicz-xsolve @scottdraves This bug should be fixed once jupyter notebook 5.3 is released. https://github.com/jupyter/notebook/pull/3088/

**Comment by scottdraves** [comment]
cool thanks, though we already fixed it via a workaround https://github.com/twosigma/beakerx/commit/2623565739b0ac6bf6e002c675d72556c595c976
