### ISSUE TITLE
Provide BeakerX jars on Maven

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6228]
I'd like to create a tablesaw-beakerx repository which publishes the [`TablesawDisplayer`](https://github.com/twosigma/beakerx/blob/73ac34418eeed06df280b774dc51d44857dd5730/doc/contents/Tablesaw_display_as_TableDisplay.ipynb) class to Maven Central

Right now, to use `TablesawDisplay` you need to either copy a large block of code into your notebook or copy `tablesaw_0.10.0_Demo.jar` into your project. I'd like to put `TablesawDisplayer` on Maven Central so that all you need to do is add a single line of code to your notebook `%classpath add mvn tech.tablesaw tablesaw-beakerx 0.10.0`

In order for me to create the tablesaw-beakerx project I need to depend on the classes:
* com.twosigma.beakerx.jvm.object.OutputCell;
* com.twosigma.beakerx.table.TableDisplay;

I would like to add these as Maven dependencies to the new tablesaw-beakerx project in the `provided` scope. I.e. I need access to them to compile the `TableDisplayer`, but then when a user wants to use the `TableDisplayer` they will get it directly from Jupyter.

**Comment by scottdraves** [comment]
That would be awesome, let me think about the right way to do it.

At least, I am not happy with the package for the OutputCell class.
So far we haven't worried about stability of our APIs yet but if this is going to start I would at least like to start from a good place.

**Comment by scottdraves** [comment]
@hadim

**Comment by benmccann** [comment]
I'm also planning to create a Java plotting capabilities per the docs below. Do you already have a Java representation of the json configuration that could possibly be exposed externally as well or should I create that from scratch?

https://github.com/twosigma/beakerx/wiki/Create-a-Plot-from-Different-Languages
https://github.com/twosigma/beakerx/wiki/Plot-JSON-Specification

**Comment by scottdraves** [comment]
Even better :) Those wikis are really old and never really complete, so I wouldn't rely on them.
All our wikis are really leftovers from Beaker Notebook and should be deleted or updated.

But about how to do this, we already have a complete java API for generating the plots, eg:
https://github.com/twosigma/beakerx/blob/e1fad3f34b22293e2f999385cc4cdc91571fda98/doc/contents/PlotFeatures.ipynb

OK that's groovy actually but the Java is there underneath, just more verbose.
See the 3rd code cell of https://github.com/twosigma/beakerx/blob/e1fad3f34b22293e2f999385cc4cdc91571fda98/doc/contents/javaTutorial.ipynb

Is that what you mean?

Or please tell me more about your plans.

**Comment by benmccann** [comment]
Oh, great! Thanks for sharing that. That helps a lot!

I just wanted to plot a chart. I couldn't figure out how to do it, but those notebooks help a lot in demonstrating.

I would like to create code that helps generate BeakerX plots from Tablesaw tables, so that it's really easy to plot a table that you have. That would rely on the plotting APIs making it into a Maven jar though same as the TableDisplayer APIs.

**Comment by benmccann** [comment]
An alternative solution if you're not ready to expose the APIs publicly yet would be to include `TablesawDisplayer` as part of BeakerX. You could do this without adding a dependency on Tablesaw by including it with `provided` scope.

**Comment by scottdraves** [comment]
I don't like "jvm" in that package name, it is a leftover.
But now that I look at it, fixing that should be done when it gets factored into kernel and runtime, and that is distant future.
So we are ready to publish the API.

**Comment by benmccann** [comment]
That's great! Instructions for doing so are here: http://central.sonatype.org/pages/ossrh-guide.html

The first step of the instructions is to [Create your JIRA account](https://issues.sonatype.org/secure/Signup!default.jspa) and [Create a New Project ticket](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134). You might want to do that part now because it can take a couple days to get your new project approved. It's pretty easy to request and will be nice to get it out of the way so it doesn't become a blocker when you try to test out publishing the jars.

**Comment by scottdraves** [comment]
Can you use the ones we already publish to jitpack? https://jitpack.io/#twosigma/beakerx/0.7.0

**Comment by benmccann** [comment]
Ok, great! I didn't realize there were already jars on jitpack. That works since I only need them in the `provided` scope

I've created a project to hold the `TablesawDisplayer` https://github.com/jtablesaw/tablesaw/commit/8d5d64f05e48a208a5b1a404b1b9d965517b9538. I'll update the docs here after the next release of Tablesaw

**Comment by scottdraves** [comment]
awesome
