### ISSUE TITLE
Need better documentation for base in category items

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#6245]
(This was going to be a comment on #6237, to which it is still relevant, but it's a separate issue.)

I can't figure out how `setBase` is supposed to work for the Category items.  The examples for `CategoryBars` in the `categoryPlot` notebook show base being set to a single number, a list of numbers, a list of lists of numbers, and a mixed list of numbers and lists of numbers.  The single number case sets `baseBase` and the other cases set `bases`, which is declared `List<Number>`.  So, this is a case where the usage is inconsistent with the type declarations in the Java code, and trying to work backwards from the types to the intended interface doesn't work.

**Comment by scottdraves** [comment]
thanks joe, uh idk let me get back to you.
@michalgce

**Comment by scottdraves** [comment]
I agree the declared type does not match the arguments.
IDK why Groovy allows this.  The implementation is confusing with the two properties as well.

Seems it would be an improvement to change `setBases` to take `List<Object>`.
Does that resolve this for you?

**Comment by jpallas** [comment]
Changing bases to be `List<Object>` would resolve the inconsistency, yes.  (Side note: I'm not sure if introducing a `BasedCategoryGraphics` subclass, similar to `BasedXYGraphics`, would be worthwhile.  It's only a few lines of common code.)  It won't help with the type-as-documentation aspect, sadly.

Given the way it's used, my dream of having a statically typed Scala interface that matches what is actually allowed seems out of reach.

**Comment by scottdraves** [comment]
Yea this bit of the API isn't amenable to static typing, sorry, it wasn't designed with that in mind.
The problem is just the mixing of the lists and numbers within the list, ie allowing [1, [2, 3]].
I don't think this is very commonly used, so if it had a more verbose syntax that would be OK.
Could you define a helper class that used a subclass to workaround lack of explicit sum types?
SetBase method would be overloaded with the following types:
`Number`, `List<Number>`, `List<List<Number>>`, and `List<ListOrNumber>`?

**Comment by scottdraves** [comment]
https://stackoverflow.com/questions/3508077/how-to-define-type-disjunction-union-types

**Comment by jpallas** [comment]
The problem with type constraints for sum types is that they are not actually types, so you can't express the constraint in the type of the parameter.  That is, a `List` that contains a mix of `Int` and `List[Int]` can still only be typed as `List[Any]`, and `Any` won't satisfy the constraint.  But your suggestion of using a helper class looks like it would work, with appropriate implicit conversions, based on some experiments I just did.

There's still a small annoyance: the implicit conversion of `Array` to `Seq` gets lost, and overloading doesn't resolve the problem because type inference and overloading don't play nicely together.  So users would need to do something explicit in the case where they wanted to use an array.  I can live with that.

**Comment by scottdraves** [comment]
OK, can you make the case where an explicit or extra thing is used be the `List<ListOrNumber>` case?

**Comment by scottdraves** [comment]
this can be closed though right?

**Comment by jpallas** [comment]
I'm preparing a PR to pull out a common base class that changes the type to `List<Object>` and checks the list at runtime in the setter to make sure it contains only Numbers and Lists of Numbers.
