### ISSUE TITLE
add environment.yaml binder file 

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6247]
so that our documentation can be opened up live online.
similar to: https://github.com/imagej/tutorials/commit/e4cd9ad55e7cc60ad6684df986c5e450526a15df

**Comment by ctrueden** [comment]
The relevant documentation which I followed was [here](http://repo2docker.readthedocs.io/en/latest/samples.html#conda-environment), along with the binder-examples like [this one](https://github.com/binder-examples/jupyter-rise/blob/c1fe3bd8afce4b9309762e489dab182ca70a5101/environment.yml).
