### ISSUE TITLE
Support plotting java.time.LocalDate and java.time.LocalDateTime

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6259]
I would like to be able to use `java.time.LocalDate` / `java.time.LocalDateTime` instances as my x-axis values

**Comment by scottdraves** [comment]
good idea, how about Instant as well?

**Comment by benmccann** [comment]
Probably a good idea. I personally don't have a need for that one at the moment, but I don't think it'd hurt to add it.

**Comment by jpallas** [comment]
I'm hoping the investigation of this issue will end up explaining the mysterious comment in `XYGraphics.setX`:

```
//        remove Java8 feature LocalDateTime, that has to wait
//        else if (x instanceof LocalDateTime) {
//          LocalDateTime date = (LocalDateTime)x;
//          ZonedDateTime zdate = date.atZone(ZoneId.of("UTC"));
//          this.xs.add(zdate.toEpochSecond() * 1000 + date.get(ChronoField.MILLI_OF_SECOND));
//        }
```

Whenever I see it I wonder, "What was the problem and what does it have to wait for?"

**Comment by scottdraves** [comment]
lol, sorry nothing too exciting. at at time one version of Beaker was compiled with Java 7.

**Comment by benmccann** [comment]
https://github.com/twosigma/beakerx/pull/6275
