### ISSUE TITLE
shows KeyError: 0

### ISSUE THREAD

**Issue by Aagam-J** [twosigma/beakerx#6269]
df.head() works fine
df.tail()  through KeyError: 0

**Comment by scottdraves** [comment]
good morning Aagam, thanks for the report.
can you provide more complete code to reproduce this problem?

**Comment by Aagam-J** [comment]
import pandas as pd
from beakerx import  *  

df = pd.read_csv('file.csv')
df.head()  #  works fine
df.tail()  # Not working

**Comment by scottdraves** [comment]
what version of BeakerX are you using?

It works with the csv files I have, eg
![screen shot 2017-11-08 at 10 52 14 am](https://user-images.githubusercontent.com/963093/32558526-f62c158e-c472-11e7-855c-49de1a3e2979.png)
if you could email your file to us so i can test it I would appreciate it.
you can use beakerx-feedback@twosigma.com
thx

**Comment by Aagam-J** [comment]
[https://screenshots.firefox.com/cHXiuDohQHDA7w8O/localhost](url)
[https://screenshots.firefox.com/k01CCxYwsET2DdN8/localhost](url)

mailed you the data file.
Thnx

**Comment by Aagam-J** [comment]
![](https://screenshots.firefoxusercontent.com/images/0ea3b857-aedd-4172-bdff-bcad025f3311.png)

![](https://screenshots.firefoxusercontent.com/images/ec11bae9-6afb-47ad-ac24-16e3def4304b.png)

Using Python 3, beakerx version 0.7.0
mailed you the data file.
Thnx

**Comment by scottdraves** [comment]
Thanks, I got it and tested it.
I am able to reproduce the problem with version 0.7.0, and indeed on master it works fine.
So this bug has already been fixed and it should be released soon (I am aiming for 0.8.0 next week).

Thank you very much for the report.
