### ISSUE TITLE
No suitable driver postgresql

### ISSUE THREAD

**Issue by alnjxn** [twosigma/beakerx#6272]
Getting this error when trying to connect to a Postgres RDS instance out of the box using the latest docker image. Also seeing this from a local pip based installation. How do I install the proper jdbc driver for postgresql?

`com.twosigma.beakerx.sql.DBConnectionException: Connection URI:jdbc:postgresql:// ... No suitable driver`

thanks!

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/pull/6281
