### ISSUE TITLE
polyglot kernel

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6279]
a kernel that switches between all other kernels, like:
https://github.com/vatlab/SOS
https://github.com/minrk/allthekernels

useful with autotranslation: https://github.com/twosigma/beakerx/issues/5039

The groovy magic is our prototype implementation of this: http://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/python/GroovyMagic.ipynb

**Comment by scottdraves** [comment]
A first step to this will be %%python magic for the JVM kernels, using https://github.com/bartdag/py4j

**Comment by scottdraves** [comment]
Here's an example: https://www.py4j.org/advanced_topics.html#implementing-java-interfaces-from-python-callback

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/pull/7340

**Comment by jpallas** [comment]
I'm not raising an objection to closing, but I have a question.  One case discussed in #6578 (get data using SQL, process using another JVM language) is not handled by the work done so far.  Is that still a goal?

**Comment by scottdraves** [comment]
If I understand you correctly, then yes, that will be covered by https://github.com/twosigma/beakerx/issues/7350 and https://github.com/twosigma/beakerx/issues/5039.
