### ISSUE TITLE
Please integrate/upgrade Groovy 2.4.x instead of 2.3.x

### ISSUE THREAD

**Issue by KIC** [twosigma/beakerx#6297]
println GroovySystem.version gives 2.3.4. There are plenty of nice features like `.withIndex()` in 2.4.x.

Thanks
KIC

PS really great job I love the notebooks very much!

**Comment by scottdraves** [comment]
Hi thank you for the feedback.
It sounds like you are running Beaker Notebook and not BeakerX?
The project has migrated, please see http://BeakerX.com
We agree, BeakerX comes with 2.4.3.

**Comment by altavir** [comment]
It will soon be time to migrate to 2.5 though.

**Comment by scottdraves** [comment]
Please reopen or file a new issue at that time.
Thanks.
