### ISSUE TITLE
Add new hotkeys for cell level menu items

### ISSUE THREAD

**Issue by melmac48** [twosigma/beakerx#631]
Cell move up: Ctrl-Alt-UP
Cell move down: Ctrl-Alt-DOWN
Cell show: Ctrl-Alt-S
Cell hide:  Ctrl-Alt-H
Cell delete: Ctrl-Alt-D

**Comment by samccone** [comment]
@anglee do you have this one?

**Comment by anglee** [comment]
yes, in progress, thanks for checking

**Comment by anglee** [comment]
There is no straightforward way to "cell show" as when the input cell is hidden, the CodeMirror of it is not in focus. @melmac48 can we drop that for V1?

**Comment by scottdraves** [comment]
we should just show the icons.  they will rarely actually overlap the text since the first line is rarely so long as to go all the way to the right.

**Comment by scottdraves** [comment]
@melmac48 says that is too big a change to contemplate now, and showing hidden input is available from the menu, so users are not completely stuck.  so yea just drop that one, i'll test and merge the rest after i get some food.

**Comment by anglee** [comment]
To make it clear, to show hidden input, there was already a icon for doing so, and which is easier than using the menu.

**Comment by scottdraves** [comment]
not in advanced mode

On Fri, Sep 12, 2014 at 1:41 PM, Ang Lee notifications@github.com wrote:

> To make it clear, to show hidden input, there was already a icon for doing
> so, and which is easier than using the menu.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twosigma/beaker-notebook/issues/631#issuecomment-55436689
> .

## 

ScottDraves.com http://www.ScottDraves.com
google.com/+ScottDraves
