### ISSUE TITLE
embed beaker in to existing Angularjs application

### ISSUE THREAD

**Issue by simar7777** [twosigma/beakerx#6313]
Hi , 
I already have my angularjs application and i am planning to embed beaker into my tool , since both are Angular i am planning to integrate both application for easy maintenance and data exchange. 

I don't want to use iframe . Please guide me how to achieve the same.

Cheers,
Siva

**Comment by scottdraves** [comment]
We are now developing BeakerX, a jupyter and jupyter lab version of Beaker, so we aren't working on the angular version anymore, sorry.
