### ISSUE TITLE
Document how to update beakerx

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6316]
I'm not sure how to get the latest version. I tried, but I seem to be stuck on an older version...

```
$ conda update beakerx
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/bmccann/packages/anaconda2/envs/beakerx:
#
beakerx                   0.4.1.dev0               py35_0    conda-forge
```

**Comment by scottdraves** [comment]
try adding `-c conda-forge`

**Comment by benmccann** [comment]
Yes, `conda update -c conda-forge beakerx` worked!

I'll leave this issue open as a suggestion to add to http://beakerx.com/documentation

**Comment by altavir** [comment]
Good idea, I was just calling install each time. The result is the same, but will be good to have it documented.

**Comment by scottdraves** [comment]
thanks https://github.com/twosigma/beakerx-www/commit/d844c77f4198dc9286b154e26cd79a213294f135
