### ISSUE TITLE
classpath add mvn should use local Maven cache

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6340]
`classpath add mvn` takes a really long time, which makes me think it's going out to the internet instead of using `~/.m2/repository/`

**Comment by benmccann** [comment]
Hmm, I can't seem to get it to complete at all, so maybe that's not the problem. First time I tried was from an airplane, so I though it was just a bad connection. But now I've tried from three different internet connections. On every single one it's freezing on the first cell of `Tablesaw_display_as_TableDisplay.ipynb`, while many other example notebooks are working. Is there possibly some file lock that needs to be deleted or some state somewhere that I should try clearing? I don't know how to tell what it's doing...

**Comment by benmccann** [comment]
Maybe it does some kind of caching though? I'm trying to update the Tablesaw example to use 0.11.0 and it's not working. The first time I tried I wasn't surprised because normally it takes up to an hour for new jars to become available on Maven Central. Now it's been a few hours since I published Tablesaw 0.11.0 and I see it available on Maven Central, but yet it's still erroring:

>Could not resolve dependencies for: tech.tablesaw : tablesaw-plot : 0.11.0Could not resolve dependencies for: tech.tablesaw : tablesaw-smile : 0.11.0Could not resolve dependencies for: tech.tablesaw : tablesaw-beakerx : 0.11.0Could not import com.beakerx.TablesawDisplayer, class not found.

**Comment by jpallas** [comment]
It looks like all the BeakerX kernels are sharing a repository in `${java.io.tmpdir}/beakerMvnCache`.  Any sharing is risky, though: see [Concurrent-safe access to local Maven repository](https://issues.apache.org/jira/browse/MNG-2802).  But people have been using Maven working around this for years (and years and years).

On some systems, having the cache in the default temp directory may mean that it periodically gets reclaimed.

**Comment by scottdraves** [comment]
i hope one download is OK, right?

using our own cache reduces chances of interference and insures version compatibility.
you are right though the first download takes a long time and there is no feedback and it seems hung.  we have already added a progress display and will make a better progress display after that https://github.com/twosigma/beakerx/issues/6367.  i suspect performance bugs in the rest of that cell too https://github.com/twosigma/beakerx/issues/6372

**Comment by scottdraves** [comment]
maybe we should provide our own locking to prevent %classpath commands in different notebooks from running in parallel?

**Comment by altavir** [comment]
> using our own cache reduces chances of interference and insures version compatibility

I am not sure it is wise. Contrary to Python, maven has very good interference locks of its own. Also maven stores multiple versions of the same package and therefore should not produce any version compatibility issues. Also maven users usually already have all their favorite dependencies  in maven local repository, so why not use it?

**Comment by benmccann** [comment]
The main case I could see for BeakerX having it's own cache directory is if we're not too confident in it yet and wanted to avoid breaking the user's main cache - e.g. if BeakerX were producing corrupted/incorrect Maven poms.

I think that the progress display could help substantially, so I'm interested to see how much of a difference it ends up making.

**Comment by altavir** [comment]
> if BeakerX were producing corrupted/incorrect Maven poms.

I can't see, how it could possibly happen if beakerx uses maven distribution internally.

**Comment by jpallas** [comment]
I'm not too concerned about BeakerX producing bad POMs for Maven, and I trust Maven to look after itself in most respects, certainly including managing multiple versions of artifacts.  But the documented issue with potential corruption from running multiple concurrent Maven processes is a concern, and in the one scenario we might corrupt the user's default local repo while in the other we only corrupt the BeakerX private repo.  That seems like an argument for isolation.

In all of this, I have no idea how likely corruption is to actually happen.  I just think that opening multiple notebooks that use `%classpath add mvn` concurrently seems somewhat more likely than typing Maven command lines into multiple terminal windows concurrently.

**Comment by benmccann** [comment]
Just opening a notebook won't run the command though, right? You have to manually run that cell of the notebook. It could happen, but I'm not sure it's dramatically more likely than it is on the command line

**Comment by jpallas** [comment]
> Just opening a notebook won't run the command though, right? You have to manually run that cell of the notebook. 

In general, that's true.  I suspect `%classpath add` is a reasonable candidate for an initialization cell, though.  In that case, the user may not always be thinking about the side effects of opening a notebook.

**Comment by benmccann** [comment]
Another thing I'd really like to be able to do is publish a library I'm working on locally to my local Maven repository (i.e. `mvn install`) and then consumer it from BeakerX. That means that BeakerX would need to at least read from my local repo

**Comment by jpallas** [comment]
That's a pretty compelling use case, I have to admit.  Perhaps it could be satisfied by configuring the `~/.m2/repository` location as a "remote" repository using a `file:` URL.  That would mean copying files to the beaker-private repository from the user's default repository, though, with accompanying cost in duplicated storage and possible complications in managing the caching for snapshots of work that's in flux.

Maybe the right thing to do is just put a big red CAUTION warning in the documentation about the risk of concurrent updates and use the default local repository location.

**Comment by altavir** [comment]
> Maybe the right thing to do is just put a big red CAUTION warning in the documentation about the risk of concurrent updates and use the default local repository location.

I completely agree with this. Also, I think, it is quite easy to add additional safety lock from beakerx side. Just add some kind of `maven.lock` file to beakerx temp directory and ensure only one beakerx process can access the repository at a time. One of course needs to be careful about removing this lock in case of interruption, so maybe it should be somehow connected to jupyter session.

**Comment by scottdraves** [comment]
i don't mind some extra copying if it can buy reliability.
can't `%classpath add repo ...` (https://github.com/twosigma/beakerx/issues/6347) or something like it handle this? maybe `%classpath add local-repo ...`. it sounds like a wrapper around what joe is suggesting.
that way we can guarantee safety except if you use this magic, and the warning label applies to it specifically.

**Comment by scottdraves** [comment]
1) Our research indicates maven does not provide locking and can misbehave if more than one process accesses the cache at the same time.  So we should use our own cache and provide locking.

2) Location of our cache is not clear, perhaps in the conda environment is best because that eliminates the possibility of envs affecting each other in any way (good), though it does mean redownloading when you create a new env.  This could be seen as good or bad.  Good because it's more reproducible and that's exactly what envs should be, but bad because it means extra time spent waiting compared to a more shared location.

3) we still need to look into a solution for "publish a library I'm working on locally to my local Maven repository (i.e. mvn install) and then consuming it from BeakerX"

**Comment by jmsdnns** [comment]
I don't feel confident enough in my understanding to be sure this helps, but the description on this Takari project seems pretty close to some of the issue here.

https://github.com/takari/takari-local-repository: _The Takari Concurrent Local Repository component is a replacement for the management of a local Maven repository of a default Maven installation. It makes access to the local repository safe for concurrent access from multiple threads and Maven invocations._

I learned about _takari-local-repository_ from this Jira for the Maven project: https://issues.apache.org/jira/browse/MNG-2802
