### ISSUE TITLE
allow adding maven resolvers

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6347]
https://github.com/twosigma/beakerx/issues/6343
```
@GrabResolver(name='bintray', root='http://dl.bintray.com/6thsolution/apexnlp'),
```
make the equiv of this for `%classpath add mvn`

**Comment by scottdraves** [comment]
`%classpath add repo ...`

**Comment by jpallas** [comment]
Maybe a different subcommand than `add`?  The existing `add` commands both add things to the classpath, while this does not.  `%classpath config resolver`?

**Comment by scottdraves** [comment]
good point.
