### ISSUE TITLE
Removing a widget leaves an empty line 

### ISSUE THREAD

**Issue by jaroslawmalekcodete** [twosigma/beakerx#6374]
run the following code:
%classpath add mvn org.datavec datavec-api 0.9.1
%classpath add mvn org.datavec datavec-local 0.9.1
%classpath add mvn org.datavec datavec-dataframe 0.9.1
%classpath add mvn org.deeplearning4j deeplearning4j-core 0.9.1
%classpath add mvn org.nd4j nd4j-native-platform 0.9.1
%classpath add mvn org.nd4j nd4j-native 0.9.1

or look at an example below
![removingwidget](https://user-images.githubusercontent.com/21952713/33124426-3ac43a04-cf7d-11e7-8451-64a108a61469.jpg)

**Comment by scottdraves** [comment]
yup thanks

**Comment by MariuszJurowicz** [comment]
@jaroslawmalekcodete @scottdraves 
I don't know if this is something we need to worry about.
Empty line is just an empty `<div class="output_subarea">` element that has the default Jupyter's style with `padding: 0.4em`.
If i run your example code it tries to render the output and adds the `output_area` element each time.

After executing each line `%classpath add mvn ...` the `output_area` is added.

**Comment by MariuszJurowicz** [comment]
This issue is about clearing output by ipywidgets that do not removes the `output_area`.
So after rendering the output by sending the `display_data` msg, calling the `.close()` method will not remove this output area but the widget.

**Comment by MariuszJurowicz** [comment]
@scottdraves any thoughts on this issue?
