### ISSUE TITLE
Some plotting examples are broken

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6386]
About half the plotting examples work for me while half don't. E.g. the files below don't seem to do anything for me:

* categoryPlot.ipynb
* histogram.ipynb
* heatmap.ipynb

**Comment by scottdraves** [comment]
Thanks Ben.  I can't reproduce that right now -- but I have seen that kind of catastrophic error and usually clearing the repo and rebuilding fixes it.  I use `git clean -fxd`.  Please LMK if that works for you.  I guess that's a build bug.

**Comment by benmccann** [comment]
That's a good suggestion. Unfortunately it's not working for me

I'm trying with:

```
beakerx                   0.8.1                    py35_0    conda-forge
```

**Comment by scottdraves** [comment]
is this still a problem?

**Comment by benmccann** [comment]
Looks like it's working now. Thanks
