### ISSUE TITLE
Error gets overwritten

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6407]
I have BeakerX working on my Ubuntu machine. I'm also trying to get it to work on my RedHat machine, but am getting the message `Cell magic  not found`. Any ideas?

**Comment by scottdraves** [comment]
Hi Ben thanks for the issue.
That sounds really weird.  Normal cells, like just "1+1" work fine?
How did you make the environment and install BeakerX into it?

**Comment by benmccann** [comment]
Yes, `1+1` worked.

I followed the steps on beakerx.com/documentation to install:

```
conda create -y -n beakerx 'python>=3'
source activate beakerx
conda install -y -c conda-forge ipywidgets
conda install -y -c conda-forge beakerx
```

It's not clear from the instructions if I also need to run the line below?
```
jupyter labextension install beakerx-jupyterlab
```

The other thing I wasn't 100% sure about was what version of Jupyter to install. I downloaded the Python 2.7 version from https://www.anaconda.com/download/#linux because my machine has Python 2.7 installed on it. I assumed this would be okay because Conda installs Python 3 then:

```
$ source activate beakerx
(beakerx) $ python --version
Python 3.6.3 :: Anaconda, Inc.
```

**Comment by scottdraves** [comment]
Labextension is only if you want to run jupyter lab (i just added some more instructions for that).

Yea root env should not matter.

IDK how it could fail like that, will have to think about it.

**Comment by benmccann** [comment]
I figured it out. If I change the first cell to just:

```
%classpath add mvn tech.tablesaw tablesaw-plot 0.11.0
%classpath add mvn tech.tablesaw tablesaw-smile 0.11.0
```

Then I get the error message:

```
Error configuring command-line. Reason: Maven executable not found at: /local/maven/bin/mvnError configuring command-line. Reason: Maven executable not found at: /local/maven/bin/mvn
```

We should probably concatenate errors instead of overwriting them

**Comment by scottdraves** [comment]
Ah good catch.
But I don't understand why it can't find maven, it should be installed into the conda env, and we just find it in the path.
Do you have M2_HOME set to something funny?

**Comment by benmccann** [comment]
Yeah, my $M2_HOME was set to a non-existent directory. It wasn't a big deal to fix once I realized that's what the issue was

**Comment by scottdraves** [comment]
Jarek and I both tried setting a bad M2_HOME and I got an error like you did, but it was clearly visible:
![screen shot 2017-12-01 at 10 31 27 am](https://user-images.githubusercontent.com/963093/33489771-ddc0e318-d682-11e7-906b-915fef9a8268.png)

so still not sure what's wrong here.

**Comment by benmccann** [comment]
Hmmm. Not sure this is worth leaving open then if you don't have a way to reproduce unless other users end up reporting too. Feel free to close
