### ISSUE TITLE
table alignment is off

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6408]
columns are too narrow, and the headers don't match the body exactly.
<img width="382" alt="screen shot 2017-11-28 at 8 45 53 pm" src="https://user-images.githubusercontent.com/963093/33353734-3f2cc8c2-d47d-11e7-9066-d67456f46910.png">

**Comment by MariuszJurowicz** [comment]
@scottdraves 
I couldn't reproduce this bug. I think it can be caused by other error thrown somewhere else in js.

**Comment by scottdraves** [comment]
try installing 0.9.0

**Comment by scottdraves** [comment]
could not reproduce
