### ISSUE TITLE
link to src in github, fix spelling

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6411]
fix spelling, Evns to Envs throughout
link to: https://github.com/twosigma/beakerx/blob/master/kernel/demoProjects/loadMagicJarDemo/src/main/java/com/twosigma/beakerx/custom/magic/command/ShowEvnsCustomMagicCommand.java
apply same fix to ditto for AddJarToClasspathMagicCommands.ipynb

<img width="428" alt="screen shot 2017-11-28 at 10 36 47 pm" src="https://user-images.githubusercontent.com/963093/33356827-ad33b1d2-d48c-11e7-8c84-e525fdbf554e.png">

**Comment by jaroslawmalekcodete** [comment]
Links will be valid after merging
