### ISSUE TITLE
add jupyterlab and jupyterhub to docker image

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6429]
i think it's as simple as
```
conda install -c conda-forge jupyterhub jupyterlab
```

**Comment by michalgce** [comment]
@mjurowicz-xsolve after added jupyterlab 
![image](https://user-images.githubusercontent.com/1582983/33482877-6e44f6dc-d69b-11e7-8005-0a30d8328d9e.png)

after execute random groovy cell

**Comment by scottdraves** [comment]
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

**Comment by michalgce** [comment]
![image](https://user-images.githubusercontent.com/1582983/33550128-1c415f52-d8ed-11e7-96c9-aaef125471b9.png)

![image](https://user-images.githubusercontent.com/1582983/33550117-118b8416-d8ed-11e7-9efd-3196d839ddce.png)

**Comment by MariuszJurowicz** [comment]
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`
`jupyter labextension install beakerx-jupyterlab`
