### ISSUE TITLE
Returning anonymous result from Java cell results in compilation error

### ISSUE THREAD

**Issue by Zavster** [twosigma/beakerx#6431]
<img width="1084" alt="screen shot 2017-12-01 at 09 55 03" src="https://user-images.githubusercontent.com/9557117/33477520-d85c35ee-d67d-11e7-85b5-19035b62d71d.png">

This is not an issue if you assign the result to a variable, and then return the variable...

<img width="697" alt="screen shot 2017-12-01 at 09 56 37" src="https://user-images.githubusercontent.com/9557117/33477554-f3cf25e8-d67d-11e7-8823-007231c8b71f.png">

**Comment by scottdraves** [comment]
Hi thanks for the bug report, can you please publish a notebook that reproduces that and link us to it?

**Comment by Zavster** [comment]
It seems to be related to multiline expressions... see notebook linked below...

https://nbviewer.jupyter.org/gist/anonymous/01e4d55477cd289dbab32554831acc6b

**Comment by scottdraves** [comment]
Our long term plan is to support JShell but we are currently blocked on java9:
https://github.com/conda-forge/openjdk-feedstock/issues/21
