### ISSUE TITLE
Strange display of updated plot

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#6443]
I _think_ this is a bug; it's definitely confusing.

Three one-line cells (I did Groovy, but I first saw it in Scala, so language-independent, I think):

    lines = new Line(x: [1, 2, 3], y: [1, 4, 9])
    p = new Plot()
    p << lines

When the third cell is executed, the updated plot is now displayed twice, but both instances appear below the second cell.
![screen shot 2017-12-01 at 1 31 42 pm](https://user-images.githubusercontent.com/4623910/33504752-8c09a7ec-d69d-11e7-9a3c-d03b78632552.png)

**Comment by scottdraves** [comment]
yea i think the 2nd plot should appear in the output of the 3rd cell, not 2 plots in the 2nd cell.
