### ISSUE TITLE
rename "beakerx" to "python"?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6462]
i am pretty sure that this directory: https://github.com/twosigma/beakerx/tree/master/beakerx
should be named "py" or "python".  what about the one inside of it:
https://github.com/twosigma/beakerx/tree/master/beakerx/beakerx
?  right now when i clone this repository it gets named "beakerx" by default and 3 in row is too confusing for sure.

**Comment by jmsdnns** [comment]
I thought about this and believe the current model is actually right, but on a technicality.

It is typical for a Python repo to share the name of the module we'd use in code. This ends up being something like a directory called `jamesx` and then a subdirectory also called `jamesx`. The repo name _can_ be anything, so this is a convention.

In our case, we are packaging the usual form inside another directory, like `jamesx/jamesx/jamesx`.

If I break that apart and number them, like jamesx (1) / jamesx (2) / jamesx (3), I believe 1 and 3 should stay the same. 1 is the repo name and 3 is the module that gets imported in code. 2 is then arbitrarily changeable. _python_ or _py_ would both be suitable, but I am not sure what the convention is. Having a directory above the directory where "setup.py" lives doesn't come up too often.

I wonder if this issue will go away after we break the kernels out into their own packages?

**Comment by scottdraves** [comment]
oh you are right, creating new packages for each kernel changes this anyway, and we already have a PR to do that so no sense changing this now.  let's just focus on getting that PR right: https://github.com/twosigma/beakerx/pull/6333
