### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6479]
Lots of the links in StartHere are broken now. E.g. link is to Histogram.ipynb but filename is histogram.ipynb

**Comment by scottdraves** [comment]
thanks you are right.  my filesystem is case insensitive so i didn't notice.

**Comment by scottdraves** [comment]
~also, move StartHere.ipynb into the doc directory, including update the link to it in the readme.~

**Comment by scottdraves** [comment]
actually, leave it where it is at the top level.  but add doc/README.md that links to https://github.com/twosigma/beakerx/blob/master/StartHere.ipynb
