### ISSUE TITLE
Scala input/output problem after classpath add

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#6510]
While #6508 fixed the problem with the Scala interpreter going bonkers, there seems to be something odd happening with the first line of input after a class path change.

```
In [1]: println("line 1"); "first input"
line 1
Out[1]: first input

In [2]: %classpath add mvn org.scalacheck scalacheck_2.11 1.13.5
Added jars: [test-interface-1.0.jar, scala-library-2.11.8.jar, scalacheck_2.11-1.13.5.jar]

In [3]: println("line 3"); "third input"
Out[3]: first input

In [4]: println("line 4"); "fourth input"
line 4
Out[4]: fourth input
```

It looks like the input may not be processed, and a previous result is being returned.  Or something.  It's confusing.  Only seems to show up if the `%classpath` is not the first input.

**Comment by scottdraves** [comment]
thank you joe
