### ISSUE TITLE
[Scala] : native lib problem

### ISSUE THREAD

**Issue by jaroslawmalekcodete** [twosigma/beakerx#6517]
This issue is back: https://github.com/twosigma/beakerx/issues/6257 because of the fix for https://github.com/twosigma/beakerx/issues/6503

**Comment by jaroslawmalekcodete** [comment]
Right now we create new classLoader when we add jar by magic command which causes problem with native lib and we create new scala shell which introduces problem with variables across the cell

It looks like both problems #6257 and #6503 can be fixed by changing scala version to 2.12.3 
(branch https://github.com/twosigma/beakerx/tree/jarek/6517_changing_scala_to_2_12_3)
but unfortunately we are blocked by spark which doesn't support scala 2.12.3
We have to wait for finishing https://issues.apache.org/jira/browse/SPARK-14220

**Comment by jpallas** [comment]
I wish I understood this problem better.  I don't know anything about the interaction between the Scala compiler and the class loader.  It doesn't seem like adding a jar should require creating a new class loader, but I'm sure there's more to this than meets the eye.
