### ISSUE TITLE
what's the minimum requirement?

### ISSUE THREAD

**Issue by mcdoyaji** [twosigma/beakerx#6518]
I try beaker notebook docker image on my raspberry pi 3.

but it stopped at the end of image  pull & extract stage.

Is there any minimum requirement?

**Comment by scottdraves** [comment]
we are not sure of the minimum but it is not a small application. sorry
it's not working for you on the raspi.

BeakerX.com
ScottDraves.com
twitter.com/Scott_Draves

**Comment by mcdoyaji** [comment]
Ok, I got It. Thanks!!
