### ISSUE TITLE
[Python] make TableDisplay object clickable

### ISSUE THREAD

**Issue by buhl22** [twosigma/beakerx#6524]
Hello,
is there a possibility to make the interactive tables from TableDisplay clickable or let them handle events?
as in get the selected row and do something with the values.
Or react to double clicks on a cell.
The latter was mentioned in a tutorial but only with code that looked like C

**Comment by scottdraves** [comment]
hi, thanks for your question.
not sure what you mean, but to make dataframes display interactively, just do a `from beakerx import *` as documented here:
http://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/python/TableAPI.ipynb

to confirm, are you using BeakerX, or Beaker Notebook?

**Comment by buhl22** [comment]
Hey,
I am using beakerX on python 3.6x.
I am sorry if my question was not clear.
I was wondering if there is a functionality like the observe function for ipywidgets. 
And with that observing for example which cell/column/row is selected in the TableDisplay and then perform an action like summing or printing that row.
Only thing I found was 
"display7.setDoubleClickAction { row, col, tableDisplay ->
   tableDisplay.values[row][col] = tableDisplay.values[row].sum()"
in http://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/groovy/TableAPI.ipynb
But that is clearly no python code and I havent found anything similar

**Comment by scottdraves** [comment]
hi sorry i forgot to get back to you about this.

you are right, the addContextMenuItem and setDoubleClickAction APIs were never implemented for Python.

but now they will be, thank you for the reminder, they just slipped through the cracks.
