### ISSUE TITLE
browser opens up settings/help tab while tests are running

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6542]
the test in progress at that time hangs and fails.
if i close the settings tab fast enough, then the tests run.
![screen shot 2017-12-18 at 12 01 57 pm](https://user-images.githubusercontent.com/963093/34171773-9d87e172-e4bd-11e7-8a12-f78d481eae35.png)

**Comment by EfimovVladimir** [comment]
It looks like the problem for mac and version of chromedriver
https://github.com/GoogleChrome/lighthouse/issues/3667
