### ISSUE TITLE
Table display widget reverses table

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6567]
The table displayer is printing the columns in reverse order. The code below shows a table with "Value" and then "Date". However, I'd expect the column order to be "Date" and then "Value", which is what printing the table shows

Source code for the TablesawDisplayer: https://github.com/jtablesaw/tablesaw/blob/master/beakerx/src/main/java/tech/tablesaw/beakerx/TablesawDisplayer.java

This code will execute the table display widget:

```
%classpath add mvn tech.tablesaw tablesaw-core 0.11.3
%classpath add mvn tech.tablesaw tablesaw-beakerx 0.11.3
%classpath add mvn com.jimmoores quandl-tablesaw 2.0.0
%import com.jimmoores.quandl.*
%import com.jimmoores.quandl.tablesaw.*
%import tech.tablesaw.api.*
%import tech.tablesaw.columns.*

tech.tablesaw.beakerx.TablesawDisplayer.register()

session = TableSawQuandlSession.create();
cape = session.getDataSet(DataSetRequest.Builder.of("MULTPL/SHILLER_PE_RATIO_MONTH").build());
```

Now in a new cell:
```
cape.print()
```

Notice that the display widget shows the table backwards

**Comment by scottdraves** [comment]
looks like  https://github.com/twosigma/beakerx/issues/6445

**Comment by benmccann** [comment]
Yes. Closing as duplicate
