### ISSUE TITLE
mvn commands overwrite each other?

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6569]
I'm alternately getting tablesaw 0.9 (pulled in transitively via `quandl-tablesaw`) and 0.11 on my classpath.

At first I thought it might be related to the ordering. E.g. this:

```
%classpath add mvn tech.tablesaw tablesaw-core 0.11.4
%classpath add mvn tech.tablesaw tablesaw-beakerx 0.11.4
%classpath add mvn com.jimmoores quandl-tablesaw 2.0.0
```

Vs this:
```
%classpath add mvn com.jimmoores quandl-tablesaw 2.0.0
%classpath add mvn tech.tablesaw tablesaw-core 0.11.4
%classpath add mvn tech.tablesaw tablesaw-beakerx 0.11.4
```

Now I'm thinking it's just random.

The way I would expect this to work is that each `%classpath add` adds to the list of Maven dependencies and then they all get resolved together.

**Comment by jmsdnns** [comment]
Please correct me if I'm wrong here, but I am under the impression that mvn does uses the first matching classes found unless a pom file has configuration to do something different.

So I looked into where that code lives and found these relevant parts:

Executes the JVM magics: https://github.com/twosigma/beakerx/blob/master/kernel/base/src/main/java/com/twosigma/beakerx/kernel/handler/MagicCommandExecutor.java#L37

Implements the `add mvn` magic, which uses a pom: https://github.com/twosigma/beakerx/blob/master/kernel/base/src/main/java/com/twosigma/beakerx/kernel/magic/command/functionality/ClasspathAddMvnMagicCommand.java#L57

On line 74 we eventually see the call to retrieve is done with a single magic and a single pom factory, which is unaware of the other magics. I'd like @scottdraves or someone else to confirm for me, but I believe I've confirmed what you're observing.

**Comment by jmsdnns** [comment]
I thought about this a little more and realized you could use the BeakerX tab to pass JVM options that load the jars, presumably as you need.

You have a valid point about the classpath magics, but I think we have a way to support what you need today too.

![screenshot from 2017-12-28 09-12-18](https://user-images.githubusercontent.com/7950614/34413270-3d987444-ebb0-11e7-9eff-76c97bb2a509.png)

**Comment by benmccann** [comment]
> I am under the impression that mvn does uses the first matching classes found

If you resolve multiple dependencies at once and it finds multiple versions of a given library on the classpath then it picks the one with the highest version number. The issue is that I'm not sure that's happening since I think we're running separate resolve operations

> you could use the BeakerX tab to pass JVM options that load the jars, presumably as you need

That sounds pretty complicated. To be completely honest, I'd probably give up on using beakerx before I did that

**Comment by jmsdnns** [comment]
> If you resolve multiple dependencies at once and it finds multiple versions of a given library on the classpath then it picks the one with the highest version number.

The [Maven wiki](https://wiki.apache.org/commons/MavenAndClasspath) has the following text:

_Maven identifies jars using the coordinate triple {groupId, artifactId, version}. It assumes that jars with the same pair {groupId, artifactId} are different versions of the same jar, and will ensure that only one instance of the jar is added to the classpath (in general the one with the highest version)._

_Jars with different {groupId, artifactId} pairs are treated as entirely different jars, even if they contain identical classes. Maven does not examine the contents of jars; it relies on the {groupId, artifactId} pair to determine whether different jars have the same or different classes in them._

From your code above, it looks as though you have different versions of the same class in jars with a different groupId and artifactId, suggesting Maven won't examine the contents of the jars for version resolution of the same class, and so it would fall back to iterating through the classpath for a match.

Would be helpful to test this with actual code soon.

> The issue is that I'm not sure that's happening since I think we're running separate resolve operations

My prior comment makes the case this is true.

> That sounds pretty complicated. To be completely honest, I'd probably give up on using beakerx before I did that

The specific step is to add this command line option `-classpath /path/to/A.jar:/path/to/B.jar`. It isn't clear to me why this is more complicated than using magics.

Do you mean to say the UI isn't as friendly or obvious as you'd prefer?

**Comment by benmccann** [comment]
> The specific step is to add this command line option -classpath /path/to/A.jar:/path/to/B.jar. It isn't clear to me why this is more complicated than using magics.
Do you mean to say the UI isn't as friendly or obvious as you'd prefer?

Maven resolves transitive dependencies. So if A depends on B, C, D which in turn depend on E, F then I can just do `%classpath add mvn A` and have all six jars added to my classpath. I'm assuming that the `-classpath` option does not do this in which case I'd need to do `-classpath A.jar:B.jar:C.jar:D.jar:E.jar:F.jar`. This could be very cumbersome because adding two or three jars via Maven could turn into adding dozens of jars via command line option, which could be quite difficult to deal with as I'd have to make sure they're all downloaded and then create a text string with the paths to all of these different jars

> it looks as though you have different versions of the same class in jars with a different groupId and artifactId

No, this is not what I'm suggesting

`com.jimmoores:quandl-tablesaw:2.0.0` depends on `tech.tablesaw:tablesaw-core:0.9.2`. I'm also directly including `tech.tablesaw:tablesaw-core:0.11.4`. If Maven resolves `com.jimmoores:quandl-tablesaw:2.0.0` and `tech.tablesaw:tablesaw-core:0.11.4` at the same time then `tech.tablesaw:tablesaw-core:0.9.2` should be evicted in favor of `tech.tablesaw:tablesaw-core:0.11.4`. This would match the description above of how Maven works:

> It assumes that jars with the same pair {groupId, artifactId} are different versions of the same jar, and will ensure that only one instance of the jar is added to the classpath (in general the one with the highest version).

What I'm worried about is that it looks to me like `tech.tablesaw:tablesaw-core:0.11.4` is resolved during the first magic. And then `com.jimmoores:quandl-tablesaw:2.0.0` is resolved in the last magic pulling in `tech.tablesaw:tablesaw-core:0.9.2` and adding a second version of `tablesaw-core` (0.9.2) to the classpath which may take precedence over `tech.tablesaw:tablesaw-core:0.11.4` depending on classpath ordering

What I'd like is to have a way to resolve these Maven jars at the same time so that Maven can do it's normal logic of seeing two jars with the same pair {groupId, artifactId} and ensuring that only one instance of the jar is added to the classpath (in general the one with the highest version).

**Comment by jmsdnns** [comment]
I see what happened. I mistook what you were saying to mean `tech.tablesaw:tablesaw-core:0.9.2` was packaged inside `com.jimmoores:quandl-tablesaw:2.0.0`. Your last description makes it clear it is a separate jar file. My mistake. Sorry about that.

My earlier description of the commands being independent is still helpful, but I would add that each invocation has a separate `PomFactory`. If that were shared at the cell or even notebook level, we might get the effect you're looking for.

A `PomFactory` is created fresh for each `ClasspathAddMvnMagicCommand` instance here: https://github.com/twosigma/beakerx/blob/master/kernel/base/src/main/java/com/twosigma/beakerx/kernel/magic/command/functionality/ClasspathAddMvnMagicCommand.java#L43

**Comment by scottdraves** [comment]
Hi Ben thanks for discovering this, I am on holiday and will look into it
in the new year. We definitely intend to use maven's normal logic and not
the class path cmd line argument.

**Comment by scottdraves** [comment]
confirmed this problem.

**Comment by scottdraves** [comment]
proposed solution:  introduce a cell magic for classpath where you can give multiple dependencies to maven to solve all together:
```
%%classpath add mvn
com.jimmoores quandl-tablesaw 2.0.0
tech.tablesaw tablesaw-core 0.11.4
tech.tablesaw tablesaw-beakerx 0.11.4
```

but given the iterative UX, there's really no way to avoid allowing the user to request conflicting jar versions.  so when this happens we should just make a clear warning to the user.  at this point they can reset their kernel if they want to.

**Comment by benmccann** [comment]
That seems like it'd work to me. We can suggest in the documentation that the user have one cell at the beginning of the notebook where they add all their dependencies and avoid using multiple magics at the risk of overriding their classpath

**Comment by jmsdnns** [comment]
Regarding _conflicting jar versions_: if the paths were all processed together, could we rely on maven's dependency resolution to do what it normally does?

My thought (_hope?_) is that that'd give the user an experience consistent with how maven behaves outside BeakerX.

**Comment by scottdraves** [comment]
maven runs on a pom.xml file, it doesn't have the same iterative model, so it doesn't face this kind of conflict.  the classpath cell magic described above does process everything given to it together, as if it were all in a pom.xml.

**Comment by jmsdnns** [comment]
We're mostly on the same page, but I'm stuck on this: _... given the iterative UX, there's really no way to avoid allowing the user to request conflicting jar versions_.

I think we agree the proposed cell magic would do this correctly. Is the comment about _iterative UX_ then an issue of informing the user to use a cell magic instead of a line magic?

**Comment by jmsdnns** [comment]
I caught up with @scottdraves and understand now that the cells do not share a pom.

**Comment by scottdraves** [comment]
It's possible they could, we could keep the pom around for the duration of the kernel and each %classpath add mvn would add to it, and would unload, resolve and download.  i think it would be a performance hit and be more complicated and users could be confused.  but really idk what's right.

**Comment by benmccann** [comment]
I'd be fine saying that you can only have a single `%classpath add mvn` command in the notebook. Not sure if we want to do that, but it's most analogous to how folks use Maven outside of Beakerx
