### ISSUE TITLE
zoomable time chart

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6570]
It can be quite hard to read a chart with many data points. If you look at other sites like [Yahoo Finance's S&P 500 chart](https://finance.yahoo.com/chart/%5EGSPC) or [Google Finance's S&P 500 chart](https://finance.google.com/finance?q=INDEXSP%3A.INX) they let you zoom in and see just a segment of the chart in more detail. It would be wonderful to have the same functionality in beakerx

I contribute quite a bit to Chart.js, which is a canvas-based JS charting library. It has a [zoom plugin](https://github.com/chartjs/chartjs-plugin-zoom), which provides this type of functionality. I'm not sure what JS charting library you use, but maybe we could develop the same functionality for it or use something like Chart.js which already provides it.

**Comment by benmccann** [comment]
It's also worth mentioning that the reason I use Chart.js in my other projects is that it's canvas based, so there's a really substantial performance benefit vs other JS chart libraries especially when you have a good number of charts on a single page. I see the current beakerx charts are drawn with SVG, so this might be another reason to consider using Chart.js

**Comment by scottdraves** [comment]
Hi Ben, BeakerX plots support zooming already. Click on a chart to begin interacting with it.
Drag to pan, use the mouse wheel to zoom (two fingers drag up/down on the mac).  Or right click and drag for box zoom.

This is documented here: http://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/groovy/Charting.ipynb#Navigation


In the long run we are not that interested in supporting our own charting implementation given the many fine open source options.  I think switching to a more standard API is a great idea but it will take us some time to get there.  I filed an issue for that goal: https://github.com/twosigma/beakerx/issues/6572

**Comment by benmccann** [comment]
Thanks! I didn't realize this was supported already.
