### ISSUE TITLE
mvn caching improvements

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6571]
There are two improvements that could be made to the way `%classpath add mvn` works

The first is that downloaded jars should be cached permanently. This would be far more performant as jars wouldn't have to be re-downloaded. It's also how the `mvn` command line tool works, so would be more consistent with user expectations

The second is that if a jar is not found it would be nice not to cache that the jar is not available. I've run into the situation a few times now where I've tried to publish a jar and then consume it from beakerx. I try the first time and it's not available yet. I then expect to be able to retry and see if the jar is available yet, but it's caching that the jar doesn't exist. This is quite unexpected because it does not match the way that the `mvn` command line tool works. It's also a bit cumbersome to deal with because I have to find the directory where the cache is stored and go manually clear it out

**Comment by jpallas** [comment]
On the second point: I'm pretty sure that command-line `mvn` does cache the absence of an artifact, because I recall having to fight with it over that.  […] Yes, I just did a quick test:
```
[ERROR] Failed to execute goal on project mvntest: Could not resolve dependencies for project com.example:mvntest:jar:1.0-SNAPSHOT: Failure to find com.example:dummy:jar:1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

So, that may make a case for having a `-U` option on `%classpath add mvn`, although it would be odd to save that in a notebook, since you'd really only want to use it when required.

**Comment by benmccann** [comment]
Thanks for correcting me. I've been using sbt much more than Maven lately and it looks like only sbt behaves the way I described on the second point. It could be nice if beakerx printed the error message you referenced. The thing that really caught me off guard was that I didn't know it was caching the absence of the artifact and it took me awhile to figure that out. Printing the message above would help with that

**Comment by scottdraves** [comment]
Hey guys thanks for your research and ideas on how to handle caching of missing mvn packages.
I will look into this more when I get back from holiday and make a plan, it sounds like better error messages and a way to access the "update snapshot" option would do it.  any other options that would be useful?

Ben does this mean you are publishing and consuming locally as we discussed once before, or is this going through maven central?

As for permanent caching, we discussed this at https://github.com/twosigma/beakerx/issues/6340
and implemented the cache in the conda environment, though this hasn't been released yet.
Further work on locking for the cache is happening on https://github.com/twosigma/beakerx/issues/6497

**Comment by benmccann** [comment]
I'm not sure why Maven bothers caching missing artifacts. A user isn't likely to have many missing and if one's missing they need to fix something, which is either changing the artifact specified or publishing the artifact. I just don't see the benefit of caching misses. It might be a far easier fix to just turn off caching of misses than providing an "update snapshot" option

I'm still going through Maven Central. I wasn't sure that publishing and consuming locally was supported yet. I can't think of any other options that would be useful.

**Comment by jpallas** [comment]
I'm not sure either why Maven caches missing artifacts.  The explanation in [MNG-4343](https://issues.apache.org/jira/browse/MNG-4343) (which seems to be the JIRA nexus for this feature) is pretty vague ("does not have noticeable performance impact on regular maven cli builds … does cause significant performance problems in embedding applications … in some scenarios").  

I think it only affects release artifacts, not snapshots, so there's that.  Don't try to rely on releases that haven't been published?  That's still not very forgiving of errors.  I'm not at all certain that it's possible to turn off _only_ caching of misses, though.

**Comment by scottdraves** [comment]
Then maybe -U should be the default.

**Comment by benmccann** [comment]
Making `-U` the default sounds like it could work well
