### ISSUE TITLE
Right-click menu interferes with box zoom functionality

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6574]
http://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/groovy/Charting.ipynb#Navigation says:

>Box Zoom
You can zoom to a selected rectangle region. Right click the mouse and drag out the box you’d like to zoom into. You do NOT necessarily need to drag the box from the left-top to the bottom-right. Any direction will do

The issue I'm having is that when you right click it pops up a menu with the options:

* Save as SVG
* Save as PNG
* Save as PNG as high DPI...

**Comment by scottdraves** [comment]
Just a click should bring up the menu.  Click and drag to zoom.  I can't test it right now...

**Comment by scottdraves** [comment]
we had this bug before https://github.com/twosigma/beakerx/issues/5605

**Comment by benmccann** [comment]
@mjurowicz-xsolve it looks like maybe there's been a regression in this issue you fixed previously

**Comment by scottdraves** [comment]
@EfimovVladimir need a test for this one

**Comment by EfimovVladimir** [comment]
yes, bug #5605 is reproduce again
