### ISSUE TITLE
Zoom the x-axis and scale the y-axis

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6575]
Zooming in zooms equally on the x and y axes. It would be nice if it zoomed the x-axis and then rescaled the y-axis according to the values showing on the chart. This is how most charts I've seen such as Yahoo Finance or Google Finance work

I have a chart with many small values on the left and then some large values on the right. I want to zoom in on the left to see those values. The problem is that they still remain tiny after zooming because the y-axis remains scaled for the largest values in the chart which are no longer showing

**Comment by scottdraves** [comment]
interesting idea, will have to experiment with that.  for now, you can zoom differently in x and y by moving the mouse over an axis and then zooming to apply it just to that axis.  but for time plots at least doing it automatically seems like a win, as long as it is not too jarring.
