### ISSUE TITLE
Can I install BeakerX without conda? 

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#6576]
Are there corresponding pip packages?

**Comment by scottdraves** [comment]
Yes, just run 'beakerx-install' to finish the job.

**Comment by dclong** [comment]
@scottdraves Thank you! I just found the official documentation which is clear and simple to follow. The doc in this repository needs update.

**Comment by scottdraves** [comment]
You are very welcome, glad to hear it.
The repository is for developers, and so far we don't have a process for developers without conda.
Users should be fine with just pip though.
