### ISSUE TITLE
Doc on magics

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#6577]
Is there any doc on magics? The links in StartHere.ipynb are broken.

**Comment by scottdraves** [comment]
Hi thanks for the report, but I can't find the bad links.
I just tested master and seemed fine, and the online version is also fine: 
http://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/StartHere.ipynb

**Comment by dclong** [comment]
I use the notebook below. It seems that links in sometimes work sometimes not. 

https://github.com/twosigma/beakerx/blob/master/StartHere.ipynb

Thank you for letting me know the online version. It works well.

**Comment by scottdraves** [comment]
Hm that sounds super weird that a link would work only sometimes.
When it doesn't work, is there an error?

**Comment by jmsdnns** [comment]
It seems I can reproduce the broken link. Looks like something about how Github is rendering the notebook.

If I click one of the links in the notebook @dclong linked to above, I get sent to a URL, like this https://render.githubusercontent.com/view/doc/python/PlotJSAPI.ipynb, and the page simply says _"Unknown type"_

**Comment by scottdraves** [comment]
interesting, if i click on that link i get that "unknown type", but not if i click on a link in the original notebook.  however, when i hover over the links in the original notebook i do see a link with githubusercontent.com like you say, not github.com.  i would guess this s a problem with how github is handling ipynb files.
