### ISSUE TITLE
Can SQL results be used in other programming languages?

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#6578]
e.g., Python, Scala, etc.

There's a simple example in Sql.ipynb, but it's for %%javascript. I tried %%python, %%scala, etc. but failed. It seems that there are no such magics for python and scala? Is there doc on this?

**Comment by scottdraves** [comment]
Correct there are not yet such magics.  This is the part of Beaker Notebook that is going to take the longest to port to Jupyter.  See https://github.com/twosigma/beakerx/issues/5039 and https://github.com/twosigma/beakerx/issues/6279

**Comment by dclong** [comment]
Thank you, @scottdraves! I'm watching the 2 issues.
