### ISSUE TITLE
Failed to install BeakerX for JupyterLab

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#6579]
Below is the error message.

[91m> /usr/local/bin/npm pack @jupyter-widgets/jupyterlab-manager 
[0m jupyter-widgets-jupyterlab-manager-0.32.3.tgz 
[91m "@jupyter-widgets/jupyterlab-manager@0.32.3" is not compatible with the current JupyterLab 

Conflicting Dependencies: 
JupyterLab                            Extension                        Package 
>=0.13.1-0 <0.14.0-0         >=0.14.1-0 <0.15.0-0       @jupyterlab/application 
>=0.13.0-0 <0.14.0-0        >=0.14.1-0 <0.15.0-0       @jupyterlab/rendermime 
>=0.13.0-0 <0.14.0-0        >=1.0.1-0 <2.0.0-0           @jupyterlab/coreutils 
>=0.4.3-0 <0.5.0-0           >=1.0.1-0 <2.0.0-0           @jupyterlab/rendermime-interfaces 
>=0.52.0-0 <0.53.0-0       >=1.0.1-0 <2.0.0-0           @jupyterlab/services 
>=0.13.0-0 <0.14.0-0        >=0.14.1-0 <0.15.0-0       @jupyterlab/notebook

**Comment by scottdraves** [comment]
Hey Ben thanks for letting us know.  I will try this when I get back to my workstation, I am still on holiday.
As I am sure you know, Jupyter Lab is evolving rapidly and we have had to make updates to continue to work with it.

**Comment by dclong** [comment]
There's no hurry. Please take your time. Hopefully JupyterLab releases beta soon and things become a little easier for extension developers.

**Comment by scottdraves** [comment]
When I run our Jupyter Lab install instructions:
```
conda create -y -n labx 'python>=3'
source activate labx
conda install -y -c conda-forge jupyterlab beakerx
```

 I am actually getting this error:
```
pkg_resources.DistributionNotFound: The 'pytest; python_version >= "3.4" or python_version == "2.7" and extra == "test"' distribution was not found and\
 is required by jupyter-client
```
well before I get to installing the lab extension, so something more serious has gone wrong.
the error i am seeing is actually like something we have been getting from conda-forge CI:
https://github.com/conda-forge/beakerx-feedstock/pull/14

so we are looking into that.

can you give a more complete set of commands to reproduce what you are seeing?

**Comment by scottdraves** [comment]
OK so @jmsdnns solved that one: just `conda install pytest`.

and now I see an error like yours:
```
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
> /usr/local/bin/npm pack @jupyter-widgets/jupyterlab-manager
jupyter-widgets-jupyterlab-manager-0.32.3.tgz

"@jupyter-widgets/jupyterlab-manager@0.32.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab                        Extension            Package
>=0.13.1-0 <0.14.0-0              >=0.14.1-0 <0.15.0-0 @jupyterlab/application
>=0.13.0-0 <0.14.0-0              >=1.0.1-0 <2.0.0-0   @jupyterlab/coreutils
>=0.13.0-0 <0.14.0-0              >=0.14.1-0 <0.15.0-0 @jupyterlab/notebook
>=0.13.0-0 <0.14.0-0              >=0.14.1-0 <0.15.0-0 @jupyterlab/rendermime
>=0.4.3-0 <0.5.0-0                >=1.0.1-0 <2.0.0-0   @jupyterlab/rendermime-interfaces
>=0.52.0-0 <0.53.0-0              >=1.0.1-0 <2.0.0-0   @jupyterlab/services
```

**Comment by scottdraves** [comment]
https://github.com/jupyterlab/jupyterlab/issues/3215

**Comment by scottdraves** [comment]
doc updated:
https://github.com/twosigma/beakerx-www/commit/9f50cc8288c6c3be12b42eef415cc5d75d58f171

ben, please LMK if that works for you.
