### ISSUE TITLE
Error: Class jupyter.widget not found in registry

### ISSUE THREAD

**Issue by beaumoaj** [twosigma/beakerx#6582]
[firstJava.ipynb.zip](https://github.com/twosigma/beakerx/files/1600222/firstJava.ipynb.zip)

When I try to display a chart from Java, I get an error and nothing displays. I have attached the notebook which has code from your Java documentation, I modified it from "return p;" to have "p.display();" which I believe should display the chart, but instead nothing is shown.

[localhost-1514980563624.log](https://github.com/twosigma/beakerx/files/1600212/localhost-1514980563624.log)

**Comment by scottdraves** [comment]
Thanks for the report.  How did you install BeakerX and what version do you have?

**Comment by beaumoaj** [comment]
I installed BeakerX today using pip (for python3) following the two-line instructions on your website and ran it from the command line using "jupyter notebook" to create a new notebook.  The version appears to be 0.10.0

I'm running it on Ubuntu 16.04.

**Comment by scottdraves** [comment]
@jmsdnns

**Comment by scottdraves** [comment]
what version of ipywidgets do you have?

**Comment by scottdraves** [comment]
and widgetsnbextension

**Comment by beaumoaj** [comment]
I have...

Name: ipywidgets
Version: 7.1.0
Summary: IPython HTML widgets for Jupyter

Name: widgetsnbextension
Version: 3.1.0
Summary: IPython HTML widgets for Jupyter

**Comment by jmsdnns** [comment]
I took a look and am not able to reproduce.

## Trying To Reproduce

I tested by creating a fresh virtualenv and installed beakerx using the two commands in our docs (as you said you did). _I use virtualenv and virtualenvwrapper when I'm not using conda. virtualenvwrapper provides the `mkvirtualenv` and `workon` commands you see below._

```
$ mkvirtualenv -p /usr/bin/python3 bx.test
$ workon bx.test
(bx.test) $ pip install beakerx
(bx.test) $ beakerx-install
(bx.test) $ jupyter notebook
```

I then ran your notebook and it produced a nice graph. I also tried creating the notebook from scratch and then brought your code into a fresh notebook. Alas, everything worked that way too.

## More Info

It would be helpful to us to get more info.

First, let's make sure all of the notebook extensions are shown. Run `jupyter nbextension list` and you should get output like below.

```
$ jupyter nbextension list
Known nbextensions:
  config dir: /home/jmsdnns/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /home/jmsdnns/.virtualenvs/bx.test/etc/jupyter/nbconfig
    notebook section
      beakerx/extension  enabled 
      - Validating: OK
    tree section
      beakerx/tree  enabled 
      - Validating: OK
```

We can determine what python packages you have installed with `pip freeze`. My minimal install for beakerx looks like below.

```
$ pip freeze
beakerx==0.10.0
bleach==2.1.2
decorator==4.1.2
entrypoints==0.2.3
html5lib==1.0.1
ipykernel==4.7.0
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.0
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.1
jupyter-core==4.4.0
MarkupSafe==1.0
mistune==0.8.3
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.2.2
numpy==1.13.3
pandas==0.22.0
pandocfilters==1.4.2
parso==0.1.1
pexpect==4.3.1
pickleshare==0.7.4
pkg-resources==0.0.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
python-dateutil==2.6.1
pytz==2017.3
pyzmq==16.0.3
simplegeneric==0.8.1
six==1.11.0
terminado==0.8.1
testpath==0.3.1
tornado==4.5.2
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.0
```

The log file you sent appears to correlate with people who have conflicting versions of some libraries, widget related stuff in particular. I would like to either determine that's it and upgrade your libraries or rule this out and continue debugging.

Please attach the output of both commands and we'll go from there.

**Comment by beaumoaj** [comment]
Ok.  I have some differences.   In the first output, I am missing the jupyter-js-widgets/extension:
**jupyter nbextension list**
Known nbextensions:
  config dir: /usr/etc/jupyter/nbconfig
    notebook section
      beakerx/extension  enabled 
      - Validating: OK
    tree section
      beakerx/tree  enabled 
      - Validating: OK

In the second output, the differences I can see are: 
Jinja2==2.8 (you have 2.10),
jupyter-client==5.2.0 (you have 5.2.1), 
MarkupSafe==0.23 (you have 1.0), 
numpy==1.12.1 (you have 1.13.3), 
pexpect==4.0.1 (you have 4.3.1), 
I am missing pkg-resources==0.0.0, 
ptyprocess==0.5 (your 0.5.2), 
python-dateutil==2.6.0 (your 2.6.1), 
pytz==2017.2 (yours is  2017.3), 
six==1.10.0 (yours 1.11.1)

The full output from my version is: **pip3 freeze**
appdirs==1.4.3
apturl==0.5.2
beakerx==0.10.0
beautifulsoup4==4.4.1
bleach==2.1.2
blinker==1.3
Brlapi==0.6.4
chardet==2.3.0
checkbox-support==0.22
command-not-found==0.3
cryptography==1.2.3
cycler==0.10.0
decorator==4.1.2
defer==1.0.6
entrypoints==0.2.3
feedparser==5.1.3
guacamole==0.9.2
html5lib==1.0.1
httplib2==0.9.1
idna==2.0
ipykernel==4.7.0
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.0
jedi==0.11.1
Jinja2==2.8
jsonschema==2.6.0
jupyter-client==5.2.0
jupyter-core==4.4.0
language-selector==0.1
louis==2.6.4
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
matplotlib==2.0.2
mistune==0.8.3
mysqlclient==1.3.10
nbconvert==5.3.1
nbformat==4.4.0
nltk==3.2.4
notebook==5.2.2
numpy==1.12.1
oauthlib==1.0.3
onboard==1.2.0
packaging==16.8
padme==1.1.1
pandas==0.22.0
pandocfilters==1.4.2
parso==0.1.1
pdfminer3k==1.3.1
pexpect==4.0.1
pickleshare==0.7.4
Pillow==3.1.2
plainbox==0.25
ply==3.10
prompt-toolkit==1.0.15
ptyprocess==0.5
py==1.4.33
pyasn1==0.1.9
pycups==1.9.73
pycurl==7.43.0
Pygments==2.2.0
pygobject==3.20.0
PyJWT==1.3.0
PyMySQL==0.7.11
pyparsing==2.2.0
pytest==3.0.7
python-apt==1.1.0b1
python-dateutil==2.6.0
python-debian==0.1.27
python-ly==0.9.3
python-poppler-qt4==0.24.0
python-systemd==231
pytz==2017.2
pyxdg==0.25
pyzmq==16.0.3
reportlab==3.3.0
requests==2.9.1
scikit-learn==0.19.1
scipy==1.0.0
screen-resolution-extra==0.0.0
sessioninstaller==0.0.0
simplegeneric==0.8.1
six==1.10.0
sklearn==0.0
ssh-import-id==5.5
system-service==0.3
terminado==0.8.1
testpath==0.3.1
tornado==4.5.2
traitlets==4.3.2
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.13.1
usb-creator==0.3.0
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.0
xdiagnose==3.8.4.1
xkit==0.0.0
XlsxWriter==0.7.3

**Comment by beaumoaj** [comment]
I have now installed jupyter-js-widgets/extension and the problem is fixed.  Thanks for your help.

**Comment by jmsdnns** [comment]
Great news and happy to be helpful!
