### ISSUE TITLE
document mvn caching

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6583]
https://github.com/twosigma/beakerx/issues/6340
location of cache, as well as how to override it with an envar.

**Comment by benmccann** [comment]
Is it possible for me to publish a jar locally from another project and then consume it in Beakerx with the recent Maven improvements?

**Comment by holgerbrandl** [comment]
I'd also be curious about such a feature. With https://github.com/ligee/kotlin-jupyter it's possible to use gradle like locators to fetch maven artifacts (including sub-dependencies if present) with
```kotlin
@file:DependsOnMaven(“de.mpicbg.scicomp:krangl:0.7”)

import krangl.*

irisData.glimpse()
```
I wonder if  a similar functionality is planned for beakerx or already built-in?

**Comment by scottdraves** [comment]
Hi Holger thank you for your question.
BeakerX has maven support via a magic `@classpath add mvn`, see http://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/groovy/ClasspathMagicCommands.ipynb

What Ben is asking for (?) is the ability to load not from maven central but a local package under development.

That's something I would like to support but I don't fully understand it yet.
If kotlin-jupyter does that I would like to know how, or if anyone can specify the needed API or magic then I can look into making it happen.

**Comment by scottdraves** [comment]
That said, there seems to be a problem loading your library:
https://github.com/twosigma/beakerx/issues/6979
I think we have already seen this bug and I expect it to be addressed shortly.

**Comment by scottdraves** [comment]
@benmccann can you say exactly what you mean by "publish a jar locally"? https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html ?

**Comment by benmccann** [comment]
Usually I'm installing a first party jar locally (vs a 3rd party jar as mentioned in that article). I.e. I'm developing a library and want to see the latest changes in BeakerX by running `mvn install`, `gradle publishToMavenLocal`, or `sbt publishLocal`

**Comment by jpallas** [comment]
@benmccann Per the discussion at [#6340](https://github.com/twosigma/beakerx/issues/6340#issuecomment-347042528) I think this does what you want:
```
%classpath config resolver local file:/Users/joe/.m2/repository
```
… with the understanding that, unless your artifact is versioned as a `SNAPSHOT`, you will not be able to get the latest changes unless you manually clear the BeakerX maven cache.

**Comment by holgerbrandl** [comment]
How can I clear the beakerx cache?

**Comment by scottdraves** [comment]
Currently you would have to do it manually,
```
rm -rf $CONDA_PREFIX/share/beakerx/maven
```
and then restart your kernel.  but yea there should be a magic for this, one that removes any repos as well: https://github.com/twosigma/beakerx/issues/6987.

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beakerx/issues/6994

**Comment by scottdraves** [comment]
include `%classpath config resolver mvnLocal`

**Comment by holgerbrandl** [comment]
Cool thanks!

**Comment by benmccann** [comment]
@jpallas yes, that looks like it would do what I want. Though the last comment from @scottdraves looks like an even nicer way to do that

Typically that's done automatically when using Maven, SBT, etc. and doesn't require an extra step from the user. It would be nice to consider including the local repo by default

**Comment by meta-forte** [comment]
beakerx does not seem to honour my .m2/settings.xml configuration
It is downloading to C drive only, even though I configured to use D drive
```XML
<settings  xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository>d:/Users/me/.m2/repository</localRepository>
</settings>

````
