### ISSUE TITLE
allow publishing non-anonymously

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6594]
the publish dialog, instead of just supporting anonymous gists, should support using your regular github identity via oauth.

**Comment by MariuszJurowicz** [comment]
@scottdraves 

As i understood, to allow users for publishing gists into their accounts we need to register an app in github that will request for the `gists` oAuth scope.
To register the app we need to provide the:

- full URL to the application homepage,
- Authorization callback URL that can be changed by `redirect_uri` paramenter in the request.

The flow looks like we need to redirect to github page for authentication and the we are redirected back to our beakerx page with the `code` data that can be exchanged to `access_token`.
This token has to be used to sign the `/gists` POST call.

- who should register the app and provide such data,
- how should the configuration look like and where it should be kept,
- is it possible to redirect to dynamic url with different port like eg. in our local instances?
- is this solution secure enough like eg. what if someone's beakerx instance requests for different scopes and use it for some illegal actions? Should we even care about that?
  
We can also request in pop up for the user's Personal Access Token that is configured for `gists` scope and use it to sign up the creating gist request.

**Comment by jmsdnns** [comment]
OAuth wouldn't make sense for us as we don't have a concept of user accounts in BeakerX.

Personal Access Tokens are the right approach here.
