### ISSUE TITLE
Disconnecting from server causes issues

### ISSUE THREAD

**Issue by planyon** [twosigma/beakerx#660]
After being disconnected from beaker server, opening a notebook takes the user to the plugin manager page. I expected an error message if the notebook could not be opened.

**Comment by scottdraves** [comment]
Hi, thanks for the bug report.
What exactly do you mean "after being disconnected"?  What happened?
What URL did you reconnect to?  Then what exact buttons/menus did you click?

**Comment by planyon** [comment]
I had left Beaker running for about a day and when I opened my tab I received pop up that said Beaker had been disconnected from the server. I clicked OK. Then I went to my list of notebooks and when I opened the only notebook in my list, I was taken to the plugin manager page.

**Comment by scottdraves** [comment]
could not reproduce
