### ISSUE TITLE
Bug in table widget sorting feature

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6609]
Load a table with the line of code below:

```
tenYr = Table.read().html("http://www.multpl.com/10-year-treasury-rate/table/by-month");
```

Now sort by date ascending. You get the dates:
* 1970-01-01
* 1810-01-01
* 1810-02-01
* 1810-03-01
* 1810-04-01
.
.
.

**Comment by scottdraves** [comment]
thank you ben!

**Comment by benmccann** [comment]
I should clarify that this requires loading the tablesaw jars first. There's an example in the docs

**Comment by MariuszJurowicz** [comment]
@benmccann 
Can you reproduce this bug? I need more info as when i'm running the `TableSaw` example and the adding the cell `tenYr = Table.read().html("http://www.multpl.com/10-year-treasury-rate/table/by-month");`
the result seems just fine:

![sortresult](https://user-images.githubusercontent.com/7079774/34666343-1dfc932e-f464-11e7-860f-81f63f1e2fb4.png)

**Comment by scottdraves** [comment]
After loading the table, click the header of the date column to sort it.

**Comment by scottdraves** [comment]
I'm getting a different result.

**Comment by scottdraves** [comment]
<img width="331" alt="screen shot 2018-01-08 at 8 06 45 am" src="https://user-images.githubusercontent.com/963093/34672016-ccf763b4-f44a-11e7-9019-ad6f2dfd6f38.png">

**Comment by scottdraves** [comment]
confirmed on another computer (both are mac if that matters).

**Comment by MariuszJurowicz** [comment]
Maybe this date value is null or 0 or some other non date value and formatted by moment gives the `1970-01-01` but sorting function takes not formatted value for caculations.

**Comment by scottdraves** [comment]
csv file written looks like:
```
"Date","Value Value"
"1970-01-01","7.79%"
"1871-01-01","5.32%"
"1871-02-01","5.32%"
"1871-03-01","5.33%"
"1871-04-01","5.33%"
"1871-05-01","5.33%"
```

**Comment by scottdraves** [comment]
Ben, I tried
```
tenYr.exportToCsv("/tmp/tenYr.csv")
```
to debug this but I get an error
```
groovy.lang.MissingMethodException: No signature of method: tech.tablesaw.api.Table.exportToCsv() is applicable for argument types: (java.lang.String) values: [/tmp/tenYr.csv]
	at script15154265520491933561977.run(script15154265520491933561977.groovy:1)
	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.run(GroovyCodeRunner.java:71)
```
i found this method in:
https://github.com/jtablesaw/tablesaw/blob/master/docs/gettingstarted.md

**Comment by benmccann** [comment]
I'll update that page. It should be:

    tenYr.write().csv("/tmp/tenYr.csv")

**Comment by scottdraves** [comment]
that works thanks.  in the middle of the table i see
```
1970-04-01,7.39%
1970-03-01,7.07%
1970-02-01,7.24%
1970-01-01,7.79%
1969-12-01,7.65%
1969-11-01,7.14%
1969-10-01,7.10%
1969-09-01,7.16%
```
so it appears this row is in the original data, not the result of a 0.

**Comment by scottdraves** [comment]
Why is mariusz seeing "Apr" and we are getting the numeric view??

**Comment by MariuszJurowicz** [comment]
I think it's caused by my locale (`pl`). Moment takes different formats for different locales.
That is why i'm getting the date values in strings as `Apr 1, 1981` and that is why i can't reproduce this bug this way.
But i've tried to use the prepared `csv` data file with the data you are using and I can reproduce this bug:
![zrzut ekranu z 2018-01-09 11-36-12](https://user-images.githubusercontent.com/7079774/34716889-820feed8-f531-11e7-9322-517e872554ac.png)

**Comment by MariuszJurowicz** [comment]
This is a DataTables.net bug of sorting formatters. When DataTables processes the table sort by this column it uses the `date-pre` formatter for retrieving the sort data:
```
		"date-pre": function ( d ) {
			return Date.parse( d ) || -Infinity;
		},
```
And if the formatted string is the `1970-01-01` the `Date.parse('1970-01-01')` returns `0` so the formatter returns the `-Infinity`. That is why this row will be always first or last.

https://github.com/DataTables/DataTablesSrc/issues/114

**Comment by benmccann** [comment]
Thanks for tracking this down!! I've sent them a PR with the fix

**Comment by benmccann** [comment]
The fix has been merged. Now we'll just need to wait for them to cut a new release, which they've said they expect to happen in February

**Comment by scottdraves** [comment]
wow awesome
