### ISSUE TITLE
easyform h checkbox labels vanish on narrow window

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6610]
<img width="682" alt="screen shot 2018-01-08 at 12 02 08 am" src="https://user-images.githubusercontent.com/963093/34659495-41773582-f407-11e7-8ad3-6701097c0c68.png">

**Comment by piorek** [comment]
![zrzut ekranu z 2018-01-12 13-49-07](https://user-images.githubusercontent.com/743617/34875910-804ae97a-f79f-11e7-8d32-570db3b7806c.png)

Can't reproduce this on 3 different browsers (Vivaldi/Firefox/Chrome)
For me there is horizontal scroll
