### ISSUE TITLE
support windows in doc

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6636]
on windows we should use `activate beakerx` not `source activate beakerx`

**Comment by EfimovVladimir** [comment]
https://conda.io/docs/user-guide/tasks/manage-environments.html#activating-an-environment

**Comment by jaroslawmalekcodete** [comment]
we should update our README by windows 
``` 
conda create -y -n beakerx python>=3 nodejs pandas openjdk=8.0.121 maven py4j requests
activate beakerx
conda config --env --add pinned_packages openjdk=8.0.121
conda install -y -c conda-forge ipywidgets
cd beakerx
pip install -e . --verbose
cd ..
beakerx install
```

**Comment by altavir** [comment]
On windows it won't work either way since `cmd` is deprecated and conda does not support `activate` for PowerShell. The issue is here: https://github.com/conda/conda/issues/626.
