### ISSUE TITLE
Is it possible to change logging level

### ISSUE THREAD

**Issue by jarutis** [twosigma/beakerx#6643]
Hi,

At the moment logging level is set to INFO. Using Spark this outputs a lot of information in the notebook. Is it possible to change the logging level at runtime?

I tried Sparks `spark.sparkContext.setLogLevel("ERROR")` but it didn't worked.

Thanks,

Jonas

**Comment by scottdraves** [comment]
hi thanks for writing Jonas, I agree there's too much log output from Spark.
We will look into how to fix that.

**Comment by jarutis** [comment]
It would be nice if logs would be printed to javascript console instead of output cell. Spark Notebook was done in such way, it was very convenient. Lots of logs is not a problem that way.

**Comment by scottdraves** [comment]
Hey that's an interesting idea, thanks!

Maybe the Output widget could be used to capture the logs.
And maybe Output widget could have an option to direct to JS console....

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/issues/6829
