### ISSUE TITLE
kernel-bond Java processes do not exit while python3 kernel restart

### ISSUE THREAD

**Issue by mirokymac** [twosigma/beakerx#6646]
OS: Ubuntu 16.04.3 LTS (GNU/Linux 2.6.32-042stab126.2 x86_64)
With python3.6.4 and anaconda 4.4.7, BeakerX version 0.11.0.

I have used version 0.10.0 on my server. This morning, I came across an issue that the Python kernel always dead and could not restart. After check, when the Python kernel stopped, the Java threads remained in system and consumed all the memory.

I update to 0.11.0, the issue remains.

**Comment by jmsdnns** [comment]
Could you provide steps for reproducing this please? Specifically, anything you did with java before your system got in this state.

**Comment by scottdraves** [comment]
might have been this: https://github.com/twosigma/beakerx/issues/6832
