### ISSUE TITLE
EasyForm List doesn't interact from code

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#6648]
create list:
`f6 = new EasyForm("form6")`
`f6.addList("field name6", ["one", "two", "three"])`
`f6`
try to select value by code:
`f6['field name6'] = 'three'`
Expected result: the value should be selected on the List

![image](https://user-images.githubusercontent.com/17744188/34869405-dc22c842-f797-11e7-8c22-d235a26938a1.png)

**Comment by scottdraves** [comment]
actually it's worse, it should take a list as a value, not a string.
```
f6['field name6'] = ['three']
```
