### ISSUE TITLE
EasyForm Editable Combobox doesn't save the value

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#6649]
After we edit value on combobox this value isn't saved 
code:
`g = new EasyForm("Field Types")`
`options = ["a", "b", "c", "d"]`
`g.addComboBox("Combo Box", options)`
`g.addComboBox("Editable Combo", options, true)`
`g`
![image](https://user-images.githubusercontent.com/17744188/34870599-a5d9da74-f79b-11e7-9309-c4403d972edf.png)

Step to reproduce:
1. Edit any value.
2. Select another value.
Open combobox again and try to find that edited value

![image](https://user-images.githubusercontent.com/17744188/34875491-7e4d2df4-f7ae-11e7-8a65-c288d6951bbd.png)

reproduced for groovy kernel

**Comment by scottdraves** [comment]
working as intended
