### ISSUE TITLE
installing an R package gives error

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#666]
install.packages("corrgram")

results in 

Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
Warning in install.packages("corrgram") :
  'lib = "/usr/local/lib/R/site-library"' is not writable

with the container

**Comment by pgensler** [comment]
Are you able to install packages from base R and load them in Beaker? I know this issue is old, but I am trying to do so now with the new docker container, and am still receiving this error above.

**Comment by scottdraves** [comment]
The instructions for installing packages in the docker container are in the docker wiki: https://github.com/twosigma/beaker-notebook/wiki/Running-the-Docker-Container

**Comment by pgensler** [comment]
I see. I tried installing dplyr from CRAN into my container, and when I try to load it via the library command, I get the following error:

> Error in library.dynam(lib, package, package.lib) : 
>   shared object 'dplyr.so' not found
> In addition: Warning message:
> S3 methods '[.fun_list', '[.grouped_df', 'all.equal.tbl_df', 'anti_join.data.frame', 'anti_join.tbl_df',
>  -Error : package or namespace load failed for 'dplyr'

Am I supposed to load the package in my bash script as well? I noticed in some notebooks you can load the package in Beaker, so I'm just trying to make sure I understand this.
