### ISSUE TITLE
Make an uninstall process to restore previous environment

### ISSUE THREAD

**Issue by paulochf** [twosigma/beakerx#6667]
I remember seeing that beakerx installed some things in jupyter's folder. After doing some tests, I would like to uninstall it, but I didn't find any references to how to delete those files.

I realized that `pip uninstall beakerx` is not enough, because it left some config files behind, making old `jupyter notebook` broken.

After removing both `.jupyter` and `.ipython` config folders, I managed to get a cleaner error output.

```
$ jupyter notebook
[W 18:50:10.914 NotebookApp] Error loading server extension beakerx
    Traceback (most recent call last):
      File "python_path/lib/python3.6/site-packages/notebook/notebookapp.py", line 1343, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "python_path/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'beakerx'
[I 18:50:10.937 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.8
[I 18:50:10.997 NotebookApp] Serving notebooks from local directory: /home/paulo/Documents/work/scorer-svc
[I 18:50:10.997 NotebookApp] 0 active kernels
[I 18:50:10.997 NotebookApp] The Jupyter Notebook is running at:
[I 18:50:10.997 NotebookApp] http://localhost:8888/?token=4261729b3fb906e6e2d70259a809e4429646eec24e031792
[I 18:50:10.997 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:50:10.999 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=4261729b3fb906e6e2d70259a809e4429646eec24e031792
[I 18:50:12.073 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[14437:14477:0115/185012.104051:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.
Created new window in existing browser session.
[W 18:50:13.006 NotebookApp] 404 GET /nbextensions/beakerx/tree.js (127.0.0.1) 10.89ms referer=http://localhost:8888/tree
```

Running `jupyter notebook --debug`, I could manage to backtrack the following config files:
* `python_env_path/etc/{jupyter,ipython}`
* `python_env_path/share/jupyter/kernels/{groovy,clojure,sql,scala,java,kotlin}`
* `python_env_path/share/jupyter/nbextensions/beakerx`

As I had no previous configuration in them, I deleted all of them and then I got my Jupyter again.

**Comment by scottdraves** [comment]
if you installed with pip, then i think it's:
```
beakerx-install --disable
jupyter nbextension uninstall beakerx --py --sys-prefix
```

**Comment by scottdraves** [comment]
> beakerx-install --disable

this should run "jupyter nbextension uninstall ..." automatically, no extra cmd should be required.

**Comment by scottdraves** [comment]
beakerx-install --disable
already does that, so just need to make sure all doc/website is up to date.

**Comment by misolietavec** [comment]
I had very frustrating experience with uninstalling beakerx. What helped, was to remove the file `/usr/etc/ipython/ipython_config.py `.  Nothing from above helped. I wrote this, in case someone has similar  troubles.

**Comment by scottdraves** [comment]
Hi sorry it gave you trouble.
Can you say how you installed it, how you uninstalled it and what error did you get?

**Comment by nscozzaro** [comment]
I'm getting the following error when I try to install packages with pip after installing beakerx. The command `beakerx-install --disable` is not recognized. How can I make this error go away?

`FileNotFoundError: [Errno 2] No such file or directory: '/anaconda3/lib/python3.6/site-packages/beakerx-1.4.1.dist-info/METADATA'`
