### ISSUE TITLE
output tray should only appear for unattributed output, normal output goes into cell output

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#667]
for python and other languages where you can identify that source of stdout/stderr,
we should just put it in the output part of the cell.

as long as you only run only one cell at a time then you can do it for groovy too....

**Comment by jchendy** [comment]
The real issue with Groovy is that you can start a thread that prints to stdout after the cell has already returned. It might be possible to grab a stack trace when you receive the output and figure out which cell it belongs to?

**Comment by scottdraves** [comment]
Right that's what I mean by only one cell running at a time, ie no threads left going.

It's possible there is a JVM trick to identify the source of output.  It's worth investigating that.

But I am going to assume that's not possible.  Even so, 99% of the time I think we can avoid the tray for Groovy because:

1) for multiple notebooks at the same time you can use multiple JVMs.  That's the other way you can get output crossed currently.

2) we can't prevent or know if they are going to spawn a thread.  but at the end of evaluation, we can test if they did by asking the JVM for all stack traces.  as long as the answer is no then we can put the output in the cell.  if the answer is yes then we can pop up an alert and say "you left a thread running do you want to switch to the output tray"

The situation for R is the same as for groovy btw, just without the JVM.  there is a parallel package for forking threads.  https://stat.ethz.ch/R-manual/R-devel/library/parallel/doc/parallel.pdf

so yea there are probably people who like the output tray or need it because they are using long-running threads.  fine, let them.  make the use of the output tray an option that defaults off.

The UX of output under the input is so much better, and the case of doing this correctly is so common, I think we should make this our default.

**Comment by scottdraves** [comment]
As per https://github.com/twosigma/beaker-notebook/issues/699, when we revamp output handling, make sure that output without a newline is handled without delay.

**Comment by ildipo** [comment]
It is possible to have a per java thread System.out and System.err.
To do it you should implement our own PrintWriter and set it with System.setOut / setErr.
This PrintStream implementation should check if the current thread as registered it's own output handler using ThreadLocal<> and use that if available or output to the standard one if not.

**Comment by ildipo** [comment]
done
