### ISSUE TITLE
widgets should respect theme

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6688]
jupyter lab has a dark theme.  our widgets should work with it.

**Comment by scottdraves** [comment]
<img width="559" alt="screen shot 2018-02-03 at 7 12 06 pm" src="https://user-images.githubusercontent.com/963093/35773087-2eda1a60-0916-11e8-99bf-d4d5b76f07ed.png">

**Comment by davecazz** [comment]
Just ran into this one. was looking forward to checking out beakerx but had to uninstall at least until it works with the dark theme.
