### ISSUE TITLE
check prefs file perms on windows

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6695]
https://github.com/twosigma/beakerx/blob/master/beakerx/beakerx/install.py#L134
https://github.com/twosigma/beakerx/blob/2fb631e22191615aaae175070577b1d5c2a45455/beakerx/beakerx/environment.py#L43

we need to check if these actually work on windows.
i am pretty sure chmod is just ignored.
not sure about the os.open.

**Comment by jmsdnns** [comment]
Possibly relevant: https://stackoverflow.com/questions/12168110/setting-folder-permissions-in-windows-using-python
