### ISSUE TITLE
rename `beakerx-install` to `beakerx install`

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6697]
also support `beakerx uninstall`
`beakerx --help`
`beakerx --version`
`beakerx` by itself should be the same as `jupyter notebook`

see https://github.com/twosigma/beakerx/issues/6667

**Comment by jmsdnns** [comment]
@lmitusinski would love to catch up with you before you start. I imagine we're already thinking in the same direction, but I have some extra context I'd like to add to your thoughts.

**Comment by scottdraves** [comment]
james pointed out that argparse has support for subcommands https://docs.python.org/3.5/library/argparse.html#sub-commands

**Comment by jmsdnns** [comment]
Even though we discussed this, I'm going to add the context from our discussion here for the sake of this thread being complete to readers.

argparse calls subcommands "subparsers". You have the top level command, eg `beakerx`, and then if the next string entered matches the name of a subparser, the subparser is invoked for processing the rest of it.

Here is an example from a personal project called MarkUpUpDownDown. The top level command is here: https://github.com/MarkUpUpDownDown/markupupdowndown/blob/master/markupupdowndown/commands/__init__.py and we see that it imports other modules for the rest of the commands.

The `init_subparser` method is my own convention, so use it if you like it or don't if you prefer something else: https://github.com/MarkUpUpDownDown/markupupdowndown/blob/master/markupupdowndown/commands/push.py#L5 The main idea to take from `init_subparser` is how easy it can be to link multiple modules together into a robust command suite, should we need one.

As Scott suggested via conversation, we are probably fine with all of the commands together in a single file.
