### ISSUE TITLE
old version of JVM/openjdk being installed

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6719]
docker version has this in the log:
```

The following packages will be DOWNGRADED:

    openjdk:            8.0.152-h46b5887_1             --> 8.0.121-1
```
why??

**Comment by jaroslawmalekcodete** [comment]
Is it possible to change our installation instruction 
from 

conda create -y -n beakerx 'python>=3' nodejs pandas openjdk maven
source activate beakerx
conda install -y -c conda-forge ipywidgets

to

conda create -y -n beakerx 'python>=3' nodejs pandas
source activate beakerx
conda install -y -c conda-forge ipywidgets openjdk maven

?

**Comment by scottdraves** [comment]
please apply this to docker version

**Comment by scottdraves** [comment]
we could but that doesn't leave us with 8.0.152....

**Comment by jaroslawmalekcodete** [comment]
As I understand if we decide to use conda-forge the newest version will be 8.0.144
```conda search openjdk --channel conda-forge```
![openjdk_conda-forge](https://user-images.githubusercontent.com/21952713/36658683-fe9b97fc-1ad1-11e8-93f9-0b74d843f68f.png)

**Comment by scottdraves** [comment]
```
conda create -y -n testx 'python>=3' openjdk
conda activate testx
conda install -c conda-forge bleach
```
reproduces the same problem.
seems like this is a bug in conda or we need some option to suppress this bogus behavior.
downgrading makes no sense.
https://github.com/conda/conda/issues/6948

**Comment by scottdraves** [comment]
The upshot is we should say:
```
conda create -y -n beakerx 'python>=3' nodejs pandas openjdk maven
source activate beakerx
conda config --env --add pinned_packages 'openjdk >8.0.121'
conda install -y -c conda-forge ipywidgets
```

**Comment by scottdraves** [comment]
Docker done, should also add to both user and dev docs.
