### ISSUE TITLE
Inserting/Deleting a Section Header near the top of notebook jumps to some point near the mid/end of the notebook

### ISSUE THREAD

**Issue by melmac48** [twosigma/beakerx#672]
See the example notebook "Parking Tickets" for repro steps.
Instert a H2 after the very first heading
Screen moves to the middle of the notebook

**Comment by scottdraves** [comment]
yea i have seen this

**Comment by scottdraves** [comment]
we also have a problem when notebooks are opened, they sometimes start out scrolled in the middle.
there is a hack in the code to prevent this but perhaps it does not cover all cases?
