### ISSUE TITLE
make a demo of STIL integration (astronomy formats)

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6722]
http://www.star.bristol.ac.uk/~mbt/stil/

**Comment by scottdraves** [comment]
https://github.com/Starlink/starjava

**Comment by mbtaylor** [comment]
I'm author of starjava/stil/stilts, and looking at integrating them somehow or other with Jupyter has been on my to-do list for a while, but I'm not sure (a) how to get started or (b) how useful it would actually be.

It's still not close enough to the top of my to-do list to actually get down to doing it, but if any jupyter/beakerx expert wants to have a go, I'm very willing to pitch in with advice or assistance from the stilts/starjava side.

There is already a jython front-end to stilts (http://www.starlink.ac.uk/stilts/sun256/jystilts.html), which can pop up interactive plots, amongst a load of other table operations.  From a user-interface point of view that would be a good starting point.  

Thanks to @maartenbreddels for pointing me at this.

**Comment by scottdraves** [comment]
Hi Mark great to hear from you.  Getting STIL to load was easy since you provide a jar. I just ran
```
%classpath add jar stil.jar
```
then I was then able to call `makeStarTable()` but I don't have a file to read.  Will definitely pursue this further, and report back here.

Indeed thank you Maarten for the intro.

**Comment by mbtaylor** [comment]
Plenty of data files to choose from.  You probably have or can find some CSV files lying around; a couple of medium-sized astronomy FITS files (more efficient) if you want them are ftp://andromeda.star.bris.ac.uk/pub/star/data/dr5qso.fits, http://andromeda.star.bristol.ac.uk/data/tgas_source.fits.

**Comment by scottdraves** [comment]
Cool, CSV works: https://nbviewer.jupyter.org/gist/anonymous/6f68bb70a73945aaea5b94c650fbb28d

Will see about writing an adaptor so the tables are displayed with our GUI automatically.

**Comment by scottdraves** [comment]
here's a live demo:
https://mybinder.org/v2/gh/twosigma/beakerx/0.12.1?filepath=doc%2Fgroovy%2FSTIL.ipynb
