### ISSUE TITLE
Clicking the first few columns of text in a text cell doesn't place the cursor in it

### ISSUE THREAD

**Issue by melmac48** [twosigma/beakerx#673]
Repro steps
Create a new text cell
type a few words in it
click out of the cell (as in, put the cursor into another cell)
try clicking of the first few letters in the text cell - the cursor should be positioned next to them, but it isn't. It doesn't get positioned until you're about three or four characters in from the left margin.

**Comment by buob** [comment]
This would appear to be fixed, could you confirm?

**Comment by scottdraves** [comment]
still see it

**Comment by buob** [comment]
The element that has padding isn't a block level element, and if you make it block it increases the padding on the left and right as well as the top and bottom, like so:

![image](https://cloud.githubusercontent.com/assets/986404/5729567/463431a0-9b41-11e4-85c2-21c4563f1ddf.png)

Do we want it to look like that or like it currently looks... 

![image](https://cloud.githubusercontent.com/assets/986404/5729574/53def7b8-9b41-11e4-9dbd-7499ac18bacc.png)

**Comment by buob** [comment]
The design has the former, so I'm going to do that :+1:

**Comment by buob** [comment]
Actually I'm not -- it would affect sections as well.  I'll keep it looking as it does now. :+1: :+1:
