### ISSUE TITLE
update values in TableDisplay without reinstantiation

### ISSUE THREAD

**Issue by themeshter** [twosigma/beakerx#6730]
I am trying to use TableDisplay as part of an interactive Python cell. All is good so far - values get displayed as I want them to, so no concerns there.
The values in the table should change based on some user input - so the problem that I have is that I would like to programatically update the values without reinitializing the TableDisplay object?
 
I looked over the documentation and the only examples I found are based on constructing the table with the values preinitialized and then using it do display. Is it any example that shows how can you update the values or this feature is not supported? If this is not supported, can you point me out to what the best practice would be in this scenario (refreshing the data in a component)?

**Comment by scottdraves** [comment]
Hi thanks for the question.  That should be possible, there is no direct documentation of that though, you are right.  Check out the use of `setDoubleClickAction` though, it does it.  I will look into expanding the doc on this point.

**Comment by scottdraves** [comment]
this would be a nb like doc/groovy/PlotsPythonStyle.ipynb but that changes numeric and string values in the table.

**Comment by scottdraves** [comment]
we have this for groovy, need it for python now too.
