### ISSUE TITLE
didn't we move this to the conda env?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6733]
<img width="923" alt="screen shot 2018-01-27 at 1 29 42 pm" src="https://user-images.githubusercontent.com/963093/35475086-31640a58-0366-11e8-9bc5-464d90880805.png">

"mvnJars" should be in the conda env, not in java tmp, didn't that happen back in https://github.com/twosigma/beakerx/commit/5966d860d5ecece147a1e751156781b1cc44d72d?

**Comment by jaroslawmalekcodete** [comment]
here https://github.com/twosigma/beakerx/commit/5966d860d5ecece147a1e751156781b1cc44d72d we moved maven cache from tmp to conda env (EnvCacheFolderFactory.class), but maven magic command uses tmp folder to put jars on classpath https://github.com/twosigma/beakerx/blob/master/kernel/base/src/main/java/com/twosigma/beakerx/kernel/magic/command/MagicCommandTypesFactory.java#L125 . As I understand maven cache works for all notebooks but tmp folder "classpath"  is per notebook.
