### ISSUE TITLE
make groovy stack traces easier to read

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6737]
many of the lines do not refer to the users groovy code, but to the java implementation.
these can be really useful but the most likely the user wants to know about their own code.
can the lines from just the interpreter be made bold?

in the below example, only the last 2 lines would not be bold:

![screen shot 2018-01-29 at 5 45 40 pm](https://user-images.githubusercontent.com/963093/35538531-3e5c0a5a-051c-11e8-838b-893a6fdeffe9.png)

**Comment by scottdraves** [comment]
More precisely, only the lines that go through run and doCall should be bold.

and those lines should be rewritten to just say "at this Jupyter code cell, line Y" if it is this cell (check the long number).  or  "at another Jupyter code cell X, line Y"

in order to identify X, every time we run a cell we have to keep track of the mapping from the long number to the cell sequence number shown in the UI at In[X].

**Comment by dsblank** [comment]
Instead of making the user code bold, what if you made the system lines collapsible/expandable and not show the non-user code initially? These stacks of system code can be really long! 

I think that there is a Python extension (or plans) to do that in IPython, which would also be a nice default for them.

**Comment by scottdraves** [comment]
agreed that's better, and we should support it at some point.  in addition, should be able to show something in the code cells themselves like a proper debugger or IDE would (highlight where it crashed).  bold is just the first little step.
