### ISSUE TITLE
D3 example does not run in Lab

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6747]
doc/python/AutoTranslation.ipynb

module system must be updated

add another `%%javascript` cell with the Lab version (keep both versions in the nb).

**Comment by piorek** [comment]
is adding 

```
%%javascript
if (!!require) {
    var s = document.createElement('script');
    s.src = '//cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.min.js';
    this.node.appendChild(s);
}
```

before 

```
%%javascript
require.config({
  paths: {
      d3: '//cdnjs.cloudflare.com/ajax/libs/d3/4.9.1/d3.min'
  }});
```

acceptable solution?

**Comment by scottdraves** [comment]
i prefer something cleaner.  what's the Jupyter Lab native way?

**Comment by piorek** [comment]
that was only way i could think of, but i'll try to find something better

**Comment by scottdraves** [comment]
sounds like it's time for https://github.com/twosigma/beakerx/issues/5567

**Comment by scottdraves** [comment]
But the workaround above isn't working for me anyway.  I just get
```
require is not defined - please check console
```

**Comment by MariuszJurowicz** [comment]
I think that we can expose the RequireJS in global scope right inside our beakerx Lab extension.
Or extend the global context with our solution for loading the js files.

I don't think that Lab has any other solution for module resolving inside a browser.
It does not use the AMD for embeding the required modules/extensions same way the Notebook does.

**Comment by scottdraves** [comment]
> I think that we can expose the RequireJS in global scope right inside our beakerx Lab extension.

this sounds fine.  i would like to get to 5567 at some point though...

**Comment by rchossein** [comment]
Could you provide a working D3 example in Jupyter Lab?
