### ISSUE TITLE
Hamburger menu is off

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#676]
This is tutorial notebook in what I think is latest RC. 

![screen shot 2014-09-22 at 10 12 26 am](https://cloud.githubusercontent.com/assets/1740497/4357629/d4b85ac8-4263-11e4-8da5-d26bebb777e9.png)

**Comment by jchendy** [comment]
Just noticed I had advanced mode on, looks fine in normal.

**Comment by scottdraves** [comment]
i was sure i had reported this before but i can't find it

**Comment by buob** [comment]
Is this the same issue as this bug (no padding for the top of a datatable) in advanced mode?

http://cl.ly/image/1Y3W3l0J4529

**Comment by scottdraves** [comment]
i am not seeing the original bug right now, so not sure if they are the same, but i am seeing the problem with the output menu overlapping the dataframe in advanced mode.

i wouldn't worry about this one now.
