### ISSUE TITLE
How to disable Publish feature

### ISSUE THREAD

**Issue by mced** [twosigma/beakerx#6767]
How to customize settings and choose displayed buttons in the toolbar especially "Publish..." button ?
I tried to edit that file `.beaker/v1/config/beaker.pref.json` but I've no idea what to put inside.
Thank you.

**Comment by scottdraves** [comment]
Hi, thanks for your question.
Are you asking about BeakerX (for Jupyter) or Beaker Notebook?
We don't have an easy way to do that, but I am curious why you want to...

**Comment by mced** [comment]
I'm asking for BeakerX for JupyterLab.

Reasons:
- the plugin is buggy on jupyterlab (even on clicking on cancel the notebook is published on nbviewer website)
- I prefer to disable features, removing buttons from toolbar that I don't use


Here is a subset of my plugins installed with conda:
```
beakerx                   0.12.1                   py36_1    conda-forge
jupyter                   1.0.0            py36h9896ce5_0  
jupyter_client            5.2.2                    py36_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.4.0            py36h7c827e3_0  
jupyterlab                0.31.2                   py36_0  
jupyterlab_launcher       0.10.2                   py36_0
```

**Comment by scottdraves** [comment]
Hi you are right about that cancel/pub bug!  it's been fixed on master and will appear in the next release. I think next release we'll move from alpha quality to beta for the lab support.

agree on removing publication if not needed or wanted.  we have an options panel under development https://github.com/twosigma/beakerx/issues/6214
will add a switch for this.

i could also see wanting to redirect this publication feature to a private or team server instead of just going to github.

**Comment by mced** [comment]
> Hi you are right about that cancel/pub bug! it's been fixed on master and will appear in the next release. I think next release we'll move from alpha quality to beta for the lab support.

> agree on removing publication if not needed or wanted. we have an options panel under development #6214 will add a switch for this.

Awesome.

> i could also see wanting to redirect this publication feature to a private or team server instead of just going to github.

Actually, that would best fit my needs.

Thank you Scott for your support, and your prompt response.

**Comment by scottdraves** [comment]
You would need some kind of internal server to publish to though.  Do you have something already, like GitLab?  Do you need an API to connect with your own code?  This could be a somewhat longer term project.

**Comment by mced** [comment]
For now, none of this.

**Comment by scottdraves** [comment]
6214 was done.  releasing it in 0.13.0 shortly.
when you can say more about what API is needed for a private publication server please open a new issue for that.
thank you.
