### ISSUE TITLE
docker version cannot load from maven

### ISSUE THREAD

**Issue by titimoby** [twosigma/beakerx#6781]
When running the first cell of the Tablesaw example, the maven trick seems to fail

`Local repository location: '/opt/conda/envs/beakerx/share/beakerx/maven/cache' is NOT a directory.`

I ran it from docker, according to BeakerX documentation, on my ubuntu 17.10 laptop.

**Comment by scottdraves** [comment]
to reproduce, run docker, create a groovy notebook, then run this cell:
```
%classpath add mvn com.google.code.gson gson 2.2.4
new com.google.gson.GsonBuilder().create().toJson("Hello", System.out)
```
perhaps a permission problem?

**Comment by scottdraves** [comment]
@titimoby thanks for letting us know about this problem!
we'll fix it asap and release 0.12.2

**Comment by titimoby** [comment]
I'm not in front of the machine with the docker usage.
In the meantime I use a more direct approach with a simple pip install and it's great.

**Comment by scottdraves** [comment]
hm that directory is not there at all.  it's look for `/opt/conda/envs/beakerx/share/beakerx/maven/cache` but:
<img width="489" alt="screen shot 2018-02-05 at 10 09 16 pm" src="https://user-images.githubusercontent.com/963093/35839966-530c8a06-0ac1-11e8-9a34-b6eb90f30862.png">
