### ISSUE TITLE
Is there any way to disable rendering of pandas DataFrame in a Python notebook?

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#6794]
The ability to rendering pandas DataFrame is cool, but it's better for users to be able to disable it for 2 reasons. 

1. The rendering fails on some corner situations. 

2. The rendering won't work on GitHub. If I share the notebook with someone, he/she has to run the code again to see the result. It's probably better to just disable rendering of DataFrame in this situation.

**Comment by scottdraves** [comment]
Hi yes, agreed, call `beakerx.pandas_display_default()` to return to default pandas rendering.
This is documented here: http://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/python/TableAPI.ipynb

nbviewer can show the tables, btw.

**Comment by scottdraves** [comment]
ps.  if you can let us know what corner situations cause failure, please do!

**Comment by scottdraves** [comment]
looks like this feature got turned on by default by mistake, maybe a factor:  https://github.com/twosigma/beakerx/issues/6810
