### ISSUE TITLE
another UI option: improve fonts

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6802]
followup to https://github.com/twosigma/beakerx/issues/6214

add a checkbox "improve fonts".  enabled by default.

**Comment by piorek** [comment]
What should it do when checked?

**Comment by scottdraves** [comment]
enable/disable the lato/roboto fonts.  leave the fonts files installed like they are, just put in JS turning them on and off, according to the UI.

**Comment by piorek** [comment]
@scottdraves 
I've prepared most of the functionality, but have questions.

Current css styles uses Lato/Roboto font in couple of different places.
We have following font stacks:
- Lato, Helvetica, sans-serif, 
- verdana, helvetica, arial, sans-serif;
and 
- "Roboto Mono", monospace, sans-serif;

I'm guessing that this should be font stacks when **improve fonts** is checked, but what about unchecked state?

Should it only apply to code cells or application wide?

**Comment by scottdraves** [comment]
Sounds good, with no check then same as if Beaker X is not installed at all
