### ISSUE TITLE
Failed import produces no error message

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6804]
The code below produces no error message even though `com.github.lwhite1.tablesaw.api.QueryHelper.column` is not valid (it should be `tech.tablesaw.api.QueryHelper.column`)

```
%%classpath add mvn
tech.tablesaw tablesaw-core 0.11.4
tech.tablesaw tablesaw-beakerx 0.11.4
```

```
%import tech.tablesaw.api.*
%import tech.tablesaw.columns.*
%import tech.tablesaw.io.csv.*
%import static com.github.lwhite1.tablesaw.api.QueryHelper.column

// display Tablesaw tables with BeakerX table display widget
tech.tablesaw.beakerx.TablesawDisplayer.register()
```

**Comment by scottdraves** [comment]
thanks!

**Comment by scottdraves** [comment]
first cell gives error, 2nd does not:
![screen shot 2018-02-07 at 4 00 27 pm](https://user-images.githubusercontent.com/963093/35941390-0e7cde6c-0c20-11e8-96b0-c00d08501db2.png)
