### ISSUE TITLE
Excessive Output in Cells from Logging if jar is based on SLF4J

### ISSUE THREAD

**Issue by pschatzmann** [twosigma/beakerx#6829]
Beakerx add the SLF4J simple logger in it's default system classpath:
/home/beakerx/beakerx/beakerx/kernel/base/lib/slf4j-simple-1.7.25.jar

I have other libraries (which are added via the classpath magic) which also depend on SLF4J and if I use them  I also automatically get all (undesired) INFO messages displayed as result of the execution of a cell. Unfortunately I did not find any way to configure or change this (at runtime). 

Could you please consider to replace the simple logger with something more flexible ? E.g with slf4j-log4j12-1.7.25.jar we could simply change the log level in any cell  by calling org.apache.log4j.Logger.getRootLogger().setLevel(org.apache.log4j.Level.ERROR);

Or do you have any other proposal how to influence the logging within a Notebook

**Comment by scottdraves** [comment]
agreed we are working on this, thank you!

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/pull/6845
