### ISSUE TITLE
Chrome gives a warning when downloading on Windows

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#683]
Something like "this file is not commonly downloaded and could be dangerous." It would be great if you could figure out how to tell Google that you're not dangerous.

**Comment by scottdraves** [comment]
https://productforums.google.com/forum/#!topic/webmasters/kaJ0cSw91Ng

this produces warnings: Content-Type: application/x-zip-compressed

I added .zip as application/zip mime type and the warnings went away.

**Comment by scottdraves** [comment]
moved to https://github.com/twosigma/beaker-notebook-www/issues/95
