### ISSUE TITLE
more package renames

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6852]
after https://github.com/twosigma/beakerx/issues/6729

com.twosigma.beakerx.widget.{bools,floats,integers,selections,strings}
→
com.twosigma.beakerx.widget.{bool,float,integer,selection,string}

**Comment by jaroslawmalekcodete** [comment]
I could not rename floats to float because float is a reserved Java keyword

**Comment by jaroslawmalekcodete** [comment]
Is it ready to close?
