### ISSUE TITLE
direct only error output

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6856]
after, OutputManager.setOutput()
add
OutputManager.setStderr() and OutputManger.setStdout() that do only those parts.

**Comment by jaroslawmalekcodete** [comment]
please explain how it should work, right now Output widget has two methods which can be used to write directly to stdout and stderr
```  
public void appendStdout(String text) {
    sendOutput(new ConsoleOutput(false, text + "\n"));
}

public void appendStderr(String text) {
   sendOutput(new ConsoleOutput(true, text + "\n"));
}
```
try our example test/notebooks/groovy/JavaWidgetsTest.ipynb
![screenshot from 2018-02-14 12-50-22](https://user-images.githubusercontent.com/21952713/36202836-a6992f38-1185-11e8-89ad-f89b6df4a224.png)

**Comment by scottdraves** [comment]
this is neither this is about capturing stderr.  right now we have the method OutputManager.setOutput(out) that redirects stdout and stderr to an output widget.
we want to be able to redirect only stderr to the widget, and stdout would continue to appear in each cell output as normal.
