### ISSUE TITLE
language version upgrades

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6869]
scala 2.11.12
https://www.scala-lang.org/download/2.11.12.html
we are on 2.11.11

clojure 1.9
https://clojure.org/community/downloads
we are on 1.8

**Comment by jpallas** [comment]
Kotlin?  IntelliJ complains:
```
2:42 PM	Outdated Kotlin Runtime
        Version of Kotlin runtime is outdated in several libraries (Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.2.0, Gradle: org.jetbrains.kotlin:kotlin-runtime:1.2.0). Plugin version is 1.2.10-release-IJ2017.3-1.
        Runtime libraries should be updated to avoid compatibility problems.
```

**Comment by scottdraves** [comment]
If possible, but iirc we are using an undocumented API and there were some constraints on the version.
