### ISSUE TITLE
Autocomplete doesn't work on lab

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#6888]
Open groovy notebook, type `tim` and press `Tab`. 
on lab the autocomplete doesn't work
![image](https://user-images.githubusercontent.com/17744188/36484873-ab99d90a-172b-11e8-827b-33df7ae521ef.png)

on classic notebook all is fine
![image](https://user-images.githubusercontent.com/17744188/36484834-92635128-172b-11e8-8675-95a1a2e586a9.png)

**Comment by piorek** [comment]
After investigation and testing it turned out, that there is labextension for autocompletion feature. 
After I did 
```
jupyter labextension install @jupyterlab/completer-extension@0.15.4
```
everything started to work as expected.

**Comment by scottdraves** [comment]
i can't reproduce this problem.  afaik this extension should already be included:
https://github.com/jupyterlab/jupyterlab/blob/d5b1bd9d6e4056b545d3464e7ce393c2afd98e3d/packages/completer-extension/README.md
