### ISSUE TITLE
install-dependencies.sh not included in Ubuntu download

### ISSUE THREAD

**Issue by jc00ke** [twosigma/beakerx#689]
I can't find it in `beaker-notebook-v1.0-0-g5644b78-ubuntu/`

![selection_001](https://cloud.githubusercontent.com/assets/18191/4397507/f58c8ba2-4443-11e4-8a34-cc5cf83a98f1.png)

**Comment by scottdraves** [comment]
Thanks for the bug report and sorry for the oversight.  You can find the file here:
https://github.com/twosigma/beaker-notebook/blob/master/launcher/ubuntu/install-dependencies.sh
we'll get it into the dist asap.

**Comment by scottdraves** [comment]
download updated to beaker-notebook-v1.0-1-g5644b78-ubuntu.zip
