### ISSUE TITLE
Plots are not being displayed

### ISSUE THREAD

**Issue by tb8900** [twosigma/beakerx#6899]
This may be a very stupid question, but I searched through issues and documentation and could not find an answer.

I just started to use BeakerX today. I tried to run ChartingAPI.ipynb on my machine, but none of the plots is being displayed in my browsers.

For example, the following simple lines of code (with no dependent data), will not return display anything (with no errors either):
''
Plot(title="Title",
     xLabel="Horizontal",
     yLabel="Vertical",
     initWidth=500,
     initHeight=200)
''

I tried on Binder and everything worked fine. The same codes do not display anything locally. I have checked that I am running version 0.13.0 with everything updated. Normally, matplotlib would just show the plot with a plt.show().

Is there an option or package that I am missing?

**Comment by scottdraves** [comment]
Thanks for your question.
How did you install BeakerX, into what kind of env and what OS?
Is there any error on the JS console?
Seems like that should work.

**Comment by tb8900** [comment]
I am running Linux Subsystem on Windows 10 to launch BeakerX, then using my browser (Chrome or Firefox) to access localhost:8888. I know this may be an unusual setup, let me know if that does not work.

The errors that I get in Linux are as follow:
''
[W 18:58:14.270 NotebookApp] 404 GET /static/components/preact/preact.min.js.map (127.0.0.1) 22.49ms referer=None
[W 18:58:14.291 NotebookApp] 404 GET /static/components/proptypes/index.js.map (127.0.0.1) 3.38ms referer=None
[I 19:00:03.883 NotebookApp] Starting buffering for e52dfcac-a417-4854-95b6-c2c40f7e0e88:02e5c799be714f3c819069e7bd6694c1
[I 19:00:45.314 NotebookApp] Adapting to protocol v5.1 for kernel e52dfcac-a417-4854-95b6-c2c40f7e0e88
[W 19:00:45.380 NotebookApp] zmq message arrived on closed channel
[W 19:00:45.407 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180226185612 (127.0.0.1) 2.95ms referer=http://localhost:8888/notebooks/beakerx.ipynb
 zmq message arrived on closed channel
 zmq message arrived on closed channel
 zmq message arrived on closed channel
''

In my browser's console:
''
Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:230 Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
(anonymous) @ main.js:230
Could not open comm  --  Error: Class jupyter.widget not found in registry 
    at utils.js:894
    at new Promise (<anonymous>)
    at Object.load_class (utils.js:879)
    at CommManager.comm_open (comm.js:84)
    at i (jquery.min.js:4)
    at Kernel._handle_iopub_message (kernel.js:1223)
    at Kernel._finish_ws_message (kernel.js:1015)
    at kernel.js:1006
    at <anonymous>
(anonymous) @ utils.js:930
kernel.js:1007 Couldn't process kernel message WrappedError
''

I do have widgetsnbextension 3.1.4 and ipywidgets 7.1.2 installed in my Linux Subsystem.  I appreciate your quick response.

**Comment by scottdraves** [comment]
There's all kinds of problems there.  If you just run Python, can you create and use widgets?

**Comment by scottdraves** [comment]
I've never used the Linux Subsystem, this is the first I've heard of trying to run Jupyter in it...

**Comment by tb8900** [comment]
Thanks to your comment I have narrowed it down to it being a widget issue that is not unique to BeakerX. I will close this issue. If I find a solution, I will edit and post it here as well.

Thanks again!

**Comment by scottdraves** [comment]
👍

**Comment by dstieglitz** [comment]
@tb8900 what was the issue?
