### ISSUE TITLE
spambase.csv does not load in table widget

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6909]
I've attached the file here. (I had to change the extension from `.csv` to `.txt` to get it to upload to GitHub)

Some of the columns get cut off in the table widget. If you look at the first row of the file there are additional columns that what's displayed on the screen

You can load with:
```
%%classpath add mvn
tech.tablesaw tablesaw-plot 0.11.9
tech.tablesaw tablesaw-smile 0.11.9
tech.tablesaw tablesaw-beakerx 0.11.9

%import tech.tablesaw.aggregate.*
%import tech.tablesaw.api.*
%import tech.tablesaw.api.ml.regression.*
%import tech.tablesaw.columns.*

// display Tablesaw tables with BeakerX table display widget
tech.tablesaw.beakerx.TablesawDisplayer.register()

table = Table.read().csv("spambase.txt")
```

[spambase.txt](https://github.com/twosigma/beakerx/files/1765535/spambase.txt)

**Comment by scottdraves** [comment]
Thanks Ben, will look into it.

**Comment by scottdraves** [comment]
Yea by default it shows no more than 50 columns.  When the table first appears it should warn and give an opportunity to pick which ones to display.  If that is skipped, just use the table menu item "Show All Columns" to just bring them back.  For 58 probably OK but the performance is a problem with too many.

The rewrite of the table widget that removes this limitation is coming along well, see https://github.com/twosigma/beakerx/tree/feature/6674

**Comment by benmccann** [comment]
Will the table widget rewrite still use the DataTables JavaScript library that's used today?

**Comment by scottdraves** [comment]
no, we are switching to phosphor's datagrid (http://phosphorjs.github.io/examples/datagrid/) which uses canvas.
