### ISSUE TITLE
Add some D3 examples to the website

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#691]
The comments on reddit back up my suspicion that [R, Python] -> D3 could be your killer use case. You illustrate this in the very first graphic on the website, but there are no real examples.

http://www.reddit.com/r/datascience/comments/2hdfdg/open_source_polyglot_web_app/

**Comment by scottdraves** [comment]
Yup.  The problem is that right now the way we do D3 doesn't work with the sharing server.
I have some ideas for fixing that: https://github.com/twosigma/beaker-notebook/issues/407

**Comment by scottdraves** [comment]
moved to https://github.com/twosigma/beaker-notebook-www/issues/94
