### ISSUE TITLE
How do I run static class of java.

### ISSUE THREAD

**Issue by aka9** [twosigma/beakerx#6918]
I use beakerx kernel in jupyter.  I have Question. Please help...

I want to run static main class of Java. it is example.

```
In []: public class Main{
            public static void main(String args[]){
                System.out.println("Hello world");
            }
         }

Out [] : com.twosigma.beaker.javash.bkrfc10fc5e.Main
```

I want output "Hello world". How do I get the output? 

i want 

```
Out [] : Hello world 

or

Hello world
Out [] : com.twosigma.beaker.javash.bkrfc10fc5e.Main
```

**Comment by aka9** [comment]
I can only know a little English and I might so not polite(manners). Sorry...

**Comment by scottdraves** [comment]
Hi, no problem.  This works: https://nbviewer.jupyter.org/gist/anonymous/f4d3e984308e91abcf853bd037bb4e81

**Comment by aka9** [comment]
Thanks!! At first, I don't work this code;

![beakerx_java](https://user-images.githubusercontent.com/23370043/36879541-a842de72-1e07-11e8-870f-6867618a2efe.jpg)



But, I do "Restart Kernel". It is work!

![beaker_java2](https://user-images.githubusercontent.com/23370043/36879581-df36ecfc-1e07-11e8-98f7-8049ec8490dd.jpg)

Thank you for helping me!
