### ISSUE TITLE
Histogram should have binCount default

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6922]
This draws a blank chart:
```
double[] arr = table.column("word_freq_make").collect()
new Histogram(data: arr)
```

I needed to change it to:
```
double[] arr = table.column("word_freq_make").collect()
new Histogram(data: arr, binCount: 25)
```

A default of 10 would be sensible, but anything would work really. It took me awhile to figure out this was a required parameter

**Comment by scottdraves** [comment]
Thanks, agreed, will do something here.

**Comment by scottdraves** [comment]
Yup default binCount should be 10.
