### ISSUE TITLE
Could not resolve dependencies

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#6927]
I got an error message saying that "Could not resolve dependencies for ..." when running the following magic in a Scala notebook. 
```
%classpath add mvn org.apache.spark spark-sql_2.11 2.2.1
```

**Comment by scottdraves** [comment]
do you have the latest version of BeakerX (0.13.0)?

**Comment by dclong** [comment]
Yes, I'm using the latest version (0.15) but same issue still exists!

**Comment by scottdraves** [comment]
I'm not seeing it, can you please better document how to reproduce this?

**Comment by scottdraves** [comment]
i just tried on binder and it worked there.  can you see it on binder?
https://mybinder.org/v2/gh/twosigma/beakerx/0.15.0?filepath=StartHere.ipynb

**Comment by dclong** [comment]
Below is the information of notebook that run into issues. 

OS: Ubuntu 16.04
Notebook server: 5.4.1
Python: 3.5.2 [GCC: 5.4.0] installed using apt-get and packages managed by pip3
BeakerX 0.15.2
Scala 2.11.12
hash e46e2de

I tried to install Jupyter Notebook and BeakerX using conda and everything works well. 
OS: Ubuntu 16.04
Notebook server: 5.4.1
Python: 3.6.4 |Anaconda, Inc.| [GCC 7.2.0] installed using conda and packages managed by conda
BeakerX 0.15.2
Scala 2.11.12
hash e46e2de

So my question is does BeakerX rely on Python 3.6 or/and conda to work?

**Comment by scottdraves** [comment]
> So my question is does BeakerX rely on Python 3.6 or/and conda to work?

It works with Python 3.5 for sure.  It also works without conda, but there are a couple of dependencies that pip doesn't have, like a JDK and Maven.

> Python: 3.5.2 [GCC: 5.4.0] installed using apt-get and packages managed by pip3

If you can report exactly how you set up the environment then maybe I can reproduce this.

Do other simpler maven commands work?  Try this in a Groovy notebook:
```
%classpath add mvn com.google.code.gson gson 2.2.4
new com.google.gson.GsonBuilder().create().toJson("Hello", System.out)
```

**Comment by laurensdv** [comment]
I had the same issue, in my case the cause was that my conda environment did not include maven.

Fixed it by running `conda install maven` (java mvn already installed) in my beakerx conda environment (after running `source activate beakerx`)

**Comment by dclong** [comment]
@scottdraves 

I had been using the conda version of Docker image, however, it is bloated (almost twice in size) compared to the pip version of Docker image. I'd like to switch back to pip and figure out the issue here. 
```
%classpath add mvn com.google.code.gson gson 2.2.4
new com.google.gson.GsonBuilder().create().toJson("Hello", System.out)
```
generates the following error message and output.
<img width="1269" alt="screen shot 2018-07-22 at 2 38 01 pm" src="https://user-images.githubusercontent.com/824507/43043049-021ca010-8d50-11e8-83f1-60a9bff02bcf.png">
I have OpenJDK, Scala and maven installed using `apt-get`. 

<img width="1052" alt="screen shot 2018-07-22 at 2 40 34 pm" src="https://user-images.githubusercontent.com/824507/43043069-56c1c0d2-8d50-11e8-864f-44e234b60769.png">
Here's the Dockerfile if you want to dig into it. 

https://github.com/dclong/docker-jupyterlab-beakerx/blob/master/Dockerfile

And Dockerfile of the base image

https://github.com/dclong/docker-jupyterlab-py/blob/master/Dockerfile

**Comment by dclong** [comment]
@scottdraves Can you reopen this issue?
