### ISSUE TITLE
How to share variables across cells in Java

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6928]
Is there anyway to reference a variable defined in a previous cell in a Java notebook?

**Comment by scottdraves** [comment]
Hi Ben, use a class like this: https://nbviewer.jupyter.org/gist/anonymous/738a93ecfffc9fd85275fa8061a27237

**Comment by benmccann** [comment]
Ah, thanks! That's helpful

I wonder if there might be any way to improve the support for this that makes it a bit simpler for end users to write. I'm not too familiar with the way the kernels are implemented under the covers. E.g. it might be cool if you could declare a variable as `static` without defining a class for it to live in. Or if all variables were automatically available in cells that followed.

I'm really looking forward to Groovy 3.0 as it will make it much more possibly to use Java syntax in Groovy notebooks without getting errors. Unfortunately it seems like that won't happen for several months still

**Comment by scottdraves** [comment]
I think JShell is the best approach to this: https://github.com/twosigma/beakerx/issues/5428
But this is blocked on getting java 9 in conda, and I don't see any activity on that front: https://github.com/conda-forge/openjdk-feedstock/issues/21

Our java kernel works by wrapping statements in a class (if you are not compiling a class yourself).
I don't see any easy way to simplify it for the user.

**Comment by benmccann** [comment]
Makes sense. Thanks
