### ISSUE TITLE
spark dependency conflict

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6938]
user report:
https://nbviewer.jupyter.org/gist/anonymous/46b28f9bc1d130d22afc484292cb01c5
https://stackoverflow.com/questions/36427291/illegalaccesserror-to-guavas-stopwatch-from-org-apache-hadoop-mapreduce-lib-inp

**Comment by scottdraves** [comment]
Ultimately this is a pretty fundamental problem that stems from how we load code into the kernel.
Guava is already in BeakerX and if we load it dynamically too, the conflict cannot be resolved: https://github.com/twosigma/beakerx/issues/6782

In the meantime as a workaround we can probably take guava out of BeakerX.
Looking into it...

**Comment by jpallas** [comment]
> The last release to remove non-@Beta APIs was Guava 21.0.

In fairness to them, they did keep changing the major version number when they broke compatibility.  You can't say they didn't play by the rules, they just did it in a way likely to cause problems for everyone downstream.  Which turns out to be just about every major project anywhere.
