### ISSUE TITLE
python plugin mangles dataframe made with groupby

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#694]
The following code:

```
import pandas as pd
df=pd.DataFrame([[12,34,1],[12,56,8],[13,34,6]],columns=['pet','colour','value'])
df.groupby(['pet','colour']).sum()
```

produces this in IPy:

![screen shot 2014-09-25 at 4 38 10 pm](https://cloud.githubusercontent.com/assets/963093/4411950/fc5473b8-44f3-11e4-90c9-7c28ab2f1b20.png)

and like this in Beaker:

![screen shot 2014-09-25 at 4 39 58 pm](https://cloud.githubusercontent.com/assets/963093/4411966/2868eb6e-44f4-11e4-963a-0de0b97b9aae.png)

**Comment by scottdraves** [comment]
as a workaround, you can alter the HTML to avoid Beaker's interactive table display:

```
from IPython.display import HTML
import pandas as pd
df=pd.DataFrame([[12,34,1],[12,56,8],[13,34,6]],columns=['pet','colour','value'])
HTML("<span>"+df.groupby(['pet','colour']).sum().to_html()+"</span>")
```

**Comment by ildipo** [comment]
Created pull request with bug fix: Since slick grid does not support row/colspan we do not use it if the table has it. The same pull contains a fix for merging two header lines.
