### ISSUE TITLE
python plugin fails with python3

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#695]
urllib2 (used by autotranslate) does not exist in python3.

**Comment by HanniAli** [comment]
I would note that using 2to3 to migrate the beakey.py works fine to upgrade the code and I can successfully use most of the Ipython functionality against my Python33 installation. However it I try to use the beaker.set method I run into encoding problems even with a simple string.

Full python3 support out of the box would be appreciated.

**Comment by scottdraves** [comment]
Thanks Hanniali, that helps.  This issue is next on my agenda.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/733
