### ISSUE TITLE
Scala completion is not working correctly

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#6957]
This has been broken for a while, I think.  I'm not sure exactly since when, because the behavior is a little bit confusing.  Autocompletion sees the standard library and beaker-specific imports, but it doesn't see values defined by the user.  At least, that's my interpretation of the behavior.

So, concretely:  If the first cell contains
```
val xyzzy = "hello"
```
then we would expect that typing `xyz<TAB>` in the second cell would offer the completion `xyzzy`.  But it doesn't.

My intuition says this has something to do with `ScalaEvaluator`'s `acshell`.  I don't understand the Scala kernel autocomplete stuff, but it seems odd to have a separate evaluator just for completions.  Does this have something to do with class loaders?  I don't know.

**Comment by jpallas** [comment]
At this point my theory is that the existence of `ScalaEvaluator.acshell` is a mistake (possibly based on some code that pre-dated the Scala 2.11 presentation compiler, but that's just a guess).  The presentation-compiler-based autocomplete shouldn't mess with the state of the interpreter.  Evaluating code specifically for the side-effects in the namespace (in `ScalaEvaluator.autocomplete`) is a serious error.  (Example: don't try hitting `abc<TAB>` on line 2 if line 1 says `System.exit(0)`!)

I'm going to try excising `acshell` completely and see if anything breaks.  If there _is_ any kind of weird class-loading interaction with completion, though, I'm not confident that the existing tests will expose it.

**Comment by scottdraves** [comment]
Cool thanks Joe
