### ISSUE TITLE
Mathjax in markdown cells

### ISSUE THREAD

**Issue by nbren12** [twosigma/beakerx#696]
Coming from the ipython notebook, I am used to writing equations directly in my markdown cells. Usually, when I am writing math, it is interweaved with text, pictures, etc. I rarely have a need for standalone equations isolated in a cell away from my other text, so beaker's "Latex" cell is inadequate for my purposes. It should be a relatively simple matter of adding 

```
<script type="text/javascript"
    src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```

in an appropriate place.

**Comment by samccone** [comment]
:+1: to this

**Comment by scottdraves** [comment]
we prob need to use something other than epiceditor for this to work.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/1182

**Comment by scottdraves** [comment]
this should be doable now

**Comment by samccone** [comment]
:clap: great work @buob
