### ISSUE TITLE
SQL results don't show up

### ISSUE THREAD

**Issue by rmchale** [twosigma/beakerx#6976]
When I run any non-trivial SQL the results don't show up.

SQL
```
SELECT 1, 2
```
Screenshot:
https://www.dropbox.com/s/9mwhwxz412f8eck/Screenshot%202018-03-14%2010.57.58.png?dl=0

I'm using:
```
jupyter-lab Beta Release Series
Version 0.31.5
```

I installed it following these directions:
http://beakerx.com/documentation#tutorials-and-examples

**Comment by scottdraves** [comment]
Thanks for the report, will look into it.

**Comment by rmchale** [comment]
I'm connecting to postgres.

**Comment by rmchale** [comment]
FWIW, ```select 1``` worked

**Comment by rmchale** [comment]
The install was not right.  I think I had to:
```
conda install -y nodejs
```
Before it would install the webpacks.  I'd say this can be closed.
