### ISSUE TITLE
KaTeX support

### ISSUE THREAD

**Issue by renkun-ken** [twosigma/beakerx#698]
As an alternative to MathJax, KaTeX has much higher render performance which is good for document with many equations.

https://github.com/Khan/KaTeX

Would appreciate if KaTeX is supported.

**Comment by scottdraves** [comment]
mathjax also has like 150MB of png font files that we could save.

**Comment by scottdraves** [comment]
we may be blocked by https://github.com/Khan/KaTeX/issues/5

**Comment by xymostech** [comment]
Can I ask why dollar signs in `\text` is what's blocking you from using KaTeX?

At Khan Academy, we use a hybrid approach, where things that are renderable with KaTeX use it, and things that aren't use MathJax, which makes a lot of things faster but also still supports all of the MathJax features that people might be using already.

**Comment by scottdraves** [comment]
that's possible but the space savings is more than half my motivation.
how hard is it to fix?

**Comment by scottdraves** [comment]
@xymostech we decided the upside of the performance and size outweighed the downside of the nested $/text/$ bug.  thank you for a great library!

**Comment by xymostech** [comment]
@scottdraves Awesome! Looking through the pull request, it's awesome how well the `renderMathInElement` extension is working for you! (@spicyj just made the extension better, we'll make a release soon) Let me know if you run into any problems!

**Comment by samccone** [comment]
:+1:
