### ISSUE TITLE
Support ggvis graphics for R cells

### ISSUE THREAD

**Issue by renkun-ken** [twosigma/beakerx#700]
[ggvis](http://ggvis.rstudio.com/) is a data visualization package for R to create rich interactive graphics. Currently, the code does not produce anything:

``` r
library(ggvis)
mtcars %>%
  ggvis(~ wt, ~ mpg) %>%
  layer_points()
```

which in RStudio produces a nice svg chart.

**Comment by renkun-ken** [comment]
Duplicate #693.

**Comment by scottdraves** [comment]
Thanks for the request.
