### ISSUE TITLE
can not overwrite java class in jupyter.

### ISSUE THREAD

**Issue by aka9** [twosigma/beakerx#7015]
I run cell simple java class. 
![overwrite](https://user-images.githubusercontent.com/23370043/37775246-d1f27b00-2e25-11e8-8e87-46c5754ba6ec.jpg)

but, run again.
![overwrite2](https://user-images.githubusercontent.com/23370043/37775332-0e3f8864-2e26-11e8-97c9-6330af15104b.jpg)

I want "hello world" in output cell.
solution which I have only is "kernel restart", but It requires a lot of run cell.

Does anyone have any other solutions?

**Comment by scottdraves** [comment]
Hi thank you for your report.
This is a limitation of our Java Kernel and it should be better documented.
Unfortunately I can't think of an easy way to fix it.  @jaroslawmalekcodete ?

Eventually we'll get Java9 support and then we should be able to make a JShell kernel that handles this kind of thing: https://github.com/twosigma/beakerx/issues/5428

**Comment by aka9** [comment]
Thanks you answer. I am excited about fix.
