### ISSUE TITLE
docker container and port remapping breaks ipython

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#702]
you get the following on the JS console:

```
XMLHttpRequest cannot load https://XXX:8800/beaker/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://XXX:8801' is therefore not allowed access. 
```

**Comment by ildipo** [comment]
The issue is created by nginx that is trying to redirect the /beaker URI into /beaker/ since in the configuration file there's no match for /beaker without a slash. URI rewrite will not work. The solution is to add a second location block that matches /beaker URI and proxy passes them.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/714
