### ISSUE TITLE
login shell causes PATH problems on Mac

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#703]
Our method of finding IPython on Mac is to create a login shell during application boot in beaker.command:

https://github.com/twosigma/beaker-notebook/blob/master/core/beaker.command#L30

however, if the user sets up their path in the terminal because they use virtualenv, or they don't use bash and so their PATH setup is not in .bash_profile, then this fails.

**Comment by scottdraves** [comment]
could just add a Path string to the language spec.

but how do we get the initial value and where does that default get saved?

**Comment by scottdraves** [comment]
duh, It needs to be a Beaker config not a property of the plugin or notebook.

I propose a adding a table to beaker.prefs.json with config for each plugin available.
primarily this is the name and path (and maybe the badge, to address https://github.com/twosigma/beaker-notebook/pull/648).  These table entries
are overrides for a similar table in beaker.conf.json.  this isn't the path where the xxxPlugin
launcher script is found, but where the original backend is found, ie R (aka Rscript), ipython&python,
etc are found.

There should be a GUI for this too, part of the Plugin Manager.  It a Path field (optional because if not set then just use as is) in the tabbed section (but omit if makes no sense like html, js, etc).  ideally next to this text field is an indicator for if a working backend was found at that location.  every time the user enters something we should try firing it up, confirm it works, and report/record the status.  when Beaker is first run, it tries each of them and records the status as runnable (gray).  Otherwise the plugin is dead.  This indicator should be combined with the gray/yellow/green indicator we already have.  The fourth state is perhaps red X.

For R on Windows we could then get rid of the part where you have to add it to PATH which is hard for users.  The right way to find R on windows is via a resource, so the core server would read it and initialize the conf.

we used to have an option for finding the ipython path but it was command-line only, and python-only.  this is generalizing that and putting a GUI on it.  we should also consider GUI for the backend options like JVM heap size.  Another language configuration in the mix is python2 vs python3.  i am pretty sure that what `source activate` reduces down to.

maybe python should just use "source activate" directly?
this along with the R resource above makes it seem like the xxxPlugin should have a chance to override this.

**Comment by scottdraves** [comment]
@bradicdesign next step for plugin manager

**Comment by justinlent** [comment]
re: comment above: "however, if the user sets up their path in the terminal because they use virtualenv, or they don't use bash and so their PATH setup is not in .bash_profile, then this fails."

i added this to my .bash_profile and it still does not launch. i even tried launching Beaker from a terminal window is which i've run .bash_profile.  i'm on the latest stable version of ipython notebook (jupyter) and on the Python 2.7.9 (Anaconda 2.1) 

specifically, these 2 lines are at the end of my .bash_profile

export PATH="/Users/justinlent/python/anaconda210/anaconda/bin:$PATH"

export PYTHONPATH=/Users/justinlent/python/anaconda210/anaconda/bin:$PYTHONPATH

**Comment by scottdraves** [comment]
Hi, thanks for the report and sorry it doesn't run for you.  We haven't tried it with Jupyter yet, but we will.

Launching Beaker from a terminal that has the path set up doesn't work because the login shell resets the path.  What is your shell set to?

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/1178

**Comment by scottdraves** [comment]
I added a path per plugin to the prefs but left in the login-shell hack on mac because i don't want to require users to edit theirs prefs to access python, since now editing prefs is painful.

I think true resolution of this needs to wait until we control the installation of python, or we have some way to guess initial value for prefs.

So much of the problem has been solved but it would still be good to remove this hack, it will just require more work, so punting this to the next release (though that's optimistic)
