### ISSUE TITLE
Review maven support code for Windows compatibility

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#7038]
I noticed this while looking at the mvnLocal merge.  It looks like there's a fair bit of hard-coded forward-slashes in the maven-related code (not just the newest changes).

**Comment by altavir** [comment]
Windows supports unix-style slashes since XP (maybe it was 2000, but any modern windows system does). For windows one needs to be careful about case sensitivity. NTFS respects case when one creates a new file but ignores it when resolving files.

**Comment by jpallas** [comment]
Thanks.  I managed to dig up an [authoritative source](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx) that says
> **Note**  File I/O functions in the Windows API convert "/" to "\\" as part of converting the name to an NT-style name, except when using the "\\\\?\\" prefix as detailed in the following sections.

Java documentation doesn't seem to acknowledge this, which is why I thought it was still a consideration.
