### ISSUE TITLE
display spark datasets and dataframes with table widget

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7040]
see @jpallas comments https://github.com/twosigma/beakerx/pull/6993

indeed.  the widget should show just what spark normally shows ascii-formatted tables (sometimes very wide).

is there a way to configure show method to use our repr?
maybe via https://github.com/jupyter/jvm-repr?
add a new method or a subclass?

after the tables support streaming https://github.com/twosigma/beakerx/issues/7006
then we can connect them directly to that.

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beakerx/issues/7041

**Comment by jpallas** [comment]
`show` is defined directly by `Dataset` and has no return value, so I don't think there's any way to get it into a table short of scraping the output (or doing unspeakable things with cglib).

**Comment by scottdraves** [comment]
yea should be a display handler, installed by jvm-repr.
maybe start with 1000 rows.

**Comment by scottdraves** [comment]
@jpallas  on the other issue you said:
> (I've prototyped this).

care to share? jarek could pick up your work if you think it's on the right track.

**Comment by jpallas** [comment]
What I did is just a few lines:
```scala
implicit class DatasetOps(ds: org.apache.spark.sql.Dataset[_]) {
    def display(rows: Int = 20) = {
        // I do not understand why this import is necessary
        import com.twosigma.beakerx.scala.table.TableDisplay
        val columns = ds.columns
        val rowVals = ds.toDF.take(rows)
        val t = new TableDisplay(rowVals map (row => (columns zip row.toSeq).toMap))
        t.display()
    }
}
```

(There is something strange going on with imports and visibility in the Scala kernel, maybe some odd interaction with the way the interpreter wraps things.)

Example with a `Dataset[Fields]` where `case class Fields(first: String, second: String, third: Int)`:
![screen shot 2018-03-28 at 11 48 35 am](https://user-images.githubusercontent.com/4623910/38049870-2ced014a-327e-11e8-90dd-d77694d9df3c.png)
