### ISSUE TITLE
zero does not appear

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7043]
<img width="212" alt="screen shot 2018-03-25 at 10 55 41 pm" src="https://user-images.githubusercontent.com/963093/37884854-ff941c06-307f-11e8-803e-8db456049b96.png">

**Comment by EfimovVladimir** [comment]
Reproduced for table with PhosphorJS DataGrid (Window, Ubuntu)

Doesn't reproduced. Classic notebook, without PhosphorJS DataGrid. (Windows, Ubuntu)
![image](https://user-images.githubusercontent.com/17744188/37897842-e1081f56-30ef-11e8-9611-4a53bcd0e12b.png)

But table is'not displayed at all on jupyterLab. (Windows, Ubuntu, with PhosphorJS DataGrid and without )
![image](https://user-images.githubusercontent.com/17744188/37898000-4e622a56-30f0-11e8-87a3-aa2d9c14a1e8.png)

Console log:
![image](https://user-images.githubusercontent.com/17744188/37898100-9799b8f6-30f0-11e8-942a-e8d1a4566632.png)
