### ISSUE TITLE
JDBC client

### ISSUE THREAD

**Issue by janovergoor** [twosigma/beakerx#706]
It would be awesome to be able to connect to a JDBC client and query from a mysql/postgres/redshift/presto server.

**Comment by scottdraves** [comment]
hi i am not sure what you mean.  i believe you can connect to mysql with JDBC via the Groovy plugin: http://groovy.codehaus.org/Tutorial+6+-+Groovy+SQL

would that help?

i agree we need to beef up the SQL story...

**Comment by janovergoor** [comment]
Yeah, there are python binding to most common JDBC clients. I just thought it would be cool do it natively, but it's low priority.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/2382
