### ISSUE TITLE
lab install cmd

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7062]
`beakerx install --lab` should also run
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install beakerx-jupyterlab
jupyter labextension install beakerx-jupyterlab-js
```

**Comment by CerebralMastication** [comment]
Hey I realize that commenting on closed issues is not always good form... however, I'm installing on JupyterLab with JupyterHub using `pip` in a Docker image. Should I be running `beakerx install --lab` after I run `pip3.6 -v install beakerx`? I may be overlooking it somewhere, but I can't find any documentation that explains the `--lab` switch. 

I'm on CentOS with a custom Dockerfile and my bit that loads BeakerX looks like this:

```
RUN pip3.6 -v install beakerx 
RUN beakerx install
RUN jupyter labextension install beakerx-jupyterlab
RUN jupyter nbextension enable beakerx --py --sys-prefix

```
