### ISSUE TITLE
anon Gist publication unsupported

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7065]
Try to publish any notebook
![image](https://user-images.githubusercontent.com/17744188/37965696-9c26ff58-31ce-11e8-9f2e-9fafd04807ff.png)

Console log:
![image](https://user-images.githubusercontent.com/17744188/37965795-f8e189fc-31ce-11e8-96bb-e6f2e36be9c9.png)

**Comment by scottdraves** [comment]
confirmed

**Comment by lmitusinski** [comment]
Seems to be the same issue as this reported on stack-overflow:
https://stackoverflow.com/questions/49531422/git-gist-missing-field-user

I sent a support request to ask if it's really problem on their side because i didn't found any changes in API docs.

**Comment by scottdraves** [comment]
https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/

**Comment by scottdraves** [comment]
we should update our UI to require the token.

**Comment by scottdraves** [comment]
remove this text and the box around it:

> Leave the Personal Access Token field empty to publish as an anonymous gist. 
Press enter or click the "Publish" button below. A window will open with the results, which you can share like any URL.
