### ISSUE TITLE
Set size of R graphics

### ISSUE THREAD

**Issue by janovergoor** [twosigma/beakerx#707]
I'd like to be able to set the size of R output graphics. 

For example, I would usually shape graphics by writing to a pdf file and setting height=5, width=10.
Since the beaker screen is generally wider than taller, such aspect ratio's would be useful to set.

Right now, the only solution I can think of is using theme(aspect.ratio=0.5) from ggplot, but that creates a a bad-looking sea of whitespace.

**Comment by scottdraves** [comment]
yea this has been requested several times.

**Comment by scottdraves** [comment]
demo of the API (from the R tutorial):
http://sharing.beakernotebook.com/gist/anonymous/8703affdf1e53e3ac73b

remaining issue:
https://github.com/twosigma/beaker-notebook/issues/731
