### ISSUE TITLE
empty column tooltip

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7071]
run the cell with `class MyClass` at the end of test/ipynb/groovy/MapLikeTableTest.ipynb
and then hover over the column. the tooltip is empty.  should be "Object".
![screen shot 2018-03-27 at 11 19 55 am](https://user-images.githubusercontent.com/963093/37977098-141ddb76-31b1-11e8-8786-9be9e9dc55a0.png)

**Comment by MariuszJurowicz** [comment]
@scottdraves could you plz test it once again?
And please give me more info about when and where it does not work for you.
