### ISSUE TITLE
The fonts are diffrents on DataGrid table

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7080]
On jupyter lab
![image](https://user-images.githubusercontent.com/17744188/38033150-07cb8b1e-32a8-11e8-9a46-d3717de19e41.png)

On classic notebook
![image](https://user-images.githubusercontent.com/17744188/38033173-1a1fdd56-32a8-11e8-843a-8224842e2297.png)

Expected Font should be the same as on classic notebook.

**Comment by scottdraves** [comment]
fixed

**Comment by MariuszJurowicz** [comment]
I think it's related to: https://github.com/twosigma/beakerx/issues/6687

**Comment by piorek** [comment]
I think its fixed. 
Looks ok now
