### ISSUE TITLE
numerical sort of NaN in table

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7085]
if there's a NaN in a double column, and you sort it, then NaN should be greater than any normal number.

to reproduce, same setup as https://github.com/twosigma/beakerx/issues/7053
```
import pandas as pd
import beakerx as bx
pd.read_excel('titanic3.xls')
```
then click on the column "fare" to sort, and note first few rows.
click it again and note them again.  

The row for Thomas Storey should have a fare of "NaN".
it should sort as greater than any normal FP number.

**Comment by jpallas** [comment]
Not disagreeing, but I notice that there isn't universal agreement on this.  Looking at sorting in spreadsheets, Excel and Google Sheets treats NaN as larger than numbers, while Apple Numbers treats NaN as larger for ascending sort and smaller for descending sort (that is, NaNs always come after numbers).

**Comment by scottdraves** [comment]
Thanks for researching that.  Interesting.
