### ISSUE TITLE
Support for export to HTML

### ISSUE THREAD

**Issue by daveholtz** [twosigma/beakerx#709]
IPython supports export to HTML quite nicely.  You can do this in Beaker by just running command+S while in the browser with a notebook open, but this can mangle some of the tables and charts.  Would be nice to more explicitly support the HTML export (a la IPython).

**Comment by scottdraves** [comment]
Yea we should have an export dialog that picks the format (html, pdf, ipynb, etc).

**Comment by daveholtz** [comment]
Yeah, from a UI perspective that would be fine.  I think the upshot is that simplying saving by (on a mac) pressing command+S actually creates an HTML page that doesn't render well as HTML. 

For example, the following code:

```
L3 <- LETTERS[1:3]
fac <- sample(L3, 10, replace = TRUE)
(d <- data.frame(x = 1, y = 1:10, fac = fac))
```

produces a table that looks like this in a live notebook:
![screen shot 2014-09-30 at 7 43 14 pm](https://cloud.githubusercontent.com/assets/2642134/4469591/d48f42d4-4914-11e4-8c4c-fcc4758e117e.png)
but that looks like this in an HTML file reopened:
![screen shot 2014-09-30 at 7 43 31 pm](https://cloud.githubusercontent.com/assets/2642134/4469596/dda86f62-4914-11e4-8290-bb1b0042ed13.png)
