### ISSUE TITLE
Support for export code only

### ISSUE THREAD

**Issue by daveholtz** [twosigma/beakerx#710]
Another IPython comparison - there is a nice feature to be able to export all of the code contained in the notebook in IPython to a .py file.  Would be great to be able to do this with a beaker file, and generate all of the necessary files (e.g., .py, .R, .html, etc.).

**Comment by scottdraves** [comment]
cool, sounds like just be another item in the format menu in the "Save As" dialog.

**Comment by daveholtz** [comment]
Yep - one more (that actually seems like it may be the best) is to save as Markdown.

FWIW, most of these features seem baked into IPython, but the code to get this done actually looks pretty messy: https://github.com/ipython/ipython/tree/master/IPython/nbconvert

**Comment by scottdraves** [comment]
also and perhaps most important is export to a reveal.js slideshow.

**Comment by scottdraves** [comment]
related: https://github.com/twosigma/beaker-notebook/issues/709
https://github.com/twosigma/beaker-notebook/issues/710
https://github.com/twosigma/beaker-notebook/issues/974

**Comment by scottdraves** [comment]
might be even better than export:
https://github.com/damianavila/RISE
