### ISSUE TITLE
Running beakerx with binder

### ISSUE THREAD

**Issue by rdmueller** [twosigma/beakerx#7132]
I am trying to run my own beakerx notebook with binder

https://github.com/rdmueller/jupyter.git

https://mybinder.org/v2/gh/rdmueller/jupyter.git/master

but it complains that it can't find the pandas module. For me, it seems that conda is stuck at 98% while trying to resolve pandas.

Any idea on what I am doing wrong?

**Comment by scottdraves** [comment]
yea here's the error:
```
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::beakerx-0.14.0-py36_1'.
LinkError: post-link script failed for package conda-forge::beakerx-0.14.0-py36_1
running your command again with `-v` will provide additional information
location of failed script: /srv/conda/bin/.beakerx-post-link.sh
==> script messages <==
+ /srv/conda/bin/beakerx install
Traceback (most recent call last):
  File "/srv/conda/bin/beakerx", line 4, in <module>
    import beakerx
  File "/srv/conda/lib/python3.6/site-packages/beakerx/__init__.py", line 15, in <module>
    from .runtime import BeakerX
  File "/srv/conda/lib/python3.6/site-packages/beakerx/runtime.py", line 17, in <module>
    import os, json, pandas, numpy
ModuleNotFoundError: No module named 'pandas'


Attempting to roll back.


LinkError: post-link script failed for package conda-forge::beakerx-0.14.0-py36_1
running your command again with `-v` will provide additional information
location of failed script: /srv/conda/bin/.beakerx-post-link.sh
==> script messages <==
+ /srv/conda/bin/beakerx install
Traceback (most recent call last):
  File "/srv/conda/bin/beakerx", line 4, in <module>
    import beakerx
  File "/srv/conda/lib/python3.6/site-packages/beakerx/__init__.py", line 15, in <module>
    from .runtime import BeakerX
  File "/srv/conda/lib/python3.6/site-packages/beakerx/runtime.py", line 17, in <module>
    import os, json, pandas, numpy
ModuleNotFoundError: No module named 'pandas'
```

the source of this problem is an unfortunate interaction between problems in conda and numpy/mkl:
https://github.com/conda/conda/issues/7115

i haven't found an issue for the circular dependency between numpy and mkl, that's probably the best place to fix this.  unfortunately i don't know of a workaround for binder, but i expect i will be looking for one as soon.  if you can find an issue for the fixing the circular dependency or a workaround for binder please LMK.

**Comment by scottdraves** [comment]
I filed this to break the circularity, not sure if it's the right place: https://github.com/ContinuumIO/anaconda-issues/issues/9117

**Comment by scottdraves** [comment]
As a workaround I think we could just not run the tests: https://github.com/conda-forge/beakerx-feedstock/blob/master/recipe/meta.yaml#L40

and refactor "beakerx install" so it does not import pandas.

another possible workaround: require an older version of numpy or mkl?

**Comment by rdmueller** [comment]
thanx for the uick replies.
how do you make the beakerx demos run on binder if this a general error

**Comment by scottdraves** [comment]
we made our binder demo before the circularity appeared, and now that our container is cached, we are good.
you might also be able to workaround by going with an old version of numpy or mkl.
i haven't found the repo with the meta.yml files for those packages yet though.

**Comment by scottdraves** [comment]
yea confirmed if you run beakerx master branch instead of tag 0.14.0: https://mybinder.org/v2/gh/twosigma/beakerx/master
same crash.

**Comment by rdmueller** [comment]
ok. so as I understand, your demo runs because of the cache and I currently have no chance to select another version... interesting. So I just wait until this is fixed.

nevertheless: beakeex is very cool!

**Comment by scottdraves** [comment]
0.15.0 released and working on binder (however there's an unrelated problem: https://github.com/twosigma/beakerx/issues/7149)

**Comment by rdmueller** [comment]
very cool! It works. Thanx a lot!
