### ISSUE TITLE
Error displaying widget (python, Lab)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7143]
See doc/python/OutputContainers.ipynb on jupyter Lab
![image](https://user-images.githubusercontent.com/17744188/38551500-f509b888-3cc1-11e8-948e-2cc4746d4a59.png)

**Comment by jtpio** [comment]
Have you tried installing the JupyterLab extension manually:

```bash
jupyter labextension install beakerx-jupyterlab
```

You can then check whether the extension is enabled with `jupyter labextension list`.

**Comment by piorek** [comment]
@EfimovVladimir cannot reproduce it looks like it's fixed now. Can you check it?

**Comment by EfimovVladimir** [comment]
fixed
