### ISSUE TITLE
add table screenshot to readme

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7152]

**Comment by manuhortet** [comment]
Can help with this if anybody describes slightly which table should I include, which df should I use and where in the readme do we want it :smile:

**Comment by scottdraves** [comment]
![screen shot 2018-04-12 at 5 06 51 pm 2](https://user-images.githubusercontent.com/963093/38704584-d1fc16d8-3e74-11e8-95d5-c916bd44d10b.png)
