### ISSUE TITLE
julia RDatasets won't load

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#72]
on ubuntu

Pkg.add("RDatasets")

produces

ERROR: failed process: Process(`sh -c 'cd /home/sheep/.julia/v0.2/.cache/RDatasets && git rev-parse --git-dir'`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:476
 in readbytes at process.jl:430
 in readall at process.jl:437
 in dir at git.jl:12
 in git at git.jl:18
 in cmd at git.jl:23
 in run at git.jl:24
 in set_remote_url at git.jl:96
 in prefetch at pkg/cache.jl:40
 in resolve at pkg/entry.jl:341
 in resolve at pkg/entry.jl:316
 in edit at pkg/entry.jl:24
 in add at pkg/entry.jl:44
 in add at pkg/entry.jl:48
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:22
 in cd at pkg/dir.jl:28
 in add at pkg.jl:19

**Comment by scottdraves** [comment]
this makes it hard to run the graphics demos :(

**Comment by melmac48** [comment]
closing, no repro
