### ISSUE TITLE
Add %classpath support for maven classifiers

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#7209]
Maven classifiers are sometimes used to distinguish platform-specific versions of an artifact (examples: [ND4J](https://nd4j.org/dependencies#platform-specific-binaries), [TensorFlow for Scala](http://platanios.org/tensorflow_scala/installation.html#installation-0-dependencies-1)).  The current `%classpath add mvn` magic doesn't have any way to specify a classifier.

Adding an additional optional classifier field seems pretty straightforward.

For this use case (platform-specific variation), maybe a dynamic capability like the one in `%classpath add dynamic` ought to be available to the mvn magic.  That would allow computing the desired Maven coordinates, making notebooks using this a little more portable.  But it's not obvious how to do that without the syntax getting ugly.

**Comment by scottdraves** [comment]
Hey Joe thanks for alerting me to this.  I see your point about needing dynamic access too.
Let me think about it.  When we did dynamic it was kind of a hurry and I knew there should be a general mechanism.  My first thought it something like what shells does, `$(code)`. 
It might as well work for all magics?

**Comment by jpallas** [comment]
Yeah, the possibility of having a generalized substitution mechanism crossed my mind, too.  Doing `$(code)` substitution on all magics doesn't sound crazy.  It might be weird if that code had any side effects, but that would probably be covered by a general "don't be surprised if doing strange things gives you strange results" disclaimer.  If the code threw an exception, you'd want to report it sensibly.  But if that all happens before the final version with substitutions is processed, the existing magic commands might not need any changes.
