### ISSUE TITLE
Kotlin syntax highlighting not working in Lab

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7222]
![screen shot 2018-04-23 at 2 32 23 pm](https://user-images.githubusercontent.com/963093/39145898-33b45976-4703-11e8-982f-595783d1a6f9.png)

**Comment by acq** [comment]
I encountered the same, but changing the following gave me back syntax highlighting.
![image](https://user-images.githubusercontent.com/4502798/41243989-0adc0c70-6da4-11e8-903c-0fab941a2a18.png)

CodeMirror uses `kotlin` for the mode, instead of `kt`

**Comment by scottdraves** [comment]
thanks!
