### ISSUE TITLE
TableDisplay Widget not working

### ISSUE THREAD

**Issue by ktc312** [twosigma/beakerx#7239]
Hi,
I just install beakerX and wants to try out beakerx.pandas_display_table(). My Jupyter notebook returns nothing, no table shows up and no error message. The table will shows if I run "beakerx.pandas_display_default()"

I'm running Jupyter notebook on a mac with:
OSX 10.12.6
beakerx==0.15.2
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
pandas==0.22.0

do I need to update some of the libraries or??

**Comment by scottdraves** [comment]
Hi, thanks for the report.  Those packages look fine.  What do you get if you run the following in a fresh Python3 kernel:
```
from beakerx import *
TableDisplay([{'y1':4, 'm3':2, 'z2':1}, {'m3':4, 'z2':2}])
```

**Comment by scottdraves** [comment]
And how did you install BeakerX?

**Comment by ktc312** [comment]
it returns
`TableDisplay(model={'alignmentForColumn': {}, 'alignmentForType': {}, 'cellHighlighters': [], 'columnNames': ['y1', 'm3', 'z2'], 'columnOrder': [], 'columnsFrozen': {}, 'columnsFrozenRight': {}, 'columnsVisible': {}, 'contextMenuItems': [], 'contextMenuTags': {}, 'fontColor': [], 'hasDoubleClickAction': False, 'headersVertical': False, 'rendererForColumn': {}, 'rendererForType': {}, 'stringFormatForColumn': {}, 'stringFormatForType': {}, 'subtype': 'ListOfMaps', 'tooManyRows': False, 'tooltips': [], 'type': 'TableDisplay', 'types': ['integer', 'integer', 'integer'], 'values': [['4', '2', '1'], ['', '4', '2']]})
`

and I use `pip install beakerx`
got `Successfully built beakerx
Installing collected packages: beakerx
Successfully installed beakerx-0.15.2`

**Comment by ktc312** [comment]
got this warning message when running pd.read_csv('some_mock_data.csv')

`[W 13:43:01.696 NotebookApp] 404 GET /static/beakerx.js?v=20180425134245 (::1) 10.69ms referer=http://localhost:8889/notebooks/test_beakerX_local.ipynb`

**Comment by scottdraves** [comment]
Did you run `beakerx install` after installing the package?

**Comment by ktc312** [comment]
I did not. Now it works fine! Thank you!!

**Comment by scottdraves** [comment]
excellent.

**Comment by MadushanPathirana** [comment]
Hi, I am having the same issue. I ran beakerx install and still having the issue.
( I am using Jupyter lab)
> from beakerx import *
TableDisplay([{'y1':4, 'm3':2, 'z2':1}, {'m3':4, 'z2':2}])

no output or warning for the above code.

**Comment by MadushanPathirana** [comment]
Ok , now I do not have the problem with jupyter note book. But I love to work with jupyter lab
