### ISSUE TITLE
make the data browser optional

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7240]
Add a UI Option for the Data Browser (similar to the one for publication).  Default should be to not show it.

https://github.com/twosigma/beakerx/pull/7232

**Comment by manchansan** [comment]
I have just downloaded the latest docker beakerx/beakerx.  I seem not able to find the "data browser" option.  Where can I turn it on?

**Comment by scottdraves** [comment]
Hi thank you for your question.
The browser is on master and will be released soon (this week).
The option to turn it on will be in the regular UI Options panel.
