### ISSUE TITLE
Config options for Scala Spark magic

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#7264]
Following up on discussion in #6993.

1. The UI always asks for a name for the Spark session.  There's no way to use more than one session in a notebook, so customizing the name isn't likely to be especially useful.  The `spark-shell` REPL always names the session `spark`.  I can see where customizing the name would be useful if code is being shared between a notebook and some external library or application, not sure about other use cases.

2. If you do try to connect to a second session, things get confused and the widget doesn't update, although I think the Spark configuration will get updated.  Not sure if it should check in the magic processing or when you try to connect, but it should probably warn the user instead of doing something confusing.

3. The Spark shell automatically does several imports.  I can see how some of those imports might not be desirable in every case.  And, again, if you're sharing code (cutting and pasting) between the notebook and compiled code (not the Spark REPL), it could cause confusion to have those imports in scope.  If the Spark magic does **not** automatically do those imports, maybe it could/should display a message like:
```
Spark session is named "spark".  Suggested imports for spark-shell compatibility:
import org.apache.spark.SparkContext._
import spark.implicits._
import spark.sql
import org.apache.spark.sql.functions._
```
Then the user could choose to paste those into the next cell.  Maybe it could be part of the text displayed after a successful "Connect"?

4. Right now the session name is declared as a `var` instead of a `val`.  That's a bug that prevents doing the imports (it generates `error: stable identifier required`).  This needs to be fixed regardless of how the preceding are resolved.  (Sorry I didn't note that before the merge.  Literally a one-character change.)

**Comment by scottdraves** [comment]
Thanks Joe.  Agree on 1 and it will be removed from the basic dialog (it should be an advanced option).  And we should handle 2 better.  Jarek will get to those next week when he gets back from holiday.  3 and 4 were easy I just did them, thanks for the suggestion.
