### ISSUE TITLE
filter/search boxes positioning and margins off

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7283]
![screen shot 2018-05-01 at 6 43 39 pm](https://user-images.githubusercontent.com/963093/39497114-c7e78696-4d6f-11e8-937c-9cc9ecb61569.png)

the boxes are not all enough and have a gap below them.

**Comment by MariuszJurowicz** [comment]
It's fixed in https://github.com/twosigma/beakerx/pull/7311
