### ISSUE TITLE
Checkbox not working correctly

### ISSUE THREAD

**Issue by ldmtwo** [twosigma/beakerx#7308]
The checkboxes seem to be sharing an underlying object. See the image for a proper explanation.

![screenshot from 2018-05-03 08-46-51](https://user-images.githubusercontent.com/7573669/39587548-a10d33be-4eae-11e8-8d39-d37349d2d7d8.png)

Specifics:
I'm just trying out beakerx now with python 3.6 from anaconda. I installed via:
conda install -c conda-forge beakerx ipywidgets

I grabbed the current examples:
git clone https://github.com/twosigma/beakerx.git

I set a cell in my notebook to this:

g = EasyForm("Field Types")
g.addCheckBoxes("Check Boxes 1", ["a", "b", "c", "d"], orientation=EasyForm.HORIZONTAL)
g.addCheckBoxes("Check Boxes 2", ["a", "b", "c", "d"], orientation=EasyForm.HORIZONTAL)
g.addCheckBoxes("Check Boxes 3", ["a", "b", "c", "e"], orientation=EasyForm.HORIZONTAL)
g.addButton("Go!", tag="run2")

I checked:
a
a,b
b

I clicked Go and ran the next cell:
result = dict()
for child in g:
    result[child] = g[child]
result

Which output:
{'Check Boxes 1': ['b', 'a', 'a', 'b', 'b'],
 'Check Boxes 2': ['b', 'a', 'a', 'b', 'b'],
 'Check Boxes 3': ['b', 'a', 'a', 'b', 'b']}

after checking 'e' in the 3rd row, it becomes this:
{'Check Boxes 1': ['b', 'a', 'a', 'b', 'b', 'e'],
 'Check Boxes 2': ['b', 'a', 'a', 'b', 'b', 'e'],
 'Check Boxes 3': ['b', 'a', 'a', 'b', 'b', 'e']}

**Comment by scottdraves** [comment]
thanks for the report, confirmed it, will fix shortly.
