### ISSUE TITLE
Typescript typings file needed to use widgets in typescript projects

### ISSUE THREAD

**Issue by jdundondev** [twosigma/beakerx#7322]
I was trying to use the BeakerXDataGrid in a JupyterLab MimeRenderer to display tabular results, but I'm not able to import the widget because the BeakerX npm package does not include the required type information. It would be great if the BeakerX module contained the required type information or a separate @types/beakerx-jupyterlab npm module was created.

**Comment by scottdraves** [comment]
@jdundondev This should be in 0.20.0 released today: https://www.npmjs.com/package/beakerx-jupyterlab
please let me know how it works for you, and if you do build a MimeRenderer with it.
