### ISSUE TITLE
images break html format in tables

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7335]
best solution might be a image format.
extending html format to handle this seems tricky.

![screen shot 2018-05-10 at 9 32 59 am](https://user-images.githubusercontent.com/963093/39872863-4c75db9c-5437-11e8-845c-06a6b0af60ee.png)

**Comment by MariuszJurowicz** [comment]
@scottdraves 
I've searched a little on supporting imgs in HTMLCellRenderer and imho it's too complex to get this working:
1. Async rendering the HTML on canvas when the image loads is tricky see (https://github.com/twosigma/beakerx/issues/7598),
2. I tried to render the svg with loaded image into the canvas and the result was the empty cell. I don't event know if this is possible to render into canvas this way.

So i think we should implement the `image` format and render the image with `drawImage` canvas method.
