### ISSUE TITLE
Replace slickgrid

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#735]
Slickgrid is not maintained anymore and has several issues.
We should replace it with another grip implementation, such as http://datatables.net/

**Comment by scottdraves** [comment]
That library looks great in general but selection support seems limited.
we need to confirm users can live without range of cells selections.

**Comment by jchendy** [comment]
I'm pretty sure we used DataTable originally and replaced it with SlickGrid for performance reasons. I'd definitely suggest digging through the old notes before selecting the new widget.

**Comment by scottdraves** [comment]
thanks for the tip, jeff

**Comment by abresler** [comment]
Checkout ember table as a possible option

## 

Alex Bresler

ASBC LLLC
917-455-0239

aragorntech.com |abresler@asbcllc.com alex@aragorntech.com | @abresler

**Comment by ildipo** [comment]
the branch ildipo/datatables contains a fully working slickgrid replacement with datatables. Some performance testing is required to make sure thinks are fine.
