### ISSUE TITLE
In Python3, table wont display if statement indented

### ISSUE THREAD

**Issue by gkatakou** [twosigma/beakerx#7358]
Using the Python3 kernel, tables won't display if the statement is indented. Contrived example below:

![image](https://user-images.githubusercontent.com/39306971/40064166-4c752ea8-58a2-11e8-9b07-d4071efc8a08.png)

![image](https://user-images.githubusercontent.com/39306971/40064266-7e124392-58a2-11e8-8f8e-055109ed10d6.png)

When no indentation
![image](https://user-images.githubusercontent.com/39306971/40064353-ab455db8-58a2-11e8-8c0f-338f3faa6f9c.png)

**Comment by scottdraves** [comment]
Conditional statements (the "if") don't return a value, so putting "display" into one of the branches like that doesn't do anything.

You can either put "display" at the end (like your last example) and use a conditional expression (X if C else Y), OR assign different values to a variable in the different branches, like this:
```
t = None
if x == 0:
    t = display
t
```
You can also use the standard display() function (http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Basics.html), which can display a widget from within an "if" statement:
```
t = TableDisplay(....)
if x == 0:
    display(t)
```

**Comment by gkatakou** [comment]
Thanks Scott. That's perfect. Was going blind from skimming documentation :-) Missed the display() function.

Cheers,
George
