### ISSUE TITLE
Naming conflicts with matplotlib caused by 'from beakerx import *'

### ISSUE THREAD

**Issue by LeeTZ** [twosigma/beakerx#7360]
In general a user could import 'plot' from matplotlib by calling:
`from matplotlib.pyplot import plot`
But if user have another cell importing everything from beakerx:
`from beakerx import *`
Then all plotting in matplot lib would fail with exception: 'TypeError: module object is not callable' Because beakerx.plot override the matplotlib plot.

**Comment by scottdraves** [comment]
yup thanks. IMO we should not recommend the import *, it's just bad style.
could also rename the "plot" submodule to avoid the conflict as a workaround.
