### ISSUE TITLE
Python EasyForm error for addList on Lab

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7381]
code:
```
f6 = EasyForm("form6")
f6.addList("field name6", ["onef6", "twof6", "threef6"], rows = 3)
f6
```
![image](https://user-images.githubusercontent.com/17744188/40245418-4ad4f4a6-5ace-11e8-9ccf-29d61b4eb3ae.png)

**Comment by piorek** [comment]
It's working now

![image](https://user-images.githubusercontent.com/743617/50219572-f6f57980-038f-11e9-828a-bb384915d199.png)
