### ISSUE TITLE
Python EasyForm error for addRadioButtons on Lab

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7382]
code:
```
from beakerx import *
f8 = EasyForm("form8")
f8.addRadioButtons("field name8", ["onef8", "twof8", "threef8"])
f8
```
![image](https://user-images.githubusercontent.com/17744188/40245895-90f94878-5acf-11e8-9ebf-2caa9b3b1342.png)

**Comment by piorek** [comment]
It's working now

![image](https://user-images.githubusercontent.com/743617/50219629-24dabe00-0390-11e9-85a3-6bba33797f05.png)
