### ISSUE TITLE
easyform date field only updates on enter

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7384]
it should not wait for the user to press enter, it should sync immediately like a regular text field.
same bug exists in python and groovy, so probably in the JS part of the widget.
to reproduce:
1) new groovy notebook, run this cell:
```
gdp = new EasyForm()
gdp.addDatePicker("mydate")
gdp
```
2) type "20100101" into the field that appears.
3) run this cell:
```
gdp['mydate']
```
result "null"
expected result is something like "Fri Jan 01 00:00:00 EST 2010"

if you press enter in the date field, then it works but this should be be required.

**Comment by MariuszJurowicz** [comment]
@LeeTZ 
I've tested this feature and it works fine for me. Could you test this one as well?

**Comment by LeeTZ** [comment]
Cannot reproduce, closing it.
