### ISSUE TITLE
spark UI improvements

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7416]
* hover over the "+" button it should say "Add property".  next to the button should be a link to https://spark.apache.org/docs/2.1.1/configuration.html#available-properties (with correct version).
anchor should read "property documentation".

* if a property is set via the code, it should appear in the UI, same as the master URL and executor # and memory. you can get the version from the session:
https://spark.apache.org/docs/2.3.0/api/java/org/apache/spark/sql/SparkSession.html#version--

* the + and - buttons should not be so wide.  "-" should be an "x".

* align the name/value pairs, should be the same for the 3 we support by default and the rest:

<img width="799" alt="screen shot 2018-05-23 at 4 50 59 pm" src="https://user-images.githubusercontent.com/963093/40450437-b28c6866-5ea9-11e8-97ca-c2a6d7d5acdb.png">

**Comment by scottdraves** [comment]
maybe link to this page https://spark.apache.org/docs/latest/configuration.html
or the appropriate version.

**Comment by jaroslawmalekcodete** [comment]
The 2nd point will be implemented https://github.com/twosigma/beakerx/issues/7331
