### ISSUE TITLE
jvm options empty

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7417]
BeakerX tab in tree view is empty until you click again:
![screen shot 2018-05-23 at 8 29 04 am](https://user-images.githubusercontent.com/963093/40424443-9db5593e-5e63-11e8-9350-228053d0b7c4.png)

**Comment by piorek** [comment]
@scottdraves 
1) are there any errors in console?
2) can you paste me content of your beakerx.json file
3) after 2) try to remove beakerx.json and see if that fixes the issue

**Comment by scottdraves** [comment]
currently not able to reproduce, i guess ignore for now.
