### ISSUE TITLE
Dependency missing?

### ISSUE THREAD

**Issue by piorek** [twosigma/beakerx#7421]
On a clean env, when doing 

`(cd beakerx; pip install -e . --verbose)`

im seeing

```
mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.0 requires cython, which is not installed.
```

**Comment by scottdraves** [comment]
Did you install py4j see the readme.

**Comment by piorek** [comment]
yes I did

I did everything step by step as described in README, after removing all envs 
It may be something new due to new version of ubuntu (Ubuntu 18.04 LTS)

**Comment by scottdraves** [comment]
i think we can ignore it
https://github.com/AnacondaRecipes/aggregate/issues/53
