### ISSUE TITLE
add interrupt button to spark progress

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7428]
an "x" aligned right that interrupts the job on the cluster.

**Comment by scottdraves** [comment]
how about a "bkg" button that allows the cell to finish even though it is still running.
as if you had run it with %%async?

**Comment by scottdraves** [comment]
yes the bkg button is a good idea.  it should be labeled with "&".  it should be to the left of the "x".
tooltip for "x" should be "interrupt spark job".  tooltip for "&" should be "put spark job in the background, let it complete asynchronously".

**Comment by LeeTZ** [comment]
@piorek Please help @jaroslawmalekcodete with frontend development, to style the widget.
