### ISSUE TITLE
further improve spark status

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7447]
* remove the big margin to the right of "Connected".
* no decimals in the storage memory box.  show integers 0-999, followed by KB, MB, GB, etc.  do not not show "B" by itself, if it's that small show "0 KB".
* hover over "x" says "Stop Spark Session".
* ~~increase the gap between the "connected" button and the 3 status numbers, make it about the same as the gap from the numbers to the "x".~~
<img width="342" alt="screen shot 2018-05-29 at 11 00 39 pm" src="https://user-images.githubusercontent.com/963093/40696514-26e8497a-6394-11e8-9ec7-02d5be4bd117.png">

**Comment by vishnu2kmohan** [comment]
Don't mean to hijack this issue but (thanks and kudos to) @krishnan-r has put together an impressive Spark Monitor at https://github.com/krishnan-r/sparkmonitor and we stand to benefit from a joint collaboration to implement his feature set esp. the timeline view, overall executor count/status and UI proxy for the BeakerX JVM Kernels.

**Comment by scottdraves** [comment]
yea that looks even better, would love it.
