### ISSUE TITLE
Save beakerx.json to paths specified in JUPTYER_CONFIG_DIR

### ISSUE THREAD

**Issue by vishnu2kmohan** [twosigma/beakerx#7468]
The `%%spark` magic is currently [hardwired](https://github.com/twosigma/beakerx/blob/0.18.2/kernel/sparkex/src/main/java/com/twosigma/beakerx/scala/magic/command/SparkMagicCommand.java#L62) to store its configuration at `Paths.get(System.getProperty("user.home") + File.separator + ".jupyter" + File.separator + "beakerx.json"))));`

It should instead honor paths (if) specified in the `JUPYTER_CONFIG_DIR` environment variable

e.g., I have `JUPYTER_CONFIG_DIR` set to `/mnt/mesos/sandbox/.jupyter` which yields the following acceptable config locations with `jupyter --paths`:
```
$ jupyter --paths
config:
    /mnt/mesos/sandbox/.jupyter
    /opt/conda/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /mnt/mesos/sandbox/.local/share/jupyter
    /opt/conda/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /mnt/mesos/sandbox/.local/share/jupyter/runtime
```

Instead, the Spark Magic fails to initialize when I run the notebook as the non-privileged user `nobody` because it attempts to store `beakerx.json` under `/nonexistent/.jupyter`, which as the name implies, is non-existent :)

```
$ grep nobody /etc/passwd
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
```

**Comment by scottdraves** [comment]
Thanks for the report, will get this into the next release.

**Comment by scottdraves** [comment]
the envar would be a good quick fix.
would it be more accurate to use Python API:
`jupyter_core.paths.jupyter_config_dir()`
?

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/blob/8893d41fb735aa8f727b1b40642f938bc5b7b525/kernel/sparkex/src/main/java/com/twosigma/beakerx/widget/SparkUiDefaultsImpl.java#L43

should this class be in python, ie reuse
https://github.com/twosigma/beakerx/blob/8893d41fb735aa8f727b1b40642f938bc5b7b525/beakerx/beakerx/environment.py#L48
could call into it with py4j?
