### ISSUE TITLE
update jupyter.org/widgets

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7475]
http://jupyter.org/widgets
should have the new table, like https://nbviewer.jupyter.org/gist/anonymous/d7dbf536abade987157c085b1850416d does.

to be done in https://github.com/twosigma/jupyter.github.io

**Comment by MariuszJurowicz** [comment]
https://github.com/twosigma/jupyter.github.io/pull/1

**Comment by scottdraves** [comment]
https://github.com/jupyter/jupyter.github.io/pull/286

**Comment by scottdraves** [comment]
change the text. 

> BeakerX includes widgets for interactive tables, plots, forms, and more.

to

> BeakerX includes widgets for interactive tables, plots, forms, Apache Spark, and more.

the paragraph ends ... 

> This makes connecting to spreadsheets quick and easy.

add a new paragraph:

> The table widget, shown below, is so fast because it's implemented with the [PhosphorJS Data Grid](http://phosphorjs.github.io/examples/datagrid/), part of Jupyter Lab's architecture.

**Comment by MariuszJurowicz** [comment]
https://github.com/twosigma/jupyter.github.io/pull/2
