### ISSUE TITLE
Clojure Easy Form Buttons

### ISSUE THREAD

**Issue by RobertAron** [twosigma/beakerx#7491]
I'm trying to create an easy form to run another cell in clojure and running into issues. I'm not sure if there is a different way to access easy forms or if this is actually a bug. Here's how to replicate the issue.

Place this into a cell, run it, and click the button.
```clojure
(doto (com.twosigma.beakerx.easyform.EasyForm. "Test Form")
    (. addButton "Click Me!" "test"))
```

It throws this error in the terminal and the kernel dies.
```shell
Exception: org.zeromq.ZMQException thrown from the UncaughtExceptionHandler in thread "Thread-0"
```

**Comment by scottdraves** [comment]
This is actually a bug, thanks for the report!
We never got as far as making this stuff work in Clojure.
Should be able to fix soon.
