### ISSUE TITLE
document this trick for spark

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7492]
suggested by @jarutis
```
%%spark
val jars = Set(ClasspathManager.getJars().toArray: _*).mkString(",")
SparkSession.builder().config("spark.jars", jars)
```

**Comment by jpallas** [comment]
Hmm.  It looks like `toArray` is being used as a shortcut to avoid importing `JavaConverters`.  I can't decide if that's sleazy or clever.  But can the classpath ever contain duplicates?  The `Set` seems unnecessary.

**Comment by scottdraves** [comment]
good point joe, i simplified it.
