### ISSUE TITLE
dark theme fixes

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7517]
EasyForm
==
the following components have a white bkg:

- [x] password,
- [x] combo box,
- [x] editable combo box,
- [x] list single,
- [x] and date.

also, 
- [x] the text in the form title is too black, 
- [x] the the border around the form is too bright.

Plots
==
- [x] please make the text (title, tick labels, text items, legend) the same brightness as regular body markdown text.

- [x] make the plot bkg same as page background (lose a rectangle).

- [x] the plot tooltips need dark theme:
![screen shot 2018-06-12 at 3 43 35 pm](https://user-images.githubusercontent.com/963093/41313239-7024b97a-6e57-11e8-93e3-715e51d6c3e1.png)

Table
==
- [x] fix color of selected cells and current cell (use blue and green, 266196 and 198e1d)
<img width="637" alt="screen shot 2018-06-12 at 10 47 45 pm" src="https://user-images.githubusercontent.com/963093/41327840-063d9b30-6e93-11e8-9bb5-fcd627cfb33d.png">

- [x] table tooltips
<img width="188" alt="screen shot 2018-06-12 at 10 52 41 pm" src="https://user-images.githubusercontent.com/963093/41327911-6855045c-6e93-11e8-8759-04e5d2d3b88d.png">

- [x] color by unique, use dark colors instead of light:
<img width="143" alt="screen shot 2018-06-12 at 10 58 20 pm" src="https://user-images.githubusercontent.com/963093/41328060-29809cea-6e94-11e8-90f8-9bde7e29326b.png">

- [x] there is an extra rectangle.  this rectangle turns green when you select and interact with the table.
it should not be there at all if the table is not focused.
<img width="168" alt="screen shot 2018-06-12 at 11 00 01 pm" src="https://user-images.githubusercontent.com/963093/41328111-6defe750-6e94-11e8-8a89-1509d3e35239.png">

- [x] for table headers and rulers, please match:
<img width="293" alt="screen shot 2018-06-12 at 11 03 32 pm" src="https://user-images.githubusercontent.com/963093/41328314-721a7448-6e95-11e8-8b56-c646a6bce747.png">
except stronger/more-contrast especially between even/odd rows.

**Comment by scottdraves** [comment]
also, the spark UI start spinner is too hard to see:
![screen shot 2018-06-13 at 10 37 50 am](https://user-images.githubusercontent.com/963093/41358258-fdec2c9a-6ef5-11e8-88c8-c9c66263fc0a.png)

**Comment by piorek** [comment]
Also made spark ui start spinner lighter blue in dark theme
