### ISSUE TITLE
Is it possible to configure a default JDBC connection in the kernelspec?

### ISSUE THREAD

**Issue by jdavidheiser** [twosigma/beakerx#7518]
I'd like to define multiple SQL kernelspecs, each of which defaults to a different database.  Is it possible to configure this in the kernel json, possibly through command line arguments or environment variables?

I saw #2506 about making this configurable, but that looked like it was through the UI, and I am only using the Beaker SQL kernel without the rest of the UI elements.

**Comment by scottdraves** [comment]
Hi James, interesting idea, I haven't thought about that.
If you want to do that it would have to get the default database from the kernel.json file.
That file has the parameters to the JVM, so you could set a property there.
It would be a one-line change to check for a property as the source of the default data source.
This isn't on our agenda but I don't see much downside, so I would welcome a PR.

**Comment by jdavidheiser** [comment]
Java is pretty far outside my wheelhouse, but this is important enough that I'm willing to take a stab at it.  Unfortunately, I'm running into #7042 and not familiar enough with these build systems to have much of an idea where to go from here.

**Comment by scottdraves** [comment]
Did you install maven into your build env?

**Comment by jdavidheiser** [comment]
Installing maven did the trick, and I was able to get something together and working.
