### ISSUE TITLE
Filtering with $ not working for Tables with column names with multiple spaces 

### ISSUE THREAD

**Issue by tcombes1** [twosigma/beakerx#7534]
Hello beakerX folks, you made my life so much easier, so thank you for the great work (especially with these tables!).

Found an issue (I think) that is able to be reproduced inside of the TableAPI.ipynb example notebook environment from inside Binder. (if more info is needed, please reach out). 

I created this simple table from a defined pandas dataframe to demonstrate and ran it in a new cell in the notebook:

```
table=TableDisplay(pd.DataFrame(data=[[4.0,'Hello',1.0],
                                      [2.9,'World',3.2]],
                                columns=['col 1try','col2','col3']))
table
```
It looks like this after I turn on the "Filter by Expression"
![filteredpresuccess](https://user-images.githubusercontent.com/23373651/41467844-d7b4cf7c-709f-11e8-853c-948b4ddddaf3.PNG)

I then attempt to filter the column 'col 1try' like this (even without using 3.0):
![filteredsuccess](https://user-images.githubusercontent.com/23373651/41467879-f0d45c8e-709f-11e8-8bd6-bbcfcb322956.PNG)

Which works as I would think. Wonderful. 

Now when I change the name of the column from 'col 1try' to 'col 1 try' (whitespace between 1 and try) like this:

```
table=TableDisplay(pd.DataFrame(data=[[4.0,'Hello',1.0],
                                      [2.9,'World',3.2]],
                                columns=['col 1 try','col2','col3']))
table
```
I get this after I turn on the "Filter by Expression":
![filteredprefailure](https://user-images.githubusercontent.com/23373651/41468098-ada189d6-70a0-11e8-9962-f626fea9b387.PNG)

I then attempt to filter the column 'col 1 try' like this:
![filteredfailure](https://user-images.githubusercontent.com/23373651/41468124-c509d0ce-70a0-11e8-8a87-2198f063ae74.PNG)

And get no filtering action. I've tried 3.0 and nothing still. From what I can tell it appears to be column names with non-consecutive whitespaces. I tried it with success for multiple whitespaces and it behaved as in the first scenario. 

I'm am unsure whether this is actually a bug or just a nuance of the table text parsing engine, or whether I should be using different syntax for the logic, so feedback would be appreciated. Thanks everyone!

**Comment by scottdraves** [comment]
wow thanks for the report!

**Comment by scottdraves** [comment]
related? https://github.com/twosigma/beakerx/issues/7295

**Comment by scottdraves** [comment]
https://github.com/twosigma/beakerx/pull/7537

**Comment by tcombes1** [comment]
Thank you @scottdraves !
