### ISSUE TITLE
yet further spark UI polish

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7535]
when you click start:
1) the "start" button should become de-active.  a good way to test this is with the master url "spark://1.2.3.4:5050" which will take a long time to try to connect and then error out.  you should not be able to click "start" while the spinner is going.
2) after connection succeeds, and the status display appears, the start button vanishes and is replaced by the "x" button.
3) the rest of the form should not shift vertically.
4) move the start/stop buttons to the right and into line with the status.

Here are mocks:

![screen shot 2018-06-19 at 5 54 41 pm](https://user-images.githubusercontent.com/963093/41627394-284de418-73ee-11e8-9086-0b29db80b8d8.png)

![screen shot 2018-06-19 at 5 54 41 pm2](https://user-images.githubusercontent.com/963093/41627393-283fb2ee-73ee-11e8-8efd-6565efb32ef3.png)

**Comment by piorek** [comment]
![image](https://user-images.githubusercontent.com/743617/41723317-0f88163c-756b-11e8-9ff3-3cd7beaa340c.png)
