### ISSUE TITLE
Add Python modules for Excel file reading (and writing?) 

### ISSUE THREAD

**Issue by yozlet** [twosigma/beakerx#7540]
The full set of current modules is [explained here](http://www.python-excel.org/) but having at least xlrd and openpyxl would help a lot.

EDITED TO ADD: Apologies for not being clear here. I'm working on the assumption that BeakerX is a  kitchen-sink distro for Jupyter, including many kernels and common modules that might be useful for data science. I'm proposing the addition of a couple of Python modules for handling Excel files. However, if I'm misunderstanding BeakerX's policies and aims, please feel free to close this. (It's easy enough to open a terminal and add those modules manually.)

**Comment by scottdraves** [comment]
Sorry I don't understand what you are suggesting, can you explain?

**Comment by yozlet** [comment]
@scottdraves Sorry for being so vague! I've updated the issue description.

**Comment by scottdraves** [comment]
No problem.  Not a kitchen sink, nearly all original content.
