### ISSUE TITLE
Kernels hang/timeout when using IPC transport

### ISSUE THREAD

**Issue by alfredo-gimenez** [twosigma/beakerx#7545]
When starting Jupyter with IPC specified (instead of default TCP) for the KernelManager:

```bash
jupyter notebook --KernelManager.transport=ipc
```

Kernels hang indefinitely and cause timeout errors like:

```
[W 17:02:42.238 NotebookApp] Timeout waiting for kernel_info reply from 097f9e85-a297-4ce3-8972-8ce09ca18747
```

Is IPC supported in beakerx? Any possible workarounds?

**Comment by scottdraves** [comment]
thanks for the report, never heard of this before, and don't have time to research it, but would welcome a pull request.

**Comment by altavir** [comment]
I do not think it is possible to support direct inter-process communication in beakerx. IPC is very OS-specific and therefore is not supported well in Java, hence the problems in beakerx.

The most efficient way to communicate between different languages for now is tcp socket. The performance difference between TCP socket and UNIX socket right now is negligibly small.

**Comment by alfredo-gimenez** [comment]
Thanks, I got it to work finally, using jzmq instead of jeromq (and some slight modifications to handle the ipc path correctly), which requires a JNI layer to an OS-specific zeromq installation. I wouldn't recommend adding that build complexity (and OS incompatibility) so won't submit a PR. 

My concern wasn't so much performance--file-based IPC provides simple and secure unix-based permissions. 

I'll go ahead and close but can answer questions about the IPC implementation.

**Comment by alfredo-gimenez** [comment]
Do you know if the spark UI through `%%spark` magic also requires TCP transport? When i try to run the magic on a notebook running with IPC, it just hangs indefinitely
