### ISSUE TITLE
Spark Dataset preview appears in wrong location

### ISSUE THREAD

**Issue by jpallas** [twosigma/beakerx#7561]
I have a notebook with four cells:
1. `%%classpath add mvn`
`org.apache.spark spark-sql_2.11 2.3.1`
2. `%%spark -c`
3. `val ds1 = spark.createDataset(Seq(("a", "this", 7), ("b", "this", 5), ("b", "that", 11)))`
4. `val ds2 = spark.range(1, 10)`

After running all four cells, my notebook looks like this:
![screen shot 2018-06-20 at 2 50 28 pm](https://user-images.githubusercontent.com/4623910/41686566-63b3a140-7499-11e8-9e97-a4630b8dbe9b.png)
If I click on the "Preview 10 Rows" button in cell 3, I get this:
![screen shot 2018-06-20 at 2 52 42 pm](https://user-images.githubusercontent.com/4623910/41686648-aeeb2d0e-7499-11e8-9c9f-0435b1df9262.png)

The preview of ds1 from cell 3 appears in the output area for cell 4, below the preview button and schema info for ds2.

If I click on ds2's preview button at this point, the Spark status indicator and data preview will appear below the preview of ds1 (but all still in the cell 4 output area).

**Comment by scottdraves** [comment]
Thanks for the report Joe, will test on my return.

**Comment by scottdraves** [comment]
confirmed.
