### ISSUE TITLE
JVM option, heap size, fp bug?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7562]
@jpallas 16:51
I set my BeakerX JVM size to "3", and sometimes I get this:
Invalid maximum heap size: -Xmx3.0g
It's like some kind of round-trip involving the settings is converting an integer to a floating point. Anyone else seen this? If I touch the setting the problem goes away.
It's not consistently reproducible for me. I haven't figured out what triggers it.

**Comment by scottdraves** [comment]
we had a NaN bug last week, maybe more to it than https://github.com/twosigma/beakerx/commit/ae166867114cced6751355f39a8dd8fb95aa58f9

**Comment by scottdraves** [comment]
maybe when the file is written by java, it changes the format?

**Comment by jpallas** [comment]
My first inclination is to blame Javascript, because it only has one type for numbers. I suppose some kind of JSON library screwup is possible.

Right now, my `.jupyter/beaker.json` file contains `"heap_GB": 3.0,`.

**Comment by scottdraves** [comment]
yea i can reproduce this by running a spark notebook, and saving a new profile.
seems like this is another manifestation of https://github.com/twosigma/beakerx/issues/7468

it also mangled the version field:
```
"version": 2.0,
```
that should just be an int.  but a fp value for heap should be OK.  very weird.

**Comment by scottdraves** [comment]
there is a 2nd bug: fp heap values are ok, unless they end in ".0".
this is in the normal python to JS path.  Just edit beakerx.json and replace "3" with "3.0" and then start a groovy notebook and it will die.

**Comment by jpallas** [comment]
> there is a 2nd bug: fp heap values are ok, unless they end in ".0".

That totally makes sense given this code:
```typescript
  public static normaliseHeapSize(heap_GB: number): string {
    if (heap_GB % 1 === 0) {
      return `${heap_GB}g`;
    }
    return parseInt(`${heap_GB * 1024}`) + 'm';
  }
```
