### ISSUE TITLE
loading Jupyter Lab fails on 0.20.1 with JS error `Plugin 'beakerx.javascript:factory' is already registered. `

### ISSUE THREAD

**Issue by jdavidheiser** [twosigma/beakerx#7594]
On Beakerx 0.20.1, I get an error about beakerx already being registered.  Firefox JS console output:

 ```
Error: Plugin 'beakerx.javascript:factory' is already registered. index.js:89
l9te/s</e.prototype.registerPlugin         index.js:89
t/<                                                           index.js:68:47
forEach                                                   self-hosted:268:13 
t                                                              index.js:68
o                                                             index.out.js:1408
```

Repro:
```
pip install beakerx==0.20.1
beakerx install --lab
```

**Comment by scottdraves** [comment]
Thanks for the report.

We ended up not using beakerx-jupyterlab-js, since its function was incorporated into jupyterlab directly, upstream. See https://github.com/twosigma/beakerx/pull/7028.

But I forgot to remove this from --lab.  I just did.

In the meantime, you can install for lab like this:
```
beakerx install
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install beakerx-jupyterlab
```

**Comment by liyingbin1213** [comment]
check if you install two same extensions but two authors. I solve this problem just disable one of them in menu.
