### ISSUE TITLE
in the new datatables UI

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#760]
when I click on the buttons to page through, the notebook scrolls, making it hard to click again.

move the buttons to the bottom, both the popup menu with the number of rows, as the row of buttons on top-right.

show/hide columns should not dark the background.

should use alternate row shading.

add an option to the popup for the number of rows with 10 rows.

if there are just a few columns, they get stretched to fill the whole page.

**Comment by ildipo** [comment]
These are implemented in ildipo/dtlookandfeel branch:
- move the buttons to the bottom, both the popup menu with the number of rows, as the row of buttons on top-right.
- should use alternate row shading.
- add an option to the popup for the number of rows with 10 rows.

This one requires changes to the vendor provided ColVis extension:
- show/hide columns should not dark the background.

This one requires changes to datatable itself:
- if there are just a few columns, they get stretched to fill the whole page.
  but it is in the pipeline of features so we might get it soon enough

**Comment by ildipo** [comment]
Closing this issue since it is partially done and merged - added issue #764 to track remaining items
