### ISSUE TITLE
Cannot specify maven binary (mvn) location for %classpath magic

### ISSUE THREAD

**Issue by alfredo-gimenez** [twosigma/beakerx#7643]
I'm on a system where the globally installed maven is both broken and untouchable... Whenever I run `%classpath add mvn ...` I get failures from the broken maven. I can run a locally installed maven just fine however.

Is there a way to specify which mvn binary to use when using `%classpath` ?

I could edit the `PATH` in the kernel.json but there is no way to append to the path there, only reassign it completely.

**Comment by scottdraves** [comment]
Thanks for your question.
Put the mvn you want to use in your PATH before starting jupyter.

**Comment by alfredo-gimenez** [comment]
Thanks, unfortunately it's not straightforward due to how we spawn Jupyter kernels, but if there's no other option I can make it work.
