### ISSUE TITLE
TableDisplay corrupts data in groovy

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#7645]
Conversation of map to TableDisplay corrupts map itself instead of creating a copy:

```Groovy
def b = ["a" : 2, "b" : 3, "c" : 4]
println(b)
println(b.a)
```
[a:2, b:3, c:4]
2

```Groovy
println(b)
println(b.a)
```

[type:TableDisplay, columnNames:[Key, Value], values:[[a, 2], [b, 3], [c, 4]], subtype:Dictionary]
null

**Comment by scottdraves** [comment]
thanks for the report but i am not able to reproduce, even if i remove the "def", which allows the 2nd cell to run.  what am i missing?

**Comment by altavir** [comment]
Sorry, it seems to I forgot to restart the notebook and forgot that  Groovy is copying links instead of values. The problem has something to do with autotranslation.
Try `beakerx.b = ["a" : 2, "b" : 3, "c" : 4]` and then `beakerx.b` in another cell. Second one is broken.

**Comment by altavir** [comment]
Correction even `beakerx.a = a; beakerx.a` is broken.

**Comment by scottdraves** [comment]
yes this is a deficiency, essentially values we get back from autotranslation are not converted to the right class, they are left in JSON.  Here's another case of it: https://github.com/twosigma/beakerx/issues/7610
Your case demonstrates it more clearly, actually.
