### ISSUE TITLE
Autotranslation error for javascript (jupyterlab)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7670]
see doc/groovy/GeneralAutotranslation.ipynb
![image](https://user-images.githubusercontent.com/17744188/42495464-d28dd8e6-842b-11e8-91f1-21ccb83bfb2f.png)

**Comment by MariuszJurowicz** [comment]
@EfimovVladimir 
It looks like you have the old js sources here. the `beaker.autotranslation` has been replaced by `beakerx.autotranslation`

**Comment by EfimovVladimir** [comment]
after update I get only this error
![image](https://user-images.githubusercontent.com/17744188/42498373-ae4e1ad2-8434-11e8-8257-5e1fb97faaba.png)
