### ISSUE TITLE
Scrollbar on table widget covers data

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#7685]
Screenshot of the issue below. I can fix it by dragging the table to be wider, but it would be nice to have the default width be a bit larger

![screenshot from 2018-07-12 23-04-26](https://user-images.githubusercontent.com/322311/42721214-744f1ab6-86eb-11e8-9105-dd4e06ab1df4.png)

**Comment by benmccann** [comment]
Btw, another thing that would be a small nice tweak would be if the top of the scrollbar were better aligned with the table header. It's a little weird that I can scroll past the table header currently. Mostly cosmetic though...

**Comment by piorek** [comment]
@benmccann can you see if this issue still exists? In current master I get this:

![image](https://user-images.githubusercontent.com/743617/47217336-593df800-d3a8-11e8-9999-bbd8216d0780.png)

**Comment by piorek** [comment]
@LeeTZ that scroll position could be tricky. Would have to analyse how phosphor/datagrid we are extending is handling that. 

How should it look? 
Horizontal scroll bar should be moved right by the width of left header.
Vertical scroll bar should be moved down by the height of top header.
How should the empty space we introduce this way look?

**Comment by benmccann** [comment]
Ok, great. I will trust that it's fixed then

I was thinking that it could be nice to align the top of the scrollbar like the below image. I photoshopped your screenshot to demonstrate. See the top-right corner of the table

![47217336-593df800-d3a8-11e8-9999-bbd8216d0780](https://user-images.githubusercontent.com/322311/47230697-cab58080-d37f-11e8-8b28-f5134416fad6.png)

**Comment by piorek** [comment]
@LeeTZ close this issue please
