### ISSUE TITLE
Allow reading CSV as an iterator

### ISSUE THREAD

**Issue by JD557** [twosigma/beakerx#7689]
The CSV `read` method (https://github.com/twosigma/beakerx/blob/dbe869b27e641095db6ebc3dee4b8e66104adb1c/kernel/base/src/main/java/com/twosigma/beakerx/fileloader/CSV.java) only allows reading CSVs to a `List`.

This makes parsing large CSVs impossible, even if the code is something like `new CSV().readFile("./large-file.csv").take(10).toList`.

Adding a `readIterator` method would fix this (and it would also be possible to add safer methods in Scala, such as `streamFile: Stream[Map[String, AnyRef]]`).

**Comment by LeeTZ** [comment]
Thank you for the contribution! @JD557
