### ISSUE TITLE
Configurable gist and nbviewer URLs

### ISSUE THREAD

**Issue by rseymour** [twosigma/beakerx#769]
It would be awesome to have the following two URLs (lines 59 and 74) configurable.

https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/java/com/twosigma/beaker/core/rest/PublishRest.java#L59

https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/java/com/twosigma/beaker/core/rest/PublishRest.java#L74

It was easy to put in our hosted github enterprise, local nbviewer and rebuild but it would be nice to have that as a config option as well.  I don't know how to do it offhand since my java skills drop sharply after hello world.  Are you using a certain config library that allows for easy access to the config.json key/values inside your compiled code?

Thanks (and thanks for electricsheep!)

**Comment by scottdraves** [comment]
You are very welcome Rich.
Yes those should definitely be config options.
Should be an easy to do, we'll see if we can fit it into the next release.
Thanks.

**Comment by rseymour** [comment]
Thanks!

**Comment by rseymour** [comment]
There is one issue with this, sorry I didn't get a chance to test it.  The problem that I can't get around is that the github enterprise puts the /raw at the end of the URL (meaning after the gist id).  I'm thinking of a way to insert it after, but I wonder what you all think.  I had just hardcoded it.

**Comment by scottdraves** [comment]
I think I know what you mean but to actually implement a fix, it would help if I could see your code.

**Comment by rseymour** [comment]
I will give you the full URL string when I'm back at work tomorrow.  I went into the enterprise api side, but it still looked like the API 'raw' link appended /raw instead of prepending it like github.com does.  Full bug report forthcoming.  And since you pulled the JSON config parsing into Java I may be able to send you a proper pull request to save you some work.  Thanks.

**Comment by rseymour** [comment]
My annoyance just fixed itself with our latest github enterprise upgrade.  Muchos gracias for the configurability.
