### ISSUE TITLE
error during install, notebook 5.6?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7708]
following current beakerx.com instructions to install for lab i got this error:
```
Enabling: beakerx
- Writing config: /Users/scottdraves/anaconda/envs/labx/etc/jupyter
    - Validating...
      beakerx 1.0.0 ^[[32mOK^[[0m
  File "/Users/scottdraves/anaconda/envs/labx/bin/jupyter-kernelspec", line 5
    from jupyter_client.kernelspecapp import KernelSpecApp.launch_instance
                                                          ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/scottdraves/anaconda/envs/labx/bin/beakerx", line 6, in <module>
    sys.exit(beakerx.run())
```
perhaps the notebook 5.6 release broke it?

**Comment by jaroslawmalekcodete** [comment]
@scottdraves What is your conda version? if you do not have conda version 4.4.9 or newer, please update it and try to install the lab again

**Comment by EfimovVladimir** [comment]
labx was have successfully installed on my Windows (conda 4.4.9)

**Comment by LeeTZ** [comment]
I could confirmed that in conda 4.3.14 & 4.3.30 it throws same error.
After updating conda to latest version(4.5.8), code for ENV_PATH/bin/jupyter-kernelspec changed:
```
#!/home/leetz/miniconda3/envs/beakerxtest/bin/python3.6
# -*- coding: utf-8 -*-
import re
import sys

from jupyter_client.kernelspecapp import KernelSpecApp

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(KernelSpecApp.launch_instance())
```
And then there is no such SyntaxError. Seems like the jupyter-kernelspec binary inside conda is contaminated. Updating conda solves the issue.

**Comment by wojciechowskim** [comment]
I stopped having this issue after updating conda to 4.5.4 on Ubuntu.

**Comment by scottdraves** [comment]
Thanks for the tips guys will try it out when I get back to that PC.

**Comment by scottdraves** [comment]
ty, works with 4.5.4
