### ISSUE TITLE
Changing from code doesn't work on EasyForm List (Scala)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7713]
![image](https://user-images.githubusercontent.com/17744188/43126776-5b868ef8-8f36-11e8-9934-d10ea4737614.png)

**Comment by jpallas** [comment]
An overload of `put` in the Scala `EasyForm` that takes a `Seq` and applies the `asJava` converter probably covers all the likely use cases.

**Comment by LeeTZ** [comment]
Great, thanks @jpallas
