### ISSUE TITLE
Docs Not Loading in Github

### ISSUE THREAD

**Issue by JohnOmernik** [twosigma/beakerx#7715]
The ipynb files try to load, and then github says "something when wrong... reload?" Reload doesn't work. 

This is a great tool to use, but if we can't get basic examples to load from Github it's really hard to start using it.

**Comment by LeeTZ** [comment]
Thanks for the report, we will look into that. In the meantime, I suggest using  [Binder](https://mybinder.org/v2/gh/twosigma/beakerx/1.0.0?filepath=StartHere.ipynb) to load our repo. The examples would be shown as hosted, interactive notebooks for you to explore with

**Comment by LeeTZ** [comment]
Seems like a transient issue. Cannot reproduce now.
