### ISSUE TITLE
dialogs have wrong style buttons

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#772]
they are missing the bootstrap class or something.

**Comment by melmac48** [comment]
Disconnect dialog should be skinned to match existing designs

**Comment by scottdraves** [comment]
actually it's not just the disconnect dialog, it's other dialogs too like the "file exists / overwrite" dialog.
and even the file save dialog, the OK/cancel at the bottom is the wrong style.
so this is a bigger deal than i thought, punting to 1.2

**Comment by buob** [comment]
Where exactly is the disconnect dialog?

**Comment by samccone** [comment]
Simply kill your server to reproduce
