### ISSUE TITLE
EasyForm incorrectly display legend element on Lab

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7723]
![image](https://user-images.githubusercontent.com/17744188/43317688-82074212-91a6-11e8-939d-8196744a6a17.png)

**Comment by piorek** [comment]
@LeeTZ @EfimovVladimir 
Cannot reproduce this in current master.
![image](https://user-images.githubusercontent.com/743617/43715051-6f42f4c4-997f-11e8-8e67-66628ef26a1c.png)
