### ISSUE TITLE
Better support for undo/redo at notebook level

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#773]
Current undo/redo operates only on cell delete and has only one undo level.
We need a better support with a larger history buffer and to support also cell reorg, cut and paste, etc.

**Comment by scottdraves** [comment]
this is very important.  we should make sure that our undo and editing is compatible with collaborative editing: https://github.com/twosigma/beaker-notebook/issues/128

**Comment by hydrosquall** [comment]
I just accidentally deleted a cell- in the meantime before undo is implemented, it would be nice to ask for a confirmation before deleting a cell.

**Comment by scottdraves** [comment]
actually we do support undo in that case.
just hit control z.

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves
