### ISSUE TITLE
Could not resolve dependencies when installed with pip3

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#7730]
Original issue here https://github.com/twosigma/beakerx/issues/6927

I got an error message saying that "Could not resolve dependencies for ..." when running the following magic in a Scala notebook. 
```
%classpath add mvn org.apache.spark spark-sql_2.11 2.2.1
```
Below is the information of notebook that run into issues. 

OS: Ubuntu 16.04
Notebook server: 5.6.0
Python: 3.5.2 [GCC: 5.4.0] installed using apt-get and packages managed by pip3
BeakerX 1.0.0
Open JDK 8
Maven: 3.3.9
Scala 2.11.12

**Comment by dclong** [comment]
```
%classpath add mvn com.google.code.gson gson 2.2.4
new com.google.gson.GsonBuilder().create().toJson("Hello", System.out)
```
generates the following error message and output.
<img width="1269" alt="screen shot 2018-07-22 at 2 38 01 pm" src="https://user-images.githubusercontent.com/824507/43043049-021ca010-8d50-11e8-83f1-60a9bff02bcf.png">
I have OpenJDK, Scala and maven installed using `apt-get`. 

<img width="1052" alt="screen shot 2018-07-22 at 2 40 34 pm" src="https://user-images.githubusercontent.com/824507/43043069-56c1c0d2-8d50-11e8-864f-44e234b60769.png">
Here's the Dockerfile if you want to dig into it. 

https://github.com/dclong/docker-jupyterlab-beakerx/blob/master/Dockerfile

And Dockerfile of the base image

https://github.com/dclong/docker-jupyterlab-py/blob/master/Dockerfile

**Comment by LeeTZ** [comment]
Thanks for the report @dclong, looking into that

**Comment by dclong** [comment]
@LeeTZ Any update on this?

**Comment by dankolesnikov** [comment]
I am experiencing the same issue as of August 29th, 2018. 

Latest Mac, pip, python 3, beakerx, maven, conda. Everything is installed and the latest versions. 
Loading local jars from ivy works fine. 

Currently blocked by this issue. Any updates? Can I help in any way?

**Comment by ljank** [comment]
@dankolesnikov I've solved this issue by adding `M2_HOME` env variable as suggested in https://github.com/twosigma/beakerx/issues/7452

```
export M2_HOME=/usr/share/maven

# run jupyter
```
