### ISSUE TITLE
With table output, I can't copy a value from a cell

### ISSUE THREAD

**Issue by JohnOmernik** [twosigma/beakerx#7740]
I am on a mac running on Firefox in Jupyter Lab. When I try to copy a cell value to use in a query/filter, there is no right click menu, and when I do cmd + c to copy the highlighted cell, the value does not get added to my clipboard.

**Comment by LeeTZ** [comment]
Hello John, cmd + c is implemented by the browser and it won't recognize our table. To copy cells, select them, then go to the top left corner of the table, click the menu (three dots) and select "Copy to clipboard". Thanks.

**Comment by JohnOmernik** [comment]
Perfect thank you!
