### ISSUE TITLE
Histogram Groovy has wrong scale for default mode

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7743]
See http://localhost:8888/notebooks/doc/groovy/Histogram.ipynb (cell with Default is Overlap)
Setup initWidth == initHeight. After that we expect to see square area of chart.

![image](https://user-images.githubusercontent.com/17744188/43890791-61d29670-9bd0-11e8-8154-32212bbce4ae.png)

**Comment by piorek** [comment]
@LeeTZ if you updated documentation as we discussed please close this one
