### ISSUE TITLE
Grid OutputContainer works wrong 

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7745]
See http://localhost:8888/notebooks/doc/groovy/OutputContainers.ipynb (cell with grid output)

plot1 has styles and looks as at the picture. 
There it has right styles. But legend located above plot area
![image](https://user-images.githubusercontent.com/17744188/43894940-5619ee80-9bdc-11e8-990d-8bbac9e197bc.png)

On grid outputContainer are wrong  this:
-  plot1 lost his styles on grid output Container (another plots also lost styles)
-  plot3 is empty
![image](https://user-images.githubusercontent.com/17744188/43895108-e3818774-9bdc-11e8-97ad-ddd831f33d11.png)

**Comment by piorek** [comment]
@EfimovVladimir is the legend overlapping plot still present? I can't reproduce it. 
![image](https://user-images.githubusercontent.com/743617/45753416-0fcb8300-bc19-11e8-8cc8-482e3a051407.png)

**Comment by EfimovVladimir** [comment]
@piorek  Now I have this view
![image](https://user-images.githubusercontent.com/17744188/45755420-119c4300-bc27-11e8-9c8d-95517c728e4e.png)

console log:
![image](https://user-images.githubusercontent.com/17744188/45755501-4a3c1c80-bc27-11e8-9412-ee75d4c1a569.png)

then I run next cell 'grid output containers' and get this view for tabbed output
![image](https://user-images.githubusercontent.com/17744188/45755792-fb42b700-bc27-11e8-9f53-8c555293fb79.png)

By the way 'grid' output works fine now

**Comment by LeeTZ** [comment]
When resizing the plot inside the output container, the legend stays there. It should be moving and keep relative distance between the plot when resizing.
