### ISSUE TITLE
check non Promises objects in latest Lab

### ISSUE THREAD

**Issue by LeeTZ** [twosigma/beakerx#7747]
Łukasz Pior found that there were some major changes some objects are not Promises anymore, some properties were renamed. We should check these Promises to make sure everything works.

**Comment by afshin** [comment]
https://github.com/jupyterlab/jupyterlab/blob/8413909e6c954288d5d3f3725ad2733a39fec125/CHANGELOG.md#changes-for-developers

There were some backward-incompatible changes between 0.32 and 0.33 (in semver while your version is less than 1.0, minor versions count as major, with backward incompatible changes allowed). The most prominent promise that is now synchronous is the `connectTo` mentioned in that change log.

**Comment by piorek** [comment]
**Fixed**
- [x] connectTo
- [x] panel.notebook renamed to panel.content

**Comment by piorek** [comment]
Found another issue I'm not seeing in the changelog. Publishing gist is not working.

Invoking it via toolbar or context menu causes:
```
Modal.js:42 Uncaught (in promise) TypeError: Class constructor f cannot be invoked without 'new'
    at new t (Modal.js:42)
    at e.create (gistPublishModal.js:73)
    at gistPublishModal.js:40
```
@LeeTZ you can merge PR I did and I will fix gist related issue in separate PR

**Comment by piorek** [comment]
@afshin can you please check if you will find any info what may cause errors when extending Dialog class.

**Comment by piorek** [comment]
Dialog problem fixed
