### ISSUE TITLE
The Legend element doesn't work

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7758]
The option `all` works fine. But another options don't works. 
See http://localhost:8888/notebooks/doc/groovy/CategoryPlot.ipynb or any Chart with legend

![image](https://user-images.githubusercontent.com/17744188/44263111-5860dc80-a226-11e8-9008-f4ec284cbf5a.png)

![image](https://user-images.githubusercontent.com/17744188/44263150-80504000-a226-11e8-818e-8558d1254f26.png)

**Comment by piorek** [comment]
@LeeTZ this can be closed
