### ISSUE TITLE
Without importing beakerx, pandas dataframe output is by default forced to be rendered using widgets?!

### ISSUE THREAD

**Issue by pybokeh** [twosigma/beakerx#7766]
Hi, after installing beakerx, when I do df.head(), the output of my dataframe is a nice, javascript widget of the dataframe even when I haven't imported beakerx.  Also, when I want to save the .ipynb as html, the resulting html file doesn't display the dataframe.  I see from [this](https://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/python/TableAPI.ipynb) that I can revert to default pandas dataframe rendering, but why by default, my pandas dataframe is being rendered with the beakerx javascript widget without even importing beakerx?  This is strange or unexpected behavior.  
  
Also, when I uninstall beakerx, now I can't render my pandas dataframe at all!  It seems my jupyter installation is now no good.  So I re-installed beakerx, and now I can render my dataframe.  Is there a proper way to uninstall beakerx without messing up my pandas dataframe rendering capability?  

I uninstalled by first doing:
beakerx uninstall, then did pip uninstall beakerx

**Comment by LeeTZ** [comment]
Thanks for the report we will definitely look into that.
In the meantime, you could get the HTML table back by:
```
beakerx.pandas_display_default()

**Comment by dclong** [comment]
Actually I reported this issue before and it was fixed. Don't know why this issue come up again.

https://github.com/twosigma/beakerx/issues/6794

**Comment by NumesSanguis** [comment]
Having the same issue with beakerx 1.1.0 that without any import it's being used, but I have the additional problem that tables don't show up anymore at all: https://github.com/twosigma/beakerx/issues/7819 (includes info about my conda env setup)

**Comment by pybokeh** [comment]
@LeeTZ beakerx.pandas_display_default() doesn't work for me.

Error message:
AttributeError: module 'beakerx' has no attribute 'pandas_display_default'

beakerx version==1.0

**Comment by whiteboxbatteries** [comment]
> @LeeTZ beakerx.pandas_display_default() doesn't work for me.
> 
> Error message:
> AttributeError: module 'beakerx' has no attribute 'pandas_display_default'
> 
> beakerx version==1.0

Per https://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/python/TableAPI.ipynb,
you actually want to call:
`beakerx.object.beakerx.pandas_display_default()`
