### ISSUE TITLE
Jupyterlab installation hangs

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#7781]
Freezes on `beakerx-jupyterlab@file:../extensions/beakerx-jupyterlab-1.0.0.tgz` on windows.

The same goes for 1.1.0.

**Comment by Techdread** [comment]
Weird I got it to install in Jupyterlab had to update Jupyterlab to the latest on Win10 using Conda.

Though BeakerX is best run on the older Jupyter notebook, as Javascript stuff is horrible broken, 

JupyterLab people I think have made a mistake in that regard, pity as it is a brilliant piece of software.

**Comment by altavir** [comment]
I have two computers with Windows 10 and beakerx. At first is stopped working on one, and now it also does not work on the other one. The notebook works as expected. I think that the problem is not with beakerx itself, but with yarn installation procedure.

**Comment by altavir** [comment]
The problem seems to be resolved by forcibly upgrading to `jupyterlab=0.34.7` which comes with new yarn. For some reason it does not upgrade itself automatically. It would be good to mention it as minimal version.
