### ISSUE TITLE
How to use customized maven repositories?

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#7793]
When using the following command? I'm behind a enterprise firewall and must use the company's own maven repositories instead of the public ones. 
```
%%classpath add mvn
org.apache.spark spark-sql_2.11 2.3.1
```

**Comment by jpallas** [comment]
Did you try the `%classpath config resolver` magic command?

**Comment by dclong** [comment]
Didn't know this before. I checked and found the following in the doc for Groovy. I'll give it a try.

![image](https://user-images.githubusercontent.com/824507/45662388-52fff600-bb34-11e8-9c0d-1a99fd06c195.png)
