### ISSUE TITLE
Updated Ubuntu branch has broken groovysh comet handshake

### ISSUE THREAD

**Issue by planetmcd** [twosigma/beakerx#78]
Somewhere in the process of resolving merge conflicts between master and the ubuntu branch or somewhere in a new commit, something has gone awry.  I'll see what I can figure out but if it is obvious to anyone else, please let me know.

15:53:51.144 [QUIET] [system.out] nginx-stderr>2014/03/06 15:53:51 [error] 26272#0: *418 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "POST /groovysh/cometd/handshake HTTP/1.1", upstream: "http://127.0.0.1:8806/cometd/handshake", host: "mojotech-mcd:8801", referrer: "http://mojotech-mcd:8801/beaker/"

**Comment by scottdraves** [comment]
I retested the groovy plugin on ubuntu and can't reproduce this problem.
using current code, on a 12.04 VM.

**Comment by planetmcd** [comment]
When you say current code, you rebased the Ubuntu branch against master?  If so, I probably made an error in the resolving the merge conflicts.

**Comment by scottdraves** [comment]
oh sorry i misunderstood -- no i testing the ubuntu branch as it is.
after i look at the node PR i will bring it up to date and see what happens.

**Comment by planetmcd** [comment]
Thanks.  The updated Ubuntu branch was my attempt at bringing it upto date.

**Comment by scottdraves** [comment]
i merged master into ubuntu and pushed it.
everything seems fine.

**Comment by planetmcd** [comment]
Let me rebase from there.

**Comment by planetmcd** [comment]
The new Ubuntu branch won't run as is for me.
core:copyNginx FAILED

Might be something slightly different with my distro/version.  If it is generic, would you share the vm image your using?

**Comment by scottdraves** [comment]
i suspect you have left the branch as that task is commented out.
look at core/build.gradle here:
https://github.com/twosigma/beaker-notebook/compare/ubuntu

**Comment by planetmcd** [comment]
Scott,
FYI, Sam is seeing the same issue on a Mac on master.  
Mike

**Comment by planetmcd** [comment]
I think it is missing running this:
gradle plugin:groovy:installApp

**Comment by scottdraves** [comment]
That's great you figured this out.  I was worried!
Indeed those commands are at the end of https://github.com/twosigma/beaker-notebook/wiki/Ubuntu-build-and-run
They aren't dependencies of the run target because we are about to make the plugins be separate repositories that may or may not be checked out.  Part of Ang's reorg will be to make gradle automatically detect and build them.
Sorry you got bit by this burr!

**Comment by planetmcd** [comment]
No worries.  I'm glad it was a pibkac and not something larger to be
concerned about.

**Comment by planetmcd** [comment]
I'll have Sam check on his box to see if that was the culprit for him as well.
