### ISSUE TITLE
Ability to copy the contents of table to clipboard

### ISSUE THREAD

**Issue by harmbuisman** [twosigma/beakerx#7813]
BeakerX gives nice features, but I lose one important one compared to standard jupyter: the ability to copy paste the text from a table (e.g. cell(s) or column header) to a clipboard. I like to request this feature.

Desired functionality:
- click-drag over cell highlights text in either table cell or column header which I can then copy to clipboard using CTRL-C or right-click copy

**Comment by LeeTZ** [comment]
Hi @harmbuisman You could do selection, go to the menu at the top left, then click on "Copy to clipboard" to copy that. Ctrl-C is implemeted by browser it cannot understand the table widgets.

**Comment by harmbuisman** [comment]
@LeeTZ, ah that was unexpected that this copies the selected cells, thanks.

Any chance this menu item can move to the cell? That would satisfy the right click copy requirement for cells.
