### ISSUE TITLE
How do you add scala compiler options in beakerx? 

### ISSUE THREAD

**Issue by vikramrao619** [twosigma/beakerx#7827]
Hi,

In sbt, it is straightforward to add compiler options as described [here](https://docs.scala-lang.org/overviews/compiler-options/index.html). Is there a way to do this in a beakerx Scala notebook?

**Comment by LeeTZ** [comment]
Hello @vrao85  you could add JVM options in BeakerX panel in tree view. An introduction to that could be find in our doc/groovy/JavaArgs.ipynb
