### ISSUE TITLE
BoundedIntText widget bug (GroovyAPI)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7830]
when we set a value by code the boundedIntText don't restrict value on groovy 
![image](https://user-images.githubusercontent.com/17744188/47148827-799f8100-d2da-11e8-9523-85333cde10b2.png)

Expected result should be as on python
![image](https://user-images.githubusercontent.com/17744188/47148874-a05db780-d2da-11e8-94dd-028486934fcd.png)

**Comment by jaroslawmalekcodete** [comment]
the issue was fix here https://github.com/twosigma/beakerx/pull/7835
