### ISSUE TITLE
Bug with deleting rows in the Python Table API

### ISSUE THREAD

**Issue by rdhyee** [twosigma/beakerx#7833]
I've had success in using the Python Table API to add a context menu to delete a given row.  However, with a specific table I've run into a bug.  The code is at 

https://github.com/rdhyee/beakerx/blob/delete-row-bug/doc/python/delete_row_bug.ipynb

When I run the notebook, the table displays properly

![image](https://user-images.githubusercontent.com/153266/47171189-e73cb480-d2bc-11e8-9ef1-004f448a0a70.png)

However after I invoke the delete row context menu

![image](https://user-images.githubusercontent.com/153266/47171372-66ca8380-d2bd-11e8-93d6-4a264c1457e2.png)

my table is scrambled up -- but I still have 4 rows:

![image](https://user-images.githubusercontent.com/153266/47171452-911c4100-d2bd-11e8-94bf-c431126ec2b7.png)

Am I deleting a row from the table incorrectly or is there a bug?

**Comment by LeeTZ** [comment]
Thanks @rdhyee it should be a bug. I saw error from browser console:
```
index.js?v=20181018221654:120257 TypeError: Cannot read property 'index' of undefined
    at Object (index.js?v=20181018221654:22509)
    at index.js?v=20181018221654:62677
    at index.js?v=20181018221654:62637
    at index.js?v=20181018221654:62691
    at index.js?v=20181018221654:62637
    at ColumnManager.getColumn (index.js?v=20181018221654:24333)
    at BeakerXDataGrid.getColumn (index.js?v=20181018221654:121332)
    at HeaderCellRenderer.getRenderer (index.js?v=20181018221654:47136)
    at HeaderCellRenderer.drawBackground (index.js?v=20181018221654:47050)
    at HeaderCellRenderer.TextRenderer.paint (index.js?v=20181018221654:61784)
```

We will look into that.
