### ISSUE TITLE
Issue with selection/indexing of cells

### ISSUE THREAD

**Issue by gkatakou** [twosigma/beakerx#7834]
I'm having an issue with correct cell selection using a beakerx table with Python3. Incorrect cell is selected after either having sorted a column, or having filtered on a column using the 'Search for Substring' menu option. Not sure if I'm doing something wrong or it's a bug. Demonstration below. In the first two screenshots, the right click content menu function PrintCell has been used on the highlighted cells and returns the correct data. In the third screenshot, column labelled 'b' has been sorted Ascending. Used PrintCell on the highlighted cell again, but it does not show the correct data, and in fact shows the same data for that cell previous to sorting. Seems to be a discrepency between the Model and the View.

<img width="460" alt="shot1" src="https://user-images.githubusercontent.com/39306971/47250844-dcc51b00-d474-11e8-983f-a7eecc4236db.png">

<img width="460" alt="shot2" src="https://user-images.githubusercontent.com/39306971/47250878-a2a84900-d475-11e8-9b52-c4ec7f0b5cc7.png">

<img width="460" alt="shot3" src="https://user-images.githubusercontent.com/39306971/47250879-a89e2a00-d475-11e8-8f7c-b41f17cefd30.png">

Cheers,

George

**Comment by rdhyee** [comment]
@gkatakou I can see whether I can reproduce your problem if you provide a Jupyter notebook with your code and tell us what version of beakerx you're running.

**Comment by gkatakou** [comment]
Hi @rdhyee,

Sure. beakerx version is 1.2.0. Attached is a notebook that demonstrates issue.

[gk-notebook.ipynb.zip](https://github.com/twosigma/beakerx/files/2508805/gk-notebook.ipynb.zip)

Cheers,

George

**Comment by rdhyee** [comment]
@gkatakou I can confirm the problem running the code on version 1.2.0.  In fact, you can run an earlier version 0.12.0 of beakerx on Binder by:

* Launching an instance at https://mybinder.org/v2/gh/twosigma/beakerx/0.12.0?filepath=doc/python/TableAPI.ipynb

and then

* pasting your code fragment into the notebook and running the cell:

```Python
from IPython.display import display
from beakerx import *

def printCell(row, col, tableDisplay):
    print("Row = " + str(row))
    print("Col = " + str(col))
    print("Val = " + tableDisplay.values[row][col])
    
myTable = [
    {'a':'cat','b':'pear','c':'truck'},
    {'a':'dog','b':'apple','c':'bus'},
    {'a':'cow','b':'orange','c':'car'}
]
myTable = TableDisplay(myTable)
myTable.addContextMenuItem("print cell", printCell)

display(myTable)
```
I'm surprised that others (including myself) haven't caught and reported this problem beforehand.

**Comment by gkatakou** [comment]
@rdhyee Good to see it has been confirmed, and wasn't me doing something stupid 😄

**Comment by gkatakou** [comment]
@rdhyee Hey Raymond. What's the status of this. Is it officially a bug that will be fixed anytime soon?

**Comment by LeeTZ** [comment]
Thanks for the report we will look into that.

**Comment by gkatakou** [comment]
@LeeTZ Hi. Not sure if I'm doing something wrong, but I am still getting the same result. I have uninstalled and re-installed beakerx in my Ubuntu environment (pip install beakerx, install beakerx), but I get the same issue. In addition, I have tried in Binder, and I get the same problem. Has this been resolved?
