### ISSUE TITLE
BeakerX interactive tables no longer being used by default in JupyterLab

### ISSUE THREAD

**Issue by dhendry** [twosigma/beakerx#7844]
* After a recent update, beakerx interactive tables no longer seem to be used by default in JupyterLab
* Moreover, the following code from the example notebook: https://github.com/twosigma/beakerx/blob/master/doc/python/TableAPI.ipynb no longer works:

```
import pandas as pd
from beakerx import *
beakerx.pandas_display_table()
```

and fails with

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-242a38fe0d48> in <module>
      1 import pandas as pd
      2 from beakerx import *
----> 3 beakerx.pandas_display_table()

NameError: name 'beakerx' is not defined
```

After looking at the commits, it seems like https://github.com/twosigma/beakerx/commit/2ec11222802f13af82da9b9bc8e7eadc66ae4a4f is the culprit, and after calling the following, things work as expected:

```
import pandas as pd
from beakerx import *
runtime.BeakerX.pandas_display_table()
```

Not sure where the bug is here, not having the widget loaded by default or documentation being out of date.

For reference:

```
jupyter labextension list
JupyterLab v0.35.3
Known labextensions:
   app dir: XXXXXX
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        beakerx-jupyterlab v1.2.0  enabled  OK
```

**Comment by jaroslawmalekcodete** [comment]
Hi
because of https://github.com/twosigma/beakerx/issues/7766 we decided to move beakerx to beakerx.object so you need to import beakerx as follows
```
from beakerx.object import beakerx
```
for sure we will have to update the documentation

**Comment by LeeTZ** [comment]
Thanks for the report, doc is updated and it should work well.
