### ISSUE TITLE
beakerx.showProgressUpdate from Scala

### ISSUE THREAD

**Issue by pschatzmann** [twosigma/beakerx#7859]
I am not able to call beakerx.showProgressUpdate() from Scala:
- beakerx.showProgressUpdate("", 1) gives the error: <console>:99: error: the result type of an implicit conversion must be more specific than AnyRef beakerx.showProgressUpdate("", 1)
- beakerx.showProgressUpdate("", new java.lang.Integer(1)) gives the error: java.lang.NoSuchMethodException: com.twosigma.beakerx.NamespaceClient.showProgressUpdate(java.lang.String, java.lang.Integer)

I think it would help if you change the method definition from   public void showProgressUpdate(String message, int progress)  to   public void showProgressUpdate(String message, Integer progress) in  com.twosigma.beakerx.NamespaceClient

**Comment by jpallas** [comment]
The `beakerx` object currently does everything through the dynamic interface, and that's the real problem.  A quick workaround would be to use `_beakerx`.  If `beakerx` should support the `BeakerXClient` interface, then it needs to implement that interface.

**Comment by pschatzmann** [comment]
You are right! In Groovy the beakerx variable is of the class com.twosigma.beakerx.NamespaceClient and this seems to be different in Scala: _beakerx.showProgressUpdate("",50) is working as expected!

Thanks for the clarification...

**Comment by jpallas** [comment]
I think it's confusing that the `beakerx` object in Groovy has both static behavior and dynamic fields, while in Scala some of the static behavior happens to work but some doesn't.  I mentioned in [an earlier discussion](https://github.com/twosigma/beakerx/issues/7618#issuecomment-401652687) that I don't think the `dynamicApply` support in the `beakerx` object is useful.

Either `_beakerx` should be documented, or `beakerx` should implement the static behavior.  I think the latter would be more consistent with other kernels.

**Comment by pschatzmann** [comment]
I think the following approach should work consistently across the different kernels:

var client = NamespaceClient.getBeakerX()
client.showProgressUpdate("", progress )
