### ISSUE TITLE
QuandlRequestFailedException when use Tablesaw

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7876]
http://localhost:8888/notebooks/doc/groovy/Tablesaw.ipynb

![image](https://user-images.githubusercontent.com/17744188/49370070-2c4d6680-f704-11e8-9695-c2d0f7345525.png)

**Comment by benmccann** [comment]
This generally works. I'm guessing that Quandl was having a temporary outage. Can you try again?

**Comment by benmccann** [comment]
Also of note, Quandl4j 2.0.0 doesn't give great error messages. I've fixed that in master, but am waiting for the next release to be cut: https://github.com/jimmoores/quandl4j/commit/c4067f6f079a01b38058f8f394df71e05d1b65c9
