### ISSUE TITLE
%%classpath add mvn support proxy

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#7891]
Many working environment in companies cannot access the public maven directory directly.

**Comment by ctrueden** [comment]
Is it necessary for the magic to have this feature? Did you try something like
```groovy
System.setProperty("http.proxyHost","myproxy.domain")
System.setProperty("http.proxyPort","8080")
```
before invoking the magic?

**Comment by dclong** [comment]
@ctrueden Good point! I didn't try but I think it will work as I have been using this way to pass around the firewall in other tools. Will have a try and give a update here later.
