### ISSUE TITLE
Table with 0 rows should display column names

### ISSUE THREAD

**Issue by LeeTZ** [twosigma/beakerx#7924]
![screenshot from 2019-01-15 14-51-08](https://user-images.githubusercontent.com/3425710/51208622-2ee2d480-18dc-11e9-92b1-a0a1c9b46c36.png)

If we load a table with 0 rows, we should output some summary of the column names, and gave a warning of "This table has 0 rows."

**Comment by jaroslawmalekcodete** [comment]
![info](https://user-images.githubusercontent.com/21952713/51470053-173f9c00-1d73-11e9-8c78-2a21dceccb63.png)
