### ISSUE TITLE
Time difference between python and groovy

### ISSUE THREAD

**Issue by piorek** [twosigma/beakerx#7932]
loading and displaying same data in python and groovy results in different output for time column

python
```import pandas as pd
from beakerx import *
from beakerx.object import beakerx
df = pd.read_csv('../resources/data/interest-rates.csv')
df['time'] = df['time'].str.slice(0,19).astype('datetime64[ns]')
table = TableDisplay(df)
table
```

groovy
```
import com.twosigma.beakerx.table.*

table = new TableDisplay(new CSV().read("../resources/data/interest-rates.csv"))
table
```

 src | value 
-----|----------
 csv | 1990-01-30 19:00:00.000 -0500
 python | 1990-01-30 20:00:00.000 +0100
 groovy | 1990-01-30 00:00:00.000 +0100

![image](https://user-images.githubusercontent.com/743617/51536565-4aa22980-1e4c-11e9-954a-05fbaf13a523.png)

**Comment by jaroslawmalekcodete** [comment]
now the date are equal but In python we need use
 ```
         df['time'] = df['time'].str.slice(0, 27).astype('datetime64[ns]')
```
![tabledisplaytimecolumn](https://user-images.githubusercontent.com/21952713/52057376-238eda80-2565-11e9-92fa-5f3bd42e12f4.png)

the difference between csv and groovy/python is related with how we interpret date, maybe it is time to change it.
