### ISSUE TITLE
Investigate on solution to get user input in Java kernel  

### ISSUE THREAD

**Issue by LeeTZ** [twosigma/beakerx#7933]
A java user may use class like Scanner to read from user input. 
We should provide a solution to read from user input in Java kernel as well.

**Comment by jaroslawmalekcodete** [comment]
look at an example ``` http://localhost:8888/notebooks/test/ipynb/java/stdin.ipynb ```

**Comment by ghost** [comment]
Just a quick comment - this would be very valuable for using BeakerX to help teach a Java course. Any progress on getting Scanner to work? If stdin is working, are there any examples to demonstrate? Finally, is there anything beyond "conda update -c conda-forge beakerx" to get the new version?

**Comment by ghost** [comment]
Quick question: I looked through the 'handle stdin' commit and found stdin.ipynb. Last night I updated JupyterHub and BeakerX on my server. Today I tried the example "stdin.ipynb" and it does not work i.e. does not pause for keyboard input and shows error instead:ERROR: java.util.NoSuchElementException: No line found.
How do I obtain or enable this patch?

**Comment by ghost** [comment]
Just tried keyboard input using the Xeus cling (C++) kernel. It works in a way that is exactly what I'd love to see in BeakerX - Java. Here's the example program. It puts up a small box and waits for user input...
(note: Xeus-cling doesn't like 'main' outside C++ classes, so I commented that out).

#include <iostream>
using namespace std;
//int main() {
    char name[64];
    cout << "Please enter your name ";
    cin >> name;
    cout << "Welcome " << name << endl;
//}
