### ISSUE TITLE
Error: Circular reference detected (Python table)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7935]
try http://localhost:8888/notebooks/test/ipynb/python/TableAPIPythonTest.ipynb notebook
and cell with code:
```
import pandas as pd
from beakerx import *
from beakerx.object import beakerx
#Display mode: TableDisplay Widget
beakerx.pandas_display_table()

pd.DataFrame(data=np.zeros((5,5)), index=pd.Int64Index([0, 1, 2, 3, 4], dtype='int64'))
```

![image](https://user-images.githubusercontent.com/17744188/51612931-7a782c80-1f33-11e9-89f6-7a7c0adf65cb.png)

**Comment by EfimovVladimir** [comment]
#6963

**Comment by EfimovVladimir** [comment]
At the same time the  `pd.Float64Index()` works fine
![image](https://user-images.githubusercontent.com/17744188/51676178-e5367000-1fe6-11e9-9328-01553c4c008e.png)

**Comment by piorek** [comment]
@EfimovVladimir @LeeTZ https://github.com/twosigma/beakerx/commit/f460b909b3e04629b262610fa3b4dbbd28b87d1b fixes this but someone with more knowledge about python should look at this
