### ISSUE TITLE
The Legend not visible (Python)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7937]
See http://localhost:8888/notebooks/test/ipynb/python/ChartingTest.ipynb
![image](https://user-images.githubusercontent.com/17744188/51686770-11131f00-2002-11e9-95db-bfca517dc77e.png)

see right result on groovy: 
http://localhost:8888/notebooks/test/ipynb/groovy/XChartingTest.ipynb
![image](https://user-images.githubusercontent.com/17744188/51686893-5f282280-2002-11e9-87ca-e5ddc863426f.png)

**Comment by piorek** [comment]
![image](https://user-images.githubusercontent.com/743617/51838331-44a5c000-2306-11e9-9202-f2af258b85a7.png)
@EfimovVladimir @LeeTZ cannot reproduce this

**Comment by EfimovVladimir** [comment]
@piorek 
console log on browser:
![image](https://user-images.githubusercontent.com/17744188/51840436-26978a00-231d-11e9-8059-bae3782562e3.png)
