### ISSUE TITLE
Legend position doesn't work (Python)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7938]
we can't set TOP position for HeatMap Legend 
see http://localhost:8888/notebooks/test/ipynb/python/ChartingTest.ipynb
![image](https://user-images.githubusercontent.com/17744188/51687424-87645100-2003-11e9-9e5a-81ab8117244a.png)

see right result on groovy:
http://localhost:8888/notebooks/test/ipynb/groovy/XChartingTest.ipynb
![image](https://user-images.githubusercontent.com/17744188/51687504-b1b60e80-2003-11e9-9b94-7ff9592c7286.png)

**Comment by EfimovVladimir** [comment]
#7937

**Comment by piorek** [comment]
![image](https://user-images.githubusercontent.com/743617/51838799-b29eb700-2307-11e9-8f2a-6c90108f386d.png)
@EfimovVladimir @LeeTZ Works for me
