### ISSUE TITLE
warning message doesn't appear (Python)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7939]
see http://localhost:8888/notebooks/test/ipynb/python/ChartingTest.ipynb
![image](https://user-images.githubusercontent.com/17744188/51688257-3fdec480-2005-11e9-8a6f-59dc5c21a375.png)

see right result on groovy:
http://localhost:8888/notebooks/test/ipynb/groovy/XChartingTest.ipynb
![image](https://user-images.githubusercontent.com/17744188/51688345-6dc40900-2005-11e9-8320-800219a4cca9.png)

**Comment by piorek** [comment]
![image](https://user-images.githubusercontent.com/743617/51839027-4a040a00-2308-11e9-8c77-3ec50d497922.png)
@LeeTZ @EfimovVladimir Works 4 me
