### ISSUE TITLE
The Points in Plot doesn't work (Python)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7940]
try code
```
plot3 = Plot()
plot3.add(Points(y=[1, 3, 6, 3, 1], 
              x=[1, 2, 3, 4, 5], 
              size=10, 
              shape=ShapeType.DIAMOND))
```
we don't see any Point element
![image](https://user-images.githubusercontent.com/17744188/51741271-87b62800-20a7-11e9-85fa-a488047bd9c7.png)

expected result:
![image](https://user-images.githubusercontent.com/17744188/51741713-c39dbd00-20a8-11e9-8950-d4aa8bc568a6.png)

**Comment by piorek** [comment]
![image](https://user-images.githubusercontent.com/743617/51839169-c4cd2500-2308-11e9-8dbb-9779391b7967.png)
@LeeTZ @EfimovVladimir cannot reproduce it

**Comment by EfimovVladimir** [comment]
@piorek 
console log on browser
![image](https://user-images.githubusercontent.com/17744188/51841152-fa7d0880-231e-11e9-95bf-16d6d707f60c.png)
