### ISSUE TITLE
The TimePlot doesn't work (Python)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7941]
see http://localhost:8888/notebooks/test/ipynb/python/PlotPythonTest.ipynb
cell with TimePlot (milliseconds)
![image](https://user-images.githubusercontent.com/17744188/51742115-df559300-20a9-11e9-9c03-5b4ec2045cf9.png)
cell with TimePlot (nanoseconds)
![image](https://user-images.githubusercontent.com/17744188/51742205-20e63e00-20aa-11e9-8ee9-cafc2124160d.png)

**Comment by EfimovVladimir** [comment]
#7940

**Comment by piorek** [comment]
@EfimovVladimir @LeeTZ Reproduced. 

It looks like data that I'm getting from python is different than data in groovy.
In groovy shape property for a point is "rect"
In python it's "7"

**Comment by EfimovVladimir** [comment]
see this [code](https://github.com/twosigma/beakerx/pull/7931/files#diff-841395705044869a1d14027b3062e487R171)  
using Enum.name is fixed the bug
