### ISSUE TITLE
duplicate of index column

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7946]
Does we need every time when we download table add new index column?
see http://localhost:8888/notebooks/doc/python/TableAPI.ipynb
Let say you have table and you format and save it.
![image](https://user-images.githubusercontent.com/17744188/51977716-320fc000-2499-11e9-9f18-e76006c96868.png)

Then you display that new table.
The new table will have duplicate for `index` column
![image](https://user-images.githubusercontent.com/17744188/51977774-5cfa1400-2499-11e9-84e5-c2c2a1102745.png)

**Comment by EfimovVladimir** [comment]
for groovy kernel, the `index` column is added to 5 position
![image](https://user-images.githubusercontent.com/17744188/53419303-abdc9000-39ea-11e9-9759-b7fc0a30028c.png)

**Comment by EfimovVladimir** [comment]
Our decision for this issue:
1. don't adding new column when save table to csv file. 
2. don't use own label for `index` column (i.e. the same as pandas).
3. if there is `index` in csv its normal column

**Comment by jaroslawmalekcodete** [comment]
I think this issue is only about 1st point, it fixes problem with duplicate index.
I suggest to create new issue for 2nd and 3rd point, because the issue won't fix a bug but provide similar behaviour like in pandas view

**Comment by EfimovVladimir** [comment]
[issue #7994](https://github.com/twosigma/beakerx/issues/7994) for 2nd and 3rd  points
