### ISSUE TITLE
table setRowFilter() method doesn't work (Python, Groovy)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7958]
let see http://localhost:8888/notebooks/doc/python/TableAPI.ipynb

![image](https://user-images.githubusercontent.com/17744188/52272168-f7090300-2956-11e9-9d85-e2cfa2f86bdf.png)

http://localhost:8888/notebooks/doc/groovy/TableAPI.ipynb
![image](https://user-images.githubusercontent.com/17744188/52272399-bc539a80-2957-11e9-9c78-355e288dd819.png)

**Comment by jaroslawmalekcodete** [comment]
it is duplication of https://github.com/twosigma/beakerx/issues/7925

**Comment by jaroslawmalekcodete** [comment]
it can be closed because of #7925
