### ISSUE TITLE
any plan for upgrading to groovy 2.5.x?

### ISSUE THREAD

**Issue by jizhilong** [twosigma/beakerx#7962]
Hi,
   I noticed the groovy version has stayed at 2.4.3 for a long time(since the last upgrade at #1624), and groovy has evolved a lot,  the latest stable branch is 2.5.x,  so is there any plan for beakerx to upgrade to groovy 2.5?

**Comment by LeeTZ** [comment]
Good point, we are working on that now.

**Comment by jizhilong** [comment]
> Good point, we are working on that now.

that's awesome, thanks.
