### ISSUE TITLE
Install via Conda but without JDK11

### ISSUE THREAD

**Issue by geoHeil** [twosigma/beakerx#7968]
Installing via:
`conda install -c conda-forge ipywidgets beakerx` as mentioned http://beakerx.com results in a JDK 11 being installed to this specific environment.

This is causing 2 problems for me:
- I am developing with spark and it only supports JDK8
- in a corporate environment with custom certificates the Conda installed JDK is using a different keystone than the IT managed JDK8 installation

How can I install beakerX but use the existing JDK8 which is managed by IT?

**Comment by lakemove** [comment]
I am running beakerx-1.3.0 in corporate env also, beakerx auto select my jdk8 from env(JAVA_HOME and $PATH).

**Comment by geoHeil** [comment]
@lakemove did you manually set your PATH / JAVA_HOME after Conda's overwrites? In my case Conda is overwriting it.

**Comment by geoHeil** [comment]
Temporary workaround is to 

in:
`~/.conda/envs/<<my_env>>/etc/conda/activate.d/openjdk_activate.sh
` 
disable:
 
`#export JAVA_HOME=$CONDA_PREFIX
` 
and set
 
`export PATH=$JAVA_HOME/bin:$PATH`

now I can again use the IT managed JDK installation.
