### ISSUE TITLE
No connection to kernel

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#8011]
To reproduce this error: build new environment, install beakerx by our instruction, run jupyter notebook, open any notebook.
The result no any kernels will works.
![image](https://user-images.githubusercontent.com/17744188/54426120-1cdcb100-4728-11e9-9fb2-0277425b3d07.png)

browser console:
![image](https://user-images.githubusercontent.com/17744188/54426311-88268300-4728-11e9-8b83-4261abad410d.png)

warning on console:
```
c:\aconda3\envs\test_env\lib\site-packages\notebook\base\zmqhandlers.py:284: Run
timeWarning: coroutine 'WebSocketHandler.get' was never awaited
  super(AuthenticatedZMQStreamHandler, self).get(*args, **kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by EfimovVladimir** [comment]
looks like the problem is on 5.7.4 version of notebook. 

Issue was fixed after I downgraded notebook to version 5.7.2
`conda install notebook=5.7.2`

**Comment by jaroslawmalekcodete** [comment]
related with https://github.com/twosigma/beakerx/issues/8009
working on it

**Comment by jaroslawmalekcodete** [comment]
fixed in 8009
