### ISSUE TITLE
Spark/Scala Issues

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#8034]
1. Spark (in the Scala kernel) cannot read in parquet files (throws IllegalArgumentException)
2. DataFrame.count throws IllegalArgumentException
```
%%classpath add mvn
org.apache.spark spark-core_2.11 2.3.1
org.apache.spark spark-sql_2.11 2.3.1
org.apache.spark spark-hive_2.11 2.3.1
```
```
import org.apache.spark.sql.SparkSession

val spark = SparkSession.builder().master("local")
    .appName("IO")
    .getOrCreate()
spark
```
![image](https://user-images.githubusercontent.com/824507/56068565-2f043c00-5d34-11e9-83f0-6264d4cfb2c1.png)

![image](https://user-images.githubusercontent.com/824507/56068675-90c4a600-5d34-11e9-9893-9a9ba57af606.png)

**Comment by jaroslawmalekcodete** [comment]
Hi @dclong 
I created [an example](https://github.com/twosigma/beakerx/blob/jarek/8034_parquet_files/test/ipynb/scala/parquet.ipynb) in branch **jarek/8034_parquet_files** and it looks like the parquet files work well

![parquetExample](https://user-images.githubusercontent.com/21952713/56425570-30de7a00-62b5-11e9-9a64-f49a44c83583.png)

please provide your example that will allow us to reproduce it

**Comment by dclong** [comment]
@jaroslawmalekcodete Thank you for taking time investigating the issue. Please follow the steps below to reproduce the issue. 

1. Pull the Docker image `dclong/jupyterhub-ds`.
```
docker pull dclong/jupyterhub-ds
```
2. Start a container by running the following command. 
```
docker run -d \
    --log-opt max-size=50m \
    -p 8000:8000 \
    -e DOCKER_USER=`id -un` \
    -e DOCKER_USER_ID=`id -u` \
    -e DOCKER_PASSWORD=`id -un` \
    -e DOCKER_GROUP_ID=`id -g` \
    -e DOCKER_ADMIN_USER=`id -un` \
    -v `pwd`:/workdir \
    -v `dirname $HOME`:/home_host \
    dclong/jupyterhub-ds
```
3. Login to the JupyterHub server using your username on the host machine as both user name and password. For example, if you launched a container on a machine with ip `some_ip` using the above command and your user name on the machine is `user`, then you visit `http://some_ip:8000` in your browser and login with `user` as both the user name and password. 

4. Now run your previous example and you will see the error messages. 

## Comment

The Docker image `dclong/jupyterhub-ds` that I built is based on `pip` instead of `conda`. I'm not sure whether the issue is due to some missing components.

**Comment by jaroslawmalekcodete** [comment]
Hi @dclong 
It looks like your docker container uses java 11
![parquet_java_version](https://user-images.githubusercontent.com/21952713/56588664-19b8c880-65e4-11e9-8da2-0a51685e4194.png)

beakerx supports java 8 https://github.com/twosigma/beakerx/blob/master/configuration.yml#L6

from your docker container

![dockerContainerJdks](https://user-images.githubusercontent.com/21952713/56588687-23dac700-65e4-11e9-9c3c-03a0ab84b5a5.png)

please try to remove java11 or change java alternatives to java8

**Comment by dclong** [comment]
@jaroslawmalekcodete Thank you very much! It seems that `apt-get install openjdk-8-jdk maven gradle` installed openjdk-11-jdk in my Docker image. Install openjdk-8-jdk specifically resolves the issue.
