### ISSUE TITLE
Issue updating cells

### ISSUE THREAD

**Issue by gkatakou** [twosigma/beakerx#8060]
BeakerX 1.4.1

Issues when updating cells using similar code to the documentation examples notebook. 

**Example 1:**

```
from beakerx import *
from beakerx.object import beakerx

dataToUpdate = [
   {'a':1, 'b':2, 'c':3},
   {'a':4, 'b':5, 'c':6},
   {'a':7, 'b':8, 'c':9}
]
tableToUpdate = TableDisplay(dataToUpdate)
tableToUpdate.setColumnOrder(["a","b"])
tableToUpdate.setColumnVisible("c", False)
tableToUpdate.addCellHighlighter(TableDisplayCellHighlighter.getUniqueEntriesHighlighter("a", TableDisplayCellHighlighter.SINGLE_COLUMN))
display(tableToUpdate)
```
Running this code produces the following table:

![image](https://user-images.githubusercontent.com/39306971/58142420-4a932880-7c8a-11e9-95cb-e772399ab8d1.png)

Updating a cell with either of the following two code blocks:

```
tableToUpdate.updateCell(1,"b",99)
tableToUpdate.sendModel()
```
or
```
tableToUpdate.values[1][1] = 99
tableToUpdate.sendModel()
```

produces the following result:

![image](https://user-images.githubusercontent.com/39306971/58143016-a959a180-7c8c-11e9-9783-4d117ee5608c.png)

As can be seen, the unique entries highlighter in column 'a' has been lost.

**Example 2: (using setColumnFrozen)**

```
from beakerx import *
from beakerx.object import beakerx

dataToUpdate = [
   {'a':1, 'b':2, 'c':3},
   {'a':4, 'b':5, 'c':6},
   {'a':7, 'b':8, 'c':9}
]
tableToUpdate = TableDisplay(dataToUpdate)
tableToUpdate.setColumnOrder(["a","b"])
tableToUpdate.setColumnVisible("c", False)
tableToUpdate.setColumnFrozen("a", True)
tableToUpdate.addCellHighlighter(TableDisplayCellHighlighter.getUniqueEntriesHighlighter("b", TableDisplayCellHighlighter.SINGLE_COLUMN))
display(tableToUpdate)
```

Running this code produces the following table:

![image](https://user-images.githubusercontent.com/39306971/58142745-a3af8c00-7c8b-11e9-9999-923c4412b06c.png)

Updating a cell with either of the two update code blocks shown previously produces the following result:

![image](https://user-images.githubusercontent.com/39306971/58142826-ea9d8180-7c8b-11e9-986f-23a871c59656.png)

As can be seen, the unique entries highlighter in column 'b' has been lost (the frozen column in column 'a' remains in place), the cells that should not be visible are now being displayed (column 'c'), and more importantly, the cell update has not taken place. 
​

**Comment by qqingvarqq** [comment]
I want to attempt this one.
