### ISSUE TITLE
Highlighting for full row (Python)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#8062]
Highlighting doesn't work for `time` column.
code:
```
table = TableDisplay(pd.read_csv('../../resources/data/interest-rates-small.csv'))
table.addCellHighlighter(TableDisplayCellHighlighter.getHeatmapHighlighter("m3", TableDisplayCellHighlighter.FULL_ROW))
table
```
result:
![image](https://user-images.githubusercontent.com/17744188/58253174-81436e80-7d70-11e9-971a-170130bb6c9a.png)

**Comment by EfimovVladimir** [comment]
#8026

**Comment by LeeTZ** [comment]
We won't highlight String type or datetime columns, will only do numerical columns.

**Comment by EfimovVladimir** [comment]
In case we use `TableDisplayCellHighlighter.FULL_ROW` constant we expect that whole row will have the same color as base column. 
Let's see example above. We add highlighting for whole row by values from column `m3`. See column `y30` that have string type (because NaN value) but works correctly.

**Comment by jaroslawmalekcodete** [comment]
the issue was fixed in https://github.com/twosigma/beakerx/issues/8072
