### ISSUE TITLE
highlighting for full row (Groovy)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#8072]
related with #8062  
code:
```
table8 = new TableDisplay(new CSV().read('../../resources/data/interest-rates-small.csv'))
table8.addCellHighlighter(TableDisplayCellHighlighter.getHeatmapHighlighter("m3", TableDisplayCellHighlighter.FULL_ROW))
table8
```
result:
![image](https://user-images.githubusercontent.com/17744188/59508836-f4e02380-8eb7-11e9-9674-c92678259a94.png)

**Comment by jaroslawmalekcodete** [comment]
Hi @EfimovVladimir 
look at rows from 4  to 7, there are "NaN" strings.
In groovy "NaN" is treated as String so this is why there is no highlighting in this column.
It looks like "interest-rates-small.csv" file is prepared for python,
please try to replace "NaN" to "0" in interest-rates-small.csv

**Comment by EfimovVladimir** [comment]
In case we use `TableDisplayCellHighlighter.FULL_ROW` constant we expect that whole row will have the same color as base column.
