### ISSUE TITLE
EasyForm errors 

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#8086]
try http://localhost:8888/notebooks/doc/groovy/EasyForm.ipynb notebook

![image](https://user-images.githubusercontent.com/17744188/60720573-dd82dc00-9f33-11e9-8bad-d0cd6f05e7b1.png)

**Comment by piorek** [comment]
Reproduced. Happens with ipywidgets@7.5.0 but with ipywidgets@7.4.2 everything is ok.

**Comment by ghost** [comment]
```
pipenv uninstall ipywidgets
pipenv install ipywidgets==7.4.2
``` 
But still getting error

**Comment by piorek** [comment]
@EfimovVladimir @LeeTZ fixed in master
