### ISSUE TITLE
beakerx: command not found

### ISSUE THREAD

**Issue by ghost** [twosigma/beakerx#8092]
Trying to get beakerx working with `pipenv` and an existing `JupyterLab` setup.

```
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
$ jupyter labextension install beakerx-jupyterlab
$ npm i beakerx-jupyterlab
```

```
$ pipenv install beakerx
$ beakerx install

'-bash: beakerx: command not found'
```

At this point, I have restarted the JupyterLab server but `import beakerx` is not rendering pandas df's as beakerx tables.

**Comment by HashRocketSyntax** [comment]
Update: it works successfully in JupyterLab like so `from beakerx.object import beakerx`.

**Comment by HashRocketSyntax** [comment]
It does however, work in JupyterLab like so: `from beakerx.object import beakerx`
