### ISSUE TITLE
Allow plugins to access CodeMirror areas

### ISSUE THREAD

**Issue by prosconi** [twosigma/beakerx#817]
It would be nice if a plugin had access to the CodeMirror objects in order to perform extra customization. A couple examples would be advanced auto complete functionality or Tooltip popups when hovering over text.

**Comment by scottdraves** [comment]
yea this sounds useful.

**Comment by scottdraves** [comment]
API for https://github.com/BayardRock/FsBeaker/blob/master/plugins/eval/fsharp/fsharp.js#L223
