### ISSUE TITLE
DROP TABLE IF EXISTS fails on non-existent table

### ISSUE THREAD

**Issue by Ben-Epstein** [twosigma/beakerx#8175]
When I run DROP TABLE IF EXISTS using %%sql magic on a table that exists, it's dropped. But when I run it on a table that does not exist, I get the following error

<code>java.sql.SQLNonTransientConnectionException: The DDM parameter value 0x1149 is not supported.  An input host variable may not be within the range the server supports.  The connection has been terminated.</code>

I'm running BeakerX release 1.3.0 installed with Conda on the Python3 Kernel.

**Comment by jaroslawmalekcodete** [comment]
Hi @Ben-Epstein 
can you try to use newer version of Beakerx?, I mean 1.4.1 (https://anaconda.org/conda-forge/beakerx).
I tried "DROP TABLE IF EXISTS" on this version 1.4.1 and It looks like everything works fine. If you reproduce the problem please send us your example.

**Comment by Ben-Epstein** [comment]
Hi @jaroslawmalekcodete 
Thanks for the reply! I will try to run this on my system and see if I can reproduce. Why is the latest release (1.4.X) not represented on the Github releases or on Dockerhub? Is it beta?

**Comment by LeeTZ** [comment]
Thanks Ben, we will release a new version of BeakerX to Github and Dockerhub soon.

**Comment by Ben-Epstein** [comment]
Closing this as I'm no longer seeing the issue
