### ISSUE TITLE
should be able to specify types per column 

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#818]
a user asked to be able to put html into a table output display.  right now there is no way to do this.
it is a more general problem though.  in addition to html, we should be able to specify string vs numeric (for sorting) vs dates (for display in their own way).

there are possibly other column attributes like width or color that would be useful.

**Comment by scottdraves** [comment]
and should be able to specify number precision per table colums https://github.com/twosigma/beaker-notebook/issues/820

**Comment by scottdraves** [comment]
hover over the column to see the type?

**Comment by ildipo** [comment]
The data type and number precision is handled by the new datatable output display.
Types are automagically detected by language backend and the user can manually change them.
What was the 'html in a cell'?

**Comment by scottdraves** [comment]
raw html string, so you could have hyperlink in the table, for example.

**Comment by ildipo** [comment]
ok - at the moment the output display is filtering the special characters.
We could add a 'display type' like 'rawstring' where this filtering is disabled.

**Comment by ildipo** [comment]
We also need a way to programmatically override type autoselection

**Comment by scottdraves** [comment]
yes but as a start, just adding the rawstring (better to just call it "html") type so it can be selected from the table options GUI would be good.
