### ISSUE TITLE
can't run Jupyter Lab

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#8181]
After recreating new conda env and installation Lab I can't run it.

Traceback (most recent call last):

>   File "C:\Aconda3\envs\labx17\Scripts\jupyter-lab-script.py", line 9, in <module>
>     sys.exit(main())
>   File "C:\Aconda3\envs\labx17\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
>     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
>   File "C:\Aconda3\envs\labx17\lib\site-packages\traitlets\config\application.py", line 663, in laun
> ch_instance
>     app.initialize(argv)
>   File "<C:\Aconda3\envs\labx17\lib\site-packages\decorator.py:decorator-gen-7>", line 2, in initialize
>   File "C:\Aconda3\envs\labx17\lib\site-packages\traitlets\config\application.py", line 87, in catch
> _config_error
>     return method(app, *args, **kwargs)
>   File "C:\Aconda3\envs\labx17\lib\site-packages\notebook\notebookapp.py", line 1679, in initialize   self.init_webapp()
>   File "C:\Aconda3\envs\labx17\lib\site-packages\jupyterlab\labapp.py", line 404, in init_webapp
>     super().init_webapp(*args, **kwargs)
>   File "C:\Aconda3\envs\labx17\lib\site-packages\notebook\notebookapp.py", line 1442, in init_webapp
>   self.http_server.listen(port, self.ip)
>   File "C:\Aconda3\envs\labx17\lib\site-packages\tornado\tcpserver.py", line 152, in listen
>     self.add_sockets(sockets)
>   File "C:\Aconda3\envs\labx17\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
>     self._handlers[sock.fileno()] = add_accept_handler(
>   File "C:\Aconda3\envs\labx17\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
>     io_loop.add_handler(sock, accept_handler, IOLoop.READ)
>   File "C:\Aconda3\envs\labx17\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
>     self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
>   File "C:\Aconda3\envs\labx17\lib\asyncio\events.py", line 501, in add_reader
>     raise NotImplementedError
> NotImplementedError

the version tornado:
`tornado                   6.0.3            py38hfa6e2cd_0    conda-forge`

**Comment by jaroslawmalekcodete** [comment]
There seems to be a problem in win Tornado 6.0.3 version,
the jupyter laboratory works for Linux

**Comment by EfimovVladimir** [comment]
the problem was in old version jupyter Lab from conda
