### ISSUE TITLE
python dataframe display

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#821]
If from python you output a data frame without wrapping in html the system still detects a table BUT python outputs only a part of the data frame and the last table row contains only dots (....).

**Comment by scottdraves** [comment]
dup? https://github.com/twosigma/beaker-notebook/issues/681

**Comment by ildipo** [comment]
Almost... we should handle the dots better when displaying the table:
they should always appear at the bottom of the table.

**Comment by ildipo** [comment]
this is fixed now since we return the table in JSON format now
