### ISSUE TITLE
[BUG] %%classpath add mvn not working with POM

### ISSUE THREAD

**Issue by ThibTrip** [twosigma/beakerx#8284]
Hello,

I tried the snippet below found in [ClasspathMagicCommands.ipynb](https://github.com/twosigma/beakerx/blob/master/doc/groovy/ClasspathMagicCommands.ipynb
) in Binder and a local installation and it did not work.

# Snippet
In:
```xml
%%classpath add mvn
<dependencies>
 <dependency>
    <groupId>commons-httpclient</groupId>
    <artifactId>commons-httpclient</artifactId>
    <version>3.1</version>
    <exclusions>
        <exclusion>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
        </exclusion>
    </exclusions>
 </dependency>
 <dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.26</version>
 </dependency>
</dependencies>
```
Out:
```
Wrong command format, should be %%classpath add mvn
 group name version [type classifier] or group:name:version[:type:classifier]
 group name version [type classifier] or group:name:version[:type:classifier]
```

# Notes on my use case

I'd like to be able to put the content of my pom.xml and have it loaded via a magic command as I use Jupyter Lab to make Java packages (I know it's not really meant for that but the interactivity is really helpful since I am used to do the same with Python). I basically have cells corresponding to Java classes, pom.xml, etc. plus images for documentation. This works with IJava but I wanted to try beakerx to see what it offers (notably multilanguage notebooks).

**Comment by EfimovVladimir** [comment]
It can be reproduced on beakerx 1.4.0.
On current master it was fixed. @ThibTrip you can try to install master using our [instructions](https://github.com/twosigma/beakerx#build-and-install-linux-and-mac) or wait next release.
