### ISSUE TITLE
IPython won't print output after installation of optional beakerx modules

### ISSUE THREAD

**Issue by shivendra90** [twosigma/beakerx#8306]
Hello,

I installed the latest beakerx with its optional modules such as `tabledisplay`. Before beakerx, on IPython consoles, running simple commands would produce outputs as expected. However after installation of optional modules, I have to add the print() command to return the same output.

For example:
```python
df = pd.read_csv("some_data.csv")
df.describe()
```
Would return descriptive stats without the print function. Now, after installation of beakerx, I have to add `print(df.describe())` to return the same output. Running only `df.describe()` shows a blank line. Is there a setting/dependency preventing this normal behaviour and how can I fix it?

**Comment by ildipo** [comment]
@EfimovVladimir Can you verify this please?

**Comment by shivendra90** [comment]
Please do note that this is after installation of `beakerx_widgets` and `beakerx_tabledisplay` modules.

**Comment by Berezhnyk** [comment]
BeakerX uses a deprecated function. See this: https://github.com/welfare-state-analytics/welfare_state_analytics/issues/51#issuecomment-595743523

**Comment by EfimovVladimir** [comment]
@shivendra90 @Berezhnyk may be you are not correctly installed beakerx 
not reproduced on jupyter notebook
![image](https://user-images.githubusercontent.com/17744188/94829757-88be6180-0413-11eb-91ad-ba9f0248814c.png)

not reproduced on IPython console
![image](https://user-images.githubusercontent.com/17744188/94829901-ac81a780-0413-11eb-9d9f-66f85fc375c3.png)

try to install beakerx on new conda environment with python 3.7.5 and openjdk=11.0.1 like
```
conda create -y --name be1_all python=3.7.5
conda activate be1_all
conda install -y -c conda-forge openjdk=11.0.1
conda install -y -c beakerx beakerx_all
```

**Comment by shivendra90** [comment]
@EfimovVladimir Ok thanks. Could be the missing `open_jdk`.
