### ISSUE TITLE
hangs on "starting IPython" when run directly from the dmg

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#832]
Here's what I did:

1) I have an instance of 1.0 running
2) Downloaded 1.1, double clicked the dmg, the double clicked 'Beaker'
3) Waited for Beaker to open in Chrome and clicked 'new default notebook'

It's hanging on "starting IPython" and the Chrome console produces:

installing keydownHandler controlpanel-directive.js:130
Failed to load resource: the server responded with a status of 500 (Server Error) http://127.0.0.1:8809/22ec655/beaker/rest/plugin-services/getIPythonVersion

**Comment by scottdraves** [comment]
thanks for the bug report.
were you able to run it normally (without leaving 1.0 running, and without running it out of the dmg)?

**Comment by scottdraves** [comment]
i was able to reproduce this by running the app out of the dmg, regardless of an old version already running.

i agree with you that should work but i don't think it's a big problem.  we could/should make a note of it by adding a "starting beaker" section under the download link, like we have for ubuntu and windows.

**Comment by scottdraves** [comment]
fixed in 1.2
