### ISSUE TITLE
Using Beaker.app, I don't know how to reconnect

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#833]
Since that startup stdout isn't shown, I don't know what URL to connect to after I close my browser tab. I think my preferred solution would be for the app to have a tiny UI with a "reconnect" button. I'm pretty sure there's already a GH issue for the UI somewhere. Maybe there's a simpler interim solution if the UI isn't coming for a while.

**Comment by scottdraves** [comment]
The reconnection link is in the "About Beaker" window, which is the only window we have so far.  Agreed that this is too hard to find.  It could be made easier to find by just making a menu item for it, I think that's the best next step.  But yea, eventually there should be a window that has that, and also things like the log, and memory and CPU usage, maybe autoupdate status, and copies of some of the information available in the web app.

**Comment by jchendy** [comment]
Oh cool, I had no idea that was there! Works for me.
