### ISSUE TITLE
Beaker 1.1.1 won't run upon install "Beaker is damaged and can't be opened"

### ISSUE THREAD

**Issue by bradicdesign** [twosigma/beakerx#835]
I tried downloading the latest mac version from the website but when I install it to Applications and try to run it I get a "beaker is damaged and can't be open". It copies to Applications without errors. I also tried running from .dmg as well and get the same error.

![screen shot 2014-11-01 at 12 34 39 pm](https://cloud.githubusercontent.com/assets/6478279/4873034/e8a228ec-61fe-11e4-9c06-8c533c6469bc.png)
![screen shot 2014-11-01 at 12 34 20 pm](https://cloud.githubusercontent.com/assets/6478279/4873035/e8a38e26-61fe-11e4-8b1f-e1cd1a9f037f.png)

**Comment by scottdraves** [comment]
Thanks for the report.
I'll test this again when I get to higher bandwidth.

**Comment by bradicdesign** [comment]
Maybe Yosemite? On another machine that had it before I upgraded to Yosemite it works fine.

**Comment by janovergoor** [comment]
I am experiencing exactly this problem and am on 10.9.5 still

**Comment by bradicdesign** [comment]
Makes sense - the one that works fine is actually 1.0.1

**Comment by scottdraves** [comment]
Jan, do you mean 1.1 worked for you, but 1.1.1 does not?

**Comment by scottdraves** [comment]
Ljubo, there was no 1.0.1.... ??

**Comment by bradicdesign** [comment]
This is the one (no pun intended).

![screen shot 2014-11-01 at 2 45 52 pm](https://cloud.githubusercontent.com/assets/6478279/4873394/93930350-6210-11e4-847d-181ae3ae4e21.png)

**Comment by scottdraves** [comment]
thanks, hhh ok yea that's 1.0.  i am still on the train back to nyc, and i have family responsibilities when i get home.  maybe later tonight but probably tomorrow i can do some testing and see if i can reproduce this.

**Comment by janovergoor** [comment]
Hey, yes 1.1 worked (in the sense that it installed and launched, but then there was the R function bug) but I can't install 1.1.1

**Comment by scottdraves** [comment]
confirmed :(

**Comment by scottdraves** [comment]
i am really baffled, the DMG I made is byte-for-byte identical to the one you get when you download it from AWS.  But the one I still have on my local disk works fine.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook-www/commit/b90f4b4371cb6f9010028e712ea82db889153881

i recompiled and rebuilt the dmg and uploaded and now it works.
i can't explain what went wrong though.

**Comment by janovergoor** [comment]
it works now. Thanks for your active support!
