### ISSUE TITLE
New testing framework

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#837]
We need a testing framework that is easier to write tests than dill, and we don't need that acceptance testing style that dill is good for.  Since Beaker uses Angular, [Protractor](https://github.com/angular/protractor) is the obvious choice.  [People seem to like it](http://testautomation.applitools.com/post/94994807787/protractor-vs-selenium-which-is-easier).  It can be used for performance testing [like this](https://gist.github.com/axemclion/9594795).  It even has a waitForAngular() method that might answer our question about when the notebook render cascade is complete.

**Comment by ildipo** [comment]
delivered to origin/master with two example tests
