### ISSUE TITLE
write performance tests

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#838]
once we have our framework up, the tests we need are:
- starting a big notebook (time until completely rendered, and also longest interval stuck inside JS interpreter)
- starting a notebook with no cells but major evaluators (R, python, groovy) (time until completely rendered)
- run through all the tutorials (repeat and monitor memory usage)
- run through all UI interactions (repeat and monitor memory usage)

**Comment by scottdraves** [comment]
depends on https://github.com/twosigma/beaker-notebook/issues/837

**Comment by scottdraves** [comment]
some good info here on APIs for memory perf:
http://www.html5rocks.com/en/tutorials/memory/effectivemanagement/

**Comment by samccone** [comment]
I am currently working on a tool to do just this, it is a combination of chrome debugger-protocol and selenium-webdriver.

When it is ready it should allow for an objective measure of memory useage, FPS, node count, and time to first paint. :+1:

**Comment by scottdraves** [comment]
great thanks sam.

**Comment by samccone** [comment]
unfortunately this is blocked via
https://code.google.com/p/chromedriver/issues/detail?id=878#makechanges
