### ISSUE TITLE
New Default Notebook hangs

### ISSUE THREAD

**Issue by bradicdesign** [twosigma/beakerx#852]
From Beaker home, I click New Default Notebook.
I slowly makes it trough various plugins and then hangs on iRuby one.

![screen shot 2014-11-07 at 1 31 26 pm](https://cloud.githubusercontent.com/assets/6478279/4960666/a36a6070-66c5-11e4-9e76-8812f0c67d51.png)

Then, if I go back to home and try it again, I get this:

![screen shot 2014-11-07 at 1 33 22 pm](https://cloud.githubusercontent.com/assets/6478279/4960683/d593b524-66c5-11e4-8c88-9ed6c38cfe94.png)

**Comment by bradicdesign** [comment]
And I should add that no buttons on the page work (ok / cancel / close / insert cell).

**Comment by scottdraves** [comment]
had an old default notebook, fixed by rm -rf ~/.beaker
