### ISSUE TITLE
$BEAKERDIR changes

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#868]
$BEAKERDIR as just added https://github.com/twosigma/beaker-notebook/pull/865/files
is good because we need a way to share the classes between languages.
really this should be the default.
but we really don't want to share them between notebooks.
we need a different mechanism here.

**Comment by ildipo** [comment]
By default classes are shared in a session-specific directories. The user can still specify another directory and can still use $BEAKERDIR to put it inside the beaker temporary directory
