### ISSUE TITLE
Revisit IPython keepalive timer issue

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#87]
As Dmitri pointed out in:
https://github.com/twosigma/beaker-notebook/pull/86#discussion-diff-10723247R25

**Comment by melmac48** [comment]
@anglee what's the issue? how does it manifest? thnx

**Comment by anglee** [comment]
@scottdraves, I believe you made those comments. Can you elaborate?

**Comment by scottdraves** [comment]
basically dmitri said we should have an issue to track this comment:
https://github.com/twosigma/beaker-notebook/blob/master/core/nginx/nginx.conf.template#L25
which i wrote.

what's going on: nginx closes connections that are not used after some timeout.
this isn't a feature we want, and i believe the doc says if you set it to 0 then it doesn't happen.
but i tried setting it to 0 and it still closed idle connections.
so i just set it to 1000 and set up a timer in the python code to keep it open:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/ipythonPlugins/src/dist/ipython/ipython.js#L91

i don't think we really need an issue to track this.
it is just one of many many things in the code that are not completely explained.
