### ISSUE TITLE
remove RELEASE_6 hack

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#870]
https://github.com/twosigma/beaker-notebook/blob/771ff3519bfe28df93fd7f917104cac249664346/core/src/main/java/com/twosigma/beaker/core/rest/StreamGobbler.java#L82

org.antlr has the unfortunate property that it has been marked as qualified to run only with java6.
hence we get a runtime warning since we use java 7, and this must be hidden from the users by the StreamGobbler.

when antlr is fixed we should remove the hack.

**Comment by ildipo** [comment]
This has been moved from the StreamGobbler into the std output handler
