### ISSUE TITLE
Cell running status in the wrong place

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#876]
We currently have this:
![current run](https://cloud.githubusercontent.com/assets/6478279/4600685/f12d8820-50d9-11e4-88bb-985e9a191e75.png)

What we should have is this:
![new run](https://cloud.githubusercontent.com/assets/6478279/4600686/129bee2a-50da-11e4-9530-29882b7fe5b8.png)

Run status should move next to run action (by the button)
Run button should turn into Stop button

---

We should also move the final run time up by the Run button.
What we have now: 
![current run time](https://cloud.githubusercontent.com/assets/6478279/4600726/41b48a7c-50db-11e4-8cd8-89485b3fb76f.png)

What we should have:
![new run time](https://cloud.githubusercontent.com/assets/6478279/4600729/6731b504-50db-11e4-98d1-e6d3df11ccef.png)

copied from https://github.com/twosigma/beaker-notebook-www/issues/105

**Comment by thejohnfreeman** [comment]
Be careful changing the run button to stop button. Try to protect the user from accidental double clicks (quickly starting and stopping evaluation with non-transactional but incomplete side effects in between). Maybe disable the stop button for a half second after switching.

**Comment by scottdraves** [comment]
thanks john. we have found some other problems with this UI, not sure it's really on the agenda anymore.  i agree with the additional problem you point out.
