### ISSUE TITLE
Increase cell description font size 

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#877]
Bump up font to 13px for collapsed cell text and initialization text.

![init](https://cloud.githubusercontent.com/assets/6478279/4600635/a5d4c57e-50d8-11e4-9379-ce212a9e2146.png)
![collapsed](https://cloud.githubusercontent.com/assets/6478279/4600634/a5d0bc4a-50d8-11e4-8839-2b6488b9bb24.png)

copied from https://github.com/twosigma/beaker-notebook-www/issues/104

**Comment by hydrosquall** [comment]
It would be convenient to have a "settings" menu where the readability things like font size can be set by the user globally. 13px is too small for presentations. 

Currently as a workaround, I'm working on preparing a beaker notebook for a class presentation, and am editing the `app.css` through my web browser's "inspector" each time the notebook loads. It looks like this would be used by at least 1 other user based on [twitter].(https://twitter.com/beakernotebook/status/593848112462069760)

**Comment by scottdraves** [comment]
I've considered it but sass at runtime is nontrivial.
what's wrong with control plus?
that's what i do.

**Comment by scottdraves** [comment]
btw, we have introduced color themes including dark bkg for next release.

**Comment by hydrosquall** [comment]
Control plus works, it's just seems like a common feature in IDEs to be able to set font-size with a settings menu. But certainly not an essential feature :)

Looking forward to the new color themes !
