### ISSUE TITLE
View menu modification

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#879]
Start page should have home icon.
New checkmark attached.
Divider after start page.
Indentation for icons.

Mock and both icons attached.

![home](https://cloud.githubusercontent.com/assets/6478279/4599636/df29efbc-50c8-11e4-88ce-c9d521ee8d0a.png)
![home 2x](https://cloud.githubusercontent.com/assets/6478279/4599637/df42a976-50c8-11e4-9a3f-b2bf0d90b9a9.png)
![showing](https://cloud.githubusercontent.com/assets/6478279/4599638/df4c4094-50c8-11e4-9bf2-2f345ffb1437.png)
![showing 2x](https://cloud.githubusercontent.com/assets/6478279/4599639/df505f26-50c8-11e4-8807-c9e543883d85.png)
![view menu](https://cloud.githubusercontent.com/assets/6478279/4599645/f7e89666-50c8-11e4-9175-9a9c27497896.png)

**Comment by scottdraves** [comment]
Same for modification should be done for cell language menu as well.
![cell menu](https://cloud.githubusercontent.com/assets/6478279/4600712/eb800d48-50da-11e4-9e63-260c7f01ead1.png)

![cell menu 2](https://cloud.githubusercontent.com/assets/6478279/4600715/fea33990-50da-11e4-81d3-8d54ff8a668e.png)

**Comment by scottdraves** [comment]
copied from https://github.com/twosigma/beaker-notebook-www/issues/100

**Comment by samccone** [comment]
@scottdraves I noticed that you have all the menu items indented, do we want this on all menus that can have checked items?

<img width="438" alt="screen shot 2015-08-17 at 2 07 14 pm" src="https://cloud.githubusercontent.com/assets/883126/9312268/ade996d0-44e9-11e5-85eb-c5433ba2b562.png">
<img width="351" alt="screen shot 2015-08-17 at 2 06 55 pm" src="https://cloud.githubusercontent.com/assets/883126/9312262/a64ec47c-44e9-11e5-87d8-a2784d9b8cd3.png">

**Comment by scottdraves** [comment]
margin should be consistent for all menus so it doesn't have to move when the check mark is there.
basically it should work like mac menus.
