### ISSUE TITLE
line number of javascript errors is not reported

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#889]

**Comment by scottdraves** [comment]
PR#1356 covers syntax errors, still need to handle runtime errors.

**Comment by buob** [comment]
https://github.com/twosigma/beaker-notebook/commit/98a101940d04f21c090469537363ebbb1fcfd0bf This commit actually shows the line and column number of a runtime error

**Comment by scottdraves** [comment]
oh ok great, thanks.
very hard to read though.
https://github.com/twosigma/beaker-notebook/issues/1357
