### ISSUE TITLE
remove the chart output type

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#897]
it has been superceded by plot and combinedplot

**Comment by ildipo** [comment]
done

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/outputdisplay/bko-chart.js

**Comment by scottdraves** [comment]
then we can get rid of flotr2 too: https://github.com/twosigma/beaker-notebook/issues/1717

**Comment by scottdraves** [comment]
fixed by https://github.com/twosigma/beaker-notebook/tree/spot/897
