### ISSUE TITLE
Clicking on python in the language manager in an empty notebook throws errors.

### ISSUE THREAD

**Issue by samccone** [twosigma/beakerx#925]
![](http://dl.dropbox.com/u/36928599/Screenshots/0mm.png)

**Comment by samccone** [comment]
This is predicated by having an invalid ipython install, perhaps the real fix is to throw a descriptive error message.

**Comment by scottdraves** [comment]
yea lack of good error messages from missing backends is an old big problem.
https://github.com/twosigma/beaker-notebook/issues/880

**Comment by samccone** [comment]
:+1:
