### ISSUE TITLE
Cannot share to web

### ISSUE THREAD

**Issue by desilinguist** [twosigma/beakerx#928]
I have finally got Beaker working on OS X and like it quite a bit. I have created some notebooks that I want to share on the web but nothing happens when I click on `File -> Share to Web`.

**Comment by scottdraves** [comment]
Thanks for the bug report Nitin.  If you open the Console app and log at the logs while you try to do the share, do you see errors from Beaker?

**Comment by desilinguist** [comment]
Nope, nothing at all.

**Comment by desilinguist** [comment]
I do see errors like these at start up though:

```
11/25/14 3:33:37.213 PM Beaker[12094]: nginx-stderr>2014/11/25 15:33:37 [error] 12150#0: *52 open() "/Users/nmadnani/.beaker/v1/nginx3520127964673133111/html/restart.445046040329/present.html" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /restart.445046040329/present.html HTTP/1.1", host: "127.0.0.1:8803"
```

**Comment by scottdraves** [comment]
Thanks.  That's a normal part of starting a plugin, despite the "error" on the line.

What about in the Javascript console?  If you are on Chrome, hit command-alt-J.
You are online right?  Behind any kind of proxy?

**Comment by desilinguist** [comment]
I am online, no proxy. 

I am using Safari and the JS console just shows the following logging messages, no errors:

```
[Log] Using ipython 1.x compatibility mode: false (ipython.js, line 359)
[Log] Kernel started:  88d85f9d-bc15-485b-9a8d-cd523e25b4f6 (kernel.js, line 125)
[Log] Starting WebSockets: ws://127.0.0.1:8801/../../b1a7d5f/ipython.405746437525/api/kernels/88d85f9d-bc15-485b-9a8d-cd523e25b4f6 (kernel.js, line 153)
```

**Comment by desilinguist** [comment]
Never mind, it seems to have been an adblocking issue as the pop up was blocked by Safari. Tried on Firefox and it sort of worked. It went to the gist page but showed a 404 error first. Reloading showed the notebook. Thanks!

**Comment by scottdraves** [comment]
great
