### ISSUE TITLE
Allow customization of keyboard shortcuts

### ISSUE THREAD

**Issue by adgnaw** [twosigma/beakerx#930]
This would make transition from other tools, such as IPython notebook, much easier.

**Comment by scottdraves** [comment]
Thanks for the suggestion.  Indeed we'll need something like this eventually.  What keyboard commands were you thinking about in particular?

**Comment by adgnaw** [comment]
I am an IPython user and I found the following keyboard commands very useful:
1. tab completion 
2. inserting cells: in IPython control mode, one can use "b" for inserting a cell below and "a" for inserting a cell above

**Comment by scottdraves** [comment]
thanks.  i can see making completion work on tab in addition to control-space like it does now, especially if the cursor is not at the start of a line (ie only spaces to the left, when it would make more sense for it to auto-indent).

and even though our interface is modeless, if the focus is not on a code cell, you could have keys like a and b for insert.

really, we have just begun to consider keyboard commands in general and i expect we are going to make a lot of improvements in this area, so feedback on how to prioritize them is much appreciated.

**Comment by scottdraves** [comment]
The tab key should never put an actual tab character into the code text.

**Comment by scottdraves** [comment]
tab completion done.  general keyboard commands left to a future release.
