### ISSUE TITLE
If a markdown cell is moved it breaks (firefox)

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#940]
This seems to be firefox specific:
1 create a blank notebook
2 add a  code cell
3 add a markdown cell
4 write something in markdown cell
5 move the markdown cell on top

-> content disappears and the cell is not clickable anymore

**Comment by buob** [comment]
This is what I'm seeing -- it's not necessarily the first cell, it's if it is moved up at all.  For some reason moving it down is fine.

**Comment by buob** [comment]
Disappears if moved up, becomes uneditable if moved down...

**Comment by buob** [comment]
shoot -- https://github.com/twosigma/beaker-notebook/issues/350

**Comment by scottdraves** [comment]
oh yea good find jake :+1:
