### ISSUE TITLE
python cells cannot display latex

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#95]
```
from IPython.core.display import display_latex
display_latex('$$x/y$$', raw=True)
```

does not work.  need to identify this as bkoLatex.  but the real problem is that we do not handle multiple results from python, right now we force them to html.  they should be encapsulated in an OutputContainer.  ie this should work too:

```
from IPython.core.display import display_latex, display_html
display_latex('$$x/y$$', raw=True)
display_html('<b>bold</b>text', raw=True)
```

**Comment by melmac48** [comment]
dup of #85
