### ISSUE TITLE
Stuck in iPython initialization

### ISSUE THREAD

**Issue by balakrishnanc** [twosigma/beakerx#962]
I'm trying to run beaker on a OS X 10.10. I've anaconda installed and from the terminal I can confirm that the python/ipython binaries point to that within the anaconda distribution.

When I launch the default notebook, however, the notebook is stuck in initializing iPython forever.

![Stuck in iPython initialization](https://cloud.githubusercontent.com/assets/1592721/5375984/85baeabc-803e-11e4-9c21-1924e5d48e41.png)

**Comment by scottdraves** [comment]
Thanks for the bug report.  What web browser are you using?  Do you see anything on its JS console?
What if you run the Console application, do you see any log messages from Beaker?

**Comment by scottdraves** [comment]
cannot reproduce

**Comment by omadav** [comment]
Same happened to me. It also happens when trying to use a R cell.

**Comment by scottdraves** [comment]
Hi Omar thanks.  What web browser are you using? Do you see anything on its JS console?
What if you run the Console application, do you see any log messages from Beaker?

**Comment by omadav** [comment]
Hi Scott. Chrome under Win 7. 

"INFO: ERROR reading file C:\Users....beaker\v1\config\beaker.pref.json"

**Comment by scottdraves** [comment]
I think this has been fixed.  Can you try our prerelease of v1.2, linked from the last question in the FAQ http://beakernotebook.com/faq and let us know if that works?

**Comment by decisionstats** [comment]
I am getting this error. on  Ubuntu and Chrome

This is the error in Console

nginx-stderr>2015/12/09 13:44:37 [error] 7585#0: *303 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/ipython.212925280646/login HTTP/1.1", upstream: "http://127.0.0.1:8806/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/12/09 13:44:38 [error] 7585#0: *303 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/ipython.212925280646/login HTTP/1.1", upstream: "http://127.0.0.1:8806/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/12/09 13:44:39 [error] 7585#0: *303 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/ipython.212925280646/login HTTP/1.1", upstream: "http://127.0.0.1:8806/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
nginx-stderr>2015/12/09 13:44:40 [error] 7585#0: *303 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /e55c059/ipython.212925280646/login HTTP/1.1", upstream: "http://127.0.0.1:8806/login", host: "127.0.0.1:8801", referrer: "http://127.0.0.1:8801/beaker/"
