### ISSUE TITLE
language manager overflows window

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#972]
if there are a lot of controls for a language, then they can overflow the manager window.
this is happening with groovy, even for reasonably tall browser windows.
we should introduce a scroll bar into the tabbed section if necessary.
![screen shot 2014-12-15 at 10 19 06 am](https://cloud.githubusercontent.com/assets/963093/5438165/40d254da-8444-11e4-933f-37498e565808.png)

**Comment by buob** [comment]
Fixed in upgrade to bootstrap 3

https://github.com/twosigma/beaker-notebook/pull/1005
