### ISSUE TITLE
cell.output depends on when you access it

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#979]
the cell objects returned by beaker.getCodeCells have a output field, it can either be just a string or an object depending on when you call it.  see the following notebook and check the console

http://sharing.beakernotebook.com/gist/anonymous/9b1961478327b3c1aa24

i get these two lines

```
 look, no semicolon!
Object {selectedType: "Text", elapsedTime: 39, state: Object, result: "look, no semicolon!"}
```

**Comment by scottdraves** [comment]
another datapoint:  with this notebook (http://sharing.beakernotebook.com/gist/anonymous/daa3e25bf5d04c7ec4aa)
results in the following on the console:

```
match?
{"type":"Plot","init_width":640,"init_height":480,...
Object init_height: 480 init_width: 640...
string
object
```

where the "Object" line is the foldout object browser.
so before the evaluation not only do we only get part of the results but it has been stringified :(

**Comment by scottdraves** [comment]
I spoke with Davide about this and the code responsible for removing the object and stringifying is in this case: https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/mainapp.js#L711

there seem to be two problems: in the case when it's not an array, the object-hiding and stringifying is done, but not for a singleton result, this is def a bug.

but also I question if this API should make these simplifications at all.  Yes if the data is later converted to JSON we have to avoid an exception if it contains a DOM element.  So maybe it can be turned into a string later, or there can another API that does that.  It seems to me that our basic API for access to cell results should not be cleaning up or simplifying those results.

**Comment by ildipo** [comment]
The first use case is fixed.
The second use case is fixed.
