### ISSUE TITLE
public-server option not implemented on windows

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#984]
it needs the openssl binary which exists on windows, but is not standard.
or maybe there's a better way that's more native?

https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/java/com/twosigma/beaker/core/module/config/DefaultBeakerConfig.java#L175 is where it is run.

**Comment by altavir** [comment]
Is this problem fixed yet? When I try to launch public server on windows I get:

```
Exception in thread "main" com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.io.IOException: Cannot run program "sh": CreateProcess error=
2, The system cannot find the file specified
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.<init>(DefaultBeakerConfig.java:89
)
  at com.twosigma.beaker.core.module.config.DefaultBeakerConfig.class(DefaultBeakerConfig.java:89)

  while locating com.twosigma.beaker.core.module.config.DefaultBeakerConfig
  while locating com.twosigma.beaker.core.module.config.BeakerConfig
    for parameter 0 at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.<init>(PluginService
LocatorRest.java:73)
  at com.twosigma.beaker.core.module.URLConfigModule.configureServlets(URLConfigModule.java:77)
  while locating com.twosigma.beaker.core.rest.PluginServiceLocatorRest
```

And long uninformative stacktrace after that.

**Comment by altavir** [comment]
And why not to use [JSSE](http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html) which is part of JVM in case native library is not found? I believe that openSSL is better for very high workloads, but still it is better to have some slower client than to have none.
