### ISSUE TITLE
Need more padding before first cell

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#990]
Screenshot below is from v1.1.2. The distance between the menu bar and the first cell doesn't seem to be compliant with Ljubomir's definition of the vertical grid. 

![screen shot 2014-12-31 at 2 05 29 pm](https://cloud.githubusercontent.com/assets/1740497/5589863/3ffc8abc-90f6-11e4-9fad-aeebe5ecaf60.png)

**Comment by scottdraves** [comment]
agreed, thanks for the report
